### ISSUE TITLE
希望DataTable增加一些特性(default-expand-all,default-expanded-keys,受控expanded-keys等)

### ISSUE THREAD

**Issue by qqfei1858** [tusen-ai/naive-ui#1068]
### This function solves the problem (这个功能解决的问题)
解决table树形表格一些操作,目前无法控制展开所有树形table
### Expected API (期望的 API)
default-expand-all,default-expanded-keys,受控expanded-keys
default-select-all,default-selected-keys,受控selected-keys

**Comment by qqfei1858** [comment]
我发现 NDataTable 中有api expandedRowKeys 不知道为啥文档中没有

**Comment by Volankey** [comment]
确实没在文档上

**Comment by qqfei1858** [comment]
@Volankey 用户有时需要点击展开所有树,目前DataTable不知道咋搞?

**Comment by 07akioni** [comment]
> 我发现 NDataTable 中有 expandedRowKeys 不知道为啥文档中没有

估计是忘了

**Comment by 07akioni** [comment]
> @Volankey 用户有时需要点击展开所有树,目前DataTable不知道咋搞?

这个可以研究一下，我也不知道怎么弄比较好

**Comment by rashagu** [comment]
表格的行点击事件有吗？

**Comment by 07akioni** [comment]
> 表格的行点击事件有吗？

rowProps

**Comment by luterc** [comment]
> > @Volankey 用户有时需要点击展开所有树,目前DataTable不知道咋搞?
> 
> 这个可以研究一下，我也不知道怎么弄比较好

我暂时这么干的：
1、树初始化的时候，expanded-keys="allTreeKeys"，把所有树节点 的key 给expanded-keys（不知道为何，default-expand-all这个参数暂时没起效）
2、全部展开的时候，执行 expanded-keys="allTreeKeys"
3、全部收起的时候，执行expanded-keys=[]
4、手动展开某个节点的时候，先expanded-keys=[],然后：expandedKeys = [...keys]，触发界面更新
至少看起来，像那么 回事。。。

**Comment by 07akioni** [comment]
> 我发现 NDataTable 中有 expandedRowKeys 不知道为啥文档中没有

已经加上了

**Comment by fy0** [comment]
> > > @Volankey 用户有时需要点击展开所有树,目前DataTable不知道咋搞?
> > 
> > 
> > 这个可以研究一下，我也不知道怎么弄比较好
> 
> 我暂时这么干的： 1、树初始化的时候，expanded-keys="allTreeKeys"，把所有树节点 的key 给expanded-keys（不知道为何，default-expand-all这个参数暂时没起效） 2、全部展开的时候，执行 expanded-keys="allTreeKeys" 3、全部收起的时候，执行expanded-keys=[] 4、手动展开某个节点的时候，先expanded-keys=[],然后：expandedKeys = [...keys]，触发界面更新 至少看起来，像那么 回事。。。

额，看起来default-expand-all 至今仍无效果，版本2.35.0，然后最新的2.37.3
数据是 onBeforeMount 里面取的

**Comment by fy0** [comment]
另外 expandedRowKeys 有效，但是我的需求中不太需要数据受控，如果是双向绑定倒也可以绕过实现

**Comment by AshleyFang** [comment]
v2.38.2  :default-expand-all="true" 没有作用

**Comment by Lastcall9** [comment]
v24.1.0 default-expand-all 还是无效

**Comment by darknesstm** [comment]
当前这个问题还存在
