### ISSUE TITLE
希望作者能增加一个分割面板  就是可以左右拖动分割线调整左右或者上下的大小

### ISSUE THREAD

**Issue by yq5858588** [tusen-ai/naive-ui#1111]
### TuSimple/naive-ui version (版本)
2.18.0

### Vue version (Vue 版本)
3.2.9

### Browser and its version (浏览器及其版本)
chrome89

### System and its version (系统及其版本)
windows10

### Node version (Node 版本)
14

### Reappearance link (重现链接)
https://github.com/TuSimple/naive-ui

### Reappearance steps (重现步骤)
新的需求哦

### Expected results (期望的结果)
希望作者能实现谢谢

### Actual results (实际的结果)
可以方便后台管理可以复杂布局

**Comment by Volankey** [comment]
应该不会实现，不属于基础组件的范畴

**Comment by jahnli** [comment]
https://github.com/tusen-ai/naive-ui/issues/3557#issuecomment-1685572444
