### ISSUE TITLE
Hope the NRadioGroup NRadioButton can provide a 'Vertical' style, just like the NButtonGroup. 希望单选按钮组可以提供一个垂直的显示风格, 就像普通按钮组一样.

### ISSUE THREAD

**Issue by funwaywang** [tusen-ai/naive-ui#1126]
### This function solves the problem (这个功能解决的问题)
a vertical radio group list, binding to a list and selected value, it behave like a menu but without dropping/popup. 需要一个垂直的单选列表, 我搜了一遍, 目前Naive库里似乎没有类似的组件, NRadioGroup NRadioButton非常接近我想要的效果, 如果能垂直布局的话.. 非常感谢Naive团队的贡献.
### Expected API (期望的 API)
<n-radio-group vertical>
   <n-radio-button .... />
  <n-radio-button .... />
</n-radio-group>

**Comment by funwaywang** [comment]
Expected API (期望的 API)

<n-radio-group vertical> <n-radio-button v-for='....' /> </n-radio-group>

**Comment by 07akioni** [comment]
> Expected API (期望的 API)
> 
> `<n-radio-group vertical> <n-radio-button v-for='....' /> </n-radio-group>`

RadioButton 为了样式的完美使用了一个非常绕的实现，垂直选择这个短期内未必会加上

**Comment by dellenshang** [comment]
`                <n-radio-group>
                    <div>
                      <n-radio></n-radio>
                    </div>
                  </n-radio-group>` radio外面包一层div就行了，非常简单

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
