### ISSUE TITLE
当表格single-line为false时,表格可否增加可伸缩列。

### ISSUE THREAD

**Issue by yanbowe** [tusen-ai/naive-ui#1180]
### This function solves the problem (这个功能解决的问题)
当列设置固定宽度时，用户鼠标移动到列border-right时可自定义修改列的宽度。
### Expected API (期望的 API)
默认开启

**Comment by yanbowe** [comment]
像element-plus表格伸缩列一样

**Comment by 07akioni** [comment]
> 伸缩列

https://element-plus.gitee.io/#/zh-CN/component/table 哪个是伸缩列的 demo

**Comment by yanbowe** [comment]
![image](https://user-images.githubusercontent.com/43030980/133533932-8a479c03-9c2e-4776-87ef-2d4fe989583e.png)
鼠标移动到竖线上可以伸缩列的宽度

**Comment by yiptsangkin** [comment]
https://github.com/yiptsangkin/near-admin-naive/blob/master/src/core/component/NCommonTable.vue

可以先参考这个，结合vue3-draggable-resizable可以实现简单的列宽调整

**Comment by lx11573** [comment]
这个功能会在未来添加吗？ @07akioni

**Comment by equt** [comment]
track in #3165
