### ISSUE TITLE
数据表格总结栏优化

### ISSUE THREAD

**Issue by yanbowe** [tusen-ai/naive-ui#1185]
### This function solves the problem (这个功能解决的问题)
减低合计行心智负担，现在合计行心智负担太重
### Expected API (期望的 API)
summary 不传入方法时，则该列值是数字的时候自动展示合计行，第一列默认显示合计文字，文字可配置

**Comment by yanbowe** [comment]
可参考合计行
[elemnt-plus](https://element-plus.gitee.io/#/zh-CN/component/table)

**Comment by yanbowe** [comment]
补充：当数据量大时候合计行增加固定到表格底部显示
![image](https://user-images.githubusercontent.com/43030980/133552486-9b19db20-0125-4458-b7ee-25e0d95a8825.png)

**Comment by equt** [comment]
track in #2814
