### ISSUE TITLE
Add Horizontal Virtual Scroll Support to `<NDataTable />` - 表格横向虚拟滚动

### ISSUE THREAD

**Issue by Dzorogh** [tusen-ai/naive-ui#1340]
### This function solves the problem (这个功能解决的问题)
Performance of big tables in both directions, ability to build something like spreadsheets. PrimeVue has some kind of this functionality, but not in DataTable.
### Expected API (期望的 API)
```
<n-data-table
  :columns="columns"
  :data="data"
  virtual-scroll="horizontal | vertical | both"
/>
```

**Comment by Asgen** [comment]
+1

**Comment by vitjaz** [comment]
+1

**Comment by lvjinze** [comment]
+1

**Comment by jahnli** [comment]
As far as I know, the author is already in the planning, please look forward to the follow-up

**Comment by ValentinDankovtsev** [comment]
+1. I have the same problem with a large number of columns in a table
