### ISSUE TITLE
Allow to specify custom class name for DataTable cell

### ISSUE THREAD

**Issue by apaulau** [tusen-ai/naive-ui#1357]
### This function solves the problem (这个功能解决的问题)
At the moment style customization of the DataTable is limited to either column or row level. With the proposed feature, it would be possible to style specific cells based on the user's criteria.
### Expected API (期望的 API)
I think it should be similar to the `row-class-name` for consistency: `cell-class-name`:  `string | (cellData: any) => string | object`

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem


This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
