### ISSUE TITLE
Allow to select only one value in Range Date Picker

### ISSUE THREAD

**Issue by stulnikov-roud** [tusen-ai/naive-ui#1368]
### This function solves the problem (这个功能解决的问题)
Sometimes in applications it is required to have possibility to select only "from" or "to" value. And this feature should be enabled by default without extra property.
### Expected API (期望的 API)
No change in API.

**Comment by 07akioni** [comment]
We will eventually implement this but not very soon.

**Comment by equt** [comment]
@07akioni, is this somehow related to https://github.com/tusen-ai/naive-ui/issues/1178? Maybe we should close this and track it in that one.
