### ISSUE TITLE
Allow to change component state by media query （中文描述：通过媒体查询改变组件状态）

### ISSUE THREAD

**Issue by N-index** [tusen-ai/naive-ui#1396]
### This function solves the problem (这个功能解决的问题)
A common use case: On desktop, we set the mode of 'n-menu' to 'horizontal', and when the media query detects that the current page is on mobile, we need to change the mode to 'vertical' to fit the layout. After adding this feature, we can update the component state via media query.  （中文描述：一个常见的用例：在桌面端，我们设置 'n-menu' 的 mode 为  'horizontal'，而通过媒体查询检测到当前页面处于移动端时，我们需要将 mode 修改 为 'vertical' 以适应布局。添加这个功能后，我们能以媒体查询的方式更新组件状态。）
### Expected API (期望的 API)
This API allows to set the media query details for a component. （中文描述：通过此 API 可以设置组件的媒体查询细节）

**Comment by 07akioni** [comment]
https://www.npmjs.com/package/react-responsive

![image](https://user-images.githubusercontent.com/18677354/139592575-0fccf201-9851-4324-a9a8-94b0d34935dd.png)

这个库思路感觉挺好，值得学习一下

**Comment by equt** [comment]
As it's already 2022, I would recommend to use the [VueUse](https://vueuse.org), they have components like [`UseWindowSize `](https://vueuse.org/core/usewindowsize/#component-usage) and [`UseDark`](https://vueuse.org/core/usedark/#component-usage).

考虑到已经 2022 年了，可以使用上面两个 VueUse 提供的组件

c.c. @07akioni 提议 close as not planned
