### ISSUE TITLE
tabs  enhancements - Add position and type props

### ISSUE THREAD

**Issue by jahnli** [tusen-ai/naive-ui#1466]
### This function solves the problem (这个功能解决的问题)
Improve functions and enhance user experience
### Expected API (期望的 API)
1.Customize the location of the label bar
2.Set the style of the label

**Comment by 07akioni** [comment]
> 位置这个属性，element做的很好，值得借鉴；实际应用过程中还算常见的。
> 
> ![image](https://user-images.githubusercontent.com/5443355/139356053-4c464027-e25e-4605-95ec-2e2f7a41ec25.png)

常见是常见，不过我觉得这是错误的设计。

不过鉴于它太常见了，所以还是会考虑提供的，只是优先级不是很高。

**Comment by GreatAuk** [comment]
+1

**Comment by AnsGoo** [comment]
+1 可否提升这个需求的优先级

**Comment by Amine27** [comment]
Please, consider adding this feature.

**Comment by HyattXt** [comment]
我也只能单独加个element了
