### ISSUE TITLE
Add Transition Animation for Table Expanded Content - 表格展开内容动画

### ISSUE THREAD

**Issue by jahnli** [tusen-ai/naive-ui#1487]
### This function solves the problem (这个功能解决的问题)
Support for drag and drop sorting and animation enhancement
### Expected API (期望的 API)
1.Supports table drag and drop sorting
2.Added transition animation for table expansion and collapse

**Comment by equt** [comment]
track the row d&d in #2273

**Comment by 07akioni** [comment]
We won't implement expand transition. It would be too complex.
