### ISSUE TITLE
Add Secondary Header Slot to `<NCard />`

### ISSUE THREAD

**Issue by radudiaconu0** [tusen-ai/naive-ui#1550]
### This function solves the problem (这个功能解决的问题)
The card component can be more customizable
### Expected API (期望的 API)
Something like the vuetify approach https://vuetifyjs.com/en/components/cards/

**Comment by 07akioni** [comment]
Can you specify which effect is needed? After seeing the page I can't figure out which is important.

**Comment by radudiaconu0** [comment]
actually i would want just a subtitle component for the card and maybe some header like where you display how much times passed  or something like that

**Comment by jahnli** [comment]
Closed due to inactivity. Feel free to reopen if you're still having trouble.
