### ISSUE TITLE
Expose `<NScrollbar />` Options to `<NDataTable />`

### ISSUE THREAD

**Issue by liuzw2579** [tusen-ai/naive-ui#1573]
### This function solves the problem (这个功能解决的问题)
in data-table component, scrollbar always auto hidden, maybe provide a scrollbar hidden prop in scrollbar component and config provider component ?
### Expected API (期望的 API)
scrollbar auto-hide: boolean | number
config provider: scrollbarAutoHide: : boolean | number

**Comment by Talljack** [comment]
The scroll bar will only appear when the amount of data exceeds the width of the table.
You want to hide scrollbar?

**Comment by liuzw2579** [comment]
> The scroll bar will only appear when the amount of data exceeds the width of the table. You want to hide scrollbar?

no no, let scrollbar can set auto hide timeout( 0 or false -> don't auto hide)

**Comment by 07akioni** [comment]
I don't think it's that neccessary.

If you need it, create a PR and implement it. Maybe call it `always-show` prop.

**Comment by liuzw2579** [comment]
> I don't think it's that neccessary.
> 
> If you need it, create a PR and implement it. Maybe call it `always-show` prop.


我注意到 scrollbar组件有了 trigger: none 让滚动条可以一直显示，但是如何在 data-table 组件中支持它呢？记得之前在触屏设备上使用手指横向滚动 data-table 时 滚动条不会展示出来。
是否可以考虑提供一个 scrollbar provider 组件 支持后代 scrollbar 组件设置 默认 trigger 为 none ？

**Comment by 07akioni** [comment]
> 有了 trigger: none 让滚动条可以一直显示，但是如何在 data-table 组件中支持它呢？记得之前在触屏设备上使用手指横向滚动 data-table 时 滚动条不会展示出来。
> 是否可以考虑提供一个 s

可能会考虑允许全局配置，但是优先级不会很高，有需求欢迎 PR
