### ISSUE TITLE
Support for calling spin as a service or directive

### ISSUE THREAD

**Issue by jahnli** [tusen-ai/naive-ui#1598]
### This function solves the problem (这个功能解决的问题)
Support for calling spin as a service or directive
### Expected API (期望的 API)
Support for calling spin as a service or directive
![image](https://user-images.githubusercontent.com/20943608/142005025-f06ca8c1-93db-4aa2-bcfc-16c381e3ed8e.png)

**Comment by 07akioni** [comment]
API format need to be considered. I don't like service or directive api.

**Comment by liuzw2579** [comment]
> API format need to be considered. I don't like service or directive api, they lose context of the app.

使用类似 useDialog() 的方式呢？ 
```js
setup() {
  const spin = useSpin()
  async onXxx() {
    spin.start()
    try {
      await doXxx()
    } finally {
      spin.stop()
    }
  }
}
````

**Comment by liuzw2579** [comment]
也许局部指令的也行：
```js
setup() {
  const { vSpin } = useSin({ /* ...options */ })
  const isLoading = ref(false)
  return {
     vSpin,
     isLoading 
  }
}
```
在模板中：
```html
<div v-spin="isLoading">内容</div>
```

**Comment by 07akioni** [comment]
Provider 肯定是可以的，只不过就是说，这种方式最多支持全局的，没办法再处理成局部的给用户用了
