### ISSUE TITLE
Supports the stroke-width and rotate properties for global configuration spin  

### ISSUE THREAD

**Issue by muchenfine** [tusen-ai/naive-ui#1627]
### This function solves the problem (这个功能解决的问题)
Supports the stroke-width and rotate properties for global configuration spin  
### Expected API (期望的 API)
Supports the stroke-width and rotate properties for global configuration spin

**Comment by 07akioni** [comment]
That would be a good idea, since in different sizes spin has different proper stroke. If you must do it,  specify the props for every spin.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
