### ISSUE TITLE
When the page stays on for too long, the spin load freezes, causing the lower right corner to be mutilated  

### ISSUE THREAD

**Issue by jahnli** [tusen-ai/naive-ui#1730]
### TuSimple/naive-ui version (版本)
2.21.3

### Vue version (Vue 版本)
3.2.23

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
windows

### Reappearance link (重现链接)
https://codesandbox.io/s/ijvg3

![xzQ0M6tAQY](https://user-images.githubusercontent.com/20943608/144528836-3fb925e8-1e0c-4ec5-8d69-9024b404c8b6.gif)
### Reappearance steps (重现步骤)
When the page stays on for too long, the spin load freezes, causing the lower right corner to be mutilated  

### Expected results (期望的结果)
Normal loading  

### Actual results (实际的结果)
When the page stays on for too long, the spin load freezes, causing the lower right corner to be mutilated

**Comment by 07akioni** [comment]
What does lower right corner mean? I can't understand the issue.

**Comment by 07akioni** [comment]
Do you mean you want to interact with content below the spin during spin is active?

**Comment by jahnli** [comment]
@07akioni  No, I mean the rotation icon is missing in the lower right corner, and the rotation is stuck

**Comment by jahnli** [comment]
Pay close attention to the spin icon

**Comment by 07akioni** [comment]
> Pay close attention to the spin icon

我还是没怎么搞明白，复现的链接也看不太出来，是说右下角有啥问题？

**Comment by jahnli** [comment]
旋转的时候，右下角是缺失的，还有些卡顿

**Comment by 07akioni** [comment]
> 旋转的时候，右下角是缺失的，还有些卡顿

有啥触发条件吗，我感觉我手头的设备很难研究出这个来

一个比较关键的点在于 svg 这个玩意写出来的时候都是理论上严丝合缝的，但是浏览器画出来的时候就会出一些奇怪的问题

**Comment by jahnli** [comment]
> > 旋转的时候，右下角是缺失的，还有些卡顿
> 
> 有啥触发条件吗，我感觉我手头的设备很难研究出这个来
> 
> 一个比较关键的点在于 svg 这个玩意写出来的时候都是理论上严丝合缝的，但是浏览器画出来的时候就会出一些奇怪的问题
> 
> 一个典型的例子就是 spin 的老实现我检查过所有的参数都没问题，但是由于 rotate 和 stroke-array 的变化是分开的，chrome 就会在那稀里糊涂的闪
> 
> 估摸着如果要一个比较完美的方案就要搞个导出的动画播放，类似 lottie？

我也不确定他是在什么特定情况下复现，但我已经遇到三次了。
或者长时间挂着页面会这样，我关闭标签后重新打开，动画就是OK的。我不确定是不是这个原因。

**Comment by 07akioni** [comment]
> > > 旋转的时候，右下角是缺失的，还有些卡顿
> > 
> > 
> > 有啥触发条件吗，我感觉我手头的设备很难研究出这个来
> > 一个比较关键的点在于 svg 这个玩意写出来的时候都是理论上严丝合缝的，但是浏览器画出来的时候就会出一些奇怪的问题
> > 一个典型的例子就是 spin 的老实现我检查过所有的参数都没问题，但是由于 rotate 和 stroke-array 的变化是分开的，chrome 就会在那稀里糊涂的闪
> > 估摸着如果要一个比较完美的方案就要搞个导出的动画播放，类似 lottie？
> 
> 我也不确定他是在什么特定情况下复现，但我已经遇到三次了。 或者长时间挂着页面会这样，我关闭标签后重新打开，动画就是OK的。我不确定是不是这个原因。

我怀疑有可能是时间长了两个定时器会错开，这个先开着吧，不知道有没有什么足够好的 loading 方案

**Comment by jahnli** [comment]
> > > > 旋转的时候，右下角是那个谁，还卡顿
> > > 
> > > 
> > > 有啥触发条件吗，我觉得我手头的设备怪出这个来了
> > > 一个比较关键的点在于这个玩意写出来的时候什么时候严丝合缝的，但是浏览器画出来的时候就会出现一些奇怪的的问题
> > > 一个典型的例子自旋的老实现我检查过所有的问题，因为旋转和笔划阵列是不同的，铬是不是稀里糊涂的闪
> > > 瞎想摸着如果要一个比较完美的团体方案搞个出没的动画，类似抽奖？
> > 
> > 
> > 我也确实他是在什么特定情况下复现，但我已经关闭了三次就是这样。 。
> 
> 我怀疑有可能是时间长了两个定时器会错开，这个先开着吧，不知道有没有什么好的加载方案

是否可以参考element  antd 的实现方式
