### ISSUE TITLE
'Select all' checkbox callback

### ISSUE THREAD

**Issue by AlexZCP** [tusen-ai/naive-ui#1776]
### This function solves the problem (这个功能解决的问题)
Hi!
I cant find callback that represent click on checkbox "Select all" in header of table?

How can I change behavior of that event, I want to involve 'reverse selecting'.
### Expected API (期望的 API)
Prorpose to involve 'on-select-all' callback to change behavior of checkbox.

**Comment by Talljack** [comment]
https://www.naiveui.com/zh-CN/os-theme/components/data-table#select
You can look at the on-update:checked-row-keys event of this demo, you can get the selected keys.

**Comment by Talljack** [comment]
Closed first, if you still have questions, I will reopen.

**Comment by AlexZCP** [comment]
Sorry for so long pause.
But the problem is  that mentioned callback run always:
 - when you press 'Select all'
 - when you press any checkbox.
 But i need to catch only 'Select all' - cause I need to reverse currently selected checkboxes

**Comment by 07akioni** [comment]
You want to reverse the current page selection? Why it's important?

I think it should be done in a dropdown menu like [this](https://www.naiveui.com/en-US/os-theme/components/data-table#custom-select). We can add more selection type.

**Comment by AlexZCP** [comment]
Thanks you guys, I solve this by setting event on "thead .cp-checkbox-box__border"

But now one more question: do we have option to select how "Select All" box should behave with pagination:
 - select all on current page;
 - select all on all pages.

**Comment by AlexZCP** [comment]
> You want to reverse the current page selection?
> 
> I think it should be done in a dropdown menu like [this](https://www.naiveui.com/en-US/os-theme/components/data-table#custom-select) not in header checkbox. We can add more selection type.

Thank you.
In Selection callback we have Pagedata, which represent data on current page.
How can I get this out of that callback?

**Comment by 07akioni** [comment]
> ow can I get this out of that ca

Currently click on checkbox won't emit corresponding row data.

**Comment by 07akioni** [comment]
We may consider add row data for onUpdateCheckKeys callback. However the behavior of header checkbox won't be changed.

**Comment by AlexZCP** [comment]
Thank you, I accessed pageData via ref="table" on **data-table** component.
In this case if you need access pagedata anywhere:
`table.value.paginatedData`

So I created reverse selecting like this:
`  let checkedArray: never[] = []
  if (table) {
    table.value.paginatedData.map((item: { key: never }) => !currentCheckedRowKeys.value.includes(item.key) && checkedArray.push(item.key))
  }
  currentCheckedRowKeys.value = checkedArray
`

**Comment by equt** [comment]
Closed as implemented in 0a7181a87f401b2b57f579bc98bc3aaeab1f9e49.
