### ISSUE TITLE
希望数据表格增加索引列和增加表头对齐方式属性

### ISSUE THREAD

**Issue by jsdjiazhiheng** [tusen-ai/naive-ui#1849]
### This function solves the problem (这个功能解决的问题)
1、索引列可以让表格数据的顺序看的更加清楚
2、表头对齐方式属性可以设置表头的对齐，特别是在表头合并时，更加需要
3、增加表格的border，目前只能对行之间有border，在某些表格中，列和行都需要border
### Expected API (期望的 API)
索引列增加列类型为rownidex或者index
表头对齐方式增加属性header-align

**Comment by 07akioni** [comment]
1. 表头对齐应该会近期加一下
2. rowIndex 现在可以通过 render 实现，这个我们应该会加的比较谨慎，因为还有树形数据的情况，这块需要尤其谨慎，加有加的问题，不加有不加的问题
3. singlerow: false 应该可以满足你的需求

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
