### ISSUE TITLE
NDataTable should have an option for horizontal floating scrollbar.

### ISSUE THREAD

**Issue by findridoy** [tusen-ai/naive-ui#2036]
### This function solves the problem (这个功能解决的问题)
When there are many columns in Data table and table height is fixed to (say for example) 600px, I need to always go to down to find the horizontal scrollbar to see content to the right.

So, if there are a floating scroll bar, I can see the right content without need to go down. 
### Expected API (期望的 API)
<NDataTable
    ****
    : horizontal-floating-scroll="true"
    ****
/>

**Comment by equt** [comment]
track in https://github.com/tusen-ai/naive-ui/issues/1573
