### ISSUE TITLE
add CascaderPanel

### ISSUE THREAD

**Issue by iota9star** [tusen-ai/naive-ui#2047]
### This function solves the problem (这个功能解决的问题)
custom display
### Expected API (期望的 API)
like https://element.eleme.cn/#/zh-CN/component/cascader

**Comment by Talljack** [comment]
what do you mean? add cascader panel?

**Comment by iota9star** [comment]
only cascader panel, no input and popup.

![image](https://user-images.githubusercontent.com/21272154/147537733-ab67797d-ae24-4e41-a4c6-cf37c4dab71c.png)

**Comment by Talljack** [comment]
> only cascader panel, no input and popup.
> 
> ![image](https://user-images.githubusercontent.com/21272154/147537733-ab67797d-ae24-4e41-a4c6-cf37c4dab71c.png)

ok，i got you

**Comment by 07akioni** [comment]
It would be complex.

**Comment by iota9star** [comment]
i dont know why, maybe there are `CascaderPanel `  before `Cascader`

**Comment by 07akioni** [comment]
We may have a try later.

**Comment by 07akioni** [comment]
Not recently.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
