### ISSUE TITLE
Suggestion for improving the dialog component

### ISSUE THREAD

**Issue by cefiro** [tusen-ai/naive-ui#2062]
### This function solves the problem (这个功能解决的问题)
Usability of the dialog box
### Expected API (期望的 API)
1. [Very necessary] Blocking the "Negative button" when the loading property = true or give access to button properties;

2. [Very necessary] Adding a dialog closing event to the "ESC" key;

3. Make "useDialog" promisable for comfortable work with asynchronous functions. 

Example:
```
async test() {
    await useDialog().success(...);
    // resolve: click on a positive button
}
```

**Comment by 07akioni** [comment]
I'll think of it.

**Comment by 07akioni** [comment]
1. consideration needed
2. should doo
3. consideration needed

**Comment by cefiro** [comment]
Thanks :)

**Comment by Talljack** [comment]
> 1. consideration needed
> 2. should do
> 3. consideration needed

2是不是已经做了？

**Comment by 07akioni** [comment]
> > 1. consideration needed
> > 2. should do
> > 3. consideration needed
> 
> 2是不是已经做了？

We haven't finished 2. If esc is pressed, no callback will be fired. You may mean close (clicked) event.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
