### ISSUE TITLE
`Data Table` header `Affix`

### ISSUE THREAD

**Issue by Air-Cooled** [tusen-ai/naive-ui#2079]
### This function solves the problem (这个功能解决的问题)
When have too many rows and do not use paging,  I don't want the header to be invisible because of scrolling
Of course the bottom Pagination bar sometimes needs to be `Affix`
### Expected API (期望的 API)
Like：https://demo15.zentao.net/project-bug-15-0-status,id_desc-0-all-0-12-20-1.html
![Floating head](https://user-images.githubusercontent.com/55440364/147730359-3865af9f-be13-45ba-95c8-7ce943b26d87.gif)

**Comment by equt** [comment]
track in #1555
