### ISSUE TITLE
Granular Control over `<NLoadingBar />`

### ISSUE THREAD

**Issue by jaulz** [tusen-ai/naive-ui#2103]
### This function solves the problem (这个功能解决的问题)
It would be great if the `LoadingBar` would be more "exciting". Currently, it feels very static and if you compare it to `nprogress`(https://ricostacruz.com/nprogress/) for example it looks more dynamic. Also, at the same time it would be great to have an API to set the percentage of the `Loading Bar` which is sometimes handy in an upload scenario.
### Expected API (期望的 API)
Expose `set` function in `loadingBar`.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
