### ISSUE TITLE
VirtualList itemSize property via root component property

### ISSUE THREAD

**Issue by luxliber** [tusen-ai/naive-ui#2119]
### This function solves the problem (这个功能解决的问题)
Now itemSize property of VirtualList hardcoded inside all component where it used. For example:

In Tree component: const ITEM_SIZE = 30 // 24   3   3
in DataTable component (Body part): <VirtualList itemSize={28} ...

Rows may have various styling with less heights and in this case VirtualList calculates items count wrong with standard hardcoded item sizes
### Expected API (期望的 API)
Would be very helpful if all components with virtual list feature (Tree, DataTable etc) could have itemSize property for setting.

**Comment by 07akioni** [comment]
In fact you can find there's no problem make item height different. Since itemSize in VirtualList actually means min item height.

![image](https://user-images.githubusercontent.com/18677354/148226662-231ba5a0-1ba9-40da-8c54-a6730ba9b44f.png)

We would make code more clean later by using theme variable. However there won't be issues if you make item height larger than specified.

**Comment by 07akioni** [comment]
I'll consider expose more API later.

**Comment by luxliber** [comment]
yes, itemSize is min height, so if my row actual height less then hardcoded min height, virtualList calculates and shows less items then needed.
for example hardcoded itemSize for Tree component is 30px but actual row height in my case i 17px (30px is big for me) and VirtualList calculates row count incorrectly (rows must be more for actual tree height)
![image](https://user-images.githubusercontent.com/9447605/148235378-bccc4c81-b702-48c2-94a4-06c496892de3.png)

**Comment by 07akioni** [comment]
> yes, itemSize is min height, so if my row actual height less then hardcoded min height, virtualList calculates and shows less items then needed. for example hardcoded itemSize for Tree component is 30px but actual row height in my case is 17px (30px is big for me) and VirtualList calculates row count incorrectly (there must be more rows for actual tree height) ![image](https://user-images.githubusercontent.com/9447605/148235378-bccc4c81-b702-48c2-94a4-06c496892de3.png)

I see. So how about using height from theme variable by default? Have you edited theme overrides?

**Comment by luxliber** [comment]
Yes, it will be good option. Thanks!

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
