### ISSUE TITLE
n-image-group 图片没办法设置大小，图片预览大图发现变形

### ISSUE THREAD

**Issue by louisqing** [tusen-ai/naive-ui#2166]
### TuSimple/naive-ui version (版本)
2.23.2

### Vue version (Vue 版本)
3.2.16

### Browser and its version (浏览器及其版本)
版本 97.0.4692.71（正式版本） （64 位）

### System and its version (系统及其版本)
win10

### Node version (Node 版本)
14

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/image

### Reappearance steps (重现步骤)
n-image-group 图片没办法设置大小，图片预览大图发现变形

### Expected results (期望的结果)
修复图片预览问题

### Actual results (实际的结果)
修复图片预览问题

**Comment by 07akioni** [comment]
![image](https://user-images.githubusercontent.com/18677354/149663566-7f0f6000-1e7b-452b-b0d6-db64e2c47458.png)

我用了一张非常大的图，没有看出来变形在哪里，需要一个明确的复现

**Comment by 07akioni** [comment]
https://upload.wikimedia.org/wikipedia/commons/2/2b/NYC_Downtown_Manhattan_Skyline_seen_from_Paulus_Hook_2019-12-20_IMG_7347_FRD_%28cropped%29.jpg

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
