### ISSUE TITLE
Customizable Mask for Modal, Dialog, Drawer

### ISSUE THREAD

**Issue by AlexZCP** [tusen-ai/naive-ui#2261]
### This function solves the problem (这个功能解决的问题)
We have a lot of component in Naive , that allow us to create some popup or modal window with content:
Modal, Dialog, Drawer.
But how can I create popup or modal content with my custom content without mask.

Im creating popup for some actions list and at the same moment main content should be accessible.
If there is already an option for some of above components, please point me.

Thanks
### Expected API (期望的 API)
modal component:
showMask: boolean

**Comment by Talljack** [comment]
will do

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
