### ISSUE TITLE
css style标签插入问题

### ISSUE THREAD

**Issue by duyuntaoGG** [tusen-ai/naive-ui#2371]
### This function solves the problem (这个功能解决的问题)
我在使用第三方的微前端架构，例如qiankun，我发现naiveui的样式表是动态插入的，文档提供了解决样式插入位置的方案，但是无法满足我的需求，qiankun在加载应用时去掉了head标签，<meta name="naive-ui-style">没有生效，我编写的样式被naiveUI的样式覆盖。我想在样式插入完成后动态改变顺序，但是我无法获得样式表全部插入完成事件，我希望样式表在全部插入完成后可以有对应方法触发，或者样式表（DOM元素）插入的生命周期函数，将样式表位置完全交于用户定义。
### Expected API (期望的 API)
cssTagMount(styles){}

**Comment by 07akioni** [comment]
如果去掉了 head 标签，预期是插在哪里呢？

**Comment by duyuntaoGG** [comment]
> 如果去掉了 head 标签，预期是插在哪里呢？

naive是面向大众主流的，不需要考虑去掉head标签的情况，毕竟这是非常少见的场景。我的设想是naive生成style DOM，如果用户提供了函数，那么DOM的插入操作由用户接管，向用户提供DOM就可以了。或者说在现有功能和逻辑不变的情况下，提供样式表全部插入完成的回调就也可以。

**Comment by 07akioni** [comment]
> > 如果去掉了 head 标签，预期是插在哪里呢？
> 
> naive是面向大众主流的，不需要考虑去掉head标签的情况，毕竟这是非常少见的场景。我的设想是naive生成style DOM，如果用户提供了函数，那么DOM的插入操作由用户接管，向用户提供DOM就可以了。或者说在现有功能和逻辑不变的情况下，提供样式表全部插入完成的回调就也可以。

我考虑一下吧，现在的问题是假设我搞出了一个 style 标签，你确认有地方能插？

还有卸载和重新挂载的问题，会出问题么？

因为未来可能还有人有 shadow dom 的需求，不我不是很确定这种 hook 可以满足。

**Comment by duyuntaoGG** [comment]
> > > 如果去掉了头标签，可能是插在哪里呢？
> > 
> > 
> > 天真是提供非常幼稚的日常使用风格的，而不是像我这样向用户展示的场景，考虑用户是天真生成的，如果，如果用户占用，那么的插件操作是由用户接管的。或者说在现有和不同的情况下，提供样式表全部实现的目标也可以。
> 
> 我考虑一下吧，现在的标签是假设我提出了一种风格，你确认有地方可以吗？
> 
> 卸载和重新挂载的问题，会出问题还有么？
> 
> 因为未来可能人有shadow dom的需求，不是我很确定还有这个钩子可以满足。


 我基本确定这个hook无法满足所有情况，或者说这个hook的提供的功能非常有限。

 我提议的api只是为抛砖引玉，我想要naive提供的是用户有高自由度自定义style position的能力
 
 所以以此为目标的前提下，naive可能需要暴露一系列的api以满足不同的场景，这可能是个复杂的工作

但是我无法提供更多的解决方案，很抱歉。naive的大牛们加油吧

**Comment by phcent** [comment]
@07akioni 大佬在QQ浏览器下报错，导致style无法渲染 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.  具体可以看看naiveui.com 在QQ浏览器的复现 目前在nuxt中使用时样式不显示或导致nuxt中部分功能失效

**Comment by 07akioni** [comment]
> webkitStorageInfo

这个看起来不像是 naive 引入的，你搜一下自己 APP 的打包？naive 的源码没有出现过这个玩意

**Comment by 07akioni** [comment]
> @07akioni naiveui.com在QQ浏览器(10.8.4559.400版本)打开一片空白window.webkitStorageInfo是唯一的报错，且我在nuxt中使用naiveui在QQ浏览器中依然存在问题，国内使用QQ浏览器的用户也不少，能否检查一下是什么带来的异常吗？其他浏览器中都是正常工作的，为了排除是naiveui带来的异常，特意安装了elmentplus进行测试 没有发现异常，由此可见是由于naiveui中存在异常哦

希望能给点错误调用栈的信息，还有 qq 浏览器对应的浏览器内核版本的信息，我没有 windows 电脑，用不了 qq 浏览器

**Comment by phcent** [comment]
@07akioni 除了这个'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.  啥都没有，当然问题可能不是这个 但是没有更多提示 建议找台windows电脑测试一下 毕竟这个你专业一点

**Comment by 0undefined0** [comment]
> 确实有个shadow dom的需求，我想搞个chrome插件，然后在页面插入一个shadown dom，但是样式被隔离了跑到外面去了，这是我插件的入口代码：
> 
> ```js
> const container = document.createElement('div')
> const root = document.createElement('div')
> const shadowDOM =
>   container.attachShadow?.({ mode: __DEV__ ? 'open' : 'closed' }) || container
> shadowDOM.appendChild(root)
> document.body.appendChild(container)
> const app = createApp(App)
> app.mount(root)
> ```
> 
> 大佬有什么好的建议吗，能用来做chrome插件 @07akioni

解决了吗👬🏻，我也有这个诉求

**Comment by Xdy1579883916** [comment]
臣附议，我觉得可以use的时候设置一个类似appRoot的字段，用来支持自定义HTMLElement 或者 ShadowRoot，默认即 document.body，所有之前默认挂在到body的如popover modal中的to属性直接指向appRoot。

样式也差不多是这个样子，默认是document.header
当然这是我的看法，不一定是个好方案，我们可以讨论讨论

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
