### ISSUE TITLE
Select, Cascader多选, 鼠标放到  某个数字上, 增加tooltip效果, 

### ISSUE THREAD

**Issue by a15218378694** [tusen-ai/naive-ui#2381]
### This function solves the problem (这个功能解决的问题)
现在是, 下拉框出现, 就没有这个效果了, 希望一直有这个效果, 而且只选一个的时候, 没有 号, 这个时候放到单个选中项上面, 如果超出隐藏了, 希望也有tooltip效果, 非常感谢你们
### Expected API (期望的 API)
Select, Cascader

**Comment by 07akioni** [comment]
不想一直给这个效果，两个弹窗一起弹我觉得不好

**Comment by 07akioni** [comment]
从内部实现上来看还要处理一大堆乱七八糟的问题

**Comment by 07akioni** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/29919045/153736479-058cbdad-ccee-4318-b45d-3d57004b0794.png) 鼠标放到框框中, 希望可以看到省略的内容, 这就是只选中一个的情况下

这个可以考虑一下

**Comment by 07akioni** [comment]
但是上面搞了下面不搞也不合适，整体来看就是个有点麻烦的事了= =

**Comment by a15218378694** [comment]
> 但是上面搞了下面不搞也不合适，整体来看就是个有点麻烦的事了= =

麻烦了, 非常感谢

**Comment by fxjs** [comment]
> 

同样需求，这里特别是输入框里有省略，下面选项里也是显示省略，这样最后一级就看不全了。如果只对有省略的选项给个默认的title提示， 体验也会很好，希望官方能考虑下这个提议，谢谢。
![image](https://user-images.githubusercontent.com/3682415/218387694-3ab5c9ef-5dd1-4591-be25-59e39ae09d6e.png)
