### ISSUE TITLE
能否开发一个Split组件？

### ISSUE THREAD

**Issue by mollerzhu** [tusen-ai/naive-ui#2394]
### This function solves the problem (这个功能解决的问题)
有些应用上，会使用到面板分割组件
### Expected API (期望的 API)
类似Arco Design Vue中的Split，但是它实现的效果不够精致，并且有一定的BUG。比如参考VSCode的面板间分割移动的效果。
最好能实现Max和Min的百分比及px限制。同时支持hover样式的快捷自定义。

有空我也可以参与进这个组件的开发。

**Comment by Sepush** [comment]
有团队成员在做 不过上的时间不定 优先级比较低
ref #1111

**Comment by nooooooom** [comment]
有一些想法

首先是基于 draggable 的方式来实现一个 hook 用来控制拖拽事件，然后做一个 drag 组件，可以支持 teleport，可以自定义组件的渲染，主要是帮助更好的使用 hook

这两个做好之后就可以基于去实现一个类似于 slider 中的 handle 组件，不过它的灵活度更高，它可以做拖拽距离的监听，可以实时的传递拖拽（Model 的拖拽，Textarea 的拓展等）或者仅支持某些方向（Table 列的拓展、Slider 的拖拽等）或者某段距离（部分业务可能会用到）

因为这类的组件的底层都是由拖拽来支撑的，所以当时看到这个 feature 的时候就觉得可以做一个底层的东西来支持他们，但是到现在一直没有时间去实践，如果你有更好的方案可以提 PR 上来我们一起讨论

**Comment by 07akioni** [comment]
> 有一些想法
> 
> 首先是基于 draggable 的方式来实现一个 hook 用来控制拖拽事件，然后做一个 drag 组件，可以支持 teleport，可以自定义组件的渲染，主要是帮助更好的使用 hook
> 
> 这两个做好之后就可以基于去实现一个类似于 slider 中的 handle 组件，不过它的灵活度更高，它可以做拖拽距离的监听，可以实时的传递拖拽（Model 的拖拽，Textarea 的拓展等）或者仅支持某些方向（Table 列的拓展、Slider 的拖拽等）或者某段距离（部分业务可能会用到）
> 
> 因为这类的组件的底层都是由拖拽来支撑的，所以当时看到这个 feature 的时候就觉得可以做一个底层的东西来支持他们，但是到现在一直没有时间去实践，如果你有更好的方案可以提 PR 上来我们一起讨论

这个和 split 的需求一致吗？感觉更像是节点拖拽之类的

**Comment by nooooooom** [comment]
> > 有一些想法
> > 首先是基于 draggable 的方式来实现一个 hook 用来控制拖拽事件，然后做一个 drag 组件，可以支持 teleport，可以自定义组件的渲染，主要是帮助更好的使用 hook
> > 这两个做好之后就可以基于去实现一个类似于 slider 中的 handle 组件，不过它的灵活度更高，它可以做拖拽距离的监听，可以实时的传递拖拽（Model 的拖拽，Textarea 的拓展等）或者仅支持某些方向（Table 列的拓展、Slider 的拖拽等）或者某段距离（部分业务可能会用到）
> > 因为这类的组件的底层都是由拖拽来支撑的，所以当时看到这个 feature 的时候就觉得可以做一个底层的东西来支持他们，但是到现在一直没有时间去实践，如果你有更好的方案可以提 PR 上来我们一起讨论
> 
> 这个和 split 的需求一致吗？感觉更像是节点拖拽之类的

我想远了，不过分离一个 drag 组件出来感觉很有必要

**Comment by 07akioni** [comment]
> > > 有一些想法
> > > 首先是基于 draggable 的方式来实现一个 hook 用来控制拖拽事件，然后做一个 drag 组件，可以支持 teleport，可以自定义组件的渲染，主要是帮助更好的使用 hook
> > > 这两个做好之后就可以基于去实现一个类似于 slider 中的 handle 组件，不过它的灵活度更高，它可以做拖拽距离的监听，可以实时的传递拖拽（Model 的拖拽，Textarea 的拓展等）或者仅支持某些方向（Table 列的拓展、Slider 的拖拽等）或者某段距离（部分业务可能会用到）
> > > 因为这类的组件的底层都是由拖拽来支撑的，所以当时看到这个 feature 的时候就觉得可以做一个底层的东西来支持他们，但是到现在一直没有时间去实践，如果你有更好的方案可以提 PR 上来我们一起讨论
> > 
> > 
> > 这个和 split 的需求一致吗？感觉更像是节点拖拽之类的
> 
> 我想远了，不过分离一个 drag 组件出来感觉很有必要

类似于 react-dnd？或者 react-beautiful-dnd?

**Comment by nooooooom** [comment]
> 

其实还要更加简单一些，他们之间都有一个基于鼠标进行拖动的逻辑并计算移动距离的逻辑，我感觉这块的代码的实现应该是一模一样的，所以想把这一块做成一个 hooks 或者组件来进行复用，只不过 drag 比它们之间多了一个 drop 的动作，这个可以另外进行实现

**Comment by nooooooom** [comment]
> > > > 有一些想法
> > > > 首先是基于 draggable 的方式来实现一个 hook 用来控制拖拽事件，然后做一个 drag 组件，可以支持 teleport，可以自定义组件的渲染，主要是帮助更好的使用 hook
> > > > 这两个做好之后就可以基于去实现一个类似于 slider 中的 handle 组件，不过它的灵活度更高，它可以做拖拽距离的监听，可以实时的传递拖拽（Model 的拖拽，Textarea 的拓展等）或者仅支持某些方向（Table 列的拓展、Slider 的拖拽等）或者某段距离（部分业务可能会用到）
> > > > 因为这类的组件的底层都是由拖拽来支撑的，所以当时看到这个 feature 的时候就觉得可以做一个底层的东西来支持他们，但是到现在一直没有时间去实践，如果你有更好的方案可以提 PR 上来我们一起讨论
> > > 
> > > 
> > > 这个和 split 的需求一致吗？感觉更像是节点拖拽之类的
> > 
> > 
> > 我想远了，不过分离一个 drag 组件出来感觉很有必要
> 
> 类似于 react-dnd？或者 react-beautiful-dnd?

其实还要更加简单一些，他们之间都有一个基于鼠标进行拖动的逻辑并计算移动距离的逻辑，我感觉这块的代码的实现应该是一模一样的，所以想把这一块做成一个 hooks 或者组件来进行复用，只不过 drag 比它们之间多了一个 drop 的动作，这个可以另外进行实现

**Comment by equt** [comment]
closed as duplicated of https://github.com/tusen-ai/naive-ui/issues/1111
