### ISSUE TITLE
希望增加一个带有背景色的分页

### ISSUE THREAD

**Issue by labradorGitHubCanine** [tusen-ai/naive-ui#2443]
### This function solves the problem (这个功能解决的问题)
分页组件目前样式比较单一，希望增加一个带有背景颜色的分页组件，参考链接贴在下方
### Expected API (期望的 API)
参考https://element.eleme.cn/#/zh-CN/component/pagination#slot

**Comment by 07akioni** [comment]
这是个长期的工作，需要先想想怎么做

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
