### ISSUE TITLE
dropdown组件的disabled设置无法响应式

### ISSUE THREAD

**Issue by popdo** [tusen-ai/naive-ui#2478]
### This function solves the problem (这个功能解决的问题)
1、很多时候我们需要根据用户切换功能来动态决定是否展示下拉菜单的某些选项。但是dropdown组件的disabled设置无法响应式切换。

2、就算传入computed计算属性也无法实时响应切换disabled的状态

3、我通过自定义props传入class来控制disabled状态 发现也无法响应式切换状态

### Expected API (期望的 API)
1、希望dropdown组件的disabled设置可以实时响应
2、希望dropdown组件增加一个“item是否隐藏”的功能，在很多时候 我们还是希望能动态决定某些选项是否展示出来

**Comment by LunaGod** [comment]
> 希望dropdown组件的disabled设置可以实时响应

无法复现
例：https://codesandbox.io/s/broken-wood-v6ht8y?file=/src/Demo.vue:152-201
> 希望dropdown组件增加一个“item是否隐藏”的功能，在很多时候 我们还是希望能动态决定某些选项是否展示出来

这个完全是业务上的问题
例：https://codesandbox.io/s/broken-wood-v6ht8y?file=/src/Demo.vue

**Comment by 07akioni** [comment]
展示的话我觉得属于一个怎么说呢，是不至于特别需要的 feature，我倒是想过如果未来比较闲的时候做一下这个 feature。

**Comment by Nakus0426** [comment]
> ### This function solves the problem (这个功能解决的问题)
> 1、很多时候我们需要根据用户切换功能来动态决定是否展示下拉菜单的某些选项。但是dropdown组件的disabled设置无法响应式切换。
> 
> 2、就算传入computed计算属性也无法实时响应切换disabled的状态
> 
> 3、我通过自定义props传入class来控制disabled状态 发现也无法响应式切换状态
> 
> ### Expected API (期望的 API)
> 1、希望dropdown组件的disabled设置可以实时响应 2、希望dropdown组件增加一个“item是否隐藏”的功能，在很多时候 我们还是希望能动态决定某些选项是否展示出来

我这边是通过动态生成options来实现动态显示的，而不是固定options再动态改变disabled

**Comment by wj007881** [comment]
使用h函数渲染NInputNumber时设置 disabled: check_month('M4'),，返回值无论是‘false'还是false都无法解除禁用状态

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
