### ISSUE TITLE
数据表格添加懒加载树形数据功能

### ISSUE THREAD

**Issue by yuzhenqiang** [tusen-ai/naive-ui#2489]
### This function solves the problem (这个功能解决的问题)
懒加载树形数据
### Expected API (期望的 API)
https://element.eleme.cn/#/zh-CN/component/table#shu-xing-shu-ju-yu-lan-jia-zai

**Comment by coader** [comment]
其实是希望是有hide 不显示行功能  现在要控制过滤就必须是重新生成一个新的array

**Comment by 07akioni** [comment]
> 其实是希望是有hide 不显示行功能 现在要控制过滤就必须是重新生成一个新的array columns也是这样

不显示列这个可以考虑，要做的话得考虑多级列的情况。

行百分之百不会做的，没什么用，实现起来肯定一屁股问题。

**Comment by zhangle1** [comment]
@07akioni  大佬现在还没有懒加载吗 刚好有需求需要用

**Comment by zhangle1** [comment]
刚好有需求需要用到 ^_^

**Comment by 07akioni** [comment]
> @07akioni 大佬现在还没有懒加载吗 刚好有需求需要用

之前已经有了，忘了加了

<img width="1485" alt="image" src="https://user-images.githubusercontent.com/18677354/184541092-4c61029a-c05d-4566-b442-c197b4119135.png">
