### ISSUE TITLE
n-select n-datepicker add method to show dropdown panel by code

### ISSUE THREAD

**Issue by coader** [tusen-ai/naive-ui#2518]
### This function solves the problem (这个功能解决的问题)
sometimes we use keyboard navigation to focus control element(eg: press enter to jump to next)
if use 'show' props, should control all behaviors, it's too complex to accept
### Expected API (期望的 API)
ctrlRef.value.dropdown()

**Comment by minosss** [comment]
`show` 都有 `on-update:show` 的事件抛出，绑个 `v-model`，然后获取焦点的时候显示

比如

```tsx
<form>
<n-input tabindex="1"></n-input>
<n-select tabindex="2" v-model:show="show" @focus="show = true"></n-select>
</form>
```

**Comment by coader** [comment]
这样后续所有对下拉的处理全部需要自己完成 非常麻烦 如果有方法支持打开 但其它行为仍由组件自行控制则会方便很多

**Comment by 07akioni** [comment]
> 这样后续所有对下拉的处理全部需要自己完成 非常麻烦 如果有方法支持打开 但其它行为仍由组件自行控制则会方便很多

这对应的是什么场景？我还从未遇到过这种需求

**Comment by equt** [comment]
closed as no response, feel free to reopen
