### ISSUE TITLE
二维码组件、拖拽排序组件、视频组件

### ISSUE THREAD

**Issue by evanlong0926** [tusen-ai/naive-ui#2535]
### This function solves the problem (这个功能解决的问题)
二维码：解决高频支付站点的需求
拖拽排序：提高用户体验
视频：属于用户常用组件，同时对Vue3开发者带来的问题（常用视频库体积大，不兼容Vue3，TS支持差 等瓶颈）
### Expected API (期望的 API)
二维码：https://lolicode.gitee.io/scui-doc/demo/#/vab/qrcode
拖拽排序：https://lolicode.gitee.io/scui-doc/demo/#/vab/drag
视频：https://lolicode.gitee.io/scui-doc/demo/#/vab/video

**Comment by amadeus711** [comment]
个人感觉二维码和拖拽有时间可以考虑一下，优先级不高；
视频组件可能单开一个库比较好，优先级低。
@07akioni

**Comment by toolse** [comment]
好的，快快做吧聪聪

**Comment by 07akioni** [comment]
> 个人感觉二维码和拖拽有时间可以考虑一下，优先级不高； 视频组件可能单开一个库比较好，优先级低。 @07akioni

二维码考虑一下可以，给个凑活能用的帮用户省点事。

拖拽这个有点麻烦，估计一时半会儿搞不了。

**Comment by 07akioni** [comment]
视频就算了，没这个能力。

**Comment by colin5213** [comment]
> 视频就算了，完全没必要，用专门的库就好了

建议增加一个 Infinite Scroll 无限滚动 组件，可实现滚动到底部时自动执行加载方法

**Comment by 07akioni** [comment]
> > 视频就算了，完全没必要，用专门的库就好了
> 
> 建议增加一个 Infinite Scroll 无限滚动 组件，可实现滚动到底部时自动执行加载方法

暂时不考虑

**Comment by CS-liujf** [comment]
> 可实现滚动到底部

我最近遇上了无限滚动的需求，我尝试用vueuse里的方法，但是似乎没法和naive的scroller使用
