### ISSUE TITLE
期望Modal遮罩层拥有更多的出现动画

### ISSUE THREAD

**Issue by SngBlog** [tusen-ai/naive-ui#2537]
### This function solves the problem (这个功能解决的问题)
可以有更多的使用场景 ，比如点击登录 能有一个滑落式的卡片落下来真的很棒
### Expected API (期望的 API)
仅需要给modal模态框的 transform-origin
添加更多值 比如 left top right bottom 滑出式卡片

**Comment by 07akioni** [comment]
目前不是很考虑，最多给用户开个自定义的口子

**Comment by SngBlog** [comment]
> 目前不是很考虑，最多给用户开个自定义的口子

自定义口子也好，比较不同动画的需求也是很常见的

**Comment by colin5213** [comment]
希望能给modal模态框加个**拖动**和**全屏**就好了

**Comment by colin5213** [comment]
> 目前不是很考虑，最多给用户开个自定义的口子

希望能给modal模态框加个拖动和全屏属性就好了

**Comment by 07akioni** [comment]
> > 目前不是很考虑，最多给用户开个自定义的口子
> 
> 希望能给modal模态框加个拖动和全屏属性就好了

全屏应该是不会给的，拖动考虑中，但是最后一定会落地

**Comment by equt** [comment]
1. 动画相关 https://github.com/tusen-ai/naive-ui/issues/490
2. Modal 拖动 https://github.com/tusen-ai/naive-ui/issues/1414
