### ISSUE TITLE
循环表单验证

### ISSUE THREAD

**Issue by zh1923** [tusen-ai/naive-ui#2578]
### This function solves the problem (这个功能解决的问题)
数组数据需要用表单来进行验证，试过例如element-ui似的方式，结果行不通
### Expected API (期望的 API)
<n-form-item-gi
            label="被投诉科室："
            :path="'formValue.defendantList.'   index   '.deptId'"
            :rule="{ required: true, trigger: ['blur', 'change'], message: '请选择' }"
          >
            <n-tree-select
              v-model:value="item.deptId"
              :options="deptList"
            />
          </n-form-item-gi>

**Comment by 07akioni** [comment]
数组数据是分散在多个 form-item 还是一个？

**Comment by 07akioni** [comment]
有新的回复之后会打开

**Comment by zh1923** [comment]
`<n-grid
          :cols="24"
          :x-gap="24"
          v-for="(item, index) in formValue.defendantList.filter((val) => val.deleted !== 1)"
          :key="index"
        >
          <n-form-item-gi
            :span="6"
            label="被投诉科室："
            ```
:path="'formValue.defendantList.' + index + '.deptId'"
            :rule="{ required: true, trigger: ['blur', 'change'], message: '请选择' }"
```
          >
            <n-tree-select
              v-model:value="item.deptId"
              :options="deptList"
              check-strategy="child"
              @update-value="(value: any, options: any) => updateBeComplainDept(value, options, item)"
            />
          </n-form-item-gi>
</n-grid>`
formValue.defendantList是我的数组数据，他是一个对象数组，这个数组中的deptId是必填的，
`:path="'formValue.defendantList.' + index + '.deptId'"
            :rule="{ required: true, trigger: ['blur', 'change'], message: '请选择' }"`
按照这种方式设置表单的rules无效，同方法element-ui或者antd都是可以的

**Comment by zh1923** [comment]
`<n-grid
          :cols="24"
          :x-gap="24"
          v-for="(item, index) in formValue.defendantList.filter((val) => val.deleted !== 1)"
          :key="index"
        >
          <n-form-item-gi
            :span="6"
            label="被投诉科室："
            ```
:path="'formValue.defendantList.' + index + '.deptId'"
            :rule="{ required: true, trigger: ['blur', 'change'], message: '请选择' }"
```
          >
            <n-tree-select
              v-model:value="item.deptId"
              :options="deptList"
              check-strategy="child"
              @update-value="(value: any, options: any) => updateBeComplainDept(value, options, item)"
            />
          </n-form-item-gi>
</n-grid>`
formValue.defendantList是我的数组数据，他是一个对象数组，这个数组中的deptId是必填的，
`:path="'formValue.defendantList.' + index + '.deptId'"
            :rule="{ required: true, trigger: ['blur', 'change'], message: '请选择' }"`
按照这种方式设置表单的rules无效，同方法element-ui或者antd都是可以的

**Comment by 07akioni** [comment]
这个复现有点抽象，缺太多代码的上下文了，需要一个最小复现

**Comment by equt** [comment]
close as no response

**Comment by chendj89** [comment]
看看这个，数组表单
```html

<template>
  <n-button @click="() => (show = true)"> 来吧 </n-button>
  <n-modal v-model:show="show" preset="dialog" title="Dialog" size="small">
    <n-form ref="formRef2" :model="values" require-mark-placement="left" label-placement="left">
      <n-form-item
        v-for="(item, index) in values"
        :label="item.label"
        :path="`values[${index}].value`"
        index="1"
        :rule="item.rule"
      >
        <n-input v-model:value="values[index].value" :placeholder="item.placeholder" />
      </n-form-item>
    </n-form>
    <template #action>
      <n-button type="primary" size="small" @click="submit">确定</n-button>
    </template>
  </n-modal>
</template>

<script setup lang="ts">
import type { FormItemRule } from 'naive-ui'
import { ref } from 'vue'
const show = ref(false)
const formRef: any = ref(null)
const formRef2: any = ref(null)

const validator = (rule: any) => {
  const result = rule.field.match(/\[(\d)\]/)
  if (result) {
    return values.value[result[1]].value ? true : false
  }
  return false
}

const values: any = ref([
  {
    label: '名称',
    value: '',
    placeholder: '请输入',
    rule: {
      trigger: ['input', 'blur'],
      required:true,
      message: '请输入',
      validator
    }
  },
  {
    label: '头像',
    value: '',
    placeholder: '请输入',
    rule: {
      trigger: ['input', 'blur'],
      message: '请输入',
      validator
    }
  },
  {
    label: '链接',
    value: '',
    placeholder: '请输入',
    index: 2,
    rule: {
      trigger: ['input', 'blur'],
      message: '请输入',
      validator
    }
  }
])

const submit = (e: MouseEvent) => {
  e.preventDefault()
  formRef2.value?.validate((errors: any) => {
    if (!errors) {
      console.log('验证成功')
      values.value.forEach((item: any) => {
        console.log(item.value)
      })
    } else {
      console.log(errors)
    }
  })
}
</script>

<style scoped></style>

```

**Comment by Lgowen** [comment]
想问下目前这个有解决方案嘛
