### ISSUE TITLE
在 keep-alive 下使用 NModal ，NModal 显示异常

### ISSUE THREAD

**Issue by pengzhen-developer** [tusen-ai/naive-ui#2649]
### TuSimple/naive-ui version (版本)
2.26.4

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
Chrome

### System and its version (系统及其版本)
MacOS

### Reappearance link (重现链接)
https://codesandbox.io/s/nifty-zhukovsky-vx2p1j?file=/src/views/About.vue

### Reappearance steps (重现步骤)
1，在 Home 路由，点击按钮，弹出 NModal。
2，在 NModal 里，点击按钮，跳转 About 路由。

### Expected results (期望的结果)
NModal 消失

### Actual results (实际的结果)
NModal 未消失

**Comment by 07akioni** [comment]
It may be a bug of vue.

ref https://github.com/vuejs/core/issues/5603

**Comment by pengzhen-developer** [comment]
@07akioni 

有人提供了解决方案，是否可以采用？

https://github.com/vuejs/core/issues/5603#issuecomment-1715369413

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
