### ISSUE TITLE
possibility to choose own icons for certain component

### ISSUE THREAD

**Issue by glutjenkossink** [tusen-ai/naive-ui#2668]
### This function solves the problem (这个功能解决的问题)
Being able to choose your own icon (library) for the design and be consistent with it.
At the moment the fluent icons are being used for example inputs such as 
- DatePicker
- TimePicker
- Password
- Select
- Number
- ...Many others most likely

But if one wants to use Material or FontAwesome thats currently not possible.
This could be possible with slots perhabs?
### Expected API (期望的 API)
```
<n-date-picker v-model:value="timestamp" type="date">
<template #icon>
{{ icon }}
</template>
</n-date-picker>
```

**Comment by izcream** [comment]
password input toggle already have custom icon slot in latest version(2.27.0)

custom icon slot for another component is on progress. Hope its finished soon🥹

**Comment by amadeus711** [comment]
#2756 
#2750

**Comment by 07akioni** [comment]
I think we can close the issue now. If you find there are still icons can't be customized, you can create an new issue.
