### ISSUE TITLE
新增 Infinite Scroll 无限滚动 组件

### ISSUE THREAD

**Issue by muchenfine** [tusen-ai/naive-ui#2670]
### This function solves the problem (这个功能解决的问题)
新增 Infinite Scroll 无限滚动 组件
### Expected API (期望的 API)
新增 Infinite Scroll 无限滚动 组件

**Comment by 07akioni** [comment]
暂时不会考虑

**Comment by liuzw2579** [comment]
也许可以试试 vueuse 的虚拟滚动： [https://vueuse.org/core/useInfiniteScroll/](https://vueuse.org/core/useInfiniteScroll/)
其提供 compose 函数和指令用法

**Comment by CS-liujf** [comment]
> 函数和指令用法

我是用它ref的方式，但是似乎没法和naive ui 的scroller搭配
