### ISSUE TITLE
n-form validation status reactive

### ISSUE THREAD

**Issue by AlexZCP** [tusen-ai/naive-ui#2675]
### This function solves the problem (这个功能解决的问题)
Validation status of whole form that can be used for disabling submit buttons, etc
### Expected API (期望的 API)
Currently n-form-item has a validationErrored reactive field to check if it passed validation or not.
It would be great to have analogical field for whole form.

However, if there is an alternative way to make disabled submit button whole it's not valid, point me please.

Concept example:
```
    <n-form ref="formRef" :model="model" :rules="rules">
      <n-form-item label="Label A" path="fieldA">
        <n-input v-model:value="model.fieldA" />
      </n-form-item>
      <n-form-item label="Label B" path="fieldB">
        <n-input v-model:value="model.fieldB" />
      </n-form-item>
     <n-button :disabled="formRef.validationErrored">Submit</n-button>
    </n-form>
```

**Comment by 07akioni** [comment]
Currently it would be very complex and you will need to take over form's validation.

I think we should somehow provide a way to achieve it.

**Comment by mrhammadasif** [comment]
You can use something like 

```typescript
// import {computedAsync} from "@vueuse/core"
const isValid = computedAsync(async () => {
  return formRef.value && formRef.value?.validate().then(o => true).catch(e => false)
}, false)
```

but that will always trigger validate state for you

**Comment by alanscandrett** [comment]
For posterity's sake, the workaround I found was to use a computed property. I wanted to avoid this, but I really need the button to be triggered only if the form is valid, without having users to click validate each time.

Below is the code in question, and below that is a description of what it does.

**Code**
```
const formInvalid = ref(false)
computed(async () => {
  await formRefEMSA?.value?.validate((errors) => {
    if (!errors) {
      formInvalid.value = false
    } else {
      console.log(errors)
      formInvalid.value = true
    }
  })
})
```

**AI Description of the code:**

> This code uses Vue 3 with the Naive UI framework to create a reactive form validation.
> 
> The variable formInvalid is created using the ref function, which creates a reactive reference that can be used in the Vue template to update the state of the application when it changes. Initially, formInvalid is set to false, indicating that the form is valid.
> 
> A computed property is then created using the computed function. Computed properties are functions that return a value based on the current state of the application. In this case, the computed property is an asynchronous function that awaits the validation of the form.
> 
> The form validation is triggered by calling the validate method on the formRefEMSA object, which should be a reference to the form element. The validate method takes a callback function as its argument, which is called when the validation is complete.
> 
> If there are no errors in the form, the errors parameter passed to the callback function will be undefined. In this case, the formInvalid value is set to false using the value property of the reactive reference.
> 
> If there are errors in the form, the errors parameter passed to the callback will be an array of error messages. In this case, the errors are logged to the console and the formInvalid value is set to true.
> 
> Overall, this code sets up a reactive form validation using Vue 3 and the Naive UI framework, updating the state of the application based on the validity of the form.
> 
> Share this explanation with colleagues: [whatdoesthiscodedo.com/g/1aa5261](https://whatdoesthiscodedo.com/g/1aa5261)













This code uses Vue 3 with the Naive UI framework to create a reactive form validation.

The variable formInvalid is created using the ref function, which creates a reactive reference that can be used in the Vue template to update the state of the application when it changes. Initially, formInvalid is set to false, indicating that the form is valid.

A computed property is then created using the computed function. Computed properties are functions that return a value based on the current state of the application. In this case, the computed property is an asynchronous function that awaits the validation of the form.

The form validation is triggered by calling the validate method on the formRefEMSA object, which should be a reference to the form element. The validate method takes a callback function as its argument, which is called when the validation is complete.

If there are no errors in the form, the errors parameter passed to the callback function will be undefined. In this case, the formInvalid value is set to false using the value property of the reactive reference.

If there are errors in the form, the errors parameter passed to the callback will be an array of error messages. In this case, the errors are logged to the console and the formInvalid value is set to true.

Overall, this code sets up a reactive form validation using Vue 3 and the Naive UI framework, updating the state of the application based on the validity of the form.

Share this explanation with colleagues: [whatdoesthiscodedo.com/g/1aa5261](https://whatdoesthiscodedo.com/g/1aa5261)

**Comment by zmj0920** [comment]
解决了吗 

const isValid = computedAsync(async () => {
  return formRef.value && formRef.value?.validate().then(o => true).catch(e => false)
}, false)
这个页面不自动更新啊

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
