### ISSUE TITLE
日期选择器 Date Picker可以新增开始周/月/年-结束周/月/年以及周筛选的功能吗

### ISSUE THREAD

**Issue by liyuaaa** [tusen-ai/naive-ui#2676]
### This function solves the problem (这个功能解决的问题)
日期选择器 Date Picker可以新增开始周/月/年-结束周/月/年以及周筛选的功能吗
### Expected API (期望的 API)
类似https://ant.design/components/date-picker-cn/#API

**Comment by zerotower69** [comment]
支持

**Comment by 07akioni** [comment]
周暂时不考虑，年和月是有计划的

**Comment by yanbowe** [comment]
> 周暂时不考虑，年和月是有计划的

季度范围选择器会有计划吗

**Comment by 07akioni** [comment]
> > 周暂时不考虑，年和月是有计划的
> 
> 季度范围选择器会有计划吗

有，有时间会优先搞

**Comment by yanbowe** [comment]
> > > 周暂时不考虑，年和月是有计划的
> > 
> > 
> > 季度范围选择器会有计划吗
> 
> 有，有时间会优先搞

收到

**Comment by donkeylmx** [comment]
你好，请问一下 Date Picker 组件 可否增加一个 周 的 类型  比如element-ui 这样的：
![image](https://user-images.githubusercontent.com/25096110/209056593-d3c2ac43-ccc7-40ed-8170-b88d401f3cfd.png)
<n-date-picker v-model:value="timestamp" type="week"  /> 
通过 type= “week” 来调用
因为我发现在做统计分析的页面时，会经常有周为单位的时间周期来进行数据过滤

**Comment by zhangke1722** [comment]
支持  目前业务需求确实会用周选择器

**Comment by palmerye** [comment]
> 你好，请问一下 Date Picker 组件 可否增加一个 周 的 类型 比如element-ui 这样的： ![image](https://user-images.githubusercontent.com/25096110/209056593-d3c2ac43-ccc7-40ed-8170-b88d401f3cfd.png) 通过 type= “week” 来调用 因为我发现在做统计分析的页面时，会经常有周为单位的时间周期来进行数据过滤

+1

**Comment by duanmw** [comment]
> 你好，请问一下 Date Picker 组件 可否增加一个 周 的 类型 比如element-ui 这样的： ![image](https://user-images.githubusercontent.com/25096110/209056593-d3c2ac43-ccc7-40ed-8170-b88d401f3cfd.png) 通过 type= “week” 来调用 因为我发现在做统计分析的页面时，会经常有周为单位的时间周期来进行数据过滤

+1

**Comment by jahnli** [comment]
It already exists in the new version
