### ISSUE TITLE
DataTable 在 safari 下滚动卡顿（横向滚动条异常）

### ISSUE THREAD

**Issue by pengzhen-developer** [tusen-ai/naive-ui#2735]
### TuSimple/naive-ui version (版本)
2.27.0

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
Safari 版本15.1 (17612.2.9.1.20)

### System and its version (系统及其版本)
MacOS Monterey MacBook Air (M1, 2020)

### Reappearance link (重现链接)
https://codesandbox.io/s/ygdp4d?file=/src/main.js:0-158

### Reappearance steps (重现步骤)
官网例子可复现。

水平滚动时，滚动非常卡顿。

### Expected results (期望的结果)
滚动正常

### Actual results (实际的结果)
滚动卡顿

**Comment by pengzhen-developer** [comment]
https://user-images.githubusercontent.com/12759499/161611838-d6157489-d9cd-4601-af97-3e5567d01198.mov

**Comment by 07akioni** [comment]
这个我其实也发现过，不知道是不是 DOM 数太多导致的，假设你的页面只有一个或者几个 Table，会出这个问题吗？

**Comment by 07akioni** [comment]
长期来看会想办法试试解决
