### ISSUE TITLE
点击输入框的输入组组的按钮时，左上角出现小三角形

### ISSUE THREAD

**Issue by jahnli** [tusen-ai/naive-ui#2741]
### TuSimple/naive-ui version (版本)
2.27.0

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
chrome  100.0.4896.60

### System and its version (系统及其版本)
windows

### Reappearance link (重现链接)
https://codesandbox.io/s/yf5rq6

### Reappearance steps (重现步骤)
点击输入框组的按钮时，左上角出现小三角形

### Expected results (期望的结果)
fix

### Actual results (实际的结果)
点击输入框组的按钮时，左上角出现小三角形

**Comment by Sepush** [comment]
> ### TuSimple/naive-ui version (版本)
> 2.27.0
> 
> ### Vue version (Vue 版本)
> 3.2.31
> 
> ### Browser and its version (浏览器及其版本)
> chrome 100.0.4896.60
> 
> ### System and its version (系统及其版本)
> windows
> 
> ### Node version (Node 版本)
> ### Reappearance link (重现链接)
> https://codesandbox.io/api/v1/sandboxes/define
> 
> ### Reappearance steps (重现步骤)
> 点击输入框组的按钮时，左上角出现小三角形
> 
> ### Expected results (期望的结果)
> fix
> 
> ### Actual results (实际的结果)
> 点击输入框组的按钮时，左上角出现小三角形
> 
> ### Remarks (补充说明)

复现链接看不了

**Comment by jahnli** [comment]
已更改，其实就是官网的demo链接，官网就可以复现

**Comment by Sepush** [comment]
感觉可能是chrome的bug

**Comment by Talljack** [comment]
加一个信息，chrome 99.0.4844.51版本没有问题

**Comment by 07akioni** [comment]
是不是 windows 专属？我在 mac 上面没能复现

**Comment by 07akioni** [comment]
<img width="544" alt="image" src="https://user-images.githubusercontent.com/18677354/162606641-6dc59854-4b7a-47f4-af45-b0baa69997e7.png">

**Comment by Sepush** [comment]
> <img alt="image" width="544" src="https://user-images.githubusercontent.com/18677354/162606641-6dc59854-4b7a-47f4-af45-b0baa69997e7.png">

左边搜索的 左上角 左下角 你这张图放大就能看到了

**Comment by 07akioni** [comment]
这波属于 chrome 摆烂了，我觉得不好修

有的时候放大一下再回来就没了

**Comment by 07akioni** [comment]
再等几个 chrome 版本吧

**Comment by Sepush** [comment]
> 这波属于 chrome 摆烂了，我觉得不好修
> 
> 有的时候放大一下再回来就没了

最近 chrome 的bug 确实有点多 这个问题在 firefox 上 就没问题

**Comment by 07akioni** [comment]
人家也在冲业绩呢，100 了
