### ISSUE TITLE
`<NModal />` Maximize & Minimize Support

### ISSUE THREAD

**Issue by yuntian001** [tusen-ai/naive-ui#2807]
### This function solves the problem (这个功能解决的问题)
弹窗组件加上 最大化 最小化 可拖动 自定义大小
### Expected API (期望的 API)
可以看下 https://vxetable.cn/#/table/module/modal 的demo

**Comment by yudan215** [comment]
并且增加弹出位置设置，现在貌似只能在中间

**Comment by equt** [comment]
拖动参考 https://github.com/tusen-ai/naive-ui/issues/2152

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
