### ISSUE TITLE
是否可以支持两个树之间进行拖放

### ISSUE THREAD

**Issue by aohanhe** [tusen-ai/naive-ui#2820]
### This function solves the problem (这个功能解决的问题)
我现在有一个需求，要从左侧的树把节点拖放到右侧，但测试了一下现在n-tree是无法实现的，是否可以支持该功能。或者有其它方法来实现？
### Expected API (期望的 API)
添加一个属性允许跨树进行拖放

**Comment by 07akioni** [comment]
有这个想法，先看看难度吧。

**Comment by songispm** [comment]
很需要这个功能，+1

**Comment by songispm** [comment]
可稍微提一丢丢优先级

**Comment by equt** [comment]
拖动短期内不可能实现，[现行的做法](https://www.naiveui.com/en-US/os-theme/components/transfer#render-source-list.vue)是使用 `<NTransfer />` 然后在左边用 `<NTree />`，但是右侧目前不能自定义渲染。

**Comment by equt** [comment]
@07akioni 考虑允许右侧自定义？

目前先关闭，有自定义需求另开新 issue

**Comment by 07akioni** [comment]
@equt antd 在比较老的版本直接支持，具体怎么搞的我不太记得了，后面改过好像一直没修。

主要是 Tree 的内部状态需要比较多的调整在能支持这件事

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
