### ISSUE TITLE
fallback-option callback need to understand returning 'false' value

### ISSUE THREAD

**Issue by AlexZCP** [tusen-ai/naive-ui#2833]
### This function solves the problem (这个功能解决的问题)
We have n-select component, which has as prop 'fallback-option' for solving problem, when we have select value out of options list.

'fallback-option' can have: false | void

But if I need to do something before and after return false - naive draw an empty option in n-select.

This will draw an empty option:
`:fallback-option="(value) => { doSmth(); return false }"`

Now I will explain why its important, for example:
```
      <n-select 
        :options="organizationSelectOptions"
        v-model:value="organization_id"
        @update:value="(value) => emit('update:organization_id', value)"
        :fallback-option="false"
        ...
      ></n-select>
```
This code emits value to parent component every time when you changing select. Works fine, but when `organizationSelectOptions` changes I have **out of list value** and select reset to unselected state (because of fallback-option="false"). 
And thats also good, but at the same time `organization_id` and `update:value` doesn't trigger. 
So I still has an old value, when n-select is unselected. 

### Expected API (期望的 API)
:fallback-option < false | void > 
Add the same react on "(value) => false" like on "false"

Or fix the bug with updating value.

**Comment by AlexZCP** [comment]
> 1. fallback doesn't allow to return false, as it's shown in docs `false | ((value: string | number) => SelectOption)`
> 2. update:value will never be triggered by data change, it can only be triggered by user interaction

Exactly, that is the problem: when you have :fallback-option='false' and selectValue out of range - cp-select resets and you see 'Please select' placeholder, but selectValue still keep old value. So current select state and binding select value not syncronized.

**Comment by 07akioni** [comment]
> > 1. fallback doesn't allow to return false, as it's shown in docs `false | ((value: string | number) => SelectOption)`
> > 2. update:value will never be triggered by data change, it can only be triggered by user interaction
> 
> Exactly, that is the problem: when you have :fallback-option='false' and selectValue out of range - cp-select resets and you see 'Please select' placeholder, but selectValue still keep old value. So current select state and binding select value not syncronized.

value is controlled by user but not the component

**Comment by AlexZCP** [comment]
At least it would be good to have even on-fallbackOption to know when you have value out of range.

**Comment by 07akioni** [comment]
> o have event on-fallbackOption to know

The API is not designed for that. It only let you show different label for value with not resolved options. If you want to know it, check it outside the component.
