### ISSUE TITLE
Customizable Mask for Modal, Dialog, Drawer

### ISSUE THREAD

**Issue by felixzhou555** [tusen-ai/naive-ui#2846]
### This function solves the problem (这个功能解决的问题)
在部分场景中，弹窗和抽屉我们不需要mask
### Expected API (期望的 API)
希望弹窗和抽屉的mask可以做到自定义

**Comment by 07akioni** [comment]
会考虑先给 drawer 加上，modal 的问题稍微复杂一些

**Comment by equt** [comment]
For the mask related feature request, see https://github.com/tusen-ai/naive-ui/issues/2261

**Comment by jahnli** [comment]
duplicate https://github.com/tusen-ai/naive-ui/issues/2261

**Comment by z-z-zz** [comment]
这个功能实现了吗？2.37.3版本还未看到对应props
