### ISSUE TITLE
期望新增一个切换暗色主题时颜色过渡动画的开关

### ISSUE THREAD

**Issue by colin5213** [tusen-ai/naive-ui#2848]
### This function solves the problem (这个功能解决的问题)
因为有的项目要求亮暗主题切换时不需要 transition: color .3s 的动画，如果直接 transition: color 0s !important 又会让其他的 比如（Dialog，Drawer）的动画失效；
### Expected API (期望的 API)
在主题编辑器 common 中加一个控制颜色类过渡动画时间，方便自由控制 也不影响其他过渡动画

**Comment by Talljack** [comment]
ref #555

**Comment by colin5213** [comment]
> ref #555

但是我要怎么解决这个问题呢，一个一个覆盖也不现实吧，覆盖也会影响 Dialog，Drawer ...组件的动画

**Comment by 07akioni** [comment]
> > ref #555
> 
> 但是我要怎么解决这个问题呢，一个一个覆盖也不现实吧，覆盖也会影响 Dialog，Drawer ...组件的动画

这个问题解决起来很麻烦，如果你不要的话没什么好办法。

要实现的话需要给每个组件都增加一些特殊用于切换时的样式，不好整。

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
