### ISSUE TITLE
Missing indeterminate state for Progress or a Spinner component

### ISSUE THREAD

**Issue by gdgcentrica** [tusen-ai/naive-ui#2880]
### This function solves the problem (这个功能解决的问题)
It will be really useful to have an "indeterminate" state for the Progress component or a Spinner component, because it's not always possible to have a progress value during some long processing.
### Expected API (期望的 API)
```vue
<n-progress type="circle" :indeterminate="true" />
```

**Comment by equt** [comment]
Duplicate of https://github.com/tusen-ai/naive-ui/issues/2103
