### ISSUE TITLE
建议通过方法调用对话框（`useDialog`）支持modal内容完全自定义

### ISSUE THREAD

**Issue by lakca** [tusen-ai/naive-ui#2895]
### This function solves the problem (这个功能解决的问题)
如题，支持通过方法调用对话框时可以选择不提供任何内容预设，即支持[DialogEnvironment](https://github.com/TuSimple/naive-ui/blob/v2.28.2/src/dialog/src/DialogEnvironment.tsx#L129)模块的`default`插槽完全自定义。

目前，只能通过以下类似方式妥协实现：
```ts
dialog.create({
  title: '',
  showIcon: false,
  closable: false,
  style: { padding: 0 }
})
```
以及单独覆写一些组件，如`.n-dialog_content`的样式。
### Expected API (期望的 API)
比如：

- 通过提供`DialogOptions.render: () => VNode`属性指定默认插槽。
- 或者提供新方法`useDialog.bare()`/`useModal.create()`等。

**Comment by 07akioni** [comment]
如果真的要这么做我感觉得增加一个 modal provider。

**Comment by 07akioni** [comment]
dialog 不是用来做 modal 的

**Comment by 07akioni** [comment]
这个属于 nice to have 的，优先级应该会非常低

**Comment by jahnli** [comment]
It already exists in the new version
