### ISSUE TITLE
建议在日历组件中增加一个卡片模式的日历组件，就类似于日期选择那的那样

### ISSUE THREAD

**Issue by nameJw** [tusen-ai/naive-ui#2920]
### This function solves the problem (这个功能解决的问题)
建议在日历组件中增加一个卡片模式的日历组件，就类似于日期选择器那的那样。以便适用更多场景
### Expected API (期望的 API)
<n-calendar {...calendarProps, mode='card'}></n-calendar>

**Comment by 07akioni** [comment]
date-picker 新增了 panel 属性，符合需求么？

**Comment by equt** [comment]
close as no response
