### ISSUE TITLE
Add `divider` slot to Tabs component

### ISSUE THREAD

**Issue by jdwit** [tusen-ai/naive-ui#2931]
### This function solves the problem (这个功能解决的问题)
Sometimes it is needed to add something between tabs, for instance a divider symbol. An example use case is to add an arrow ">" as a divider between tabs. There is a `prefix` and `suffix` slot now, and the `divider` slot would complement this. It will greatly increase the number of scenarios in which the Tabs component can be used very much.
### Expected API (期望的 API)
add a slot `divider` which will be rendered _between_ tab instances.

**Comment by 07akioni** [comment]
Why '>' can be a divider? What's it for?

I don't think it will be useful for most type of tabs.

**Comment by equt** [comment]
close as no response
