### ISSUE TITLE
请愿新增类似公告栏、数据列表滚动的组件

### ISSUE THREAD

**Issue by lin-code-world** [tusen-ai/naive-ui#2937]
### This function solves the problem (这个功能解决的问题)
1.通知公告栏文字水平滚动
2.数据列表上下一行行滚动，或者整个翻页滚动
### Expected API (期望的 API)
新增滚动组件，或者在原组件上新增属性用于配置滚动效果，DataTable

**Comment by muchenfine** [comment]
+1

**Comment by equt** [comment]
Log 应该可以满足对应需求
