### ISSUE TITLE
表格总结栏优化

### ISSUE THREAD

**Issue by yanbowe** [tusen-ai/naive-ui#2948]
### This function solves the problem (这个功能解决的问题)
可以更好，更清晰方便的自定义数据表格的总结栏
### Expected API (期望的 API)
columns支持footer来插入当前列的总结，如果footer为字符串的话就使用template方式渲染当前列的总结
例子： https://tdesign.tencent.com/vue-next/components/table?tab=demo#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A1%A8%E5%B0%BE%E7%9A%84%E8%A1%A8%E6%A0%BC

**Comment by equt** [comment]
与 #2814 重复，如果有更加好的接口设计想法，可以在 Discussions 里面讨论
