### ISSUE TITLE
image-card类型中的upload组件支持拆分，加一个可以通过props指定单个文件的组件

### ISSUE THREAD

**Issue by JerryCheng1** [tusen-ai/naive-ui#2983]
### This function solves the problem (这个功能解决的问题)
目的是想给照片墙加draggable控制file-list顺序
### Expected API (期望的 API)
upload image-card 类型给个文件组件，或者image-card上draggable功能

**Comment by 07akioni** [comment]
所以就是渲染单个 item 的能力？

**Comment by JerryCheng1** [comment]
您的邮件已收到。祝您生活愉快！

**Comment by equt** [comment]
close as no response

**Comment by JerryCheng1** [comment]
您的邮件已收到。祝您生活愉快！
