### ISSUE TITLE
【n-tree】虚拟滚动展开节点有卡顿

### ISSUE THREAD

**Issue by vurrr** [tusen-ai/naive-ui#3011]
### TuSimple/naive-ui version (版本)
2.29.0

### Vue version (Vue 版本)
3.2.36

### Browser and its version (浏览器及其版本)
Chrome(101.0.4951.64)

### System and its version (系统及其版本)
MacOS(11.1)

### Reappearance link (重现链接)
https://codesandbox.io/s/epic-kapitsa-ele9p5?file=/src/Demo.vue

### Reappearance steps (重现步骤)
1. 设置 virtual-scroll 和组件高度
2. 把节点的高度调整到 40px( 高于 30px）
3. 展开节点和收起节点

### Expected results (期望的结果)
希望能顺滑展开

### Actual results (实际的结果)
会先卡一下再完全展开

**Comment by 07akioni** [comment]
https://user-images.githubusercontent.com/18677354/170573498-91cd43eb-7674-4498-bf88-b42bd50321e6.mov

没能复现

**Comment by amadeus711** [comment]
> 2022-05-27.4.20.05.mov 
> 没能复现

https://user-images.githubusercontent.com/46394163/170725360-4eb6abef-79fe-4a03-89a1-18aa8aff142f.mov

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
