### ISSUE TITLE
n-menu包含子菜单的父级菜单可以被选中

### ISSUE THREAD

**Issue by hackyoMa** [tusen-ai/naive-ui#3092]
### This function solves the problem (这个功能解决的问题)
例如当父菜单同样拥有界面时，可以通过on-update:value进行跳转。
### Expected API (期望的 API)
n-menu -> activate-parent: true | false

**Comment by 07akioni** [comment]
如果具有展开交互，怎么处理

**Comment by 07akioni** [comment]
又可以展开又可以点击的那种

**Comment by hackyoMa** [comment]
我的需求通过render-label解决了。
我说的就是又可以展开又可以点击的这种场景，现在点击菜单的话是只触发了展开，但是不触发value update，建议是增加个配置，点击菜单可以即触发展开又触发value update。

**Comment by pro-xiaoy** [comment]
hello，可以share下代码吗？如何做到选中了，menu-item整体的高亮

> 我的需求通过render-label解决了。 我说的就是又可以展开又可以点击的这种场景，现在点击菜单的话是只触发了展开，但是不触发value update，建议是增加个配置，点击菜单可以即触发展开又触发value update。

**Comment by hackyoMa** [comment]
没做那么复杂，但实际上你label自定义的话，想怎么画就怎么画。
`{
      key: '/workflows/' + org.id,
      label: () =>
        h(
          RouterLink,
          {
            to: '/workflows/' + org.id
          },
          {
            default: () => org.name
          }
        ),
      id: org.id,
      parentId: org.parentId
    }`

**Comment by 07akioni** [comment]
这个我再考虑一下，看看要不要加一个功能允许选中

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
