### ISSUE TITLE
Allow sticky headers for NDataTable without fixed height

### ISSUE THREAD

**Issue by Jasenkoo** [tusen-ai/naive-ui#3133]
### This function solves the problem (这个功能解决的问题)
It would be great if we could have a sticky header on the table without needing a fixed height. Tried overriding the header style, but looks like the parent divs are blocking it.
### Expected API (期望的 API)
```
<NDataTable sticky-headers></NDataTable>
```

**Comment by equt** [comment]
track in #1555
