### ISSUE TITLE
希望 NInputNumber 添加 decimal 支持

### ISSUE THREAD

**Issue by MBMll** [tusen-ai/naive-ui#3152]
### This function solves the problem (这个功能解决的问题)
当输入一些长小数时, 比如: 200000.00000002, 数据会错乱
### Expected API (期望的 API)
组件内部的计算最好可以使用decimal进行

**Comment by 07akioni** [comment]
只要运算还在用 number 来做，就很难从根源上避免这个问题

**Comment by 07akioni** [comment]
这还是一个比较长期的问题，我自己去想比较根本的做法是给一个 string value 的模式，然后 number 的就这样吧。

double 已经摆烂了。

**Comment by MBMll** [comment]
我按照 string value, 引入 decimal.js , 做了一版:
[https://github.com/MBMll/snippet/blob/main/src/components/LocalInputDecimal/index.vue](url)
