### ISSUE TITLE
Resizable Column Width for `<NDataTable />` - 表格支持可调节列宽

### ISSUE THREAD

**Issue by feifandeni** [tusen-ai/naive-ui#3165]
### This function solves the problem (这个功能解决的问题)
表头拖拽宽度，这个需求，很多场合都需要
### Expected API (期望的 API)
无

**Comment by Sepush** [comment]
https://www.naiveui.com/zh-CN/os-theme/components/data-table#controlled-page.vue
分页条数显示是支持的
track in https://github.com/tusen-ai/naive-ui/issues/1563
