### ISSUE TITLE
Yup/Zod Validation Support for Forms

### ISSUE THREAD

**Issue by siamekanto19** [tusen-ai/naive-ui#3225]
### This function solves the problem (这个功能解决的问题)
While building forms, it is very painful having to write all the possible validation rules, functions and regex from scratch. It would make a lot of developer's DX better if there was native Yup/Zod Schema validation baked into the Form System of Naive UI. Most of the dedicated form libraries already have this feature by default.
### Expected API (期望的 API)
It can be implemented in many ways I suppose, but what makes the most sense to me is, when we create a form with the `n-form` component, we can pass the validation schema as a prop. Probably something like,

```
// Inside script

const schema = Yup.object().shape(.....)

// Inside template

<n-form :validationSchema="schema">

........

</n-form>

```

**Comment by oikalyptus** [comment]
I second this. This would be awesome. 👍

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by rimonmath** [comment]
This would be awesome. 👍 (3)

**Comment by andrei-dracea** [comment]
any chance of this happening?
