### ISSUE TITLE
Events on image preview open/close.

### ISSUE THREAD

**Issue by kieste** [tusen-ai/naive-ui#3231]
### This function solves the problem (这个功能解决的问题)
The app cannot react to the image preview. 

For example I would like to display custom controls in front of the current image preview.

### Expected API (期望的 API)
```
<n-image
    width="100"
    src="https://07akioni.oss-cn-beijing.aliyuncs.com/07akioni.jpeg"
    on-preview-open="handleImagePreviewOpen"
    on-preview-close="handleImagePreviewClose"
/>
```
When moving to the previous/next image in an image group, the close-handler of the current image is called and the open-handler of the previous/next image.

**Comment by jahnli** [comment]
`on-preview-prev`  `on-preview-next`
