### ISSUE TITLE
【upload】组件下载功能添加download属性

### ISSUE THREAD

**Issue by seafronthu** [tusen-ai/naive-ui#3274]
### This function solves the problem (这个功能解决的问题)
可以在后端不配合的情况下，浏览器上直接能打开的文件能支持下载。譬如jpg、png、gif等等
### Expected API (期望的 API)
添加download属性

**Comment by 2277419213** [comment]
image是可以预览跨域的图片资源的，但是下载发送get请求的时候会提示跨域，这个怎么搞 @07akioni

**Comment by 07akioni** [comment]
> 预览跨域的图片资源的，但是下载发送get请求的时候会提示跨域，这个

这个应该只能靠你的服务端解决了，允许跨域的 xhr

**Comment by 07akioni** [comment]
如果不是靠 xhr 的就，可以考虑一下 a + download 属性试试，不确定会 work

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
