### ISSUE TITLE
Upload component drag sort file list, and large file segment upload support.

### ISSUE THREAD

**Issue by xpader** [tusen-ai/naive-ui#3279]
期望添加上传文件分片，和文件列表拖拽排序功能。

### This function solves the problem (这个功能解决的问题)
When we upload a big file, like video, iso files, segment upload can be more stable.
And drag sort file list is also a useful feature.
### Expected API (期望的 API)
Add some options like plupload:
chunk-size: 0 means no chunk upload, and great thant 0 mean chunk size, eg: 200 mean 200kb.
file-list-drag-sort: true means allow drag sort file list.

**Comment by 07akioni** [comment]
We don't plan to add segment upload & sort file list currently.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
