### ISSUE TITLE
[DateRangePicker] is-date-disabled 里面的value没有与default-time 关联

### ISSUE THREAD

**Issue by yuzhenqiang** [tusen-ai/naive-ui#3283]
### TuSimple/naive-ui version (版本)
2.31.0

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Chrome/103.0.0.0

### System and its version (系统及其版本)
Mac OS 12.4

### Reappearance link (重现链接)
https://codesandbox.io/s/cocky-cloud-y49j61

### Reappearance steps (重现步骤)
选择时间范围

### Expected results (期望的结果)
当传入 default-time="['00:00:00', '23:59:59']" 时，希望在 is-date-disabled 里，value是按照传入的 default-time 设置默认的时分秒

### Actual results (实际的结果)
没有关联默认时间

**Comment by yuzhenqiang** [comment]
<img width="749" alt="image" src="https://user-images.githubusercontent.com/25284107/178881622-fd1b46fb-87b2-4c30-9a04-5c3e8096b29b.png">
因为设置了 default-time 所以时间那里会展示出来，但实际上在 id-date-disabled 里，开始和结束的时间都是 00:00:00

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
