### ISSUE TITLE
Carousel 组件 重加载显示空白

### ISSUE THREAD

**Issue by wildor1** [tusen-ai/naive-ui#3285]
### TuSimple/naive-ui version (版本)
2.31.0

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
chrome 103.0.5060.114

### System and its version (系统及其版本)
Win10

### Reappearance link (重现链接)
https://github.com/wildor1/testNaive

### Reappearance steps (重现步骤)
<n-carousel autoplay=true interval=4000 effect="custom" trigger="hover"
    dot-type="line" :transition-props="{ name: 'creative' }" class="relative" >
<img src=''>
<img src=''>
<img src=''>
</n-carousel>

### Expected results (期望的结果)
避免Carousel 会显示空白

### Actual results (实际的结果)
我在切换到游览器其他页面后者切换到桌面其他程序的时候，过一段时间在返回测试页，Carousel 会显示空白，4秒后才正常显示

**Comment by nooooooom** [comment]
有没有可能是咱的[类型写错了](https://github.com/wildor1/testNaive/blob/b79b223e39e3aef0e174430c32157a34801bb26c/src/components/SwiperComponent.vue#L2)

![image](https://user-images.githubusercontent.com/61452855/178893826-4bb27df9-eedf-4114-82ce-8e4639342f0f.png)

**Comment by nooooooom** [comment]
4秒后才显示正常是因为 `auto-loop` 在4秒后更新了状态，将正确的 `current-index` 调回来了

**Comment by wildor1** [comment]
谢谢您的解答，但是我在标签里传的是数字，并没有传递字符串。 interval=4000 current-index=0 default-index=0

**Comment by nooooooom** [comment]
> 谢谢您的解答，但是我在标签里传的是数字，并没有传递字符串。 interval=4000 current-index=0 default-index=0

传数字的话一般是 `:current-index="0"`，之所以写的时候不报错是因为 Vue 的模板解析插件帮你做了处理了，处理完之后 `current=0` 就相当于 `current="0"`

**Comment by nooooooom** [comment]
> 谢谢您的解答，但是我在标签里传的是数字，并没有传递字符串。 interval=4000 current-index=0 default-index=0

`interval` 为了方便单位转换是可以传字符串跟数字的

**Comment by wildor1** [comment]
我更改之后，:autoplay=true :interval="4000" :current-index="0" :default-index="0"，没有warning，但是切到其他tab，一分钟后回到测试页面还是会有空白。

**Comment by jahnli** [comment]
Closed due to inactivity. Feel free to reopen if you're still having trouble.
