### ISSUE TITLE
Nlog，Timing push data, resulting in strong jitter of the whole data

### ISSUE THREAD

**Issue by jahnli** [tusen-ai/naive-ui#329]
### TuSimple/naive-ui version (版本)
2.14.0

### Vue version (Vue 版本)
3.1.2

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
windows

### Reappearance link (重现链接)
https://codesandbox.io/s/9cy02

### Reappearance steps (重现步骤)
Nlog，Timing push data, resulting in strong jitter of the whole data

### Expected results (期望的结果)
Transitional scrolling, similar to CMD log

### Actual results (实际的结果)
Nlog，Timing push data, resulting in strong jitter of the whole data

**Comment by jahnli** [comment]
https://user-images.githubusercontent.com/20943608/123825064-28703800-d931-11eb-9d90-6bc0d669ad76.mp4

**Comment by equt** [comment]
Implemented as [`<NLog />`](https://www.naiveui.com/en-US/os-theme/components/log)
