### ISSUE TITLE
n-grid组件SSR渲染自适应异常

### ISSUE THREAD

**Issue by Baiyuetribe** [tusen-ai/naive-ui#3301]
### TuSimple/naive-ui version (版本)
2.31.0

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
windows

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/grid

### Reappearance steps (重现步骤)
ssr模式下，n-gird自适应组件会先闪一下，然后缩放回正常结果。实际测试观感影响很大。

### Expected results (期望的结果)
期望解决闪现问题。实现类似https://arco.design/vue/component/grid这样的正常输出

### Actual results (实际的结果)
先浏览器闪一下，然后布局缩放回正常结果， nuxt3及vite-ssg里表现均如此

**Comment by 07akioni** [comment]
这个不属于 BUG，而是属于符合预期的行为。

现在的行为在某些情况下有值得优化的空间。

**Comment by zhouxiaoercom** [comment]
我也遇到了这个问题。
现在nuxt3能用的框架不多，naive-ui 深受nuxt3开发者喜欢的，期待优化。

**Comment by 07akioni** [comment]
> 我也遇到了这个问题。 现在nuxt3能用的框架不多，naive-ui 深受nuxt3开发者喜欢的，期待优化。

如果说你没有用 grid 的一些特殊特性，可以使用 legacy-grid

**Comment by chendalin666** [comment]
在nuxt3中n-grid的x-gap，y-gap和cols属性用到ResponsiveDescription类型后，刷新会出现不生效的情况

**Comment by chendalin666** [comment]
@07akioni

**Comment by chendalin666** [comment]
![image](https://user-images.githubusercontent.com/49202260/233521634-7627a53e-17d2-4198-a575-5de72eefde77.png)
![image](https://user-images.githubusercontent.com/49202260/233521700-a1ca57eb-9394-4b22-849a-ec149fa2689d.png)
测试发现，刷新后style中gap属性消失。
