### ISSUE TITLE
表格拖拽列头可控制宽度

### ISSUE THREAD

**Issue by muchenfine** [tusen-ai/naive-ui#3318]
### This function solves the problem (这个功能解决的问题)
表格拖拽列头可控制宽度
### Expected API (期望的 API)
表格拖拽列头可控制宽度

**Comment by muchenfine** [comment]
@07akioni  是否考虑支持， 表格数据量大的时候 ，如果无法拖拽列宽，数据显示不了，不方便查看和操作

**Comment by Sepush** [comment]
track in https://github.com/tusen-ai/naive-ui/issues/1563

**Comment by muchenfine** [comment]
> track in #1563

我看了这个Issue好好像不是同一个需求，他是对表格内的内容排序，希望能对表格能拖拽控制显示内容的宽度。
类似于 https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBib3JkZXIgc3R5bGU9XCJ3aWR0aDogMTAwJVwiPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImRhdGVcIiBsYWJlbD1cIkRhdGVcIiB3aWR0aD1cIjE4MFwiIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwibmFtZVwiIGxhYmVsPVwiTmFtZVwiIHdpZHRoPVwiMTgwXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJhZGRyZXNzXCIgbGFiZWw9XCJBZGRyZXNzXCIgLz5cbiAgPC9lbC10YWJsZT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5jb25zdCB0YWJsZURhdGEgPSBbXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMicsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMScsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG5dXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==

**Comment by muchenfine** [comment]
拖拽data name 的表头部分

**Comment by Sepush** [comment]
> 拖拽data name 的表头部分

https://github.com/tusen-ai/naive-ui/issues/3165 和这个应该是同一个需求 刚才贴错链接了

**Comment by muchenfine** [comment]
是的， 我也看到很多人有同样的需求，而且在很多后台系统中，他的确很重要， 希望官方可以考虑

**Comment by Sepush** [comment]
确实是比较常见的需求 我们会想办法支持 团队里已经有 PR 尝试解决了 https://github.com/tusen-ai/naive-ui/pull/3462

**Comment by muchenfine** [comment]
感谢naiveUI
