### ISSUE TITLE
[NInputNumber] Strange loop when @update:value

### ISSUE THREAD

**Issue by vicenterusso** [tusen-ai/naive-ui#3329]
### TuSimple/naive-ui version (版本)
2.25.3

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Tested on Chrome and Firefox

### System and its version (系统及其版本)
Linux Fedora 36

### Reappearance link (重现链接)
https://codesandbox.io/s/gallant-bassi-d5cr5i?file=/src/Demo.vue

### Reappearance steps (重现步骤)
Source:
https://codesandbox.io/s/gallant-bassi-d5cr5i?file=/src/Demo.vue

To reproduce:
1) Open link [ https://d5cr5i.csb.app/ ]
2) Open devtools (sometimes it doesnt work with dev tools not present)
3) Fast click to increase or decrease
4) Loop starts

Video: 
https://i.imgur.com/6RU9Vto.mp4

### Expected results (期望的结果)
Expected no loop behaviour

### Actual results (实际的结果)
Loop starts when fast click

### Remarks (补充说明)
Bug happens from version 2.25.3 to the latest.

**Comment by 07akioni** [comment]
I can't reproduce it but it may be relevant with
 https://github.com/TuSimple/naive-ui/pull/3333

**Comment by OrbisK** [comment]
I managed to repod it, with a macro that presses 30 times (every 2ms).

**Comment by vicenterusso** [comment]
I confirm it's not fixed, version 2.32.1

**Comment by vicenterusso** [comment]
Confirmed: **Fixed**
