### ISSUE TITLE
[Select] Allow to sort the selected options when dragging

### ISSUE THREAD

**Issue by DannyFeliz** [tusen-ai/naive-ui#3341]
### This function solves the problem (这个功能解决的问题)
When multiple options are selected, it would be great to be able to reorder them if we wanted to just drag and drop them instead of carefully selecting them in the order we want.
### Expected API (期望的 API)
Add a `draggable-options` prop to the `NSelect`

```vue
<n-select v-model:value="value" multiple draggable-options :options="options" />
```

Or, if you want to leave the implementation up to the user, expose a slot to control what to display when an option is selected, similar to this https://vue-multiselect.js.org/#sub-custom-option-template

**Comment by 07akioni** [comment]
Not going to support it. At least not soon.

**Comment by DannyFeliz** [comment]
That is understandable; I guess one day we will have one day.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
