### ISSUE TITLE
data table 中当 renderExpand 返回 undefined 时，展开后会出现空白块

### ISSUE THREAD

**Issue by atAurora** [tusen-ai/naive-ui#3373]
### TuSimple/naive-ui version (版本)
2.31.0

### Vue version (Vue 版本)
3.2.13

### Browser and its version (浏览器及其版本)
Chrome(103.0.5060.114)

### System and its version (系统及其版本)
MacOS(11.6)

### Reappearance link (重现链接)
https://github.com/atAurora/naive-ui-datatable-bug

### Reappearance steps (重现步骤)
打开项目，点击 data table 的展开按钮

### Expected results (期望的结果)
renderExpand 并没有返回任何内容，展开后应该不渲染任何内容

### Actual results (实际的结果)
展开后渲染空白块

### Remarks (补充说明)
![screenshot-20220728-142103](https://user-images.githubusercontent.com/57202389/181435497-60c18542-f00e-4ed7-9d53-e28b3c7cd045.png)

**Comment by 07akioni** [comment]
你需要用 expandable 控制行是否可展开

**Comment by atAurora** [comment]
比如以下场景：
展开后的内容仍然是一个 data table，data table 里面的数据可删除
expandable 当 展开的 data table 中没有数据的时候不显示
当把 data table 中的数据全部删除，展开按钮消失，此时最后的状态是展开的，就会有上述空白
expandable确实可以控制行是否展开，那么当expandable消失的时候，是不是下面可展开的内容也随之消失呢？

**Comment by 07akioni** [comment]
> data table，data table 里面的数据可删除
> expandable 当 展开的 data table 中没有数据的时候不显示
> 当把 data table 中的数据全部删除，展开按钮消失，此时最后的状态是展开的，就会有上述空白
> expandable确实可以控制

按照预期是会的

**Comment by atAurora** [comment]
> > data table，data table 里面的数据可删除
> > expandable 当 展开的 data table 中没有数据的时候不显示
> > 当把 data table 中的数据全部删除，展开按钮消失，此时最后的状态是展开的，就会有上述空白
> > expandable确实可以控制
> 
> 按照预期是会的

但是实际上下面可展开的内容并不会随之消失，上述场景下，当expandable消失的时候，下面可展开的内容依然会保持展开状态，此时渲染的就是renderExpand返回的内容，如果返回的是undefined，那么就会如Remarks (补充说明)中图片上那样，渲染一个空白块

**Comment by atAurora** [comment]
![bug-naive-ui](https://user-images.githubusercontent.com/57202389/182593438-75a31545-abbd-4665-b3d7-2635bc8daf68.png)
 图片渲染结果来自https://github.com/atAurora/naive-ui-datatable-bug
@07akioni
