### ISSUE TITLE
【tree】tree组件在使用搜索功能时会造成页面卡顿（数据量稍微大些的情况下）

### ISSUE THREAD

**Issue by duangkey** [tusen-ai/naive-ui#3389]
### TuSimple/naive-ui version (版本)
2.32.0

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
103.0.5060.134

### System and its version (系统及其版本)
window64

### Reappearance link (重现链接)
https://github.com

### Reappearance steps (重现步骤)
1.输入想要搜索的内容
2.观察树结构的反馈

### Expected results (期望的结果)
不影响页面卡顿，搜索无感

### Actual results (实际的结果)
页面卡顿，搜索迟钝

**Comment by 07akioni** [comment]
稍微大指的是多大？

**Comment by 07akioni** [comment]
需要一个复现，我看看大概是什么性能

**Comment by duangkey** [comment]
![freeze-frame](https://user-images.githubusercontent.com/52771631/181924979-aff02b61-0e02-439c-84ae-0bdeec07d2f7.gif)
你好，因数据原因，仅能录制部分内容，如gif，输入闸机，输入框空白的时间为页面卡顿的时长，树的结构为四个层级，总数据量为4500左右；
希望能够满足复现的要求

**Comment by 07akioni** [comment]
> ![freeze-frame](https://user-images.githubusercontent.com/52771631/181924979-aff02b61-0e02-439c-84ae-0bdeec07d2f7.gif) [ ![freeze-frame](https://user-images.githubusercontent.com/52771631/181924979-aff02b61-0e02-439c-84ae-0bdeec07d2f7.gif) ](https://user-images.githubusercontent.com/52771631/181924979-aff02b61-0e02-439c-84ae-0bdeec07d2f7.gif) [ ](https://user-images.githubusercontent.com/52771631/181924979-aff02b61-0e02-439c-84ae-0bdeec07d2f7.gif) 你好，因数据原因，仅能录制部分内容，如gif，输入闸机，输入框空白的时间为页面卡顿的时长，树的结构为四个层级，总数据量为4500左右； 希望能够满足复现的要求

4500 行用了虚拟滚动吗？

**Comment by duangkey** [comment]
> 4500 行用了虚拟滚动吗？

尝试用过，不能解决问题

**Comment by 07akioni** [comment]
> > 4500 行用了虚拟滚动吗？
> 
> 尝试用过，不能解决问题

不能解决问题具体是说什么？还是慢？还是说不适合你的业务场景

**Comment by duangkey** [comment]
> 



> > > 4500 行用了虚拟滚动吗？
> > 
> > 
> > 尝试用过，不能解决问题
> 
> 不能解决问题具体是说什么？还是慢？还是说不适合你的业务场景
还是会卡顿

**Comment by 07akioni** [comment]
最好能给个复现看看
