### ISSUE TITLE
Popover或tooltip在暗黑模式下，提示信息的箭头有一条边框

### ISSUE THREAD

**Issue by maddenBoy** [tusen-ai/naive-ui#3402]
### TuSimple/naive-ui version (版本)
2.32.1

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Chrome（103.0.5060.134）

### System and its version (系统及其版本)
window 11

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/dark/components/popover#Popover-Props

### Reappearance steps (重现步骤)
1、把页签切成暗黑模式或Popover的背景色改成暗色，箭头处会有一条细边框
![image](https://user-images.githubusercontent.com/71129660/182064882-fbbf1d6b-f71f-4523-9553-e054cc301c53.png)

### Expected results (期望的结果)
去掉箭头处的边框

### Actual results (实际的结果)
箭头处显示了边框

**Comment by Nakus0426** [comment]
不在暗黑模式下也有哈哈
![image](https://user-images.githubusercontent.com/41540888/182283774-5ec62d0d-d939-4d00-990c-83c70c9b02b7.png)

**Comment by maddenBoy** [comment]
popover是深色背景就会很明显，但popover有些弹出位置又不会显示
![image](https://user-images.githubusercontent.com/71129660/182284356-12f95074-d260-40f0-b1f3-0daa966a499b.png)

**Comment by 07akioni** [comment]
这个确实是很难处理，之前试过往里走一个像素，但是阴影效果就不好了

**Comment by 07akioni** [comment]
暂时不把这个看作一个 bug，确实可以再想想优化的办法

**Comment by maddenBoy** [comment]
elementui的popover和tooltip没有这种情况，能否有参考价值

**Comment by Innei** [comment]
> 这个确实是很难处理，之前试过往里走一个像素，但是阴影效果就不好了

0.5px 看起来还行？1px 阴影有点断裂了.

```
top: calc(100% - 0.5px)
```

**Comment by amadeus711** [comment]
> > 这个确实是很难处理，之前试过往里走一个像素，但是阴影效果就不好了
> 
> 0.5px 看起来还行？1px 阴影有点断裂了.
> 
> ```
> top: calc(100% - 0.5px)
> ```

Top 这个值理论上是不支持半像素的

**Comment by amadeus711** [comment]
> elementui的popover和tooltip没有这种情况，能否有参考价值

原理不太一样，他们的那个 arrow 不带阴影

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
