### ISSUE TITLE
NTransfer 需要支持 target filter

### ISSUE THREAD

**Issue by ManiaJack** [tusen-ai/naive-ui#3407]
### This function solves the problem (这个功能解决的问题)
可以对 target 部分进行筛选。
旧版 transfer 是支持的。新版 transfer 的 props 可能从旧版 copy 了一部分，所以有 target-filter-placeholder 的 prop，但是并没有得到对应功能的支持
### Expected API (期望的 API)
props: 
filterable: true

和旧版 transfer 一致。

**Comment by 07akioni** [comment]
@amadeus711 这个加一下吧
