### ISSUE TITLE
分页器中每页条数的选择器的位置能否调整位置

### ISSUE THREAD

**Issue by maddenBoy** [tusen-ai/naive-ui#3466]
### TuSimple/naive-ui version (版本)
2.32.2-beta.0

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Chrome（103.0.5060.134）

### System and its version (系统及其版本)
window 11

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/pagination

### Reappearance steps (重现步骤)
分页器中每页条数的选择器位置好像只能在分页器的固定位置展示，能否放到分页器中的任意位置

### Expected results (期望的结果)
期望能把分页器中每页条数的选择的位置放在分页前后缀中

### Actual results (实际的结果)
实际分页器中每页条数的选择器的位置只能按固定位置展示

**Comment by 07akioni** [comment]
任意位置可能有点麻烦，但是感觉可以想办法允许调整
