### ISSUE TITLE
n-textarea: resizing issue 

### ISSUE THREAD

**Issue by OrbisK** [tusen-ai/naive-ui#3479]
### TuSimple/naive-ui version (版本)
2.32.2-beta.0

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
OperaGX LVL4 (core: 89.0.4447.64)

### System and its version (系统及其版本)
Win 11

### Reappearance link (重现链接)
https://codesandbox.io/s/gracious-lumiere-bb7685?file=/src/Demo.vue

### Reappearance steps (重现步骤)
1. Open reprod
2. resize more than one textarea multiple times

### Expected results (期望的结果)
textareas are always resizable.

### Actual results (实际的结果)
at one point some textareas are not resizable anymore

**Comment by 07akioni** [comment]
Is it reproducible out of codesandbox?
I tried to copy demo and reproduce it in local environment but doesn't work.

**Comment by OrbisK** [comment]
I opend a codesandbox, because it appeared in development.
