### ISSUE TITLE
n-select: dropdown and 'input' not styled from peer theme

### ISSUE THREAD

**Issue by OrbisK** [tusen-ai/naive-ui#3493]
### TuSimple/naive-ui version (版本)
2.32.2-beta.0

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
OperaGX LVL4 (core: 89.0.4447.64)

### System and its version (系统及其版本)
win 11

### Reappearance link (重现链接)
https://codesandbox.io/s/laughing-pond-obxd6h?file=/src/Demo.vue

### Reappearance steps (重现步骤)
1. open link
2. open dropdown
3. open select

### Expected results (期望的结果)
same style for select input and dropdown

### Actual results (实际的结果)
select does not apply select input and dropdown stlyes

### Remarks (补充说明)
offtopic: somehow the select highlighting is weired in repro

**Comment by 07akioni** [comment]
use these two

<img width="397" alt="image" src="https://user-images.githubusercontent.com/18677354/184212114-25d9df4e-37d2-4bb5-937f-59bc9c6422db.png">

**Comment by 07akioni** [comment]
<img width="893" alt="image" src="https://user-images.githubusercontent.com/18677354/184212157-fd86f00a-f14e-492c-9e09-c69c3ca1d210.png">

**Comment by OrbisK** [comment]
> <img alt="image" width="893" src="https://user-images.githubusercontent.com/18677354/184212157-fd86f00a-f14e-492c-9e09-c69c3ca1d210.png">

1. why isnt `InternalSelection` and `InternalSelectionMenu` not defaulting to `Input` and `Dropdown`?

2. and whats this weired highlighting of options (hover effect without hover)

**Comment by 07akioni** [comment]
> > <img alt="image" width="893" src="https://user-images.githubusercontent.com/18677354/184212157-fd86f00a-f14e-492c-9e09-c69c3ca1d210.png">
> 
> 1. why isnt `InternalSelection` and `InternalSelectionMenu` not defaulting to `Input` and `Dropdown`? The styles of the selection tags (if multiple) are styled from `Tag`.
> 2. and whats this weired highlighting of options (hover effect without hover)
> 3. some props are not overridable (`InternalSelection`) like boxshadows (i can open seperate issue?)

1. Input & Internal has many distinctions which makes impossible to merge the style.
2. Maybe you have value set to `undefined`
3. Box shadow is overridable:
<img width="656" alt="image" src="https://user-images.githubusercontent.com/18677354/184541218-360ffb34-3ab6-47af-824e-07b7d85b49ba.png">

**Comment by OrbisK** [comment]
> > > <img alt="image" width="893" src="https://user-images.githubusercontent.com/18677354/184212157-fd86f00a-f14e-492c-9e09-c69c3ca1d210.png">
> > 
> > 
> > 
> > 1. why isnt `InternalSelection` and `InternalSelectionMenu` not defaulting to `Input` and `Dropdown`? The styles of the selection tags (if multiple) are styled from `Tag`.
> > 2. and whats this weired highlighting of options (hover effect without hover)
> > 3. some props are not overridable (`InternalSelection`) like boxshadows (i can open seperate issue?)
> 
> 1. Input & Internal has many distinctions which makes impossible to merge the style.
> 2. Maybe you have value set to `undefined`
> 3. Box shadow is overridable:
> 
> <img alt="image" width="656" src="https://user-images.githubusercontent.com/18677354/184541218-360ffb34-3ab6-47af-824e-07b7d85b49ba.png">

I think I expressed myself incorrectly.

2. 
![image](https://user-images.githubusercontent.com/37191683/184605851-d1af5900-078c-4f70-b53f-a27bbcf49291.png)

No value is set to `undefined` (see sandbox)

3. box shadow override is there, but its not working!

**Comment by 07akioni** [comment]
> https://codesandbox.io/s/laughing-pond-obxd6h?file=/src/Demo.vue

For 2 you should provide `value` field not `key` or use `value-field="key"`

<img width="590" alt="image" src="https://user-images.githubusercontent.com/18677354/184930778-c17c83cb-0ee7-4bfb-8865-a103417bf15c.png">

For 3 I will check
