### ISSUE TITLE
希望能为 NTree 组件的 render-switcher-icon API 传入 option 参数

### ISSUE THREAD

**Issue by qingruikz** [tusen-ai/naive-ui#3495]
### This function solves the problem (这个功能解决的问题)
根据已关闭的 [#1973](https://github.com/tusen-ai/naive-ui/pull/1973#issuecomment-1003743131)，在 2.24.0 中增加了NTree 组件的 render-switcher-icon API，但该函数不像 `renderPrefix` 等，没有传入 option 参数。

但实际有需要传参的场景！
当为 NTree 绑定 `expanded-keys` 属性后，NTree 组件处于受控模式下，此时点击展开开关的图标将不起作用，此时如果需要在受控模式下实现展开开关的功能的话，需要获取点击的节点信息，因此需要有传参的 `render-switcher-icon` API 而不是现在的 `() => VNodeChild`。

### Expected API (期望的 API)
希望为 `render-switcher-icon` API 传入参数：
- 类似 `renderPrefix` 的 `(info: { option: TreeOption, checked: boolean, selected: boolean }) => VNodeChild`
- 或者按类似[#1973 原来方案](https://github.com/tusen-ai/naive-ui/commit/ec83c9360057835388331da780c611a1d7f3f1b5?diff=unified#)，仅把 `rawNode` 作为 option 传入即可

**Comment by Jiangk1996** [comment]
render-switcher-icon 可以支持自定义展开和折叠状态的icon吗？

**Comment by Liubasara** [comment]
render-switcher-icon 是否可以获取到当前这个根节点的对应 option 以及其下的 children 列表？

**Comment by hiwurun** [comment]
附议!
