### ISSUE TITLE
Message组件自定义主题（themeOverrides）不生效

### ISSUE THREAD

**Issue by XiaoDaiGua-Ray** [tusen-ai/naive-ui#3496]
### TuSimple/naive-ui version (版本)
2.30.5

### Vue version (Vue 版本)
3.2.36

### Browser and its version (浏览器及其版本)
104.0.5112.79（正式版本） (arm64)

### System and its version (系统及其版本)
MacOS（12.4）

### Reappearance link (重现链接)
https://naive-ui.github.io/issue-helper/?lang=en-US（暂无）

### Reappearance steps (重现步骤)
1. 自定义 themeOverrides 主题
2. 在 App.tsx 中的最外层引入 <NConfigProvider /> 组件并且引入 themeOverrides 主题
3. 配置参数fontSize: '22px', iconSize: '28px', closeIconSize: '24px',

### Expected results (期望的结果)
1. 主题配置应该对应生效

### Actual results (实际的结果)
1. 主题配置后，并没生效

**Comment by 07akioni** [comment]
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/18677354/184383881-817d02d3-e8ba-44c2-a3f7-ca3df9e705fb.png">

**Comment by XiaoDaiGua-Ray** [comment]
您好，我按照您的方式进行修改，但是还是依旧不能正常生效
<img width="530" alt="image" src="https://user-images.githubusercontent.com/51957438/185348784-04fbdb65-fb6b-466f-b3f8-a8eada642cb2.png">
![image](https://user-images.githubusercontent.com/51957438/185348830-05982d9e-55c0-4911-a9e4-c9ca21ad7a15.png)

**Comment by XiaoDaiGua-Ray** [comment]
![](https://user-images.githubusercontent.com/51957438/185348784-04fbdb65-fb6b-466f-b3f8-a8eada642cb2.png)


![](https://user-images.githubusercontent.com/51957438/185348830-05982d9e-55c0-4911-a9e4-c9ca21ad7a15.png)
您好，我按照您的方式进行修改，但是还是依旧不能正常生效

**Comment by XiaoDaiGua-Ray** [comment]
> <img alt="image" width="1010" src="https://user-images.githubusercontent.com/18677354/184383881-817d02d3-e8ba-44c2-a3f7-ca3df9e705fb.png">



> <img alt="图片" width="1010" src="https://user-images.githubusercontent.com/18677354/184383881-817d02d3-e8ba-44c2-a3f7-ca3df9e705fb.png">

您好，我按照您的方式修改，依旧不生效
![image](https://user-images.githubusercontent.com/51957438/185352117-88253db6-fa13-4c1f-8a6f-38386758a8fa.png)
<img width="588" alt="image" src="https://user-images.githubusercontent.com/51957438/185352148-9d2e9c44-f453-4b1b-bc53-890a652bc93d.png">

**Comment by XiaoDaiGua-Ray** [comment]
您好，这是我全部的代码截图，不仅仅是在全局修改了provider，也在message provder进行了修改，同样是无法生效。感谢您的回复



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月18日(星期四) 晚上11:24
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tusen-ai/naive-ui] Message组件自定义主题（themeOverrides）不生效 (Issue #3496)





        
您好，我按照您的方式修改，依旧不生效  
  
我感觉你呼出来的这个 message 不一定是 provider 提供的那个，你最好给一个完整的复现，不然的话我们没有办法猜出来原因

**Comment by SuperManito** [comment]
> > > <img alt="image" width="1010" src="https://user-images.githubusercontent.com/18677354/184383881-817d02d3-e8ba-44c2-a3f7-ca3df9e705fb.png">
> > 
> > 
> > > <img alt="图片" width="1010" src="https://user-images.githubusercontent.com/18677354/184383881-817d02d3-e8ba-44c2-a3f7-ca3df9e705fb.png">
> > 
> > 
> > 您好，我按照您的方式修改，依旧不生效 ![image](https://user-images.githubusercontent.com/51957438/185352117-88253db6-fa13-4c1f-8a6f-38386758a8fa.png) <img alt="image" width="588" src="https://user-images.githubusercontent.com/51957438/185352148-9d2e9c44-f453-4b1b-bc53-890a652bc93d.png">
> 
> 我感觉你呼出来的这个 message 不一定是 provider 提供的那个，你最好给一个完整的复现，不然的话我们没有办法猜出来原因

您好，我是新手不方便创建codesandbox复现，故特此请教下我在使用中遇到的一个问题

主题切换至 darkTheme 后很多var变量加载不正常，并且使用themeOverrides全局覆盖也没有效果（例如 `Menu.itemColorHover` ），仅 `common.primaryColor` 等少数主要变量可以有效更改，下面是切换主题后的前后对比

![image](https://user-images.githubusercontent.com/68613938/215404411-93361714-dccb-4887-8fe8-bc1b979109c0.png)
![image](https://user-images.githubusercontent.com/68613938/215404452-2d535100-d3b2-41d1-a820-e79e2db7a498.png)

我所使用的原生项目是awesome里面的 [zmtlwzy-admin](https://github.com/naive-ui/awesome-naive/blob/8484cc9a64eb6fd01fe666058fd8f0aabfaacf0d/README.zh-CN.md?plain=1#L39)，该项目同样存在上述问题，方便帮忙分析下原因吗？

项目地址：https://github.com/zmtlwzy/zmtlwzy-admin
远程预览：https://zmtlwzy-admin.netlify.app/

https://github.com/zmtlwzy/zmtlwzy-admin/blob/a7f016e6dec30950b1fdc86897534a76e680dd1c/src/store/modules/app.ts#L54

我不清楚是否与 useThemeVars 组件有关，themeOverrides数据替换正常并且加载到了 `n-config-provider` 中

![image](https://user-images.githubusercontent.com/68613938/215405195-0782c852-0d10-4b5c-bbf7-25afc4aebe90.png)

期待回复，感谢
