### ISSUE TITLE
n-select 动态创建选项后会触发 on:update-value 事件，在此事件中我又过滤掉了创建的选项，但是视图中的 option 没有发生变化

### ISSUE THREAD

**Issue by Zheng-Changfu** [tusen-ai/naive-ui#3498]
### TuSimple/naive-ui version (版本)
2.32.1

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Chrome(104.0.5112.81)

### System and its version (系统及其版本)
windows 10

### Node version (Node 版本)
16.15.1

### Reappearance link (重现链接)
https://codesandbox.io/s/damp-wind-jjj8vm?file=/src/App.vue

### Reappearance steps (重现步骤)
1. 随便输入一个值，按下回车
2. 此时页面中的下拉选项中出现了添加的值
3. 但是我打印 v-model:value 绑定的值中没有添加的值

### Expected results (期望的结果)
希望动态创建选项的时候，外层 v-model:value 数据进行同步，因为我可能会在 on:update-value 中根据一些规则来判断是否可以添加选项

### Actual results (实际的结果)
实际上外层 v-model:value 的数据没有同步视图

### Remarks (补充说明)
可能 n-select 内部自己维护了一份数据，没有和外部数据同步

**Comment by 07akioni** [comment]
首先 options 是不可能改变的，组件是不能擅自修改用户传入的值的

**Comment by 07akioni** [comment]
是否允许创建这个有点复杂，哪怕说不能创建也要给用户点交互，简单禁止这个做法不是很完善，需要想一想完善的解决方案

**Comment by zhuangState** [comment]
我觉得可能需要把用户添加的数据分离出来，userAddList。然后添加到列表前通过一个钩子函数用于加工数据和决定是否需要添加到userAddList。

**Comment by 07akioni** [comment]
> 我觉得可能需要把用户添加的数据分离出来，userAddList。然后添加到列表前通过一个钩子函数用于加工数据和决定是否需要添加到userAddList。

如果这么搞的话不如全都交给用户

**Comment by Zheng-Changfu** [comment]
是不是可以考虑在来一个 v-model:options="options" 变成受控模式

**Comment by Zheng-Changfu** [comment]
我目前的做法就是 将 select 变成可搜索的，但是绑定回车事件，在回车事件中自己做相关的业务处理

**Comment by 07akioni** [comment]
> 是 将 select 变成可搜索的，但是绑定回车事件，在回车事件中

我其实也在想把这个事件暴露出去

**Comment by Zheng-Changfu** [comment]
现在已经有了 :options 选项，那如果在向外暴露一个事件的话，是不是可以考虑 做一个 v-model:option 的设计来代替 :options 和事件的 api？

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
