### ISSUE TITLE
nuxt3工程报错：CSSRender is not a function

### ISSUE THREAD

**Issue by mohong** [tusen-ai/naive-ui#3506]
### TuSimple/naive-ui version (版本)
2.32.2-beta.0

### Vue version (Vue 版本)
3.2.37

### Nuxt version(Nuxt版本)
3.0.0-rc.8

### Browser and its version (浏览器及其版本)
Chrome(104.0.5112.79)

### System and its version (系统及其版本)
MacOS(12.4 (21F79))

### Node version (Node 版本)
14.17.3

### Reappearance link (重现链接)
https://github.com/mohong/nuxt-app

### Reappearance steps (重现步骤)
1、npm run dev模式下可以正常访问；
2、npm run build可以正常打包；
3、npm run preview，访问，浏览器报“CSSRender is not a function”。

### Expected results (期望的结果)
npm run build之后可以正常preview。

### Actual results (实际的结果)
浏览器报“CSSRender is not a function”。

**Comment by cinob** [comment]
You can temporarily add 'css-render' and '@css-render/plugin-bem' to the 'transpile'

**Comment by mohong** [comment]
> You can temporarily add 'css-render' and '@css-render/plugin-bem' to the 'transpile'

It`s works, thanks!
