### ISSUE TITLE
n-data-table横轴滚动问题

### ISSUE THREAD

**Issue by PZ-18664918826** [tusen-ai/naive-ui#3511]
### This function solves the problem (这个功能解决的问题)
如果需求是很多列的数据不是固定的，又不想固定宽造成列的数据省略，只好不设定宽，又无法知道每列的宽度，scroll-x需要自己进行设定，如果某列数据很多，该列的高度会很高，造成改行的高度一样高。

### Expected API (期望的 API)
希望除掉scroll-x，只需设定fixed即可，如果数据量很多，表格自动滚动，列的宽度自动撑开而不是撑高

**Comment by PZ-18664918826** [comment]
![1660551571316](https://user-images.githubusercontent.com/64340432/184601077-1a85bc2c-dc07-4111-84ec-25905156246d.jpg)

**Comment by kiccer** [comment]
建议还是增加一个自动调整的功能，出现某个单元格特别长的情况，可以自行添加 ellipsis 和 maxWidth 来解决。
