### ISSUE TITLE
NFormItem Label Type support Object

### ISSUE THREAD

**Issue by KAMATILinc** [tusen-ai/naive-ui#3521]
### TuSimple/naive-ui version (版本)
2.32.2-beta.0

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Edge

### System and its version (系统及其版本)
Windows 11

### Reappearance link (重现链接)
https://codepen.com

### Reappearance steps (重现步骤)
https://prnt.sc/061v0DBQsdnv

### Expected results (期望的结果)
Add support for Object in Label prop, to render h()

### Actual results (实际的结果)
Invalid prop: type check failed for prop "label". Expected String with value "[object Object]", got Object

**Comment by amadeus711** [comment]
![image](https://user-images.githubusercontent.com/46394163/184903731-b15fbb08-9652-4808-a99f-d9c9782514c1.png)

**Comment by KAMATILinc** [comment]
@amadeus711 Yes, but the label currently support just type 'String' not 'Object' and the render function h() returns Object
so when using h() in label i got a warning : Invalid prop: type check failed for prop "label". Expected String, got Object

**Comment by 07akioni** [comment]
You should write like this
```
{
  label: () => h(NSpace, ...
```
