### ISSUE TITLE
Support Spacer in `<NMenu />`

### ISSUE THREAD

**Issue by equt** [tusen-ai/naive-ui#3524]
### This function solves the problem (这个功能解决的问题)

To achieve effects like `justify-content: space-between` or arbitrary length of whitespace.

### Expected API (期望的 API)

Almost the same as `MenuDivider` but without the default background.

https://github.com/tusen-ai/naive-ui/blob/9088b114c69d7311c617c95da115f7a7345095ba/src/menu/src/MenuDivider.tsx#L4-L15

**Comment by equt** [comment]
(please feel free to assign it me if it's worth to have)

**Comment by 07akioni** [comment]
Maybe we can expose some new theme overrides to support it.
