### ISSUE TITLE
按钮点击Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by zhoufanglu** [tusen-ai/naive-ui#3530]
### TuSimple/naive-ui version (版本)
2.30.8

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
win7

### Node version (Node 版本)
16

### Reappearance link (重现链接)
-

### Reappearance steps (重现步骤)
```js
setup() {
    const openAddDialog = () => {
      console.log('open click')
    }
    const projectDialogRef = ref(null)
    // @ts-ignore
    console.log(15, projectDialogRef.value)
    return {
      openAddDialog,
      projectDialogRef
    }
  },
  render() {
    //@ts-ignore
    return (
      <div class={styles['project-list']}>
        <div class={styles['filter']}>
          <NButton type='info' size={'small'} onClick={this.openAddDialog}>
            <NIcon class={styles.icon}>
              <PlusOutlined />
            </NIcon>
            新增项目
          </NButton>
        </div>
        {/*项目弹窗*/}
        <ProjectDialog>
          {{
            bar: () => <span>我是bar</span>
          }}
        </ProjectDialog>
      </div>
    )
  }
```

### Expected results (期望的结果)
点击事件`openAddDialog `不报错

### Actual results (实际的结果)
点击事件`openAddDialog`报错Unable to preventDefault inside passive event listener invocation.

**Comment by 07akioni** [comment]
你看看哪个库报的吧，是不是装了什么库把所有的事件都搞成 passive 了

**Comment by 07akioni** [comment]
passive 的事件应该只有 wheel、touch 之类的

**Comment by zhoufanglu** [comment]
> 

就是naive-ui库的button报错了, 我普通按钮事件没问题

**Comment by 07akioni** [comment]
> > 
> 
> 就是naive-ui库的button报错了, 我普通按钮事件没问题

之前我也见人提过类似的问题，最终发现是他自己装的库导致的。有仓库的复现最好，没有的话可以贴个 lockfile 我看看。

**Comment by zhoufanglu** [comment]
> > > 
> > 
> > 
> > 就是naive-ui库的button报错了, 我普通按钮事件没问题
> 
> 之前我也见人提过类似的问题，最终发现是他自己装的库导致的。有仓库的复现最好，没有的话可以贴个 lockfile 我看看。

感谢回答，找到问题了，使用了`default-passive-events`这个库导致的
