### ISSUE TITLE
DataTable has no horizontal scroll bar when set "max-height" prop

### ISSUE THREAD

**Issue by mazhewei** [tusen-ai/naive-ui#3535]
### TuSimple/naive-ui version (版本)
2.32.1

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Chrome(104.0.5112.81)

### System and its version (系统及其版本)
Windows 10

### Node version (Node 版本)
v14.17.0

### Reappearance link (重现链接)
https://codesandbox.io/s/funny-leakey-kfko0u

### Reappearance steps (重现步骤)
1. define columns with width prop(so table will show horizontal scroll bar)
2. add "max-height" prop to table component
3. table show vertical scroll bar(as expected), but horizontal scroll bar disappear

actually i can use middle mouse button to control horizontal scroll bar, it just no show.

### Expected results (期望的结果)
horizontal scroll bar show correctly, when "max-height" prop has been set

### Actual results (实际的结果)
no horizontal scroll bar show, when "max-height" prop has been set

**Comment by 07akioni** [comment]
ScrollX is not set. This is the actual reason.
