### ISSUE TITLE
scrollbar

### ISSUE THREAD

**Issue by Yehudic** [tusen-ai/naive-ui#3537]
### This function solves the problem (这个功能解决的问题)
在scrollbar只有横向滚动条时，希望scrollbar可以通过鼠标滚轮控制左右移动
### Expected API (期望的 API)
添加一个boolean属性 鼠标滚轮是否可以控制横向滚动条

**Comment by 07akioni** [comment]
和原生 DOM 行为一致，按住 shift 就能滚动

**Comment by wj007881** [comment]
scrollbar太细，不容易操作，希望有个参数可以设置大小

**Comment by wj007881** [comment]
> 和原生 DOM 行为一致，按住 shift 就能滚动

scrollbar太细，不容易操作，希望有个参数可以设置大小
