### ISSUE TITLE
Radio, RadioButton and RadioGroup should accept Boolean as value

### ISSUE THREAD

**Issue by M1CK431** [tusen-ai/naive-ui#3540]
### This function solves the problem (这个功能解决的问题)
I would like to use `Radio`, `RadioButton` and `RadioGroup` to build a `true`/`false` switch (it looks better than the dedicated `Switch` component in my use case). Of course it's already working but raise a warning in browser console. In addition, I can't see any reason to forbid a `Boolean` as value here. What do you think?
### Expected API (期望的 API)
No change is required at API, except that the existing `value` prop should just accept a `Boolean` in addition of `String` and `Number`.

**Comment by Sepush** [comment]
@equt 不需要 label 不需要打这么细 太多label 反而不清晰了

**Comment by 07akioni** [comment]
> @equt 不需要 n-radio label 太多label 反而不清晰了

For component that has too many issues, I think we can add a tag. Currently I think the only one is data table.

cc @equt  @Sepush

**Comment by M1CK431** [comment]
It's soooo fast! :rocket:  Thanks a lot!
