### ISSUE TITLE
SSR: NuxtJS 3.0.0-rc.8 Exists is not defined (Using a context component)

### ISSUE THREAD

**Issue by brys0** [tusen-ai/naive-ui#3546]
### TuSimple/naive-ui version (版本)
2.32.1

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Not affiliable

### System and its version (系统及其版本)
Windows 11 10.0.22621 Build 22621

### Node version (Node 版本)
v16.13.0

### Reappearance link (重现链接)
https://github.com/brys0/naive-ui-nuxt-demo

### Reappearance steps (重现步骤)
`pnpm install --shamefully-hoist`
`pnpm build`
edit `.output/server/chunks/server.mjs`
replace 
```js
import CSSRender, { hash } from 'css-render';
import BEMPlugin from '@css-render/plugin-bem';
```
with
```js
import { hash,CssRender as CSSRender } from 'css-render';
import { plugin as BEMPlugin} from '@css-render/plugin-bem';
```

pnpm preview
go to http://localhost:3000

In console see error: ReferenceError: exists is not defined

### Expected results (期望的结果)
It should either import exists or find another method of using this

### Actual results (实际的结果)
It breaks on not modifying css render AND trying to use context api in naive

**Comment by Yorksh1re** [comment]
+1

**Comment by itmanyong** [comment]
+1

**Comment by 07akioni** [comment]
> +1

You can add broken to `transpile` in nuxt config as a temporal solution.

**Comment by 07akioni** [comment]
The bug is fixed in latest version.
