### ISSUE TITLE
Provides a palette to easily switch themes

### ISSUE THREAD

**Issue by sky124380729** [tusen-ai/naive-ui#3548]
### This function solves the problem (这个功能解决的问题)
Currently, modifying primaryColor also requires synchronously modifying series values ​​such as primaryColorHover. I hope to provide a js method to automatically generate the corresponding series values, similar to the generate method of @ant-design/colors
### Expected API (期望的 API)
```
import { generate, presetPalettes } from 'naive-ui/colors'

const baseColor = '#DC0000'
const {hoverColor, pressedColor, supplColor} = generate(baseColor)

const themeOverrides: GlobalThemeOverrides = {
	common: {
		primaryColor:  baseColor,
		primaryColorHover:  hoverColor,
                primaryColorPressed: pressedColor,
                primaryColorSuppl: supplColor
	}
}
```

**Comment by 07akioni** [comment]
I think it's not hard for user to implement one, so we won't provide it in short term.

**Comment by sky124380729** [comment]
Well, I thought the source series was also compiled via less or sass. By reading the source code, it is found that it is native css.
