### ISSUE TITLE
通知类型的组件优化

### ISSUE THREAD

**Issue by wyswill** [tusen-ai/naive-ui#3551]
### This function solves the problem (这个功能解决的问题)
在root 组件中不再需要使用provider类型的组件包裹子组件。在任何.vue组件或是.js/ts文件中可以随时进行通知。
eg: 在同一的接口请求处理函数中可以统一处理各种通知。
### Expected API (期望的 API)
cosnt note = useNotification(); // or useMesage()
note[  note type ]({ message:'' your message ' })

**Comment by equt** [comment]
可以参考 [在 `setup` 外使用](https://www.naiveui.com/zh-CN/os-theme/components/message#%E5%9C%A8-setup-%E5%A4%96%E4%BD%BF%E7%94%A8) 这一节进行设置。
