### ISSUE TITLE
 [ERROR] [plugin vite:dep-scan] Missing "./es/_mixins" export in "naive-ui" package

### ISSUE THREAD

**Issue by zhoufanglu** [tusen-ai/naive-ui#3553]
### TuSimple/naive-ui version (版本)
2.32.2

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
89

### System and its version (系统及其版本)
win10

### Node version (Node 版本)
16

### Reappearance link (重现链接)
--
### Reappearance steps (重现步骤)
naive-ui版本 升级 2.30 -> 2.32.2， 然后报错

### Expected results (期望的结果)
正常运行

### Actual results (实际的结果)
 [ERROR] [plugin vite:dep-scan] Missing "./es/_mixins" export in "naive-ui" package

**Comment by 07akioni** [comment]
你是不是在某些源代码里直接引了 es/_mixins 的东西？

**Comment by zhoufanglu** [comment]
> 你是不是在某些源代码里直接引了 es/_mixins 的东西？如果是的话应该尽量从统一入口引入

**Comment by zhoufanglu** [comment]
> 你是不是在某些源代码里直接引了 es/_mixins 的东西？如果是的话应该尽量从统一入口引入

我看到在某些组件内是引入了`es/_mixins`， 目前这个导致打不了包
![image](https://user-images.githubusercontent.com/24451091/186602945-30b03cc8-4c0d-4868-9597-7b80a23554cf.png)

**Comment by 07akioni** [comment]
好多组件，指的是？你用了什么模板项目吗？

**Comment by zhoufanglu** [comment]
> 好多组件，指的是？你用了什么模板项目吗？

https://github.com/apache/dolphinscheduler/tree/dev/dolphinscheduler-ui  用的这个前端改的，项目里引用到了这个，导致打包报错
![image](https://user-images.githubusercontent.com/24451091/186797049-30ef18a1-8799-4bd4-bce0-89591d9f7b27.png)

**Comment by 07akioni** [comment]
> > 好多组件，指的是？你用了什么模板项目吗？
> 
> https://github.com/apache/dolphinscheduler/tree/dev/dolphinscheduler-ui 用的这个前端改的，项目里引用到了这个，导致打包报错 ![image](https://user-images.githubusercontent.com/24451091/186797049-30ef18a1-8799-4bd4-bce0-89591d9f7b27.png)

这个未来会提供一个公开的 useFormItem，之前这种用法属于使用了内部 API，你可以暂时锁定一下 naive 的版本。2.32.1 或者之前的没有这个问题。

**Comment by songjianet** [comment]
> > > 好多组件，指的是？你用了什么模板项目吗？
> > 
> > 
> > https://github.com/apache/dolphinscheduler/tree/dev/dolphinscheduler-ui 用的这个前端改的，项目里引用到了这个，导致打包报错 ![image](https://user-images.githubusercontent.com/24451091/186797049-30ef18a1-8799-4bd4-bce0-89591d9f7b27.png)
> 
> 这个未来会提供一个公开的 useFormItem，之前这种用法属于使用了内部 API，你可以暂时锁定一下 naive 的版本。2.32.1 或者之前的没有这个问题。

@zhoufanglu 不好意思对你造成了一定的影响，这个后续naive提供公开的useFormItem后，dolphinscheduler对应也会修改这四处引用

**Comment by songjianet** [comment]
> > 
> 
> > > > > 好多组件，指的是？你用了什么模板项目吗？
> > > > 
> > > > 
> > > > https://github.com/apache/dolphinscheduler/tree/dev/dolphinscheduler-ui 用的这个前端改的，项目里引用到了这个，导致打包报错 ![image](https://user-images.githubusercontent.com/24451091/186797049-30ef18a1-8799-4bd4-bce0-89591d9f7b27.png)
> > > 
> > > 
> > > 这个未来会提供一个公开的 useFormItem，之前这种用法属于使用了内部 API，你可以暂时锁定一下 naive 的版本。2.32.1 或者之前的没有这个问题。
> > 
> > 
> > @zhoufanglu 不好意思对你造成了一定的影响，这个后续naive提供公开的useFormItem后，dolphinscheduler对应也会修改这四处引用
> 
> 没关系。目前我把版本锁定了2.30， 然后改成`import { useFormItem } from 'naive-ui/lib/_mixins'`这个，暂时解决了问题，后续有问题我在看看

嗯嗯，可以先按照作者的思路，暂时锁一下naive版本，后续在进行处理

**Comment by 07akioni** [comment]
暂时移除了 package.json 重的 exports 字段，这个兼容性确实有点差，会导致一些很难解决的问题。这个问题也不存在了
