### ISSUE TITLE
[image] Allow to zoom in/out with the mouse scroll wheel in preview

### ISSUE THREAD

**Issue by DannyFeliz** [tusen-ai/naive-ui#3573]
### This function solves the problem (这个功能解决的问题)
The only way to zoom in/out when you're viewing the image preview is by clicking the amplifier icons in the toolbar, it would be nice if we could use the mouse scroll wheel to zoom in/out when the mouse is hoving the preview.
### Expected API (期望的 API)
I feel this behavior can be the default but can be something like this.

```vue
 <n-image src="https://my-image.jpeg" use-mouse-wheel />
```

The Ant.design team has this by default in their [Image](https://ant.design/components/image) component.

**Comment by jahnli** [comment]
https://github.com/tusen-ai/naive-ui/issues/3902

Seems to be there already
