### ISSUE TITLE
文档中form表单的异步验证示例代码缺少组件

### ISSUE THREAD

**Issue by BertonWalker** [tusen-ai/naive-ui#3574]
### TuSimple/naive-ui version (版本)
2.32.2

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
chrome103

### System and its version (系统及其版本)
MacOS15.1

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/form

### Reappearance steps (重现步骤)
复制demo的代码

### Expected results (期望的结果)
正常运行

### Actual results (实际的结果)
提示缺少<n-message-provider>节点

### Remarks (补充说明)
期望文档中实例代码补充n-message-provider

**Comment by amadeus711** [comment]
没理解你的意思，官网的异步验证示例看起来没问题，请提供更多报错信息或最小实现

**Comment by Sepush** [comment]
文档中又很多的 demo 都写的话过于麻烦，你可以点进 codesanbox 查看 App.vue

**Comment by BertonWalker** [comment]
> 

可示例代码中应该保留当前实例可运行的代码吧，而不是报错

**Comment by Sepush** [comment]
> 

https://www.naiveui.com/zh-CN/os-theme/components/message

**Comment by 07akioni** [comment]
> > 
> 
> 可示例代码中应该保留当前实例可运行的代码吧，而不是报错

Provider 会限制 Demo 的写法，要么把一个 SFC 写得很复杂，要么至少需要两个文件才能写明白。权衡的结果是使用现在的方法，如果不用 message 就只能 alert 了
