### ISSUE TITLE
nuxt preview error

### ISSUE THREAD

**Issue by sunshineroper** [tusen-ai/naive-ui#3576]
### TuSimple/naive-ui version (版本)
2.32.2

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
苹果系统

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/docs/ssr

### Reappearance steps (重现步骤)
Use versions:
```
"naive-ui": "^2.32.2"
"@css-render/vue3-ssr": "^0.15.11"
```
Configure as documented:
https://www.naiveui.com/zh-CN/os-theme/docs/ssr
const lifecycle = process.env.npm_lifecycle_event
```js
vite: {
    optimizeDeps: {
      include:
        process.env.NODE_ENV === 'development'
          ? ['naive-ui', 'vueuc', 'date-fns-tz/esm/formatInTimeZone']
          : []
    }
  },
  build: {
    transpile:
      lifecycle === 'build' || lifecycle === 'generate' ? ['naive-ui',
      'vueuc',
      '@css-render/vue3-ssr',
      '@juggle/resize-observer','element-plus'] : ['@juggle/resize-observer']
  },

```
### Expected results (期望的结果)
The display is normal in development mode, npm run build After running the npm run preview, an error is reported TypeError: BemPlugin is not a function

### Actual results (实际的结果)
TypeError: BemPlugin is not a function

**Comment by zhangzhibang0309** [comment]
这里我也遇到了问题，请问有同学发现解决方案吗？

**Comment by 07akioni** [comment]
可以先把报错的库加入 transpile

**Comment by 07akioni** [comment]
这个问题会发版解决

**Comment by 07akioni** [comment]
BemPlugin 报错的问题已经解决了，现在是 nuxt 自己那个莫名其妙的转换会出问题了
