### ISSUE TITLE
使用Nuxt3，Pnpm Monorepo，安装Naive之后，Vite构建速度变慢。

### ISSUE THREAD

**Issue by zhangzhibang0309** [tusen-ai/naive-ui#3579]
### TuSimple/naive-ui version (版本)
2.32.2

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Chrome

### System and its version (系统及其版本)
Windows11

### Node version (Node 版本)
16

### Reappearance link (重现链接)
https://github.com/OrangeSiteDeveloper/OrangeLanding

### Reappearance steps (重现步骤)
package.json中添加naive依赖，启动项目，Vite构建速度变慢。

### Expected results (期望的结果)
引入Naive后Vite构建速度不应该变慢。

### Actual results (实际的结果)
Vite构建速度变慢很多，甚至到达一分钟。

**Comment by sunshineroper** [comment]
刚刚遇到同样的问题 正准备提交issue, 等一波官方

**Comment by 07akioni** [comment]
可以参考这个 issue，需要你做一些配置

https://github.com/07akioni/naive-ui-nuxt-demo/issues/6
