### ISSUE TITLE
DataTable组件中分页配置itemCount不起作用？

### ISSUE THREAD

**Issue by dajun1230** [tusen-ai/naive-ui#3582]
### TuSimple/naive-ui version (版本)
2.32.1

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
最新版本

### System and its version (系统及其版本)
最新版本

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/pagination#Pagination-Props

### Reappearance steps (重现步骤)
<n-data-table
        bordered
        :columns="columns"
        :data="userList"
        :pagination="paginationReactive"
      />

setup中：

 const userList = ref<User[]>([]);
  const currUser = ref<User | null>(null);
  const paginationReactive = reactive({
    page: 1,
    pageSize: 10,
    itemCount: 50,
    showSizePicker: true,
    // showQuickJumper: true,
    pageSizes: [5, 10, 20, 50, 100],
    onChange: (page: number) => {
      paginationReactive.page = page;
      initData();
    },
    onUpdatePageSize: (pageSize: number) => {
      paginationReactive.pageSize = pageSize;
      paginationReactive.page = 1;
      initData();
    }
  })

### Expected results (期望的结果)
期望能正常显示

### Actual results (实际的结果)
配置了 itemCount的值之后，未能按照正常显示有多少页。

**Comment by dajun1230** [comment]
<n-data-table
        bordered
        :columns="columns"
        :data="userList"
        :pagination="paginationReactive"
      />

**Comment by dajun1230** [comment]
<n-data-table
        bordered
        :columns="columns"
        :data="userList"
        :pagination="paginationReactive"
      />

**Comment by dajun1230** [comment]
<n-data-table
        bordered
        :columns="columns"
        :data="userList"
        :pagination="paginationReactive"
      />

**Comment by 07akioni** [comment]
比如你传了 100 条 data，然后告诉 pagination 有 50 条，DataTable 会使用 100 条。

**Comment by dajun1230** [comment]
意思是 DataTable 的分页显示数量的判断依旧是根据传入的 data 对应的值的长度所决定的是吗？ 跟像上述一样传入的 itemCount 没有任何关系，是这个意思吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月24日(星期三) 晚上10:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tusen-ai/naive-ui] DataTable组件中分页配置itemCount不起作用？ (Issue #3582)





 
比如你传了 100 条 data，然后告诉 pagination 有 50 条，DataTable 会使用 100 条。

**Comment by 07akioni** [comment]
> 意思是 DataTable 的分页显示数量的判断依旧是根据传入的 data 对应的值的长度所决定的是吗？ 跟像上述一样传入的 itemCount 没有任何关系，是这个意思吗？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年8月24日(星期三) 晚上10:45 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [tusen-ai/naive-ui] DataTable组件中分页配置itemCount不起作用？ (Issue #3582) 比如你传了 100 条 data，然后告诉 pagination 有 50 条，DataTable 会使用 100 条。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

是的，否则的话会出现更麻烦的问题

**Comment by dajun1230** [comment]
好的，谢谢， 那我还是不用内嵌的吧，单独用 分页组件，谢谢了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月24日(星期三) 晚上10:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tusen-ai/naive-ui] DataTable组件中分页配置itemCount不起作用？ (Issue #3582)





  
意思是 DataTable 的分页显示数量的判断依旧是根据传入的 data 对应的值的长度所决定的是吗？ 跟像上述一样传入的 itemCount 没有任何关系，是这个意思吗？
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2022年8月24日(星期三) 晚上10:45 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [tusen-ai/naive-ui] DataTable组件中分页配置itemCount不起作用？ (Issue #3582) 比如你传了 100 条 data，然后告诉 pagination 有 50 条，DataTable 会使用 100 条。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
是的，否则的话会出现更麻烦的问题
