### ISSUE TITLE
轮播图自定义dots样式后无法响应鼠标经过指示点切换

### ISSUE THREAD

**Issue by chaoliu03** [tusen-ai/naive-ui#3583]
### TuSimple/naive-ui version (版本)
2.32.2

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
chrome 106.0.5245.0

### System and its version (系统及其版本)
Windows11 22621.382

### Reappearance link (重现链接)
https://codesandbox.io/s/elegant-proskuriakova-mts8ne?file=/src/App.vue

### Reappearance steps (重现步骤)
自定义dots样式后设置 trigger="hover"

### Expected results (期望的结果)
响应 trigger="hover" 属性

### Actual results (实际的结果)
未响应 trigger="hover" 属性

**Comment by amadeus711** [comment]
当自定义 dots 后，组件会将控制权交给用户，此时想实现 hover 效果，必须用户自己实现：
https://codesandbox.io/s/divine-mountain-3jcwm4?file=/src/App.vue
