### ISSUE TITLE
树，点击树杈的时候能否不响应onClick事件

### ISSUE THREAD

**Issue by hiipeng** [tusen-ai/naive-ui#3595]
### This function solves the problem (这个功能解决的问题)
有些情况下只想展开子集并不想触发父级的click事件
<img width="227" alt="image" src="https://user-images.githubusercontent.com/32444545/186681981-821374a6-900b-45b1-8cb5-37cd0721d77c.png">
比如上图，我展开“硬装部”是想看下面的部门信息，但展开时就会触发“硬装部”的click事件，从而展示“硬装部”的信息。
更不友好的是此时“硬装部”并没有底色表明已选中，选中应该入下图，此时展示“硬装部”的信息是合适的。
<img width="339" alt="image" src="https://user-images.githubusercontent.com/32444545/186683184-30da72e0-25f5-41d6-a063-483f01cae92d.png">
能不能解决一下呢？
1、最偷懒的做法，点击展开下级图标后，当前节点直接有选中底纹
或
2、onClick时返回节点是否选中的状态
或
3、展开单独给一个事件，跟onClick不混淆

**Comment by 07akioni** [comment]
你可以通过判断 `@update:selected-keys` 的第二个参数来判断是否要更新，比如如果

```
const selectedKeys = ref([])

const handleUpdateSelectedKeys = (keys, options) => {
  if (options[0]?.children) {
    // 不是叶节点，什么都不做
  } else {
    selectedKeys.value = keys
  }
}
```
