### ISSUE TITLE
Dialog: close button is focused initially (and styled)

### ISSUE THREAD

**Issue by OrbisK** [tusen-ai/naive-ui#3596]
### TuSimple/naive-ui version (版本)
2.32.2

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
OperaGX

### System and its version (系统及其版本)
Win 11 (64)

### Node version (Node 版本)
/

### Reappearance link (重现链接)
https://codesandbox.io/s/ufo1ln

### Reappearance steps (重现步骤)
click on any button

### Expected results (期望的结果)
close button should not be focused and styled like focus

### Actual results (实际的结果)
close button is focused/styled

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
