### ISSUE TITLE
n-progress  指标位置为 inside时浅色与深色模式与outside字体颜色相反

### ISSUE THREAD

**Issue by zhangke1722** [tusen-ai/naive-ui#3599]
### TuSimple/naive-ui version (版本)
2.32.2

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
window

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/progress

### Reappearance steps (重现步骤)
n-progress  指标位置为 inside时  浅色模式 指标文本颜色为白色  黑暗模式时指标文本颜色为黑色,与指标位置为outside的 指标文本颜色相反,,官网 n-progress进行时demo可以复现

### Expected results (期望的结果)
n-progress 指标位置为 inside时,指标文本颜色,在浅色与黑暗模式下与指标位置为 outside的文本颜色一致

### Actual results (实际的结果)
n-progress  指标位置为 inside时  浅色模式 指标文本颜色为白色  黑暗模式时指标文本颜色为黑色,与指标位置为outside的 指标文本颜色相反,,官网 n-progress进行时demo 可以复现

**Comment by OrbisK** [comment]
this might be related to a discussion on dicsord:

https://discord.com/channels/842427094214770768/842427094214770771/1008260799338389504

**Comment by 07akioni** [comment]
We will consider changing it to lighter color.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
