### ISSUE TITLE
Date Picker 選完年、月之後會擋住「日」的選擇

### ISSUE THREAD

**Issue by SkyleLai** [tusen-ai/naive-ui#3615]
### This function solves the problem (这个功能解决的问题)
現在 Date Picker（type="date"）在選完年、月之後，會擋住「日」的選擇。使用者必須先點一個錯誤的日期，再點一次 Date Picker 選擇正確的日期。

希望可以像 type="datetime" 提供 done 按鈕，或是像 type="month" 一樣選擇日期（變成年、月、日三欄）。

謝謝！
### Expected API (期望的 API)
-

**Comment by sos233** [comment]
![image](https://user-images.githubusercontent.com/7446920/198241284-2acc4909-9eaa-44b6-b4f1-32f5a28dd2c1.png)
现在可以点击红框位置，关掉年月弹框。
理想情况应该是选完月直接关掉年月弹框。

**Comment by zhzwz** [comment]
附议。

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
