### ISSUE TITLE
TreeOption Properties-- set 'checkboxDisabled' props, node can't selected

### ISSUE THREAD

**Issue by SSQLQIANBB** [tusen-ai/naive-ui#3620]
### This function solves the problem (这个功能解决的问题)
set 'checkboxDisabled' props, node can't selected, why props of "checkboxDisabled" was effected node's selected?  laji--comp
### Expected API (期望的 API)
垃圾ui

**Comment by 07akioni** [comment]
这是个 bug，需要修一下
