### ISSUE TITLE
InternalSelection: theme override `boxShadowFocus` not working

### ISSUE THREAD

**Issue by OrbisK** [tusen-ai/naive-ui#3624]
### TuSimple/naive-ui version (版本)
2.33.0

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
OperaGX

### System and its version (系统及其版本)
Win 11 (64)

### Node version (Node 版本)
/

### Reappearance link (重现链接)
https://codesandbox.io/s/laughing-pond-obxd6h?file=/src/Demo.vue

### Reappearance steps (重现步骤)
open link, focus select

### Expected results (期望的结果)
red box shadow

### Actual results (实际的结果)
green (default) boxsahdow

### Remarks (补充说明)
related to https://github.com/tusen-ai/naive-ui/issues/3493#issuecomment-1216870366

**Comment by 07akioni** [comment]
`boxShadowActive` has higher priority.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/18677354/188319000-5032a545-3e0c-439f-b46f-e24b932af365.png">
