### ISSUE TITLE
DataTable update:checked-row-keys 参数可以是rowKey 

### ISSUE THREAD

**Issue by wichochiu** [tusen-ai/naive-ui#3626]
### This function solves the problem (这个功能解决的问题)
单独对数据行操作需要对大量的数据进行处理，无法捕获用户操作具体数据行
### Expected API (期望的 API)
update:checked-row-keys(rowKey|rowKeys,row|rows)

**Comment by 07akioni** [comment]
会考虑增加具体行信息

**Comment by jahnli** [comment]
`(keys: Array<string | number>, rows: object[], meta: { row: object | undefined, action: 'check' | 'uncheck' | 'checkAll' | 'uncheckAll' }) => void`
