### ISSUE TITLE
通过createVNode 创建的DOM节点无法响应主题

### ISSUE THREAD

**Issue by AnsGoo** [tusen-ai/naive-ui#3631]
### TuSimple/naive-ui version (版本)
2.32.1

### Vue version (Vue 版本)
3.2.20

### Browser and its version (浏览器及其版本)
Chrome

### System and its version (系统及其版本)
Win10

### Node version (Node 版本)
14.17.1

### Reappearance link (重现链接)
https://github.com/AnsGoo/openDataV/blob/main/src/designer/Pane/Toolbar/modules/iconList/index.ts

### Reappearance steps (重现步骤)
1.  clone 项目运行，或者打开http://datav.byteportrait.com/#/page/create 
2.  点击右上角主题切换按钮，切换至暗黑模式，并点击图标按钮会弹出图标的模态框

### Expected results (期望的结果)
模态框应该随着项目主题一起变化

### Actual results (实际的结果)
但是实际上模态框一直是默认样式

### Remarks (补充说明)
已经按照官方文档指导通过`n-global-style`将主题样式扩展到body上了

**Comment by 07akioni** [comment]
这个目前来看是符合预期的，因为脱离了 App 上下文了，如果有需要的话可以在 App 根部设定一个包装的 Modal 然后通过 ref 控制。有计划提供一个 ModalProvider 来解决这个问题。

**Comment by AnsGoo** [comment]
> 这个目前来看是符合预期的，因为脱离了 App 上下文了，如果有需要的话可以在 App 根部设定一个包装的 Modal 然后通过 ref 控制。有计划提供一个 ModalProvider 来解决这个问题。

这个不仅仅是Modal组件有这个问题，只要是通过CreateVNode创建的组件，脱离APP上下文的都存在这种情况，例如这个：https://github.com/AnsGoo/openDataV/blob/main/src/plugins/directive/contextmenu/index.ts，通过指令动态创建ContextMenu,所以通过APP根部包装Modal不太方便，有可能我的不是Modal，有其他好的解决方式话请告知，感谢

**Comment by AnsGoo** [comment]
> 这个目前来看是符合预期的，因为脱离了 App 上下文了，如果有需要的话可以在 App 根部设定一个包装的 Modal 然后通过 ref 控制。有计划提供一个 ModalProvider 来解决这个问题。

已经解决了，封装了NConfigProvider, 将在CreateVNode创建的虚拟节点外面包一层ConfigProvider组件就好了，https://github.com/AnsGoo/openDataV/blob/main/src/designer/Pane/Toolbar/modules/iconList/IconFont.vue

**Comment by 1071125093** [comment]
牛逼兄弟

**Comment by Lnunu** [comment]
> > 这个目前来看是符合预期的，因为脱离了 App 上下文了，如果有需要的话可以在 App 根部设定一个包装的 Modal 然后通过 ref 控制。有计划提供一个 ModalProvider 来解决这个问题。
> 
> 已经解决了，封装了NConfigProvider, 将在CreateVNode创建的虚拟节点外面包一层ConfigProvider组件就好了，https://github.com/AnsGoo/openDataV/blob/main/src/designer/Pane/Toolbar/modules/iconList/IconFont.vue

看了您的代码，是放弃使用naive组件实现了吗

**Comment by AnsGoo** [comment]
> 

没有，我改变了项目目录结构， 类似这样即可
```vue
<template>
  <ConfigProvider>
    <n-modal
      class="show-card"
      :show="isShow"
      preset="card"
      :title="`图标数量${iconList.length}`"
      style="width: 50%; max-width: 800px"
      @mask-click="close"
      @close="close"
      @update:show="isShow = false"
    >
      <ul class="icon-list">
        <li v-for="icon in iconList" :key="icon" class="dib" @click="handleClick(icon)">
          <span :class="`icon iconfont ${icon}`"></span>
        </li>
      </ul>
    </n-modal>
  </ConfigProvider>
</template>
```
