### ISSUE TITLE
为什么使用n-layout布局时页面中使用带弹出层组件时，最外层会多一条滚动条

### ISSUE THREAD

**Issue by maddenBoy** [tusen-ai/naive-ui#3632]
### TuSimple/naive-ui version (版本)
2.33.1

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Chrome（104.0.5112.102）

### System and its version (系统及其版本)
window11

### Reappearance link (重现链接)
https://github.com/maddenBoy/layout-problem

### Reappearance steps (重现步骤)
1、使用组件文档中的layout布局组件绝对定位模式的示例代码
2、layout组件的内容区域使用pagination等有弹出层的组件
或者使用github地址中的复现demo

### Expected results (期望的结果)
页面中使用NLayout布局组件时，页面中使用NPagination、NPopcomfirm等带弹出层的组件，点击组件，在弹出层显示时，滚向上滚动时，浏览器外侧不显示滚动条，（组件文档中不会这种情况，想知道是如何解决的）

### Actual results (实际的结果)
页面中使用NLayout布局组件时，页面中使用NPagination、NPopcomfirm等带弹出层的组件时，点击组件，在弹出层显示时，滚动到页面到顶部，浏览器外侧会多一条滚动条

### Remarks (补充说明)

![image](https://user-images.githubusercontent.com/71129660/187388221-5ac92ca8-bb12-4472-9c22-fb98d84aa5d5.png)

**Comment by 07akioni** [comment]
把 html 设为 overflow hidden 应该就能解决了

**Comment by 07akioni** [comment]
文档里也是这个原理

**Comment by maddenBoy** [comment]
十分感谢，加上后有效
