### ISSUE TITLE
DataTable column 合并列时,children多列时fixed会存在后列覆盖前列 

### ISSUE THREAD

**Issue by yandezhi** [tusen-ai/naive-ui#3639]
### TuSimple/naive-ui version (版本)
2.33.1

### Vue version (Vue 版本)
3.2.38

### Browser and its version (浏览器及其版本)
 chrome

### System and its version (系统及其版本)
MacBook

### Reappearance link (重现链接)
https://codesandbox.io/s/summer-thunder-pgy6h7?file=/src/App.vue:0-1626

### Reappearance steps (重现步骤)
<template>
  <div>
    <n-data-table
      :data="data"
      :columns="columns"
      :single-line="false"
      :pagination="pagination"
    />
  </div>
</template>

<script>
import { defineComponent, ref } from "vue";
import { NDataTable } from "naive-ui";
function createCols() {
  return [
    {
      title: "Name",
      key: "name",
      fixed: "left",
    },
    {
      title: "Attack",
      key: "attack",
      fixed: "left",
      children: [
        {
          title: "Physics Attack",
          key: "physicsAttack",
          fixed: "left",
        },
        {
          title: "Magic Attack",
          key: "magicAttack",
          fixed: "left",
        },
      ],
    },
    {
      title: "Defend",
      key: "defend",
      width: "500px",
    },
    {
      title: "defend2",
      key: "defend2",
      width: "500px",
    },
    {
      title: "Speed",
      key: "speed",
      width: "500px",
    },
    {
      title: "Speed1",
      key: "speed1",
      width: "500px",
    },
  ];
}

function createData() {
  return Array.from({ length: 50 }).map((_, i) => {
    return {
      key: i,
      name: `name_${i}`,
      physicsAttack: `physicsAttack_${i}`,
      magicAttack: `magicAttack_${i}`,
      defend: `defend_${i}`,
      defend2: `defend_${i   10}`,
      speed: `speed_${i}`,
      speed1: `speed_${i   10}`,
    };
  });
}
export default defineComponent({
  name: "App",
  components: {
    NDataTable,
  },
  setup() {
    return {
      data: ref(createData()),
      columns: ref(createCols()),
      pagination: ref({
        pageSize: 10,
      }),
    };
  },
});
</script>

### Expected results (期望的结果)
期忘可以固定子列

### Actual results (实际的结果)
后列覆盖前列

### Remarks (补充说明)
稳定复现

**Comment by 07akioni** [comment]
因为没有给 width，fixed 的列必须有宽度

<img width="400" alt="image" src="https://user-images.githubusercontent.com/18677354/188319526-95c9c14c-487a-4b56-9a61-151ef8d56534.png">
