### ISSUE TITLE
n-input-number 的值改变时validator会触发多次

### ISSUE THREAD

**Issue by jyp0912** [tusen-ai/naive-ui#3650]
### TuSimple/naive-ui version (版本)
2.33.2

### Vue version (Vue 版本)
3.2.38

### Browser and its version (浏览器及其版本)
Chrome（104.0.5112.102）

### System and its version (系统及其版本)
Windows 10 专业版

### Reappearance link (重现链接)
https://codesandbox.io/s/determined-forest-copnf2?file=/src/Demo.vue

### Reappearance steps (重现步骤)
点击加减或直接输入

### Expected results (期望的结果)
console只触发一次

### Actual results (实际的结果)
console触发了多次

**Comment by 07akioni** [comment]
这个是符合预期的，validator 会在很多时机被调用，举个最简单的例子就是会验证一下当前值是不是合法，是的话才会去验证变了之后的值。实际的逻辑还会比这个麻烦很多。
