### ISSUE TITLE
Select All options

### ISSUE THREAD

**Issue by nasir-xel** [tusen-ai/naive-ui#3653]
### This function solves the problem (这个功能解决的问题)
I am working on a B2B application that has a lot of select options from which user can select multiple or all options. Sometimes the options can be pretty big for user to select them all one by one. So my client wanted to have an option to *Select All* instead of manual selecting as a better UX.
### Expected API (期望的 API)
< Select :options="allUsers" enable-select-all />

**Comment by 07akioni** [comment]
We need to consider about it.

**Comment by wrtisans** [comment]
i've this request too, in the meantime i've archieved this with the action slot in the select https://www.naiveui.com/en-US/os-theme/components/select#action.vue and a checkbox, im happy to make a pull request to add this functionality if it can help to somebody :)
