### ISSUE TITLE
Tree 组件点击事件

### ISSUE THREAD

**Issue by skrlst** [tusen-ai/naive-ui#3657]
### This function solves the problem (这个功能解决的问题)
需要一个点击节点的事件，文档看下来没有找到类似功能的东西，可以添加该功能吗？
### Expected API (期望的 API)
https://element-plus.gitee.io/zh-CN/component/tree.html

node-click	当节点被点击的时候触发	三个参数：对应于节点点击的节点对象， TreeNode 节点 属性，事件对象

**Comment by jizai1125** [comment]
可以用 `node-props` 属性

**Comment by skrlst** [comment]
> 可以用 `node-props` 属性

😅 是我疏忽了，官网是有解释该属性的。
