### ISSUE TITLE
n-dropdown 是否有属性配置下拉选项的选中颜色 ，不想修改主题那样全部都改了

### ISSUE THREAD

**Issue by Muxin-007** [tusen-ai/naive-ui#3660]
### This function solves the problem (这个功能解决的问题)
某一个页面的需要改变下拉选项的hover 颜色，修改主题能修改但是会把整个项目的下拉选项改掉
### Expected API (期望的 API)
ColorHover ： "red"

**Comment by jizai1125** [comment]
可以用组件的 `theme-overrides` [link](https://www.naiveui.com/zh-CN/os-theme/docs/customize-theme#%E8%B0%83%E6%95%B4%E7%BB%84%E4%BB%B6%E4%B8%BB%E9%A2%98%E5%8F%98%E9%87%8F)
