### ISSUE TITLE
UMD：连续使用组件后渲染异常

### ISSUE THREAD

**Issue by sxwlmsrbi** [tusen-ai/naive-ui#3661]
### TuSimple/naive-ui version (版本)
2.33.2

### Vue version (Vue 版本)
3.2.38

### Browser and its version (浏览器及其版本)
Firefox(104); Chrome(104)

### System and its version (系统及其版本)
Windows 10; Android

### Reappearance link (重现链接)
https://jsbin.com/fayoyocavi/edit?html,output

### Reappearance steps (重现步骤)
在使用UMD模块的前提下，部分组件如果与其他组件（如按钮等）连续使用，这些组件（如按钮等）无法被渲染。最明显的示例是 https://www.naiveui.com/zh-CN/os-theme/components/input 中的输入组示例代码，改写成重现链接中的代码后，许多组件无法正常渲染。因为组件数量和组合可能太多，其他组件还未测试是否也有类似问题。

在使用构建工具的前提下，如输入组示例代码的官方 CodeSandbox 示例，组件渲染是正常的。简单测试后发现 Naive UI 所有版本的 UMD 模块均有此问题。如果将这些组件替换成浏览器原生组件，则不会出现该问题。

### Expected results (期望的结果)
正常渲染所有组件

### Actual results (实际的结果)
部分组件没有被渲染

**Comment by sxwlmsrbi** [comment]
再次简单测试后发现，如果每个组件外套一层<div>，输入组内的所有组件则可以正常渲染

**Comment by 07akioni** [comment]
我试了一下，标签自闭合就会出问题，我觉得这个看起来不像 naive 的问题。

像下面这样就可以正常渲染：
<img width="414" alt="image" src="https://user-images.githubusercontent.com/18677354/188318547-d17598f9-9e7e-4694-98ae-7f5350ec0476.png">

**Comment by sunyiming** [comment]
2.34.3 中仍然存在。是否可以在文档中提及这个问题？
