### ISSUE TITLE
XMLHttpRequest.responseType for upload component

### ISSUE THREAD

**Issue by kieste** [tusen-ai/naive-ui#3666]
### This function solves the problem (这个功能解决的问题)
I can set the responseType of upload components XMLHttpRequest so that I don't need to parse the response by myself.

see: https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseType
### Expected API (期望的 API)
```
<n-upload
    responseType="json|arraybuffer|blob|document|text">
</n-upload>
```

**Comment by 07akioni** [comment]
Good suggestion.
