### ISSUE TITLE
改进部分反馈组件的使用方式，使其更加灵活

### ISSUE THREAD

**Issue by sxwlmsrbi** [tusen-ai/naive-ui#3668]
### This function solves the problem (这个功能解决的问题)

希望 Dialog、Message、Notification、LoadingBar 这四个反馈组件的使用方式以及 Discrete API 的使用可以参考 Varlet UI 相关组件的[使用方式](https://varlet.gitee.io/varlet-ui/#/zh-CN/snackbar)改进，使其可以更加灵活的使用🧐

#### 组件使用

```html
<n-message-bar type="error" v-model:show="snackBarFlag"> 消息条 </n-message-bar>
```

#### 函数使用（UMD 示例）

```javascript
 naive.MessageBar({
    type: "info",
    content: "消息条",
    position: "bottom"
  })
```

**Comment by 07akioni** [comment]
不会改变现有 API
