### ISSUE TITLE
[Feature Request]: Dropdown support Enter-Key

### ISSUE THREAD

**Issue by BeanWei** [tusen-ai/naive-ui#3669]
### This function solves the problem (这个功能解决的问题)
Dropdown only support up/down event, hope to support enter event
### Expected API (期望的 API)
dont need add new api, just enhance keybord event

**Comment by Sepush** [comment]
> ### This function solves the problem (这个功能解决的问题)
> Dropdown only support up/down event, hope to support enter event
> 
> ### Expected API (期望的 API)
> dont need add new api, just enhance keybord event

It's already suppoted.
https://github.com/tusen-ai/naive-ui/blob/12178654b2a21f66a4346d5c45b27a7e21958e6a/src/dropdown/src/Dropdown.tsx#L209-L211

**Comment by BeanWei** [comment]
@Sepush  我测试了官网上的demo，这个 enter 的 event 貌似只有当 `trigger="hover"` 时才会生效

**Comment by BeanWei** [comment]
@Sepush  can you reopen

**Comment by Sepush** [comment]
> @Sepush 我测试了官网上的demo，这个 enter 的 event 貌似只有当 `trigger="hover"` 时才会生效

试了一下 trigger = click 和 没有 trigger的时候也是正常工作的

**Comment by 07akioni** [comment]
没太理解是什么意思，我试了试无论 trigger 是什么这个都可以被触发

**Comment by Sepush** [comment]
> 没太理解是什么意思，我试了试无论 trigger 是什么这个都可以被触发

官网多级的那个例子好像不会触发

**Comment by wmnv222666** [comment]
这个功能怎么处理？是否支持Enter

**Comment by 07akioni** [comment]
> 这个功能怎么处理？是否支持Enter

支持的

**Comment by 07akioni** [comment]
fixed
