### ISSUE TITLE
点击n-menu中的菜单时，不应该触发render-icon事件

### ISSUE THREAD

**Issue by 0xyk3r** [tusen-ai/naive-ui#3670]
### This function solves the problem (这个功能解决的问题)
点击n-menu中的菜单时，会触发render-icon事件（在options未被改变的情况下）。我不确定这是一个bug还是有意而为之的。
### Expected API (期望的 API)
render-icon事件应该仅在options变动后触发，或者提供一个开关来控制是否在点击menu item时触发？

**Comment by 07akioni** [comment]
这个原因很早以前 vue 有个 bug，所以当时用一个不确保渲染性能的方法解决了：
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/18677354/188316715-90e78167-cb32-4f35-b954-3590b545a692.png">

我不是很确认这个 bug Vue 后面处理了么，不过大概率应该是处理了。
