### ISSUE TITLE
data-table  add  clearSelection  toggleAllSelection function 

### ISSUE THREAD

**Issue by muchenfine** [tusen-ai/naive-ui#3671]
### This function solves the problem (这个功能解决的问题)
data-table  add  clearSelection  toggleAllSelection function 
### Expected API (期望的 API)
data-table  add  clearSelection  toggleAllSelection function

toggleAllSelection: Used for selecting multiple tables, toggle select all and select none
clearSelection: Used for multiple selection tables to clear the user's choices

**Comment by jahnli** [comment]
duplicate https://github.com/tusen-ai/naive-ui/issues/3704
