### ISSUE TITLE
tabs 标签添加左右布局的功能

### ISSUE THREAD

**Issue by wei1034937343** [tusen-ai/naive-ui#3672]
### This function solves the problem (这个功能解决的问题)
当给定的容器内容较小，又需要展示较多的分类数据时，左右布局要比上下布局操作方便美观
### Expected API (期望的 API)
如参考NutUI的tabs，添加配置属性direction，使用横纵方向 可选值 horizontal、vertical

效果如下：
![image](https://user-images.githubusercontent.com/28970254/188354967-b1232afa-6fa8-4d4a-8442-56d3741a2f08.png)

**Comment by 07akioni** [comment]
dup of https://github.com/tusen-ai/naive-ui/issues/1466
