### ISSUE TITLE
DateTimeRange  add close-on-select props 

### ISSUE THREAD

**Issue by laterdays** [tusen-ai/naive-ui#3673]
### This function solves the problem (这个功能解决的问题)
I see close-on-select in the dateRange type, but DateTimeRange does not support it

### Expected API (期望的 API)
close-on-select	boolean  Whether to close the panel automatically after the user selects a time range

**Comment by dickofn** [comment]
can confirm not working with yearrange too

**Comment by duanmw** [comment]
MonthRange、QuarterRange、YearRange neither support, but this prop in the document

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
