### ISSUE TITLE
Provide information about slots in web-types or *.d.ts files

### ISSUE THREAD

**Issue by linkurzweg** [tusen-ai/naive-ui#3675]
### This function solves the problem (这个功能解决的问题)
When developing projects with Naive UI in WebStorm I get lots of false positive warnings about unrecognized slot names, which is pretty annoying. It seems information about the slots needs to be provided either via web-types or *.d.ts definitions (see this [issue](https://youtrack.jetbrains.com/issue/WEB-55215#focus=Comments-27-6426056.0-0)). Could you provide these? It would help a lot, thank you!
### Expected API (期望的 API)
Provide information about slots in type definitions.

**Comment by Sepush** [comment]
If you use webstrom maybe you coulde follow this issue of webstrom https://youtrack.jetbrains.com/issue/WEB-50453/Provide-completiontype-checking-of-Vue-library-components-props-defined-in-dts-files

**Comment by linkurzweg** [comment]
> If you use webstrom maybe you coulde follow this issue of webstrom https://youtrack.jetbrains.com/issue/WEB-50453/Provide-completiontype-checking-of-Vue-library-components-props-defined-in-dts-files

This is specifically about slots and as far as I understand, Naive UI does not yet provide information about the slots of its components in their type definitions so far. The corresponding issue is here on the JetBrains issue tracker: https://youtrack.jetbrains.com/issue/WEB-55215

A developer from JetBrains was kind enough to open a PR to improve the generation of web types to resolve this:
https://github.com/tusen-ai/naive-ui/pull/3691
