### ISSUE TITLE
scrollbar组件添加滚动条"一直不显示"的的选项

### ISSUE THREAD

**Issue by longmaobure** [tusen-ai/naive-ui#3676]
### This function solves the problem (这个功能解决的问题)
在当前需要使用scrollbar组件并且不需要显示滚动条的情况下,还需要打开控制台,找到滚动条对应的元素,再设置css
### Expected API (期望的 API)
建议给scrollbar组件的 trigger添加一个never选项, 用来阻止右侧滚动条的显示

**Comment by kirklin** [comment]
这个issue是不是可以关闭了
[https://www.naiveui.com/zh-CN/light/components/scrollbar](https://www.naiveui.com/zh-CN/light/components/scrollbar)
