### ISSUE TITLE
DataTable: add option to set summary row on top

### ISSUE THREAD

**Issue by topvis** [tusen-ai/naive-ui#3681]
### This function solves the problem (这个功能解决的问题)
There are cases that user want to see summary on top of the data table (below the header row and above the first data row).
Another case is that summary row is not visible when there are many rows. User would have to scroll down to see the summary row.
### Expected API (期望的 API)
```HTML
<n-data-table ...  summary-position="top" ... />
```

**Comment by wj007881** [comment]
![image](https://user-images.githubusercontent.com/26053141/201315850-1280eac3-dcc7-414e-a8dc-361587534acf.png)
这部分需要传过去什么值？按照文档的传过去报错
![image](https://user-images.githubusercontent.com/26053141/201316010-aebcf2cb-7aa8-4ec6-8630-540ecc1a7104.png)
![image](https://user-images.githubusercontent.com/26053141/201316055-9575cc9f-51ba-4079-b2f8-9c8d75af0e62.png)

**Comment by vitjaz** [comment]
@wj007881 same issue!
