### ISSUE TITLE
html中使用scale导致下拉等组件定位有问题

### ISSUE THREAD

**Issue by seafronthu** [tusen-ai/naive-ui#3682]
### TuSimple/naive-ui version (版本)
2.33.2

### Vue version (Vue 版本)
3.2.38

### Browser and its version (浏览器及其版本)
Edge(104.0.1293.70)

### System and its version (系统及其版本)
MacOS(12.5.1)

### Reappearance link (重现链接)
https://codesandbox.io/s/goofy-bird-e3t327?file=/src/Demo.vue

### Reappearance steps (重现步骤)
在html标签样式添加如下属性：
``` html
<html style="
    transform: scale(0.8);
    width: 125vw;
    height: 125vh;
    transform-origin: 0 0;
">
```
### Expected results (期望的结果)
希望所有的下拉内容能够正确定位

### Actual results (实际的结果)
定位偏移

**Comment by amadeus711** [comment]
![image](https://user-images.githubusercontent.com/46394163/188657005-82ae7a16-875f-4f65-9993-fcdfc73b8ecf.png)
https://codesandbox.io/s/shy-star-d3lp9j?file=/src/Demo.vue
这个组件的这个用法弹出的位置只与用户传入的 `x`、`y` props 有关，而比例变化是用户行为，需要用户自行对变化后事件中取到的位置进行换算处理

**Comment by seafronthu** [comment]
整体缩小，clientX和clientY位置计算的时候不应该也是对应缩小的吗。而且不能设置x和y的那些提示框也有同样的问题。

**Comment by 07akioni** [comment]
> 整体缩小，clientX和clientY位置计算的时候不应该也是对应缩小的吗。而且不能设置x和y的那些提示框也有同样的问题。

getBoundingtClientRect 这个 API 拿不到正确的值，目前并不打算处理这种情况

**Comment by seafronthu** [comment]
> > 整体缩小，clientX和clientY位置计算的时候不应该也是对应缩小的吗。而且不能设置x和y的那些提示框也有同样的问题。
> 
> getBoundingtClientRect 这个 API 拿不到正确的值，目前并不打算处理这种情况

![image](https://user-images.githubusercontent.com/50374650/189790854-182ed2c0-9b63-440e-a019-290929009083.png)
![image](https://user-images.githubusercontent.com/50374650/189790905-a667505d-82f1-46db-b34b-90fd1caf0540.png)
https://codesandbox.io/s/xenodochial-sound-fxxymi?file=/index.html
getBoundingtClientRect计算是正确的。

**Comment by 07akioni** [comment]
> > > 整体缩小，clientX和clientY位置计算的时候不应该也是对应缩小的吗。而且不能设置x和y的那些提示框也有同样的问题。
> > 
> > 
> > getBoundingtClientRect 这个 API 拿不到正确的值，目前并不打算处理这种情况
> 
> ![image](https://user-images.githubusercontent.com/50374650/189790854-182ed2c0-9b63-440e-a019-290929009083.png) ![image](https://user-images.githubusercontent.com/50374650/189790905-a667505d-82f1-46db-b34b-90fd1caf0540.png) https://codesandbox.io/s/xenodochial-sound-fxxymi?file=/index.html getBoundingtClientRect计算是正确的。

计算位置基于的是原始值，而不是缩放后的值

**Comment by hizhengfu** [comment]
有什么推荐的方式吗？大屏中用到一般都是根据比例缩放的，如果不处理体验还是有些问题。

**Comment by zhangkejian0** [comment]
> 有什么推荐的方式吗？大屏中用到一般都是根据比例缩放的，如果不处理体验还是有些问题。

属性to给false，可以直接修改样式解决呀
![image](https://user-images.githubusercontent.com/26479724/206394132-f9596a46-091c-4b72-b39f-c4a980a4cc95.png)

**Comment by zhangkejian0** [comment]
> 有什么推荐的方式吗？大屏中用到一般都是根据比例缩放的，如果不处理体验还是有些问题。
![image](https://user-images.githubusercontent.com/26479724/206395197-866305fa-a866-480f-8f88-2983e3947a06.png)
修改css
![image](https://user-images.githubusercontent.com/26479724/206395304-ab2b1795-369e-47d2-ad92-d491794e67ac.png)

**Comment by hizhengfu** [comment]
用到to=false 本身也基本在元素附近了，但是这个有个问题是可能被外层的遮挡了。一个思路是根据缩放比例动态计算出来。

**Comment by hizhengfu** [comment]
使用手动定位，结合缩放比例设置x,y比较好的解决了。

**Comment by hanjialin** [comment]
> 使用手动定位，结合缩放比例设置x,y比较好的解决了。
可以给一些类似的思路吗？这块还是不太明白如何全部使用手动定位解决。另外如何全局解决这样的问题呢？

**Comment by wuzeqingit** [comment]
最终你们怎么解决的
