### ISSUE TITLE
轮播图组件宽高缩放不等比例时显示异常

### ISSUE THREAD

**Issue by bundlejs** [tusen-ai/naive-ui#3684]
### TuSimple/naive-ui version (版本)
2.33.2

### Vue version (Vue 版本)
3.2.38

### Browser and its version (浏览器及其版本)
Chrome(105.0.5195.102)

### System and its version (系统及其版本)
MacOS(12.5.1)

### Node version (Node 版本)
18.8

### Reappearance link (重现链接)
https://codesandbox.io/s/happy-alex-mnt9k0?file=/src/Demo.vue

### Reappearance steps (重现步骤)
直接查看

### Expected results (期望的结果)
正常显示

### Actual results (实际的结果)
显示异常

### Remarks (补充说明)
这个组件在2.32.0之前是没有这个问题的,在2.32.0及其之后的版本才出现这个问题

**Comment by priority3** [comment]
you can add `transform: scaleX(0.5)` in class（carousel item）,rather than in root Crousel

**Comment by bundlejs** [comment]
> you can add `transform: scaleX(0.5)` in class（carousel item）,rather than in root Crousel

组件的上级有缩放, 组件内部不能调整, 另外不是只有不等比例的时候有问题,只要有缩放显示就是有问题的,貌似初始的偏移量计算就有问题
