### ISSUE TITLE
Button 点击并且鼠标移出后 hover 样式仍然存在，怎么取消呢

### ISSUE THREAD

**Issue by yhyzgn** [tusen-ai/naive-ui#3688]
### TuSimple/naive-ui version (版本)
2.33.2

### Vue version (Vue 版本)
3.2.38

### Browser and its version (浏览器及其版本)
Chrome(105.0.5195.102)

### System and its version (系统及其版本)
Windows 11

### Node version (Node 版本)
16.17.0

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/button

### Reappearance steps (重现步骤)
官网上的所有按钮，点了就能复现
https://www.naiveui.com/zh-CN/os-theme/components/button
1、先把鼠标移进按钮，hover样式生效
2、然后点击按钮并松开
3、再把鼠标移出按钮区域，发现hover样式还存在
4、需要点击一下空白地方，样式才恢复到默认状态

### Expected results (期望的结果)
按钮点击并且鼠标移出后，hover 样式恢复默认样式

### Actual results (实际的结果)
Button 点击并且鼠标移出后 hover 样式仍然存在，怎么取消呢

**Comment by OrbisK** [comment]
this is not hover style. Its actually the focus style!

![image](https://user-images.githubusercontent.com/37191683/188854593-4ddf9e05-6ed3-49c0-976c-368eda651665.png)

**Comment by Sepush** [comment]
hover style 鼠标移出就会消失 如果是点击 button 会聚焦需要失去焦点才会恢复 如果你不想要 可以设置 `:focusable = false`
