### ISSUE TITLE
icon: `color` theme-override not working when no depth is set

### ISSUE THREAD

**Issue by OrbisK** [tusen-ai/naive-ui#3690]
### TuSimple/naive-ui version (版本)
2.33.2

### Vue version (Vue 版本)
3.2.38

### Browser and its version (浏览器及其版本)
OperaGX

### System and its version (系统及其版本)
Win 11

### Node version (Node 版本)
/

### Reappearance link (重现链接)
https://codesandbox.io/s/intelligent-water-7p4by0?file=/src/Demo.vue

### Reappearance steps (重现步骤)
open reprod

### Expected results (期望的结果)
all icons should be red.

### Actual results (实际的结果)
only icons with depth are red

**Comment by 07akioni** [comment]
This is expected. By default icon's color is `currentColor`.

**Comment by OrbisK** [comment]
> This is expected. By default icon's color is `currentColor`.

But why does it work with depth?

**Comment by 07akioni** [comment]
> > This is expected. By default icon's color is `currentColor`.
> 
> But why does it work with depth?

Depth means you expect icon has a exact color.
