### ISSUE TITLE
NSelect: no way to know the group of an option

### ISSUE THREAD

**Issue by M1CK431** [tusen-ai/naive-ui#3693]
### This function solves the problem (这个功能解决的问题)
If multiple `SelectOption` in different `SelectGroupOption` have the same `value`, there is no way to distinguish which one the user have selected.

This problem happens with this really common use case:
- We fetch list `A`, `B` and `C` from API
- Each list have their own id auto increment (dedicated table in database) and so there is the same ids in each list
- We want to use each list as a `SelectGroupOption` in the same `NSelect`
- Because there is the same `value` (aka `id`) `1` (for example) in list `A`, `B` and `C`, we have no way to know which `SelectOption` the user have selected :sob:

### Expected API (期望的 API)
A very flexible way of handling that could be a new `option-as-value` boolean prop.

Once set to `true`, the `value` prop (and corresponding `update:value` event) while now deal with the whole `SelectOption` object instead of only the `value`. Because it's an object, it become easy to add a `group` property which contains the corresponding `SelectGroupOption` `key` (or even the whole `SelectGroupOption` object after all :man_shrugging:).

In addition, if the developer provides extra properties to `SelectOption` objects, he will be able to better identify which one is selected based on that extra properties.

**Comment by 07akioni** [comment]
Select doesn't support options with same value, whether they are in same group. If you need to distinguish them, you should convert options first.

**Comment by 07akioni** [comment]
You can concat group key to option value after partial list is fetched.

**Comment by M1CK431** [comment]
Hi @07akioni thanks for your reply.

> You can concat group key to option value after partial list is fetched
It's exactly what I'm doing for now, as a workaround.

> Select doesn't support options with same value, whether they are in same group
Please don't mix two different things: the `value` used for each option must be uniq, ok, and adding the group `key` is an easy way to do it, no problem.
BUT that doesn't means it's then easy to retrieve the original option (the one without added group `key`) with the current state of the `NSelect` component!

In my use case, I have a remote search and the search is clear after the user select an option (normal and needed behavior) so the list from my API is "reset". At the end, it's excessively complicated to find the selected entry from API list and I need some extra properties (I mean, other than `value` aka `id`) to display them to the user.

Currently I have more than 100 lignes of code just to build the `options` from API, transform the user selection from API (I store and retrieve the previous user selection if any) to `NSelect` `value` and transform back `NSelect` `update:value` event in API option object format... :exploding_head: 

All that complicated things could be avoid if I can directly pass the objects coming from API as `options` (ok, I will still need a few computation to build groups) and `value` and retrieve them as `update:value` event!

The use case I'm experiencing (remote search, needs of extra properties in `options` and get them back on the user selection) seems excessively common (at least, I have to deal with that multiple times in the past three years with other UI framework) and so, please please consider adding the `option-as-value` prop as a general, really useful enhancement :pray: :pleading_face:

**Comment by 07akioni** [comment]
`onUpdate:value` will pass original option as the second param.

**Comment by M1CK431** [comment]
> `onUpdate:value` will pass original option as the second param.

:scream: :scream: :scream: Hoooo I'm sooooo sorry! I miss that part in the documentation!! I apology for the useless noise.
Thanks a lot for your quick answer and patience :hugs: :heart:

**Comment by 9mm** [comment]
@07akioni how do I pass the index into on-update? I can't find any way to actually know WHICH select was triggered (I have multiple dynamic rows of a form)

```
          <n-select
            v-model:value="part.name"
            :on-update:value="onSelect(index)"
            :options="itemsForSelect"
            size="medium"
            filterable
          />
```

**Comment by M1CK431** [comment]
@9mm you could probably do something like this:
```html
          <n-select
            v-model:value="part.name"
            :on-update:value="(_, { index }) => onSelect(index)"
            :options="itemsForSelect.map((item, index) => ({ ...item, index }))"
            size="medium"
            filterable
          />
```

**Comment by 9mm** [comment]
@M1CK431 awesome, thank you! Great idea
