### ISSUE TITLE
Form 标签中的 asyncValidator 异步校验失效

### ISSUE THREAD

**Issue by wei1034937343** [tusen-ai/naive-ui#3695]
### TuSimple/naive-ui version (版本)
2.33.2

### Vue version (Vue 版本)
3.2.39

### Browser and its version (浏览器及其版本)
edge

### System and its version (系统及其版本)
windows11

### Reappearance link (重现链接)
https://codesandbox.io/s/icy-water-qt3nu0?file=/src/Demo.vue

### Reappearance steps (重现步骤)
form 标签 rules 配置校验规则使用 asyncValidator 异步校验回调callback方法中，传入固定参数true不生效，始终校验不通过

### Expected results (期望的结果)
callback回答方法中，传入参数true校验通过，传入参数false校验不通过

### Actual results (实际的结果)
callback回答方法中，传入参数true或false校验都不通过

### Remarks (补充说明)

![image](https://user-images.githubusercontent.com/28970254/189095940-c1c252ac-e82b-40eb-a5d9-b636d441abbb.png)

**Comment by 0xyk3r** [comment]
`callback()` 代表校验通过
`callback(new Error('error info'))` 代表校验不通过

**Comment by wei1034937343** [comment]
> `callback()`代表校验通过 代表校验不通过`callback(new Error('error info'))`

谢谢，不传确实可以，那就把文档更新一下吧，我当上写的是传一个布尔值。

![image](https://user-images.githubusercontent.com/28970254/189294742-002af87f-9741-49a5-8670-df658e5faf70.png)
