### ISSUE TITLE
NPopover下使用NUpload，mac环境下无法触发导入接口，win环境下正常

### ISSUE THREAD

**Issue by duangkey** [tusen-ai/naive-ui#3697]
### TuSimple/naive-ui version (版本)
2.33.2

### Vue version (Vue 版本)
3.2.39

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
macOS Big Sur 11.6

### Node version (Node 版本)
14.18.0

### Reappearance link (重现链接)
https://naive-ui.github.io/issue-helper/?lang=en-US

### Reappearance steps (重现步骤)
no
复现地址无效，代码放在了comments中

### Expected results (期望的结果)
mac环境下也能够正常使用

### Actual results (实际的结果)
mac环境下在popover里使用NUpload组件时，没法触发导入请求

### Remarks (补充说明)
              <n-popover trigger="hover" placement="bottom">
                <template #trigger>
                  <n-button
                    :bordered="false"
                    class="btn import_btn iconfont icon-import"
                  >
                    导入
                  </n-button>
                </template>
                <ul class="import_list">
                  <li
                    class="import_item"
                    v-for="(item, index) in dropdownOptions"
                    :key="index"
                  >
                    <n-upload
                      v-if="item.tag !== 'a'"
                      :action="item.action"
                      :show-file-list="false"
                      @finish="(options) => handleFinish(options, item)"
                    >
                      <span>{{ item.label }}</span>
                    </n-upload>

                    <a v-else :href="item.href">{{ item.label }}</a>
                  </li>
                </ul>
              </n-popover>

**Comment by Sepush** [comment]
你的复现不完整如果你不能提供在线复现的地址 你可以建一个 github repo 然后贴 repo 链接

**Comment by 07akioni** [comment]
导入接口是说什么问题？IDE 不能导入类型吗？这个应该是 IDE 使用问题，和库本身无关。

**Comment by JuneOY** [comment]
我也遇到了相同的问题，n-popover需要设置display-directive="show"可以解决这个问题
