### ISSUE TITLE
Thing/Button: Strange click/pressed boxshadow

### ISSUE THREAD

**Issue by OrbisK** [tusen-ai/naive-ui#3709]
### TuSimple/naive-ui version (版本)
2.33.2

### Vue version (Vue 版本)
3.2.39

### Browser and its version (浏览器及其版本)
OperaGX / Chrome

### System and its version (系统及其版本)
Win 11 64

### Node version (Node 版本)
/

### Reappearance link (重现链接)
https://codesandbox.io/s/yfyylg

### Reappearance steps (重现步骤)
Click on Moneybutton in header.

### Expected results (期望的结果)
normal boxshadow on button press.

### Actual results (实际的结果)
strange animation.

**Comment by 07akioni** [comment]
Is there any problem?
https://user-images.githubusercontent.com/18677354/189705803-ce3503f2-4cdc-46fa-bf00-47fbeb48e74f.mov

**Comment by OrbisK** [comment]
https://user-images.githubusercontent.com/37191683/189867831-9aed4f74-0cdc-4739-bc4c-1800010111f7.mov

if zoomed in its not happening 🤔 but if zoomed out

**Comment by OrbisK** [comment]
https://user-images.githubusercontent.com/37191683/189868162-5a08b164-e795-4520-a1ad-2e61fe310868.mp4

not happening if zoomed in.

**Comment by OrbisK** [comment]
FYI: still an issue with `2.33.3`

**Comment by 07akioni** [comment]
I think this is a platform specific bug. It may not be easy to fix since button's animation code hasn't been changed for a long time.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
