### ISSUE TITLE
datatable组件的展开行功能，要求data必须提供一个key，且这个key字段字段的名称也必须是“key”？

### ISSUE THREAD

**Issue by angeltxwh** [tusen-ai/naive-ui#3714]
### This function solves the problem (这个功能解决的问题)
是否能提供一个DataTable Props来让用户指定key字段的具体值？比如id或者uuid之类的？或者允许指定index?
现在的情况是必须在data中指定一个叫做key的字段，但是后端又不提供这个字段，就导致每次数据来了还要再 遍历一遍才能使用
### Expected API (期望的 API)
提供用于设置自定义key字段的datatable props

**Comment by 07akioni** [comment]
`row-key` 就是用来做这个的，比如可以 `row => row.index`
