### ISSUE TITLE
Limit the number of selections for `NSelect`

### ISSUE THREAD

**Issue by KeroZhai** [tusen-ai/naive-ui#3716]
### The problem this function solves

For now, users can select as many as possible options in `NSelect`, but sometimes, we want to limit the number of selections.

### Expected API

Provide a prop `max`, just like `NUpload`.

**Comment by 07akioni** [comment]
You can limit it by drop value in `on-update:value`

**Comment by KeroZhai** [comment]
Yeah, it should work, but it would be better if there were some visual effects. For example, options (except the selected ones) will be automatically disabled once the limit is reached, so that users can immediately know that they cannot select more options.

**Comment by yaojunmiss77** [comment]
I agree with KeroZhai

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
