### ISSUE TITLE
tabs标签页特定情况下能否去掉hover属性？

### ISSUE THREAD

**Issue by maddenBoy** [tusen-ai/naive-ui#3717]
### TuSimple/naive-ui version (版本)
2.33.3

### Vue version (Vue 版本)
3.2.39

### Browser and its version (浏览器及其版本)
Chrome（105.0.5195.102）

### System and its version (系统及其版本)
Window11

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/tabs

### Reappearance steps (重现步骤)
1、主题编辑器中修改Tabs下的tabTextColorHoverSegment（选择白色比较明显）
2、鼠标移入分段的例子，字跟背景同色时鼠标无法看清字

### Expected results (期望的结果)
期望某些情况下可以去掉hover的效果，tabs的某些色彩搭配不想受hover的影响

### Actual results (实际的结果)
无法掉hover的效果

### Remarks (补充说明)
![image](https://user-images.githubusercontent.com/71129660/190120592-9bb9cc87-35c8-47ac-b998-c075fb159f2b.png)

**Comment by 07akioni** [comment]
我感觉说的还挺合理，应该去掉

**Comment by 07akioni** [comment]
`tabTextColorHoverSegment` 只对 `segment` 类型的生效，所以如果不需要的话，不设定这个就好了

**Comment by maddenBoy** [comment]
我并没有设置tabTextColorHoverSegment，但它有绑定默认值，我无法完全去除该效果![image](https://user-images.githubusercontent.com/71129660/190903174-fb77f3f8-7c35-4e76-b74a-c8034853324a.png)

**Comment by maddenBoy** [comment]
> `tabTextColorHoverSegment` 只对 `segment` 类型的生效，所以如果不需要的话，不设定这个就好了

我并没有设置tabTextColorHoverSegment，但它必须会绑定默认值，我无法完全去除hover绑定的效果![image](https://user-images.githubusercontent.com/71129660/190903174-fb77f3f8-7c35-4e76-b74a-c8034853324a.png)

**Comment by 07akioni** [comment]
> > `tabTextColorHoverSegment` 只对 `segment` 类型的生效，所以如果不需要的话，不设定这个就好了
> 
> 我并没有设置tabTextColorHoverSegment，但它必须会绑定默认值，我无法完全去除hover绑定的效果![image](https://user-images.githubusercontent.com/71129660/190903174-fb77f3f8-7c35-4e76-b74a-c8034853324a.png)

<img width="527" alt="image" src="https://user-images.githubusercontent.com/18677354/190913214-b97fdfa9-e3b6-4cdf-a7ea-4b5a7a5e2897.png">

**Comment by maddenBoy** [comment]
> > > `tabTextColorHoverSegment` 只对 `segment` 类型的生效，所以如果不需要的话，不设定这个就好了
> > 
> > 
> > 我并没有设置tabTextColorHoverSegment，但它必须会绑定默认值，我无法完全去除hover绑定的效果![image](https://user-images.githubusercontent.com/71129660/190903174-fb77f3f8-7c35-4e76-b74a-c8034853324a.png)
> 
> <img alt="image" width="527" src="https://user-images.githubusercontent.com/18677354/190913214-b97fdfa9-e3b6-4cdf-a7ea-4b5a7a5e2897.png">
可能举的例子有点误解，我的意思是想做到不要这个hover效果，某些情况下只想要一个正常的效果和active的效果，hover的字体效果在一些场景下并不好，因为它存在默认值，我无法完全去除这个hover效果，举这个改变颜色的例子只是想体现这种场景

**Comment by 07akioni** [comment]
> 

可以把 hover 的颜色配制成和普通状态颜色一致，内置的行为确实是有 hover 这个变量的

**Comment by maddenBoy** [comment]
> > 
> 
> 可以把 hover 的颜色配制成和普通状态颜色一致，内置的行为确实是有 hover 这个变量的

但有些场景配置什么色似乎都不合适，例如active的字和默认的字配的是反色，正常状态下效果还是可以的，但受到hover影响，鼠标移上去时效果会很差，如果无法去除hover的效果，感觉是不是要加个tabTextColorHoverActiveSegment的配置会好一些，用于区分acitve的hover和普通状态的hover
这个鼠标未移入时的效果
![image](https://user-images.githubusercontent.com/71129660/191050881-36cde62f-4432-4de9-9cd9-02c22e2ed102.png)
这是鼠标移入时的效果
![image](https://user-images.githubusercontent.com/71129660/191051093-a01f3a50-e562-48c3-b20f-76d08fc3ad66.png)

**Comment by 07akioni** [comment]
> > > 
> > 
> > 
> > 可以把 hover 的颜色配制成和普通状态颜色一致，内置的行为确实是有 hover 这个变量的
> 
> 但有些场景配置什么色似乎都不合适，例如active的字和默认的字配的是反色，正常状态下效果还是可以的，但受到hover影响，鼠标移上去时效果会很差，如果无法去除hover的效果，感觉是不是要加个tabTextColorHoverActiveSegment的配置会好一些，用于区分acitve的hover和普通状态的hover 这个鼠标未移入时的效果 ![image](https://user-images.githubusercontent.com/71129660/191050881-36cde62f-4432-4de9-9cd9-02c22e2ed102.png) 这是鼠标移入时的效果 ![image](https://user-images.githubusercontent.com/71129660/191051093-a01f3a50-e562-48c3-b20f-76d08fc3ad66.png)

我能理解了，这才是问题的关键

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
