### ISSUE TITLE
<n-list/> implement virtual scrolling（<n-list/> 组件提供虚拟滚动）

### ISSUE THREAD

**Issue by NoahCodeGG** [tusen-ai/naive-ui#3719]
### This function solves the problem (这个功能解决的问题)
Large data volume <list-item/> rendering lag problem（大数据量 <list-item/> 渲染卡顿问题）
### Expected API (期望的 API)
```
<n-list
    :data="data"
    :max-height="250"
    :scroll-x="1800"
    virtual-scroll
  >
    <template v-slot="{ item, index }">
     </template>
</n-list>
```

**Comment by 07akioni** [comment]
Won't do.

You can use some third party virtual list component.

**Comment by mlesin** [comment]
With third party virtual list components it's pretty tricky to get these lists to work inside n-scrollbar to get it's nice consistent look in all browsers
