### ISSUE TITLE
NInput 能否支持键盘触发事件

### ISSUE THREAD

**Issue by Congb19** [tusen-ai/naive-ui#3725]
### This function solves the problem (这个功能解决的问题)
NInput 能否支持键盘触发事件 on-keypress
例如 输入完文字后单击Enter键 直接触发搜索事件 等场景
### Expected API (期望的 API)
on-keypress，on-enter，...

**Comment by Congb19** [comment]
好像已有on-keyup....但官网文档的API里没写🤔

**Comment by 07akioni** [comment]
> 好像已有on-keyup....但官网文档的API里没写🤔

这个是 Vue 的行为，原生事件绑上去也能得到结果

**Comment by Congb19** [comment]
> > 好像已有on-keyup....但官网文档的API里没写🤔
> 
> 这个是 Vue 的行为，原生事件绑上去也能得到结果

感谢回复，是我学艺不精了🙇‍
