### ISSUE TITLE
在 Nuxt3 中使用 NDatePicker 组件导致无法打包。

### ISSUE THREAD

**Issue by hmingv** [tusen-ai/naive-ui#3727]
### TuSimple/naive-ui version (版本)
2.33.3

### Vue version (Vue 版本)
3.2.39

### Browser and its version (浏览器及其版本)
Chrome(105.0.5195.126)

### System and its version (系统及其版本)
Windows(11)

### Node version (Node 版本)
16.15.1

### Reappearance link (重现链接)
https://codesandbox.io/p/github/productdevbook/oku-nuxt3-template/csb-u4eoio/draft/happy-cloud?file=%2Fsrc%2Fcomponents%2Fstarter.vue&selection=%5B%7B%22endColumn%22%3A21%2C%22endLineNumber%22%3A25%2C%22startColumn%22%3A21%2C%22startLineNumber%22%3A25%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl842inq4000xlrhr4cmdc3ev%2522%252C%2522openFiles%2522%253A%255B%2522%252Fsrc%252Fplugins%252Fnaive-ui.ts%2522%252C%2522%252Fsrc%252Fcomponents%252Fstarter.vue%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%252C%2522key%2522%253A%2522cl842o0a1077b356hdrm4ci5u%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cl842kqwb002vlrhr39xqd22o%2522%252C%2522key%2522%253A%2522cl842kqk905zo356h08adc5no%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cl842k97y05pz356h9ezvfnsg%2522%252C%2522isMinimized%2522%253Afalse%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cl842k6yw05o1356homnrlohl%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D

### Reappearance steps (重现步骤)
安装 Nuxt3 框架，并安装 naive-ui，然后在组件内使用 NDatePicker 组件。

执行命令打包程序， nuxt build

### Expected results (期望的结果)
正常打包，并可以访问

### Actual results (实际的结果)
 WARN  'date-fns/esm.js' is imported by .nuxt/dist/server/_nuxt/500.380f286f.js, but could not be resolved – treating it as an external dependency

**Comment by 07akioni** [comment]
这个实际上是 nuxt 的 bug，它每个 rc 之后都会挂掉一些东西，我看看有没有办法可以通过 nuxt 的配置解决

**Comment by hmingv** [comment]
> 这个实际上是 nuxt 的 bug，它每个 rc 之后都会挂掉一些东西，我看看有没有办法可以通过 nuxt 的配置解决

辛苦您，如果您有任何解决方案那太好了，我现在只能禁止在项目中使用此组件，但导致部分功能不可用。。。

我目前升级到了 RC.10，是存在该问题的。

其他组件都运行的很好。

**Comment by newbill** [comment]
也遇到了，同样 RC10

**Comment by Baiyuetribe** [comment]
transpile加上`date-fns`可以解决。另外n-tooltip在SSR模式下提示document不存在。
`transpile:['date-fns']`

**Comment by hmingv** [comment]
> transpile加上`date-fns`可以解决。另外n-tooltip在SSR模式下提示document不存在。 `transpile:['date-fns']`

谢谢，您提供的方案有效！

另外，关于您碰到的 提示 document 不存在的问题，我也碰到过。

我的错误来源是 `@css-render/vue3-ssr` 依赖。

当时的解决方案是删除node_modules并将 `@css-render/vue3-ssr` 安装固定版本 0.15.10。

不过目前我使用 0.15.11 也没再碰到问题。

**Comment by 07akioni** [comment]
> > transpile加上`date-fns`可以解决。另外n-tooltip在SSR模式下提示document不存在。 `transpile:['date-fns']`
> 
> 谢谢，您提供的方案有效！
> 
> 另外，关于您碰到的 提示 document 不存在的问题，我也碰到过。
> 
> 我的错误来源是 `@css-render/vue3-ssr` 依赖。
> 
> 当时的解决方案是删除node_modules并将 `@css-render/vue3-ssr` 安装固定版本 0.15.10。
> 
> 不过目前我使用 0.15.11 也没再碰到问题。

对，这个是专门修过的，后面就好了
