### ISSUE TITLE
upLoad组件百分比进度显示 （数字进度）

### ISSUE THREAD

**Issue by WHYHAHA** [tusen-ai/naive-ui#3728]
### This function solves the problem (这个功能解决的问题)
upLoad组件希望添加一个支持显示 数字进度功能 目前只有进度条没有显示具体数字进度
### Expected API (期望的 API)
upLoad组件希望添加一个支持显示 数字进度功能 目前只有进度条没有显示具体数字进度

**Comment by 07akioni** [comment]
暂时没有这个打算，感觉体验变化不会很明显
