### ISSUE TITLE
希望增加周选择器以及表格列宽拖拽功能

### ISSUE THREAD

**Issue by zhangke1722** [tusen-ai/naive-ui#3729]
### This function solves the problem (这个功能解决的问题)
目前naiveUI在项目开发中,部分功能暂时还无法满足,希望可以增加周选择器以及表格列宽拖能,这两个常用的功能,请问下有计划在排期吗?
### Expected API (期望的 API)
<n-date-picker type="week" />周选择器
 <n-data-table bordered />   或者 <n-data-table column-resizable/>  列宽调整表格

**Comment by equt** [comment]
- 关于周的选择可以参考 https://github.com/tusen-ai/naive-ui/issues/2676
- 表格列宽 https://github.com/tusen-ai/naive-ui/issues/3165
