### ISSUE TITLE
ts类型丢失，无法进行类型提示

### ISSUE THREAD

**Issue by laterdays** [tusen-ai/naive-ui#3730]
### TuSimple/naive-ui version (版本)
2.33.3

### Vue version (Vue 版本)
3.2.39

### Browser and its version (浏览器及其版本)
last

### System and its version (系统及其版本)
windows

### Node version (Node 版本)
last

### Reappearance link (重现链接)
https://codesandbox.io/s/*

### Reappearance steps (重现步骤)

ts：4.8.2
vscode: 1.71.2

ts类型丢失，无法进行类型提示

![image](https://user-images.githubusercontent.com/112848218/190640105-714d7047-95e9-4895-8ac9-dc3808259b6c.png)

**Comment by laterdays** [comment]
@07akioni

**Comment by 07akioni** [comment]
type 不接受空字符串，你的代码里传了空字符串
