### ISSUE TITLE
[Nuxt3] useOsTheme方法在服务端和客户端获取到的值不一致导致自动暗黑无法使用

### ISSUE THREAD

**Issue by lvzhenbo** [tusen-ai/naive-ui#3732]
### TuSimple/naive-ui version (版本)
2.33.3

### Vue version (Vue 版本)
3.2.39

### Browser and its version (浏览器及其版本)
105.0.5195.127

### System and its version (系统及其版本)
Windows 10 v21H2

### Node version (Node 版本)
Node 16

### Reappearance link (重现链接)
https://github.com/lvzhenbo/nuxt-app

### Reappearance steps (重现步骤)
创建一个nuxt 3 RC10的项目，安装naive ui，使用全局化配置组件，引入useOsTheme方法，执行命令启动项目

### Expected results (期望的结果)
根据浏览器的配置自动暗黑能够使用

### Actual results (实际的结果)
自动暗黑无法使用

### Remarks (补充说明)
原因是服务端和客户端的值不一致，服务端无法获取到正确的值
同样问题的链接：https://blog.csdn.net/loveaborn/article/details/125011604

**Comment by SngBlog** [comment]
这个似乎没有什么好办法解决，http请求里面又没有 携带当前用户的 明暗主题色信息
![image](https://user-images.githubusercontent.com/59474029/190844958-fa5aed39-5088-4ba1-b07b-63633f468333.png)
我之前也是遇到这个问题，计算属性不正确，会导致水合失败，所以我干脆不用计算属性，把globaltheme抽出来ref包裹在直接watch监听osThemeRef的值就可以了

**Comment by lvzhenbo** [comment]
> 这个似乎没有什么好办法解决，http请求里面又没有 携带当前用户的 明暗主题色信息 ![image](https://user-images.githubusercontent.com/59474029/190844958-fa5aed39-5088-4ba1-b07b-63633f468333.png) 我之前也是遇到这个问题，计算属性不正确，会导致水合失败，所以我干脆不用计算属性，把globaltheme抽出来ref包裹在直接watch监听osThemeRef的值就可以了

我试了试watch还是不行，不过我用onMounted做到了（可能

**Comment by 07akioni** [comment]
服务端理论上是不可能拿到客户端的主题，所以只能在客户端一侧处理

**Comment by SngBlog** [comment]
建议默认白色主题，然后在客户端的时候再进行一次检测，再去修改一次
