### ISSUE TITLE
在 Nuxt3 框架中同时使用 Naive-UI 和 Tailwind 存在样式冲突

### ISSUE THREAD

**Issue by hmingv** [tusen-ai/naive-ui#3733]
### This function solves the problem (这个功能解决的问题)
解决潜在的样式冲突

https://www.naiveui.com/zh-CN/os-theme/docs/style-conflict

官方文档已经提供了一个解决方案，但在 Nuxt3 中无法完全实现。
### Expected API (期望的 API)
可以避免样式冲突

**Comment by 07akioni** [comment]
只有 tailwind 自己才能解决这个问题，不然的话需要手动挪一下样式的位置

**Comment by kuizuo** [comment]
nuxt3 要解决的话可以这样

创建 `plugins/naive-ui.ts` 文件内容如下

```typescript
import { defineNuxtPlugin } from '#app'

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.hook('app:mounted', () => {
    const meta = document.createElement('meta')
    meta.name = 'naive-ui-style'
    document.head.appendChild(meta)
  })
})
```

**Comment by anton-liam** [comment]
nuxt3在开起ssr的情况下不行哦.  服务端预先渲染了. naive-ul-style样式就没用了

**Comment by czhlin** [comment]
其实保持：1.tailwind 2.naive-ui 3.main.css的顺序是最合理的
所以可以在html中这样修改

In fact, maintaining the order of 1.tailwind 2.naive-ui 3.main.css is the most reasonable, so it can be modified like this in html
```html
<link rel="stylesheet" href="/tailwind.css" />
<meta name="naive-ui-style" />
```
```typescript
// main.ts
import 'uno.css'
import '~/styles/main.css'
````

**Comment by wooly99** [comment]
试试在 tailwind 中增加配置
参考：[https://v3.tailwindcss.com/docs/configuration#important](https://v3.tailwindcss.com/docs/configuration#important)

// 确保tailwind的优先级 高于Naive UI组件库
important: '#__nuxt'
