### ISSUE TITLE
时间选择器

### ISSUE THREAD

**Issue by xychstudy** [tusen-ai/naive-ui#3734]
### This function solves the problem (这个功能解决的问题)
用户选择时间不是一个时间段，而是可以点击选择其中的几天，比如出差审批和周末冲突了，需要手动排除周末的时间
### Expected API (期望的 API)
像element-plus中，日期选择器type有一个dates类型，可以选择其中的某几天

**Comment by Sepush** [comment]
或许你应该使用 date-piker

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
