### ISSUE TITLE
组件库中的关闭按钮能否支持自定义

### ISSUE THREAD

**Issue by maddenBoy** [tusen-ai/naive-ui#3736]
### TuSimple/naive-ui version (版本)
2.33.3

### Vue version (Vue 版本)
3.2.39

### Browser and its version (浏览器及其版本)
Chrome（105.0.5195.127）

### System and its version (系统及其版本)
window 11

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/dialog

### Reappearance steps (重现步骤)
1、Dialog、Model、Tag等有关闭按钮的组件，关闭按钮可以类似icon那样传入vnode进行自定义吗？

### Expected results (期望的结果)
Dialog、Model、Tag等有关闭按钮的组件，关闭按钮可以类似icon那样传入vnode进行自定义

### Actual results (实际的结果)
Dialog、Model、Tag等有关闭按钮的组件，无法自定义关闭按钮

**Comment by 07akioni** [comment]
track in https://github.com/tusen-ai/naive-ui/issues/3597
