### ISSUE TITLE
组件库中每次显示下拉框时控制台会多一条警告

### ISSUE THREAD

**Issue by maddenBoy** [tusen-ai/naive-ui#3737]
### TuSimple/naive-ui version (版本)
2.33.3

### Vue version (Vue 版本)
3.2.39

### Browser and its version (浏览器及其版本)
Chrome（105.0.5195.127）

### System and its version (系统及其版本)
window 11

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/data-table

### Reappearance steps (重现步骤)
1、鼠标移入或点击任意带下拉框的组件时，控制台会出现一条Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.警告（如果这并不是很重要，当我没说）

### Expected results (期望的结果)
鼠标移入或点击任意带下拉框的组件时，无警告。

### Actual results (实际的结果)
鼠标移入或点击任意带下拉框的组件时，有警告。

### Remarks (补充说明)
![image](https://user-images.githubusercontent.com/71129660/190911786-558accfa-c70b-4a52-ac76-f40d04c509c3.png)

**Comment by 07akioni** [comment]
在可以 passive 的事件上使用 preventDefault 是故意的，为了实现某种效果，所以其实是没事。

浏览器这个提示我不太清楚有啥去掉的方法，但是应该没啥事。
