### ISSUE TITLE
NInput error with hsl theme primary color

### ISSUE THREAD

**Issue by M1CK431** [tusen-ai/naive-ui#3744]
### TuSimple/naive-ui version (版本)
2.33.3

### Vue version (Vue 版本)
3.2.39

### Browser and its version (浏览器及其版本)
Chrome/104.0.5112.126

### System and its version (系统及其版本)
Archlinux

### Node version (Node 版本)
18.9.0

### Reappearance link (重现链接)
https://github.com/M1CK431/naiveui-input-issue

### Reappearance steps (重现步骤)
- Start the dev server with `yarn dev`
- Open it in your browser
- Open dev tools console

### Expected results (期望的结果)
`NInput` component is displayed and no console error

### Actual results (实际的结果)
No render at all and console error:
```
Uncaught Error: [seemly/rgba]: Invalid color value hsl(350deg 78% 56%).
```

### Remarks (补充说明)
The key here is the use of `hsl` color as theme `primaryColor`.
I try with `NButton` component and it works so it really seems to be specific with `NInput` but I haven't try with all NaiveUI component.

**Comment by M1CK431** [comment]
Up! :up:

**Comment by 07akioni** [comment]
Currently it's the expected behavior. Naive need some color computation to create theme variables.

**Comment by 07akioni** [comment]
<img width="675" alt="image" src="https://user-images.githubusercontent.com/18677354/192145102-48af1417-694f-4eeb-be56-82d45987c07e.png">

**Comment by M1CK431** [comment]
> Currently it's the expected behavior. Naive need some color computation to create theme variables
Excuse me @07akioni , I'm not sure to well understand nor your answer, nor the reason why this issue is closed "as completed" without any linked merged pull request nor your screenshot...

Do you means that NaiveUI doesn't support hsl colors in theme?

**Comment by M1CK431** [comment]
@07akioni Is there a chance to make use of `hslRegex` (from https://github.com/07akioni/seemly/blob/bbc56fd8cbfbb64cbe6847a6ec7b2617d6b320a0/src/color/index.ts#L16) in `rgba` (from https://github.com/07akioni/seemly/blob/bbc56fd8cbfbb64cbe6847a6ec7b2617d6b320a0/src/color/index.ts#L96) and so any hsl colors will be converted in rgb using `hsl2rgb` (from https://github.com/07akioni/seemly/blob/bbc56fd8cbfbb64cbe6847a6ec7b2617d6b320a0/src/color/convert.ts#L88)? I guess it will effectively solve this issue.

In addition, the [theme documentation](https://www.naiveui.com/en-US/light/docs/customize-theme) should explicit supported colors formats (for example, I'm not sure it's technically possible to handle alpha channel since `changeColor` will overwrite it for many colors, like `boxShadowFocusWarning` in your screenshot).

wdyt?

**Comment by 07akioni** [comment]
> there a chance to make use of `hslRegex` (from

It doesn't mean hsl can't be used in anywhere. Only some variables need rgb format color. It would be cumbersome to let specify every variables' color format.

**Comment by 07akioni** [comment]
> @07akioni Is there a chance to make use of `hslRegex` (from https://github.com/07akioni/seemly/blob/bbc56fd8cbfbb64cbe6847a6ec7b2617d6b320a0/src/color/index.ts#L16) in `rgba` (from https://github.com/07akioni/seemly/blob/bbc56fd8cbfbb64cbe6847a6ec7b2617d6b320a0/src/color/index.ts#L96) and so any hsl colors will be converted in rgb using `hsl2rgb` (from https://github.com/07akioni/seemly/blob/bbc56fd8cbfbb64cbe6847a6ec7b2617d6b320a0/src/color/convert.ts#L88)? I guess it will effectively solve this issue.
> 
> In addition, the [theme documentation](https://www.naiveui.com/en-US/light/docs/customize-theme) should explicit supported colors formats (for example, I'm not sure it's technically possible to handle alpha channel since `changeColor` will overwrite it for many colors, like `boxShadowFocusWarning` in your screenshot).
> 
> wdyt?

It is possible. If `changeColor` can support more format that's great.

**Comment by M1CK431** [comment]
Ok thanks, I will open a PR on seemly repo today. However, I don't use typescript nor unit test, so probably there will be one more commit to add after my work, sorry for that. I hope it will still be okay for you to accept the change and complete the few missing things just after... :pleading_face:

**Comment by M1CK431** [comment]
Hooo, just to tell you, thanks to your code I learn that, in JS, variable affectation return the affected value. Thanks, it will be useful in my code base too :kissing_heart:

**Comment by 07akioni** [comment]
> Ok thanks, I will open a PR on seemly repo today. However, I don't use typescript nor unit test, so probably there will be one more commit to add after my work, sorry for that. I hope it will still be okay for you to accept the change and complete the few missing things just after... 🥺

You can check at that PR, there are some small issues.
