### ISSUE TITLE
on-last-row-scroll event for data-table component

### ISSUE THREAD

**Issue by enricobasso** [tusen-ai/naive-ui#3745]
### This function solves the problem (这个功能解决的问题)
I'd like to realize an infinite scrolling with the data-table component. To do so I think it would be necessary to know when the user scrolls to the end of the rows so that one can fetch the next set of data. 
### Expected API (期望的 API)
`<n-data-table :on-last-row-scroll="fetchNextPage" />`

**Comment by 07akioni** [comment]
onScroll would expose a event. You can check DOM prop on it's target to know whether it's scrolled to the bottom.
