### ISSUE TITLE
Tree组件可以控制checkbox的显示，以及checkbox点击的事件

### ISSUE THREAD

**Issue by sky124380729** [tusen-ai/naive-ui#3746]
### This function solves the problem (这个功能解决的问题)
1.目前只能控制Checbox的Disabled的，不能控制显示
2.目前只能拿到Checked keys变化的事件，没有checkbox点击的事件
### Expected API (期望的 API)
1. TreeOption Properties {
  checkable: boolean //When Tree is checkable, set TreeNode display Checkbox or not
}
2. onCheck: (checkedKeys, e:{checked: bool, checkedNodes, node, event}) => void

**Comment by sky124380729** [comment]
这个onCheck对我来说很重要，我需要拿到当前节点是选中还是取消，还有内部的option。
目前只有checkedKeys更新事件，取消选中的时候我拿不到子节点的数据以及option

**Comment by sky124380729** [comment]
不要沉呀

**Comment by sky124380729** [comment]
help help

**Comment by Ikki-Dai** [comment]
+1 
want to disable uncheckable on parent node and only keep it expandable while click
also want childern node is checkable

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
