### ISSUE TITLE
骨架屏和加载组件可否增加延迟属性

### ISSUE THREAD

**Issue by Aicmortal** [tusen-ai/naive-ui#3747]
### This function solves the problem (这个功能解决的问题)
延迟显示加载和骨架屏效果的时间，用于防止请求速度过快引起的闪烁
### Expected API (期望的 API)

| API | 描述 |
| ------------- | ------------- |
| delay  | 延迟显示加载效果的时间，用于防止请求速度过快引起的闪烁 |
| loadingProps   | DataTable、Card等组件支持透传loading的Props来设置delay  |

**Comment by 07akioni** [comment]
可以加
