### ISSUE TITLE
Select选择器的勾选项后面的图标能否隐藏或自定义

### ISSUE THREAD

**Issue by maddenBoy** [tusen-ai/naive-ui#3749]
### TuSimple/naive-ui version (版本)
2.33.3

### Vue version (Vue 版本)
3.2.39

### Browser and its version (浏览器及其版本)
Chrome（105.0.5195.127）

### System and its version (系统及其版本)
Window 11

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/select

### Reappearance steps (重现步骤)
1、点击Select组件，选择面板中任意选择一项

### Expected results (期望的结果)
期望Select组件的选择项后面的√可隐藏或自定义（看到Pagination中的pagition-size中可去掉选择的√，但不知道是怎么实现的）

### Actual results (实际的结果)
无法对Select组件的选择项后面的√隐藏或自定义

### Remarks (补充说明)
![image](https://user-images.githubusercontent.com/71129660/191229377-55684f1d-ce0e-4f37-a199-68c6cd4eafc5.png)

**Comment by OrbisK** [comment]
i think this is not a bug. This might be a feature request.

**Comment by equt** [comment]
可以直接使用 `render`，估计 @07akioni 不太愿意再开一个口子做这个
