### ISSUE TITLE
覆写主题后select下拉框丢失

### ISSUE THREAD

**Issue by Preyou** [tusen-ai/naive-ui#3750]
### TuSimple/naive-ui version (版本)
2.33.3

### Vue version (Vue 版本)
3.2.39

### Browser and its version (浏览器及其版本)
89.0.4389.128

### System and its version (系统及其版本)
win11

### Reappearance link (重现链接)
https://codesandbox.io/embed/still-brook-i5nzko?fontsize=14&hidenavigation=1&theme=dark

### Reappearance steps (重现步骤)
点击选项展开按钮

### Expected results (期望的结果)
出现下拉框

### Actual results (实际的结果)
下拉框内没内容

**Comment by 07akioni** [comment]
Height 只支持 PX，不然没办法支持虚拟滚动了。

或者你可以设定  :virtual-scroll="false"，这样也可以让你的设定生效
