### ISSUE TITLE
颜色选择器增加预定义选项

### ISSUE THREAD

**Issue by 2509989976** [tusen-ai/naive-ui#3752]
### This function solves the problem (这个功能解决的问题)
方便在多次选择颜色时，能快速选择特定的颜色值。
可参考ElementUI：https://element-plus.gitee.io/zh-CN/component/color-picker.html#%E9%A2%84%E5%AE%9A%E4%B9%89%E9%A2%9C%E8%89%B2

### Expected API (期望的 API)
新增可选属性 predefine：Array | null =["#FFFFFF","#FFDDCC"]

**Comment by equt** [comment]
[Swatches](https://www.naiveui.com/zh-CN/os-theme/components/color-picker#swatches.vue) 不能满足使用情景吗
