### ISSUE TITLE
input 密码icon,  jsx插槽不生效

### ISSUE THREAD

**Issue by zhoufanglu** [tusen-ai/naive-ui#3753]
### TuSimple/naive-ui version (版本)
2.30.8

### Vue version (Vue 版本)
3.2.39

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
win10

### Reappearance steps (重现步骤)
```js
<NInput
                    type='password'
                    placeholder={t('password.confirm_password_tips')}
                    v-model={[this.passwordForm.confirmPassword, 'value']}
                  >
                    {{
                      passwordVisibleIcon: () => (
                        <NIcon>
                          {{
                            default: () =>
                              h(svgIcon, {
                                icon: '#icon-shanchu1'
                              })
                          }}
                        </NIcon>
                      ),
                      passwordInvisibleIcon: () => (
                        <NIcon>
                          {{
                            default: () =>
                              h(svgIcon, {
                                icon: '#icon-shanchu1'
                              })
                          }}
                        </NIcon>
                      )
                    }}
                  </NInput>
```

### Expected results (期望的结果)
显示icon

### Actual results (实际的结果)
icon不显示

**Comment by equt** [comment]
- 上面这段代码如果是 Vue SFC 的 template，那么 [Slots 用法错了](https://vuejs.org/guide/components/slots.html#named-slots)
- 上面那段代码如果是 JSX 语法，那么 [`v-modal` 就是不合法的](https://vuejs.org/guide/extras/render-function.html#v-model)

**Comment by zhoufanglu** [comment]
> 

v-modal

> * 上面这段代码如果是 Vue SFC 的 template，那么 [Slots 用法错了](https://vuejs.org/guide/components/slots.html#named-slots)
> * 上面那段代码如果是 JSX 语法，那么 [`v-modal` 就是不合法的](https://vuejs.org/guide/extras/render-function.html#v-model)

v-model明确是生效了
是jsx语法， 请问插槽按钮语法有问题吗？ `prefix`插槽是可用的
![image](https://user-images.githubusercontent.com/24451091/191405908-71c053b7-b694-4933-8abb-a4dda358ead6.png)

**Comment by jizai1125** [comment]
不支持驼峰
![image](https://user-images.githubusercontent.com/33979706/191438842-cd41559f-33b1-40cf-a4ab-d79aacdc7451.png)

**Comment by jizai1125** [comment]
我也是用 jsx 语法，我试了我这边是生效了

![image](https://user-images.githubusercontent.com/33979706/191444351-a7aacf23-cfed-4297-9a94-60da773cab8c.png)

**Comment by zhoufanglu** [comment]
> 

-_-|| 解决了 是这个属性没加        `show-password-on='click' `
