### ISSUE TITLE
Cascader:期望鼠标移到因文字太长而省略的选项可以悬浮显示全部文字

### ISSUE THREAD

**Issue by yourxiaomai** [tusen-ai/naive-ui#3754]
### This function solves the problem (这个功能解决的问题)
无法查看全部文字全会影响用户理解这个选项
### Expected API (期望的 API)
期望自带属性:鼠标移到因文字太长而省略的选项可以悬浮显示全部文字

**Comment by xinrays** [comment]
使用 render-label 可以自行实现这个功能

**Comment by xinrays** [comment]
此功能暂时可通过render-label自行实现

**Comment by Sepush** [comment]
tack in https://github.com/tusen-ai/naive-ui/issues/2381
