### ISSUE TITLE
data-table tree 设置 ellipsis

### ISSUE THREAD

**Issue by lx11573** [tusen-ai/naive-ui#3755]
### TuSimple/naive-ui version (版本)
2.33.3

### Vue version (Vue 版本)
3.2.39

### Browser and its version (浏览器及其版本)
103.0.5060.134

### System and its version (系统及其版本)
11.5.2

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/data-table#tree.vue

### Reappearance steps (重现步骤)
当使用树形表格时，某一列设置了固定宽度且 ellipsis: true后，如果文字溢出，不会显示省略号，而是换行

### Expected results (期望的结果)
可以正常显示

### Actual results (实际的结果)
显示异常

### Remarks (补充说明)
![image](https://user-images.githubusercontent.com/12030247/191704287-7f0c2f32-ba31-4a03-9da9-82bd83654cd8.png)

**Comment by 07akioni** [comment]
这个感觉不太好处理
