### ISSUE TITLE
NTransfer has no min or max selection

### ISSUE THREAD

**Issue by JarneStaalPXL** [tusen-ai/naive-ui#3757]
### This function solves the problem (这个功能解决的问题)
Please put a minimum and maximum selection on NTransfer.
### Expected API (期望的 API)
I propose you built this functionality in like props of NTransfer.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
