### ISSUE TITLE
Improve layout of month, year and quarter pickers

### ISSUE THREAD

**Issue by jdwit** [tusen-ai/naive-ui#3758]
### This function solves the problem (这个功能解决的问题)
The layout of month, year and quarter types of the `DatePicker` component are not intuitive at this time. This also applies to the 'range' versions for month, year and quarter. Other libraries such as [Ant Design](https://ant.design/components/date-picker/#components-date-picker-demo-range-picker) and [Arco Design](https://arco.design/vue/en-US/component/date-picker#range) use the same type of layout for 'normal' date range and year, month and quarter ranges. This is a layout that is expected by users.

![](https://i.stack.imgur.com/F1O5w.png)

My request is to improve the layout of month, year quarter (range)pickers following the example by Ant Design. I think this would be a great improvement to the library.
### Expected API (期望的 API)
This request is about visual layout only; no API changes needed.

**Comment by OrbisK** [comment]
> We won't adopt this layout since it's simply hard to maintain and needs lots of work.
>
> `07akioni` on [discord](https://discord.com/channels/842427094214770768/842427094214770771/1024673431284875326)

**Comment by 07akioni** [comment]
We won't add it since it's simply too complex to change current behavior.
