### ISSUE TITLE
n-data-table开启虚拟滚动virtual-scroll后，对于有展开内容(子页面)的表格点击后滚动到底部时无法继续滚动网页

### ISSUE THREAD

**Issue by wj007881** [tusen-ai/naive-ui#3760]
### TuSimple/naive-ui version (版本)
2.33.3

### Vue version (Vue 版本)
3.2.39

### Browser and its version (浏览器及其版本)
edge105

### System and its version (系统及其版本)
windows11

### Reappearance link (重现链接)
https://codesandbox.io/s/awesome-lumiere-npw838?file=/src/Demo.vue

### Reappearance steps (重现步骤)
添加子页面为展开内容

### Expected results (期望的结果)
可以继续滚动到页面底部

### Actual results (实际的结果)
停止滚动

**Comment by wj007881** [comment]
和设置的最大高度有关，当超过了最大高度时就无法滚动了

**Comment by wj007881** [comment]
顺带问问，有没有办法更改表格的滚动条样式，，太细了不好控制

**Comment by 07akioni** [comment]
我觉得这可以看成是个 bug，我想办法改一下

**Comment by 07akioni** [comment]
> 顺带问问，有没有办法更改表格的滚动条样式，，太细了不好控制

滚动条暂时没有，也考虑加一下

**Comment by 07akioni** [comment]
我试了试在文档网站没遇到这个问题，具体是怎么复现？

**Comment by 07akioni** [comment]
https://user-images.githubusercontent.com/18677354/192939903-bbe05558-d993-410d-9601-034117d66ca3.mov

**Comment by 07akioni** [comment]
没能复现，有明确复现后再打开
