### ISSUE TITLE
Menu 是否可以新增一个选项，用来让其超出边界时自动变为可滚动

### ISSUE THREAD

**Issue by poerlang** [tusen-ai/naive-ui#3761]
### This function solves the problem (这个功能解决的问题)
menu item 太多的情况下，会把整改页面撑开，产生滚动条，布局会被打乱，如果有这个新增特性，整个页面不会被撑开，或者如果 body 使用了 over-flow：hiden 的情况下，此时如果有这个新特性，超出部分的菜单项也不会被遮挡隐藏
![image](https://user-images.githubusercontent.com/3243514/191906599-8113f2a3-92d3-4047-a693-980c8b047f4c.png)
### Expected API (期望的 API)
![image](https://user-images.githubusercontent.com/3243514/191906864-4cabf5b7-a6b2-4343-8769-6b5dbdd8470b.png)

指定一个 css selector， 如果超出这个容器，则菜单可以自动地以容器边界为限，menu 可以在界限内滚动，而不是超出边界。
over-flow-scroll-parent=" .a_panel "

**Comment by 07akioni** [comment]
我感觉这个是容器的问题，你只需要把容器设为可以溢出滚动的就好了

**Comment by poerlang** [comment]
确实，我漏看了文档一个属性（scrollable），给这个帖子补充一下。

这个属性不在 n-menu 的 API 里面，而是在 n-popover 的属性里面。
n-menu 可以通过 dropdown-props 这个属性来设置 menu 内部的  n-popover 的 scrollable 属性 。
