### ISSUE TITLE
表单中使用n-input时，trim修饰符不生效

### ISSUE THREAD

**Issue by cooperGao** [tusen-ai/naive-ui#3762]
### TuSimple/naive-ui version (版本)
2.33.3

### Vue version (Vue 版本)
3.2.39

### Browser and its version (浏览器及其版本)
Google Chrome-105.0.5195.127

### System and its version (系统及其版本)
Windows 11

### Node version (Node 版本)
v16.14.0

### Reappearance link (重现链接)
https://codesandbox.io/s/recursing-bhabha-6ftb4u?file=/src/App.vue

### Reappearance steps (重现步骤)
1. 在input组件的value属性后面添加trim修饰符；
2. 输入时，在输入值的前后都添加空格，打印出来的value是带空格的；
3. 结论是trim修饰符没有生效；

### Expected results (期望的结果)
希望支持文本框的trim属性

### Actual results (实际的结果)
trim修饰符没有生效

**Comment by Sepush** [comment]
没有实现.trim 自己在JS里面 trim一下就好 一行代码

**Comment by 07akioni** [comment]
文档网站有使用 allow-input 来实现 trim 的例子

**Comment by duanmw** [comment]
+1, 大多数人第一反应肯定是直接用.trim,  结果却只能增加几行代码实现😕

**Comment by 8debug** [comment]
> +1, 大多数人第一反应肯定是直接用.trim, 结果却只能增加几行代码实现😕

为了不同而不同😕？

**Comment by machao7** [comment]
up

**Comment by Yuan-ZW** [comment]
> 文档网站有使用 allow-input 来实现 trim 的例子

先不说 allow-input 用起来要多写几行代码

如果用 allow-input 来实现 trim，用户体验也特别差，举两个例子：
- 我想输入 `a b` 必须先输入 `ab` 再退回来补一个空格，否则根本打不出来
- 复制了一段前后带空格的文本无法粘贴（都怀疑自己复制了没，或者怀疑键盘坏了）

总之，建议还是实现一下 `.trim` 吧
