### ISSUE TITLE
data-table中，无法异步修改row的switch状态

### ISSUE THREAD

**Issue by laterdays** [tusen-ai/naive-ui#3764]
### TuSimple/naive-ui version (版本)
2.33.3

### Vue version (Vue 版本)
3.2.39

### Browser and its version (浏览器及其版本)
windows

### System and its version (系统及其版本)
windows

### Reappearance link (重现链接)
https://codesandbox.io/s/lucid-aj-rtkrpx?file=/src/Demo.vue

### Reappearance steps (重现步骤)
data-table中，无法异步修改row的switch状态

目前场景是：点击switch请求接口，根据接口返回数据来解决switch是true还是false，但目前data-table嵌套的switch好像无法实现 

```
    render(row) {
        return h(NSwitch, {
          defaultValue: row.state,
          onUpdateValue: () => handleChange(row),
        });
      },

const handleChange = (row: any) => {
    // 模拟接口
  setTimeout(() => {
    console.log(row.state);
  }, 2000);
   // 无法等待接口后修改switch状态
  row.state = false;
};
```

![image](https://user-images.githubusercontent.com/112848218/191972180-70bf20d3-6cbc-4a86-9ad3-e5f79aeb8082.png)

### Expected results (期望的结果)
支持接口请求后设置switch状态

### Actual results (实际的结果)
支持接口请求后设置switch状态

**Comment by amadeus711** [comment]
这是使用问题，解法如下：
https://codesandbox.io/s/relaxed-violet-gv19w4?file=/src/Demo.vue

**Comment by laterdays** [comment]
@amadeus711  但如果是shallowRef这种是无法生效的

**Comment by laterdays** [comment]
@amadeus711  https://codesandbox.io/s/sad-james-wio19r?file=/src/Demo.vue:1085-1585

```
const data = shallowRef(createData());
    const handleChange = (row, index) => {
      setTimeout(() => {
        // 模拟接口
        // 无法等待接口后修改switch状态
        console.log(row.state);
        data.value[index].state = false;
        triggerRef(data)
      }, 1000);
    };
``

**Comment by laterdays** [comment]
因为配合vueuse的useAxios，返回的是shallowRef类型数据，这就导致无法实现该功能

**Comment by laterdays** [comment]
数据已经变更，但是表格内的内容没有更新
https://codesandbox.io/s/fervent-ishizaka-7fbjq9?file=/src/Demo.vue:43-68
