### ISSUE TITLE
数据表格有超长带提示的省略异常

### ISSUE THREAD

**Issue by hqzh** [tusen-ai/naive-ui#3766]
### TuSimple/naive-ui version (版本)
2.33.3

### Vue version (Vue 版本)
3.2.39

### Browser and its version (浏览器及其版本)
 chrome 104.0.5112.81（正式版本） （64 位）

### System and its version (系统及其版本)
win11

### Reappearance link (重现链接)
https://codesandbox.io/s/amazing-violet-1u31mc

### Reappearance steps (重现步骤)
1、某列超长字段
2、省略提示不全

### Expected results (期望的结果)
显示完全或者支持传入弹窗宽度

### Actual results (实际的结果)
显示不完全

### Remarks (补充说明)
![image](https://user-images.githubusercontent.com/26128706/192088904-055040ee-4bf8-49d7-98b2-680ef0132831.png)
![image](https://user-images.githubusercontent.com/26128706/192088969-fab284bb-5049-492e-8cff-cd92e80e6afa.png)

**Comment by 07akioni** [comment]
可以给 ellipsis 设定为 `{ style: { maxWidth: '200px' }}` 之类的

**Comment by 07akioni** [comment]
<img width="1692" alt="截屏2022-09-25 20 58 03" src="https://user-images.githubusercontent.com/18677354/192144676-bc0fa216-816b-4d3a-9e70-163a2af2e7e8.png">

**Comment by hqzh** [comment]
可以支持table全局参数传入吗？@07akioni

**Comment by 07akioni** [comment]
> 可以支持table全局参数传入吗？@07akioni 项目中有省略号的columns都写一遍略显麻烦了点

暂时没有，说麻烦的话其实感觉还好，写个函数处理一下 columns 就好了

**Comment by hqzh** [comment]
> > 可以支持table全局参数传入吗？@07akioni 项目中有省略号的columns都写一遍略显麻烦了点
> 
> 暂时没有，说麻烦的话其实感觉还好，写个函数处理一下 columns 就好了

那不还是每次都要调用一下，哈哈哈
