### ISSUE TITLE
[SSR] Nuxt3 RC11 上传组件大概率打开的是文件夹选择，而不是正常的文件选择

### ISSUE THREAD

**Issue by lvzhenbo** [tusen-ai/naive-ui#3768]
### TuSimple/naive-ui version (版本)
2.33.3

### Vue version (Vue 版本)
3.2.39

### Browser and its version (浏览器及其版本)
105.0.5195.127

### System and its version (系统及其版本)
Win 10

### Node version (Node 版本)
16.17.1

### Reappearance link (重现链接)
https://github.com/lvzhenbo/nuxt-app

### Reappearance steps (重现步骤)
环境Nuxt3 RC11, naive-ui 2.33.3,在Form表单组件中使用Upload上传组件，点击上传组件

### Expected results (期望的结果)
打开的窗口为文件选择窗口

### Actual results (实际的结果)
只有极小概率打开的是正常的文件选择窗口，其他打开的都是文件夹选择窗口

### Remarks (补充说明)

https://user-images.githubusercontent.com/32427677/192118173-0e91cdcd-f0bf-406b-b9ba-ec6d40180045.mp4

**Comment by 07akioni** [comment]
这个有点奇怪，是不是因为 `webkitdirectory` 属性导致的？我感觉至少应该表现是一致的，不应该偶尔有偶尔没有

**Comment by lvzhenbo** [comment]
![image](https://user-images.githubusercontent.com/32427677/193549296-a47c3085-1fd1-4266-a8f2-bfafa62de23d.png)
确实很奇怪

**Comment by 07akioni** [comment]
> ![image](https://user-images.githubusercontent.com/32427677/193549296-a47c3085-1fd1-4266-a8f2-bfafa62de23d.png) 确实很奇怪

估计就是这个原因了，这个已经修复了，下个版本会发

**Comment by 07akioni** [comment]
fixed in 4a3a0406cc3a1caa9d7cc3b517e6aa8dd4a3ad18
