### ISSUE TITLE
无法通过vitetest测试

### ISSUE THREAD

**Issue by slgxmh** [tusen-ai/naive-ui#3769]
### TuSimple/naive-ui version (版本)
2.33.3

### Vue version (Vue 版本)
3.2.38

### Browser and its version (浏览器及其版本)
Edge(105.0.1343.50)

### System and its version (系统及其版本)
MacOS(12,6)

### Reappearance link (重现链接)
https://github.com/slgxmh/naive_ui_vitetest

### Reappearance steps (重现步骤)
```bash
pnpm i
pnpm exec -- vitest run -t "renders properly" src/components/__tests__/HelloWorld.spec.ts
```

### Expected results (期望的结果)
the test should pass.

### Actual results (实际的结果)
 FAIL  src/components/__tests__/HelloWorld.spec.ts [ src/components/__tests__/HelloWorld.spec.ts ]
 ❯ Object.compileFunction node:vm:352:18
 ❯ async /Users/xiaminghui/project/test_vue/bug/node_modules/.pnpm/date-fns@2.29.3/node_modules/date-fns/esm/index.js:194:32
SyntaxError: Cannot use import statement outside a module

**Comment by 07akioni** [comment]
You can try this:

<img width="272" alt="image" src="https://user-images.githubusercontent.com/18677354/193517225-bb742e6f-adf6-47d9-ae96-702807b8809e.png">

It works. I think the problem is that `date-fns` doesn't specified proper package type in `package.json`.

**Comment by 07akioni** [comment]
<img width="620" alt="image" src="https://user-images.githubusercontent.com/18677354/193517337-899728ff-6b17-4874-b5ed-753bff302e92.png">
