### ISSUE TITLE
data-table中，shallowRef数据已经更改，但是表格中的内容没有改变

### ISSUE THREAD

**Issue by laterdays** [tusen-ai/naive-ui#3771]
### TuSimple/naive-ui version (版本)
2.33.3

### Vue version (Vue 版本)
3.2.39

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
windows

### Reappearance link (重现链接)
https://codesandbox.io/s/fervent-ishizaka-7fbjq9?file=/src/Demo.vue:43-68

### Reappearance steps (重现步骤)
使用vueuse的useAxios，返回的data是shallowRef数据，但是triggerRef更新数据，数据已经变化，但是表格的视图没有改变

### Expected results (期望的结果)
表格视图跟随数据改变

### Actual results (实际的结果)
使用vueuse的useAxios，返回的data是shallowRef数据，但是triggerRef更新数据，数据已经变化，但是表格的视图没有改变

**Comment by laterdays** [comment]
```
const data = shallowRef(createData());
    const handleChange = (row, index) => {
      setTimeout(() => {
        console.log(row.state);
        data.value[index].state = false;
        triggerRef(data);
      }, 1000);
    };
```

**Comment by 07akioni** [comment]
这个应该是符合预期的，把 `response.data` 赋值给一个 `ref` 就行了

**Comment by laterdays** [comment]
@07akioni  但是使用了vueuse的responseData是shallowRef数据， 或者怎么能将shallowRef转为可用的ref给到表格。 https://github.com/vueuse/vueuse/blob/main/packages/integrations/useAxios/index.ts
![image](https://user-images.githubusercontent.com/112848218/192146176-b5a472ca-c826-45ce-b056-300cd2c139b2.png)

**Comment by laterdays** [comment]
![lADPJwKt0r9SjtHNBaDNB4A_1920_1440](https://user-images.githubusercontent.com/112848218/192148451-31b7c64c-5fe1-4782-8804-813add0ea190.jpg)
![lADPJwKt0r9Xp7rNBaDNB4A_1920_1440](https://user-images.githubusercontent.com/112848218/192148459-58ff6a31-1923-4fd2-9fd8-a4aeb2e70f4f.jpg)

从数据来看，表格的row数据已经变化，但是嵌套的switch并没有跟随row的数据进行更新 

@07akioni

**Comment by 07akioni** [comment]
> ![lADPJwKt0r9SjtHNBaDNB4A_1920_1440](https://user-images.githubusercontent.com/112848218/192148451-31b7c64c-5fe1-4782-8804-813add0ea190.jpg) ![lADPJwKt0r9Xp7rNBaDNB4A_1920_1440](https://user-images.githubusercontent.com/112848218/192148459-58ff6a31-1923-4fd2-9fd8-a4aeb2e70f4f.jpg)
> 
> 从数据来看，表格的row数据已经变化，但是嵌套的switch并没有跟随row的数据进行更新
> 
> @07akioni

直接把 shallowRef.value 赋值给一个 ref 就好了，然后让 data table 接受这个 ref 的数据
