### ISSUE TITLE
在 UMD 引入的方式下能否使用 message/notification 组件 ?

### ISSUE THREAD

**Issue by pengcu** [tusen-ai/naive-ui#3772]
### TuSimple/naive-ui version (版本)
2.33.3

### Vue version (Vue 版本)
3.2.39

### Browser and its version (浏览器及其版本)
Chrome 105.0.5195.125

### System and its version (系统及其版本)
macOS 12.6

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/message

### Reappearance steps (重现步骤)
使用 UMD 版本

### Expected results (期望的结果)
正常使用 useMessage / createDiscreteApi

### Actual results (实际的结果)
使用 createDiscreteApi 提示错误：
Failed to execute 'setAttribute' on 'Element': '0' is not a valid attribute name.
使用 useMessage 提示错误：
No outer `n-message-provider` found.

**Comment by 07akioni** [comment]
理论上肯定是可以用的，具体问题还是得具体看看

**Comment by 07akioni** [comment]
<img width="1757" alt="image" src="https://user-images.githubusercontent.com/18677354/193459863-53fa11ab-1d23-4e8d-8241-84992988fb94.png">

我试了一下是可以用的

**Comment by 07akioni** [comment]
provider 的用法写起来应该会比较麻烦，但是应该也是可以使用

**Comment by chenxi2015** [comment]
同问 怎么使用？
