### ISSUE TITLE
可不可以加个datatable的列宽拖拽功能啊？

### ISSUE THREAD

**Issue by imtns** [tusen-ai/naive-ui#3776]
### This function solves the problem (这个功能解决的问题)
力排众议在最新的项目采用了NaiveUI，但是现在产品要加拖拽列宽设置，大佬下个版本能不能加一个这个功能啊？我要死了
### Expected API (期望的 API)
colums-width

**Comment by lx11573** [comment]
我记得官方已经开发这个功能了，就是不知道什么时候发布了，坐等

**Comment by 07akioni** [comment]
下个版本会有
