### ISSUE TITLE
tabs: can't wrap `n-tabs` and `n-tab-pane`

### ISSUE THREAD

**Issue by OrbisK** [tusen-ai/naive-ui#3777]
### TuSimple/naive-ui version (版本)
2.33.3

### Vue version (Vue 版本)
3.2.39

### Browser and its version (浏览器及其版本)
OperaGX

### System and its version (系统及其版本)
win 11 (64)

### Node version (Node 版本)
/

### Reappearance link (重现链接)
https://codesandbox.io/s/zealous-frost-snpoq8?file=/src/Demo.vue

### Reappearance steps (重现步骤)
open reprod.

Wrap Tabs and TabPane. Tabs are not working.

### Expected results (期望的结果)
tabs working like always.

### Actual results (实际的结果)
tabs 0px heigth

**Comment by 07akioni** [comment]
This is the expected behavior and may not be changed for a while.
