### ISSUE TITLE
data-table: mergable table header cells

### ISSUE THREAD

**Issue by OrbisK** [tusen-ai/naive-ui#3780]
### This function solves the problem (这个功能解决的问题)
header cells are not meragable without gouping. 
### Expected API (期望的 API)
```html
<template>
  <n-data-table
    :columns="columns"
    :data="data"
    :pagination="pagination"
    :single-line="false"
  />
</template>

<script setup>
import { h, defineComponent } from 'vue'

const createColumns = () => {
const columns = [
    {
      title: 'Name',
      key: 'name',
      headerColSpan: 2,
      // ...
    },
]
</script>
```

**Comment by OrbisK** [comment]
maybe `cellProps` can do this?

**Comment by 07akioni** [comment]
I don't think it's a good idea to merge header cell without group. Currently every cell is rendered so if you set a cell with `col=2`, other cells would be pushed.

**Comment by OrbisK** [comment]
> I don't think it's a good idea to merge header cell without group. Currently every cell is rendered so if you set a cell with `col=2`, other cells would be pushed.

okay, sure... what if we can split like cells.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
