### ISSUE TITLE
Tree Select  有children字段，但是children为空时，依然显示节点箭头

### ISSUE THREAD

**Issue by laterdays** [tusen-ai/naive-ui#3783]
### TuSimple/naive-ui version (版本)
2.33.3

### Vue version (Vue 版本)
3.2.39

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
windows

### Reappearance link (重现链接)
https://codesandbox.io/s/t5wkwp?file=/src/Demo.vue

### Reappearance steps (重现步骤)
Tree Select  有children字段，但是children为空时，依然显示节点箭头

### Expected results (期望的结果)
是否应该有children字段，但children为空时，不应该显示节点箭头， 因为已经没有节点了

### Actual results (实际的结果)
Tree Select  有children字段，但是children为空时，依然显示节点箭头

### Remarks (补充说明)
Tree Select  有children字段，但是children为空时，依然显示节点箭头

**Comment by lx11573** [comment]
目前官方是需要自己指定节点的 isLeaf，不过只能是 boolean, 可否添加一个 function 呢

**Comment by laterdays** [comment]
目前是如果没有children字段，表示没有子节点，是否可以更人性化一点，如果children字段里没有内容 也代表没有子节点

**Comment by 07akioni** [comment]
> 目前是如果没有children字段，表示没有子节点，是否可以更人性化一点，如果children字段里没有内容 也代表没有子节点

空文件夹和文件是两种东西，如果需要扭转这种语义需要用户手动设定一下

**Comment by laterdays** [comment]
是需要什么操作，遍历数据，把每个空children字段设为null  还是 有更好的解决方案 ？ @07akioni  @lx11573

**Comment by laterdays** [comment]
https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdHJlZSA6ZGF0YT1cImRhdGFcIiA6cHJvcHM9XCJkZWZhdWx0UHJvcHNcIiBAbm9kZS1jbGljaz1cImhhbmRsZU5vZGVDbGlja1wiIC8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW50ZXJmYWNlIFRyZWUge1xuICBsYWJlbDogc3RyaW5nXG4gIGNoaWxkcmVuPzogVHJlZVtdXG59XG5cbmNvbnN0IGhhbmRsZU5vZGVDbGljayA9IChkYXRhOiBUcmVlKSA9PiB7XG4gIGNvbnNvbGUubG9nKGRhdGEpXG59XG5cbmNvbnN0IGRhdGE6IFRyZWVbXSA9IFtcbiAge1xuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDEnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDEtMScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtMScsXG4gICAgICAgICAgICBjaGlsZHJlbjpbXG4gICAgICAgICAgICBdXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDInLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDItMScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAyLTEtMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDItMicsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAyLTItMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDMnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDMtMScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAzLTEtMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDMtMicsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAzLTItMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbl1cblxuY29uc3QgZGVmYXVsdFByb3BzID0ge1xuICBjaGlsZHJlbjogJ2NoaWxkcmVuJyxcbiAgbGFiZWw6ICdsYWJlbCcsXG59XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==

**Comment by laterdays** [comment]
我看了一下别的UI库的设计，基本都是如果children字段为空， 就代表没有节点

**Comment by 07akioni** [comment]
> 我看了一下别的UI库的设计，基本都是如果children字段为空， 就代表没有节点

可以理解他们的处理方式，这就是两种选择而已。我的倾向是空数组还是一个可以展开的节点，至少这样数据出问题的情况下，用户还能第一时间发现。

**Comment by laterdays** [comment]
@07akioni  可以考虑加个属性控制也行， 目前来看很多UI库都是以children的内容数量来决定是否有子节点，如果按照现有方式，会有大量的后台接口需要更改， 希望官方可以提供个属性接口，多种选择
