### ISSUE TITLE
Tree: Provide ability to disable expand/collapse animation

### ISSUE THREAD

**Issue by brsanthu** [tusen-ai/naive-ui#3784]
### This function solves the problem (这个功能解决的问题)
As of now, the expand and collapse happens fairly quickly but still not instant due to some animation transition. Please provide a prop to disable this animation so make expand/collapse instant.
### Expected API (期望的 API)
transition-delay?: number

With this, we can set the transition-delay = 0 to disable animation

**Comment by 07akioni** [comment]
We will add it.

**Comment by brsanthu** [comment]
@07akioni thank you for adding this prop. Does it make sense to read transition-delay from a var and default it to 0.3s (as its the current value) so that users can change that to any value and it will be automatically taken effect in all other places?
