### ISSUE TITLE
NDataTable设置maxHeight为空字符串会导致fixed滚动条不一致

### ISSUE THREAD

**Issue by JimFirst** [tusen-ai/naive-ui#3785]
### TuSimple/naive-ui version (版本)
2.33.3

### Vue version (Vue 版本)
3.2.39

### Browser and its version (浏览器及其版本)
Chrome(105.0.5195.125)

### System and its version (系统及其版本)
MacOs(12.1)

### Node version (Node 版本)
14.18.1

### Reappearance link (重现链接)
https://codesandbox.io/s/red-waterfall-1sbd59?file=/src/Demo.vue

### Reappearance steps (重现步骤)
NDataTable设置maxHeight为空字符串，设置ScrollX，设置其中几个字段为fixed，拖动横向滚动条，会发现header和content滚动不一致，只有content滚动，header不会滚动

### Expected results (期望的结果)
列表header和content滚动一致，两者同时滚动

### Actual results (实际的结果)
列表header和content滚动不一致，header和content各自滚动

**Comment by 07akioni** [comment]
空字符串不是合法的值，换成 undefined 应该就没问题了
