### ISSUE TITLE
表格列宽宽度问题

### ISSUE THREAD

**Issue by zhoufanglu** [tusen-ai/naive-ui#3787]
### TuSimple/naive-ui version (版本)
2.30.8

### Vue version (Vue 版本)
3.2.39

### Browser and its version (浏览器及其版本)
chrome.89

### System and its version (系统及其版本)
win10

### Reappearance steps (重现步骤)
表格列宽设置了最小宽度`minWidth: '530px'`,

### Expected results (期望的结果)
表格列宽设置了最小宽度`minWidth: '530px'`,
点击分页后， 表格宽度跟第一次一样

### Actual results (实际的结果)
表格列宽设置了最小宽度`minWidth: '530px'`,
如何在表格点击分页的时候，列宽发生了变化。
是否能跟 element一样， 设置min-width，分页后宽度是不会发生变化的

* 目前效果
![gt33tnMXs7](https://user-images.githubusercontent.com/24451091/192467936-996abeb7-c7de-4909-9e3e-e35670083590.gif)

**Comment by 07akioni** [comment]
变化前后两次都是超过 530px 么？

**Comment by zhoufanglu** [comment]
> 变化前后两次都是超过 530px 么？

530px只是个例子， 比如我设置了minWidth， 我分页的时候列宽能跟第一页一样宽吗？

**Comment by zhzwz** [comment]
看你的效果图，应该是给「租户名」列设置一个 width 属性就行了吧？不然「描述」列的内容变动会导致宽度的分配变化。

**Comment by zhoufanglu** [comment]
> 看你的效果图，应该是给「租户名」列设置一个 width 属性就行了吧？不然「描述」列的内容变动会导致宽度的分配变化。

目前ui要求每列宽度不定死， 需要是min-width

**Comment by zhzwz** [comment]
非得这样的话，大概可以这么写：

在渲染列「租户名」和「描述」的时候，嵌套一层 `<div>`，并设置内部 `<div>` 的宽度。

列的配置大概是下面这样：

```js
[
  { key: "name", title: "租户名", minWidth: 530, render: (rowData) => h("div", { width: "200px" }, () => rowData.name) },
  { key: "description", title: "描述", minWidth: 530, render: (rowData) => h("div", { width: "300px" }, () => rowData.description) },
]
```

由于内部元素的宽度是固定的，在自适应的时候，就不会因为内容的多少，而影响排版。

**Comment by zhoufanglu** [comment]
> 

感觉这样有点掩耳盗铃了， element-plus 设置了min-width, 分页就不会改变列宽。。。如果没有配置项，先这样吧
