### ISSUE TITLE
collapse: `theme-override`for gap between items

### ISSUE THREAD

**Issue by OrbisK** [tusen-ai/naive-ui#3788]
### This function solves the problem (这个功能解决的问题)
the gab between `<n-collapse-items />`s can't be set via theme
### Expected API (期望的 API)
```ts
const overrides: GlobalThemeOverrides = {
  Collapse: {
    gap: '20px'
  }
}
```

**Comment by OrbisK** [comment]
@07akioni gap between title and content is good, but i was refering to the gap between `<collpase-item />` to `<collapse-item />` 😅

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
