### ISSUE TITLE
Select Filtering doesn't fire on mobile keyboard on every keystroke

### ISSUE THREAD

**Issue by AlekseyMalakhov** [tusen-ai/naive-ui#3789]
### TuSimple/naive-ui version (版本)
2.32.2

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Chrome 105.0.5195.136

### System and its version (系统及其版本)
Android 8

### Node version (Node 版本)
16.17.1

### Reappearance link (重现链接)
https://github.com/AlekseyMalakhov/checkNSelectMobile

### Reappearance steps (重现步骤)
1) Run the attached code 'npm run dev -- --host'
2) Open website on mobile device (Chrome browser)
3) Try to type something in select element
4) You will see filter doesn't work on every keystroke. It works only when keyboard disappears.

### Expected results (期望的结果)
Filtering should work on every keystroke as it does on desktop

### Actual results (实际的结果)
Filtering happens only after keyboard disappears

### Remarks (补充说明)
<a href="https://ibb.co/DCs2BJj"><img src="https://i.ibb.co/2tm4z9p/Screenshot-2022-09-27-172908.png" alt="Screenshot-2022-09-27-172908" border="0"></a><br /><a target='_blank' href='https://emoticoncentral.com/category/apologetic'>apologetic emojis</a><br />

**Comment by 07akioni** [comment]
During IME composition filter won't be fired. We may expose a prop to control the behavior.
