### ISSUE TITLE
Notification use the composable

### ISSUE THREAD

**Issue by ozgurkisa** [tusen-ai/naive-ui#3790]
### This function solves the problem (这个功能解决的问题)
Interceptor is already calling a setup function. But notification undefined.

I can use notifications as composition api. In this way, I can manage the process through the interceptor in my application.
### Expected API (期望的 API)

    import { useNotification } from 'naive-ui'
  
    export const useNotify = (type, args) => {

        const notification = useNotification()

        return notification[type]({
          ...args,
        })
    }

Interceptor.js // Every request error handler

    export const useApi = async (url = '', _ops, _args = {}) => {

      return await $fetch(`/api/${url}`, {
        ..._ops,

        async onResponse({ request, response, options }) {
          return response._data
        },

        async onResponseError({ request, response, options }) {
    
          useNotify({
            type: 'error',
            content : response.message
          })
      
        },
      })
    }

**Comment by 07akioni** [comment]
https://www.naiveui.com/en-US/os-theme/components/discrete

https://www.naiveui.com/en-US/os-theme/components/message

<img width="1486" alt="image" src="https://user-images.githubusercontent.com/18677354/192939038-8de1de6e-d901-4fc6-886f-13da0bb905be.png">
