### ISSUE TITLE
ellipsis and tooltip display exceptions under dark themes

### ISSUE THREAD

**Issue by thelostword** [tusen-ai/naive-ui#3791]
### TuSimple/naive-ui version (版本)
2.33.3

### Vue version (Vue 版本)
3.2.40

### Browser and its version (浏览器及其版本)
Chrome 105.0.5195.127

### System and its version (系统及其版本)
window 10

### Reappearance link (重现链接)
https://github.com/thelostword/recurrence

### Reappearance steps (重现步骤)
按需全局引入naive-ui
使用 NEllipsis 组件

### Expected results (期望的结果)
和官网示例一样正常显示

### Actual results (实际的结果)
npopover样式显示异常，主题未发生变化

**Comment by thelostword** [comment]
DataTable 组件 ellipsis.tooltip = ture, 以及 menu 等使用到 NEllipsis 组件的地方显示都有问题。官网文档显示是正常的

**Comment by 07akioni** [comment]
<img width="518" alt="image" src="https://user-images.githubusercontent.com/18677354/192932946-b7192d40-61c2-4be9-9e1a-d5211bf92b20.png">

这里应该是 `:theme`

**Comment by thelostword** [comment]
> <img alt="image" width="518" src="https://user-images.githubusercontent.com/18677354/192932946-b7192d40-61c2-4be9-9e1a-d5211bf92b20.png">
> 
> 这里应该是 `:theme`

谢谢回复，明白了
![image](https://user-images.githubusercontent.com/41263837/192954840-fe86cdde-1af4-4895-a3c1-7da8a856ef9d.png)
