### ISSUE TITLE
Tree拖动时，节点限制在父级内部

### ISSUE THREAD

**Issue by xiaosongmao123** [tusen-ai/naive-ui#3797]
### This function solves the problem (这个功能解决的问题)
当前，Tree设置可拖动后，我们拖动一个节点
```
+ 道生一
      + 一生二01
              二生三01
              二生三02
              二生三03

     + 一生二02
              二生三04
              二生三05
```
当拖动`二生三03`时，希望让他只能调整排序，只能在`一生二01`内部拖动。而不能拖放到其他地方，例如不能拖放到`一生二02`里面
### Expected API (期望的 API)
请问是否可以通过`on-dragenter`事件里对`event: DragEvent`进行设置来实现此功能？还是可以通过`on-dragenter`的返回值来阻止拖放？

**Comment by 07akioni** [comment]
可以用 allow-drop 来做
