### ISSUE TITLE
Upload broken on firefox due to directory changes

### ISSUE THREAD

**Issue by zacwebb** [tusen-ai/naive-ui#3798]
### TuSimple/naive-ui version (版本)
2.33.3

### Vue version (Vue 版本)
3.2.40

### Browser and its version (浏览器及其版本)
Firefox 106 (but reproducible for in many previous versions)

### System and its version (系统及其版本)
MacOS 12.6

### Reappearance link (重现链接)
https://jsfiddle.net/4sjvmp6y/

### Reappearance steps (重现步骤)
Open the fiddle on Firefox, click the file input, and you'll see only directories are selectable (no individual files).

### Expected results (期望的结果)
With `webkitdirectory` set to `false` you'd expect no directories to be selectable and only individual files to be allowed

### Actual results (实际的结果)
Instead you are forced to only select directories and can't select individual files

### Remarks (补充说明)
This doesn't affect Chrome as it appears to respect boolean settings on `webkitdirectory`, but for whatever reason Firefox sees the `webkitdirectory` attribute and it assumes it as true.

The underlying `input` element in the component will probably have to be updated to exclude the `webkitdirectory` attribute altogether when the prop `directory = false`, rather than just using the boolean.

Possibly related to changes in https://github.com/tusen-ai/naive-ui/pull/2809, could be wrong though
cc: @lwansbrough

**Comment by zacwebb** [comment]
For anyone that runs into this – this is a kinda ugly/hacky approach to solve it for now 😬

```typescript
onMounted(() => {
    [...document.getElementsByClassName('n-upload-file-input')].forEach((el) => el.removeAttribute('webkitdirectory'));
});
```

**Comment by 07akioni** [comment]
I can't reproduce it in naive's project. However it quite behaves as you described in the jsfiddle, so I would fix it.
