### ISSUE TITLE
data-table  checked-row-keys回调问题

### ISSUE THREAD

**Issue by wanbo0424** [tusen-ai/naive-ui#3800]
### TuSimple/naive-ui version (版本)
2.32.1

### Vue version (Vue 版本)
3.2.33

### Browser and its version (浏览器及其版本)
chrome 105.0.5195.127（正式版本）

### System and its version (系统及其版本)
windows 10

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/data-table#API

### Reappearance steps (重现步骤)
先在第一页勾选一条数据，然后跳第二页勾选回调后的rows是[undefined, 第二页row].但是keys参数是两页里勾选的key，没有undefined的情况

### Expected results (期望的结果)
在不同页勾选后回调的rows参数也能像keys一样返回已勾选数据，不要有undefined

### Actual results (实际的结果)
跨页勾选rows参数只能获取到当前页row，其他页row为undefined,表现为[undefined, undefined, 当前页row]

**Comment by 07akioni** [comment]
是不是用了异步数据？同步数据不应该这样的

**Comment by 07akioni** [comment]
异步数据这样是符合预期的，可以手动存一下
