### ISSUE TITLE
支持引入naive-ui/es 目录下的文件

### ISSUE THREAD

**Issue by notail** [tusen-ai/naive-ui#3804]
### This function solves the problem (这个功能解决的问题)
解决 import { treeInjectionKey } from 'naive-ui/es/tree/src/interface' 编译报错
### Expected API (期望的 API)
package.json中的exports 支持引入naive-ui/es下文件，目前不支持，会到导致引入内部没有导出的变量报错

**Comment by Sepush** [comment]
你应该只从入口导入

**Comment by 07akioni** [comment]
如果有什么很需要但是目前没有导出的可以单独提 issue
