### ISSUE TITLE
More customisable styles for n-select

### ISSUE THREAD

**Issue by mitya33** [tusen-ai/naive-ui#3806]
### This function solves the problem (这个功能解决的问题)
n-select should have many of the same customisable styles as n-input. Right now, the only customisable style listed for n-select in the theme builder is menuBoxShadow. Many styles CAN be overridden by setting overrides under `common`, but it's odd that they're not explicitly overrideable at the n-select level.
### Expected API (期望的 API)
More styles available to customise for n-select - as with n-input.

**Comment by 07akioni** [comment]
It's possible by peers style. However it's not explicitly well documented. You can refer to https://www.naiveui.com/en-US/os-theme/docs/customize-theme#Use-the-peers-vars

<img width="876" alt="image" src="https://user-images.githubusercontent.com/18677354/193456933-5b78a68c-6518-4688-a829-20a605d652cd.png">
