### ISSUE TITLE
文件上传新增成功后的图标和覆盖前一个文件

### ISSUE THREAD

**Issue by laterdays** [tusen-ai/naive-ui#3812]
### This function solves the problem (这个功能解决的问题)
现在上传成功后看不出来已经成功没有对应的背景色和图标

文件上传新增成功后的图标和覆盖前一个文件

### Expected API (期望的 API)
能在文件上传成功和失败后有个成功的背景色或图标
设置 limit 和 on-exceed 可以在选中时自动替换上一个文件。

**Comment by 07akioni** [comment]
替换上一个文件这个感觉不太好，目前可以设定 `max` 控制最大的附件数量，然后删除多余的文件需要手动操作

**Comment by laterdays** [comment]
而且在onerror的回调中无法进行数据删除，还需要再定义一个change，总感觉会多了很多操作

**Comment by 07akioni** [comment]
> 而且在onerror的回调中无法进行数据删除，还需要再定义一个change，总感觉会多了很多操作

使用受控模式的话可以删掉，也可以提供一个 ref 的 API 允许用户删除数据

**Comment by laterdays** [comment]
但是很奇怪的是onerror为什么会执行两次，正常逻辑来说，是不是最终错误之后会回调这个函数

**Comment by 07akioni** [comment]
> 这算是写法问题还是组件问题，如果是写法问题，是否可以在文档中加个备注

这个很难说是哪一方的问题，是一种边界情况，在 Vue 的世界中 props 的流动是需要经过一个 tick 的传递的，除非操纵的是原始对象，不然中间需要走一次个赋值的流程，这个赋值的流程走完了才能拿到新的值

**Comment by laterdays** [comment]
> > 但是很奇怪的是onerror为什么会执行两次，正常逻辑来说，是不是最终错误之后会回调这个函数
> 
> 我没发现失败两次，那两个红色针对的是两个问题，不是一个事情

![image](https://user-images.githubusercontent.com/112848218/194316812-043a388a-6bb7-4978-a459-07ec445a7374.png)

看起来触发的俩次错误，文件和状态都是一致的

**Comment by 07akioni** [comment]
> > > 但是很奇怪的是onerror为什么会执行两次，正常逻辑来说，是不是最终错误之后会回调这个函数
> > 
> > 
> > 我没发现失败两次，那两个红色针对的是两个问题，不是一个事情
> 
> ![image](https://user-images.githubusercontent.com/112848218/194316812-043a388a-6bb7-4978-a459-07ec445a7374.png)
> 
> 看起来触发的俩次错误，文件和状态都是一致的

确实看着有点其奇怪，不过我没跑出这个来，没能复现
<img width="916" alt="image" src="https://user-images.githubusercontent.com/18677354/194546909-41b9c60c-dd8a-4d9e-927a-7010e651d55f.png">

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
