### ISSUE TITLE
Make it easier to colour icons with main colours (primary, warning, info etc.)

### ISSUE THREAD

**Issue by mitya33** [tusen-ai/naive-ui#3814]
### This function solves the problem (这个功能解决的问题)
Make it easier to colour icons with main colours (primary, warning, info etc.), without having to, as currently, pass a `color` prop to the icon, passing it a manual HEX colour code.
### Expected API (期望的 API)
The existing `color` prop would accept a string, which would be one of the colours from the main colour palette (primary, info etc.). Anything else would be inferred as a literal colour code.

**Comment by OrbisK** [comment]
Longterm a prop `type` (?) might solve this.

A quick workaround for now is:

```html
<n-text type="primary">
  <n-icon />
</n-text>
```

**Comment by mitya33** [comment]
@OrbisK Nice!

**Comment by jahnli** [comment]
Closed due to inactivity. Feel free to reopen if you're still having trouble.

**Comment by PANstudio** [comment]
Completed how?
