### ISSUE TITLE
受控的上传列表，上传失败后操作上传列表失败

### ISSUE THREAD

**Issue by laterdays** [tusen-ai/naive-ui#3815]
### TuSimple/naive-ui version (版本)
2.33.3

### Vue version (Vue 版本)
3.2.40

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
windows

### Reappearance link (重现链接)
https://codesandbox.io/s/nervous-carlos-lk5iqc

### Reappearance steps (重现步骤)
受控的上传列表，无法上传失败后操作上传列表失效

### Expected results (期望的结果)
受控的上传列表，无法上传失败后操作上传列表失效

### Actual results (实际的结果)
如何通过给fileList赋值操作上传列表

**Comment by laterdays** [comment]
https://codesandbox.io/s/dazzling-jang-gj8bxt?file=/src/Demo.vue

并且通过ref.chear() 清空列表时，会提示[naive/upload]: File has no corresponding id in current file list.

**Comment by 07akioni** [comment]
这个问题应该出在了 error 情况下只是某一个文件出了问题
如果你清空了列表中所有的文件，就会导致一些上传的过程还在跑
然后就会报那个 error
如果错误的话我感觉你清除掉那个报错的就好了

**Comment by laterdays** [comment]
@07akioni   我设置了max等于1，最多上传一个， 但是当这个文件出错的时候， 在onerror回调没办法清空列表

https://codesandbox.io/s/nervous-carlos-lk5iqc?file=/src/Demo.vue
