### ISSUE TITLE
"The inferred type of this node exceeds the maximum length the compiler will serialize..." error when exposing theme in setup function.

### ISSUE THREAD

**Issue by ilgiznurgaliev** [tusen-ai/naive-ui#3818]
### TuSimple/naive-ui version (版本)
2.33.3

### Vue version (Vue 版本)
3.2.38

### Browser and its version (浏览器及其版本)
Chrome(105.0.5195.127)

### System and its version (系统及其版本)
Windows 10

### Node version (Node 版本)
v14.20.0

### Reappearance link (重现链接)
https://github.com/ilgiznurgaliev/vue-3-typescript-naive-ui.git

### Reappearance steps (重现步骤)
1. Init Vue project:
```
$ npm init vue@latest
npx: installed 1 in 2.365s

Vue.js - The Progressive JavaScript Framework

√ Project name: ... vue-naive
√ Add TypeScript? ... No / Yes
√ Add JSX Support? ... No / Yes
√ Add Vue Router for Single Page Application development? ... No / Yes
√ Add Pinia for state management? ... No / Yes
√ Add Vitest for Unit Testing? ... No / Yes
√ Add Cypress for End-to-End testing? ... No / Yes
√ Add ESLint for code quality? ... No / Yes
√ Add Prettier for code formatting? ... No / Yes

Scaffolding project in C:\DATA\Vue3\vue-naive...

Done. Now run:

  cd vue-naive
  npm install
  npm run dev
```
2. Install node modules and naive-ui:
```
$ cd vue-naive
$ npm install
$ npm install naive-ui
```
3. In App.vue wrap everything with `NConfigProvider` component like below:
```
<script lang="ts">
  import HelloWorld from './components/HelloWorld.vue'
  import TheWelcome from './components/TheWelcome.vue'
  import { NConfigProvider, darkTheme } from 'naive-ui';
  import { ref, defineComponent } from 'vue';

  export default defineComponent({
    components: { HelloWorld, TheWelcome, NConfigProvider },
    setup() {
      const theme = ref(darkTheme);
      return { theme }
    }
  })
</script>

<template>
  <NConfigProvider :theme="theme">
    <header>
      <img alt="Vue logo" class="logo" src="./assets/logo.svg" width="125" height="125" />
      <div class="wrapper">
        <HelloWorld msg="You did it!" />
      </div>
    </header>
    <main>
      <TheWelcome />
    </main>
  </NConfigProvider>
</template>
```

or

1. Clone repository above: `git clone https://github.com/ilgiznurgaliev/vue-3-typescript-naive-ui.git`
2. Install node modules: `npm install`

After steps above open the project in VSCode with installed Volar extension and takeover mode.

### Expected results (期望的结果)
No any errors.

### Actual results (实际的结果)
![image](https://user-images.githubusercontent.com/10621366/193805624-2ad78cd3-c89a-4628-adb3-6bbd2882126c.png)

The error appear only when I pass `theme` prop to `NConfigProvider`. Without `theme` prop no any issues.

**Comment by 07akioni** [comment]
I think is may not be fixable. You can specify a exact type for them like `theme: Ref<GlobalTheme>` or just use `theme: Ref<any>`

**Comment by ilgiznurgaliev** [comment]
@07akioni thanks for response. `Ref<GlobalTheme>` solved the issue.
