### ISSUE TITLE
Slider font-size of marks can't be changed

### ISSUE THREAD

**Issue by wc-davide** [tusen-ai/naive-ui#3820]
### TuSimple/naive-ui version (版本)
2.33.3

### Vue version (Vue 版本)
3.2.40

### Browser and its version (浏览器及其版本)
Brave (latest)

### System and its version (系统及其版本)
Windows 10

### Reappearance link (重现链接)
https://codesandbox.io/s/intelligent-wilson-cz3ryd?file=/src/Demo.vue

### Reappearance steps (重现步骤)
Attempting to override fontSize option in slider component changes the font size of the value but not of the marks... 

### Expected results (期望的结果)
There should be a way to change the default font size of the marks (default 14px)

### Actual results (实际的结果)
Marks font size is not changing

### Remarks (补充说明)
Need smaller (font-size) marks for my UI

**Comment by OrbisK** [comment]
I agree, that `fontSize` is kinda confusing. Better whould be `tooltipFontSize` not sure if this will get a change soon. But maybe you can request `labelFontSize` :)

Maybe `fontSize` should be deprecated but still there and be replaced by `tooltipFontSize`.
