### ISSUE TITLE
Exception in `NButton` async click can not be captured by `app.config.errorHandler`.

### ISSUE THREAD

**Issue by RiverAge** [tusen-ai/naive-ui#3833]
### TuSimple/naive-ui version (版本)
2.33.0

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Microsoft Edge(106.0.1370.37)

### System and its version (系统及其版本)
windows 11

### Node version (Node 版本)
16.16

### Reappearance link (重现链接)
https://codesandbox.io/s/withered-firefly-xfx0e2?file=/src/App.vue

### Reappearance steps (重现步骤)
Pease Referer `https://codesandbox.io/s/withered-firefly-xfx0e2?file=/src/App.vue`

### Expected results (期望的结果)
Just like html basic button, Exception in async click can be captured by `app.config.errorHandler`.

### Actual results (实际的结果)
Exception in async click can not be captured by `app.config.errorHandler`, error stack displayed on console.

### Remarks (补充说明)
`https://github.com/tusen-ai/naive-ui/discussions/1399`

**Comment by 07akioni** [comment]
I don't think this is fixable since it may change the implementation pattern too much. It's impossible to make all callback (or so called event) work in an `emit` pattern since sometimes we need its returned value.

**Comment by not-Ryan** [comment]
Is there any way around this?

Or is this just it :(
