### ISSUE TITLE
NSelect: empty options menu when theme common > heightMedium is "2.5rem"

### ISSUE THREAD

**Issue by M1CK431** [tusen-ai/naive-ui#3841]
### TuSimple/naive-ui version (版本)
2.33.4

### Vue version (Vue 版本)
3.2.40

### Browser and its version (浏览器及其版本)
Chrome/106.0.0.0

### System and its version (系统及其版本)
Archlinux

### Reappearance link (重现链接)
https://www.naiveui.com/en-US/light/components/select

### Reappearance steps (重现步骤)
Open theme editor, expand "Common" section and fill `heightMedium` with `2.5rem`.
Try to open any NSelect menu

### Expected results (期望的结果)
NSelect menu present options

### Actual results (实际的结果)
NSelect menu is empty (at least it seems empty):
![image](https://user-images.githubusercontent.com/31622263/194909452-223c199c-5b88-4521-8d9a-97ea7e40562f.png)

**Comment by 07akioni** [comment]
Rem is expected to not work in virtual list. If you must use it you need to set `virtual-scroll` to `false`.

**Comment by M1CK431** [comment]
Good to know, thanks.
