### ISSUE TITLE
树拖放时，整个页面样式错乱，字体消失，官网操作下就会重现

### ISSUE THREAD

**Issue by zlz20180804** [tusen-ai/naive-ui#3842]
### TuSimple/naive-ui version (版本)
2.33.4

### Vue version (Vue 版本)
3.2.40

### Browser and its version (浏览器及其版本)
chrome 版本 106.0.5249.103（正式版本） （64 位）

### System and its version (系统及其版本)
window10

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/tree#drag-drop.vue

### Reappearance steps (重现步骤)
官网操作下就会重现

### Expected results (期望的结果)
修复

### Actual results (实际的结果)
树拖放时，整个页面样式错乱，字体消失

**Comment by 07akioni** [comment]
https://user-images.githubusercontent.com/18677354/195147152-af93769d-324d-4e37-8131-f2430f176259.mov

没能复现，需要更明确的一些信息

**Comment by blisssayyid** [comment]
![005rk-sk0lc](https://user-images.githubusercontent.com/11463194/195540791-1b290641-eb84-4db6-bb48-0f12f6767858.gif)

**Comment by 07akioni** [comment]
fixed
