### ISSUE TITLE
滚动条BUG

### ISSUE THREAD

**Issue by 204065248** [tusen-ai/naive-ui#3844]
### TuSimple/naive-ui version (版本)
2.33.4

### Vue version (Vue 版本)
3.2.40

### Browser and its version (浏览器及其版本)
Microsoft Edge 版本 106.0.1370.37 (正式版本) (64 位)

### System and its version (系统及其版本)
Windows 20H2

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/scrollbar

### Reappearance steps (重现步骤)
进入naiveui官网，鼠标放在任意元素上，并向上或向下滚动。注意滚动后鼠标所在元素不能发生更改。

### Expected results (期望的结果)
滚动条无法正常操作

### Actual results (实际的结果)
滚动条无法正常操作

### Remarks (补充说明)
解决办法是鼠标移动到别的元素即可正常滚动，这个问题在naiveui的官网只要用了自身的滚动条都会有这个问题，我很好奇为什么没有人提出来呢。

**Comment by 07akioni** [comment]
能给来个录屏么？没太理解

**Comment by Adaer** [comment]
看了视频和文字说明 也不理解

**Comment by 204065248** [comment]
> 看了视频和文字说明 也不理解

不理解，你就按照我说明操作一下即可

**Comment by 204065248** [comment]
> > 注意啊，问题出现的浏览器版本是Microsoft Edge 版本
> 
> Microsoft Edge 版本 106.0.1370.42 (正式版本) (64 位) 没有复现你的bug ，可能是版本不同？

我刚刚升级到了最新版还是有这个问题存在

**Comment by 07akioni** [comment]
我后面大概理解了你说的是啥，我感觉这个是 overflow hidden 对滚动行为导致的影响，现阶段没办法处理

**Comment by 204065248** [comment]
> 我后面大概理解了你说的是啥，我感觉这个是 overflow hidden 对滚动行为导致的影响，现阶段没办法处理，或许只要 body 不写 overflow hidden 就行了

好的
