### ISSUE TITLE
max-height property allows to scroll body horizontally separatly from the header on mobile

### ISSUE THREAD

**Issue by AlekseyMalakhov** [tusen-ai/naive-ui#3845]
### TuSimple/naive-ui version (版本)
2.33.4

### Vue version (Vue 版本)
3.2.38

### Browser and its version (浏览器及其版本)
Chrome 106.0.5249.79

### System and its version (系统及其版本)
Android 8.1.0

### Node version (Node 版本)
16.17.1

### Reappearance link (重现链接)
https://github.com/AlekseyMalakhov/checkNDataTable

### Reappearance steps (重现步骤)
1) Run the code from GitHub link on mobile
2) Try to scroll body horizontally
3) You will see header and body move with a small margin between each other
4) Tap on header
5) Now you are able to scroll body horizontally absolutely independently from header

### Expected results (期望的结果)
Header and body should scroll horizontally together

### Actual results (实际的结果)
Header and body scroll horizontally independently

### Remarks (补充说明)
<a href="https://ibb.co/5kLrkyc"><img src="https://i.ibb.co/XDt7DgJ/Screenshot.jpg" alt="Screenshot" border="0"></a>

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
