### ISSUE TITLE
树形数据和可展开结合在一起，无论点哪一个展开按钮，都是同时展开了 可展开的内容和树形子数据

### ISSUE THREAD

**Issue by PZ-18664918826** [tusen-ai/naive-ui#3852]
### This function solves the problem (这个功能解决的问题)
1、可展开按钮分别控制各自的功能，树形的控制树形子数据，可展开的控制可展开的内容
2、替换icon，希望能分别替换图标
3、希望树形展开和可展开能分别提供渲染函数api，可以自定义内容
4、希望能提供多个可展开的内容，比如可以展开2个子表格
5、可展开希望是可以受控的，自己来控制
![战略解码-提炼重点工作](https://user-images.githubusercontent.com/64340432/195227884-66d3af42-978f-4b27-a99b-8ccad623d2ce.png)

### Expected API (期望的 API)
1、替换icon 2个不同的渲染函数
2、希望树形展开和可展开能分别提供渲染函数api等等

**Comment by 07akioni** [comment]
现在树形展开和展开行的逻辑应该是没设计成可以共存的，搞成能共存的应该是个很复杂的事情

**Comment by PZ-18664918826** [comment]
> 现在树形展开和展开行的逻辑应该是没设计成可以共存的，搞成能共存的应该是个很复杂的事情

后面有计划弄吗
