### ISSUE TITLE
n-table resizable 时，如果同时存在sorter会导致即使设置了minWidth和ellipsis也会换行

### ISSUE THREAD

**Issue by jahnli** [tusen-ai/naive-ui#3853]
### TuSimple/naive-ui version (版本)
2.33.5

### Vue version (Vue 版本)
3.2.40

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
windows

### Node version (Node 版本)
last

### Reappearance link (重现链接)
https://codesandbox.io/s/naughty-ritchie-l5eved?file=/src/Demo.vue

### Reappearance steps (重现步骤)
n-table resizable 时，如果同时存在sorter会导致即使设置了minWidth和ellipsis也会换行

### Expected results (期望的结果)
是否应该过滤掉排序的图标宽度，或有办法解决换行问题

### Actual results (实际的结果)
n-table resizable 时，如果同时存在sorter会导致即使设置了minWidth和ellipsis也会换行

**Comment by nooooooom** [comment]
@07akioni `sorter` 之前的设计貌似就是这样的，是不是要让它始终跟 title 平排
