### ISSUE TITLE
数据表格带提示的省略tootip对象中使用style改变tooltip样式时ts类型报错

### ISSUE THREAD

**Issue by maddenBoy** [tusen-ai/naive-ui#3854]
### TuSimple/naive-ui version (版本)
2.33.5

### Vue version (Vue 版本)
3.2.40

### Browser and its version (浏览器及其版本)
Chrome（106.0.5249.103）

### System and its version (系统及其版本)
windows11

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/data-table#ellipsis-tooltip.vue

### Reappearance steps (重现步骤)
数据表格使用带提示的省略，tooltip传入TooltipProps中的值，例如：ellipsis: { tooltip: showArrow: false, style: { backround: ‘#fff’ } }

### Expected results (期望的结果)
使用ellipsis的tooltip时，可以正常使用style，并且使用style时ts类型不报错（看文档的PopoverProps，确实无style属性，但有些情况需要改变tooltip的样式，tooltip中传入style也确实可以改变tooltip的样式，但ts类型报错，能否优化一下或者讲一下数据表格中tooptip改变样式的正确使用姿势）

### Actual results (实际的结果)
使用ellipsis的tooltip时，无style提示，使用style时ts类型报错

## tooltip使用style时ts类型报错截图
![image](https://user-images.githubusercontent.com/71129660/195236150-5ec85c85-5701-46b9-97ab-743d4ac6ae9e.png)

**Comment by nooooooom** [comment]
这应该算是意外的情况，`attrs` 自动继承下去了，还是建议只用 `PopoverProps` 内提供的样式属性作为修改样式的来源，避免后续组件库逻辑变动导致该方式失效了

**Comment by maddenBoy** [comment]
问题是data-table组件没有提供修改表格中tooltip样式的的来源，希望可以提供

**Comment by nooooooom** [comment]
看下这几个 `props` 能不能满足你的业务需求，`ellipsis` 是支持 `Popover` 的所有 `props` 的
![image](https://user-images.githubusercontent.com/61452855/197164412-d210a36d-6676-406b-a341-54cffb5cd03d.png)

**Comment by maddenBoy** [comment]
配合law属性可以实现，感谢解答

**Comment by 07akioni** [comment]
style 可以直接加给 ellipsis 这个 object

**Comment by maddenBoy** [comment]
> style 可以直接加给 ellipsis 这个 object
直接给ellipsis加style改变的是单元格的格式
![image](https://user-images.githubusercontent.com/71129660/206077720-4c4f59c0-0e4e-4a8f-aae2-37ec7a20fb89.png)

**Comment by maddenBoy** [comment]
> 看下这几个 `props` 能不能满足你的业务需求，`ellipsis` 是支持 `Popover` 的所有 `props` 的 ![image](https://user-images.githubusercontent.com/61452855/197164726-1d8bfbb6-ff56-4125-a5e4-14ac7f3628b5.png)
例如我要改变tooptip的背景色，似乎给contentStyle，footerStyle，headerStyle这些属性加样式在内容滚动的时候会有问题，直接加tooltip加样式滚动时可正常展示，但ts类型报错
给contentStyle加样式滚动时的表现
![image](https://user-images.githubusercontent.com/71129660/206078702-62182f2e-b219-4d5b-8ef8-aacc842144e3.png)
给tooltip加样式滚动时的表现
![image](https://user-images.githubusercontent.com/71129660/206079068-b83450da-2597-4fc2-aade-706eef1fbc7f.png)
