### ISSUE TITLE
Add `type` prop to Dropdown option

### ISSUE THREAD

**Issue by jdwit** [tusen-ai/naive-ui#3860]
### This function solves the problem (这个功能解决的问题)
It is a common use case that Dropdown option have a particular "type": for example "danger/error" type when the option triggers a destructive action or a "success" type to indicate a positive action. In particular this is useful for destructive actions. The text and icon colors are consistent with the the success, error, etc. themes. The "hover" colors of the options are not changed.

Ant Design has a prop `danger: boolean` for its `MenuItemType` that is similar to this.

### Expected API (期望的 API)
`DropdownOption` type has a `type` attribute `'info' | 'success' | 'warning' | 'error' | 'loading' | 'default'`

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
