### ISSUE TITLE
upload 文件上传组件

### ISSUE THREAD

**Issue by DoneLyGit** [tusen-ai/naive-ui#3861]
### TuSimple/naive-ui version (版本)
2.33.5

### Vue version (Vue 版本)
3.2.40

### Browser and its version (浏览器及其版本)
Chrome 106.0.5249.103 arm64

### System and its version (系统及其版本)
MacOS 12.6

### Node version (Node 版本)
16.8

### Reappearance link (重现链接)
https://codesandbox.io/s/3l3ru8

### Reappearance steps (重现步骤)
设置upload  list-type="image-card" 并手动设置文件预览缩略图，文件为非图片文件（视频文件）

### Expected results (期望的结果)
拖拽上传文件时触发上传操作，非图片文件上传成功后可以手动设置预览缩略图

### Actual results (实际的结果)
拖拽上传文件时无响应 ，上传非图片文件（视频文件）时，文件上传成功后设置文件的thumbnailUrl属性后无法展示相关图片；
设置文件缩略图在on-finish 方法和 create-thumbnail-url 方法都进行过尝试，无法成功

**Comment by 07akioni** [comment]
目前确实只有图片才支持缩略图，这个不太合理

**Comment by unrjjlmn20185** [comment]
@07akioni 升级版本至 `2.34.x` ，发现自定义上传 `image-card`，`2.34.x`之前的版本上传后会默认显示预览缩略图，现在不显示了。这是否是期望的？这会对之前的不兼容。[demo 地址](https://codesandbox.io/s/gracious-surf-s0725s?file=/src/Demo.vue)
