### ISSUE TITLE
n-input-number doesn't allow to set input-props like n-input for changing type 

### ISSUE THREAD

**Issue by MichaelSchober** [tusen-ai/naive-ui#3866]
### This function solves the problem (这个功能解决的问题)
For the n-input-number component: 
It would be a lot more user friendly to change the type from type="text" to type="number" for users on mobile devices. 
With type="number" the user gets shown a mobile keyboard with numbers and doesn't have to switch keyboard to be able to type numbers. 

Could this be done? Or is it a Problem with native Browser Styles which get applied when using type="number"? 

Thank you so much for your help!
### Expected API (期望的 API)
`<n-input-number :input-props="{ type: 'number' }" />`

**Comment by 07akioni** [comment]
I've tried type="number" before and find there's some strange issue so it's not exposed.

**Comment by 07akioni** [comment]
I'm not quite sure about it. I'll investigate into it later and find if there is possibility.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
