### ISSUE TITLE
Enable n-input-number handlers in specific cases (min and max)

### ISSUE THREAD

**Issue by vicenterusso** [tusen-ai/naive-ui#3867]
### This function solves the problem (这个功能解决的问题)
Lets say I have a min of 30 and the value is 25 for some reason (from backend for example):

![](https://i.imgur.com/4uKMKJa.png)

It would be nice to have the "+" handler enabled and when clicked, the value changes to the minimum (30 in that case)

### Expected API (期望的 API)
No changes in API needed, or just a flag to enable this behavior

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
