### ISSUE TITLE
Upload组件上传成功回调中建议保留当前上传的File文件对象

### ISSUE THREAD

**Issue by Adangs** [tusen-ai/naive-ui#3868]
### This function solves the problem (这个功能解决的问题)
在finish回调中去获取当前上传的图片文件宽高
### Expected API (期望的 API)
before-upload回调中File文件对象是存在的，finish回调保持一致即可

<img width="554" alt="image" src="https://user-images.githubusercontent.com/5443355/195747089-7ba27b9f-4551-485f-a3b8-15f5562cc380.png">

**Comment by 07akioni** [comment]
这个确实可以考虑多存留一点时间

**Comment by 07akioni** [comment]
closed in #4085
