### ISSUE TITLE
【Data Table】    on-update:checked-row-keys  与  v-model:checked-row-keys 同时设置时，checkbox框无法被选中

### ISSUE THREAD

**Issue by sh1057771494** [tusen-ai/naive-ui#3872]
### TuSimple/naive-ui version (版本)
2.33.5

### Vue version (Vue 版本)
3.2.40

### Browser and its version (浏览器及其版本)
105.0.5195.127

### System and its version (系统及其版本)
windows 10

### Node version (Node 版本)
14.17.2

### Reappearance link (重现链接)
https://codesandbox.io/s/async-fire-lsnix2?file=/src/Demo.vue

### Reappearance steps (重现步骤)
1. 同时设置 v-model:checked-row-keys 以及 on-update:checked-row-keys 
2. 点击 checkbox 框

### Expected results (期望的结果)
点击 checkbox 框， checkbox 框被选中

### Actual results (实际的结果)
点击 checkbox 框， checkbox 无法被选中

**Comment by doom-9** [comment]
![image](https://user-images.githubusercontent.com/110001160/196142212-4daa9bd8-ff24-46dc-a061-ab543c900f2a.png)
这里改变的对象错了
