### ISSUE TITLE
Setting value of n-input to undefined does not clear entered text

### ISSUE THREAD

**Issue by roberthand9** [tusen-ai/naive-ui#3876]
### TuSimple/naive-ui version (版本)
2.33.5

### Vue version (Vue 版本)
3.2.40

### Browser and its version (浏览器及其版本)
106.0.5249.119 (Official Build) (64-bit)

### System and its version (系统及其版本)
Ubuntu 20.04

### Reappearance link (重现链接)
https://stackblitz.com/edit/vitejs-vite-jdzlxi?file=src%2FApp.vue

### Reappearance steps (重现步骤)
Enter input into a NInput, then programmatically change the value feeding the v-model to undefined, see the NInput does not clear the text

In the reproduction, click one of the three buttons after entering some text

### Expected results (期望的结果)
When the value is set to undefined the NInput should clear, the same as when the value is set to null

### Actual results (实际的结果)
The NInput does not clear

### Remarks (补充说明)
Great UI library!

**Comment by OrbisK** [comment]
This is intended.

See here: https://www.naiveui.com/en-US/light/docs/controlled-uncontrolled

**Comment by roberthand9** [comment]
Apologies, I incorrectly used v-model in the reproduction, it should now be updated

Is this still intended when the n-input is being fully controlled? i.e.

`<n-input @update:value="(val) => inputValue = val" :value="inputValue" />`

When the value is to undefined I wouldn't expect the state to remain?

**Comment by roberthand9** [comment]
I just fully read the page you sent, thanks!
