### ISSUE TITLE
Menu组件可不可以加入一个路由跳转的模式配置,push或者replace

### ISSUE THREAD

**Issue by qq295823929** [tusen-ai/naive-ui#3883]
### This function solves the problem (这个功能解决的问题)
有的系统的后台管理是其中一部分,所以顶部会有返回按钮,而后台管理的菜单如果经过多次点击跳转,那返回需要点击很多次.可不可以加个replace的路由跳转行为
### Expected API (期望的 API)
比如options=[{label:'人员管理',name:'PersonManage',mode:'replace'}],mode可以默认为push

**Comment by 07akioni** [comment]
menu 组件不直接处理路由相关的功能
