### ISSUE TITLE
当设置single-line为false且开启resizable后，拖拽线不会和单元格右边线重合

### ISSUE THREAD

**Issue by yanbowe** [tusen-ai/naive-ui#3890]
### TuSimple/naive-ui version (版本)
2.33.5

### Vue version (Vue 版本)
3.2.41

### Browser and its version (浏览器及其版本)
版本 106.0.5249.119（正式版本） (x86_64)

### System and its version (系统及其版本)
Macos(10.15.7)

### Reappearance link (重现链接)
https://codesandbox.io/s/sleepy-mendeleev-kxfs95?file=/src/Demo.vue

### Reappearance steps (重现步骤)
当name列开启resizable后，列宽拖拽线会单独占据一块儿
<img width="735" alt="image" src="https://user-images.githubusercontent.com/43030980/196625772-44b90130-aa46-4b94-b749-d890c2bb7896.png">

### Expected results (期望的结果)
当设置single-line为false且开启resizable后， 列宽拖拽功能会放在单元格右边线

### Actual results (实际的结果)
当name列开启resizable后，列宽拖拽线会单独占据一块儿

**Comment by chriszq8** [comment]
`
.n-data-table {
    .n-data-table-th {
        .n-data-table-resize-button {
            right: calc((var(--n-resizable-container-size) / -2) + 1px);
        }
    }
}
`
<img width="268" alt="image" src="https://user-images.githubusercontent.com/1823041/202884897-45633631-51e9-4d9c-ac35-5c1d4a2f85a0.png">

**Comment by HakimLu** [comment]
css 曲线救国

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
