### ISSUE TITLE
n-select分组，不同组child有相同value，scrolltop默认不是0

### ISSUE THREAD

**Issue by zz541843** [tusen-ai/naive-ui#3893]
### TuSimple/naive-ui version (版本)
2.33.5

### Vue version (Vue 版本)
3.2.41

### Browser and its version (浏览器及其版本)
106.0.1370.47 (正式版本) (64 位)

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://codesandbox.io/s/nice-beaver-3ibi20?file=/src/Demo.vue

### Reappearance steps (重现步骤)
有个业务场景，第一个分组是《常用选项》，第二个分组是《全部选项》，分组内的option会有相同的value值，然后点击select显示就会有问题，直接滚动到了第二个value值的位置
h函数写的太复杂了，我就没改，这应该是没有根据group的key去区分所有option的value
尽快修复！

### Expected results (期望的结果)
。

### Actual results (实际的结果)
。。

**Comment by amadeus711** [comment]
个人认为这是业务需求，自己在数据层面对“常用选项”等会出现重复 value 的地方对数据 map 处理即可

**Comment by zz541843** [comment]
> 个人认为这是业务需求，自己在数据层面对“常用选项”等会出现重复 value 的地方对数据 map 处理即可

我现在就是这么处理的，只能手动加key，取出来在去除key，硬要说这是业务需求也没毛病，但既然有组的概念，为什么不隔离value捏

**Comment by 07akioni** [comment]
> 就是这么处理的，只能手动加key，取出来在去除key，硬要说这是业务需求也没毛病，但既然有组的概念，为什么不隔离value捏

不同分组的值也不应该出现相同的，因为最终都会在 select 中被显示出来。

不能只想像每个值都是用户点出来的，假设存在一个默认值 1，然后对应于两个不同分组的 option，那么应该显示哪个被选中。
