### ISSUE TITLE
组件下拉菜单图标功能存在抖动BUG

### ISSUE THREAD

**Issue by MyBaymax** [tusen-ai/naive-ui#3895]
### TuSimple/naive-ui version (版本)
2.33.5

### Vue version (Vue 版本)
3.2.41

### Browser and its version (浏览器及其版本)
chrome(107.0.5304.10)

### System and its version (系统及其版本)
MacOS(12.6)

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/dropdown

### Reappearance steps (重现步骤)
 鼠标放在图标示例模块的用户资料（下拉菜单按钮）上

### Expected results (期望的结果)
与其他下拉菜单按钮一致，应该是一个淡入的过程

### Actual results (实际的结果)
无淡入过程，且发生抖动

**Comment by amadeus711** [comment]
https://user-images.githubusercontent.com/46394163/197331499-bd15836c-12f3-4f18-a6a7-61b0bba68457.mov

需要复现

**Comment by jahnli** [comment]
Closed due to inactivity. Feel free to reopen if you're still having trouble.
