### ISSUE TITLE
Add `timerange`  Support for `<NTimePicker />`

### ISSUE THREAD

**Issue by jahnli** [tusen-ai/naive-ui#390]
### This function solves the problem (这个功能解决的问题)
 component enhancements
### Expected API (期望的 API)
Any time range can be selected

**Comment by jahnli** [comment]
![image](https://user-images.githubusercontent.com/20943608/124449348-f427cc00-ddb5-11eb-81a9-11d85b0ad84c.png)

**Comment by jahnli** [comment]
Yes, I also think it's a complicated process, but I've consulted various UI libraries, and the multiple features of dates make it more popular

**Comment by 07akioni** [comment]
> Yes, I also think it's a complicated process, but I've consulted various UI libraries, and the multiple features of dates make it more popular

I know, we will do it after features with higher priority is implemented.
