### ISSUE TITLE
Add the option to set transform-origin for dialogs

### ISSUE THREAD

**Issue by rajmondburgaj** [tusen-ai/naive-ui#3901]
### This function solves the problem (这个功能解决的问题)
I see there is an option to add :transform-origin="'center'" for simple modals, but seems there is no such thing for dialogs, or maybe I can not find it!

Would i be possible to add it as well, so we can have the same behavor for dialogs as well in wanted?
### Expected API (期望的 API)
Add a new prop to set the :transform-origin="'center'" for dialogs

**Comment by jizai1125** [comment]
I tried, it is support though not described in the document.
`
 dialog.create({
     title: 'title',
     content: 'content',
      transformOrigin: 'center',
 })
`

**Comment by 07akioni** [comment]
> I tried, it is support though not described in the document.
> 
> ```ts
>  dialog.create({
>     title: 'title',
>     content: 'content',
>     transformOrigin: 'center',
>  })
> ```

It should be documented.

**Comment by jizai1125** [comment]
> > I tried, it is support though not described in the document.
> > ```ts
> >  dialog.create({
> >     title: 'title',
> >     content: 'content',
> >     transformOrigin: 'center',
> >  })
> > ```
> 
> It should be documented.

那我 write 一下
