### ISSUE TITLE
图像 Image 组件，图片预览情况下，右键图片，然后在页面的其他地方随便点击一下鼠标左键，然后拖动鼠标，发现图片也跟着被来回拖动了

### ISSUE THREAD

**Issue by xuanxuan321** [tusen-ai/naive-ui#3903]
### TuSimple/naive-ui version (版本)
2.33.5

### Vue version (Vue 版本)
3.2.41

### Browser and its version (浏览器及其版本)
chrome（版本 106.0.5249.119（正式版本） (x86_64)）

### System and its version (系统及其版本)
MacOS（12.6）

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/dark/components/image

### Reappearance steps (重现步骤)
1.打开https://www.naiveui.com/zh-CN/dark/components/image
2. 随便点击一张图片，弹出预览图
3. 在预览图上右键，鼠标下会出现一个菜单
4.在页面的其他地方随便点击一下鼠标左键，然后拖动鼠标，发现图片也跟着被来回拖动了

### Expected results (期望的结果)
右键图片后，再在页面上的其他部分点击左键，拖动鼠标，图片不希望也跟着移动

### Actual results (实际的结果)
右键图片后，再在页面上的其他部分点击左键，拖动鼠标，图片也跟着移动了

**Comment by 07akioni** [comment]
Mousedown 应该判断一下是哪个键

**Comment by WalkAlone0325** [comment]
这个问题有新提出的 issues，我提交了新的 pr。[#3950]

**Comment by 07akioni** [comment]
closed in #3950
