### ISSUE TITLE
TreeSelect add 'expand-on-click' from Tree prop

### ISSUE THREAD

**Issue by wh1tevs** [tusen-ai/naive-ui#3905]
### This function solves the problem (这个功能解决的问题)
Allow expand tree-select options on click
### Expected API (期望的 API)
add 'expand-on-click' prop and forward it to NTree component

**Comment by 07akioni** [comment]
It would conflict with `checkable` feature. I don't think this should be exposed.

**Comment by vcharov** [comment]
@07akioni You already have an expand-on-click implementation in https://www.naiveui.com/zh-CN/os-theme/components/tree#basic.vue 

Please do the same for NTreeSelect.
