### ISSUE TITLE
Add tab animation for `<NTab>` of `segment` type

### ISSUE THREAD

**Issue by KeroZhai** [tusen-ai/naive-ui#3910]
### The problem this function solves (这个功能解决的问题)

When using `<NTab>` of `line` type, there is a line movement animation. which is nice, but not for the `segment` type, it looks a little bit stiff when switching the active tab.

### Expected API (期望的 API)

No extra API needed.

**Comment by 07akioni** [comment]
PR welcomed. It's simply too complex to be implemented.

**Comment by 07akioni** [comment]
Also it's not add at first since font-weight's change has no transition.

**Comment by suica** [comment]
Antd uses a fancy animation in [`Segmented` component](https://ant.design/components/segmented). 
Is that a suitable for this?
If so I am willing to contribute.

**Comment by KeroZhai** [comment]
> Antd uses a fancy animation in [`Segmented` component](https://ant.design/components/segmented).
> Is that a suitable for this?
> If so I am willing to contribute.

This is it!

**Comment by Sepush** [comment]
nice to have but there is a lot of detail. happy hacking
