### ISSUE TITLE
渲染 icon

### ISSUE THREAD

**Issue by dc1314** [tusen-ai/naive-ui#3914]
### This function solves the problem (这个功能解决的问题)
 目前大部分项目菜单数据都是通过后端返回的，其中的 icon 一般都是一个字符串，前端接收到数据之后还要经过各种处理才能渲染出来 icon 图标，如何通过后端返回的 icon 字符串渲染图标呢
包括但不限于菜单数据
### Expected API (期望的 API)
菜单数据传入 icon 图标字符串就能渲染 icon

**Comment by Nakus0426** [comment]
可以用clas、svg、渲染函数、动态组件、jsx等等，处理起来并不麻烦

**Comment by 07akioni** [comment]
封装个 renderIcon 就好了

**Comment by anbeicat** [comment]
封装了renderIcon 也不行啊，这个好麻烦啊
