### ISSUE TITLE
动态表单，label-width没有响应式同步

### ISSUE THREAD

**Issue by zz541843** [tusen-ai/naive-ui#3920]
### TuSimple/naive-ui version (版本)
2.33.5

### Vue version (Vue 版本)
3.2.41

### Reappearance link (重现链接)
https://codesandbox.io/s/nice-beaver-3ibi20?file=/src/Demo.vue

### Reappearance steps (重现步骤)
如果动态的form-item的label-width小于当前表单的最大label-width，动态的form-item的label是不会更新width属性的，如果大于的话，那还是会改变整个表单的label-witdh的，奇怪的是，如果小于的情况下， 出发rules是会立马更新label-width的
并且，如果动态form-item是大于当前表单的label-witdh，在给他隐藏，当前form的label-witdh是不会缩小到原来的样子的，没有响应式更新

**Comment by 07akioni** [comment]
目前的实现是只有 onMounted 才会调用，如果要加功能的话大概率是通过 ref 暴露一个方法。
组件很难检测是不是 label 变了。

**Comment by recallwei** [comment]
+1

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
