### ISSUE TITLE
form表单部分验证的时候，多个选择字段的方式呗

### ISSUE THREAD

**Issue by zz541843** [tusen-ai/naive-ui#3921]
### This function solves the problem (这个功能解决的问题)
筛选rules的key感觉没必要啊，大部分的场景还是根据字段去挑选规则啊，可以把这个方式加上吗
### Expected API (期望的 API)
加个数组参数

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
