### ISSUE TITLE
表单对象如果赋值{}，所有表单项不会更新

### ISSUE THREAD

**Issue by zz541843** [tusen-ai/naive-ui#3929]
### TuSimple/naive-ui version (版本)
2.33.5

### Vue version (Vue 版本)
3.2.41

### Reappearance link (重现链接)
codesandbox.io还没玩明白...

### Expected results (期望的结果)
如题，如果我要清空一组已填写的表单数据，照理只要给formData={}就行了，可这样行不通，或者有一个表单切换，有多组表单数据，复用同一个表单组件，切换formData也会有问题
这样是正常的，需要手动给属性赋空值吗？

**Comment by amadeus711** [comment]
`formData={}` 是一个危险操作，这意味着 `formData ` 下的属性可能没有（注意并不是对象属性为空），这并不符合组件的设计。通常情况你可以维护一个 `initFormData`，组件加载时默认取这个值，当清空表单时，也可以用这个做覆盖。
