### ISSUE TITLE
主题编辑器导出为空

### ISSUE THREAD

**Issue by FlyingDreamSky** [tusen-ai/naive-ui#3930]
### TuSimple/naive-ui version (版本)
2.33.5

### Vue version (Vue 版本)
3.2.41

### Browser and its version (浏览器及其版本)
Edge(106.0.1370.52)

### System and its version (系统及其版本)
win11

### Reappearance link (重现链接)
https://www.naiveui.com/en-US/dark/docs/customize-theme

### Reappearance steps (重现步骤)
页面右下角的Theme Editor按钮，导出主题为空

### Expected results (期望的结果)
筛选或不筛选组件变量的时候，将当前默认值也导出来

### Actual results (实际的结果)
主题编辑器中重新修改的才会被导出，原有默认值没有被导出，比如*color*这些变量

**Comment by 07akioni** [comment]
默认值没有导出是因为运行时不需要这些值，导出的话就太大了
