### ISSUE TITLE
select滚动加载

### ISSUE THREAD

**Issue by flyingTodream** [tusen-ai/naive-ui#3932]
### TuSimple/naive-ui version (版本)
2.33.5

### Vue version (Vue 版本)
3.2.41

### Browser and its version (浏览器及其版本)
106.0.5249.119

### System and its version (系统及其版本)
MacOS(12.6)

### Reappearance link (重现链接)
https://codesandbox.io/s/w8z4su

### Reappearance steps (重现步骤)
打开select选择框，往下滚动，并不会触发滚动加载

### Expected results (期望的结果)
滚动到底部，触发加载

### Actual results (实际的结果)
并未触发（需要currentTarget.scrollTop +  currentTarget.offsetHeight  +  0.5才可以触发）

**Comment by amadeus711** [comment]
![20221026141423](https://user-images.githubusercontent.com/46394163/197948868-a2edbc25-c2b0-45fc-8109-8df5ff2d3700.gif)
没有复现，需要更多信息

**Comment by 07akioni** [comment]
那可能就是需要增加一点缓冲才能保证触发
