### ISSUE TITLE
carousel轮播图组件，当只有两张时，最后一张和第一张轮播，会有一个往左的拉动效果

### ISSUE THREAD

**Issue by zhengdaonian** [tusen-ai/naive-ui#3937]
### TuSimple/naive-ui version (版本)
2.33.5

### Vue version (Vue 版本)
3.2.41

### Browser and its version (浏览器及其版本)
chrome(106.0.5249.119)

### System and its version (系统及其版本)
win 10 

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/carousel

### Reappearance steps (重现步骤)
一、https://www.naiveui.com/zh-CN/os-theme/components/carousel相邻间距模块
二、将图片删除至只剩两张
三、最后一张向右拖动，就会有一个怪异的向左拉动效果

### Expected results (期望的结果)
兼容两张轮播图，轮播图播放效果流畅

### Actual results (实际的结果)
carousel轮播图组件
四张得拖动效果正常播放，最后一张和第一张轮播，轮播流畅
当只有两张时，最后一张和第一张轮播，会有一个往左得拉动效果

**Comment by zhengdaonian** [comment]
怪异得向左拉动效果
https://user-images.githubusercontent.com/60170001/200570447-d924d245-ffa7-4e9d-be57-2a1be0453076.mp4
正常流畅得拉动效果
https://user-images.githubusercontent.com/60170001/200570768-64fd205e-3f8e-4ba4-933c-aeb7453c4d3e.mp4

**Comment by zhengdaonian** [comment]
怪异得向左拉动效果

https://user-images.githubusercontent.com/60170001/200571035-d8212ce6-0bff-4f77-b6b0-ceb262c1c4d0.mp4


正常流畅得拉动效果

https://user-images.githubusercontent.com/60170001/200571060-530f0e4d-91e6-4a66-ab34-28e1770a6eab.mp4

**Comment by 07akioni** [comment]
> 

这个好像只有音频

**Comment by zhengdaonian** [comment]
https://user-images.githubusercontent.com/60170001/201468885-7a5cbcfa-d385-408b-9ae7-7d07e5e27900.mp4

**Comment by nooooooom** [comment]
这样只判断了左滑的情况，对于右滑的处理逻辑也是一样的

**Comment by zhengdaonian** [comment]
现在得效果
https://user-images.githubusercontent.com/60170001/201610638-28e90099-3bdb-430c-b85c-1877a108de4f.mp4
期望得效果
https://user-images.githubusercontent.com/60170001/201611187-1a32412b-4e8a-4288-9389-aec44790799b.mp4

**Comment by jizai1125** [comment]
这个问题还是存在
