### ISSUE TITLE
增加单位适配入口

### ISSUE THREAD

**Issue by Canees** [tusen-ai/naive-ui#3940]
### This function solves the problem (这个功能解决的问题)
解决PC高分屏字体适配问题，
就目前flex针对布局非常友好，
但字体适配目前没有好的处理方式，
如果UI库能提供修改各组件单位入口，对开发者而言非常实用
### Expected API (期望的 API)
1. 增加适全局配置项（可在主题json中配置），单位类型可自定义，默认使用px

**Comment by 07akioni** [comment]
没理解什么意思。px 应该是没有可能改成别的单位的，比如 rem 什么的和目前的实现原理冲突

**Comment by Canees** [comment]
自己简单做了 组件 px 转 rem 插件，有需要自取：http://git.jdjinsui.com/gandongdong/naivePx2Rem.git
