### ISSUE TITLE
Switch不支持文字描述

### ISSUE THREAD

**Issue by YaKazama** [tusen-ai/naive-ui#3942]
### This function solves the problem (这个功能解决的问题)
在开关的外部显示文件，而不仅仅只能在开关内部显示。
### Expected API (期望的 API)
与此类似：https://element-plus.gitee.io/zh-CN/component/switch.html#%E6%96%87%E5%AD%97%E6%8F%8F%E8%BF%B0

**Comment by amadeus711** [comment]
感觉没太大必要

**Comment by x101046** [comment]
确实，switch的这种文字描述才是真实业务中使用得比较多的情况
