### ISSUE TITLE
Image组件进行图片预览按住鼠标滚轮、右键或鼠标扩展按键时均可对图片进行拖拽

### ISSUE THREAD

**Issue by maddenBoy** [tusen-ai/naive-ui#3950]
### TuSimple/naive-ui version (版本)
2.33.5

### Vue version (Vue 版本)
3.2.41

### Browser and its version (浏览器及其版本)
Chrome（106.0.5249.119）

### System and its version (系统及其版本)
window 11

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/image

### Reappearance steps (重现步骤)
1、点击图像Image基础用法的图片进行预览
2、按住鼠标右键或滚轮或鼠标任意扩展键均可拖动图片

### Expected results (期望的结果)
只有按住鼠标左键时可拖动图片

### Actual results (实际的结果)
按住鼠标任意键都可拖动图片

**Comment by 07akioni** [comment]
fixed in #3950
