### ISSUE TITLE
n-select组件on-create事件异常

### ISSUE THREAD

**Issue by zhengdaonian** [tusen-ai/naive-ui#3951]
### TuSimple/naive-ui version (版本)
2.33.5

### Vue version (Vue 版本)
3.2.41

### Browser and its version (浏览器及其版本)
chrome(106.0.5249.119)

### System and its version (系统及其版本)
win 10

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/select#API

### Reappearance steps (重现步骤)
一、在n-select组件中，调用on-create
二、他就报错669行Cannot read properties of undefined (reading 'value'）

### Expected results (期望的结果)
修复on-create事件

### Actual results (实际的结果)
on-create事件报错

**Comment by WalkAlone0325** [comment]
看下类型 `(label: string) => SelectOption` ，你需要 `return` 一个 `SelectOption` 类型的数据。e.g. `label => ({ label, value: label })`
