### ISSUE TITLE
希望提供n-select组件on-create事件得操作demo

### ISSUE THREAD

**Issue by zhengdaonian** [tusen-ai/naive-ui#3952]
### This function solves the problem (这个功能解决的问题)
这个事件不在Create debug这个demo里，不太明白这个事件是干什么得
### Expected API (期望的 API)
希望提供n-select组件on-create事件例子

**Comment by 07akioni** [comment]
和 `tag` 属性配合使用。

**Comment by 07akioni** [comment]
补充了一下文档 48ac18771cefd5
