### ISSUE TITLE
关于输入框表情输入长度问题

### ISSUE THREAD

**Issue by WHYHAHA** [tusen-ai/naive-ui#3967]
### TuSimple/naive-ui version (版本)
2.33.5

### Vue version (Vue 版本)
3.2.41

### Browser and its version (浏览器及其版本)
Chrome

### System and its version (系统及其版本)
macos

### Reappearance link (重现链接)
https://codesandbox.io/s/thirsty-smoke-jmv1eb?file=/src/Demo.vue

### Reappearance steps (重现步骤)
输入框30个文字限制  表情只能输入15个之后不能输入了

### Expected results (期望的结果)
输入框中显示正确的表情占位 两个  希望全部输入组件都能支持这个输入表情问题

### Actual results (实际的结果)
输入框中显示正确的表情占位 一个

**Comment by 07akioni** [comment]
Emoji 长度衡量是个非常复杂的问题，会提供一个解决方案
