### ISSUE TITLE
n-data-table,使用ellipsis和固定列宽，没有Tooltip效果，以及换行

### ISSUE THREAD

**Issue by zhengdaonian** [tusen-ai/naive-ui#3974]
### TuSimple/naive-ui version (版本)
2.33.5

### Vue version (Vue 版本)
3.2.41

### Browser and its version (浏览器及其版本)
Chrome106.0.5249.119

### System and its version (系统及其版本)
win 10

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/tooltip

### Reappearance steps (重现步骤)
一、设置列宽以及width
二、鼠标滑过没有tooltip效果

### Expected results (期望的结果)
不换行以及修复tooltip

### Actual results (实际的结果)
svg换行以及tooltip效果确实

**Comment by zhengdaonian** [comment]
正常效果
![image](https://user-images.githubusercontent.com/60170001/199142674-5b31272f-5cc8-43b2-b251-b87a9ead8895.png)
列宽小时换行
![image](https://user-images.githubusercontent.com/60170001/199142738-de0807cb-68bb-4e11-9541-568f95c3fec5.png)
更小时出现ellipsis效果，鼠标滑过没有tooltip效果
![Uploading image.png…]()

**Comment by jizai1125** [comment]
没问题呀
https://codesandbox.io/s/zealous-almeida-y4q1hx?file=/src/Demo.vue
![image](https://user-images.githubusercontent.com/33979706/200984362-84608f0b-802b-4a7d-98cd-bc3748b7d4db.png)
