### ISSUE TITLE
n-tree 是否可以增加级联策略

### ISSUE THREAD

**Issue by shen-xiansen** [tusen-ai/naive-ui#3975]
### This function solves the problem (这个功能解决的问题)
业务需求是在勾选父级节点的时候，将所有子孙节点勾选上，但是所有子级勾选的时候不勾选父级勾选。如果cascade配置为false，无法做到在勾选父级的时候，将所有子孙节点勾选上。若cascade配置为true，在勾选了全部子级时会默认勾选父级，这不是我们想要的效果。

例如：

现在有这样的一个树

- [ ] 部门A
    - [ ] 部门A-子部门1
    - [ ] 部门A-子部门2
- [ ] 部门B 

如果此时我选中 `部门A-子部门1` 和 `部门A-子部门2` 时，`部门A` 可以不默认选中。因为业务需要，`部门A` 不等价于 `部门A-子部门1` 和 `部门A-子部门2` 的并集。

效果如下

- [ ] 部门A <-- 希望这个选项可以不默认选中
    - [x] 部门A-子部门1
    - [x] 部门A-子部门2
- [ ] 部门B 

而当前的效果是

- [x] 部门A <-- 这个选项默认选中了，没有配置可以更改这种策略
    - [x] 部门A-子部门1
    - [x] 部门A-子部门2
- [ ] 部门B 

是否可以在cascade配置为true时，增加一个属性用于配置这种级联是向上的（勾选父级），或向下的（勾选子级），或全部？

### Expected API (期望的 API)
新增 `cascade-strategy` 属性用于配置 `n-tree` 的 checkbox 父子级勾选级联策略

**Comment by shen-xiansen** [comment]
@07akioni

**Comment by jahnli** [comment]
@shen-xiansen  基础用法是不是就是你想要的效果

**Comment by shen-xiansen** [comment]
@jahnli 业务上需要在勾选父级的时候，将所有子级勾选上，但是所有子级勾选的时候不勾选父级，基础用法无法满足

**Comment by szluyu99** [comment]
我也遇到问题了，就是在级联模式下，我选中某个父节点，其子节点全部被选中了。

然后我给该父节点添加了一个新的子节点，刷新展示时这个子节点默认被选中了（因为父节点被选中了）

但是点保存，实际传值时，却没有传该子节点的值。

**Comment by jizai1125** [comment]
> @jahnli 业务上需要在勾选父级的时候，将所有子级勾选上，但是所有子级勾选的时候不勾选父级，基础用法无法满足

你 `cascade: false`，手动维护 `checked-keys` 不行么

**Comment by jahnli** [comment]
@shen-xiansen

**Comment by shen-xiansen** [comment]
@jizai1125 可以的，谢谢

**Comment by 07akioni** [comment]
建议手动添加，对于组件来说级联运算应该是一个函数式的过程，不能依赖操作过程，否则从异步数据还原状态一定会出问题。

**Comment by HadeAs** [comment]
我有个跟他相反的问题，我希望在级联模式下，勾选父节点，其下的子节点不勾选。勾选子节点，还是按照已有的级联模式！这种业务场景一般在角色权限配置中很常见，父节点可能是菜单权限，子节点可能是菜单下的组件权限。我勾选父节点，但是我不想子节点也被选中（我只分配给角色的菜单权限，不分配菜单下的组件权限）
