### ISSUE TITLE
docs(dynamic-input): add examples how to customize buttons

### ISSUE THREAD

**Issue by OrbisK** [tusen-ai/naive-ui#3978]
### This function solves the problem (这个功能解决的问题)
Currently customizing buttons is not documented well. The reference in the `CHANGELOG.md` is missing too.
### Expected API (期望的 API)
/

**Comment by OrbisK** [comment]
What effect has `create-button-default`?
Maybe this is not a docs proplem. It might be a bug.

### Reproduction:
https://codesandbox.io/s/de6f3d?file=/src/Demo.vue

### Issue
where is the slot applied?

**Comment by jizai1125** [comment]
The `create-button-default` slot is only used to set the contents of the button,  It is actually the default slot of the button component.

**Comment by OrbisK** [comment]
> The `create-button-default` slot is only used to set the contents of the create button, It is actually the default slot of the button component.

can you please clarify what you mean by "the button".  Or maybe share a screenshot where the slot is applied?

**Comment by OrbisK** [comment]
> > The `create-button-default` slot is only used to set the contents of the create button, It is actually the default slot of the button component.
> 
> can you please clarify what you mean by "the button". Or maybe share a screenshot where the slot is applied?

nvm. its the button if no field is created 😅

**Comment by OrbisK** [comment]
ill add an example for this later :)

**Comment by jizai1125** [comment]
> > > The `create-button-default` slot is only used to set the contents of the create button, It is actually the default slot of the button component.
> > 
> > 
> > can you please clarify what you mean by "the button". Or maybe share a screenshot where the slot is applied?
> 
> nvm. its the button if no field is created 😅

yes

**Comment by OrbisK** [comment]
Referenced in #3981
