### ISSUE TITLE
feat(dynamic-input): customizable add/delete/move buttons

### ISSUE THREAD

**Issue by OrbisK** [tusen-ai/naive-ui#3981]
### This function solves the problem (这个功能解决的问题)
The default buttons are currently not customizable.
### Expected API (期望的 API)
```html
<n-dynamic-input>
  <template #action="{create, delete, moveUp, moveDown, }">
    <n-button-group>
      <n-button @click="create.handler" :disabled="create.isDisabled">➕</n-button>
      <n-button @click="delete.handler" :disabled="delete.isDisabled">➖</n-button>
      <n-button @click="moveUp.handler" :disabled="moveUp.isDisabled">🆙</n-button>
      <n-button @click="moveDown.handler" :disabled="moveDown.isDisabled">👇🏽</n-button>
    </n-button-group>
  </template>
</n-dynamic-input>
```

I think my slotProps are not perfect. But they doing there job here 😄.

An additional render function would be nice.

**Comment by amadeus711** [comment]
I think it may not be possible to provide `#action`, but I can add slots for custom buttons

**Comment by amadeus711** [comment]
I think we usually just want to custom the button icon, right?

**Comment by OrbisK** [comment]
> I think we usually just want to custom the button icon, right?

Usally icons.

Maybe we can provide a prop like buttonProps

**Comment by amadeus711** [comment]
> 
No problem. I'll develop this plan.
