### ISSUE TITLE
upload 组件上传完成事件中的 event 为 undefined

### ISSUE THREAD

**Issue by taurusxin** [tusen-ai/naive-ui#3987]
### TuSimple/naive-ui version (版本)
2.33.5

### Vue version (Vue 版本)
3.2.41

### Browser and its version (浏览器及其版本)
107.0.5304.87

### System and its version (系统及其版本)
macOS 13.0

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/upload

### Reappearance steps (重现步骤)
```vue
<template>
<n-upload
  action="/api/upload"
  :on-finish="handleUploadFinish"
>
  <n-button>上传文件</n-button>
</n-upload>
</template>

<script setup lang="ts">
function handleUploadFinish(file: UploadFileInfo, event?: ProgressEvent) {
  console.log(event)
}
</script>
```

### Expected results (期望的结果)
ProgressEvent 对象

### Actual results (实际的结果)
undefined

**Comment by Wyatex** [comment]
我在codesandbox中使用https://www.naiveui.com/zh-CN/os-theme/components/upload#on-finish.vue的代码试了一下没重新问题

**Comment by taurusxin** [comment]
> 我在codesandbox中使用[https://www.naiveui.com/zh-CN/os-theme/components/upload#on-finish.vue的代码试了一下没重新问题](https://www.naiveui.com/zh-CN/os-theme/components/upload#on-finish.vue%E7%9A%84%E4%BB%A3%E7%A0%81%E8%AF%95%E4%BA%86%E4%B8%80%E4%B8%8B%E6%B2%A1%E9%87%8D%E6%96%B0%E9%97%AE%E9%A2%98)

已经解决，方法的参数写的有问题，参照文档后应该这么写：
```ts
function handleUploadFinish({ file, event }: { file: UploadFileInfo; event?: ProgressEvent }) {
  console.log(event)
}
```
