### ISSUE TITLE
for the NTree Update callback function,jahnli's change merge failed

### ISSUE THREAD

**Issue by cai1035752265** [tusen-ai/naive-ui#3989]
### TuSimple/naive-ui version (版本)
2.33.5

### Vue version (Vue 版本)
3.2.41

### Browser and its version (浏览器及其版本)
Chrome

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://github.com/tusen-ai/naive-ui/pull/3959

### Reappearance steps (重现步骤)
tree的update函数缺少第三参数即当前操作的节点信息，发现issue#3959已经实现该功能但是在合并步骤有冲突需要有权限的人去合并。

### Expected results (期望的结果)
tree的update函数有第三参数即当前操作的节点信息

### Actual results (实际的结果)
第三参数的代码未合并

**Comment by amadeus711** [comment]
Pr 合并前我们会解决其冲突。
