### ISSUE TITLE
Introduce a "secondary" color theme variable.

### ISSUE THREAD

**Issue by ChronicStone** [tusen-ai/naive-ui#3990]
### This function solves the problem (这个功能解决的问题)
Currently, when working with existing design systems, in most cases the brand colors includes more than a single color. This makes working w/ naive ui on existing branding & design system tricky.

Current workaround is to "sacrifice" one of the existing sets of customizable color props (info, warning, ...) & use it as a secondary. But sacrificing an existing color for this purpose is quite troublesome, and is a dirty workaround, not a real solution.

Now, brand colors can include more than just two colors, and naive ui isn't going to implement 10 custom extra variants, but just having a "secondary" color to play with would already make the process of working with existing branding much easier and cleaner.
### Expected API (期望的 API)
The exact same way "primary" works, implement a new secondary color props with its state variants (hover, ...) that would be consumable by the different components on the app.

Moreover, let the possibility to the user, on all input fields & other components that solely rely on primary color, to choose which color to use / apply as accent color.

**Comment by 07akioni** [comment]
I think it's a hard thing to implement since it would add too many controll flows only for color choosing. I know your problem but customization is always a hard problem. If we provide more middle layers the code would bloat.

**Comment by 07akioni** [comment]
Maybe currently the best way is to create some secondary theme-overrides for components then choose `type="primary"`.

For example

```
<n-xxx :theme-overrides="yyy" type="primary" /> // yyy is actually the secondary color configuration that you wants
```
