### ISSUE TITLE
Error: [Vue warn]: Component is missing template or render function. 

### ISSUE THREAD

**Issue by bitsnaps** [tusen-ai/naive-ui#3991]
### TuSimple/naive-ui version (版本)
2.33.5

### Vue version (Vue 版本)
3.2.41

### Browser and its version (浏览器及其版本)
Chrome(107.0.5304.87)

### System and its version (系统及其版本)
MacOS(10.14.6)

### Reappearance link (重现链接)
https://stackblitz.com/edit/vitejs-vite-ezpptt?file=src/App.vue

### Reappearance steps (重现步骤)
1- Create a new Vite/Vue3 app
2- Create a button that shows a Message component (just like: https://www.naiveui.com/en-US/light/components/message)
3- Run on dev

### Expected results (期望的结果)
It shows message on click event, it works when importing all components globally (which is not recommended as the docs mentioned).

### Actual results (实际的结果)
Nothing rendered and warning shown.

### Remarks (补充说明)
Reproduced example at: https://stackblitz.com/edit/vitejs-vite-ezpptt?file=src/App.vue
Browsers: Tried on Chrome, Firefox.

**Comment by amadeus711** [comment]
https://stackblitz.com/edit/vitejs-vite-a3zu8b?file=src%2Fcomponents%2FHelloWorld.vue,src%2FApp.vue
There is a problem with `n-message-provider`'s import in your link.
