### ISSUE TITLE
Slider demo for custom thumb is not rendering custom thumb

### ISSUE THREAD

**Issue by hkurra** [tusen-ai/naive-ui#3992]
### TuSimple/naive-ui version (版本)
2.33.5

### Vue version (Vue 版本)
3.2.41

### Browser and its version (浏览器及其版本)
Version 106.0.5249.119

### System and its version (系统及其版本)
MacOS(12.2.1 (21D62))

### Node version (Node 版本)
14.19.3

### Reappearance link (重现链接)
https://codesandbox.io/s/tvfypn?file=/src/Demo.vue:478-496

### Reappearance steps (重现步骤)
Open the custom thumb demo
It is not rendering the custom thumb because the slot name has changed from header to thumb

### Expected results (期望的结果)
Under `custom-thumb.demo` file, the slot for custom thumb should be `#thumb` instead of `#header`

### Actual results (实际的结果)
Currently, the custom thumb slot is set to `header`

**Comment by hkurra** [comment]
![image](https://user-images.githubusercontent.com/6569316/199988413-2bc87fd6-69e6-4c37-86d3-1abac44b4e25.png)

**Comment by amadeus711** [comment]
The problem has been fixed, after the next version is released
