### ISSUE TITLE
Tooltips: consider a generic mouseover prop for all components

### ISSUE THREAD

**Issue by mnantel** [tusen-ai/naive-ui#3996]
### This function solves the problem (这个功能解决的问题)
Tooltips are highly common in usage. Coming over from bootstrap-vue (so far, NaiveUI is otherwise great), this is a huge time and code saver:

`<b-button v-b-tooltip.hover title="Tooltip directive content">`

Thank you for considering!
### Expected API (期望的 API)
I wouldnt begin to have an idea :) I am unfortunately a beginner programmer who relies on frameworks to do heavy lifting...

**Comment by 07akioni** [comment]
We won't implement API in directive mode. This is a fundamental choice. If you really need it please consider encapsulate your code in a component.
