### ISSUE TITLE
[NDropdown] Get a warning and error when there is no trigger slot

### ISSUE THREAD

**Issue by ylc395** [tusen-ai/naive-ui#3997]
### TuSimple/naive-ui version (版本)
2.33.5

### Vue version (Vue 版本)
3.2.41

### Browser and its version (浏览器及其版本)
latest

### System and its version (系统及其版本)
mac 11.2.3

### Reappearance link (重现链接)
https://stackblitz.com/edit/vue-rdocid?file=src/App.vue

### Reappearance steps (重现步骤)
1. import `NDropdown`
2. use `NDropdown` with `trigger="manual"` but without a default slot
3. get a warning and error

### Expected results (期望的结果)
Since `trigger="manual"` means no trigger element/component is needed, no warning or error should be thrown.

### Actual results (实际的结果)
get a warning and error

**Comment by 07akioni** [comment]
You can't set show to true without `x` and `y` in `manual` mode
