### ISSUE TITLE
n-select value值为number的时候，表单验证失败

### ISSUE THREAD

**Issue by laterdays** [tusen-ai/naive-ui#4002]
### TuSimple/naive-ui version (版本)
2.33.5

### Vue version (Vue 版本)
3.2.41

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
windows

### Reappearance link (重现链接)
https://codesandbox.io/s/ecstatic-brown-w9fq7h?file=/src/Demo.vue

### Reappearance steps (重现步骤)
n-select value值为number的时候，表单验证失败

### Actual results (实际的结果)
n-select value值为number的时候，表单验证失败

### Remarks (补充说明)
n-select value值为number的时候，表单验证失败

**Comment by laterdays** [comment]
@Talljack   具体指的是哪个type ?  v-model的type还是select组件的type ?

**Comment by Talljack** [comment]
> @Talljack 具体指的是哪个type ? v-model的type还是select组件的type ?

![Uploading image.png…]()
selectValue的type

**Comment by Talljack** [comment]
selectValue: {
          required: true,
          type: 'number',
          trigger: ["blur", "change"],
          message: "请选择 selectValue",
        },
