### ISSUE TITLE
Datatable同时定义了row-props和selection会冲突

### ISSUE THREAD

**Issue by imtns** [tusen-ai/naive-ui#4008]
### TuSimple/naive-ui version (版本)
2.33.5

### Vue version (Vue 版本)
3.2.41

### Browser and its version (浏览器及其版本)
107.0.5304.87

### System and its version (系统及其版本)
10.15.6

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/data-table

### Reappearance steps (重现步骤)
点击checkbox勾选的时候会触发rowProps的onClick事件，导致勾选的时候页面跳走了（跳转事件在rowProps的click里），请问点击checkbox的时候怎么阻止rowProps的click事件？

### Expected results (期望的结果)
勾选checkbox的时候可以阻止rowProps的click事件

### Actual results (实际的结果)
点击checkbox勾选的时候会触发rowProps的onClick事件，导致勾选的时候页面跳走了（跳转事件在rowProps的click里），请问点击checkbox的时候怎么阻止rowProps的click事件？
``` 
      {
          type: 'selection',
        },
      rowProps: (row: RowData) => {
              return {
                style: 'cursor: pointer;',
                onClick: () => {
                  message.info(row.name)
                }
              }
      },
```

**Comment by NacoHayashi** [comment]
请问这个问题解决了吗？也遇到相同问题，目前先在row-props事件里确认event target 是不是checkbox，但似乎不是个很好的解。希望可以点击checkbox的时候不要触发row-props

**Comment by recallwei** [comment]
We cannot access the checkbox element of selection column.
