### ISSUE TITLE
tree select 在按住ctrl键时无法选择项

### ISSUE THREAD

**Issue by fashman** [tusen-ai/naive-ui#4013]
### This function solves the problem (这个功能解决的问题)

想动态控制tree的multiple，按住ctrl时可以多选，否则只能单选，发现按住ctrl之后不会触发on-update:selected-keys，无法在去选择某一项；
尝试禁用keyboard，但没有任何效果
### Expected API (期望的 API)
希望按住键盘时，on-update:selected-keys 事件可以正常触发

**Comment by 07akioni** [comment]
单选和多选之间显示逻辑和用值的逻辑是有冲突的，不建议这么搞。
另外需要一个复现。

**Comment by FEITENGGUI** [comment]
在meta 2.34.0版本中，n-tree组件的在开启多选的时候，按住Ctrl并选中时，可以正确触发on-update:selected-keys事件。这个时候可以通过window.event.ctrlKey判断是否有按住Ctrl按键。不过ts提示window.event已弃用
