### ISSUE TITLE
`pnpm run gen-volar-dts` 运行失败

### ISSUE THREAD

**Issue by jizai1125** [tusen-ai/naive-ui#4015]
### TuSimple/naive-ui version (版本)
2.33.5

### System and its version (系统及其版本)
MacOS 12.2.1

### Node version (Node 版本)
14.19.0

### Reappearance link (重现链接)
![image](https://user-images.githubusercontent.com/33979706/200981241-a037071e-fee3-46cf-83c4-61712bf2dbd6.png)

![image](https://user-images.githubusercontent.com/33979706/200981081-cbc27800-3e37-46f0-b53b-9122dc2d734c.png)

**Comment by Talljack** [comment]
nodejs版本太低了吧 升级下版本
<img width="851" alt="image" src="https://user-images.githubusercontent.com/34439652/201105142-a7bbc3e7-9d34-40c2-8c52-34bb9067caba.png">
