### ISSUE TITLE
DataTable 固定头部和列在 Safari 浏览器中滚动卡顿

### ISSUE THREAD

**Issue by jizai1125** [tusen-ai/naive-ui#4020]
### TuSimple/naive-ui version (版本)
2.33.5

### Vue version (Vue 版本)
3.2.44

### Browser and its version (浏览器及其版本)
Safari 15.3

### System and its version (系统及其版本)
MacOS 12.2.1

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/data-table#fixed-header-column.vue

###  Actual results (实际的结果)

https://user-images.githubusercontent.com/33979706/201058696-4b151ba1-4da4-4e7d-a65b-01668d2fb5eb.mp4

**Comment by 07akioni** [comment]
The problem is complex and not easy to fix.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
