### ISSUE TITLE
Add collapsed option for horizontal menu

### ISSUE THREAD

**Issue by ilgiznurgaliev** [tusen-ai/naive-ui#4022]
### This function solves the problem (这个功能解决的问题)
At the moment when horizontal menu overlaps it adds elipssis to each menu option:
![image](https://user-images.githubusercontent.com/10621366/201281807-8bfada88-b530-4c87-8824-819dfb6be243.png)

Is it possible to implement collapsing like below?
![image](https://user-images.githubusercontent.com/10621366/201281692-402d1aff-c40a-4b5b-bc35-e75d6823dd2a.png)

### Expected API (期望的 API)
Three possible options:
- collapse menu by default when it overlaps
- use the same `collapsed` attribute, but with different behaviour for horizontal menu
- add a new boolean attribute for this feature

**Comment by 07akioni** [comment]
will add in next version
