### ISSUE TITLE
NCalendar: display by day and week, responsive columns

### ISSUE THREAD

**Issue by MaximSedov** [tusen-ai/naive-ui#4024]
### This function solves the problem (这个功能解决的问题)
- Implemented viewing only by month 
Add calendar display by day and week

- The calendar is not configured for different screen sizes and viewports.
The calendar does not move columns to the next line when changing the screen size, it looks uncomfortable

![image](https://user-images.githubusercontent.com/41785330/201365168-338bb230-c5b8-4c64-89cf-14e3f1a34aa5.png)

### Expected API (期望的 API)
-In the calendar header add a selector to choose the type of display

-Automatically move calendar columns as https://www.naiveui.com/en-US/os-theme/components/grid - responsive columns

**Comment by 07akioni** [comment]
We won't do it due to large amount of work. However PR is welcomed.
