### ISSUE TITLE
动态录入 Dynamic Input组件的一个问题

### ISSUE THREAD

**Issue by popdo** [tusen-ai/naive-ui#4036]
### TuSimple/naive-ui version (版本)
2.33.5

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Microsoft Edge 版本 107.0.1418.35 (正式版本) (x86_64)

### System and its version (系统及其版本)
macos 13

### Reappearance steps (重现步骤)
动态录入 Dynamic Input组件,设置了排序按钮show-sort-button之后。点击上下排序箭头 响应式数组中的所有子元素都变成了proxy类型响应数据。这会对数组需要进行toRaw处理会失效，因为数组中每个元素都变成响应式的了。

**Comment by amadeus711** [comment]
https://codesandbox.io/s/dark-wood-s8zxee?file=/src/Demo.vue
并没有发现你说的现象

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
