### ISSUE TITLE
Custom date cell content in the Date Picker

### ISSUE THREAD

**Issue by yuriifabirovskyi** [tusen-ai/naive-ui#4037]
### This function solves the problem (这个功能解决的问题)
Often, I need to mark a day in the date picker to notify the user of some events. In my case, I want to notify the user about upcoming discounts during order checkout. I believe that this is a very useful feature because it is implemented in many other frameworks
### Expected API (期望的 API)
Default slot (as it done in [Element Plus](https://element-plus.org/en-US/component/date-picker.html#slots))
Or prop to pass rendering function (as it done in [Ant Design](https://antdv.com/components/date-picker#Common-API))

**Comment by JerryWang24** [comment]
请问一下这个功能现在添加了吗？很急，在线等~~ @07akioni

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
