### ISSUE TITLE
[docs]N-Text documentation

### ISSUE THREAD

**Issue by tiamed** [tusen-ai/naive-ui#4042]
### This function solves the problem (这个功能解决的问题)
N-Text is useful but there's no documentation for this component
### Expected API (期望的 API)
https://www.naiveui.com/zh-CN/dark/components/tag

**Comment by 07akioni** [comment]
See https://www.naiveui.com/zh-CN/os-theme/components/typography

**Comment by hyp530** [comment]
> See https://www.naiveui.com/zh-CN/os-theme/components/typography

@07akioni The property 'strong' doesn't work on Chinese characters:

      <n-text strong>
         测试 Text
      </n-text>
