### ISSUE TITLE
[ERROR] Could not resolve "vue" when use @vicons ionicons5@0.12.0

### ISSUE THREAD

**Issue by liyunde** [tusen-ai/naive-ui#4046]
### TuSimple/naive-ui version (版本)
2.33.5

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Chrome(107.0.5304.107)

### System and its version (系统及其版本)
win(11)

### Node version (Node 版本)
v18.12.1

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/menu#TypeScript

### Reappearance steps (重现步骤)
only a new project,and use the code https://www.naiveui.com/zh-CN/os-theme/components/menu#TypeScript

### Expected results (期望的结果)
no error, on mac and win

### Actual results (实际的结果)

✘ [ERROR] Could not resolve "vue"

 /AppData/Local/pnpm/virtual/global/@vicons ionicons5@0.12.0/node_modules/@vicons/ionicons5/es/PulseSharp.js:1:143:
      1 │ ...s _createElementVNode, openBlock as _openBlock, createElementBlock as _createElementBlock, defineComponent } from 'vue'
        ╵                                                                                                                      ~~~~~

  You can mark the path "vue" as external to exclude it from the bundle, which will remove this
  error.

### Remarks (补充说明)
the same code only run on macos but error on windows
"dependencies": {
    "@vicons/ionicons5": "^0.12.0",
    "naive-ui": "^2.33.5",
    "vfonts": "^0.0.3",
    "vue": "^3.2.41",
    "vue-router": "^4.1.5"
  },

**Comment by liyunde** [comment]
pnpm create vue
and use ts
if remove @vicons/ionicons5 then all correct

**Comment by 07akioni** [comment]
Maybe you didn't install vue in your project.

**Comment by liyunde** [comment]
> Maybe you didn't install vue in your project.

on windows: when add any dependency of @vicons certain causing errors, remove it auto  recovered
both use node 16,18 case same result,package manage pnpm try 16,17 still like this

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
