### ISSUE TITLE
动态标签 Dynamic Tags的onCreate支持返回false和异步false

### ISSUE THREAD

**Issue by f754699** [tusen-ai/naive-ui#4048]
### This function solves the problem (这个功能解决的问题)
我向让动态标签（ Dynamic Tags）单纯提供创建功能，不提供保存数据的功能。毕竟提供的操作没有单纯标签（NTag）多。
### Expected API (期望的 API)
function handleInputConfirm(externalValue) {
            const nextValue = externalValue !== null && externalValue !== void 0 ? externalValue : inputValueRef.value;
            if (nextValue) {
                const tags = mergedValueRef.value.slice(0);
				// tags.push(props.onCreate(nextValue));
				const result = props.onCreate(nextValue)
				if(result){
					tags.push(result);
				}
                doChange(tags);
            }
            showInputRef.value = false;
            inputForceFocusedRef.value = true;
            inputValueRef.value = '';
        }

**Comment by f754699** [comment]
不用了，我想到方法了

<NDynamicTags value={[]} onCreate={handleCreateTag} />

**Comment by f754699** [comment]
`<NDynamicTags value={[]} onCreate={handleCreateTag} />`

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
