### ISSUE TITLE
Tabs component to support position attribute

### ISSUE THREAD

**Issue by ilgiznurgaliev** [tusen-ai/naive-ui#4049]
### This function solves the problem (这个功能解决的问题)
User will be able to chose position for `tabs` component. For example to position it to left like below:
![image](https://user-images.githubusercontent.com/10621366/202371787-f4c9746c-8312-44a9-99d4-7e8b64e732eb.png)

### Expected API (期望的 API)
`:position="top|bottom|left|right"`

**Comment by Sepush** [comment]
duplicate https://github.com/tusen-ai/naive-ui/issues/1466
