### ISSUE TITLE
目前自定义主题的方式如何让项目种自定义的css和naive中的全局配置项保持一致性？

### ISSUE THREAD

**Issue by terranc** [tusen-ai/naive-ui#4054]
### This function solves the problem (这个功能解决的问题)
目前自定义主题的方案，要如何能做到应用定义打css中和naive 组件中用到的一些全局变量保持一致呢？而不需要分别去维护两份配置。
比如：主题配置中的common.primaryColor的配置值，可能同时也需要用在项目中的其它css中
### Expected API (期望的 API)
翻了翻之前的issue是有人提出过方案，能在主题的配置值中引用css veriable #322

**Comment by Nakus0426** [comment]
主题配置里的common的配置值其实就是组件库的全局css变量，在项目中可以直接使用，这样就可以让自定义组件与组件库主题保持一致了。或者你可以直接基于组件库的css变量去拓展你自己的css变量，然后在自定义组件里使用也是可以的。

**Comment by terranc** [comment]
ok
