### ISSUE TITLE
Form label-align="left" require-mark-placement="left"样式错乱

### ISSUE THREAD

**Issue by pro-xiaoy** [tusen-ai/naive-ui#4056]
### TuSimple/naive-ui version (版本)
2.33.5

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
107.0.5304.110

### System and its version (系统及其版本)
MacOS

### Reappearance link (重现链接)
https://codesandbox.io/s/vigilant-nova-tpjpwh?file=/src/Demo.vue:490-494

### Reappearance steps (重现步骤)
Form label-align="left" require-mark-placement="left"样式错乱

### Expected results (期望的结果)
Form label-align="left" require-mark-placement="left"样式错乱

### Actual results (实际的结果)
Form label-align="left" require-mark-placement="left"样式错乱

### Remarks (补充说明)
Form label-align="left" require-mark-placement="left"样式错乱

**Comment by jizai1125** [comment]
#3871

**Comment by jizai1125** [comment]
Fixed #3871

**Comment by 07akioni** [comment]
It's fixed. I'll release a new version.
