### ISSUE TITLE
Summary in dataTable fails with little change in documentation example, it is not clear its behaviour

### ISSUE THREAD

**Issue by maxneo4** [tusen-ai/naive-ui#4061]
### TuSimple/naive-ui version (版本)
2.33.3

### Vue version (Vue 版本)
3.2.39

### Browser and its version (浏览器及其版本)
Microsoft Edge Version 107.0.1418.42 (Official build) (64-bit)

### System and its version (系统及其版本)
Windows 10 X64

### Reappearance link (重现链接)
https://codesandbox.io/s/keen-joliot-lxto00?file=/src/Demo.vue

### Reappearance steps (重现步骤)
* go to edit sandbox official naive-ui documentation for summary in dataTable https://codesandbox.io/s/9hzrwu
* change order of columns name and age, set first age column
* or change colSpan value from 3 to 2 createSummary method (Why doesn't work?)

### Expected results (期望的结果)
The summary will work without try to read value from null row

### Actual results (实际的结果)
Cell.js:39         
       Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at Proxy.render (Cell.js:39:33)

### Remarks (补充说明)
I try to set an array with DataTableCreateSummary, that compiles with Java Script but ignores all, less one of them when it works.

It's not clear info about `[columnKey: string]:` because summary is always to left, I suppose if you are asking by the key of one column, every summary item will be align with that column.

When I changed colspan and rowspan values any visual change is visible, only it works or it fails in one of described scenarios

**Comment by 07akioni** [comment]
<img width="558" alt="image" src="https://user-images.githubusercontent.com/18677354/203077066-c5be1394-506f-45eb-a81b-768e95a0d7a0.png">

**Comment by 07akioni** [comment]
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/18677354/203077221-aa8904ee-643c-4010-8fee-86708a84c84c.png">
