### ISSUE TITLE
期望对日期选择期类型添加以半年为单位的选择

### ISSUE THREAD

**Issue by hanjialin** [tusen-ai/naive-ui#4073]
### This function solves the problem (这个功能解决的问题)
这个功能弥补了以半年为单位选择时间的时候无法选择的问题。
### Expected API (期望的 API)
type=’halfyear‘

**Comment by hanjialin** [comment]
为啥不理人呢

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
