### ISSUE TITLE
TreeSelect 组件在多选模式下，开启可以清空的选项，选中几个节点后，点击右边的清空图标，checkedKeys会清空，但是indeterminateKeys不会被清空

### ISSUE THREAD

**Issue by ilxqx** [tusen-ai/naive-ui#4082]
### TuSimple/naive-ui version (版本)
2.34.2

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Chrome 107.0.5304.110

### System and its version (系统及其版本)
MacOS 12.6.1

### Node version (Node 版本)
16

### Reappearance link (重现链接)
https://codesandbox.io/s/silly-scott-0w6sfh?file=/src/Demo.vue

### Reappearance steps (重现步骤)
选中几个节点，然后点击右边的清空图标，查看打印的数据

### Expected results (期望的结果)
checkedKeys和indeterminateKeys 都应该清空

### Actual results (实际的结果)
只有checkedKeys被清空了

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
