### ISSUE TITLE
CodesandBox 的样例运行失败

### ISSUE THREAD

**Issue by ldjhust** [tusen-ai/naive-ui#4083]
### TuSimple/naive-ui version (版本)
2.34.2

### Vue version (Vue 版本)
3.2.41

### Browser and its version (浏览器及其版本)
Chrome(107.0.5304.107)

### System and its version (系统及其版本)
Windows10

### Reappearance link (重现链接)
https://codesandbox.io/s/eh04i5

### Reappearance steps (重现步骤)
打开官方文档上如上的Codesandbox连接，运行一会报越少依赖，add 依赖之后报: Cannot read properties of undefined (reading 'resolve')

### Expected results (期望的结果)
正常渲染出入官方文档中的菜单效果

### Actual results (实际的结果)
页面渲染报错:
TypeError
Cannot read properties of undefined (reading 'resolve')

ReactiveEffect.eval [as fn]
https://eh04i5.csb.app/node_modules/vue-router/dist/vue-router.esm-bundler.js:1380:54
    at ReactiveEffect.run (https://eh04i5.csb.app/node_modules/
vue/reactivity/dist/reactivity.esm-bundler.js:391:19
    at get value [as value] (https://eh04i5.csb.app/node_modules/
vue/reactivity/dist/reactivity.esm-bundler.js:1230:33
useLink
https://eh04i5.csb.app/node_modules/vue-router/dist/vue-router.esm-bundler.js:1404:22
setup
https://eh04i5.csb.app/node_modules/vue-router/dist/vue-router.esm-bundler.js:1445:42
    at callWithErrorHandling (https://eh04i5.csb.app/node_modules/
vue/runtime-core/dist/runtime-core.esm-bundler.js:999:18
    at setupStatefulComponent (https://eh04i5.csb.app/node_modules/
vue/runtime-core/dist/runtime-core.esm-bundler.js:6229:25
    at setupComponent (https://eh04i5.csb.app/node_modules/
vue/runtime-core/dist/runtime-core.esm-bundler.js:6192:36
    at mountComponent (https://eh04i5.csb.app/node_modules/
vue/runtime-core/dist/runtime-core.esm-bundler.js:5014:7
    at processComponent (https://eh04i5.csb.app/node_modules/
vue/runtime-core/dist/runtime-core.esm-bundler.js:4992:9
    at patch (https://eh04i5.csb.app/node_modules/
vue/runtime-core/dist/runtime-core.esm-bundler.js:4707:11
    at mountChildren (https://eh04i5.csb.app/node_modules/
vue/runtime-core/dist/runtime-core.esm-bundler.js:4856:7
    at mountElement (https://eh04i5.csb.app/node_modules/
...

**Comment by jizai1125** [comment]
因为没有在 `main.js` 中注册路由

**Comment by ldjhust** [comment]
> 

可以麻烦修复一下吗？初次尝试使用 vue 和 naive ui 想参考一下

**Comment by jizai1125** [comment]
https://codesandbox.io/s/reverent-kepler-w5l4hq?file=/src/main.js

**Comment by ldjhust** [comment]
> https://codesandbox.io/s/reverent-kepler-w5l4hq?file=/src/main.js

感谢

**Comment by jizai1125** [comment]
> > https://codesandbox.io/s/reverent-kepler-w5l4hq?file=/src/main.js
> 
> 感谢

可以看下 [vue-router](https://router.vuejs.org/zh/) 文档
