### ISSUE TITLE
Rate support decimal (Rate组件支持小数)

### ISSUE THREAD

**Issue by de1ck** [tusen-ai/naive-ui#4084]
### This function solves the problem (这个功能解决的问题)
Rate support decimal (Rate组件支持小数)
### Expected API (期望的 API)
value 位小数的时候，自动分割小数的占比，类似:
https://element-plus.org/en-US/component/rate.html#read-only

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
