### ISSUE TITLE
Auto Complete 選取後，能否取得該項目的 AutoCompleteOption.value 

### ISSUE THREAD

**Issue by Lonka** [tusen-ai/naive-ui#4089]
### This function solves the problem (这个功能解决的问题)
options = [{"name":"aa","value":"1"},{"name":"bb","value":"2"},]

透過 v-model:value="value" 綁定選取值，而選到 aa 時，value 值會得到 AutoCompleteOption.name，該如何取得 AutoCompleteOption.value 的數值呢？
即選到 aa 時，該如何取得 1 呢？

### Expected API (期望的 API)
v-model:value="value" 可以得到 AutoCompleteOption 物件，或 AutoCompleteOption.value, AutoCompleteGroupOption.key，都沒有時再回選取值的 text

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
