### ISSUE TITLE
表格下拉选择组件

### ISSUE THREAD

**Issue by ilxqx** [tusen-ai/naive-ui#4090]
### This function solves the problem (这个功能解决的问题)
有时候下拉选择的时候需要展示很多列的信息，包括分页支持等等，这个表格就非常适用了。
### Expected API (期望的 API)
就是往下拉框中嵌套一个表格，可以单选多选，虽然目前可以通过select组件的empty插槽变相解决，但是总觉得不完美，希望官方可以出一个，完美强迫症，非常感谢大佬。

**Comment by yangliadmin** [comment]
类似：https://opentiny.design/tiny-vue/zh-CN/os-theme/components/pop-editor
