### ISSUE TITLE
unable to set multiple keydown handlers on NInput

### ISSUE THREAD

**Issue by michael-dm** [tusen-ai/naive-ui#4091]
### TuSimple/naive-ui version (版本)
2.34.2

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Chromium Engine Version 107.0.5304.110

### System and its version (系统及其版本)
MacOS(12.5.1)

### Reappearance link (重现链接)
https://codesandbox.io/s/multiple-keydown-bug-bcsgi5?file=/src/App.vue

### Reappearance steps (重现步骤)
Try to input anything in input.

### Expected results (期望的结果)
We should be able to add multiple event handlers, as in a normal input in Vue.

### Actual results (实际的结果)
It crashes. Vue warns us before with :
`Invalid prop: type check failed for prop "onKeydown". Expected Function, got Array`

**Comment by Sepush** [comment]
the type is `onKeydown: Function as PropType<(e: KeyboardEvent) => void>`
we have no plan to support the this useage 
```html 
<NInput @keydown.left.prevent @keydown.tab.stop /> 
```
you can do with a switch statement then assert the event type and handle it inside onKeydown fuction.
