### ISSUE TITLE
对话框 Dialog组件显示文本不解析\n\t等转义符

### ISSUE THREAD

**Issue by xuegao-tzx** [tusen-ai/naive-ui#4092]
### TuSimple/naive-ui version (版本)
2.34.2

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Nightly(109.0a1)

### System and its version (系统及其版本)
Windows11

### Node version (Node 版本)
18.12.1

### Reappearance steps (重现步骤)
dialog.success中设置content: "为: " res.data " \n 点击'确定'关闭",
这里”点击'确定'关闭“不会在下一行显示，但是也不会显示转义符\n

### Expected results (期望的结果)
dialog.success中设置content: "为: " res.data " \n 点击'确定'关闭",
这里”点击'确定'关闭“可以在下一行显示，但是也不会显示转义符\n

### Actual results (实际的结果)
这里”点击'确定'关闭“不会在下一行显示，但是也不会显示转义符\n

**Comment by Sepush** [comment]
This has nothing to do with naive but html
you should pass a render function to content
![image](https://user-images.githubusercontent.com/39197136/208232411-6b5b7258-0977-4e2d-995f-8347b39d9cda.png)
