### ISSUE TITLE
表格的 滚动条 想永远显示, 能不能给出api? 

### ISSUE THREAD

**Issue by gowy222** [tusen-ai/naive-ui#4093]
### This function solves the problem (这个功能解决的问题)
借鉴 trigger="none" 会让滚动条一直显示, table这边没办法设置目前..
### Expected API (期望的 API)
滚动条 Scrollbar  trigger="none" 会让滚动条一直显示, table 这边 同样给出此接口

**Comment by gowy222** [comment]
没有滚动条 总是 容易产生视觉错误...这一页就这么多条目。。。

**Comment by gowy222** [comment]
尤其是 一个页面里面 几个表格 联动父子孙 数据的时候.. 没有滚动条 明确 示意 "该表格下面还有数据...请滚动", 总不能每个表格都让用户去 鼠标hover 吧... 不够直观

**Comment by gowy222** [comment]
![image](https://user-images.githubusercontent.com/52201479/204170986-d351ae24-e090-4b80-ba92-67783215583c.png)
比如图片这种情况...正好对其基线 完全看不出来 下面还有几行数据..

**Comment by jahnli** [comment]
```
      :scrollbar-props="{ trigger: 'none' }"
```
是否可以满足

**Comment by gowy222** [comment]
@jahnli  好的，感谢大佬

**Comment by gowy222** [comment]
@jahnli   是 数据表格 Data Table，   不是那个普通table....

**Comment by jahnli** [comment]
@gowy222    
![image](https://user-images.githubusercontent.com/20943608/204985869-a8b29fb4-2e00-477a-b557-0cef247b2331.png)

**Comment by gowy222** [comment]
搞定
