### ISSUE TITLE
多个nTree拖放节点

### ISSUE THREAD

**Issue by duyuntao** [tusen-ai/naive-ui#4094]
### This function solves the problem (这个功能解决的问题)
我希望在多个n-tree之间通过拖拽的方式交换数据。
### Expected API (期望的 API)
提议新增n-tree-group 组件，子组件为n-tree(类似n-checkbox-group的感觉)。
子组件的拖放事件冒泡到父组件，on-dragend节点完成拖拽动作后的回调函数	
on-dragenter	节点拖拽中的回调函数	
on-dragleave	拖拽一个节点，该节点离开其它节点后的回调函数	
on-dragstart	开始拖拽某一个节点的回调函数	
on-drop 节点完成拖拽动作后的回调函数

回调中参数提供当前tree和目标tree

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
