### ISSUE TITLE
建议Cascader组件派生一个展示组件

### ISSUE THREAD

**Issue by duyuntao** [tusen-ai/naive-ui#4095]
### This function solves the problem (这个功能解决的问题)
首先，感谢naiveUI为开源的贡献
我的需求是模仿mac访达的展示效果，在组件库中Cascader选项的展示最为接近，所以建议从Cascader组件中将选项展示分离出一个展示组件。建议添加拖放事件，事件参考tree
### Expected API (期望的 API)
保留原api的同时添加拖放事件API ，参考tree

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
