### ISSUE TITLE
Notification组件没有avatar的时候内容区的8像素左边距是不是应该去掉

### ISSUE THREAD

**Issue by liuyang0826** [tusen-ai/naive-ui#4097]
### TuSimple/naive-ui version (版本)
2.34.2

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
windows

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/notification

### Reappearance steps (重现步骤)
通过create创建一个notification，不设置avatar。

### Expected results (期望的结果)
去掉左边多出的8像素左边距

### Actual results (实际的结果)
左边多出的8像素

**Comment by 07akioni** [comment]
为了视觉协调故意加的
