### ISSUE TITLE
in nuxt3 use NuxtLayout cannot pass props theme config when first load page.首次渲染主题无法正确传递

### ISSUE THREAD

**Issue by hdw0504** [tusen-ai/naive-ui#4100]
### TuSimple/naive-ui version (版本)
2.34.2

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
chrmoe

### System and its version (系统及其版本)
windows

### Node version (Node 版本)
16.15.0

### Reappearance link (重现链接)
https://github.com/hdw0504/naive-ui-nuxt3

### Reappearance steps (重现步骤)
npx degit https://github.com/hdw0504/naive-ui-nuxt3 nuxt3-bug
cd nuxt3-bug
pnpm i
npm run dev
https://github.com/hdw0504/naive-ui-nuxt3/blob/master/assets/firstLoad.png?raw=true
### Expected results (期望的结果)
主题样式正常传递

### Actual results (实际的结果)
NuxtLayout无法传递配置

### Remarks (补充说明)
nuxt3 中使用 NuxtLayout 组件时，首次加载页面主题并未正常传递下去，使用 `@nuxtjs/color-mode` 切换主题后再切回来没问题
目前不知道是naive UI这边还是nuxt3的问题

nuxt有issue提到 Cannot pass props to NuxtLayout？
issue地址：https://github.com/nuxt/nuxt.js/issues/15578

**Comment by yapengsoft** [comment]
@hdw0504 
const theme = computed(() => {
  return color.value === 'system' ? (color.value ? lightTheme : darkTheme) : color.value === 'light' ? lightTheme : darkTheme;
});

**Comment by yapengsoft** [comment]
![image](https://user-images.githubusercontent.com/75244754/210396053-7e9d1612-f7dd-4f18-a8d6-4b85027cfba4.png)
在app.vue 实际上你可能需要这么写

**Comment by sixdjango** [comment]
> ![image](https://user-images.githubusercontent.com/75244754/210396053-7e9d1612-f7dd-4f18-a8d6-4b85027cfba4.png) 在app.vue 实际上你可能需要这么写

你这么写就 全部 客户端渲染了

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
