### ISSUE TITLE
Autocomplete value not changed properly while typing using GBoard keyboard

### ISSUE THREAD

**Issue by erez213** [tusen-ai/naive-ui#4105]
### TuSimple/naive-ui version (版本)
2.34.2

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Chrome

### System and its version (系统及其版本)
Android

### Reappearance link (重现链接)
https://www.naiveui.com/en-US/light/components/input

### Reappearance steps (重现步骤)
Install GBoard keyboard on Android device, then start typing in the autocomplete input.
You will see that the v-model:value will not be triggered until you finish a whole word and press space.
Watch this video please: https://vimeo.com/776126572

### Expected results (期望的结果)
The expected behavior is to trigger value change after each key type, not after whole word.

### Actual results (实际的结果)
The value change event is triggered only after whole word.

### Remarks (补充说明)
Thanks

**Comment by 07akioni** [comment]
We should add an `ignoreComposition` prop on input component.

**Comment by erez213** [comment]
Hello, any plans to fix this?

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
