### ISSUE TITLE
Data Table组件使用render渲染NText组件后tooltip主题错误

### ISSUE THREAD

**Issue by Wlisfes** [tusen-ai/naive-ui#4111]
### TuSimple/naive-ui version (版本)
2.34.2

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
107.0.5304.107

### System and its version (系统及其版本)
Windows 10

### Reappearance link (重现链接)
https://codesandbox.io/s/reverent-shadow-wfrrgh?file=/src/App.vue:302-309

#### Data Table组件使用render渲染每个格子，采用h返回span后tooltip主题是正常的，使用h返回NText组件后tooltip变成了暗黑主题
![image](https://user-images.githubusercontent.com/32263302/204731708-c598eb66-85ab-47b6-ba0d-e11efc04e833.png)
![image](https://user-images.githubusercontent.com/32263302/204731779-038c3450-489b-43f9-8fe3-dcbbfebe13eb.png)

### Actual results (实际的结果)
未知

**Comment by 07akioni** [comment]
text 组件并不检测自己是不是在黑色背景的组件中，这个表现是符合预期的，使用普通的文本就行

**Comment by TyouKyou** [comment]
到底有没有ntext组件，为啥官方文档里没有这个，但是我的项目里能用ntext（项目用的navieUI）

**Comment by jahnli** [comment]
https://www.naiveui.com/zh-CN/os-theme/components/typography#Text-Props
仔细看文档

**Comment by TyouKyou** [comment]
不愧是你，兄弟2016年发大财！

**Comment by jahnli** [comment]
你也一样 👍
