### ISSUE TITLE
n-pagination 页码部分可以自定义样式

### ISSUE THREAD

**Issue by CoolJun777** [tusen-ai/naive-ui#4115]
### This function solves the problem (这个功能解决的问题)
希望分页页码的样式更加多样化，以便解决各式各样的分页样式
### Expected API (期望的 API)
希望分页页码的样式更加多样化，以便解决各式各样的分页样式

**Comment by Sepush** [comment]
https://www.naiveui.com/en-US/os-theme/components/pagination use prop `label` or slot `label`

**Comment by Upose** [comment]
then how to get the item's currentpage?i can't get the parameter each item

**Comment by Upose** [comment]
> https://www.naiveui.com/en-US/os-theme/components/pagination use prop `label` or slot `label`

then how to get the item's currentpage?i can't get the parameter each item

**Comment by Upose** [comment]
> https://www.naiveui.com/en-US/os-theme/components/pagination use prop `label` or slot `label`

ok，i know it
