### ISSUE TITLE
可编辑表格在分页的情况下只对第一页的内容有效

### ISSUE THREAD

**Issue by YaKazama** [tusen-ai/naive-ui#4118]
### TuSimple/naive-ui version (版本)
2.34.2

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Chrome(107.0.5304.110)

### System and its version (系统及其版本)
Kali GNU/Linux(2022.4)

### Reappearance link (重现链接)
https://codesandbox.io/s/elegant-wilbur-pt5jdm

### Reappearance steps (重现步骤)
1. 复制 https://www.naiveui.com/zh-CN/os-theme/components/data-table#switchable-editable 或 https://www.naiveui.com/zh-CN/os-theme/components/data-table#simple-editable.vue 下的示例代码；
2. 将 pagination.pageSize 改为 2 ，用于分页测试；
3. 点击到第 2 页，并修改 任意值。

### Expected results (期望的结果)
能正确修改对应的数据值

### Actual results (实际的结果)
第 2 页的第一行数据的修改会修改第 1 页中第一行的数据

**Comment by CoolJun777** [comment]
你可以打印一下onUpdateValue方法中的index，每个分页中的index都是重新计算的

**Comment by YaKazama** [comment]
onUpdateValue 方法中的 index，翻页后都是从 0 开始的。

这个方法计算出来新的 index，看起来是能正常获取到值的。

```ts
// 分页大小 * ( 当前页码 - 1 ) + index
let currentIndex = computed(() => pagination.value.pageSize * (pagination.value.page - 1) + index )  
data.value[currentIndex.value].name = v
```

**Comment by YaKazama** [comment]
数据表格中，在使用固定列时，如果 scroll-x 的值大于所有非固定列的宽度总和（使用 maxWidth 或 width 时），则会出现固定列宽度失效的问题。

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
