### ISSUE TITLE
In the Form document, in the inline Form section, the left border is missing when the middle button loses its hover  

### ISSUE THREAD

**Issue by jahnli** [tusen-ai/naive-ui#412]
### TuSimple/naive-ui version (版本)
2.15.3

### Vue version (Vue 版本)
3.1.4

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://codesandbox.io/s/83xrg

### Reappearance steps (重现步骤)
Document the demo  

### Expected results (期望的结果)
fix

### Actual results (实际的结果)
In the Form document, in the inline Form section, the left border is missing when the middle button loses its hover

**Comment by jahnli** [comment]
![image](https://user-images.githubusercontent.com/20943608/124536753-1ddf0280-de4b-11eb-9d13-3abf2aca1655.png)

**Comment by Fnzero** [comment]
I cannot reproduce on windows. You can see if the style has some error by F12.

**Comment by nooooooom** [comment]
或许是浏览器缩放导致的？这个图片实例上的标题不太像是正常的粗体，如果是的话或许应该调整一下分隔线的显示方式

**Comment by 07akioni** [comment]
> 或许是浏览器缩放导致的？这个图片实例上的标题不太像是正常的粗体，如果是的话或许应该调整一下分隔线的显示方式

具体还真说不清楚。

当时做分割线单独显示是我对与不同按钮交界处样式优先级的追求比较极致，就要做出理想中的效果。
