### ISSUE TITLE
upload是否可以增加成功的回调？解析后台的返回？

### ISSUE THREAD

**Issue by MarkZhuo** [tusen-ai/naive-ui#4124]
### This function solves the problem (这个功能解决的问题)
现在on-finish返回的file和url无法解析后台的返回
### Expected API (期望的 API)
on-success

**Comment by pylist** [comment]
同样希望增加这个功能, 我都没办法解析response

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
