### ISSUE TITLE
数据表格，如何实现点击行变色-高亮行?  row-class-name 居然不是computed?

### ISSUE THREAD

**Issue by gowy222** [tusen-ai/naive-ui#4127]
### This function solves the problem (这个功能解决的问题)
实现点击行变色-高亮行，尤其是展开行的时候 高亮 这一行/这一整块的 背景,  感觉这是基本功能之一吧....
### Expected API (期望的 API)
row-class-name 对应的是methods 而不是 computed... 完全没办法动态实现row的class.. 而且 methods 很消耗资源不是么?

**Comment by gowy222** [comment]
而且 row_props 为了区分 ondblclick 和 onClick 做了 debounce, 之后 即使 row-class-name  走methods 依然行不通行变色, 会先触发row-class-name 再触发 onClick 设置当前点击的行key

**Comment by Canees** [comment]
直接row-class-name 返回你当前高亮的class

**Comment by gowy222** [comment]
@Canees 没明白, 动态响应row-class-name，个人理解逻辑:  onClick  - > debounce -> 记录 row.id/uuid 到变量id，然后 row-class-name 走 computed => if row.id === this.变量id => return 'bgc-blue'  否则 return ''.
 
因为 onClick  得先走 debounce, 而 row-class-name 对应methods 不可以 绑定debounce ，会在click事件直接触发，还没有记录当前clicked row.id/uuid... 固而 无法实现..

**Comment by imxuedi** [comment]
let me tell you, in the demo code, you must set the style of 'td' instead of 'tr', so you shoud change your code like this:

```css
:deep(.too-old td) {
  background: red;
}
```

**Comment by NirvanaCh7** [comment]
\<td\> elements come with a default white background. You may need to override or remove it.

To those who come after:

```
<template>
  <n-data-table :columns="columns" :data="data" :row-props="rowProps" />
</template>

……

const selectedKey = ref<number | null>(null);

const rowProps = (row: RowData) => {
  return {
    class: selectedKey.value === row.key ? 'selected-row' : '',
    style: {
      cursor: 'pointer',
    },
    onClick: () => {
      selectedKey.value = row.key;
    },
  };
};
</script>

<style scoped>
:deep(.selected-row) {
  background: linear-gradient(90deg, #ff5858 0%, #f09819 100%) ;
}
:deep(.selected-row td) {
  background: none;
}
</style>
```

**Comment by wcldyx** [comment]
到25年了还没这么基础的功能吗
