### ISSUE TITLE
tree树形组件children为空数组时仍可对树进行展开折叠

### ISSUE THREAD

**Issue by maddenBoy** [tusen-ai/naive-ui#4128]
### TuSimple/naive-ui version (版本)
2.34.2

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Chrome(108.0.5359.71)

### System and its version (系统及其版本)
window11

### Reappearance link (重现链接)
https://codesandbox.io/s/xwo7pz?file=/src/Demo.vue

### Reappearance steps (重现步骤)
把树形组件data的children字段设置为空数组，仍可对树进行展开折叠

### Expected results (期望的结果)
期望树形组件data的children字段设置为空数组时和设置为null时的表现效果一致

### Actual results (实际的结果)
把树形组件data的children字段设置为空数组，仍可对树进行展开折叠

### Remarks (补充说明)
![image](https://user-images.githubusercontent.com/71129660/205253823-2ea50509-8405-4e6d-aed0-f8035acb954e.png)

**Comment by amadeus711** [comment]
https://github.com/tusen-ai/naive-ui/issues/3783

**Comment by laterdays** [comment]
大多数场景下，的确是靠children是否有数据来判断，是否有子级
