### ISSUE TITLE
希望可以优化 Tab 中分段类型的实现或者提供一个单独的分段控制器组件

### ISSUE THREAD

**Issue by AiHMin** [tusen-ai/naive-ui#4129]
### This function solves the problem (这个功能解决的问题)
提供一种不同于按钮组展示方式的选择组件，用于展示多个选项并允许用户选择其中单个选项；
选项可以有关联区域，当切换选中选项时，关联区域的内容会发生变化。
当前 Tabs 组件中的分段类型并不完善：
- 只能以块级形式撑满整个容器，不能作为行内元素显示，如放进表单中等
- 禁用某项时样式反馈不明确
- 切换时没有动画 _/狗头_

### Expected API (期望的 API)
可以参考 Ant Design 中 Segmented 组件的实现 [Segmented](https://ant.design/components/segmented-cn)

**Comment by xsjcTony** [comment]
+1

**Comment by Sepush** [comment]
https://github.com/tusen-ai/naive-ui/pull/5063
