### ISSUE TITLE
Data Table 开启分页  快速跳跃 => 如何实现修改goto文本?

### ISSUE THREAD

**Issue by gowy222** [tusen-ai/naive-ui#4133]
### This function solves the problem (这个功能解决的问题)
<n-data-table
:pagination="pagination"   

-------------------------------------------------------------
pagination: ref({
      page: 1,
      pageSize: 10,
      itemCount: 2000,
      showQuickJumper: true,//Data Table 配置这边开启功能
-------------------------------------------------------------
但是: goto 是个Slot,而在Data Table这边只能操作Prop...
所以, 能不能干脆给出pagination 插槽???

### Expected API (期望的 API)
干脆给出pagination 插槽?

**Comment by wwzill0928** [comment]
想问一下，我想在n-data-table组件中给pagination加前缀怎么解决。加共几条
