### ISSUE TITLE
穿梭框分页功能

### ISSUE THREAD

**Issue by lileiemq** [tusen-ai/naive-ui#4137]
### This function solves the problem (这个功能解决的问题)
穿梭框可不可以加一个分页功能，很多时候感觉都需要分页
### Expected API (期望的 API)
穿梭框列表添加分页功能

**Comment by Nakus0426** [comment]
...可以自定义穿梭框里的内容，具体可以看文档

**Comment by JeromeD3** [comment]
so, 有详细案例吗
