### ISSUE TITLE
数据表格Data Table使用带提示的省略文本内容过长时，提示内容会超出屏幕

### ISSUE THREAD

**Issue by maddenBoy** [tusen-ai/naive-ui#4146]
### TuSimple/naive-ui version (版本)
2.34.2

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Chrome（108.0.5359.95）

### System and its version (系统及其版本)
window11

### Reappearance link (重现链接)
https://codesandbox.io/s/7sfo5s?file=/src/Demo.vue

### Reappearance steps (重现步骤)
1、使用Data Table中带提示的省略的例子
2、把省略的文本加长，文本长度到可换行长度时提示会溢出屏幕

### Expected results (期望的结果)
期望Data Table中带提示的省略文本长度到可换行长度时提示不溢出屏幕

### Actual results (实际的结果)
Data Table中带提示的省略文本长度到可换行长度时提示溢出屏幕

### Remarks (补充说明)
![image](https://user-images.githubusercontent.com/71129660/205891382-43082e72-4bb9-45eb-a45c-ce040a2fa94e.png)

**Comment by Canees** [comment]
仔细看文档，它可以设置宽度！

**Comment by maddenBoy** [comment]
设置宽度可以解决，我以为这是可以自适应的

**Comment by Canees** [comment]
> 设置宽度可以解决，我以为这是可以自适应的

并不是，你可以关了这个is
