### ISSUE TITLE
n-upload 更改default-file-list，数据变更视图没有更新

### ISSUE THREAD

**Issue by laterdays** [tusen-ai/naive-ui#4151]
### TuSimple/naive-ui version (版本)
2.34.2

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
windows

### Reappearance link (重现链接)
https://codesandbox.io/s/elated-lovelace-6r3qwu?file=/src/Demo.vue

### Reappearance steps (重现步骤)
n-upload 更改default-file-list，数据变更视图没有更新

### Expected results (期望的结果)
目前的场景是，默认有一张图，然后上传后覆盖当前默认列表的图，所以需要修改default-file-list，在2.33.2中，它是可以的

### Actual results (实际的结果)
n-upload 更改default-file-list，数据变更视图没有更新

**Comment by 07akioni** [comment]
`default-file-list` 不应该是响应式的，需要响应应该使用 `v-model:file-list`

**Comment by laterdays** [comment]
@07akioni   我描述有错误， 它不是`default-file-list `,我使用的就是`v-model:file-list`

**Comment by laterdays** [comment]
@07akioni  https://codesandbox.io/s/youthful-bell-3xwug5?file=/src/Demo.vue，这个使用的是 `v-model:file-list`  ，它也是有问题的 ，如果default-file-list像v-once一样，只响应一次，是否在文档中描述下
