### ISSUE TITLE
Formatted n-input-number adds css text-decoration: line-through

### ISSUE THREAD

**Issue by mnantel** [tusen-ai/naive-ui#4153]
### TuSimple/naive-ui version (版本)
2.34.2

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Firefox latest, Safari latest

### System and its version (系统及其版本)
MacOS latest

### Reappearance link (重现链接)
https://codesandbox.io/s/agitated-fast-0j3g0e?file=/src/App.vue

### Reappearance steps (重现步骤)
Adding this control:

      <n-input-number v-model:value="item.settings.bandwidth" size="tiny" :format="formatMbps"/>

Which calls this function:

      const formatMbps = (value) => `${value}Mbps`

Yields this CSS attribute in the DOM:

element {
    text-decoration: line-through;
}

<input type="text" class="n-input__input-el" style="text-decoration: line-through;" placeholder="Please Input" size="20">

Which means the validator is determining the value is wrong. That may happen if the validator runs after formatting, in which case this is the issue.

Adding a custom validator that returns true does not remove the problem.

### Expected results (期望的结果)
Text-decoration should not be added as a result of formatting.

### Actual results (实际的结果)
Text-decoration is added as a result of formatting.

**Comment by equt** [comment]
Like [it's mentioned in the custom parsing section](https://www.naiveui.com/en-US/os-theme/components/input-number#parse.vue), you should also [provide a `parse` along with the `format`](https://codesandbox.io/s/jovial-tamas-pbb23c?file=/src/App.vue).

**Comment by mnantel** [comment]
Thanks! Lets close this, however it may be worthwhile to add a note in the site documentation that validation will fail if a parse is not provided with the format...

**Comment by equt** [comment]
make sense, and i guess the reason why it's not mentioned is that the custom `parse` & `format` is introduced later.
