### ISSUE TITLE
Collpase: Provide ability to disable expand/collapse

### ISSUE THREAD

**Issue by wushanchao** [tusen-ai/naive-ui#4175]
### TuSimple/naive-ui version (版本)
2.34.2

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
chrome107

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/collapse

### Reappearance steps (重现步骤)
当前没有折叠面板没有API去控制能否折叠，只是有个禁用属性。

### Expected results (期望的结果)
希望能提供API能去实时控制面板折叠，而不是一次性禁用。

### Actual results (实际的结果)
不能满足点击折叠标题扩展内容时不折叠的场景

**Comment by OrbisK** [comment]
this should be a feature request!

**Comment by 07akioni** [comment]
You can use controlled manner to disabled some specific expanding or collapsing action.
