### ISSUE TITLE
NImage 展开放大缩小报错

### ISSUE THREAD

**Issue by pro-xiaoy** [tusen-ai/naive-ui#4178]
### TuSimple/naive-ui version (版本)
2.34.2

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Version 107.0.5304.121 (Official Build) (x86_64)

### System and its version (系统及其版本)
MacOS

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/image

### Reappearance steps (重现步骤)
第一个demo: 基础用法 ，图片preview后，除了close操作其他的操作全部失效

### Expected results (期望的结果)
正常操作

### Actual results (实际的结果)
第一个demo: 基础用法 ，图片preview后，除了close操作其他的操作全部失效， 本地引用后也是没办法使用

**Comment by jizai1125** [comment]
在下个版本发布前可以先设置属性  `:previewedImgProps="{}"` 来避免抛错

**Comment by Sepush** [comment]
ref https://github.com/tusen-ai/naive-ui/pull/4154
