### ISSUE TITLE
n-select在from [inline]下无默认撑开宽度

### ISSUE THREAD

**Issue by kuyaaaa** [tusen-ai/naive-ui#4180]
### TuSimple/naive-ui version (版本)
2.34.2

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Chrome

### System and its version (系统及其版本)
Win

### Reappearance link (重现链接)
https://codesandbox.io/s/select-if6pnq?file=/src/Demo.vue

### Reappearance steps (重现步骤)
https://codesandbox.io/s/select-if6pnq?file=/src/Demo.vue

### Expected results (期望的结果)
form组件下使用inline模式，select组件会被挤压，希望能有跟input一样默认撑开宽度

### Actual results (实际的结果)
n-select在from [inline]下无默认撑开宽度
![image](https://user-images.githubusercontent.com/54495986/206989117-97236713-a6b1-4e89-ae92-9943f8311c60.png)

**Comment by kuyaaaa** [comment]
目前发现的问题可能是因为该样式下的width不为100%的问题
![image](https://user-images.githubusercontent.com/54495986/206991409-f812c48b-a4df-4883-9737-a75bf19ba9f0.png)

**Comment by Yhspehy** [comment]
input有个默认的size属性，而且根据浏览器不同，这个size也不同，而size就是input的宽度，所以能撑开。
select是用div实现的，默认会撑满父节点的宽度，自然不会自动撑开。
你直接给你的select加个width的style就可以了。

**Comment by 07akioni** [comment]
这个是符合预期的，出于实现层面的限制我没办法让这个东西有个预设宽度
