### ISSUE TITLE
Cascader 输入框中显示的值没变，实际值是变化的了

### ISSUE THREAD

**Issue by lileiemq** [tusen-ai/naive-ui#4184]
### TuSimple/naive-ui version (版本)
2.34.2

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
chrome(108.0.5359.98)

### System and its version (系统及其版本)
MacOS(13.0)

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/cascader#API

### Reappearance steps (重现步骤)
单项选择异步， Child Check Strategy为true，Show Path为true，改变选择的值显示没变

![1](https://user-images.githubusercontent.com/89761177/207018307-b4e45b4b-932e-48e5-8eb9-c80bb296fc85.gif)

### Expected results (期望的结果)
显示的值变化

### Actual results (实际的结果)
显示的值没变

**Comment by 07akioni** [comment]
我试了一下，没能复现
