### ISSUE TITLE
data-table 似乎性能有点问题

### ISSUE THREAD

**Issue by nmtx-2022** [tusen-ai/naive-ui#4187]
### TuSimple/naive-ui version (版本)
2.34.2

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Chrome(107.0.5304.110)

### System and its version (系统及其版本)
MacOS

### Reappearance link (重现链接)
https://github.com/nmtx-2022/naive-test/tree/main

### Reappearance steps (重现步骤)
显示表格的时候能明显感觉到卡顿,

### Expected results (期望的结果)
没那么卡顿

### Actual results (实际的结果)
卡顿

### Remarks (补充说明)
在 vue 开发者工具下更明显

<img width="1330" alt="image" src="https://user-images.githubusercontent.com/109792150/207218643-b805bf8a-7cae-418e-92df-2827613fa893.png">

**Comment by zhoufanglu** [comment]
加上这个    virtual-scroll 属性试试 虚拟滚动

**Comment by Nakus0426** [comment]
vue devtool这玩意会让你的页面变得很卡，不管是naive、antdv还是element plus，真实性能得关掉它才能体现

**Comment by Nakus0426** [comment]
vue devtool这玩意会让你的页面变得很卡，不管是naive、antdv还是element plus，真实性能得关掉它才能体现

**Comment by nmtx-2022** [comment]
似乎是最新的 vue 和 vue devtool 兼容问题
