### ISSUE TITLE
n-form 与 n-input-number存在冲突

### ISSUE THREAD

**Issue by cjh-store** [tusen-ai/naive-ui#4189]
### TuSimple/naive-ui version (版本)
2.34.2

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Chromium 102.0.5005.167

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://codesandbox.io/s/gracious-artem-h9rw0b?file=/src/Demo.vue

### Reappearance steps (重现步骤)
  <n-form
    ref="formRef"
    inline
    :label-width="80"
    :model="formValue"
    :rules="rules"
    :size="size"
  >
    <n-form-item label="电话号码" path="phone">
      <n-input-number v-model:value="formValue.phone" clearable />
    </n-form-item>
    <n-form-item>
      <n-button attr-type="button" @click="handleValidateClick">
        验证
      </n-button>
    </n-form-item>
  </n-form>

 formValue: ref({
        phone: "",
      }),
      rules: {
        phone: {
          required: true,
          trigger: ["input"],
        },
      },

### Expected results (期望的结果)
有值通过验证

### Actual results (实际的结果)
提示不为字符串

**Comment by jahnli** [comment]
添加 type:'number',
