### ISSUE TITLE
TS2742: The inferred type of 'default' cannot be named without a reference 

### ISSUE THREAD

**Issue by zz541843** [tusen-ai/naive-ui#4194]
### Vue version (Vue 版本)
3.2.45

请教个问题，自定义的库里模仿了你们的写法，定义了组件的props
![image](https://user-images.githubusercontent.com/72638366/207516821-2371f978-be0f-4229-a9a5-085b06b8571e.png)
我是为了引入进来使用这个对象或者ExtractPropTypes后的类型，但我只要类型里有PropType这个泛型就会报错
![image](https://user-images.githubusercontent.com/72638366/207516989-322d6325-6d3d-49a8-abb7-b7432131d4ac.png)
引入你们的比如cardProps却不会报错
![image](https://user-images.githubusercontent.com/72638366/207517093-f6a1ea5d-c269-4492-bd71-3bd081c3209e.png)

**Comment by Sepush** [comment]
`xxxStyle: [String, Object] as PropType<string | CSSProperties>`
