### ISSUE TITLE
date 日期框 onUpdateFormattedValue 监听返回值不变

### ISSUE THREAD

**Issue by wei1034937343** [tusen-ai/naive-ui#4197]
### TuSimple/naive-ui version (版本)
2.34.2

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Edge

### System and its version (系统及其版本)
Window11

### Reappearance link (重现链接)
https://codesandbox.io/s/new-dream-gifqyd?file=/src/Demo.vue

### Reappearance steps (重现步骤)
选择日期，onUpdateFormattedValue 传入的格式化日期参数，始终不变

### Expected results (期望的结果)
选择日期，onUpdateFormattedValue 传入的格式化日期参数，应该为选择的日期

### Actual results (实际的结果)
选择日期，onUpdateFormattedValue 传入的格式化日期参数，始终不变

**Comment by wei1034937343** [comment]
![image](https://user-images.githubusercontent.com/28970254/207571562-a5eb22bf-4c86-4c81-8e5c-ac7ee863b797.png)

**Comment by thibodeauxjl** [comment]
<template>
  <pre>{{ formattedValue }}</pre>
  <pre>{{ timestampValue }}</pre>
  <n-date-picker
    value-format="yyyy-MM-dd"
    v-model:formattedValue="formattedValue"
    type="date"
    :on-update:formatted-value="onUpdateFormattedValue"
  />
</template>

<script lang="ts">
import { defineComponent, ref } from "vue";

export default defineComponent({
  setup() {
    return {
      formattedValue: ref("2007-06-30"),
      timestampValue: ref(0),
    };
  },
  methods: {
    onUpdateFormattedValue: function (value, timestampValue) {
      this.formattedValue = value;
      this.timestampValue = timestampValue;
    },
  },
});
</script>

**Comment by wei1034937343** [comment]
Thanks, the problem has been solved
