### ISSUE TITLE
upload 上传图片组件，fileList url无后缀时，图片不回显

### ISSUE THREAD

**Issue by wei1034937343** [tusen-ai/naive-ui#4198]
### TuSimple/naive-ui version (版本)
2.34.2

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Edge

### System and its version (系统及其版本)
Window11

### Reappearance link (重现链接)
https://codesandbox.io/s/quizzical-bash-gy87jn

### Reappearance steps (重现步骤)
fileList 字段中，传入的url 不包含文件后缀名时，图片不能正常显示

### Expected results (期望的结果)
fileList 字段中，传入的url 不包含文件后缀名时，图片也应该正常显示

### Actual results (实际的结果)
fileList 字段中，传入的url 不包含文件后缀名时，图片不能正常显示

### Remarks (补充说明)

![image](https://user-images.githubusercontent.com/28970254/207573713-78f2cc02-b2f8-45a1-8e9b-dc0ee7dd8c53.png)

**Comment by thibodeauxjl** [comment]
```
fileList: ref<UploadFileInfo[]>([
    {
          id: 'c',
          name: '我是自带url的图片.png',
          status: 'finished',
          url: 'https://thirdwx.qlogo.cn/mmopen/vi_32/POgEwh4mIHO4nibH0KlMECNjjGxQUq24ZEaGT4poC6icRiccVGKSyXwibcPq4BWmiaIGuG1icwxaQX6grC9VemZoJ8rg/132',
          type: 'image/jpeg',
        },
]
```

Without the file extension, you have to include a file type.

**Comment by zxysilent** [comment]
https://aliyunoss.helaodash.com/uploads/images/4b/d98a474270c94eed7b2f2b23228a71.jpg?x-oss-process=image/resize,m_lfit,w_150,limit_0/auto-orient,1/quality,q_90

现在还是不能识别这样的图片

**Comment by thibodeauxjl** [comment]
You have code on how you're trying to view it? In the above code sandbox I can replace the bottom image preview and it shows. 

```
previewFileList: ref<UploadFileInfo[]>([
        {
          id: 'react',
          name: '我是react.png',
          status: 'finished',
          url: 'https://07akioni.oss-cn-beijing.aliyuncs.com/07akioni.jpeg'
        },
        {
          id: 'vue',
          name: '我是vue.png',
          status: 'finished',
          url: 'https://aliyunoss.helaodash.com/uploads/images/4b/d98a474270c94eed7b2f2b23228a71.jpg?x-oss-process=image/resize,m_lfit,w_150,limit_0/auto-orient,1/quality,q_90',
          type: 'image/jpeg'
        }
      ])
```
![image](https://user-images.githubusercontent.com/37092905/217580984-1bfc47c2-92ac-480a-9cde-e3188e344b91.png)

**Comment by zxysilent** [comment]
Yes, it's my fault. It can run normally
