### ISSUE TITLE
Pagination 分页组件，下拉页数据选择器的 consistent-menu-width 属性，默认设为false

### ISSUE THREAD

**Issue by wei1034937343** [tusen-ai/naive-ui#4199]
### This function solves the problem (这个功能解决的问题)
分页栏下拉页数据选择器，下拉选项内容显示不全，影响用户体验
### Expected API (期望的 API)
分页栏下拉页数据选择器的 consistent-menu-width 属性，默认设为false

![image](https://user-images.githubusercontent.com/28970254/207578166-9b2b36d1-64f3-4278-9a37-7f3662b79f07.png)

**Comment by 07akioni** [comment]
closed in #4025
