### ISSUE TITLE
Make validation messages localizable

### ISSUE THREAD

**Issue by rbaprado** [tusen-ai/naive-ui#4207]
### This function solves the problem (这个功能解决的问题)
Importing a locale does not have any effect on form validation messages as of now. Having them included in the locale definition would greatly improve the localization efforts
### Expected API (期望的 API)
Having the validation messages included in the default locale file so we can create the translated versions

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
