### ISSUE TITLE
Customizing n-image modal

### ISSUE THREAD

**Issue by summerset-zz** [tusen-ai/naive-ui#4208]
### This function solves the problem (这个功能解决的问题)
I'm now using `n-image-group` as a gallery. 
I want to add description text (or title, or other elements) when it pops up.

### Expected API (期望的 API)
the ImageGroup comp should accept a data property rather than using the slot, like:
```typescript
{
    src:string; // source
    preview?:string; // thumb source
    imgProps: {alt?:string;title?:string;}; // prop for img tag
    title?:string|()=>VNode; // title of the image, not title of the img tag
    description?:string|()=>VNode; // description block of the image    
}[]
```

when the image pops up, it should be like:
```
   -------------- 
  |              |
< |     img      | >
  |              |
   -------------- 
  /title
  /desc
  [   toolbar   ]
```

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
