### ISSUE TITLE
Hide some actions on image preview

### ISSUE THREAD

**Issue by OscarEstudilloMarin** [tusen-ai/naive-ui#4214]
### This function solves the problem (这个功能解决的问题)
When using Image component to show art it is a must that the work can't be seen rotated. 
So It will be a nice feature to be able to disable / hide some of the actions on Image component on desire.
### Expected API (期望的 API)
On Image props:
disabledActions: ["rotateLeft", "rotateRight", "zoomIn", "actionName"].
And just add a && check when displaying the action Icon:
!disabledActions.find("rotateLeft") && rotateLeft

**Comment by jahnli** [comment]
May be released in the next release
