### ISSUE TITLE
upload组件的 UploadFileInfo，建议增加一个自定义属性，用于存储一些额外的信息

### ISSUE THREAD

**Issue by greper** [tusen-ai/naive-ui#4219]
### This function solves the problem (这个功能解决的问题)
比如，我想在每个文件附加上md5信息，在onSuccess中将md5添加为fileinfo对象的属性，但是下次从fileList中获取时，会丢失这个自定义属性。

如果能够加一个字段储存用户自定义的信息，那么使用起来会更方便。
否则就得本地写一个LocalFileList用于存储额外信息，并且需要在change、success、remove等多个事件中进行list同步，相当繁琐

### Expected API (期望的 API)
UploadFileInfo.custom = { md5:xxxx}
用于存储用户自定义的信息

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
