### ISSUE TITLE
Dynamic form rule feedback wrong with select component.

### ISSUE THREAD

**Issue by chioio** [tusen-ai/naive-ui#4227]
### TuSimple/naive-ui version (版本)
2.34.2

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Chrome(89.0.4389.128)

### System and its version (系统及其版本)
MacOS(12.6)

### Node version (Node 版本)
14.19

### Reappearance link (重现链接)
https://codesandbox.io/s/currying-shape-6w7xo2

### Reappearance steps (重现步骤)
1. Make a dynamic form with dynamic select component
2. Add rule for select like document sample
3. Test form...

### Expected results (期望的结果)
When select one option, feedback correct response.

### Actual results (实际的结果)
Select one option, triggered the rule.

### Remarks (补充说明)
![image](https://user-images.githubusercontent.com/36913769/209048283-eb3fb088-9596-4b44-8eac-717206db6a96.png)

**Comment by faga295** [comment]
maybe you should specify the type of the rules, becasue the default type is string,  but yours are number

**Comment by chioio** [comment]
> maybe you should specify the type of the rules, becasue the default type is string, but yours are number

Thank you so much! That's right!
