### ISSUE TITLE
n-tree 拖拽过程中的占位符，是否可以给一个class，这样就可以控制拖拽时的状态，类似helper一样的结点

### ISSUE THREAD

**Issue by kongkang** [tusen-ai/naive-ui#4229]
### This function solves the problem (这个功能解决的问题)
n-tree 拖拽过程中的占位符，是否可以给一个class，这样就可以控制拖拽时的状态，类似helper一样的结点
现在拖拽的时候只有一个绿色的线，非常不明显。
### Expected API (期望的 API)
helperClassName?

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
