### ISSUE TITLE
N-Element class style affect child component with the same class name

### ISSUE THREAD

**Issue by recallwei** [tusen-ai/naive-ui#4232]
### TuSimple/naive-ui version (版本)
2.34.2

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Chrome(108.0.5359.124)

### System and its version (系统及其版本)
MacOS(13.0.1)

### Node version (Node 版本)
18.12.1

### Reappearance link (重现链接)
https://github.com/recallwei/resume-generator/blob/main/src/views/Test/index.vue

### Reappearance steps (重现步骤)
A father component n-element with a class named "container", and child component also named "container",
child component style will be covered.

### Expected results (期望的结果)
The class style on N-Element should not affect the children components.

### Actual results (实际的结果)
It changed the style of child component.

### Remarks (补充说明)
I use the scoped property.
https://resume.bruceworld.top/test is my test page.

**Comment by 07akioni** [comment]
I think this is a vue issue.

**Comment by recallwei** [comment]
> I think this is a vue issue.

Thanks, the root element of the child component is always affected by its father component. Maybe I should wrap it with a div or avoid using the same class name on the root element.
