### ISSUE TITLE
数据表格minWidth无效 

### ISSUE THREAD

**Issue by zh1923** [tusen-ai/naive-ui#4235]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Chrome( 90.0.4430.222（32 位）)

### System and its version (系统及其版本)
Windows 11 家庭中文版

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/data-table#API

### Reappearance steps (重现步骤)
官网示例 里面的minWidth都是无效的

### Expected results (期望的结果)
minWidth 可控制最小宽度

### Actual results (实际的结果)
minWidth 设置后无效

**Comment by amadeus711** [comment]
未提供 min-width API ，如有需要，设置 style 即可。https://codesandbox.io/s/compassionate-kalam-o6oi0v?file=/src/Demo.vue

**Comment by zh1923** [comment]
https://codesandbox.io/s/heuristic-feistel-nwexbz?file=/src/Demo.vue
谷歌浏览器：当大量数据时，在columns中设置minWidth无效
注意是谷歌浏览器，火狐没问题

**Comment by zh1923** [comment]
谷歌浏览器版本升级后就又没问题了
之前版本：Chrome( 90.0.4430.222（32 位）)
现在版本：Chrome( 108.0.5359.125（正式版本） （64 位）)

**Comment by GodEnd** [comment]
minWidth无效，官方文档里面有minWidth这个API
