### ISSUE TITLE
DateRange能否支持只修改结束日期

### ISSUE THREAD

**Issue by Charl0tter** [tusen-ai/naive-ui#4241]
### This function solves the problem (这个功能解决的问题)
日期范围选择的时候，点击结束日期框的时候，能否固定开始日期，只改变结束日期，在用户只修改结束时间的时候方便用户操作，特别是在跨年跨月时间范围选择的时候特别有用。
### Expected API (期望的 API)
不添加api，点击结束日期的时候默认直接只修改结束时间，再未选中的时候，结束日期框内日期变灰表示激活状态，
![image](https://user-images.githubusercontent.com/23480626/209605285-dae52b7a-52ef-444d-86c0-0d1f5219cb88.png)
类似这种效果

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
