### ISSUE TITLE
A bug of the Data Table's API: flex-height

### ISSUE THREAD

**Issue by Yoshua404** [tusen-ai/naive-ui#4246]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Chrome

### System and its version (系统及其版本)
Windows10

### Reappearance link (重现链接)
https://www.naiveui.com/en-US/os-theme/components/data-table#fixed-header-column.vue

### Reappearance steps (重现步骤)
Press the left mouse button in the header area and drag the mouse as fast as possible to the right, you will find that the scroll of the table header is out of sync with the scrolling of the table body, and the scroll bar does not keep up.

### Expected results (期望的结果)
I think you should know :)

### Actual results (实际的结果)
As you can see :)

### Remarks (补充说明)
As I described, this bug can be reproduced on your official website, so I won't describe it too much.

**Comment by jahnli** [comment]
https://github.com/tusen-ai/naive-ui/issues/4290
