### ISSUE TITLE
n-image cannot use local image

### ISSUE THREAD

**Issue by UTing1119** [tusen-ai/naive-ui#4251]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Chrome 108.0.5359.125

### System and its version (系统及其版本)
windows 11

### Reappearance link (重现链接)
https://codesandbox.io/s/hopeful-resonance-ld9ovu

### Reappearance steps (重现步骤)
use local image/local source with n-image

### Expected results (期望的结果)
work like ```<img>``` do

### Actual results (实际的结果)
404 not found

### Remarks (补充说明)
I tried 'src/assets/myPicture.png', and it only worked in developer mode.
After build, it shows '404 not found'.
I want the toolbar shows while clicking the image,so it's good if I cound use n-image to show the local image.

The image prop API's src description only shows 'Image source', so I'm not sure if it can show up the local image.
Or it's just me using the wrong way?

**Comment by amadeus711** [comment]
This is the problem of your build config. You need to handle the path of the image during the build.
