### ISSUE TITLE
上下文菜单组件（NContextMenu）

### ISSUE THREAD

**Issue by alaywn** [tusen-ai/naive-ui#4252]
### This function solves the problem (这个功能解决的问题)
针对特定的组件区域，点击右键，出现上下文菜单。比如，在菜单上右键-->收藏，这样就把菜单添加到收藏夹
### Expected API (期望的 API)
https://github.com/imengyu/vue3-context-menu
可以参考这个项目

**Comment by leekoho** [comment]
https://www.naiveui.com/zh-CN/light/components/dropdown#manual-position.vue

**Comment by alaywn** [comment]
> https://www.naiveui.com/zh-CN/light/components/dropdown#manual-position.vue

Thank you
