### ISSUE TITLE
sider支持左右拖动改变宽度

### ISSUE THREAD

**Issue by alaywn** [tusen-ai/naive-ui#4253]
### This function solves the problem (这个功能解决的问题)
Sider中的菜单的内容长度提前不可知，希望支持用户拖动改变Sider宽度
### Expected API (期望的 API)
https://segmentfault.com/a/1190000042039814
可以参考这篇文章

**Comment by jahnli** [comment]
配合 `n-split`

**Comment by alaywn** [comment]
> 配合 `n-split`

仿佛有点意思
