### ISSUE TITLE
NDatePicker 打开面板后选择上（下）一个月或年，点击面板外区域，不会触发 blur 事件

### ISSUE THREAD

**Issue by qingruikz** [tusen-ai/naive-ui#4256]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Chrome (108.0.5359.125)

### System and its version (系统及其版本)
Windows 11

### Reappearance link (重现链接)
https://codesandbox.io/s/kzu8dm

### Reappearance steps (重现步骤)
1. 打开官网文档的案例 [日期选择器-事件](https://www.naiveui.com/zh-CN/os-theme/components/date-picker#events.vue)
2. 点击第一个输入框，弹出日期面板后直接点击面板上跳到下一个月或下一年的按钮
3. 点击面板以外的空白区域，面板会关闭，输入框会失去聚焦，但没有触发 blur 事件

### Expected results (期望的结果)
点击输入框，弹出日期面板后直接点击面板上跳到下一个月或下一年的按钮，再点击面板以外的空白区域，应该会触发 blur 事件。

### Actual results (实际的结果)
日期面板关闭，但没有触发 blur 事件。

**Comment by niuxinyu** [comment]
当点击了面板时输入框就失去焦点了

**Comment by qingruikz** [comment]
https://www.naiveui.com/zh-CN/os-theme/components/date-picker#events.vue
比如“事件”这个例子里面，点击面板上面的日期并没有触发 on-blur 回调。
不太理解 blur 触发的逻辑是什么

**Comment by qingruikz** [comment]
> 当点击了面板时输入框就失去焦点了

https://www.naiveui.com/zh-CN/os-theme/components/date-picker#events.vue
比如“事件”这个例子里面，点击面板上面的日期并没有触发 on-blur 回调。
不太理解 blur 触发的逻辑是什么

**Comment by faga295** [comment]
逻辑应该是输入框失去焦点的时候，如果点的地方在panel里面就不会触发，如果不在，那就触发

**Comment by qingruikz** [comment]
> 逻辑应该是输入框失去焦点的时候，如果点的地方在panel里面就不会触发，如果不在，那就触发

确实是这样，谢谢！
