### ISSUE TITLE
时间选择控件能够指定返回格式化后的字符串还是时间戳

### ISSUE THREAD

**Issue by jingtu-Lincoin** [tusen-ai/naive-ui#4261]
### This function solves the problem (这个功能解决的问题)
目前时间选择器写死了只能返回时间戳，后台使用字符串做为时间格式，完全没办法对接。希望能够提供可选的方案，可以将格式化的时间字符串做为表单的值。
### Expected API (期望的 API)
inputValue:"text",  //text or value

**Comment by Nakus0426** [comment]
请看文档 `Time Picker` 组件中的 `API` -> `TimePicker Props` 的 `format` 和 `formatted-value` 属性

**Comment by jingtu-Lincoin** [comment]
请你看清楚问题。

**Comment by Nakus0426** [comment]
> 请你看清楚问题。

你指的 `将格式化的时间字符串做为表单的值` 是指 `12:00:00` 这种格式？如果是的话，那就是你压根没仔细看文档。如果不是的话那你问题表述我看不明白

**Comment by jingtu-Lincoin** [comment]
谢谢，已解决
