### ISSUE TITLE
n-pagination 部署到服务器之后，点击页码不执行@update:page函数，本地正常执行；@update:page-size方法本地和服务器环境都正常执行

### ISSUE THREAD

**Issue by wanglei1346** [tusen-ai/naive-ui#4269]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Chrome(107.0.5304.87)

### System and its version (系统及其版本)
MacOS(13.0.1)

### Node version (Node 版本)
16.18.0

### Reappearance link (重现链接)
https://github.com/wanglei1346/navie.git

### Reappearance steps (重现步骤)
线上环境中点击页码无法执行对应函数。对应git地址中的代码：src/components/DataTable.vue文件

### Expected results (期望的结果)
希望帮助解决一下

### Actual results (实际的结果)
无法点击页码

**Comment by OrbisK** [comment]
don't use `n-pagination` you can use `pagination` prop on `n-data-table` see: https://www.naiveui.com/en-US/os-theme/components/data-table#controlled-page.vue

**Comment by wanglei1346** [comment]
现在已经修复，把n-pagination的v-model:page=‘page’改成:page='page'就好了，有点奇怪，这俩个不是一个意思吗
