### ISSUE TITLE
cannot change the color of the child of Menu

### ISSUE THREAD

**Issue by UTing1119** [tusen-ai/naive-ui#4271]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Chrome 108.0.5359.125 

### System and its version (系统及其版本)
Windows 11

### Reappearance link (重现链接)
https://www.naiveui.com/en-US/os-theme/components/menu

### Reappearance steps (重现步骤)
use code or NThemeEditor to change the child's color of N-Menu

### Expected results (期望的结果)
the child color of menu will change as well

### Actual results (实际的结果)
I tried to change the child's color of menu while it's collapsing.
But nothing happened while I change color via NThemeEditor.
Neither collapsed menu nor non-collapsed menu's color changed.
It seems that it's still a part of Menu,but if you wanna change its background color,you need to change"common","popoverColor".
There has no description of what should I use to change them, so I have no idea if there's a bug or just me wrong.

我想修改當菜單摺疊時，顯示的popover內菜單的active text color
但是我透過主題編輯器修改了所有menu內的color，它都沒有任何變動
看起來它仍是屬於Menu的一部份，但是它的背景顏色卻是以common的popoverColor為主
因為沒有任何的API敘述，所以我也不確定是bug還是是我用法錯誤

![image](https://user-images.githubusercontent.com/74576629/209933188-6d9ea2d3-1b1d-45a8-bd5e-b3fa101ebdcb.png)

**Comment by amadeus711** [comment]
The scenario of n-menu is really implemented by n-popover, so it's OK to name it 'popoverColor'.
If you just want to modify independently, you can use peers API, see:
https://www.naiveui.com/en-US/os-theme/docs/customize-theme#Use-the-peers-vars
