### ISSUE TITLE
DataTable 增加template支持

### ISSUE THREAD

**Issue by liu-xinhui** [tusen-ai/naive-ui#4273]
### This function solves the problem (这个功能解决的问题)
目前的render方式过于复杂，语法晦涩难懂，复杂的单元格简直没法看。并且不能实现数据分离，我们需要持久化columns,现在这种columns中定义函数无法实现持久化。

希望能是实现类似于iview或者antd的语法，【不是element那种，不够灵活】

https://www.iviewui.com/view-ui-plus/component/form/table
https://antdv.com/components/table-cn
### Expected API (期望的 API)
``` html
<Table :columns="columns" :data="data">
    <template #name="{ row, index }">
      <Input type="text" v-model="editName" v-if="editIndex === index" />
      <span v-else>{{ row.name }}</span>
    </template>

    <template #age="{ row, index }">
      <Input type="text" v-model="editAge" v-if="editIndex === index" />
      <span v-else>{{ row.age }}</span>
    </template>
<Table/>
```

**Comment by jahnli** [comment]
ref https://github.com/tusen-ai/naive-ui/issues/216

我认为 template 在一些场景会让代码变的更不清晰, 可以通过 `tsx` 来达到基本类似的效果

**Comment by ibryang** [comment]
两种方式, 各有优缺点, 所以让用户选择不好吗?
render方式, 稍微复杂一点的表格, 写起来是真的难受.

**Comment by liu-xinhui** [comment]
> 

已经半年多没有任何更新了，这么好的一个库，只能放弃了

**Comment by liu-xinhui** [comment]
@ibryang 已经半年多没有任何更新了，这么好的一个库，只能放弃了

**Comment by liugu0914** [comment]
作者没空只能自己扩展，二次封装n-data-table组件可以达到这个效果。

**template**
```vue
    <BaseTable
      :columns="columns"
      :data="data.dataSource">
      <template #actions="{ row, index }">
        <NButton type="primary">{{ row.name + index }}</NButton>
      </template>
    </BaseTable>
```
**二次封装 columns**
``` js
  const columns = computed(() => {
    const slotKeys = Object.keys(slots) // 传递的slots
    const fColumns = props.columns // 插槽传递的columns

    fColumns.forEach((item) => {
      if (slotKeys.includes(item.key as string)) { //渲染插槽
        item.render = (row, index) => slots[item.key]({ row, index, column: item })
      }
    })

    return fColumns
  })
```

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by KigoZou** [comment]
我已经找到解决方案了：

1. 自定义表表格组件
`<template>
  <div>
    <n-data-table
      v-model:checked-row-keys="selectRows"
      :loading="loading"
      :columns="columns"
      :data="list"
      :render-cell="renderCell"
      :row-key="(row: any) => row.id"
      :scroll-x="scrollX"
    />
    <div v-if="showPagination" class="flex justify-end mt-3">
      <n-pagination v-model:page="query.page" :item-count="5000" :on-update:page="handlePageChange" @on-update:page-size="handlePageSizeChange" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, h, PropType } from 'vue'
import { NImageGroup, NImage } from 'naive-ui'
import { CustomDataTableColumn } from './type'
import dayjs from 'dayjs'

const emit = defineEmits(['fetchData'])
const query = defineModel<any>('query', { default: () => {} })
const selectRows = defineModel<any[]>('selectRows', { default: () => [] })

const slots = defineSlots<{
  action: (row: any) => any
  [key: string]: (row: any) => any
}>()

const props = defineProps({
  loading: {
    type: Boolean,
    default: false,
  },
  showPagination: {
    type: Boolean,
    default: true,
  },
  columns: {
    type: Array as PropType<CustomDataTableColumn[]>,
    required: true,
  },
  total: {
    type: Number,
    default: 0,
  },
  list: {
    type: Array,
    default: () => [],
  },
})

/**
 * 计算滚动宽度
 */
const scrollX = computed(() => {
  return props.columns.reduce((pre, cur) => pre + (cur.width || 100), 0)
})

const renderCell = (value: string | number, row: any, column: CustomDataTableColumn) => {
  // 时间格式化
  if (column.slot == 'datetime') {
    return dayjs(value).format('YYYY-MM-DD HH:mm')
  }
  // 图片
  if (column.slot == 'image' && typeof value == 'string') {
    return h(
      NImageGroup,
      { showToolbarTooltip: true },
      {
        default: () =>
          value
            ?.split(',')
            ?.filter(Boolean)
            ?.map((d: any) => h(NImage, { src: d, alt: '图片', class: 'w-12 h-12 rounded' })) || [],
      },
    )
  }
  //  自定义插槽
  if (column.slot && slots[column.slot]) {
    return h(slots[column.slot], { row })
  }
  return value
}

const handlePageChange = (page: number) => {
  query.value.page = page
  emit('fetchData')
}

const handlePageSizeChange = (pageSize: number) => {
  query.value.page = 1
  query.value.pageSize = pageSize
  emit('fetchData')
}
</script>
`
2. 使用自定义表格组件
`    <CustomTable
      v-model:query="query"
      v-model:selectRows="selectRows"
      :loading="loading"
      :columns="columns"
      :list="list"
      :total="total"
      @fetch-data="fetchData"
    >
      <template #action="{ row }">
        <n-space>
          <n-button size="small" type="primary" @click="handleDetail(row)">详情</n-button>
          <n-button v-if="row.status == 'pending'" size="small" type="warning" @click="handleEdit(row)">审核</n-button>
        </n-space>
      </template>
    </CustomTable>
`

3.columns定义

`const columns = [...,{ title: '操作', key: 'action', width: 218, fixed: 'right', slot: 'action' }]`
