### ISSUE TITLE
我fork代码了以后跑不起来报错Unexpected token '||='

### ISSUE THREAD

**Issue by whr2349** [tusen-ai/naive-ui#4282]
### This function solves the problem (这个功能解决的问题)
我fork代码了以后跑不起来报错Unexpected token '||='
### Expected API (期望的 API)
> naive-ui@2.34.3 gen-volar-dts D:\project\my\naive-ui
> esbuild scripts/gen-component-declaration.js --bundle --platform=node --tsconfig=tsconfig.esbuild.json | node

[stdin]:14
  for (var prop in b2 ||= {})
                      ^^^
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.

**Comment by jizai1125** [comment]
https://github.com/tusen-ai/naive-ui/issues/4015
