### ISSUE TITLE
建议n-select显示选中的值可跳出options的值

### ISSUE THREAD

**Issue by yudan215** [tusen-ai/naive-ui#4283]
### This function solves the problem (这个功能解决的问题)
select data-table组合使用,有很多场景的筛选，筛选数据可能存在几万条数据，希望select显示的时候显示 筛选和表格，可对表格数据进行筛选，并且点击表格单选或者多选某条数据，进行select选中
### Expected API (期望的 API)
selectedOption目前是computed，希望可以由父级组件设置进行数据的呈现

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
