### ISSUE TITLE
nuxt3稳定版的demo可以更新吗

### ISSUE THREAD

**Issue by ryiot** [tusen-ai/naive-ui#4287]
### This function solves the problem (这个功能解决的问题)
nuxt3稳定版的demo可以更新吗
### Expected API (期望的 API)
nuxt3稳定版的demo可以更新吗

**Comment by moyukingS** [comment]
按照Nuxt的modules 自动导入 naive-ui不成功，希望能出个示例

**Comment by SLSSZM** [comment]
安装unplugin-auto-import和unplugin-vue-components，在nuxt.config.ts里配置这个
![image](https://user-images.githubusercontent.com/55221184/210499205-a5d99da9-3e98-4e18-bde9-a404cf673051.png)

**Comment by TakaSoap** [comment]
同样有这个问题

**Comment by TakaSoap** [comment]
> 安装unplugin-auto-import和unplugin-vue-components，在nuxt.config.ts里配置这个 ![image](https://user-images.githubusercontent.com/55221184/210499205-a5d99da9-3e98-4e18-bde9-a404cf673051.png)

我也有一样的问题，希望作者可以看看

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by 07akioni** [comment]
https://www.naiveui.com/en-US/os-theme/docs/nuxtjs
