### ISSUE TITLE
daterange default time

### ISSUE THREAD

**Issue by tiamed** [tusen-ai/naive-ui#4288]
### This function solves the problem (这个功能解决的问题)
provide config option for default time(start and end) for date range picker
### Expected API (期望的 API)
:default-time="['00:00:00', '23:59:59']"

**Comment by jahnli** [comment]
`

const defaultTime = computed(() => {
  const types: Partial<PickerDefaultTimeType> = {
    date: 'undefined',
    datetimerange: ['00:00:00', '23:59:59']
  };
  return types[componentProps.type ?? 'date'];
});

:default-time="defaultTime"
`

There should be props for that

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
