### ISSUE TITLE
表格横向滚动表头和表体错位 

### ISSUE THREAD

**Issue by JS-an** [tusen-ai/naive-ui#4290]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Chrome(108.0.5359.125)

### System and its version (系统及其版本)
win10(64位)

### Reappearance link (重现链接)
https://codesandbox.io/s/6wmst2

### Reappearance steps (重现步骤)
先鼠标点击表体，再把鼠标移到表头(不点击)，再按下键盘右箭头，就可以看到表头和表体错位了

### Expected results (期望的结果)
预期是表头和表体不错位

### Actual results (实际的结果)
实际发生了错位

### Remarks (补充说明)
![image](https://user-images.githubusercontent.com/25688878/210498439-47e42953-245d-44a2-be32-601d6fe56f2d.png)

**Comment by Yoshua404** [comment]
设置 flex-height 属性时， 出现如上bug
