### ISSUE TITLE
关于form鼠标焦点默认在第一个formItem上的配置问题

### ISSUE THREAD

**Issue by zhoufanglu** [tusen-ai/naive-ui#4296]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.2

### Browser and its version (浏览器及其版本)
chrome89

### System and its version (系统及其版本)
win10

### Reappearance steps (重现步骤)
打开表单，鼠标焦点默认在第一个formItem上
![image](https://user-images.githubusercontent.com/24451091/210694031-04bcc706-8ba3-46f0-ba00-2f9cfc44b47f.png)

### Remarks (补充说明)
我想知道这有配置项可以配置是否选择第一个formItem

**Comment by thibodeauxjl** [comment]
Without seeing the code and only the picture I'm going to assume this is a modal and that would be the auto focus feature which is defaulted to true. Disable by setting to false:

`<n-modal :auto-focus="false" />`

**Comment by zhoufanglu** [comment]
> 

thank you for answer, this config slove my problem
