### ISSUE TITLE
n-tree组件是否可以提供编辑功能

### ISSUE THREAD

**Issue by qq229338869** [tusen-ai/naive-ui#4301]
### This function solves the problem (这个功能解决的问题)
我希望在n-tree组件node上可以直接编辑label名称。

### Expected API (期望的 API)
类似使用 node-props 为节点绑定属性，比如点击事件或者右键菜单。
提供直接api编辑节点功能：修改名称、删除节点。

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
