### ISSUE TITLE
建议n-image 组件可以添加一个下载按钮

### ISSUE THREAD

**Issue by heroSoft205** [tusen-ai/naive-ui#4302]
### This function solves the problem (这个功能解决的问题)
虽然说可以右键保存，但是如果有了下载按钮，既可以更醒目，更直观，更便捷
### Expected API (期望的 API)
无

**Comment by hellokaton** [comment]
<img width="1141" alt="image" src="https://github.com/tusen-ai/naive-ui/assets/3849072/d5ce0325-e426-4802-bdd8-28cd1ea1446a">
通需要，像这种的 :p
