### ISSUE TITLE
页面使用响应式NGrid组件和vue-router后跳转闪屏

### ISSUE THREAD

**Issue by yangsengui** [tusen-ai/naive-ui#4305]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Chrome(108.0.5359.125)

### System and its version (系统及其版本)
Windows10

### Node version (Node 版本)
16.14.2

### Reappearance link (重现链接)
https://github.com/yangsengui/naive-grid

### Reappearance steps (重现步骤)
从 / 页面点击link(vue-router)跳转后的 /page 页面

### Expected results (期望的结果)
跳转后不闪屏

### Actual results (实际的结果)
page页面使用了NGrid组件响应式模式，cols="1 400:4 600:6"，跳转过去后第一时间cols=1，然后马上变为cols=6，出现闪屏的感觉，直接从浏览器输入链接/page访问没有这个问题，感觉像是vue-router的问题

**Comment by amadeus711** [comment]
目测是 router 的过渡效果的问题

**Comment by yangsengui** [comment]
最新的版本2.34.3仍然有这个问题，由修复的计划吗，感谢

**Comment by yangsengui** [comment]
这个组件作为NGrid的替代可以使用，在响应式的情况下首屏不会出现问题，https://github.com/andrelmlins/vue-grid-responsive

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
