### ISSUE TITLE
Can implement an component like notion database

### ISSUE THREAD

**Issue by Ikki-Dai** [tusen-ai/naive-ui#4307]
### This function solves the problem (这个功能解决的问题)
an table that can provide multiple view like notion database, which can provide more attractive to users

it provide kanban, table, gantt views, and also and it allow custom column such as `date`,`link`,`selection` type fields and so on.

### Expected API (期望的 API)
`<n-database :data= data />`

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
