### ISSUE TITLE
I can’t set the first row of the data table to be selected. [Data Table by Single selection]

### ISSUE THREAD

**Issue by djr08** [tusen-ai/naive-ui#4314]
### This function solves the problem (这个功能解决的问题)
I want to use Single selection of Data Table,
to set the first line of the result to be selected.
But it doesn't have this feature
### Expected API (期望的 API)
I hope that there is a method which can set the row number of results for the default value。
![image](https://user-images.githubusercontent.com/122240611/211228176-314d3297-31c7-4eb4-9cdd-fc39a4b6fc5c.png)

**Comment by Sepush** [comment]
use `checked-row-keys` prop
```ts
const checkedRowKeysRef = ref([0]);
```

**Comment by djr08** [comment]
> use `checked-row-keys` prop
> 
> ```ts
> const checkedRowKeysRef = ref([0]);
> ```

Thank you for your reply
