### ISSUE TITLE
when in modal, some slider by v-if hide, render errro

### ISSUE THREAD

**Issue by hcwhan** [tusen-ai/naive-ui#4320]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Chrome(108.0.5359.124)

### System and its version (系统及其版本)
Liunx

### Reappearance link (重现链接)
https://codesandbox.io/s/fragrant-haze-5bfkcx?file=/src/Demo.vue

### Reappearance steps (重现步骤)
open codesandbox url, see it

### Expected results (期望的结果)
render ok

### Actual results (实际的结果)
vue error: Cannot read properties of undefined (reading 'value')

**Comment by jahnli** [comment]
Closed due to inactivity. Feel free to reopen if you're still having trouble.
