### ISSUE TITLE
Carousel 轮播图 在只有两个图展示时，轮播模拟拖拽会出现动效问题

### ISSUE THREAD

**Issue by gx12358** [tusen-ai/naive-ui#4323]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Chrome(108.0.5359.124)

### System and its version (系统及其版本)
MacOs(13.0.1)

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/carousel

### Reappearance steps (重现步骤)
childrenItem(图片)设置两个，设置loop为true，模拟拖拽（draggable为true），最后一个拖拽到第一个时，动效不是有左到右，而是直接从左边返回第一个

### Expected results (期望的结果)
动效应该正常从左边到右边展示（和childrenItem(图片)大于三个保持一致）

### Actual results (实际的结果)
直接从左边返回第一个

**Comment by amadeus711** [comment]
Remarks: https://codesandbox.io/s/elegant-kate-py7kti

**Comment by dmitryST93** [comment]
Please fix this problem
