### ISSUE TITLE
File list shows multiple files even for single-file upload fields

### ISSUE THREAD

**Issue by casperboone** [tusen-ai/naive-ui#4327]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.36

### Browser and its version (浏览器及其版本)
Chromium: 108.0.5359.128

### System and its version (系统及其版本)
macOS 12.4

### Reappearance link (重现链接)
https://codesandbox.io/s/festive-sea-q99b6s?file=/src/Demo.vue

### Reappearance steps (重现步骤)
* Upload a file
* Upload another file

### Expected results (期望的结果)
I expect the file list to only show one file, the last one that is uploaded.
Because the `multiple` property is set to false.

### Actual results (实际的结果)
It shows all files that the user uploads. This is confusing because it suggests that a user can upload multiple files while only one file is accepted.

**Comment by thibodeauxjl** [comment]
The multiple property prevents you from uploading more than one file at a time which is working in this case.  So when you press the upload button, you can only select one item. The list shows all the items you've uploaded. If you want to only allow one uploaded item, then you'll need to use a function to hide the button when the file list length is greater than 0, if you want to upload multiple files but only show one, you'll need a function to manipulate the list when uploading.

**Comment by thibodeauxjl** [comment]
Reading the Naive documentation, you can set a  `v-model:filelist=""` property as well as a `:disabled=""` property. So to only allow one file to be uploaded, it would be something like:

```
<n-upload action="https://httpstat.us/200" :multiple="false" :disabled="fileList.length" v-model:file-list="fileList">
    <n-button>Upload File</n-button>
</n-upload>
```

**Comment by thibodeauxjl** [comment]
To set just the last uploaded file.. you can refer to https://www.naiveui.com/en-US/os-theme/components/upload#controlled.vue. In your on-update:file-list function you can do something like this: 

```
handleFileListChange(options) {
  let lastIndex = options.length - 1
    fileListRef.value = [
      {
        id: options[lastIndex].id,
        name. options[lastIndex].name
        // etc...
      }
    ]
  }
}
```

This will replace the file list with the last file every time a file is uploaded.
