### ISSUE TITLE
Cannot read properties of null (reading 'emitsOptions')

### ISSUE THREAD

**Issue by HarperGG** [tusen-ai/naive-ui#4336]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Chrome(108.0.5359.124)

### System and its version (系统及其版本)
ubuntu (18.04)

### Reappearance link (重现链接)
https://codesandbox.io/s/hopeful-beaver-1hovb8?file=/src/Demo.vue

### Reappearance steps (重现步骤)
- 引入Drawer组件
- 修改to属性值为非 "body"
- show属性默认为 "true"
- 刷新页面回出现报错

### Expected results (期望的结果)
刷新页面后抽屉可以默认弹出，并且在指定 to 的位置

### Actual results (实际的结果)
抽屉没有正常弹出，并且报错。

**Comment by thibodeauxjl** [comment]
I think this is because it is trying to emit to `#content` before `<div id="content">` is mounted.

_Demo_
```
<div 
      id="content" 
      style="position: relative;
      width: 100%;
      height: 300px;
      border: 1px solid rgba(128, 128, 128, 0.2);
      margin-top: 10px;
      display: flex;
      align-items: center;
      justify-content: center;
      overflow: hidden;"
  >
    <Content />
  </div>
```
_Content_
```
<n-drawer :show="active" to="#content" :width="502" :placement="placement">
    <n-drawer-content title="斯通纳">
      《斯通纳》是美国作家约翰·威廉姆斯在 1965 年出版的小说。
    </n-drawer-content>
</n-drawer>
```

```
const active = ref(false);
const placement = ref("right");
const activate = (place) => {
  active.value = true;
  placement.value = place;
};
onMounted(() => {
  activate('right')
})
```

**Comment by HarperGG** [comment]
感谢，情况确实就是这样！

**Comment by amadeus711** [comment]
> 

This seems to be a problem of use, and this situation does not need to be considered inside the component.

**Comment by amadeus711** [comment]
> I think this is because it is trying to emit to `#content` before `<div id="content">` is mounted.
> 
> _Demo_
> 
> ```
> <div 
>       id="content" 
>       style="position: relative;
>       width: 100%;
>       height: 300px;
>       border: 1px solid rgba(128, 128, 128, 0.2);
>       margin-top: 10px;
>       display: flex;
>       align-items: center;
>       justify-content: center;
>       overflow: hidden;"
>   >
>     <Content />
>   </div>
> ```
> 
> _Content_
> 
> ```
> <n-drawer :show="active" to="#content" :width="502" :placement="placement">
>     <n-drawer-content title="斯通纳">
>       《斯通纳》是美国作家约翰·威廉姆斯在 1965 年出版的小说。
>     </n-drawer-content>
> </n-drawer>
> ```
> 
> ```
> const active = ref(false);
> const placement = ref("right");
> const activate = (place) => {
>   active.value = true;
>   placement.value = place;
> };
> onMounted(() => {
>   activate('right')
> })
> ```

This seems to be a problem of use, and this situation does not need to be considered inside the component.

**Comment by thibodeauxjl** [comment]
I agree. Nesting the NDrawer component inside the div you're trying to apply it to isn't ideal, but I'm not sure of the use case and what the end goal is. Using the NDrawer component inside the Demo.vue instead of the Content.vue would prevent you from having to use onMount.

**Comment by thibodeauxjl** [comment]
I retract my last statement after testing. The problem isn't the placement of the component, it is setting the :show value to true when trying to apply it to a nested div. No matter where you put the NDrawer component, you will have to activate it onMount if you want it to show on page load.

**Comment by jahnli** [comment]
Closed due to inactivity. Feel free to reopen if you're still having trouble
