### ISSUE TITLE
关于 Data Table 组件树形数据展示的问题

### ISSUE THREAD

**Issue by AshenOneOrz** [tusen-ai/naive-ui#4337]
### This function solves the problem (这个功能解决的问题)
例子：

- Line A
    - Child Line1
    - Child Line2
-  Line B
   -  Child Line1
    - Child Line2

现有情况：
点击 Line A 时，不但会展开/隐藏 Line A 下面的两个 Child Line，还会同时展开/隐藏 Line B 下面的两个 Chid Line。

希望：
点击 Line A 时，仅展开 Line A 下的 Child Line1 Child Line2，不影响 Line B
 
### Expected API (期望的 API)
使用 props 的方式进行控制，可以选择展开全部，也可以选择仅展开选中行
例子：
```
:expand-all="true"
```

**Comment by huahaoJiang** [comment]
正常不会这样吧？可以看看Line A和Line B的key是不是设置成一样的了

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
