### ISSUE TITLE
不能设置`<NInput/>`的高度，尤其是`type='textarea'`的时候。

### ISSUE THREAD

**Issue by heroboy** [tusen-ai/naive-ui#4339]
### This function solves the problem (这个功能解决的问题)
不是`rows`。
直接使用NInput的`text-props`勉强可以。但是，因为外面包裹了基层div，`height:100px`这种可能不准，`flex:1`不能用。

希望按照下面的API look like那样，把style属性继承到最外层的div上。

### Expected API (期望的 API)
```
<NInput style="flex:1"/>
```

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
