### ISSUE TITLE
模态框 Modal没有全屏属性设置

### ISSUE THREAD

**Issue by zyd915** [tusen-ai/naive-ui#4342]
### This function solves the problem (这个功能解决的问题)
模态框 Modal没有全屏属性配置项
### Expected API (期望的 API)
模态框 Modal有全屏属性设置 可以全屏

**Comment by Sepush** [comment]
使用 style 属性
```js
          style:{
            width:'100vw',
            height:'100vh'
          }
```

**Comment by zyd915** [comment]
谢谢 我已实现 切换全屏模式
