### ISSUE TITLE
In the table attribute, we hope to add the align of the table header and the align of the table content / table属性里面希望可以增加表头的align和表内容的align

### ISSUE THREAD

**Issue by katarinaxxx** [tusen-ai/naive-ui#4344]
### This function solves the problem (这个功能解决的问题)
Can realize header center, but content left; Or the header is left, but the content is center.
可以实现 表头center,但是内容left;或者是表头left,但是内容center
### Expected API (期望的 API)
In the table attribute, we hope to add the align of the table header and the align of the table content / table属性里面希望可以增加表头的align和表内容的align

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
