### ISSUE TITLE
能否提供聊天消息组件?

### ISSUE THREAD

**Issue by pkptzx** [tusen-ai/naive-ui#4345]
### This function solves the problem (这个功能解决的问题)
能否提供聊天组件?类似quasar提供的ChatMessage组件
[ChatMessage](https://quasar.dev/vue-components/chat)
### Expected API (期望的 API)
eg . https://quasar.dev/vue-components/chat

**Comment by Sepush** [comment]
也许会做但是优先级很低

**Comment by 07akioni** [comment]
我感觉大概率不会提供，这种组件的抽象通用的部分太少了，离业务需求更近。

**Comment by 07akioni** [comment]
倒不是说这个组件没用，而是通用的部分做出来用户还是需要大量定制，即使给出来，那一部分本身也不难实现

**Comment by jahnli** [comment]
ref https://github.com/tusen-ai/naive-ui/pull/7040
