### ISSUE TITLE
emit expand-trigger event

### ISSUE THREAD

**Issue by wc-matteo** [tusen-ai/naive-ui#4354]
### This function solves the problem (这个功能解决的问题)
being able to do something when expansion/contraction happens
### Expected API (期望的 API)
v-on:expand

**Comment by wc-matteo** [comment]
maybe add an expanded v-model prop

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
