### ISSUE TITLE
滚动条scrollTo失效,当父容器display-none的时候

### ISSUE THREAD

**Issue by gowy222** [tusen-ai/naive-ui#4355]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
chrome108

### System and its version (系统及其版本)
win11

### Node version (Node 版本)
16

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/dark/components/scrollbar

### Reappearance steps (重现步骤)
tab - show 模式
tab页内使用n-Scrollbar，当后台pinia数据刷新，tan页面 重新渲染数据的时候，不管前台渲染 还是 后台 渲染，需要强制 滚动条 归位(不管元素是否可视)。

----------
    this.$refs.n_scroll.scrollTo({
                left: 0,
                top: 0,
                behavior:'smooth'
              });

----------------
当然: 上级元素不可视 或者 n-scrollbar-rail--disabled 的时候behavior-smooth应该被强制忽略，浪费性能..(勤俭节约嘛)

tab没有切换，当前可视的时候scrollTo是有效的。

当tab已切换 => 本tab页属于display-none的时候, Scrollbar 会自变成 n-scrollbar-rail--disabled, 这会导致scrollTo函数被忽略。
最终应该归位的滚动条 没有 变化。

### Expected results (期望的结果)
scrollTo 永远生效, 不管上级元素可视与否 和 是否 n-scrollbar-rail--disabled。

### Actual results (实际的结果)
上级元素 display-none, n-scrollbar 优先执行的n-scrollbar-rail--disabled, 从而导致scrollTo不会生效.

**Comment by gowy222** [comment]
实在不行，n-scrollbar 给个新的 Method 接口：ReSet(is_smooth) //强制归位

**Comment by gowy222** [comment]
目前应用场景 是 那种 大片文字 需要 n-scrollbar 包裹的时候,

data table 内部自带 n-scrollbar 这个还没测试 会不会归位, 期望 官方考虑一下

**Comment by gowy222** [comment]
本来是想 再用一个v-if    div来包裹, 但是这样一来，不管可视不可视，smooth 滚动 那种 高大上的视觉体验就永远没机会了...

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
