### ISSUE TITLE
Add support for "white" or "light" button type

### ISSUE THREAD

**Issue by lbagic** [tusen-ai/naive-ui#4356]
### This function solves the problem (这个功能解决的问题)
The current button works great until you want a plain white button on a darker background. Setting the "color" property to white is too flawed to be used. Extending the button interface to support "white" type would be really helpful.

Example image: https://drive.google.com/file/d/1f9Dyub6RcPSo-piGkf2dGtSErlt4NCgM/view?usp=share_link
Mock implementation: https://pastebin.com/ym5ARdst
### Expected API (期望的 API)
<NButton type="white">I am a white button</NButton>

**Comment by Sepush** [comment]
here is a another solution
```vue
      <n-config-provider :theme="null">
        <n-button>Default</n-button>
      </n-config-provider>
```
