### ISSUE TITLE
CodeMirror error

### ISSUE THREAD

**Issue by AbubakirMahkamov-prog** [tusen-ai/naive-ui#4357]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Chrome

### System and its version (系统及其版本)
Windows 11

### Node version (Node 版本)
16

### Reappearance link (重现链接)
https://www.naiveui.com/

### Reappearance steps (重现步骤)
I use naive ui .Every thing is done as docs.I got console log Code Mirror error.

### Expected results (期望的结果)
Clearly console

### Actual results (实际的结果)
Using naive ui console log Code Mirror error .I confused what happaned.Every this is done as docs.

VM107:78 Uncaught TypeError: Cannot read properties of null (reading 'CodeMirror')
    at <anonymous>:78:30

**Comment by thibodeauxjl** [comment]
Do you have the blackbox chrome extension installed? I've seen some problems where this extension can result in this error. If so, the simple solution is to uninstall it.

**Comment by AbubakirMahkamov-prog** [comment]
Yes. I had it .I just uninstalled.Problem solved.I got rid of it.

**Comment by AbubakirMahkamov-prog** [comment]
[thibodeauxjl](https://github.com/thibodeauxjl), Thank you
