### ISSUE TITLE
更好的InputNumber：使用鼠标拖动来改变数值

### ISSUE THREAD

**Issue by heroboy** [tusen-ai/naive-ui#4358]
### This function solves the problem (这个功能解决的问题)
如今几乎所有Web上的UI框架的InputNumber都是对`<input type="number"/>`的简单包装，提供了一些格式化显示，验证以及"+","-"按钮。但是扪心自问，这个"+","-"按钮真的好用吗？有很多仅仅+1或-1的需求吗？为了+10，值得点10下鼠标吗？

如今，像blender，Unity3D，3dsmax等3d软件或引擎中的数值输入控件，无一例外的提供了拖动改变数值的功能。这能够使得用户通过简单的操作让数值连续变化，然后观察场景中物体的变化。

另外，这也不是Slider控件能做的。Slider的范围一定是有限的。而且如果范围太大，会使得非常难或不可能用鼠标来定位精确的数值了。

我能想到的一些设计上的点：
* 这个功能不涉及界面上的变化，只有操作的变化。对现有的InputNumber改变不大。实现起来不是很难。
* 应该使用上下拖动来改变数值。因为左右拖动是用来选择文本的。
* 加入阈值，确定是开始上下了，才开始改变数值。
* 在拖动的时候，鼠标指针改为上下箭头。甚至，当往上拖动的时候显示上箭头，往下下箭头。
* 通过另一个轴向的移动来改变上下移动时，改变数值变化的速度。也就是说，当需要精确改变数值的时候，上下拖动即可；当需要剧烈改变数值的时候，先左右拖动，在x轴方向上远离初始的位置，然后在上下拖动。（此灵感来自于一个早期的bilibili ipad客户端，在视频中心左右拖动改变进度条的功能。非常好用。）

我随便在网上找的示例：
* https://www.dearimgui.org/webdemo/master/example_emscripten.html
* https://codepen.io/DarkStar66/pen/eBrdrY
* https://www.jqueryscript.net/demo/Change-The-Value-Of-Your-Number-Input-With-Mouse-Drag-stepper-js/

### Expected API (期望的 API)
todo

**Comment by jizai1125** [comment]
我看长按 `+`, `-` 按钮可以连续递增/递减的

**Comment by Sepush** [comment]
input-number 如果你想要加10 直接键盘输入明显是更有效率的方式

**Comment by heroboy** [comment]
> input-number 如果你想要加10 直接键盘输入明显是更有效率的方式

我的这个+10的示例，只是为了说明+-按钮的没用。

但是，如果你需要+10。你可以试一下，例如blender，或者我上面第一个示例，都是可以直接在文本框内输入"+10"回车，来对数值进行+10的功能的。

**Comment by ice-fortress** [comment]
你也可以使用键盘的上下键来进行数值的快速加减。

如果是需要固定的steps来进行新增，那就设置好step。

**Comment by jahnli** [comment]
Closed due to inactivity. Feel free to reopen if you're still having trouble
