### ISSUE TITLE
UMD 方式下怎么使用@vicons/ionicons5的图标

### ISSUE THREAD

**Issue by netty2019** [tusen-ai/naive-ui#4363]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Chrome(89.0.4389.128)

### System and its version (系统及其版本)
windows

### Node version (Node 版本)
未使用Node

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/layout#inverted.vue

### Reappearance steps (重现步骤)
NA

### Expected results (期望的结果)
NA

### Actual results (实际的结果)
NA

**Comment by faga295** [comment]
看样子`@vicons/ionicons5`并没有提供umd格式的cdn https://www.jsdelivr.com/package/npm/@vicons/ionicons5

**Comment by 07akioni** [comment]
是的，这个没有提供 umd 的打包，太大了
