### ISSUE TITLE
希望对话框等更加易用

### ISSUE THREAD

**Issue by htqx** [tusen-ai/naive-ui#4367]
### This function solves the problem (这个功能解决的问题)
现在要在外层包装一个配置组件，一个功能两个组件来完成（这类组件有4个），实在想不通。大多数又是在代码中使用的东西。
感觉对话框这些东西，可以简化一些，做成一个函数，也不需要什么模板了。提供一个易用的使用界面，简化一下。谢谢。

另外配置的 to 属性，测试了很多遍，也看不出任何差别。。。也没有看到消息框位置发生改变

另外还经常看到一个错误提示：[Vue warn]: Slot "default" invoked outside of the render function: this will not track dependencies used in the slot. Invoke the slot function inside the render function instead

没有任何不敬的意思，感谢你提供的免费组件。
### Expected API (期望的 API)
let message = useMessage({...配置})
message.info("hello")

let dialog = useDialog({..配置.}) 
let d1 = dialog.create({...对话框实例属性})
d1.onPositiveClick = ()=>{确认}
d1.onClose = ()=>{拒绝}
// 希望以下是默认逻辑（不用写）
  d1.onNegativeClick = d1.onClose;
  d1.onMaskClick = d1.onClose;
  d1.onEsc = d1.onClose;

**Comment by jizai1125** [comment]
我看文档中是有块[脱离上下文的 API](https://www.naiveui.com/zh-CN/os-theme/components/discrete)

**Comment by Sepush** [comment]
to 是 message 容器节点的位置 如果你是想改变位置 可以使用 placement 属性

**Comment by 07akioni** [comment]
> 我看文档中是有块[脱离上下文的 API](https://www.naiveui.com/zh-CN/os-theme/components/discrete)，相关 PR #2969

是的，你可以用这个 API。

脱离上下文有脱离上下文的副作用，这个库设计的原则就是一切都是 App 内的东西，所以可会有一些看起来奇怪的 API，是取舍的结果。
