### ISSUE TITLE
Is Naive still maintained or will be maintained in the future

### ISSUE THREAD

**Issue by lowbote** [tusen-ai/naive-ui#4385]
### This function solves the problem (这个功能解决的问题)
I like NaiveU very much, but I'm not sure if it's being maintained or will be maintained in the future, and I've seen NiaveUI on a frequency that hasn't had a feature update in a long time
### Expected API (期望的 API)
I like NaiveU very much, but I'm not sure if it's being maintained or will be maintained in the future, and I've seen NiaveUI on a frequency that hasn't had a feature update in a long time

**Comment by Sepush** [comment]
Absolutely,We will maintain Naive as long as possible.
All maintainers are motivated by interests & love of this lib,at the same time we all have day job to do which sometimes too busy to do something else. 
If you have any feature request or bug report(with reproduction) new issue please.
We will deal with them once we have time. 
love & peace

**Comment by jahnli** [comment]
ref https://github.com/tusen-ai/naive-ui/discussions/5470
