### ISSUE TITLE
希望给datepicker组件增加多选日期功能

### ISSUE THREAD

**Issue by siriusty1** [tusen-ai/naive-ui#4395]
### This function solves the problem (这个功能解决的问题)
目前datepicker只能单选日期，或选择一个连续的日期范围，能否添加一个自由多选日期的模式
### Expected API (期望的 API)
类似elementUI的type=dates

**Comment by herofqy** [comment]
+1

**Comment by Jiadz** [comment]
+1

**Comment by firmianaQ** [comment]
+1

**Comment by jahnli** [comment]
https://github.com/tusen-ai/naive-ui/issues/3357  duplicate
