### ISSUE TITLE
Select doesn't support size prop

### ISSUE THREAD

**Issue by ksddesigner** [tusen-ai/naive-ui#4398]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Версия 109.0.5414.87

### System and its version (系统及其版本)
MacOS (13.1 (22C65))

### Reappearance link (重现链接)
https://codesandbox.io/s/interesting-feather-g1vmty

### Reappearance steps (重现步骤)
If we change the default tiny, small and large size theme values, only the font size in the field and its height will change, but it doesn't work with padding like for input, or with font size in the select dropdown.

### Expected results (期望的结果)
It will be great if theme value will be apply for all form components to be consistent when it used in one form with one size.

### Actual results (实际的结果)
Now select look different in form

**Comment by 07akioni** [comment]
Select doesn't support size `tiny` by design. It's too small for a form component.

**Comment by 07akioni** [comment]
Also dropdown's size is consistent by design. Since it should have same behavior like date-picker.

**Comment by lamka02sk** [comment]
I just came across this issue when trying to create compact UI. `size="tiny"` is actually supported, it is just not included in supported size values, so it throws TS error.
Pretty much all those elements look OK with `size="tiny"` so I don't think the argument of form components being too small is valid. 
This limitation just makes life harder. For anyone fighting this bug, you can use `<!-- @vue-ignore -->` in your Vue template.
