### ISSUE TITLE
DataTable selection filtered rows

### ISSUE THREAD

**Issue by woedux** [tusen-ai/naive-ui#4399]
### This function solves the problem (这个功能解决的问题)
DataTable column type "selection" has options param which can check or uncheck row from ALL table, and you can create your own selection method on single active page.
But there's no way how to check filtered rows from all rest pages by an "selection" option.
Ofcourse it can be resolved by filtering "data" without  DataTable API, but if this native filters support exists why not extend it?
### Expected API (期望的 API)
Make DataTable API return filtered rows/keys

**Comment by sashaj** [comment]
+

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by fyyyyy** [comment]
Yes, this would be very useful. Selecting all source data makes no sense for any usecase I can think of. By default 'all' should only select the filtered table data.
