### ISSUE TITLE
Input Mask

### ISSUE THREAD

**Issue by brunotourinho** [tusen-ai/naive-ui#4407]
### This function solves the problem (这个功能解决的问题)
Mask text inside inputs. Like Date `__/__/____` or Currency `US$ 150.00`. 
### Expected API (期望的 API)
I was thinking about something like the classic inputmask.js from https://github.com/RobinHerbots/Inputmask which allows creating custom masks.
The current input could get a mask prop like `<n-input v-model:value="value" type="text" mask="(999) 999-9999" />`

**Comment by 07akioni** [comment]
dup of https://github.com/tusen-ai/naive-ui/issues/1385
