### ISSUE TITLE
轮播图支持其他标签如div等

### ISSUE THREAD

**Issue by liu-xinhui** [tusen-ai/naive-ui#4409]
### This function solves the problem (这个功能解决的问题)
轮播echarts图表
### Expected API (期望的 API)
```  html
<n-carousel>
    <div style="background-color:red;width:100px;height:100px">1234</div>
    <img
      class="carousel-img"
      src="https://naive-ui.oss-cn-beijing.aliyuncs.com/carousel-img/carousel2.jpeg"
    >
  </n-carousel>
```

**Comment by 07akioni** [comment]
套一层这个
<img width="456" alt="image" src="https://user-images.githubusercontent.com/18677354/216801037-c20661c0-d00c-45d9-bd88-8bf215ad53a3.png">
