### ISSUE TITLE
Safari浏览器下的图标按钮存在bug

### ISSUE THREAD

**Issue by GabbyMrH** [tusen-ai/naive-ui#4415]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Safari6.2 (18614.3.7.1.5)

### System and its version (系统及其版本)
MacOS(13.1)

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/button#icon.vue

### Reappearance steps (重现步骤)
1、在safari浏览器打开官网示例->找到按钮组件->找到图标按钮；
2、即可看到本应在按钮左侧显示的图标未能正常显示。

### Expected results (期望的结果)
希望能正常显示图标按钮

### Actual results (实际的结果)
未达到期望值

### Remarks (补充说明)

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/30254530/215324687-05e482a4-de04-44d2-a1b2-b8ea18087903.png">

**Comment by GabbyMrH** [comment]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/30254530/215324642-e5b66b65-800c-4611-90f3-381aa48358bb.png">

**Comment by 07akioni** [comment]
文档 demo 有点问题
