### ISSUE TITLE
datatable的过滤功能

### ISSUE THREAD

**Issue by easyboot** [tusen-ai/naive-ui#4417]
### This function solves the problem (这个功能解决的问题)
当我展示新的查询结果时，我需要对”患者姓名”进行过滤。
我使用filterOptions: FilterPatinetName功能
我遍历整个表对FilterPatinetName进行填充
但是我发现当点击 “过滤" 按钮时，下拉弹框速度很慢。我改如何改善

另外 我如何获取过滤后的结果集。
谢谢

### Expected API (期望的 API)
filterOptions

**Comment by 07akioni** [comment]
dup of https://github.com/tusen-ai/naive-ui/issues/4418
