### ISSUE TITLE
数据表格 Data Table 的过滤功能

### ISSUE THREAD

**Issue by easyboot** [tusen-ai/naive-ui#4418]
### This function solves the problem (这个功能解决的问题)
我希望使用 ”数据表格 Data Table” 实现一些功能
当我展示新的查询结果集时，我需要对”患者姓名”进行过滤。
我使用filterOptions: FilterPatinetName功能
我遍历整个表对FilterPatinetName进行填充
但是我发现点击 “过滤" 按钮时，下拉弹框速度很慢。

我改如何改善

另外 我如何获取过滤后的结果集。
谢谢

### Expected API (期望的 API)
filterOptions

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
