### ISSUE TITLE
Highlight selected/expanded row

### ISSUE THREAD

**Issue by shaniqwa** [tusen-ai/naive-ui#4420]
### This function solves the problem (这个功能解决的问题)
Hi there, so far this library is awesome! 
I would like to know if there is a way to simply set a class to rows when they are selected or in expanded ? (the expanded row   the newly added row)

This is a very common use case where you might want to highlight a row for any reason. of course it makes the UX better when you can highlight what you want to focus on (similar to when you use stripes mode for a table, makes it more readable)

Thanks a lot
Shani
### Expected API (期望的 API)
set a class to  expanded <tr>´expanded’. 
it would be great to control it with the theme config provider. for example add a these properties to the DataTable: "selectedRowColor", "expandedRowColor", "expandedRowContentColor"

**Comment by shaniqwa** [comment]
Opened a PR adding a class to expanded rows: https://github.com/tusen-ai/naive-ui/pull/4426

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
