### ISSUE TITLE
Each Radio Button with Tooltip 为单选各项添加提示

### ISSUE THREAD

**Issue by darwintree** [tusen-ai/naive-ui#4421]
### This function solves the problem (这个功能解决的问题)
当前无法通过将 NRadioButton 外添加 NTooltip 的方式为各个NRadioButton添加不同的tooltip，相应报错：
```
`n-radio-group` in button mode only takes `n-radio-button` as children.
```
### Expected API (期望的 API)
1. NRadioGroup支持解析位于slot中的NRadioButton
2. 或 NRadioButton 添加tooltip等属性，直接渲染

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
