### ISSUE TITLE
add icon inside n-radio-button 希望單選按鈕能夠增加icon顯示

### ISSUE THREAD

**Issue by UTing1119** [tusen-ai/naive-ui#4430]
### This function solves the problem (这个功能解决的问题)
button group can do that but it cannot be checked like a radio button.
n-radio-button cannot put icon inside.

![image](https://user-images.githubusercontent.com/74576629/215990300-5848fb09-d457-4c71-b20d-1684287e127d.png)

### Expected API (期望的 API)
```
<n-radio-group v-model:value="show_grid_or_list" name="radiobuttongroup1">
  <n-radio-button
      value="grid"
      label="方格">
    <template #icon>
      <n-icon>
        <gridOutline />
      </n-icon>
    </template>
  </n-radio-button>
  <n-radio-button
    value="list"
    label="清單">
     <template #icon>
      <n-icon>
        <listOutline />
      </n-icon>
    </template>
  </n-radio-button>
</n-radio-group>
```

**Comment by zhangjiajia123** [comment]
This way of writing can solve your problem

**Comment by zhangjiajia123** [comment]
This way of writing can solve your problem
![image](https://github.com/tusen-ai/naive-ui/assets/48313333/211a2ab4-e36e-4e7f-b7f3-ac2697f880a0)
![image](https://github.com/tusen-ai/naive-ui/assets/48313333/788d0a8a-50cf-487b-9f83-c7f6558b183c)

**Comment by zhangjiajia123** [comment]
This way of writing can solve your problem
      
<n-radio-group v-model:value="value" name="radiobuttongroup1" style="height: 34px;">
  <n-radio-button
    v-for="tab in tabs"
    :key="tab.value"
    :value="tab.value"
    :label="tab.label"
  >
    <template #default>
      <n-icon style="margin-right: 5px;"><cash-icon /></n-icon>{{ tab.label }}
    </template>
  </n-radio-button>
</n-radio-group>

**Comment by zhangjiajia123** [comment]
> This way of writing can solve your problem
      
  <n-radio-group v-model:value="value" name="radiobuttongroup1" style="height: 34px;">
    <n-radio-button
      v-for="tab in tabs"
      :key="tab.value"
      :value="tab.value"
      :label="tab.label"
    >
      <template #default>
        <n-icon style="margin-right: 5px;"><cash-icon /></n-icon>{{ tab.label }}
      </template>
    </n-radio-button>
  </n-radio-group>

**Comment by zhangjiajia123** [comment]
### This way of writing can solve your problem
`<n-radio-group v-model:value="value" name="radiobuttongroup1" style="height: 34px;">
        <n-radio-button
          v-for="tab in tabs"
          :key="tab.value"
          :value="tab.value"
          :label="tab.label"
        >
          <template #default>
            <n-icon style="margin-right: 5px;"><cash-icon /></n-icon>{{ tab.label }}
          </template>
        </n-radio-button>
      </n-radio-group>`

**Comment by zhangjiajia123** [comment]
### This way of writing can solve your problem
`
<n-radio-group v-model:value="value" name="radiobuttongroup1" style="height: 34px;">
    <n-radio-button
      v-for="tab in tabs"
      :key="tab.value"
      :value="tab.value"
      :label="tab.label"
    >
      <template #default>
        <n-icon style="margin-right: 5px;"><cash-icon /></n-icon>{{ tab.label }}
      </template>
    </n-radio-button>
  </n-radio-group>
`
![image](https://github.com/tusen-ai/naive-ui/assets/48313333/55b9aeeb-9b88-48f9-bc00-ff6ccb29fad6)

**Comment by zhangjiajia123** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/48313333/b2f49a87-70e8-4e9a-ae34-8c142e2bdd40)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
