### ISSUE TITLE
将代码中的使用`VNodeChild`类型的地方增加`JSX.Element`类型

### ISSUE THREAD

**Issue by AC-0308** [tusen-ai/naive-ui#4437]
### This function solves the problem (这个功能解决的问题)
解决需要自定义渲染的地方能够使用TSX的方式而不仅仅是h函数。
### Expected API (期望的 API)
interface DataTableColumn {
    render?: <T = InternalRowData>(rowData: T, rowIndex: number) => JSX.Element | VNodeChild | string;
  }

**Comment by 07akioni** [comment]
这两个类型是兼容的，可能是你的 ts 配置存在一些问题

<img width="379" alt="image" src="https://user-images.githubusercontent.com/18677354/216800748-767b8ce4-865d-43cc-bcd0-5ada44a7406d.png">
