### ISSUE TITLE
input count-graphemes组件文档出现错别字，是字数计数，不是字素计数。

### ISSUE THREAD

**Issue by colesse** [tusen-ai/naive-ui#4438]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.47

### Browser and its version (浏览器及其版本)
108.0.5359.98

### System and its version (系统及其版本)
0.15.7

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/input#graphemes.vue

### Reappearance steps (重现步骤)
打开文档https://www.naiveui.com/zh-CN/os-theme/components/input#graphemes.vue

### Expected results (期望的结果)
字数计数

### Actual results (实际的结果)
字素计数

**Comment by jahnli** [comment]
ref https://github.com/tusen-ai/naive-ui/pull/4177

**Comment by colesse** [comment]
> ref #4177

读书少，丢人了。
