### ISSUE TITLE
数据表格 Data Table的树形数据展开开关的图标能否像树形组件那样自定义

### ISSUE THREAD

**Issue by maddenBoy** [tusen-ai/naive-ui#4439]
### This function solves the problem (这个功能解决的问题)
目前render-expand-icon无法做到展开折叠显示不同的图标，希望可以像树形组件那样通过render-switcher-icon去自定义展开折叠的图标
### Expected API (期望的 API)
1、render-switcher-icon    (props: { expanded: boolean, selected: boolean }) => VNodeChild
2、或者render-expand-icon   (props: { expanded: boolean, selected: boolean }) => VNodeChild

**Comment by zhaoyuanmeng** [comment]
请问这个问题可以了吗 我看文档还是没有更新这个
