### ISSUE TITLE
如何监听表单验证是否全部通过？

### ISSUE THREAD

**Issue by terranc** [tusen-ai/naive-ui#4443]
### This function solves the problem (这个功能解决的问题)
比如提交按钮在表单验证通过前是disabled状态，在填写通过验证后，按钮马上切换成可点击状态。
类似这样的场景，应该怎么去判断？
### Expected API (期望的 API)
是否ref对象能有个属性可以直接判断？或能提供事件监听。

**Comment by ice-fortress** [comment]
[naive ui 表单校验](https://www.naiveui.com/zh-CN/os-theme/components/form#Form-Methods)，官网好像有这个API，你看看是否满足你的需求，通过ref可以调用
![image](https://user-images.githubusercontent.com/45136949/216864035-19951b3c-69d6-474e-88e5-a466b5e6fcf1.png)

**Comment by terranc** [comment]
@ice-fortress validate是验证表单，是去触发验证的，一来在触发后输入框会变红，在初始化的时候肯定不想看到；二来，这个方法在表单没错的时候可以通过ayns&await能返回成功，但如果有失败的，会直接报异常，还得去try...catch，反正感觉这方法不是做我这个用途的

**Comment by AndSpark** [comment]
可以直接使用async-validator来做校验，这是跟ui没有关系的，通过后再用表单校验

**Comment by terranc** [comment]
@AndSpark 想请教如题的业务需求要怎么实现呢？并不是和UI有什么关系，而是没找到合适的事件

**Comment by liuzw2579** [comment]
> 可以直接使用async-validator来做校验，这是跟ui没有关系的，通过后再用表单校验

可能有些异步调用api服务校验的规则，这样做会执行多次

**Comment by jahnli** [comment]
Closed due to inactivity. Feel free to reopen if you're still having trouble
