### ISSUE TITLE
新增 `Nuxt3` modules

### ISSUE THREAD

**Issue by evanlong0803** [tusen-ai/naive-ui#4446]
### This function solves the problem (这个功能解决的问题)
1. 更好的兼容 `Nuxt3` ❤️
2. 更好的解锁流量密码 🙌
### Expected API (期望的 API)
我希望 `naive-ui` 能和官方提供的规范案例新增一个 `@naive-ui/nuxt` 的 [module](https://nuxt.com/modules)

[案例 element-plus-nuxt](https://github.com/element-plus/element-plus-nuxt)

https://nuxt.com/modules/element-plus

**Comment by ccitsxy** [comment]
There's an existing one. [naive-ui-nuxt](https://github.com/huntersofbook/huntersofbook/tree/main/projects/naive-ui-nuxt)

**Comment by evanlong0926** [comment]
> There's an existing one. [naive-ui-nuxt](https://github.com/huntersofbook/huntersofbook/tree/main/projects/naive-ui-nuxt)

Thank you.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
