### ISSUE TITLE
Upload console warning: [Vue warn]: Extraneous non-props attributes (mode) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.    at <TransitionGroup name="fade-in-height-expand-transition" mode=undefined appear=false  ... >

### ISSUE THREAD

**Issue by M1CK431** [tusen-ai/naive-ui#4447]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.47

### Browser and its version (浏览器及其版本)
Vivaldi 5.6.2867.62

### System and its version (系统及其版本)
Archlinux

### Node version (Node 版本)
19.6.0

### Reappearance link (重现链接)
https://www.naiveui.com/en-US/light/components/upload

### Reappearance steps (重现步骤)
Use NUpload component this way:
```html
  <NUpload
    @beforeUpload="handleUpload($event.file)"
    accept="text/html"
    trigger-style="height: 100%"
  />
```

### Expected results (期望的结果)
No warning in browser console

### Actual results (实际的结果)
```
[Vue warn]: Extraneous non-props attributes (mode) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
  at <TransitionGroup name="fade-in-height-expand-transition" mode=undefined appear=false  ... > 
  at <FadeInExpandTransition group=true > 
  at <UploadFileList> 
  at <Upload onBeforeUpload=fn accept="text/html" trigger-style="height: 100%"  ... >
```

### Remarks (补充说明)
This is a minor issue which could be easily workaround from user side using `:show-file-list="false"` prop.

**Comment by lhf6623** [comment]
俺也遇到了
![image](https://user-images.githubusercontent.com/29174474/217461910-987cc086-6c89-48a2-b129-d46cffeaef1f.png)

**Comment by eastecho** [comment]
Same here, after upgraded Vue from 3.2.31 to 3.2.47 .

**Comment by recallwei** [comment]
+1

**Comment by lnzhangsong** [comment]
+1

**Comment by vshepel** [comment]
+1

**Comment by wanjinzhong** [comment]
+1. And when to fix?

**Comment by zhangchenna** [comment]
+1

**Comment by hi-reeve** [comment]
+1

**Comment by franck-lynn** [comment]
+1

**Comment by turulix** [comment]
+1

**Comment by wangwang93517** [comment]
+1

**Comment by mazhewei** [comment]
+1

**Comment by hanpandeng** [comment]
我看这个问题已经在2月14号修复了，但是怎么样才能更新到本地项目里呢？
![image](https://user-images.githubusercontent.com/41031240/226135212-595358db-1a76-4280-861a-fc34352a1257.png)

**Comment by M1CK431** [comment]
@hanpandeng Since this PR is still open (not merged) you will have to wait for a merge then a release. After that, `yarn upgrade` will be enough.

In the meantime, use `:show-file-list="false"` prop as a workaround (if you are not using the file list feature, ofc).

**Comment by hanpandeng** [comment]
> @hanpandeng Since this PR is still open (not merged) you will have to wait for a merge then a release. After that, `yarn upgrade` will be enough.
> 
> In the meantime, use `:show-file-list="false"` prop as a workaround (if you are not using the file list feature, ofc).

thanks

**Comment by hanpandeng** [comment]
> @hanpandeng Since this PR is still open (not merged) you will have to wait for a merge then a release. After that, `yarn upgrade` will be enough.
> 
> In the meantime, use `:show-file-list="false"` prop as a workaround (if you are not using the file list feature, ofc).

But I need to use the file list feature

**Comment by myccy123** [comment]
如果设置list-type="image-card" ， 则这个警告就不会出现。。。

**Comment by umang-gramener** [comment]
Any Updates on this issue yet? I am facing the same issue and I want to show file list
