### ISSUE TITLE
Skeleton attribute for indicate the loading state of data in every component

### ISSUE THREAD

**Issue by rifkiard** [tusen-ai/naive-ui#4452]
### This function solves the problem (这个功能解决的问题)
Can we have the "skeleton" attribute in every component? I found it requires us to work twice just for creating a page that has skeleton components in it, we need to create same skeleton size for every components and make an if-else statement for it.
### Expected API (期望的 API)
We can create a "skeleton" attribute in every naive-UI component. We include an if-else statement in it, to determine whether we need to render the actual component or its skeleton with the same style as its actual component at that time.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
