### ISSUE TITLE
"node_modules/naive-ui/es/upload/src/interface.d.ts(125,12): error TS2304: Cannot find name 'FileSystemFileEntry'."

### ISSUE THREAD

**Issue by z1047549075** [tusen-ai/naive-ui#4453]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.1.5

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
window 10

### Reappearance link (重现链接)
https://github.com/tusen-ai/naive-ui/blob/main/src/upload/src/interface.ts

### Reappearance steps (重现步骤)
1.vue-tsc --noEmit && vite build
2.catch error node_modules/naive-ui/es/upload/src/interface.d.ts(125,12): error TS2304: Cannot find name 'FileSystemFileEntry'. can not continue

### Expected results (期望的结果)
vue-tsc --noEmit && vite build
 can be successful

### Actual results (实际的结果)
Can not find name 'FileSystemFileEntry'. can not continue

### Remarks (补充说明)
i am try to update typescript version to 4.9.5, but it is not use

**Comment by jizai1125** [comment]
You may need to import 'dom' in the 'compileOptions' of tsconfig.json.

**Comment by z1047549075** [comment]
> compileOptions

> You may need to import 'dom' in the 'compileOptions' of tsconfig.json.

hello.thx your reply very much,it is my tsconfig.json

{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "lib": ["esnext", "dom"],
    "types": ["vite/client"],
    "paths": {
      "@/*": ["./src/*"]
    }
  },

  "include": [
    "src/**/*.ts",
    "src/**/*.d.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "src/public/lang/en.ts",
    "src/public/lang/zh.ts"
  ]
}


do you mean it is in the 'lib'?it is not  work....- -

**Comment by jahnli** [comment]
Closed due to inactivity. Feel free to reopen if you're still having trouble
