### ISSUE TITLE
input组件禁用后点击会触发校验

### ISSUE THREAD

**Issue by zz541843** [tusen-ai/naive-ui#4454]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-alpha.4

### Reappearance steps (重现步骤)
input组件禁用后，点击一下，虽然看上去没有获取焦点，其实已经获取了，其他地方再点一下，就失去焦点了，就会触发校验

### Expected results (期望的结果)
所有的form组件，dissabled后点击不获取焦点就行了

**Comment by amadeus711** [comment]
Record: Maybe the same problem as #4465

**Comment by zz541843** [comment]
> ~Record: Maybe the same problem as #4465~
> 
> https://codesandbox.io/s/d0jly4?file=/src/Demo.vue
> 
> 我在 codesandbox 按你的描述没有复现出来

https://codesandbox.io/s/quirky-glade-b0eck4?file=/src/Demo.vue 
我做了修改了，加了filterable就会出现该问题

**Comment by zz541843** [comment]
虽然可能感觉怪怪，明明一个disabled的还要加filterable干嘛呢，就是这个业务很复杂，很多状态，表单形式都不一样，都加了filterable
