### ISSUE TITLE
select 组件虚拟滚动 数据错误

### ISSUE THREAD

**Issue by moyukingS** [tusen-ai/naive-ui#4456]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.47

### Browser and its version (浏览器及其版本)
Microsoft Edge 版本 109.0.1518.78 (正式版本) (64 位)

### System and its version (系统及其版本)
win 11

### Node version (Node 版本)
16 lts

### Reappearance link (重现链接)
https://codepen.io/moyukingS/pen/XWBwjzv

### Reappearance steps (重现步骤)
上下滚动select组件

### Expected results (期望的结果)
数据正常

### Actual results (实际的结果)
数据重复出现

### Remarks (补充说明)
国际电话区号选择，加拿大和美国相同,上下滚动选择错误

**Comment by amadeus711** [comment]
主要还是数据中 value 重复造成的

**Comment by moyukingS** [comment]
我改两个value的数据类型就行了 ,还好这个业务场景只有两个相同的区号，多几个就只能关闭虚拟滚动了

**Comment by moyukingS** [comment]
> 主要还是数据中 value 重复造成的

我改两个value的数据类型就行了 ，还好这个业务场景只有两个相同的区号，多几个就只能关闭虚拟滚动了
