### ISSUE TITLE
show password icon can not handle touch event

### ISSUE THREAD

**Issue by judgeou** [tusen-ai/naive-ui#4457]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
107.0.5304.105

### System and its version (系统及其版本)
Android 12

### Node version (Node 版本)
16.18.1

### Reappearance link (重现链接)
https://codesandbox.io/s/naive-ui-password-show-hmfmrl?file=/src/App.vue

### Reappearance steps (重现步骤)
1. input something to input
2. touch the show icon

### Expected results (期望的结果)
the password show

### Actual results (实际的结果)
the password not show

### Remarks (补充说明)
open chrome devtools, toggle mobile device mode, problem can be reproduce

**Comment by faga295** [comment]
Maybe showpasswordon property should add `touchstart` option.

**Comment by OnlyWick** [comment]
`show-password-on="click"`

**Comment by faga295** [comment]
In mobile device, it trigger `touchstart` instead of `mousedown`

**Comment by judgeou** [comment]
> In mobile device, it trigger `touchstart` instead of `mousedown`

but `show-password-on` only accept `click` or `mousedown`

**Comment by judgeou** [comment]
> `show-password-on="click"`

`click` work, although not the way I thought
