### ISSUE TITLE
Select 选择器  

### ISSUE THREAD

**Issue by PZ-18664918826** [tusen-ai/naive-ui#4458]
### This function solves the problem (这个功能解决的问题)
Select: 希望能增加prefix插槽

### Expected API (期望的 API)
可以是插槽 也可以是渲染函数

**Comment by PZ-18664918826** [comment]
Tree Select：希望key是可以重复的，不需要报警告，选中哪个选项就显示哪个选项，其他key一样的默认选中。有时候业务会存在这样的情况，比如一个人可以在多个部门，而这个人id是一样的。
key一样还会产生滚动bug

https://user-images.githubusercontent.com/64340432/217699937-f14211a9-1a62-49f0-b142-8c4798a784be.mp4

**Comment by amadeus711** [comment]
> Tree Select：希望key是可以重复的，不需要报警告，选中哪个选项就显示哪个选项，其他key一样的默认选中。有时候业务会存在这样的情况，比如一个人可以在多个部门，而这个人id是一样的。 key一样还会产生滚动bug
> 
>  20230209_100857.mp4

这种属于极个例，所以暂不考虑。

**Comment by amadeus711** [comment]
> 

![image](https://user-images.githubusercontent.com/46394163/217703383-79e11a92-6dab-44d4-b955-02a817f5e8d8.png)

**Comment by PZ-18664918826** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/46394163/217703383-79e11a92-6dab-44d4-b955-02a817f5e8d8.png) 已经有渲染函数了

我想要这种效果 哪个只是下拉选项 和选中的渲染函数，我想要输入框的前缀

**Comment by Nakus0426** [comment]
你可能需要 `<n-input-group>`

**Comment by flower-dc** [comment]
> Tree Select：希望key是可以重复的，不需要报警告，选中哪个选项就显示哪个选项，其他key一样的默认选中。有时候业务会存在这样的情况，比如一个人可以在多个部门，而这个人id是一样的。 key一样还会产生滚动bug

重复key的问题你可以手动处理数据，添加唯一key，选择器绑定这个唯一key，提交表单前再通过这个key找回原来的id提交

**Comment by Zlinni** [comment]
> > > 
> > 
> > 
> > ![图像](https://user-images.githubusercontent.com/46394163/217703383-79e11a92-6dab-44d4-b955-02a817f5e8d8.png) 已经有渲染函数了
> 
> 哪个只是下拉选项 和选中的渲染函数，我想要输入框的前缀 类似于输入框的前缀插槽 放图标用的

你可以通过对renderOption暴露出来的node进行操作来完成你的效果，
比如想把icon变成prefix 可以把node.children中的元素进行一次reverse，甚至可以pop之后unshift你自己的icon
![image](https://user-images.githubusercontent.com/78781776/219529869-cc92ce63-76b2-461d-8e2a-88c850ca0110.png)

**Comment by zhoukingzz** [comment]
> > > > 
> > > 
> > > 
> > > ![图像](https://user-images.githubusercontent.com/46394163/217703383-79e11a92-6dab-44d4-b955-02a817f5e8d8.png) 已经有渲染函数了
> > 
> > 
> > 哪个只是下拉选项 和选中的渲染函数，我想要输入框的前缀 类似于输入框的前缀插槽 放图标用的
> 
> 你可以通过对renderOption暴露出来的node进行操作来完成你的效果， 比如想把icon变成prefix 可以把node.children中的元素进行一次reverse，甚至可以pop之后unshift你自己的icon ![image](https://user-images.githubusercontent.com/78781776/219529869-cc92ce63-76b2-461d-8e2a-88c850ca0110.png)
请问是不是无法在暴露出来的node中获取到el对象啊
![image](https://github.com/tusen-ai/naive-ui/assets/53244153/934cab9c-edcc-4e82-843c-2078a4268043)
![image](https://github.com/tusen-ai/naive-ui/assets/53244153/f62bd643-fbf0-4928-afbf-c122afbd5fd9)

**Comment by zhoukingzz** [comment]
在使用select的时候会遇到options中的选项内容过多，超出宽度被省略为...，现在我要给内容过多导致出现...的选项添加Tooltip，非所有选项都加，应该合理吧，请问有什么好办法吗？

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
