### ISSUE TITLE
[DatePicker]日期选择器交互优化

### ISSUE THREAD

**Issue by pengzhen-developer** [tusen-ai/naive-ui#4462]
### This function solves the problem (这个功能解决的问题)
当用户修改日期时，通常有明确预期，是否考虑当完成年/月的点击后，关闭弹框，较少交互次数？

官网例子：

https://user-images.githubusercontent.com/12759499/217753580-c98341d0-e1da-46c9-84dc-1c3c9e0abc16.mov

个人觉得较好的交互例子：

https://user-images.githubusercontent.com/12759499/217753613-21e77878-d81f-4345-8ca5-54c76a9ab956.mov

### Expected API (期望的 API)
无

**Comment by DanielSimgame** [comment]
datetimerange的类型也有类似的需求，是否有实现省略点击确认即更新数据的方法？

**Comment by liuzw2579** [comment]
> datetimerange的类型也有类似的需求，是否有实现省略点击确认即更新数据的方法？

我记得有个 updateValueOnClose 的prop
![图片](https://user-images.githubusercontent.com/30503937/219281482-e196bbbf-80d2-423e-8ed7-c6444e6544ba.png)

**Comment by pengzhen-developer** [comment]
重复问题：https://github.com/tusen-ai/naive-ui/issues/3615
