### ISSUE TITLE
建议新增一个api使得折叠面板的箭头可以放在最右边

### ISSUE THREAD

**Issue by b1ues** [tusen-ai/naive-ui#4463]
### This function solves the problem (这个功能解决的问题)
功能需求
### Expected API (期望的 API)
arrow-placement新增一个value

**Comment by Innei** [comment]
> ### This function solves the problem (这个功能解决的问题)
> 功能需求
> 
> ### Expected API (期望的 API)
> arrow-placement新增一个value

可以使用 #arrow slot 解决你的问题
