### ISSUE TITLE
Imperative handle of input component

### ISSUE THREAD

**Issue by GILREICH1** [tusen-ai/naive-ui#4465]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
109.0.5414.120

### System and its version (系统及其版本)
Windows 10 Home

### Node version (Node 版本)
v18.13.0

### Reappearance link (重现链接)
https://github.com/GILREICH1/bali-bot-client/blob/main/src/views/HomeView.vue

### Reappearance steps (重现步骤)
type into input. press enter to submit.

### Expected results (期望的结果)
input should be focussed 

### Actual results (实际的结果)
input not focussed.

### Remarks (补充说明)
Trying to imperative focus on input element. handleFocus() function runs but inputInstRef.value?.focus() does not focus input. Using template from here: https://www.naiveui.com/en-US/light/components/input#focus.vue

**Comment by amadeus711** [comment]
Record: Maybe the same problem as #4454

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
