### ISSUE TITLE
弹出选择Popselect、Select组件选择选项时是否支持填充背景色勾选

### ISSUE THREAD

**Issue by maddenBoy** [tusen-ai/naive-ui#4468]
### This function solves the problem (这个功能解决的问题)
弹出选择Popselect选择选项时支持填充背景色勾选

**类似下图这种**

![image](https://user-images.githubusercontent.com/71129660/218010295-de811474-40b9-4139-8d52-849b6feb4bfd.png)

### Expected API (期望的 API)
增加个type类型？或者提供可以让用户设置选项选项勾选和未勾选时样式的API

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
