### ISSUE TITLE
menu inverted 后 hover没背景色

### ISSUE THREAD

**Issue by manyhelp** [tusen-ai/naive-ui#4472]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.47

### Browser and its version (浏览器及其版本)
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/menu

### Reappearance steps (重现步骤)
1.打开 https://www.naiveui.com/zh-CN/light/components/menu
2. 找到 反转  这个示例
3.点击 inverted 按钮

### Expected results (期望的结果)
需要带背景色

### Actual results (实际的结果)
不点击点击 inverted 按钮，下面的 且听风吟 栏目，鼠标移动上去有背景颜色。
点击 inverted 按钮后，没有背景颜色

**Comment by manyhelp** [comment]
table 一行行，鼠标移上去，能加背景颜色吗

**Comment by jizai1125** [comment]
menu 组件 `inverted` 后可以通过调整组件变量 `itemColorHoverInverted` 设置背景色
