### ISSUE TITLE
tooltip、popover组件绑定行内样式后，修改组件内容时会导致页面报错

### ISSUE THREAD

**Issue by maddenBoy** [tusen-ai/naive-ui#4474]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-alpha.4

### Browser and its version (浏览器及其版本)
Chrome（109.0.5414.121）

### System and its version (系统及其版本)
window11

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/popover

### Reappearance steps (重现步骤)
1、运行naive-ui源码项目，打开源码中tooltip组件下的basic.demo.vue文件， 给tooltip绑定style，例如 :style="{ background: 'red' }"
2、保存文件
3、修改组件中的任意文字，保存文件后页面报错，此时若点击按钮，无法弹出弹窗

### Expected results (期望的结果)
给tooltip、popover绑定style，vite热更新后浏览器无报错信息

### Actual results (实际的结果)
给tooltip、popover绑定style，vite热更新后浏览器存在报错信息，且之后不刷新页面无法热更新

### Remarks (补充说明)

**文件截图**

![image](https://user-images.githubusercontent.com/71129660/218085652-15127eed-5a68-4627-a2ef-fa86d9efe6ba.png)

浏览器报错截图

![image](https://user-images.githubusercontent.com/71129660/218085362-6989bb6a-8f14-4f7b-93a7-3cbfb6702a4e.png)

**Comment by Sepush** [comment]
![image](https://user-images.githubusercontent.com/39197136/218091210-e8adcf26-96e6-43b6-840a-427f4d87c61d.png)

**Comment by ctrl-zero** [comment]
这个问题没有解决方案么

**Comment by maddenBoy** [comment]
似乎没有人解决，不知道是vite的bug，还是组件写法导致

**Comment by ctrl-zero** [comment]
我这也是这个问题 在popover里的trigger slot内 用vue写的组件就会报错 用原生的html标签没问题
