### ISSUE TITLE
日期时间系列选择器格式特性

### ISSUE THREAD

**Issue by alaywn** [tusen-ai/naive-ui#4475]
### This function solves the problem (这个功能解决的问题)
以日期选择器为例（其他相关系列选择器同理）：实际应用中，用户往往会直接在输入框中直接修改日期，这样比较快速省事。但是。目前这个组件支持识别处理的格式受限于format属性（默认值为yyyy-MM-dd）,这样会强制用户必须输入严格的format属性指定的格式才能被识别。
### Expected API (期望的 API)
建议将format属性添加数组格式支持，比如:format="['yyyy-MM-dd','yyyy-M-d']"，此时用户无论输入2023-02-01还是2023-2-1都可以被正确识别并处理

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
