### ISSUE TITLE
DataTable：列宽拖动和列固定时的渲染问题（column resize and fixed right render bug）

### ISSUE THREAD

**Issue by liuzw2579** [tusen-ai/naive-ui#4476]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.47

### Browser and its version (浏览器及其版本)
Microsoft Edge 110.0.1587.41

### System and its version (系统及其版本)
Windows 11

### Reappearance link (重现链接)
https://codepen.io/liuzw2579/pen/VwBogBb

### Reappearance steps (重现步骤)
表格列横向滚动，假定存在4列且均设置width，第1列 fixed: left，第2列列宽可拖动，第4列 fixed: right
```html
<script src="https://unpkg.com/vue"></script>
<script src="https://unpkg.com/naive-ui"></script>

<div id="app">
      当存在 fixed: right， 设定 scrollX 时, 第二列 resize 加宽会导致 第三列 裁剪
      <n-data-table :columns="cols" :data="data" :scroll-x="scrollX" style="width: 550px"></n-data-table>
  
      当存在 fixed: right， 而不设定 scrollX 时,  第二列 resize 正常，但 fixed: right 的列没有浮动阴影
      <br />// 若不设置第三列的宽度，此表格无横向滚动
      <n-data-table :columns="cols" :data="data" style="width: 550px"></n-data-table>
  
      同上，但若 data-table 父元素未设置 width 时 无法横向滚动
      <div style="width: 550px; overflow: hidden; display: flex;">
          <div style="flex: 1 1 auto">
            <n-data-table :columns="cols" :data="data"></n-data-table>
          </div>
      </div>
</div>
```

```javascript
const App = {
        setup() {
          return {
            scrollX: 600,
            cols: [
              { title: '第一列', key: 'c1', width: 150, fixed: 'left' },
              { title: '第二列', key: 'c2', width: 150, resizable: true },
              { title: '第三列', key: 'c3', width: 150 },
              { title: '第四列', key: 'c4', width: 150, fixed: 'right' }
            ],
            data: [
              { c1: 'aaa', c2: 'bbb', c3: 'cccccccccccccccc3', c4: 'ddd' },
              { c1: 'aaa', c2: 'bbb', c3: 'cccccccccccccccc3', c4: 'ddd' }
            ]
          }
        }
      }
Vue.createApp(App).use(naive).mount('#app')
```
1、文档提示横向滚动 fixed 需要设定 scrollX，当第2列的列宽往右拖动增大时，第三列会被遮住不可见；
![图片](https://user-images.githubusercontent.com/30503937/218293712-b040cace-b6e5-4e4f-b2ff-985147b5a544.png)

2、若不设置 scrollX，第4列 fixed: right 的左边阴影不见，第一列的右边阴影正常
![图片](https://user-images.githubusercontent.com/30503937/218293670-e669a89a-1cd2-4617-9094-f3cca900223c.png)

### Expected results (期望的结果)
1、设定scrollX时第三列正常可见
2、不需要设定scrollX，fixed: right 的左边阴影正常

### Actual results (实际的结果)
如重现步骤

### Remarks (补充说明)
希望 列拖动时，抛出事件以监听列宽变化，可以更新 绑定的scrollX
或者取消 scrollX 的要求，修复 fixed: right 的左边阴影

**Comment by spanull** [comment]
同楼主，插眼

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by uporot1k** [comment]
Up!
