### ISSUE TITLE
Image组件fallback-src属性不可用

### ISSUE THREAD

**Issue by stand-unshaken** [tusen-ai/naive-ui#4480]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Edge 110.0.1587.41

### System and its version (系统及其版本)
WIN10

### Reappearance link (重现链接)
https://codesandbox.io/s/jmrho9

### Reappearance steps (重现步骤)
所见即所得
https://codesandbox.io/s/jmrho9为官方文档中的链接

### Expected results (期望的结果)
在src不可用时,显示fallback-src的src

### Actual results (实际的结果)
fallback-src的src不显示

### Remarks (补充说明)
naive-ui的2.33.3版本正常，我是因为用到Badge组件的offset属性更新到了2.34.3，发现了这个问题。

**Comment by tower1229** [comment]
这个问题还没修好啊，官网文档的示例都不好使
![image](https://user-images.githubusercontent.com/4016839/228744769-a947636d-a2d8-4d27-907d-10e99c2eb1fb.png)

**Comment by stand-unshaken** [comment]
> 这个问题还没修好啊，官网文档的示例都不好使 ![image](https://user-images.githubusercontent.com/4016839/228744769-a947636d-a2d8-4d27-907d-10e99c2eb1fb.png)

**用2.33.3把**
能看到这个问题已经更新了,但是官方他们还没发新版.
我是因为想用Badge组件的offset属性才从2.33.3升到2.34.3,就发现了这个属性不好使,你也是因为这个的话,可以单独使用Badge组件,并修改position为absolute,再调你想到的位置.

**Comment by stand-unshaken** [comment]
> 这个问题还没修好啊，官网文档的示例都不好使 ![image](https://user-images.githubusercontent.com/4016839/228744769-a947636d-a2d8-4d27-907d-10e99c2eb1fb.png)

**用2.33.3把**
能看到这个问题已经更新了,但是官方他们还没发新版.
我是因为想用Badge组件的offset属性才从2.33.3升到2.34.3,就发现了这个属性不好使,你也是因为这个的话,可以单独使用Badge组件,并修改position为absolute,再调你想到的位置.

**Comment by jeffrey-bin** [comment]
如下代码会导致当lazy属性设置为true时，fallbackSrc还是会失效，这里loading和error冲突吗？
![image](https://github.com/tusen-ai/naive-ui/assets/23428596/24a84be2-fd68-4564-b321-87c9b706ea6c)
