### ISSUE TITLE
能不能加一个在关闭模态框Modal时销毁模态框Modal中元素的功能

### ISSUE THREAD

**Issue by l406054531** [tusen-ai/naive-ui#4481]
### This function solves the problem (这个功能解决的问题)
能销毁元素
### Expected API (期望的 API)
destroy-on-close

**Comment by manyrices** [comment]
n-modal绑定一个v-if ??

**Comment by liuzw2579** [comment]
display-directive: if / show, 话说默认就是if，关闭时销毁

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
