### ISSUE TITLE
穿梭框 Transfer 添加反选功能

### ISSUE THREAD

**Issue by lbc19920615** [tusen-ai/naive-ui#4483]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-alpha.4

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
windows

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/transfer

### Reappearance steps (重现步骤)
穿梭框 Transfer 添加反选功能

### Expected results (期望的结果)
穿梭框 Transfer 添加反选功能

### Actual results (实际的结果)
穿梭框 Transfer 添加反选功能

**Comment by zhengdaonian** [comment]
可能你要的是旧版穿梭框 https://www.naiveui.com/zh-CN/os-theme/components/legacy-transfer

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
