### ISSUE TITLE
只有水平方向的tabs

### ISSUE THREAD

**Issue by CaoJ20132014** [tusen-ai/naive-ui#4489]
### This function solves the problem (这个功能解决的问题)
没有垂直方向的tabs
### Expected API (期望的 API)
tabs新增direction属性，水平方向与垂直方向切换

**Comment by faga295** [comment]
https://github.com/tusen-ai/naive-ui/pull/4295 这个pr合并后将会支持

**Comment by kingwiny** [comment]
这个pr合入了吗
