### ISSUE TITLE
在 Nuxt3 中使用Naive UI, SSR输出的HTML代码里有很多style块，整体HTML代码很大

### ISSUE THREAD

**Issue by tomkluas** [tusen-ai/naive-ui#4490]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-alpha.4

### Browser and its version (浏览器及其版本)
Chrome(89.0.4389.128)

### System and its version (系统及其版本)
windows 10

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme

### Reappearance steps (重现步骤)
nuxt会把naive ui生成的挂载内容最终结果返回给客户端，这样就在header中包含了很多style块，NaiveUI官网就能看到这个效果，header中很多style块

### Expected results (期望的结果)
期望在header中没有style块，把css内容生成到一个或多个css文件中

### Actual results (实际的结果)
header中有很多style块

### Remarks (补充说明)
SSR是在服务端渲染，类似服务端有个浏览器先拿到了页面所有的html（header里面已经有了style块），然后再返回给客户端，这个时候页面就很臃肿，不利于SEO

**Comment by Developer27149** [comment]
非常同意

**Comment by songzhen0207** [comment]
赞同

**Comment by zhonganeng** [comment]
题主解决了没？

**Comment by tomkluas** [comment]
> 题主解决了没？

两种方案，
一种是调整代码，打补丁，在SSR注入时拦截
另一种是换掉这个框架吧，场景不适合

**Comment by XYGR** [comment]
确实，搞不懂的是为什么要把css变量在每个元素上都挂一遍而不是统一放到root节点

**Comment by tomkluas** [comment]
关闭了，请大家在合适的场景下使用
