### ISSUE TITLE
n-date-picker: choose month shown when opening the calendar

### ISSUE THREAD

**Issue by Mutusen** [tusen-ai/naive-ui#4493]
### This function solves the problem (这个功能解决的问题)
I am using the `n-date-picker` component with `type="date"`. When the value is `null` and the user clicks on the field and the calendar opens, it automatically shows the current month. However, I would like to show a specific month instead and I found no way to do this. (Concretely, I would like the user to pick a date in July or August, but we are in February and they have to click "next month" several times.) I tried the `default-value` parameter but it doesn't appear to do anything, at least with `type="date"`.
### Expected API (期望的 API)
A new parameter, e.g. `default-view`:

```vue
<n-date-picker
v-model:value="timestamp"
type="date"
default-view="2023-07-15"
/>
```

So if `timestamp` is `null`, when the user clicks on the field, the calendar automatically shows the month containing the date 2023-07-15.

**Comment by Jonas949** [comment]
Is there a solution now?
