### ISSUE TITLE
Use the 'get' method of lodash-es to get the value of the attribute (labelFieldkeyField/valueField/childrenField/Menu) of TreeSelect, Tree, Select, just like the attribute 'path' of FormItem

### ISSUE THREAD

**Issue by lucio-c** [tusen-ai/naive-ui#4495]
### This function solves the problem (这个功能解决的问题)
Use the 'get' method of lodash-es to get the value of the attribute (labelFieldkeyField/valueField/childrenField/Menu) of TreeSelect, Tree, Select, just like the attribute 'path' of FormItem
### Expected API (期望的 API)
I can submit a PR to modify this if needed

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
