### ISSUE TITLE
n-modal，数据过多时， 内容和操作区超出屏幕

### ISSUE THREAD

**Issue by laterdayi** [tusen-ai/naive-ui#4496]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-alpha.4

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
window

### Reappearance link (重现链接)
https://codesandbox.io/s/xenodochial-frog-kmg3i8?file=/src/Demo.vue

### Reappearance steps (重现步骤)
n-modal，数据过多时， 内容和操作区超出屏幕

### Expected results (期望的结果)
如何能使modal始终距离屏幕上下*px，content内超出的数据内容，在内部滚动

### Actual results (实际的结果)
如何能使modal始终距离屏幕上下*px，content内超出的数据内容，在内部滚动

**Comment by KingCityKe** [comment]
我版本升到2.34.3了 我的modal还是无法滚动 我是modal包裹了一个dataTable dataTable分页选择50/页的时候 modal无法滚动查看数据
<NModal><DataTable/></NModal>

**Comment by KingCityKe** [comment]
这个是有修复吗 当前内容和操作区还是会超出屏幕
