### ISSUE TITLE
How to set the height of subMenu ?

### ISSUE THREAD

**Issue by iaa3906** [tusen-ai/naive-ui#4508]
### This function solves the problem (这个功能解决的问题)
Now, the height of menu items can only be set uniformly through the '-- n-item-height' variable. Can we set the height of the primary menu and the height of the submenu separately as root-indent and indent ? Or what else, such as css?
### Expected API (期望的 API)
Can we have root-item-height and item-height ?

**Comment by jahnli** [comment]
Closed due to inactivity. Feel free to reopen if you're still having trouble
