### ISSUE TITLE
`n-tree-select` can be expanded child options by click their parent options when `check-strategy` is `child`

### ISSUE THREAD

**Issue by WankkoRee** [tusen-ai/naive-ui#4510]
### This function solves the problem (这个功能解决的问题)
if `check-strategy` is `child`, parent options can not be clicked.
I think it's more reasonable behavior that the parent option's click event is used to expand its child options.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
