### ISSUE TITLE
DataTable组件DataTableColumn Properties没有显示在右侧大纲

### ISSUE THREAD

**Issue by zyzweb** [tusen-ai/naive-ui#4512]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-alpha.4

### Browser and its version (浏览器及其版本)
Chrome(109.0.5414.119)

### System and its version (系统及其版本)
MacOS(13.2)

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/data-table#DataTable-Props

### Reappearance steps (重现步骤)
https://www.naiveui.com/zh-CN/os-theme/components/data-table#DataTable-Props
DataTable组件文档DataTableColumn Properties没有显示在右侧大纲是文档错误吗,还是DataTable Props已经包含了DataTableColumn Properties

### Expected results (期望的结果)
右侧大纲栏显示DataTableColumn Properties

### Actual results (实际的结果)
右侧大纲栏没有显示DataTableColumn Properties

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
