### ISSUE TITLE
NDataTable 操作列在数据列之上时，若鼠标在数据列hover则会导致能在操作列看到数据列的全部内容

### ISSUE THREAD

**Issue by DanielSimgame** [tusen-ai/naive-ui#4518]
### TuSimple/naive-ui version (版本)
2.32.2

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Chrome(109.0.0.0, 108.0.0.0)

### System and its version (系统及其版本)
MacOS(13.0, 11.7)

### Node version (Node 版本)
16.14.1

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/data-table

### Reappearance steps (重现步骤)
新建一个<NDataTable>组件并定义其属性 columns 与 actionColumn（columns的列数足够横向滚动，actionColumn至少有一个操作的按钮），组件的pagination == true，autoScrollX == true，tableSetting == { size: false, fullscreen: false, striped: false, setting: false }。此时滑动横向滚动条即出现此问题。

### Expected results (期望的结果)
鼠标移入操作列或与操作列重叠的数据列时，正常显示操作列内容并切隐藏对应操作列内容。
期望修复此问题或得到规避此问题的方法。

### Actual results (实际的结果)
[![2023-02-22-17-41-13.gif](https://i.postimg.cc/pd68bb6c/2023-02-22-17-41-13.gif)](https://postimg.cc/PL1NYch1)
https://i.postimg.cc/pd68bb6c/2023-02-22-17-41-13.gif
See the gif pic above

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
