### ISSUE TITLE
naive UI数字输入框设置精度相关问题

### ISSUE THREAD

**Issue by mycodemanager** [tusen-ai/naive-ui#4520]
2.34.2 版本的数字输入框使用precision（精度属性)会报这个错误:
https://static.dingtalk.com/media/lQLPJxkqtXVGjEjNAmrNAzawMvpNnz24CCQD7-VX4UBzAA_822_618.png_620x10000q90.jpg?auth_bizType=%27IM%27&bizType=im

**Comment by liuzw2579** [comment]
应该绑定 number 值，
