### ISSUE TITLE
数字输入框设置精度相关问题

### ISSUE THREAD

**Issue by mycodemanager** [tusen-ai/naive-ui#4521]
### TuSimple/naive-ui version (版本)
2.34.2

### Vue version (Vue 版本)
3.2.25

### Browser and its version (浏览器及其版本)
Chrome 版本 110.0.5481.100（正式版本）

### System and its version (系统及其版本)
MacOS 12.3

### Reappearance link (重现链接)
https://codesandbox.io/s/bold-wright-1hc2by?file=/src/Demo.vue

### Reappearance steps (重现步骤)
使用precision设置输入小数精度时会报错误：
value.toFixed is not a finction.  
在utils.js文件的31行

### Expected results (期望的结果)
期望可以使用precision属性

### Actual results (实际的结果)
无法使用

### Remarks (补充说明)
重现链接可能无法重现这个错误，但是在本地实实在在的出现这个错误，希望排查一哈，感谢

**Comment by amadeus711** [comment]
已解决，问题原因 value 类型错误
