### ISSUE TITLE
能否在DatePicker的type选项中添加“week”选项

### ISSUE THREAD

**Issue by AdamsTsui** [tusen-ai/naive-ui#4525]
### This function solves the problem (这个功能解决的问题)
平常的需求中，会遇到选择周的情况。所以，请问下能否添加这个需求，非常感谢。
### Expected API (期望的 API)
<n-date-picker type="week" clearable />

**Comment by zhangke1722** [comment]
也在等这个

**Comment by grover142224** [comment]
强烈要求加上

**Comment by palmerye** [comment]
+1

**Comment by ZhangJunkang** [comment]
等

**Comment by yangxiao86** [comment]
+1

**Comment by suica** [comment]
I would like to contribute to this feature :)
