### ISSUE TITLE
select的renderOption函数，实现后无法选中

### ISSUE THREAD

**Issue by zz541843** [tusen-ai/naive-ui#4528]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.47

### Reappearance steps (重现步骤)
select的renderOption函数，实现后无法选中，必须要return 传进来的node才有选中的效果，否则就是一个自定义的渲染，无法和select交互

**Comment by zz541843** [comment]
但是renderLabel可以，但这样会一并渲染选中后的样子，只想自定义option样式

**Comment by zz541843** [comment]
官网实例里使用的tooltip也是用到了原来的node

**Comment by zz541843** [comment]
已解决：
```
renderOption({node,option}){
    node.children[0].children[0] = <div>{option.label} custom option</div>
    return node
}
```
但这样太蠢了吧，投机取巧
renderLabel直接return自定义的dom都行的

**Comment by amadeus711** [comment]
设计如此
