### ISSUE TITLE
能不能补全部分组件的文档

### ISSUE THREAD

**Issue by qq295823929** [tusen-ai/naive-ui#4529]
### This function solves the problem (这个功能解决的问题)
阅读源码之后发现,在web-type生成的过程中,由于tooltip等部分组件的文档的.md省略了(写的是参照popover),导致生成web-type.json的时候,tooltip的slots不能正确生成.还有就是form-item组件由于文件在form里面,导致也是不能正确地生成web-type.json里面的slots属性.
### Expected API (期望的 API)
能不能添加一下支持.加强一下webstorm的开发体验(写重复的,确实不优雅,但是却很实用).谢谢

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
