### ISSUE TITLE
Pagination 添加show-item-count的属性

### ISSUE THREAD

**Issue by srrgithub** [tusen-ai/naive-ui#4540]
### This function solves the problem (这个功能解决的问题)
可以显示分页组件  数据总数    `共 ${100} 条`。  参考自Antd
### Expected API (期望的 API)
 show-item-count	用于显示数据总量和当前数据顺序	function(total, range)	-

**Comment by jahnli** [comment]
目前可以通过 `prefix` 实现

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
