### ISSUE TITLE
表单校验问题

### ISSUE THREAD

**Issue by oneStrike** [tusen-ai/naive-ui#4541]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.47

### Browser and its version (浏览器及其版本)
 110.0.1587.50

### System and its version (系统及其版本)
window10

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/form

### Reappearance steps (重现步骤)
使用官网的校验示例，将单选框的value改为number类型，则无论怎么选择都会校验失败

### Expected results (期望的结果)
修复问题

### Actual results (实际的结果)
校验失败

**Comment by snowords** [comment]
> 尝试 `rule`里的 `type` 也设置为 `number`

在`rules`加上`type="number"`，`form`的`rules`会报ts错误，不知道有没有好的解决办法？

**Comment by Talljack** [comment]
same #4564
