### ISSUE TITLE
当tabs的value值与所有name都不匹配时，应当取消已选中的tab，或增加 n-tab-empty 子组件

### ISSUE THREAD

**Issue by 2509989976** [tusen-ai/naive-ui#4543]
### This function solves the problem (这个功能解决的问题)
当tabs为可控模式时，经常会遇到value值与所有name都不匹配的情况。比如tabs与路由配合使用时，路由导航到一个不存在的页面时，应该显示404页面，但目前的tabs的选中项不会更新，依然是选中状态。
### Expected API (期望的 API)
增加 n-tab-empty 子组件来处理不存在的tab时的展示问题。
或者添加 v-slot:empty 来展示不存在的tab的页面 
同时，应当取消当前所有tab项的选中样式。

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
