### ISSUE TITLE
input自动填充，效果欠佳

### ISSUE THREAD

**Issue by DaZiYuan** [tusen-ai/naive-ui#4545]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.47

### Browser and its version (浏览器及其版本)
110.0.5481.178

### System and its version (系统及其版本)
Windows10

### Reappearance link (重现链接)
https://www.naiveui.com/en-US/dark/components/input
![image](https://user-images.githubusercontent.com/80653/222068491-04e4e86a-83dc-4a30-b082-62191ef31753.png)

### Reappearance steps (重现步骤)
浏览器设置默认密码，自动填充后两边有间距。如果取消padding，文本又贴的太紧不好看。

### Expected results (期望的结果)
input自动填充时，两边不要有间隔

### Actual results (实际的结果)
有间隔

**Comment by jahnli** [comment]
Closed due to inactivity. Feel free to reopen if you're still having trouble
