### ISSUE TITLE
日期时间范围能不能在改变日期的时候时间不重置

### ISSUE THREAD

**Issue by JS-an** [tusen-ai/naive-ui#4548]
### This function solves the problem (这个功能解决的问题)
一直重置要浪费好几次的选择时间
![image](https://user-images.githubusercontent.com/25688878/222376311-0b182478-ecd3-4209-b307-d7a8d1f1935d.png)

### Expected API (期望的 API)
建议多一个参数，开启后选择日期不重置时间

**Comment by JS-an** [comment]
> ### This function solves the problem (这个功能解决的问题)
> 当我选择一个日期时间范围后，再次选择日期会把时间给重置。比如我第一次选择2007-06-07 13:08:03 ~
2007-06-09 00:00:00后，第二次点击开始日期时，会把开始时间变为 00:00:00，我的目的只需要修改日期， 一直重置要浪费好几次的选择时间 ![image](https://user-images.githubusercontent.com/25688878/222376311-0b182478-ecd3-4209-b307-d7a8d1f1935d.png)
> 
> ### Expected API (期望的 API)
> 建议多一个参数，开启后选择日期不重置时间

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
