### ISSUE TITLE
希望Dropdown多级菜单点击后可以返回整个链路

### ISSUE THREAD

**Issue by xdewx** [tusen-ai/naive-ui#4550]
### This function solves the problem (这个功能解决的问题)
当前点击后只会返回`叶子节点`的信息，需要确保叶子节点的key唯一。在一些场景下，叶子节点的值可能是相同的，但是其所在`链路的值组合起来`是唯一的
### Expected API (期望的 API)
`on-select =(key,opt,chainOpts)`

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
