### ISSUE TITLE
n-gird组件在nuxt3下使用Screen响应式，首屏不能显示正确的布局

### ISSUE THREAD

**Issue by zzvaki** [tusen-ai/naive-ui#4552]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.47

### Browser and its version (浏览器及其版本)
Chrome 109.0.5414.119

### System and its version (系统及其版本)
MacOS 13.2.1

### Reappearance link (重现链接)
https://github.com/zzvaki/naive-ui-n-grid-bug-in-nuxtjs

### Reappearance steps (重现步骤)
pnpm install
pnpm dev
打开网页http://localhost:5234

### Expected results (期望的结果)
第一屏显示正确的响应式布局，进入正确的宽度断点

### Actual results (实际的结果)
第一屏显示错误的响应式布局，通过放大、缩小触发宽度断点时，可显示正确的布局

**Comment by zengshuaibi** [comment]
确实

**Comment by latte03** [comment]
我也

**Comment by ginlink** [comment]
猜测是因为服务器渲染时无法检测到屏幕宽度，所以在内容挂载后再渲染一次，暂时想到的方案为：

```ts

const show = ref(true);

// 客户端重新渲染一次
onMounted(() => {
  show.value = false;
  setTimeout(() => {
    show.value = true;
  }, 0);
});

<NGrid v-if="show"> ... </NGrid>
```

**Comment by ginlink** [comment]
@zzvaki

**Comment by ginlink** [comment]
https://stackoverflow.com/questions/72749827/how-to-detect-user-device-and-load-ui-accordingly-in-nuxt3

可以通过 ua 头来判定是 pc 还是移动，从而让服务器知道渲染第一屏应该用什么
```ts
const { $isMobile, $isTablet } = useNuxtApp();
const cols = ref($isMobile() ? '1 l:2 xxl:4' : $isTablet() ? '2 l:2 xxl:4' : '4 l:2 xxl:4');

// 纠正cols
onMounted(() => {
  cols.value = '1 l:2 xxl:4';
});

<NGrid x-gap="16" y-gap="16" :cols="cols" :responsive="'screen'"> ... </NGrid>
```

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
