### ISSUE TITLE
popselect不支持上下键，dropdown在赋值了value默认值的情况下，按上下键总是从第一个开始定位

### ISSUE THREAD

**Issue by xiahdfsq** [tusen-ai/naive-ui#4553]
### This function solves the problem (这个功能解决的问题)
像要popselect样式又像要上下键，dropdown像让它的上下键第一次定位到默认的value上面
### Expected API (期望的 API)
popselect，dropdown

**Comment by poerlang** [comment]
同样的需求，需要通过键盘来 focus 并上下选择，最好还能加入 虚拟滚动

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
