### ISSUE TITLE
Search function in docs not very useful

### ISSUE THREAD

**Issue by codeflorist** [tusen-ai/naive-ui#4557]
### This function solves the problem (这个功能解决的问题)
The search-function in the docs is sadly not very useful. Examples:

`tailwind` yields no results, but the string is present on https://www.naiveui.com/en-US/os-theme/docs/style-conflict

`n-global-style` yields no results, but the string is present on https://www.naiveui.com/en-US/os-theme/components/global-style

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem****
