### ISSUE TITLE
Form表单 Select的校验 不是string

### ISSUE THREAD

**Issue by srrgithub** [tusen-ai/naive-ui#4564]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-alpha.4

### Browser and its version (浏览器及其版本)
89

### System and its version (系统及其版本)
13.0.1

### Reappearance link (重现链接)
https://codepen.io/lzxw/pen/ExevGma

### Reappearance steps (重现步骤)
Form表单校验的时候， Select组件绑定的是一个数字id，但是校验通不过，提示不是String。
目前解决方法有2种。 1. 是 rules加上type="number"    2.是自己写validator。 
不过有没有好的解决办法，不然每个地方都要这么写比较麻烦。

### Expected results (期望的结果)
无需填写type ='number ' 或者 写 validator，就通过校验

### Actual results (实际的结果)
select is not a string 校验不通过

**Comment by snowords** [comment]
按照方法1，在rules加上type="number"，form的rules会报ts错误，不知道有没有好的解决办法？
`(property) rules?: FormRules | undefined
不能将类型“{ userId: { required: boolean; trigger: string[]; message: string; type: string; }; }”分配给类型“FormRules”。
  属性“userId”与索引签名不兼容。ts(2322)`

**Comment by Talljack** [comment]
1.首先因为你的 select 的 value 是 number 类型，而 async-validator 的 type 默认是 string，这并不是 bug
2. 你报 ts 错误肯定是因为你在声明 rules 时没有声明类型
`
const rules: FormRules = {
  select: {
    required: true,
    trigger: ['blur', 'change'],
    type: 'number',
  },
  select2: {
    required: true,
    trigger: ['blur', 'change'],
    type: 'number',
  },
};
`

**Comment by snowords** [comment]
的确如此，感谢解答~

**Comment by Cwmmm** [comment]
plan: [
      { type: "number", trigger: "blur" },
      { required: true, trigger: "blur" }
    ], 这么写不会覆盖到默认的string

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by sampson762** [comment]
“  typeV: {
    required: true,
    type: 'number',
    trigger: ['blur', 'change'],
    message: '请选择订单类型',
  },”


   :rules="rules"   X 
“不能将类型“{ multipleSelectValue: { required: boolean; trigger: string[]; message: string; }; typeV: { required: boolean; type: string; trigger: string[]; message: string; }; }”分配给类型“FormRules”。”
