### ISSUE TITLE
n-data-picker `@update:value` 未被触发

### ISSUE THREAD

**Issue by zguiyang** [tusen-ai/naive-ui#4567]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.36

### Browser and its version (浏览器及其版本)
Chrome 10.0.5481.178

### System and its version (系统及其版本)
windows11

### Node version (Node 版本)
16.x

### Reappearance link (重现链接)
https://codesandbox.io/s/modest-hypatia-bnulem?file=/src/Demo.vue

### Reappearance steps (重现步骤)
1. 通过其他方法重置组件value时，未触发`@update:value`

### Expected results (期望的结果)
不管通过什么方式重置了组件绑定的值，都应触发`@update:value`

### Actual results (实际的结果)
通过其他方法重置组件value时，未触发`@update:value`

**Comment by amadeus711** [comment]
设计如此，你用其他方法重置组件 value 的行为是自己可以感知到的
