### ISSUE TITLE
标签页下方得横条错位

### ISSUE THREAD

**Issue by xlsqwg** [tusen-ai/naive-ui#4568]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.47

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
WINDOWS

### Node version (Node 版本)
v16.18.0

### Reappearance link (重现链接)
https://github.com/xlsqwg/naiveui-bug

### Reappearance steps (重现步骤)
按照例子复制过去，标签页下方得横杠条动画错位，没有移到选定项本来的位置

### Expected results (期望的结果)
不要错位

### Actual results (实际的结果)
错位

**Comment by amadeus711** [comment]
需要提供使用上下文，或者提供最小化可复现的沙盒

**Comment by jahnli** [comment]
Closed due to inactivity. Feel free to reopen if you're still having trouble
