### ISSUE TITLE
Input 在type="textarea" 情况下不显示纵向滚动条

### ISSUE THREAD

**Issue by DanielSimgame** [tusen-ai/naive-ui#4570]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Chrome(110.0.5481.177)/Safari(16.0/18614.1.22.1.2)

### System and its version (系统及其版本)
MacOS(13.0/11.7)

### Reappearance link (重现链接)
https://codesandbox.io/s/festive-sound-twe3ps?file=/src/Demo.vue

### Reappearance steps (重现步骤)
调用一个NInput组件，使用type="textarea"类型，输入大量文字使滚动条得以出现
`<n-input 
    type="textarea" 
    :value="text" 
    :autosize="{
      minRows: 5,
      maxRows: 10,
    }"
  />`

### Expected results (期望的结果)
滚动条应该出现

### Actual results (实际的结果)
没有滚动条出现

### Remarks (补充说明)
[![2023-03-08-15-50-45.gif](https://i.postimg.cc/R0ZBMn3g/2023-03-08-15-50-45.gif)](https://postimg.cc/zy6M7vFh)
https://i.postimg.cc/R0ZBMn3g/2023-03-08-15-50-45.gif

**Comment by jianxingxuejian** [comment]
我也碰到了相同的问题，测试后2.31.0是正常的，后面版本滚动条就没了
