### ISSUE TITLE
Select 选择相同的值都会触发onUpdateValue事件

### ISSUE THREAD

**Issue by srrgithub** [tusen-ai/naive-ui#4571]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-alpha.4

### Browser and its version (浏览器及其版本)
89

### System and its version (系统及其版本)
13

### Reappearance link (重现链接)
https://codesandbox.io/s/strange-darkness-7zs6be?file=/src/Demo.vue

### Reappearance steps (重现步骤)
Select组件，如果选相同的值还会触发 onValueUpdate事件

### Expected results (期望的结果)
Select选相同的值就不触发 onValueUpdate事件

### Actual results (实际的结果)
Select点击就会触发事件

**Comment by liuyang0826** [comment]
这个是不是和[#4326](https://github.com/tusen-ai/naive-ui/issues/4326)修重复了哟

**Comment by liuyang0826** [comment]
@amadeus711 这个是不是和https://github.com/tusen-ai/naive-ui/issues/4326修重复了哟

**Comment by liuyang0826** [comment]
@amadeus711 这个是不是和[#4326](https://github.com/tusen-ai/naive-ui/issues/4326)修重复了哟

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
