### ISSUE TITLE
Popover组件内无法使用v-bind

### ISSUE THREAD

**Issue by CS-liujf** [tusen-ai/naive-ui#4573]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.25

### Browser and its version (浏览器及其版本)
Microsoft Edge 版本 110.0.1587.49 (正式版本) (64 位)

### System and its version (系统及其版本)
win 10

### Reappearance link (重现链接)
https://codepen.io/cs-liujf/pen/zYJELzj

### Reappearance steps (重现步骤)
点击按钮后查看文字颜色

### Expected results (期望的结果)
如果v-bind生效，那么文字应该是红色的

### Actual results (实际的结果)
文字并不是红色，浏览器审查元素显示该css变量未定义

**Comment by CS-liujf** [comment]
这个问题可能是由于popover是挂载到<body>内第一层，跟<div id="app">同级

**Comment by CS-liujf** [comment]
> 1. 你的复现链接无法使用 `v-bind()`，[v-bind()](https://vuejs.org/api/sfc-css-features.html#v-bind-in-css) 只能在 SFC 中使用；
> 2. 设置 popover 的内容样式可以通过 `content-style` [参考文档](https://www.naiveui.com/zh-CN/os-theme/components/popover#style.vue)

哦抱歉，我的复现链接给的不合理，我自己的项目的确是在SFC中使用的。关于您的第二条，我再更具体说一下，我并不是需要设置popover的内容样式，而是想要对最内部的div使用v-bind。目前的问题就是虽然控制台、vite都不报错，但是审查元素可以发现css变量未定义。我猜测跟这个链接提到的原因是类似的https://www.jianshu.com/p/4cd415293fcb
```vue
<template>
  <n-popover trigger="hover">
    <template #trigger>
      <n-button>悬浮</n-button>
    </template>
    <div>
      <div>...</div>
    </div>
  </n-popover>
</template>
```

**Comment by jizai1125** [comment]
> 

嗯嗯，`Popover` 内容默认是挂载到 body 下的，那你可以用 `to` 去指定下挂载位置，例如下面这样：
```vue
<template>
  <div class="container"></div>
  <n-popover trigger="click" to=".container">
    <template #trigger>
      <n-button>悬浮</n-button>
    </template>
    <div>
      <div class="text">哈哈哈哈哈哈</div>
    </div>
  </n-popover>
</template>

<script>
export default {
  data() {
    return {
      color: "red",
    };
  },
};
</script>

<style scoped>
.text {
  color: v-bind(color);
}
</style>

```

**Comment by jizai1125** [comment]
> > 1. 你的复现链接无法使用 `v-bind()`，[v-bind()](https://vuejs.org/api/sfc-css-features.html#v-bind-in-css) 只能在 SFC 中使用；
> > 2. 设置 popover 的内容样式可以通过 `content-style` [参考文档](https://www.naiveui.com/zh-CN/os-theme/components/popover#style.vue)
> 
> 哦抱歉，我的复现链接给的不合理，我自己的项目的确是在SFC中使用的。关于您的第二条，我再更具体说一下，我并不是需要设置popover的内容样式，而是想要对最内部的div使用v-bind。目前的问题就是虽然控制台、vite都不报错，但是审查元素可以发现css变量未定义。我猜测跟这个链接提到的原因是类似的https://www.jianshu.com/p/4cd415293fcb
> 
> ```
> <template>
>   <n-popover trigger="hover">
>     <template #trigger>
>       <n-button>悬浮</n-button>
>     </template>
>     <div>
>       <div>...</div>
>     </div>
>   </n-popover>
> </template>
> ```

嗯嗯，`Popover` 内容默认是挂载到 body 下的，那你可以用 `to` 去指定下挂载位置，例如下面这样：
```vue
<template>
  <div class="my-container"></div>
  <n-popover trigger="click" to=".my-container">
    <template #trigger>
      <n-button>悬浮</n-button>
    </template>
    <div>
      <div class="text">哈哈哈哈哈哈</div>
    </div>
  </n-popover>
</template>

<script setup lang="ts">
const cssVars = {
  color: "red",
};
</script>

<style scoped>
.text {
  color: v-bind("cssVars.color");
}
</style>
```

**Comment by CS-liujf** [comment]
> > > 1. 你的复现链接无法使用 `v-bind()`，[v-bind()](https://vuejs.org/api/sfc-css-features.html#v-bind-in-css) 只能在 SFC 中使用；
> > > 2. 设置 popover 的内容样式可以通过 `content-style` [参考文档](https://www.naiveui.com/zh-CN/os-theme/components/popover#style.vue)
> > 
> > 
> > 哦抱歉，我的复现链接给的不合理，我自己的项目的确是在SFC中使用的。关于您的第二条，我再更具体说一下，我并不是需要设置popover的内容样式，而是想要对最内部的div使用v-bind。目前的问题就是虽然控制台、vite都不报错，但是审查元素可以发现css变量未定义。我猜测跟这个链接提到的原因是类似的https://www.jianshu.com/p/4cd415293fcb
> > ```
> > <template>
> >   <n-popover trigger="hover">
> >     <template #trigger>
> >       <n-button>悬浮</n-button>
> >     </template>
> >     <div>
> >       <div>...</div>
> >     </div>
> >   </n-popover>
> > </template>
> > ```
> 
> 嗯嗯，`Popover` 内容默认是挂载到 body 下的，那你可以将 `to` 设置为 `false` 或者去指定下挂载位置，可以详细看下文档，都有说明的。
> 
> ```
> <template>
>     <n-popover trigger="click" :to="false">
>       <template #trigger>
>         <n-button>悬浮</n-button>
>       </template>
>       <div class="text">哈哈哈哈哈哈</div>
>     </n-popover>
> </template>
> 
> <script setup lang="ts">
> const cssVars = {
>   color: "red",
> };
> </script>
> 
> <style scoped>
> .text {
>   color: v-bind("cssVars.color");
> }
> </style>
> ```

谢谢，我原本以为to是指定挂载位置，但是看文档里对to的说明是：*弹出内容的卸载位置，false 会待在原地*，我就被这个卸载位置困扰了😂

**Comment by CS-liujf** [comment]
> > > 1. 你的复现链接无法使用 `v-bind()`，[v-bind()](https://vuejs.org/api/sfc-css-features.html#v-bind-in-css) 只能在 SFC 中使用；
> > > 2. 设置 popover 的内容样式可以通过 `content-style` [参考文档](https://www.naiveui.com/zh-CN/os-theme/components/popover#style.vue)
> > 
> > 
> > 哦抱歉，我的复现链接给的不合理，我自己的项目的确是在SFC中使用的。关于您的第二条，我再更具体说一下，我并不是需要设置popover的内容样式，而是想要对最内部的div使用v-bind。目前的问题就是虽然控制台、vite都不报错，但是审查元素可以发现css变量未定义。我猜测跟这个链接提到的原因是类似的https://www.jianshu.com/p/4cd415293fcb
> > ```
> > <template>
> >   <n-popover trigger="hover">
> >     <template #trigger>
> >       <n-button>悬浮</n-button>
> >     </template>
> >     <div>
> >       <div>...</div>
> >     </div>
> >   </n-popover>
> > </template>
> > ```
> 
> 嗯嗯，`Popover` 内容默认是挂载到 body 下的，那你可以将 `to` 设置为 `false` 或者去指定下挂载位置，可以详细看下文档，都有说明的。
> 
> ```
> <template>
>     <n-popover trigger="click" :to="false">
>       <template #trigger>
>         <n-button>悬浮</n-button>
>       </template>
>       <div class="text">哈哈哈哈哈哈</div>
>     </n-popover>
> </template>
> 
> <script setup lang="ts">
> const cssVars = {
>   color: "red",
> };
> </script>
> 
> <style scoped>
> .text {
>   color: v-bind("cssVars.color");
> }
> </style>
> ```

谢谢，我原本以为to是指定挂载位置，但是看文档里对to的说明是：*弹出内容的卸载位置，false 会待在原地*，我就被这个卸载位置困扰了😂

**Comment by jizai1125** [comment]
> > > > 1. 你的复现链接无法使用 `v-bind()`，[v-bind()](https://vuejs.org/api/sfc-css-features.html#v-bind-in-css) 只能在 SFC 中使用；
> > > > 2. 设置 popover 的内容样式可以通过 `content-style` [参考文档](https://www.naiveui.com/zh-CN/os-theme/components/popover#style.vue)
> > > 
> > > 
> > > 哦抱歉，我的复现链接给的不合理，我自己的项目的确是在SFC中使用的。关于您的第二条，我再更具体说一下，我并不是需要设置popover的内容样式，而是想要对最内部的div使用v-bind。目前的问题就是虽然控制台、vite都不报错，但是审查元素可以发现css变量未定义。我猜测跟这个链接提到的原因是类似的https://www.jianshu.com/p/4cd415293fcb
> > > ```
> > > <template>
> > >   <n-popover trigger="hover">
> > >     <template #trigger>
> > >       <n-button>悬浮</n-button>
> > >     </template>
> > >     <div>
> > >       <div>...</div>
> > >     </div>
> > >   </n-popover>
> > > </template>
> > > ```
> > 
> > 
> > 嗯嗯，`Popover` 内容默认是挂载到 body 下的，那你可以将 `to` 设置为 `false` 或者去指定下挂载位置，可以详细看下文档，都有说明的。
> > ```
> > <template>
> >     <n-popover trigger="click" :to="false">
> >       <template #trigger>
> >         <n-button>悬浮</n-button>
> >       </template>
> >       <div class="text">哈哈哈哈哈哈</div>
> >     </n-popover>
> > </template>
> > 
> > <script setup lang="ts">
> > const cssVars = {
> >   color: "red",
> > };
> > </script>
> > 
> > <style scoped>
> > .text {
> >   color: v-bind("cssVars.color");
> > }
> > </style>
> > ```
> 
> 谢谢，我原本以为to是指定挂载位置，但是看文档里对to的说明是：_弹出内容的卸载位置，false 会待在原地_，我就被这个卸载位置困扰了😂

😂 对啊，应该挂载才对吧

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
