### ISSUE TITLE
n-menu 折叠状态下 子菜单的选中效果与顶层菜单的选中效果不一致

### ISSUE THREAD

**Issue by laterdayi** [tusen-ai/naive-ui#4574]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-alpha.4

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
windows

### Reappearance link (重现链接)
https://codesandbox.io/s/c5kx6x

### Reappearance steps (重现步骤)
n-menu 折叠状态下 子菜单的选中效果与顶层菜单的选中效果不一致
![image](https://user-images.githubusercontent.com/122137647/223738399-beb9b1c3-b9b0-4eba-a26b-c9b78276c116.png)
![image](https://user-images.githubusercontent.com/122137647/223738431-e8c77076-ff65-4406-9cb6-498089666b08.png)

### Expected results (期望的结果)
期望保持一致

### Actual results (实际的结果)

n-menu 折叠状态下 子菜单的选中效果与顶层菜单的选中效果不一致
![image](https://user-images.githubusercontent.com/122137647/223738399-beb9b1c3-b9b0-4eba-a26b-c9b78276c116.png)
![image](https://user-images.githubusercontent.com/122137647/223738431-e8c77076-ff65-4406-9cb6-498089666b08.png)

**Comment by laterdayi** [comment]
在UI和测试看来， 这是一个BUG， 是否可以保持一致的效果

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
