### ISSUE TITLE
数据表格最左侧列，设置 ellipsis 为 true，并设定固定宽度后展开树状结构图标被换行且子节点缩进不正常

### ISSUE THREAD

**Issue by LemonGo97** [tusen-ai/naive-ui#4575]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Chrome(110.0.5481.77)

### System and its version (系统及其版本)
MaxOS(13.0.1)

### Reappearance link (重现链接)
https://codesandbox.io/s/agitated-shadow-5c0x7v?file=/src/Demo.vue

### Reappearance steps (重现步骤)
数据表格最左侧列，设置 ellipsis 为 true，并设定固定宽度，表格中的数据为树状结构，展开行的图标被换行且子节点缩进失效

### Expected results (期望的结果)
数据表格最左侧行设置ellipsis为 true并设置固定宽width时树状结构展开行的图表不被换行且子节点缩进正常

### Actual results (实际的结果)
展开行的图标被换行且子节点缩进失效

### Remarks (补充说明)
<img width="587" alt="image" src="https://user-images.githubusercontent.com/29590079/223776882-42e761a6-3e01-47b7-85ed-3eac154d3277.png">

**Comment by liaobinbin** [comment]
max-width: 100%的问题

改成 max-wdith: calc(100% - iconWidth - iconMarginRight - indentWdith * n)

要改源代码，看了一下挺麻烦的。

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
