### ISSUE TITLE
关于`NProgress`组件的动画特性

### ISSUE THREAD

**Issue by WankkoRee** [tusen-ai/naive-ui#4577]
### This function solves the problem (这个功能解决的问题)
现有的动画效果是在数值改变的时候才会触发，是否可以提供一个属性以定义在组件挂载的时候显示动画呢？如从0到当前数值或从满值到当前数值，类似于`NNumberAnimation`组件。
### Expected API (期望的 API)
-

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
