### ISSUE TITLE
Tag组件使用strong属性后没有效果

### ISSUE THREAD

**Issue by SuperManito** [tusen-ai/naive-ui#4582]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.47

### Browser and its version (浏览器及其版本)
latest

### System and its version (系统及其版本)
Windows 11

### Node version (Node 版本)
18

### Reappearance link (重现链接)
https://codesandbox.io/s/throbbing-cdn-g2u79d?file=/src/Demo.vue

### Reappearance steps (重现步骤)
标签加上 strong 参数

### Expected results (期望的结果)
文字加粗

### Actual results (实际的结果)
前后没变化

**Comment by zhengdaonian** [comment]
![image](https://user-images.githubusercontent.com/60170001/224208474-4119f99d-ebbd-4066-8c6f-f42135eb7d0e.png)
实际上是有效果的，strong后字体font-weight为500

**Comment by amadeus711** [comment]
https://codesandbox.io/s/dreamy-pine-nkwc5l?file=/src/Demo.vue
沙盒环境没有复现，检查使用时是否受自己的样式影响

**Comment by SuperManito** [comment]
> https://codesandbox.io/s/dreamy-pine-nkwc5l?file=/src/Demo.vue 沙盒环境没有复现，检查使用时是否受自己的样式影响

确实有加上font-weight: 500，我没有检查css，但它是什么原因导致使用strong后前后没有变化的呢？我注意到button有着类似的设计，但是它前后对比非常明显

**Comment by zhengdaonian** [comment]
因为中英文，字体不一样，中文字体bold是700，fontWeight为600才有明显效果。你试试tag写英文，效果和button是一样的
