### ISSUE TITLE
clickoutside 事件点击在 web components  时不会触发

### ISSUE THREAD

**Issue by MaLuns** [tusen-ai/naive-ui#4584]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-alpha.4

### Browser and its version (浏览器及其版本)
Edg/110.0.1587.63

### System and its version (系统及其版本)
win 10

### Reappearance link (重现链接)
https://stackblitz.com/edit/vue-wqhpkc?file=src/App.vue

### Reappearance steps (重现步骤)
给 popover  怎加回调 clickoutside 函数 ，点击  Web Components 区域即可复现

### Expected results (期望的结果)
点击在 web components  元素上，触发 clickoutside

### Actual results (实际的结果)
点击在 web components  元素上时，不会触发 clickoutside

**Comment by sunny9528** [comment]
我测试了一下，可能是自定义元素没有添加事件导致的， 你给自定义元素添加一个点击事件,在点击事件中隐藏popover 可以暂时解决这个问题

**Comment by sunny9528** [comment]
```js
customElements.define(
        'my-div',
        class extends HTMLElement {
          constructor() {
            super()
            const template = document.getElementById('my-template')
            const templateContent = template.cloneNode(true)
            const shadowRoot = this.attachShadow({ mode: 'open' })
            shadowRoot.appendChild(templateContent)
            shadowRoot.addEventListener('click', (e) => (showPopover.value = false))
            
          }
        }
      )
```

**Comment by sunny9528** [comment]
> > 我测试了一下，可能是自定义元素没有添加事件导致的， 你给自定义元素添加一个点击事件,在点击事件中隐藏popover 可以暂时解决这个问题
> 
> web components 内部不一定能访问到 popover ，并不知道那些地方使用了 popover

源码中使用的是mouseleave来实现的  这个web componetns 没有响应这个 因此就无法隐藏
