### ISSUE TITLE
好多组件都不能在<script setup lang="ts"></script>使用

### ISSUE THREAD

**Issue by tgy3300** [tusen-ai/naive-ui#4586]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.46

### Browser and its version (浏览器及其版本)
最新

### System and its version (系统及其版本)
win10

### Node version (Node 版本)
node 18

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/message

### Reappearance steps (重现步骤)
用法需求1，想在setup语法糖中使用，但是报错
```
<script setup lang="ts">
import { useMessage } from 'naive-ui'
const message = useMessage()
message.success("esdfasd")
</script>
```

用法需求2，想在ts文件中直接使用，比如用axios封装的request，想在请求、响应拦截器中使用，但是报错
```
import { useMessage } from 'naive-ui'
const message = useMessage()
message.success("esdfasd")
```

### Expected results (期望的结果)
希望能满足

### Actual results (实际的结果)
希望能满足

**Comment by Talljack** [comment]
1. 请给出复现，我在codesandbox里没复现
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/34439652/224464524-5dbfe221-9357-4abc-9e8a-971e6ff74880.png">
2. 在普通 ts 文件中使用请参考 https://www.naiveui.com/zh-CN/light/components/message#%E5%9C%A8-setup-%E5%A4%96%E4%BD%BF%E7%94%A8

**Comment by tgy3300** [comment]
还有，组件提供了哪些插槽，在文档里没有写，这块可以参考一下element-plus的做法

**Comment by Talljack** [comment]
没写就是没有，写了的就有，自己去看文档，要是你发现有遗漏可以 comment 或者 提交 PR

**Comment by kinggq** [comment]
给你参考一下 https://github.com/kinggq/whiteboard

**Comment by ahkui** [comment]
應該是漏了 `n-message-provider` 吧？

**Comment by ahkui** [comment]
沒法用建議先看一看瀏覽器 Console 是否有異常

**Comment by KeyToLove** [comment]
Same issue here.
The minimum recurrence: https://codesandbox.io/s/priceless-khorana-dcvd3k?file=/src/Demo.vue

If i want to use `message ` API in `App.vue`, i must add a parent component wrap the `App.vue`,I think that's problematic
![image](https://user-images.githubusercontent.com/54970106/226517914-8bb6eda6-7609-4e34-b37f-e70048367818.png)

**Comment by herozzm** [comment]
确实不行，官方示例应该加入 <script setup lang="ts">模式的，
```
<script setup lang="ts">
import { useMessage } from 'naive-ui'
const message = useMessage()
message.success("esdfasd")
</script>
```
提示有问题，并未在setup 外

**Comment by nandaojiuai** [comment]
<script lang="ts" setup>
import { reactive, computed } from 'vue'
import { NInput, NConfigProvider, useMessage } from 'naive-ui'
import router from '@/router'
import { registerApi } from '@/service/api/login/login'

const message = useMessage()  
Uncaught (in promise) Error: [naive/use-message]: No outer <n-message-provider /> founded. See prerequisite in https://www.naiveui.com/en-US/os-theme/components/message for more details. If you want to use `useMessage` outside setup, please check https://www.naiveui.com/zh-CN/os-theme/components/message#Q-&-A.

**Comment by xiuyangzhe** [comment]
我也是一样报错明明加了<n-message-provider />，这个bug为啥要关

**Comment by dengsong666** [comment]
> 1. codesandbox

贴个codesandbox地址，我的setup怎么不行？？？

**Comment by ahkui** [comment]
> Same issue here. The minimum recurrence: https://codesandbox.io/s/priceless-khorana-dcvd3k?file=/src/Demo.vue
> 
> If i want to use `message ` API in `App.vue`, i must add a parent component wrap the `App.vue`,I think that's problematic ![image](https://user-images.githubusercontent.com/54970106/226517914-8bb6eda6-7609-4e34-b37f-e70048367818.png)

解决问题的办法都在这了，这属于设计限制

要用就直接把 provider 加到 app 就行了，为什么一定要在同个 component 使用？

**Comment by 799189288** [comment]
> > Same issue here. The minimum recurrence: https://codesandbox.io/s/priceless-khorana-dcvd3k?file=/src/Demo.vue
> > If i want to use `message ` API in `App.vue`, i must add a parent component wrap the `App.vue`,I think that's problematic ![image](https://user-images.githubusercontent.com/54970106/226517914-8bb6eda6-7609-4e34-b37f-e70048367818.png)
> 
> 解决问题的办法都在这了，这属于设计限制
> 
> 要用就直接把 provider 加到 app 就行了，为什么一定要在同个 component 使用？

1.在vue-router 的beforeEach中使用异步操作。
2. axios  window.$message.error 报找不到error

我在router.beforeEach 里面有调用接口的操作， 如果接口报错， 走到错误拦截器里面，此时此刻message是没有挂载的， 因为还没有进入到 app.vue下面的组件中。 我该如何设置才能够使用呢。

**Comment by jahnli** [comment]
`AppProvider.vue`

```
<script setup lang="ts">
import { type GlobalThemeOverrides, dateZhCN, zhCN } from 'naive-ui';
import App from './App.vue';
import { LOCAL_DEFAULT } from '@/constants/app';

const appStore = useAppStore();
const { themePrimary, local } = storeToRefs(appStore);

const lightThemeOverrides = (): GlobalThemeOverrides => {
  const { common, ...componentTheme } = light;
  return {
    common: {
      ...common,
      primaryColor: themePrimary.value,
      primaryColorHover: `${themePrimary.value}D9`,
      primaryColorPressed: themePrimary.value
    },
    ...componentTheme,
    Layout: {
      headerColor: themePrimary.value
    },
    Menu: {
      ...componentTheme.Menu,
      itemColorActive: themePrimary.value,
      itemColorActiveCollapsed: themePrimary.value,
      itemColorActiveHover: themePrimary.value,
      itemColorHover: `${themePrimary.value}13`
    }
  };
};
</script>

<template>
  <n-config-provider
    inline-theme-disabled
    :locale="local === LOCAL_DEFAULT ? zhCN : null"
    :date-locale="local === LOCAL_DEFAULT ? dateZhCN : null"
    :theme-overrides="lightThemeOverrides()"
  >
    <n-loading-bar-provider>
      <n-modal-provider>
        <n-dialog-provider>
          <n-notification-provider>
            <n-message-provider>
              <app />
            </n-message-provider>
          </n-notification-provider>
        </n-dialog-provider>
      </n-modal-provider>
    </n-loading-bar-provider>
  </n-config-provider>
</template>
```

`App.vue`


```
<script setup lang="ts">
const registerNaiveUiTools = () => {
  window.$message = useMessage();
  window.$loadingBar = useLoadingBar();
  window.$dialog = useDialog();
  window.$notification = useNotification();
};
registerNaiveUiTools();
</script>

<template>
  <router-view />
</template>
```


@799189288

**Comment by 799189288** [comment]
> `AppProvider.vue`
> 
> ```
> <script setup lang="ts">
> import { type GlobalThemeOverrides, dateZhCN, zhCN } from 'naive-ui';
> import App from './App.vue';
> import { LOCAL_DEFAULT } from '@/constants/app';
> 
> const appStore = useAppStore();
> const { themePrimary, local } = storeToRefs(appStore);
> 
> const lightThemeOverrides = (): GlobalThemeOverrides => {
>   const { common, ...componentTheme } = light;
>   return {
>     common: {
>       ...common,
>       primaryColor: themePrimary.value,
>       primaryColorHover: `${themePrimary.value}D9`,
>       primaryColorPressed: themePrimary.value
>     },
>     ...componentTheme,
>     Layout: {
>       headerColor: themePrimary.value
>     },
>     Menu: {
>       ...componentTheme.Menu,
>       itemColorActive: themePrimary.value,
>       itemColorActiveCollapsed: themePrimary.value,
>       itemColorActiveHover: themePrimary.value,
>       itemColorHover: `${themePrimary.value}13`
>     }
>   };
> };
> </script>
> 
> <template>
>   <n-config-provider
>     inline-theme-disabled
>     :locale="local === LOCAL_DEFAULT ? zhCN : null"
>     :date-locale="local === LOCAL_DEFAULT ? dateZhCN : null"
>     :theme-overrides="lightThemeOverrides()"
>   >
>     <n-loading-bar-provider>
>       <n-modal-provider>
>         <n-dialog-provider>
>           <n-notification-provider>
>             <n-message-provider>
>               <app />
>             </n-message-provider>
>           </n-notification-provider>
>         </n-dialog-provider>
>       </n-modal-provider>
>     </n-loading-bar-provider>
>   </n-config-provider>
> </template>
> ```
> 
> `App.vue`
> 
> ```
> <script setup lang="ts">
> const registerNaiveUiTools = () => {
>   window.$message = useMessage();
>   window.$loadingBar = useLoadingBar();
>   window.$dialog = useDialog();
>   window.$notification = useNotification();
> };
> registerNaiveUiTools();
> </script>
> 
> <template>
>   <router-view />
> </template>
> ```
> 
> @799189288

感谢，我多嵌套了一层路由，果然直接用组件就好了

**Comment by jahnli** [comment]
@799189288  可以开新的问题，然后引用旧的问题，这样直接评论一般看不到

**Comment by 799189288** [comment]
> @799189288 可以开新的问题，然后引用旧的问题，这样直接评论一般看不到

好的，主要是看开新问题要提供示例的地址有些麻烦
