### ISSUE TITLE
n-tree-select: Can the lazy-loaded tree selection support the echo of deep nodes

### ISSUE THREAD

**Issue by yingnian** [tusen-ai/naive-ui#4593]
### This function solves the problem (这个功能解决的问题)
Lazy-loaded tree selection also requires echoing. When the node that needs to be echoed is not at the first level, it cannot be echoed currently
（懒加载的树型选择也会有回显的需求，当需要回显的节点不在第一层级时，当前无法回显）
### Expected API (期望的 API)
Allows the user to manually pass in an object or array of selected items (take single selection as an example: { label: 'echo name', value: 'echo value' })
（可以让用户手动传入选中项的对象或数组（以单选为例：{ label: '回显名称', value: '回显值' }））

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
