### ISSUE TITLE
tabs使用问题

### ISSUE THREAD

**Issue by tgy3300** [tusen-ai/naive-ui#4594]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-alpha.4

### Browser and its version (浏览器及其版本)
最新

### System and its version (系统及其版本)
最新

### Node version (Node 版本)
最新

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/tabs#bar-width.vue

### Reappearance steps (重现步骤)
当选项有100个时，容器只能显示10个标签，剩下的标签都会隐藏，这些都没问题。
刷新页面时，如果默认值为98，定位到选项卡后，不能显示在10个标签里，如下：
```
<n-tabs type="card" v-model:value="valueRef" :closable="true">
      <n-tab v-for="panel in 200" :key="panel" :name="panel" />
</n-tabs>

valueRef = ref(98)

效果和分页一样，选中的要显示出来
... 1  2  3  4  5  6  7  8  9 10 ...
```

### Expected results (期望的结果)
能实现不

### Actual results (实际的结果)
能实现不

**Comment by 07akioni** [comment]
是应该默认显示

**Comment by codeblockhead** [comment]
这个问题不管了吗，一年过去了

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
