### ISSUE TITLE
提议Popconfirm加个状态

### ISSUE THREAD

**Issue by plunjoin** [tusen-ai/naive-ui#4595]
### This function solves the problem (这个功能解决的问题)
当弹出确认出现和消失的时候也许会做一些判断？
### Expected API (期望的 API)
如Dialog的 onAfterEnter onAfterLeave事件

**Comment by jahnli** [comment]
`Popover-Props` `on-update:show `  应该可以满足

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
