### ISSUE TITLE
button样式变形

### ISSUE THREAD

**Issue by zhxqc** [tusen-ai/naive-ui#46]
### Environment Info

- Naive UI version: (eg. 2.11.0)
- Browser Info: (eg. Chome 91)
- System Info: (eg. Mac OS 11.2.3, Windows)

### Reproduction link

https://www.naiveui.com/zh-CN/light/components/button

### What is actually happening?

![image](https://user-images.githubusercontent.com/35363368/121347865-3f3af480-c95a-11eb-84a0-ff0c44e84e69.png)

点开上面的code文档，下面的演示button样式变形

**Comment by zhxqc** [comment]
![image](https://user-images.githubusercontent.com/35363368/121348229-aa84c680-c95a-11eb-87b6-8f1cf0c7b33a.png)

**Comment by 07akioni** [comment]
Can't reproduce it on a windows with chrome 91.

**Comment by zhxqc** [comment]
浏览器版本 91.0.4472.77（正式版本） (arm64)

**Comment by 07akioni** [comment]
> 91.0.4472.77（正式版本）

A arm windows? Sorry I can't reproduce it by myself.

**Comment by zhxqc** [comment]
电脑是mac的，M1的MacBook pro ，系统是  macOS Big Sur 11.4（20F71） 抱歉没说明白

**Comment by 07akioni** [comment]
> 电脑是mac的，M1的MacBook pro ，系统是 macOS Big Sur 11.4（20F71） 抱歉没说明白

Can't reproduce by myself. I'll keep the issue open.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
