### ISSUE TITLE
Date Table: simplify the Async example by using `watchEffect`

### ISSUE THREAD

**Issue by edimitchel** [tusen-ai/naive-ui#4603]
### This function solves the problem (这个功能解决的问题)
I just into naive UI component library and see a wonderful Data Table components.
Looking into example and see the async example but quickly jump on my code to write it.
I write a version which is lighter than the example shown on doc by making fetches driven by data instead of executing on demand.

- [ ] Share code
- [ ] Get approval before PR
- [ ] Raise PR

### Expected API (期望的 API)
Using watchEffect instead of calling query when needed

**Comment by amadeus711** [comment]
Naive ui welcomes everyone to submit PR. In this case, you can add a new example. You need `git checkout` from the `docs` branch, and submit PR into `docs` branch after development. No need to modify CHANGELOG.

**Comment by beunerd** [comment]
@edimitchel Would be great to see your example. Could you post some hint as to how this is done?

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
