### ISSUE TITLE
Drawer on-update:width can not expand when set show-mask="false"

### ISSUE THREAD

**Issue by PlayerYK** [tusen-ai/naive-ui#4605]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.36

### Browser and its version (浏览器及其版本)
Chrome 111.0.5563.65

### System and its version (系统及其版本)
Windows 11

### Reappearance link (重现链接)
https://codesandbox.io/s/clever-dew-iu29gw?file=/src/Demo.vue

### Reappearance steps (重现步骤)
  <n-drawer
    v-model:show="active"
    :width="width"
    :on-update:width="onResize"
    :show-mask="false"
    :mask-closable="false"
    :resizable="true"
  >
    <n-drawer-content>
      <template #header> Header </template>
      <template #footer>
        <n-button @click="active = false">关闭</n-button>
      </template>
    </n-drawer-content>
  </n-drawer>

    const onResize = (newWidth) => {
      console.log("newWidth", newWidth);
      width.value = newWidth;
    };

Drag Drawer border to resize

### Expected results (期望的结果)
Drawer width could expans and shrink

### Actual results (实际的结果)
Drawer width can only shrink not possible to expand

### Remarks (补充说明)
when Mask is shown, it worked as expected.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
