### ISSUE TITLE
给表单 Form绑定theme-overrides，样式不生效

### ISSUE THREAD

**Issue by maddenBoy** [tusen-ai/naive-ui#4606]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-alpha.4

### Browser and its version (浏览器及其版本)
Chrome（111.0.5563.65）

### System and its version (系统及其版本)
win11

### Reappearance link (重现链接)
https://codesandbox.io/s/snowy-https-tgxkhc

### Reappearance steps (重现步骤)
给n-form绑定theme-overrides属性，样式不生效，给n-form-item绑定则生效（改变表单项样式需要一个个item去绑定？）

### Expected results (期望的结果)
给n-form绑定theme-overrides属性，样式生效

### Actual results (实际的结果)
给n-form绑定theme-overrides属性，样式不生效

**Comment by jahnli** [comment]
Closed due to inactivity. Feel free to reopen if you're still having trouble
