### ISSUE TITLE
列宽拖拽松开鼠标会触发排序功能

### ISSUE THREAD

**Issue by JS-an** [tusen-ai/naive-ui#4610]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-alpha.4

### Browser and its version (浏览器及其版本)
Chrome 版本 111.0.5563.65（正式版本） （64 位）

### System and its version (系统及其版本)
WIN 10 64位

### Node version (Node 版本)
v16.13.2

### Reappearance link (重现链接)
https://codesandbox.io/s/bds1on?file=/src/Demo.vue

### Reappearance steps (重现步骤)
按住拖拽按钮向左移动一段距离，不要超过该列，松开鼠标，则会看到排序功能被触发了
![image](https://user-images.githubusercontent.com/25688878/226268069-544230e5-59e3-471c-a357-dd5bdc9cb22e.png)

### Expected results (期望的结果)
预期是拖拽功能的事件不会和排序功能混淆

### Actual results (实际的结果)
排序功能被触发了

**Comment by chwj1208** [comment]
啥时上线？

**Comment by JS-an** [comment]
> 啥时上线？

官方一直没合进去

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
