### ISSUE TITLE
Data Table: virtual scroll pagination

### ISSUE THREAD

**Issue by edimitchel** [tusen-ai/naive-ui#4611]
### This function solves the problem (这个功能解决的问题)
This would be a game changer for the Data Table to have the pagination working in sync with an infinite mode working with virtual scroll.

This is difficult to be handled by the application but could be easier to be achieved by the component itself.

The behavior expected:
- On scroll, automatically update pagination according to the position and to the page size (with a 10 rows par page, scroll under the 10th row will update the pagination to the second page)
- On pagination click, make the scroll to the corresponding element.

This should also work with the remote mode: request on demand.
### Expected API (期望的 API)
I don't have idea for the moment about how to achieve this feature in terms of API.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
