### ISSUE TITLE
When NEllipsis slot is too long, popover will out of the screen range in some cases

### ISSUE THREAD

**Issue by dragon-fish** [tusen-ai/naive-ui#4612]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.47

### Browser and its version (浏览器及其版本)
Latest Chrome and FireFox

### System and its version (系统及其版本)
Windows 11

### Reappearance link (重现链接)
https://codesandbox.io/s/stupefied-ardinghelli-3274q1?file=/src/App.vue

### Reappearance steps (重现步骤)
1. Place Component NEllipsis component close to the edge of the screen
2. Pass very long contents into it
3. Make sure your browser screen width is around 1200-1920 pixels
4. Hover the NEllipsis
5. See bug: If NEllipsis is on the right edge, the left side of popover will exceed the screen range. Vice versa.

### Expected results (期望的结果)
The popup will not exceed the screen range

### Actual results (实际的结果)
If NEllipsis is on the right edge, the left side of popover will exceed the screen range. Vice versa.

### Remarks (补充说明)
See screenshot

![图片](https://user-images.githubusercontent.com/44761872/226295152-c70fc471-16d3-4de6-88b5-58623342b0f8.png)

**Comment by dragon-fish** [comment]
Now I believe this should be a issue of Tooltip component

**Comment by jizai1125** [comment]
I think this is expected behavior. By default, the popover max width is the  the screen width, but you can use the 'style' or 'contentStyle' properties to control it. You can also set width: 'trigger' to make the popover's width the same as its trigger.

**Comment by amadeus711** [comment]
In this case, setting max-width can solve the problem. We have two APIs: 
https://codesandbox.io/s/vigilant-cdn-d0bubv?file=/src/App.vue

**Comment by dragon-fish** [comment]
NPopover should handle this situation better to avoid body's edge get out of the screen.
Maybe I will submit a PR at the weekend.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
