### ISSUE TITLE
Data Table: let configure the sort order globally

### ISSUE THREAD

**Issue by edimitchel** [tusen-ai/naive-ui#4613]
### This function solves the problem (这个功能解决的问题)
I'm trying Naive UI in confrontation with PrimeNG/PrimeVue. I'm search a way for changing the order of sort on sortable column click.
Their datatables choose the sort order as "ascend" then "descend".
Naive UI's datatable is using "descend" then "ascend".

Don't find a solution to change the order without manipulating sort state (I took a look into config provider but was annoyed to see the only config is the current state aplied).

I would like to configure the data table with an array (with as default the current value) and let anyone change it using config provider another value, and why not, with different values than 'ascend' or 'descend'.
### Expected API (期望的 API)
- Add a new injection key which as value will receive a raw array of sort order
- Make possible to use another key than `ascend` or `descend` (a tricky feature request but which could ease migration from another datatable)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
