### ISSUE TITLE
Toggle Button

### ISSUE THREAD

**Issue by djfuzzy** [tusen-ai/naive-ui#4614]
### This function solves the problem (这个功能解决的问题)
A button that acts as a checkbox. Visually similar to an option in the Radio Button Group, but a single button with the ability to toggle off.
### Expected API (期望的 API)
```
<n-toggle-button v-model:value="active" /> <!-- Inherits some or all props of n-checkbox and n-button -->
```

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
