### ISSUE TITLE
Cascader show incomplete options

### ISSUE THREAD

**Issue by Gahotx** [tusen-ai/naive-ui#4616]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.47

### Browser and its version (浏览器及其版本)
Chrome(111.0.5563.65)

### System and its version (系统及其版本)
Windows 10

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/cascader

### Reappearance steps (重现步骤)
English:
1. select `l-12 / l-12-9 / l-12-9-12` in Demos Single
2. click the cascader of Single

Chinese:
1. 在单选中选择 `l-12 / l-12-9 / l-12-9-12`
2. 点击这个单选的级联选择器

### Expected results (期望的结果)
English:
All selected options can be displayed after clicking on the cascader (The picture below is a normal situation where the options do not exceed the selector panel)

Chinese:
点击级联选择器后所有选中的 options 都应该显示（下图是选项没超出选择器面板的正常情况）
![image](https://user-images.githubusercontent.com/53534938/226440873-715fba72-226c-4c4d-adc3-0b981418d91c.png)

### Actual results (实际的结果)
After clicking the cascade selector, except for the last child, the previous options cannot be displayed normally as long as they exceed the selector panel (the options displayed after moving the scroll bar)

点击级联选择器后，除了最后一项，前面的选项只要是超出选择器面板的（移动滚动条后显示的选项），都无法正常显示
![image](https://user-images.githubusercontent.com/53534938/226441533-95e78d1b-f54d-4511-a4d0-a729f2704619.png)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
