### ISSUE TITLE
n-auto-complete组件的select方法报错

### ISSUE THREAD

**Issue by tgy3300** [tusen-ai/naive-ui#4617]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-alpha.4

### Browser and its version (浏览器及其版本)
谷歌最新

### System and its version (系统及其版本)
最新

### Node version (Node 版本)
最新

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/auto-complete#API

### Reappearance steps (重现步骤)
```
<n-auto-complete
							v-model:value="searchValue"
							:options="searchOptions"
							placeholder="输入关键字"
							clear-after-select
							size="large"
							@select="searchShow"
						/>
```
用在ts中，自动填充 Auto Complete组件报错如下：
```
(property) select: MaybeArray<OnSelect> | undefined
不能将类型“(value: string) => void”分配给类型“MaybeArray<OnSelect> | undefined”。
  不能将类型“(value: string) => void”分配给类型“OnSelect”。ts(2322)
```
我的searchShow定义如下：
```
const searchShow = (value: string) => {
	router.push(value)
}
```

### Expected results (期望的结果)
能解决吗

### Actual results (实际的结果)
能解决吗

**Comment by amadeus711** [comment]
未复现，需要 repo

**Comment by jizai1125** [comment]
可以改成
```vue
const searchShow = (value: string | number) => {
	router.push(value)
}
```
