### ISSUE TITLE
restoreValidation 应该提供清除字段的数组，而不是考绑定多个某个 formItemRef

### ISSUE THREAD

**Issue by hairyf** [tusen-ai/naive-ui#4618]
### This function solves the problem (这个功能解决的问题)
使用 formItemRef 是很麻烦的，特别是需要清除多个字段校验的情况下，这在大面积使用会产生很多不必要的代码
### Expected API (期望的 API)
通过 formInstRef 数组关闭简单快捷：
```ts
formInstRef.restoreValidation(['mobileCode', 'mobile'])
```

**Comment by daguanren21** [comment]
> 

请问你这边在restoreValidationAPI不提供可选字段的情况下，是如何解决此场景的呢

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
