### ISSUE TITLE
从windows上传文件时，文件名如果是中文，服务端接受到的为乱码

### ISSUE THREAD

**Issue by xdewx** [tusen-ai/naive-ui#4619]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.46

### Browser and its version (浏览器及其版本)
Edge 111.0.1661.44 (正式版本) (64 位)

### System and its version (系统及其版本)
Windows 11

### Node version (Node 版本)
16

### Reappearance link (重现链接)
https://github.com/tusen-ai/naive-ui/issues/4619

### Reappearance steps (重现步骤)
1. use NUpload
2. upload file from windows, which name is chinese

### Expected results (期望的结果)
期望名字不会乱码

### Actual results (实际的结果)
名字乱码

**Comment by amadeus711** [comment]
编码问题大概率不是组件的问题，排查一下服务器配置或者上传请求配置

**Comment by jizai1125** [comment]
请求头看看 `Content-Type` 编码是不是 utf-8

**Comment by qiuyoo** [comment]
如果文件是 gb2312，那么这个文件就会乱码，好像强制改成utf-8了

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by evelynn996** [comment]
@jahnli 我也有遇到这个问题，参考[RFC文档](https://datatracker.ietf.org/doc/html/rfc6266#section-4.3)
下图是前端n-upload上传的文件的请求头，只有filename，没有filename*，导致中文名的文件名乱码
![image](https://github.com/user-attachments/assets/6a1cf75c-ed7e-4558-8ae5-3d623a6e1e0a)
下图是通过apifox上传文件时的请求头，附带了filename*，此时finename才会被正确编码
![7d4fbb0b27eaf552bf60c22d610f2ebb](https://github.com/user-attachments/assets/5583959e-cde5-4fe8-a9a6-c8efd54ec492)
