### ISSUE TITLE
TabPane组件包含了一个<component>组件时会导致切换Tab每次都触发生命周期

### ISSUE THREAD

**Issue by GrayFaith** [tusen-ai/naive-ui#4626]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.47

### Browser and its version (浏览器及其版本)
谷歌最新

### System and its version (系统及其版本)
windows11

### Node version (Node 版本)
22H2

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/dark/components/tabs

### Reappearance steps (重现步骤)
<n-tabs
		v-if='store["state"]["dynamicAsyncCustomComponentIsReady"]'
		v-model:value='store["state"]["tabs"]["selectedTab"]'
		type='card' animated pane-class='tab-pane-container-height'>
		<n-tab-pane
			v-for='(item,index) in store["state"]["tabs"]["tabs"]'
			:key='item["code"]'
			:closable='"A000" !== item["code"]'
			display-directive='show'
			:name='item["code"]'
			:tab='()=>customLabel(item["title"],item["tabIcon"],item["tabIconType"])'>
			<keep-alive v-if='item["keepAlive"]'>
				<component
					:is='getComponent(item["url"])'
					v-if='item["keepAlive"]'
					v-show='store["state"]["tabs"]["selectedTab"] === item["code"]'
					:params='item["params"]'/>
			</keep-alive>
			<component
				:is='getComponent(item["url"])'
				v-else-if='!item["keepAlive"]'
				v-show='store["state"]["tabs"]["selectedTab"] === item["code"]'
				:params='item["params"]'/>
		</n-tab-pane>
	</n-tabs>

上述代码的问题在于切换Tabs组件的时候,会触发每个动态组件的生命周期;

首先在一个<n-tabs>内放入<n-tab-pane>然后放入<component>组件,然后切换tab,可以看到开发工具栏显示每个被单击的tab都重新触发了对应异步组件的生命周期

无法正常使用<keep-alive>来缓存动态组件的状态,这个问题挺麻烦的,它困扰了我数天了

### Expected results (期望的结果)
我的预期是可以通过<keep-alive>组件来实现内部<component>动态组件的缓存,并且切换tab的时候可以不用重新触发对应<component>的生命周期

### Actual results (实际的结果)
实际上,每次切换tab的时候它都会重新触发<component>的生命周期,这非常的不科学

### Remarks (补充说明)
这个问题希望能够得到解决

**Comment by GrayFaith** [comment]
https://codesandbox.io/s/gallant-sunset-0f1x40?file=/src/componts/index.vue

**Comment by amadeus711** [comment]
![20230324101120](https://user-images.githubusercontent.com/46394163/227406645-505cdf93-9878-4bc7-900e-a4e0132e79f5.gif)

The `Mac` has not reappeared, requiring `Windows` assistance

**Comment by 07akioni** [comment]
例子无法复现

**Comment by wangcn** [comment]
我最近也遇到了。发现在v-for里会触发这种现象。比如这种：
`
<template>
  <n-tabs type="card" animated>
    <n-tab-pane v-for="item in tabs" :key="item.key" :name="item.key" :tab="item.name">
      <component :is="item.component" :key="item.key ? item.key : 'blank'" msg="aaa">
      </component>
    </n-tab-pane>
  </n-tabs>
</template>
`

**Comment by Pozhan-js** [comment]
> 我最近也遇到了。发现在v-for里会触发这种现象。比如这种： `<template> <n-tabs type="card" animated> <n-tab-pane v-for="item in tabs" :key="item.key" :name="item.key" :tab="item.name"> <component :is="item.component" :key="item.key ? item.key : 'blank'" msg="aaa"> </component> </n-tab-pane> </n-tabs> </template>`

因为这里的动态组件获得key,你可以看看vue官网文档,只要key不同都会触发组件的重新渲染
