### ISSUE TITLE
Make clickable drop-down more responsive

### ISSUE THREAD

**Issue by djfuzzy** [tusen-ai/naive-ui#4629]
### This function solves the problem (这个功能解决的问题)
When using a clickable drop-down, when the drop-down is open, losing focus should cause the drop-down to close.
### Expected API (期望的 API)
With the drop-down in focus, on blur, the drop-down is closed.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by djfuzzy** [comment]
This is still an issue

**Comment by jahnli** [comment]
At present, the problem has been submerged, I personally think that only by re-opening a problem can more people see it and be willing to add it. If this problem is closed, I am very sorry and I will re-open it
