### ISSUE TITLE
Make hoverable drop-down more accessible

### ISSUE THREAD

**Issue by djfuzzy** [tusen-ai/naive-ui#4630]
### This function solves the problem (这个功能解决的问题)
When using a hoverable drop-down, it should be able to be opened using the keyboard.
### Expected API (期望的 API)
With the primary element for the hoverable drop-down in focus, pressing enter or space bar should toggle it open and closed, similar to the clickable drop-down.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by djfuzzy** [comment]
This is still an issue. How can one using a screen reader or keyboard without a mouse open a hover?

**Comment by jahnli** [comment]
At present, the problem has been submerged, I personally think that only by re-opening a problem can more people see it and be willing to add it. If this problem is closed, I am very sorry and I will re-open it
