### ISSUE TITLE
Rendering exceptions when `n-descriptions` contain `v-if` and `n-input`

### ISSUE THREAD

**Issue by zguiyang** [tusen-ai/naive-ui#4632]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.7

### Browser and its version (浏览器及其版本)
111.0.5563.65

### System and its version (系统及其版本)
windows11

### Node version (Node 版本)
16.x

### Reappearance link (重现链接)
https://codesandbox.io/s/adoring-varahamihira-w5y8dt?file=/src/Demo.vue

### Reappearance steps (重现步骤)
1. Click the test button in the example to display the phone description item
2. The` n-input` in the phone description is rendered abnormally and the v-model binding is abnormal. so it cannot be entered normally

### Expected results (期望的结果)
No abnormal rendering of phone description items. can input normally

### Actual results (实际的结果)
The` n-input` in the phone description is rendered abnormally and the v-model binding is abnormal. so it cannot be entered normally

**Comment by zguiyang** [comment]
Seems to be a vue bug, upgrade `vue` to **`3.2.47`** on the solution

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
