### ISSUE TITLE
Dialog组件增加按钮位置和大小配置

### ISSUE THREAD

**Issue by neozo** [tusen-ai/naive-ui#4637]
### This function solves the problem (这个功能解决的问题)
希望为Dialog增加按钮的位置和大小配置，虽然用自定义插槽也能弄，加个配置项更灵活点
### Expected API (期望的 API)
Dialog增加配置
button-postion: 'left' | 'center' | 'right'
button-size: 'tiny' | 'small' | 'medium' | 'large'

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
