### ISSUE TITLE
为 <n-config-provider> 增加theme props

### ISSUE THREAD

**Issue by Capybara-sea** [tusen-ai/naive-ui#4638]
### This function solves the problem (这个功能解决的问题)
既然是主题编辑希望可以传入当前的配置，而不是只有默认的。希望能够增加像<n-config-provider>一样的props，能够使编辑器根据当前配置进行编辑。
### Expected API (期望的 API)
props:
theme:  PropType<GlobalTheme | null>
themeOverrides: themeOverrides: PropType<GlobalThemeOverrides | null>

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
