### ISSUE TITLE
Descriptions（描述）支持 content-align

### ISSUE THREAD

**Issue by hairyf** [tusen-ai/naive-ui#4640]
### This function solves the problem (这个功能解决的问题)
n-descriptions-item 无法直接控制 content 的对齐方式，需要更方便的 api 决定内容对齐
### Expected API (期望的 API)
n-descriptions: content-align: left | center | right
![image](https://user-images.githubusercontent.com/49724027/227763502-ed6b2a7e-c9df-470a-9a4f-9e2edb62fe4c.png)

**Comment by jahnli** [comment]
`content-style`
