### ISSUE TITLE
Select 的 options 的 value是number的时候无法触发校验

### ISSUE THREAD

**Issue by kinggq** [tusen-ai/naive-ui#4643]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
107.0.5304.121

### System and its version (系统及其版本)
MacOS(12.3.1)

### Node version (Node 版本)
16.16.0

### Reappearance link (重现链接)
https://codesandbox.io/s/quizzical-austin-xyxgvk?file=/src/App.vue

### Reappearance steps (重现步骤)
Select 选择之前先触发一下校验，让它变成红框，然后在去选择一项，就会发现控件并没有变成正常的，还是显示校验报错的状态。

*value是number的时候会有此问题

### Expected results (期望的结果)
希望value 是number的时候也能按正常处理

### Actual results (实际的结果)
value是number的时候会有此问题

**Comment by lx11573** [comment]
链接少代码吧

**Comment by kinggq** [comment]
> 

并没有啊

**Comment by thibodeauxjl** [comment]
```
rules: {
  pid: [
    {
      validator(rule, value) {
        if (!value) {
          return new Error("A selection is required.")
        } else if (value < 2) {
            return new Error("This selection has a value less than 2. Pick another one. ");
        }
        return true
      },
      trigger: ["blur", "change"]
    }
  ]
}
```

**Comment by lx11573** [comment]
哦，是的，不过文档中说过的，当值为数字时，需要在 rule 中添加 type: 'number' 属性

**Comment by kinggq** [comment]
> 哦，是的，不过文档中说过的，当值为数字时，需要在 rule 中添加 type: 'number' 属性 ![image](https://user-images.githubusercontent.com/12030247/229260221-f5e4dfdb-c207-4f39-80b3-0231911e99df.png)

原来如此，感谢！！！
