### ISSUE TITLE
can't hide/show n-form-item-gi with v-show

### ISSUE THREAD

**Issue by FangDingli** [tusen-ai/naive-ui#4644]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.47

### Browser and its version (浏览器及其版本)
Chrome Dev 113.0.5668.0

### System and its version (系统及其版本)
Windows 11 Pro 22H2

### Node version (Node 版本)
19.6.0

### Reappearance link (重现链接)
https://github.com/FangDingli/naive-ui-grid-bugreport

### Reappearance steps (重现步骤)
In initialize, this component is not show with v-show="false" and it will show with v-show="true".
When you want to hide it again, it's got error in console

### Expected results (期望的结果)
n-form-item-gi can work fine with v-show

### Actual results (实际的结果)
got error in console

**Comment by ottocsb** [comment]
Same question. The utilization of the `:span=0` directive, similar to the conditional statement`v-if`, hinders the usage of the `keep-alive` feature for component persistence. While `v-show` allows the component to remain without triggering a re-render, it cannot be used simultaneously with `:span=x`.

**Comment by ottocsb** [comment]
By employing the "`layout-shift-disabled=true`" attribute, it is possible to use "`v-show`" without issues. However, it should be noted that this approach may compromise the responsiveness of the layout, although no responsiveness-related issues have been encountered thus far.

**Comment by ottocsb** [comment]
#4422

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
