### ISSUE TITLE
When the 'inline' attribute is applied to the 'form' component, the 'select' component does not have a menu width.

### ISSUE THREAD

**Issue by EnlonW** [tusen-ai/naive-ui#4645]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.47

### Browser and its version (浏览器及其版本)
Chrome(111.0.5563.64)

### System and its version (系统及其版本)
MacOs(12.4)

### Node version (Node 版本)
v18.15.0

### Reappearance link (重现链接)
https://codesandbox.io/s/determined-cookies-9wuded?file=/src/Demo.vue

### Reappearance steps (重现步骤)
Please check the link.

### Expected results (期望的结果)
Same as input, has width.

### Actual results (实际的结果)
No menu width

**Comment by VanillaZen** [comment]
![image](https://user-images.githubusercontent.com/85759660/227836091-81390d06-eec3-4a64-ab88-d2302f50796e.png)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
