### ISSUE TITLE
n-date-picker 组件设置 type=month 类型时，使用 is-date-disabled 函数禁用日期不符合预期

### ISSUE THREAD

**Issue by Zheng-Changfu** [tusen-ai/naive-ui#4649]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.36

### Browser and its version (浏览器及其版本)
Chrome(111.0.5563.64)

### System and its version (系统及其版本)
MacOS(10.15.7)

### Node version (Node 版本)
14.18.1

### Reappearance link (重现链接)
https://codesandbox.io/embed/sweet-tesla-8iqo92?fontsize=14&hidenavigation=1&theme=dark

### Reappearance steps (重现步骤)
1. 打开提供的链接
2. 等待页面渲染显示就可以看到问题
3. 问题代码在 demo.vue 文件

### Expected results (期望的结果)
期待小于 2022-01-05 的月份禁用掉，并且如果一年中所有的月份都禁用掉,那么这一年也要被禁用

### Actual results (实际的结果)
实际除了 2022-01 月份被禁用，2022 年也被禁用了

### Remarks (补充说明)
我自己的分析：我查看了这一块的实现代码(src/date-picker/src/panel/month.tsx)，发现`年`的时间戳为`年-01-01`（例:2022年,时间戳为`2022-01-01`的时间戳），那么我在通过 `is-date-disabled` 方法判断的时候无法区分`年/月`类型，所以导致了这个问题

我期望：可以在调用 `is-date-disabled` 方法时除了传递 `ts（时间戳）`,在传递一个 `item` 选项,包含了当前节点的具体信息(例：里面有 `type` 信息)

**Comment by thibodeauxjl** [comment]
I understand the problem, but I don't understand the logic as to why this functionality is needed.  You are trying to select a month. Your timestamp is 2022-01-05..  and you want to disable everything prior to that.. based on months. 2022-01-04 is prior to 2022-01-05 which would then disable the month of January. I could understand the programmatic error if you were trying to select a date. Why not just find the beginning of the month of 2022-01-05 and disable the previous months.

```
const minTs = new Date(1641312000000); // 2022-01-05
const month = new Date(minTs.getFullYear(), minTs.getMonth(), 1); //2022-01-01
return ts < month;   // is ts less than 2022-01-01
```

This in return will disable every date prior to 2022-01-01 and allowing you to select January of 2022.

**Comment by Zheng-Changfu** [comment]
我想尝试选择某年的3月份，假设为 (2022-03-01)，那么我想禁用的是 2022 之前的所有年，包括 2022 的 1 月份和 2 月份，但是不能禁用 2022 ，因为这样的话，我就不能选择 2022 的 3 月份了&nbsp;


从头来过
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月1日(星期六) 上午6:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tusen-ai/naive-ui] n-date-picker 组件设置 type=month 类型时，使用 is-date-disabled 函数禁用日期不符合预期 (Issue #4649)






我明白这个问题，但我不明白为什么需要这个功能的逻辑。您正在尝试选择一个月。您的时间戳是2022-01-05..  而你想禁用之前的一切..按月计算。2022-01-04先于2022-01-05这将使一月份失效。我可以理解程序错误，如果你试图选择一个日期。为什么不干脆找一个月初的2022-01-05并禁用前几个月的
const minTs=new Date（1641312000000）；//2022-01-05const month=new Date（minTs.get Full Year（），minTs.get Month（），1）；//2022-01-01返回ts《month；//是否小于2022-01-01
作为回报，这将禁用之前的每个日期2022-01-01并允许您选择2022年1月。

—
直接回复这封邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.

**Comment by Zheng-Changfu** [comment]
> Nevermind.. I see the disfunction.
> 
> Even with like 2022-03-01.. All of 2022 is disabled and not just 2022-02 and 2022-01. Definitely a bug.

我想尝试选择某年的3月份，假设为 (2022-03-01)，那么我想禁用的是 2022 之前的所有年，包括 2022 的 1 月份和 2 月份，但是不能禁用 2022 ，因为这样的话，我就不能选择 2022 的 3 月份了

**Comment by luke358** [comment]
> > Nevermind.. I see the disfunction.
> > Even with like 2022-03-01.. All of 2022 is disabled and not just 2022-02 and 2022-01. Definitely a bug.
> 
> 我想尝试选择某年的3月份，假设为 (2022-03-01)，那么我想禁用的是 2022 之前的所有年，包括 2022 的 1 月份和 2 月份，但是不能禁用 2022 ，因为这样的话，我就不能选择 2022 的 3 月份了

我觉得那个year的数据直接用那一年的最后一天以后一秒的`ts`，就可以解决所有的情况

**Comment by luke358** [comment]
> > Nevermind.. I see the disfunction.
> > Even with like 2022-03-01.. All of 2022 is disabled and not just 2022-02 and 2022-01. Definitely a bug.
> 
> 我想尝试选择某年的3月份，假设为 (2022-03-01)，那么我想禁用的是 2022 之前的所有年，包括 2022 的 1 月份和 2 月份，但是不能禁用 2022 ，因为这样的话，我就不能选择 2022 的 3 月份了

year的数据或许可以使用那一年的最后一天最后一秒的`ts`

**Comment by g-plane** [comment]
我们也遇到了这个问题。因为要修复这个 bug 会可能涉及到 API 更改，所以我们只在项目内部做 patch，没有回馈给上游。

以下 patch 供参考：

```diff
diff --git a/es/date-picker/src/interface.d.ts b/es/date-picker/src/interface.d.ts
index d771439237929f8565f8abf605adb4163ec8e4b2..0fba51524c4912b53adf0ca745ef65e42cef4448 100644
--- a/es/date-picker/src/interface.d.ts
+++ b/es/date-picker/src/interface.d.ts
@@ -68,7 +68,7 @@ export type DatePickerInjection = {
 } & ReturnType<typeof uniCalendarValidation> & ReturnType<typeof dualCalendarValidation>;
 export declare const datePickerInjectionKey: import("vue").InjectionKey<DatePickerInjection>;
 export type IsDateDisabled = IsSingleDateDisabled | IsRangeDateDisabled;
-export type IsSingleDateDisabled = (date: number) => boolean;
+export type IsSingleDateDisabled = (date: number, position: undefined, value: undefined, type: 'date' | 'month' | 'year' | 'quarter') => boolean;
 export type IsRangeDateDisabled = (date: number, position: 'start' | 'end', value: [number, number] | null) => boolean;
 export interface TimeValidator {
     isHourDisabled?: IsHourDisabled;
@@ -76,7 +76,7 @@ export interface TimeValidator {
     isSecondDisabled?: IsSecondDisabled;
 }
 export type IsTimeDisabled = IsSingleTimeDisabled | IsRangeTimeDisabled;
-export type IsSingleTimeDisabled = (date: number) => TimeValidator;
+export type IsSingleTimeDisabled = (date: number, position: undefined, value: undefined, type: 'date' | 'month' | 'year' | 'quarter') => TimeValidator;
 export type IsRangeTimeDisabled = (date: number, position: 'start' | 'end', value: [number, number]) => TimeValidator;
 export interface DatePickerInst {
     focus: () => void;
diff --git a/es/date-picker/src/panel/date.js b/es/date-picker/src/panel/date.js
index c87995c743b9407bbcfe9218efb262e7694f4768..b26fcfe9afd6a59ccafd365b80c7eb4389c4daa7 100644
--- a/es/date-picker/src/panel/date.js
+++ b/es/date-picker/src/panel/date.js
@@ -49,7 +49,7 @@ export default defineComponent({
                             [`${mergedClsPrefix}-date-panel-date--current`]: dateItem.isCurrentDate,
                             [`${mergedClsPrefix}-date-panel-date--selected`]: dateItem.selected,
                             [`${mergedClsPrefix}-date-panel-date--excluded`]: !dateItem.inCurrentMonth,
-                            [`${mergedClsPrefix}-date-panel-date--disabled`]: this.mergedIsDateDisabled(dateItem.ts)
+                            [`${mergedClsPrefix}-date-panel-date--disabled`]: this.mergedIsDateDisabled(dateItem)
                         }
                     ], onClick: () => this.handleDateClick(dateItem) },
                     h("div", { class: `${mergedClsPrefix}-date-panel-date__trigger` }),
diff --git a/es/date-picker/src/panel/datetime.js b/es/date-picker/src/panel/datetime.js
index 9412f374bf1b391b00f5988730314f54a0ff9015..738bf2d7f453160fcc8935d9097961cccaa58ac5 100644
--- a/es/date-picker/src/panel/datetime.js
+++ b/es/date-picker/src/panel/datetime.js
@@ -46,7 +46,7 @@ export default defineComponent({
                             [`${mergedClsPrefix}-date-panel-date--current`]: dateItem.isCurrentDate,
                             [`${mergedClsPrefix}-date-panel-date--selected`]: dateItem.selected,
                             [`${mergedClsPrefix}-date-panel-date--excluded`]: !dateItem.inCurrentMonth,
-                            [`${mergedClsPrefix}-date-panel-date--disabled`]: this.mergedIsDateDisabled(dateItem.ts)
+                            [`${mergedClsPrefix}-date-panel-date--disabled`]: this.mergedIsDateDisabled(dateItem)
                         }
                     ], onClick: () => this.handleDateClick(dateItem) },
                     h("div", { class: `${mergedClsPrefix}-date-panel-date__trigger` }),
diff --git a/es/date-picker/src/panel/month.js b/es/date-picker/src/panel/month.js
index 4f73718a292b5119b9dbc89866a0632d3e4c4fbc..40a18d7bbc92b335bbd5642737426e723cb2a3fa 100644
--- a/es/date-picker/src/panel/month.js
+++ b/es/date-picker/src/panel/month.js
@@ -38,7 +38,7 @@ export default defineComponent({
                     {
                         [`${mergedClsPrefix}-date-panel-month-calendar__picker-col-item--current`]: item.isCurrent,
                         [`${mergedClsPrefix}-date-panel-month-calendar__picker-col-item--selected`]: item.selected,
-                        [`${mergedClsPrefix}-date-panel-month-calendar__picker-col-item--disabled`]: !useAsQuickJump && mergedIsDateDisabled(item.ts)
+                        [`${mergedClsPrefix}-date-panel-month-calendar__picker-col-item--disabled`]: !useAsQuickJump && mergedIsDateDisabled(item)
                     }
                 ], onClick: () => {
                     useAsQuickJump
diff --git a/es/date-picker/src/panel/use-calendar.js b/es/date-picker/src/panel/use-calendar.js
index 4981b14637b1a140db8de7e8bea6d87cf0e0f9bb..900d567ebd9bd065a6b01546014490896c6003b1 100644
--- a/es/date-picker/src/panel/use-calendar.js
+++ b/es/date-picker/src/panel/use-calendar.js
@@ -90,11 +90,11 @@ function useCalendar(props, type) {
             return getTime(startOfQuarter(value));
         return getTime(startOfDay(value));
     }
-    function mergedIsDateDisabled(ts) {
+    function mergedIsDateDisabled(dateItem) {
         const { isDateDisabled: { value: isDateDisabled } } = validation;
         if (!isDateDisabled)
             return false;
-        return isDateDisabled(ts);
+        return isDateDisabled(dateItem.ts, undefined, undefined, dateItem.type);
     }
     function handleDateInput(value) {
         const date = strictParse(value, mergedDateFormatRef.value, new Date(), panelCommon.dateFnsOptions.value);
@@ -152,7 +152,7 @@ function useCalendar(props, type) {
         }
     }
     function handleDateClick(dateItem) {
-        if (mergedIsDateDisabled(dateItem.ts)) {
+        if (mergedIsDateDisabled(dateItem)) {
             return;
         }
         let newValue;
```

如果要应用上面的 patch，要注意在使用组件的时候，修改传给 `is-date-disabled` 的回调：第一个参数之前是 timestamp，应用 patch 之后会变成一个 object。

**Comment by 1071125093** [comment]
催更催更

**Comment by Mobaiyufengfei** [comment]
> 我们也遇到了这个问题。因为要修复这个 bug 会可能涉及到 API 更改，所以我们只在项目内部做 patch，没有回馈给上游。
> 
> 以下 patch 供参考：
> 
> ```diff
> diff --git a/es/date-picker/src/interface.d.ts b/es/date-picker/src/interface.d.ts
> index d771439237929f8565f8abf605adb4163ec8e4b2..0fba51524c4912b53adf0ca745ef65e42cef4448 100644
> --- a/es/date-picker/src/interface.d.ts
> +++ b/es/date-picker/src/interface.d.ts
> @@ -68,7 +68,7 @@ export type DatePickerInjection = {
>  } & ReturnType<typeof uniCalendarValidation> & ReturnType<typeof dualCalendarValidation>;
>  export declare const datePickerInjectionKey: import("vue").InjectionKey<DatePickerInjection>;
>  export type IsDateDisabled = IsSingleDateDisabled | IsRangeDateDisabled;
> -export type IsSingleDateDisabled = (date: number) => boolean;
> +export type IsSingleDateDisabled = (date: number, position: undefined, value: undefined, type: 'date' | 'month' | 'year' | 'quarter') => boolean;
>  export type IsRangeDateDisabled = (date: number, position: 'start' | 'end', value: [number, number] | null) => boolean;
>  export interface TimeValidator {
>      isHourDisabled?: IsHourDisabled;
> @@ -76,7 +76,7 @@ export interface TimeValidator {
>      isSecondDisabled?: IsSecondDisabled;
>  }
>  export type IsTimeDisabled = IsSingleTimeDisabled | IsRangeTimeDisabled;
> -export type IsSingleTimeDisabled = (date: number) => TimeValidator;
> +export type IsSingleTimeDisabled = (date: number, position: undefined, value: undefined, type: 'date' | 'month' | 'year' | 'quarter') => TimeValidator;
>  export type IsRangeTimeDisabled = (date: number, position: 'start' | 'end', value: [number, number]) => TimeValidator;
>  export interface DatePickerInst {
>      focus: () => void;
> diff --git a/es/date-picker/src/panel/date.js b/es/date-picker/src/panel/date.js
> index c87995c743b9407bbcfe9218efb262e7694f4768..b26fcfe9afd6a59ccafd365b80c7eb4389c4daa7 100644
> --- a/es/date-picker/src/panel/date.js
> +++ b/es/date-picker/src/panel/date.js
> @@ -49,7 +49,7 @@ export default defineComponent({
>                              [`${mergedClsPrefix}-date-panel-date--current`]: dateItem.isCurrentDate,
>                              [`${mergedClsPrefix}-date-panel-date--selected`]: dateItem.selected,
>                              [`${mergedClsPrefix}-date-panel-date--excluded`]: !dateItem.inCurrentMonth,
> -                            [`${mergedClsPrefix}-date-panel-date--disabled`]: this.mergedIsDateDisabled(dateItem.ts)
> +                            [`${mergedClsPrefix}-date-panel-date--disabled`]: this.mergedIsDateDisabled(dateItem)
>                          }
>                      ], onClick: () => this.handleDateClick(dateItem) },
>                      h("div", { class: `${mergedClsPrefix}-date-panel-date__trigger` }),
> diff --git a/es/date-picker/src/panel/datetime.js b/es/date-picker/src/panel/datetime.js
> index 9412f374bf1b391b00f5988730314f54a0ff9015..738bf2d7f453160fcc8935d9097961cccaa58ac5 100644
> --- a/es/date-picker/src/panel/datetime.js
> +++ b/es/date-picker/src/panel/datetime.js
> @@ -46,7 +46,7 @@ export default defineComponent({
>                              [`${mergedClsPrefix}-date-panel-date--current`]: dateItem.isCurrentDate,
>                              [`${mergedClsPrefix}-date-panel-date--selected`]: dateItem.selected,
>                              [`${mergedClsPrefix}-date-panel-date--excluded`]: !dateItem.inCurrentMonth,
> -                            [`${mergedClsPrefix}-date-panel-date--disabled`]: this.mergedIsDateDisabled(dateItem.ts)
> +                            [`${mergedClsPrefix}-date-panel-date--disabled`]: this.mergedIsDateDisabled(dateItem)
>                          }
>                      ], onClick: () => this.handleDateClick(dateItem) },
>                      h("div", { class: `${mergedClsPrefix}-date-panel-date__trigger` }),
> diff --git a/es/date-picker/src/panel/month.js b/es/date-picker/src/panel/month.js
> index 4f73718a292b5119b9dbc89866a0632d3e4c4fbc..40a18d7bbc92b335bbd5642737426e723cb2a3fa 100644
> --- a/es/date-picker/src/panel/month.js
> +++ b/es/date-picker/src/panel/month.js
> @@ -38,7 +38,7 @@ export default defineComponent({
>                      {
>                          [`${mergedClsPrefix}-date-panel-month-calendar__picker-col-item--current`]: item.isCurrent,
>                          [`${mergedClsPrefix}-date-panel-month-calendar__picker-col-item--selected`]: item.selected,
> -                        [`${mergedClsPrefix}-date-panel-month-calendar__picker-col-item--disabled`]: !useAsQuickJump && mergedIsDateDisabled(item.ts)
> +                        [`${mergedClsPrefix}-date-panel-month-calendar__picker-col-item--disabled`]: !useAsQuickJump && mergedIsDateDisabled(item)
>                      }
>                  ], onClick: () => {
>                      useAsQuickJump
> diff --git a/es/date-picker/src/panel/use-calendar.js b/es/date-picker/src/panel/use-calendar.js
> index 4981b14637b1a140db8de7e8bea6d87cf0e0f9bb..900d567ebd9bd065a6b01546014490896c6003b1 100644
> --- a/es/date-picker/src/panel/use-calendar.js
> +++ b/es/date-picker/src/panel/use-calendar.js
> @@ -90,11 +90,11 @@ function useCalendar(props, type) {
>              return getTime(startOfQuarter(value));
>          return getTime(startOfDay(value));
>      }
> -    function mergedIsDateDisabled(ts) {
> +    function mergedIsDateDisabled(dateItem) {
>          const { isDateDisabled: { value: isDateDisabled } } = validation;
>          if (!isDateDisabled)
>              return false;
> -        return isDateDisabled(ts);
> +        return isDateDisabled(dateItem.ts, undefined, undefined, dateItem.type);
>      }
>      function handleDateInput(value) {
>          const date = strictParse(value, mergedDateFormatRef.value, new Date(), panelCommon.dateFnsOptions.value);
> @@ -152,7 +152,7 @@ function useCalendar(props, type) {
>          }
>      }
>      function handleDateClick(dateItem) {
> -        if (mergedIsDateDisabled(dateItem.ts)) {
> +        if (mergedIsDateDisabled(dateItem)) {
>              return;
>          }
>          let newValue;
> ```

为啥这么搞不起作用，具体的disabled方法是啥啊，是把原来的return ts<startDate变成return 一个对象吗

**Comment by Mobaiyufengfei** [comment]
为啥像上面那样打补丁不起作用，具体的disabled方法是啥啊，是把原来的return ts<startDate变成return 一个对象吗

**Comment by 07akioni** [comment]
Let me see.

**Comment by Soporior** [comment]
遇到了惹  催更
