### ISSUE TITLE
upload组件在开发环境中，控制台出现警告

### ISSUE THREAD

**Issue by zguiyang** [tusen-ai/naive-ui#4654]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.47

### Browser and its version (浏览器及其版本)
111.0.5563.111

### System and its version (系统及其版本)
Windows11

### Node version (Node 版本)
16.x

### Reappearance link (重现链接)
https://codesandbox.io/s/goofy-beaver-h060j2?file=/src/Demo.vue:240-251

### Reappearance steps (重现步骤)
开发环境使用upload组件，控制台会出现警告

### Expected results (期望的结果)
控制台无警告

### Actual results (实际的结果)
控制台出现警告
<img width="447" alt="image" src="https://user-images.githubusercontent.com/24975063/228206175-6ffbe1b8-f2b6-49a6-9eae-6bd9be330635.png">

**Comment by 07akioni** [comment]
fixed in https://github.com/tusen-ai/naive-ui/pull/4479/
