### ISSUE TITLE
tabs组件报错

### ISSUE THREAD

**Issue by tgy3300** [tusen-ai/naive-ui#4655]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-alpha.5

### Browser and its version (浏览器及其版本)
谷歌最新

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/tabs#basic.vue

### Reappearance steps (重现步骤)
```
<n-tabs
			type="line"
			animated
		>
			<n-tab-pane
				name="oasis"
				tab="Oasis"
			>
				Wonderwall
			</n-tab-pane>
		</n-tabs>
```

报错如下：
`[Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952`

### Expected results (期望的结果)
这个如何解决

### Actual results (实际的结果)
这个如何解决

### Remarks (补充说明)

也不能说报错吧，就是谷歌浏览器有这个提示

**Comment by amadeus711** [comment]
When we implementing the functions of some components, some wheel events need to be blocked, in which case we can ensure that they are controllable. Browsers are afraid of a large number of uncontrollable behaviors that may affect performance, so they will prompt a warning.
