### ISSUE TITLE
a bug in utils function `useLockHtmlScroll`

### ISSUE THREAD

**Issue by Dedicatus546** [tusen-ai/naive-ui#4657]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.47

### Browser and its version (浏览器及其版本)
最新

### System and its version (系统及其版本)
win11

### Node version (Node 版本)
最新

### Reappearance link (重现链接)
https://github.com/Dedicatus546/naive-useLockHtmlScroll-bug

### Reappearance steps (重现步骤)
start dev server.

click trigger button. 

the html scroll will not be locked.

### Expected results (期望的结果)
the html scroll will be locked.

### Actual results (实际的结果)
the html scroll will not be locked.

### Remarks (补充说明)
there are more details in reproduction README file.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
