### ISSUE TITLE
input组件在设置type=textarea，autosize 且触发滚动后用v-if进行切换时会在Safari有警告和刷新页面现象

### ISSUE THREAD

**Issue by jyp0912** [tusen-ai/naive-ui#4660]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Safari 14.1.3 

### System and its version (系统及其版本)
MacOS 11.7.5

### Reappearance link (重现链接)
https://codesandbox.io/s/great-varahamihira-r5sduq

### Reappearance steps (重现步骤)
在textarea中输入足够内容触发滚动条后，使用v-if的按钮进行显隐切换

### Expected results (期望的结果)
正常切换

### Actual results (实际的结果)
页面刷新

### Remarks (补充说明)
警告信息：ResizeObserver loop completed with undelivered notifications.
页面重新载入于上午10:30:22
![image](https://user-images.githubusercontent.com/50137176/228724238-1a95ff91-52bc-421d-b86f-d230d2845cb3.png)

**Comment by amadeus711** [comment]
![20230331100621](https://user-images.githubusercontent.com/46394163/229004622-81c4e84e-93cf-499b-a50c-8c0b72666516.gif)
MacOS 12.5.1  |  Safari 15.6.1
无复现，需要排查更低版本

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
