### ISSUE TITLE
dataTable支持行修改校验

### ISSUE THREAD

**Issue by poyoho** [tusen-ai/naive-ui#4662]
### This function solves the problem (这个功能解决的问题)
文档上面有dataTable列变换编辑，能不能支持每行修改校验。

### Expected API (期望的 API)
支持table校验，好像form一样，错误在input下面给错误提示。😁

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by poyoho** [comment]
ok. I tinker the data table `NInput` change to `n-form-item > NInput` can resolve my issues.
