### ISSUE TITLE
希望Dropdown可以增加slots插槽

### ISSUE THREAD

**Issue by huyuan9479** [tusen-ai/naive-ui#4663]
### This function solves the problem (这个功能解决的问题)
由于Dropdown限制的不太灵活，希望Dropdown可以增加slots插槽，自定义按钮
### Expected API (期望的 API)
slots

**Comment by amadeus711** [comment]
具体哪个图标？多级的图标？

**Comment by amadeus711** [comment]
现在的按钮就是自定义的，default slots

**Comment by CHYYHC123** [comment]
下拉菜单里面展示的内容，除了使用提供的函数方法渲染，可以直接写类似div标签进行渲染吗

**Comment by fudiwei** [comment]
毛遂自荐 [@skit/x.naive-ui](https://github.com/fudiwei/x.naive-ui)，基于 Naive-UI 二次封装了 Dropdown 组件，支持插槽式的写法。

**Comment by shiny** [comment]
现在的写法没有 slot 写法直观、容易维护

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
