### ISSUE TITLE
评分选中的星错位显示

### ISSUE THREAD

**Issue by daiyuelin** [tusen-ai/naive-ui#4664]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-alpha.6

### Browser and its version (浏览器及其版本)
111.0.5563.146

### System and its version (系统及其版本)
mac

### Node version (Node 版本)
v16.15.1

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/rate

### Reappearance steps (重现步骤)
第一次进入系统评分显示的星错位显示两行

### Expected results (期望的结果)
第一次进入系统评分显示的星错位显示两行

### Actual results (实际的结果)
第一次进入系统评分显示的星错位显示两行

### Remarks (补充说明)
第一次进入系统评分显示的星错位显示两行

**Comment by amadeus711** [comment]
未复现，需提供沙盒环境下的最小复现，先排查一下是否受使用处样式影响

**Comment by jahnli** [comment]
Closed due to inactivity. Feel free to reopen if you're still having trouble
