### ISSUE TITLE
Loading props for description

### ISSUE THREAD

**Issue by hi-reeve** [tusen-ai/naive-ui#4665]
### This function solves the problem (这个功能解决的问题)
adding an loading props for description/description item so that if the loading props is true, it is automatically change to skeleton, also adding slots for the skeleton loading for dynamic content.
### Expected API (期望的 API)
<n-description :loading="loading">
<n-description-item>
{{asyncData}}
<template #loading>
<span>Loading...</span>
</template>
</n-description-item>
</n-description

**Comment by Sepush** [comment]
use skeleton and https://vuejs.org/guide/built-ins/suspense.html#events

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
