### ISSUE TITLE
使用Drawer组件并使用了closable属性能不能添加一个关闭前的回调函数

### ISSUE THREAD

**Issue by wjw020206** [tusen-ai/naive-ui#4669]
### This function solves the problem (这个功能解决的问题)
解决了缺少一个关闭前没有的回调的问题
### Expected API (期望的 API)
使用Drawer组件并使用了closable属性，此时Drawer组件会生成一个关闭按钮，当我点击这个关闭按钮前可以触发回调，在我确认弹出框完成之后再进行是否关闭处理，这个问题的回答之前在#1571看到过，我也尝试该方法，但是每当我点击关闭按钮，它仍然是关闭，似乎只有自己写的关闭按钮才能阻止它进行关闭，Drawer组件并使用了closable属性自带的关闭按钮无法阻止它的关闭

**Comment by wjw020206** [comment]
> 我是用计算属性解决的，你目前可以参考下
> 
> ```
>  <n-drawer v-model:show="show" ></n-drawer>
> const close = ref(false);
>  const show = computed({
>     get: () => {
>       return close.value;
>     },
>     set: (val) => {
>       if (!val && close.value) {
>         执行你的代码
>       } else {
>         close.value = val;
>       }
>     },
>   });```
> ```

非常感谢你的回复，我的需求是这样的，点击 n-drawer 的关闭按钮(closable属性所生成的)，先弹出对话框让用户选择是否保存修改，如果用户选择是再关闭 n-drawer，我看你发的代码似乎用的不是 n-drawer 的关闭按钮(closable属性所生成的)，请问你的n-drawer 关闭的按钮是用自己写的吗？

**Comment by TiggerYuan** [comment]
```
 if (!val && close.value){
        执行你的代码
      }
```
在"执行你的代码"这里放入

```
 useDialog().warning({
          title: '警告',
          content: '你确定？',
          positiveText: '确定',
          negativeText: '不确定',
          onPositiveClick: () => {
            ///在这里修改 close，前提是响应没丢失，就能在点确认后关闭
              close.value=false
          },
          onNegativeClick: () => {
            message.error('不确定')
          }
        })
```
n-drawer 的关闭按钮(closable属性所生成的)的按钮也会执行这里的

**Comment by jizai1125** [comment]
如果需要代码控制显隐的话，可以将 `v-model:show` 拆成 `show` 与 `on-update:show` 的形式，这样就可以在 on-update:show 函数里去做控制了
```vue
<template>
  <n-drawer :show="show" @update:show="handleShowUpdate">
  </n-drawer>
</template>
<script setup lang="ts">
import { ref } from 'vue'

const show = ref(false)

function handleShowUpdate (value) {
    // show.value = value
}
</script>
```

**Comment by wjw020206** [comment]
> 

谢谢你的回复，我试试

**Comment by wjw020206** [comment]
> 如果需要代码控制显隐的话，可以将 `v-model:show` 拆成 `xxx` 与 `on-update:xxx` 的形式，这样就可以在 `on-update:xxx` 函数里去做控制了
> 
> ```
> <template>
>   <n-drawer :show="show" @update:show="handleShowUpdate">
>   </n-drawer>
> </template>
> <script setup lang="ts">
> import { ref } from 'vue'
> 
> const show = ref(false)
> 
> function handleShowUpdate (value) {
>     // show.value = value
> }
> </script>
> ```


谢谢你的回复，我试试
