### ISSUE TITLE
n-tabs support drag 支持托拽功能

### ISSUE THREAD

**Issue by eagleoflqj** [tusen-ai/naive-ui#4671]
### This function solves the problem (这个功能解决的问题)
In VSCode, you can drag a file tab to re-arrange order
类似VSCode文件标签的托拽排序
### Expected API (期望的 API)
draggable: boolean

**Comment by tiny-craft** [comment]
同样希望有这个功能~

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
