### ISSUE TITLE
AutoComplete - add option to disable auto selection of first matching option in menu

### ISSUE THREAD

**Issue by linkurzweg** [tusen-ai/naive-ui#4674]
### This function solves the problem (这个功能解决的问题)
Sometimes when using the AutoComplete component we may want to use it like a combination of a search input and an auto complete. The behavior would be like the Google search for example. If you type something and hit Enter, a search is triggered, regardless of the options in the autocomplete menu.

"With naive-ui's AutoComplete this is not possible currently. When typing and hitting Enter the first entry of the menu is always selected automatically. I would like a prop to disable this behavior and only select entries in the menu via the arrow keys or with the mouse.
### Expected API (期望的 API)
`<n-auto-complete :auto-select="false" />`

**Comment by johnson0903** [comment]
Is there any update?

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by linkurzweg** [comment]
> This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

The problem still persists. I'm not sure how a minimal reproduction of this is supposed to look. You could just open the docs for the autocomplete component and it's perfectly clear that there is no option to disable auto selection of the first item: https://www.naiveui.com/en-US/os-theme/components/auto-complete

**Comment by linkurzweg** [comment]
For anyone interested, I found a workaround. It is quite hacky though. I wish I wouldn't have to do it this way and just to have an option on the component for this.

Here's my code:
````
<template>
<div ref="cardWrapperRef" class="card-wrapper">
    <NCard>
      <NAutoComplete ref="autocompleteRef" ... >
        <template #default="{ handleInput, handleBlur, handleFocus, value: slotValue }">
          <NInput
            ref="inputRef"
            :value="slotValue"
            @input="handleInput"
            @focus="handleFocus"
            @blur="handleBlur"
            ...
          >
              ...
          </NInput>
          ...
        </template>
      </NAutoComplete>
      ...
</template>
<script setup lang="ts">
...
  const inputRef = ref<InstanceType<typeof NInput>>()
  const cardWrapperRef = ref<HTMLElement>()
  const autocompleteRef = ref<InstanceType<typeof NAutoComplete>>()

  // Hacky way to make the autocomplete work as desired with naive-ui
  // See https://github.com/tusen-ai/naive-ui/issues/4674

  const isFocused = ref(false)

  const onUpdateValue = (value: string) => {
    input.value = value
    if (value) {
      isFocused.value = true
      cardWrapperRef.value?.classList.add('search-focused')
    }
  }

  const onFocus = () => {
    isFocused.value = true
    cardWrapperRef.value?.classList.add('search-focused')
  }

  const onBlur = () => {
    isFocused.value = false
    cardWrapperRef.value?.classList.remove('search-focused')
  }

  const removeFocusClass = () => {
    cardWrapperRef.value?.classList.remove('search-focused')
  }

  onMounted(() => {
    if (autocompleteRef.value) {
      autocompleteRef.value.handleKeyDown = (e: KeyboardEvent) => {
        switch (e.key) {
          case 'Enter': {
            const pendingOptionTmNode = autocompleteRef.value?.menuInstRef?.getPendingTmNode()
            if (pendingOptionTmNode?.rawNode.label && !isFocused.value) {
              input.value = pendingOptionTmNode.rawNode.label as string
              e.preventDefault()
            }
            break
          }

          case 'ArrowDown':
            if (input.value && isFocused.value) {
              isFocused.value = false
            } else {
              autocompleteRef.value?.menuInstRef?.next()
            }
            break

          case 'ArrowUp':
            e.preventDefault()
            if (input.value && isFocused.value) {
              isFocused.value = false
              autocompleteRef.value?.menuInstRef?.prev()
            } else {
              autocompleteRef.value?.menuInstRef?.prev()
            }
            break
        }
      }
    }
  })
</script>
````

**Comment by daxiaraoming** [comment]
My solution: **Set the NAutoComplete's options to a computed value with NInput's value at the first place.**

**Comment by linkurzweg** [comment]
> My solution: **Set the NAutoComplete's options to a computed value with NInput's value at the first place.**

That's also a good solution. But then you have an extra option label that just repeats the input value, which might not be desired visually.
