### ISSUE TITLE
data-table组件中，pagination属性存在bug: 无论如何配置pageSize/pageCount,都只有1页，不能正常展示分页数据，而pagination组件本身是可以的。

### ISSUE THREAD

**Issue by jsoncode** [tusen-ai/naive-ui#4675]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
111.0.5563.146

### System and its version (系统及其版本)
13.0.1 (22A400)

### Node version (Node 版本)
v16.19.0

### Reappearance link (重现链接)
https://codesandbox.io/p/sandbox/modest-sound-3lxy9n?file=%2Fsrc%2FApp.vue

### Reappearance steps (重现步骤)
1. 新建vue项目
2. yarn install naive-ui
3. 添加 n-data-table 和 n-pagination 组件 , 并配置 pageSize and pageCount

### Expected results (期望的结果)
n-data-table中的分页应该和n-pagination显示保持一致

### Actual results (实际的结果)
现在的n-data-table中的分页和n-pagination中显示不一样

### Remarks (补充说明)
同样，在n-data-table中配置itemCount也是一样无效

**Comment by jsoncode** [comment]
有一个remote属性，我忽略了。

```
<n-data-table
  :remote="true"
  :pagination="{}"
/>
```
> 在非异步状况下，页面的数量是由数据的数量决定的，即使传入 page-count 也不会生效，如果你希望这么做，那么需要设定 `remote` 属性。

**Comment by Enaium** [comment]
> 有一个remote属性，我忽略了。
> 
> ```
> <n-data-table
>   :remote="true"
>   :pagination="{}"
> />
> ```
> 
> > 在非异步状况下，页面的数量是由数据的数量决定的，即使传入 page-count 也不会生效，如果你希望这么做，那么需要设定 `remote` 属性。

我加了这个也没用，只有在页面热更新后才会正常，但刷新一下页面又不正常了

**Comment by yxzlwz** [comment]
> 有一个remote属性，我忽略了。
> 
> ```
> <n-data-table
>   :remote="true"
>   :pagination="{}"
> />
> ```
> 
> > 在非异步状况下，页面的数量是由数据的数量决定的，即使传入 page-count 也不会生效，如果你希望这么做，那么需要设定 `remote` 属性。

终于解决我的问题了，感谢大佬！

**Comment by y377** [comment]
> :remote="true"

害的整整搞了5小时，GPT都被干翻车了，无奈搜了一下issue，找到了大佬的方法，感谢！

**Comment by BoyChai** [comment]
不是哥哥们 为什么我这不行
```template
<div style="height: 620px; width: 90%; overflow-y: auto">
              <n-data-table
                :remote="true"
                :bordered="false"
                :single-line="false"
                :columns="columns"
                :data="data"
                :pagination="pagination"
              />
            </div>
```
```script
// 分页展示
const pagination = ref({
  page: 1,
  pageSize: 10,
  itemCount: 10,
  //   showSizePicker: true,
  //   pageSizes: [3, 5, 7],
  onChange: (page) => {
    paginationReactive.page = page;
  },
  onUpdatePageSize: (pageSize) => {
    pagination.value.pageSize = pageSize;
    pagination.value.page = 1;
  },
});
```
