### ISSUE TITLE
n-tree-select 树选择器懒加载默认参数

### ISSUE THREAD

**Issue by wfc66986** [tusen-ai/naive-ui#4677]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-alpha.7

### Browser and its version (浏览器及其版本)
Chrome版本 111.0.5563.147

### System and its version (系统及其版本)
xx

### Reappearance link (重现链接)
https://codesandbox.io/s/epic-aryabhata-46djl7?file=/src/Demo.vue

### Reappearance steps (重现步骤)
懒加载树选择默认初始化时候v-model,绑定参数未赋值到输入框中，用户体验不好。

### Expected results (期望的结果)
希望懒加载树选择默认初始化时候参数带上，默认获取现在提供参数，现在是整么传递都是空，除非到懒加载那一程key匹配到才显示这样不科学，用户需要一直懒加载到底部才显示最终效果。

### Actual results (实际的结果)
默认进去获取v-model绑定的参数值。

**Comment by wfc66986** [comment]
有办法解决嘛

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
