### ISSUE TITLE
uploader 的 list渲染机制 触发[Vue warn] Extraneous non-props attributes (mode) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 

### ISSUE THREAD

**Issue by gowy222** [tusen-ai/naive-ui#4679]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.47

### Browser and its version (浏览器及其版本)
100 

### System and its version (系统及其版本)
win

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/dark/components/upload#drag.vue

### Reappearance steps (重现步骤)
<template>
  <n-upload
    action="https://www.mocky.io/v2/5e4bafc63100007100d8b70f"
    :headers="{
      'naive-info': 'hello!'
    }"
    :data="{
      'naive-data': 'cool! naive!'
    }"
  >
    <n-button>上传文件</n-button>
  </n-upload>
</template>

### Expected results (期望的结果)
之前一直好好的，最近升级了一下vue就这样了。

### Actual results (实际的结果)
app.js:15010 [Vue warn]: Extraneous non-props attributes (mode) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
  at <TransitionGroup name="fade-in-height-expand-transition" mode=undefined appear=false  ... > //这行。如果设置 show-file-list=false 就不会触发... 说明就是uploader的list渲染机制导致的?
  at <FadeInExpandTransition group=true > 
  at <UploadFileList> 
  at <Upload key=0 ref="upload" multiple=true  ... >

**Comment by gowy222** [comment]
https://cn.vuejs.org/api/built-in-components.html#transition
vue文档:
<TransitionGroup> 拥有与 <Transition> 除了 mode 以外所有的 props，并增加了两个额外的 props：

然后看
at <TransitionGroup name="fade-in-height-expand-transition" mode=undefined appear=false ... > //这行

换言之，最新的vue版本移除了TransitionGroup的mode属性?

**Comment by 07akioni** [comment]
fixed in https://github.com/tusen-ai/naive-ui/pull/4479/
