### ISSUE TITLE
SSR报document is not defined错误

### ISSUE THREAD

**Issue by Ocyss** [tusen-ai/naive-ui#4680]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.47

### Browser and its version (浏览器及其版本)
Chromium 102.0.5005.167

### System and its version (系统及其版本)
Win11 22H2

### Reappearance link (重现链接)
<https://github.com/Ocyss/QiuBlog/tree/ssr>

### Reappearance steps (重现步骤)
Using `n-popover` ,  `n-tabs` ,  `n-menu` all report errors
使用 `n-popover` ，`n-tabs` ，`n-menu` 都会报错

### Expected results (期望的结果)
正常使用
Normal use

### Actual results (实际的结果)
```
ReferenceError: document is not defined
    at queryElement (E:\Vue\QiuBlog\Blog\web\node_modules\css-render\lib\utils.js:17:5)
    at mount (E:\Vue\QiuBlog\Blog\web\node_modules\css-render\lib\mount.js:59:52)
    at Object.wrappedMount [as mount] (E:\Vue\QiuBlog\Blog\web\node_modules\css-render\lib\c.js:14:45)
    at setup (/node_modules/vueuc/es/binder/src/Follower.js:92:15)
    at callWithErrorHandling (E:\Vue\QiuBlog\Blog\web\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:171:22)
    at setupStatefulComponent (E:\Vue\QiuBlog\Blog\web\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7194:29)
    at setupComponent (E:\Vue\QiuBlog\Blog\web\node_modules\@vue\runtime-core\dist\runtime-core.cjs.js:7149:11)
    at renderComponentVNode (E:\Vue\QiuBlog\Blog\web\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:628:17)
    at renderVNode (E:\Vue\QiuBlog\Blog\web\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:755:22)
    at renderComponentSubTree (E:\Vue\QiuBlog\Blog\web\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:719:13)
```

**Comment by Talljack** [comment]
maybe same as #2347 , please check it

**Comment by Ocyss** [comment]
![QQ截图20230410101854](https://user-images.githubusercontent.com/68412205/230812917-ae4d510c-4773-480d-b22a-7682b40ee232.png)

I have followed the naiveui and css-render documentation and have used `const { collect } = setup(app);` but it doesn't work, it still reports errors for the components I mentioned, the other components are fine

我有按 naiveui 和 css-render 的文档操作过，有使用 `const { collect } = setup(app);`  但是不起作用，就我说的那几个组件还是会报错，其他组件没问题

**Comment by Ocyss** [comment]
> [可能与#2347](https://github.com/tusen-ai/naive-ui/issues/2347)相同，请检查

https://github.com/tusen-ai/naive-ui/issues/4680#issuecomment-1501312378

**Comment by Ocyss** [comment]
> maybe same as #2347 , please check it
Can you tell me if this is a bug, do I need to fix it, if not I'm going to change Element-UI, please give me an accurate reply, thanks!

能告诉我这是否是一个BUG，需不需要修复，不修复我就打算换Element-UI了，请麻烦给我个准确回复，谢谢

**Comment by Ocyss** [comment]
> maybe same as #2347 , please check it

@Talljack 
Can you tell me if this is a bug, do I need to fix it, if not I'm going to change Element-UI, please give me an accurate reply, thanks!

能告诉我这是否是一个BUG，需不需要修复，不修复我就打算换Element-UI了，请麻烦给我个准确回复，谢谢

**Comment by Talljack** [comment]
I think this is a BUG, We will to fix it.

**Comment by Ocyss** [comment]
> I think this is a BUG, We will to fix it.

@Talljack 
Ok, I really like naive-ui and would be happy to recommend others to use it.
好的，我非常喜欢 naive-ui 也很愿意推荐其他人使用。

**Comment by Ocyss** [comment]
@Talljack 

I removed the back-end related code and streamlined the project as much as possible to make it easier for you to debug
And I also created `codesandbox`, the local or `codesandbox` run result is error, run command is `yarn dev`

I also copied your Test.vue file from App.vue, which also reports the same error and has been commented out, and then the specific unavailable `components` in the project, including the location, are
`n-popover` at (`src\layout\components\Header.vue:31`)
`n-tabs` at (`src\components\front\post\PostList.vue:11`)
`n-menu` at (`src\layout\components\Menu.vue:151`)

New branch created: <https://github.com/Ocyss/QiuBlog/tree/debug>

codesandbox: <https://codesandbox.io/p/github/Ocyss/QiuBlog/debug?file=%2Fpackage.json&workspace=%257B%2522activeFilepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522openFiles%2522%253A%255B%2522%252Fsrc%252FApp.vue%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522spaces%2522%253A%257B%2522clgn6igho02z33j6j9u8vvoz4%2522%253A%257B%2522devtools%2522%253A%255B%255D%252C%2522key%2522%253A%2522clgn6igho02z33j6j9u8vvoz4%2522%252C%2522name%2522%253A%2522yarn%2520dev%2522%257D%257D%252C%2522currentSpace%2522%253A%2522clgn6igho02z33j6j9u8vvoz4%2522%252C%2522spacesOrder%2522%253A%255B%2522clgn6igho02z33j6j9u8vvoz4%2522%255D%252C%2522hideCodeEditor%2522%253Afalse%257D>

我将后端相关代码删了，并且尽可能的精简了项目，让你们方便调试

并且还创建了`codesandbox`，本地还是`codesandbox`的运行结果都是错误，运行命令为 `yarn dev`

App.vue中我也将你的Test.vue文件拷贝了过来，也是一样报错，已经注释了，然后项目中具体无法使用的组件包括位置分别为：
`n-popover` at (`src\layout\components\Header.vue:31`)
`n-tabs` at (`src\components\front\post\PostList.vue:11`)
`n-menu` at (`src\layout\components\Menu.vue:151`)

新建的分支：<https://github.com/Ocyss/QiuBlog/tree/debug>

**Comment by Talljack** [comment]
<img width="530" alt="image" src="https://user-images.githubusercontent.com/34439652/233400941-72b967e6-1402-4b4b-b9a8-b03c119fb27f.png">
I think there is a problem with your usage. There is a problem with the app you rendered. You can refer to this branch of mine. I use the header and menu components and help you fix the problem of rendering the app.
我认为是你的用法有问题，你渲染的 app 有问题，你可以参考我的这个分支，我使用了header和menu组件，并且帮你把渲染 app 问题修正

**Comment by Ocyss** [comment]
@Talljack 
When I saw that you could run it, I clone your branch and use yarn to initialize it, and run the same error, but I saw that there was a pnpm file under the project, deleted the node_modules, and ran it with pnpm, and the error disappeared. This is a real headache!

When I went back to my own branch of the project and ran it with pnpm, I got a new error, but installed the viteCommonjs plugin and it was fine. When I tried yarn again, I still got the same error, I don't know what it is, and I'm not going to look into it, pnpm smells good!

As for the app usage issue, I tried different usages before mentioning `issue`, different problems will occur, such as: two apps, or two apps nested, I think it is not correct to have two identical ids appear, that's why I use that in my project, maybe I need to go to vite's forum later and borrow from other people's ssr projects to see it.

Translated with www.DeepL.com/Translator (free version)

当我看到你能运行，我clone了你的分支，并且使用yarn来初始化，运行同样报错，但我看到项目下有pnpm的文件，删除了node_modules，使用pnpm运行，报错消失了。这可真是让人头疼

当我回到我自己的项目分支，使用pnpm运行，有新的错误，但将viteCommonjs插件安装上，就没问题了。当我又尝试了下yarn，还是同样错误，不知道是啥原因，我也不打算深究了，pnpm 真香

至于app的用法问题，我在提 `issue` 之前试过不同的用法，会出现不同的问题，如：两个app，或者两个app嵌套，我觉得有两个相同id出现是不正确的，所以我项目里才会那么使用，也许我待会需要去vite的论坛，借鉴下别人的ssr项目来看看了。

**Comment by Talljack** [comment]
Wish you all the best, I hope you will try more new technologies such as pnpm, and go to technical forums to learn more.

**Comment by benoitlahoz** [comment]
Hello, 

I had the same problem and the vue SSR example didn't help.
It appears that I had to remove `inline-theme-disabled` in `n-config-provider` and everything is working.
