### ISSUE TITLE
基于无界（wujie）微前端框架：子应用使用 Vue3   Naive UI，出现【内容左移】现象

### ISSUE THREAD

**Issue by cgbin24** [tusen-ai/naive-ui#4681]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.47

### Browser and its version (浏览器及其版本)
Chrome 111.0.5563.64（正式版本） (arm64)

### System and its version (系统及其版本)
Macos（Ventura 13）

### Node version (Node 版本)
v16.18.0

### Reappearance link (重现链接)
https://github.com/cgbin24/wujie-demo

### Reappearance steps (重现步骤)
**描述**
1、子应用【vue-demo】使用 `Vue3   Naive UI` 
2、控制台调试 或者 窗口大小较小时，使用模态框【Modal】出现内容左移现象 
3、据排查后，发现子应用的 `html` 标签上被添加了 `margin-right` 值
4、经对比 `Naive UI` 官网演示案例后，确认【步骤3】问题存在
5、目前可通过固定 `html` 标签 `margin-right` 值暂时解决，但暂不排除会对其他内容造成异常影响

**复现**
1、`npm run wujie:install` 
2、 `npm run dev` 
3、参照下方演示视频复现错误

### Expected results (期望的结果)
弹窗后，内容正常显示

### Actual results (实际的结果)
弹窗后，内容出现左移现象

### Remarks (补充说明)
**错误展示**

https://user-images.githubusercontent.com/46283404/229691344-93d51e36-47a4-4cc4-a540-68a5eef49850.mp4

![image](https://user-images.githubusercontent.com/46283404/229684461-f74b08d0-9f8a-4c4c-b9e2-cf01ed6b4021.png)

**Comment by sky124380729** [comment]
同样的问题，确实是由于给html加了margin-right导致的
你目前固定html margin-right的方式可行吗，有没有产生其他问题

**Comment by sky124380729** [comment]
> 固定html的 margin-right值可以解决我的问题，暂时没遇到由此引起的其它问题

好的谢谢，目前我也这样处理一下，还等待官方对此有回复了

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
