### ISSUE TITLE
DataTable Summary value in undefined

### ISSUE THREAD

**Issue by vitjaz** [tusen-ai/naive-ui#4684]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Chrome(110.0.5481.77)

### System and its version (系统及其版本)
Windows 10

### Reappearance link (重现链接)
https://codesandbox.io/s/bold-mclean-py38r4?file=/src/Demo.vue

### Reappearance steps (重现步骤)
1. Create n-data-table
2. Create columns and data with plain arrays
3. Use createSummary for summary prop
4. Get an error

### Expected results (期望的结果)
Expected extra row with red number of sum of Values

### Actual results (实际的结果)
Error in Cell.js on line 39 - value in undefined

**Comment by zyuting** [comment]
I also met this error that I found the reason. every column needs a function in createSummary when colSpan = 1.
`
const createSummary: DataTableCreateSummary = (pageData) => {
const formatNum = (key: string, sum = true) => {
      return {
        value: h(
          'span',
          { style: { color: 'red' } },
          sum ? (pageData as RowData[]).reduce((prevValue, row) => prevValue + row[key], 0) : ''
        ),
        colSpan: 1,
      };
    };
  return {
    age: formatNum('age'),
    xx: formatNum('xx'),
    aa: formatNum('aa'),
  }
}
`

**Comment by amadeus711** [comment]
Maybe: https://github.com/tusen-ai/naive-ui/pull/4507

**Comment by vitjaz** [comment]
@amadeus711 
Another error
![image](https://user-images.githubusercontent.com/47814045/231968626-f5abd714-c610-4141-89db-509133428724.png)

Same codesanbox: https://codesandbox.io/s/bold-mclean-py38r4?file=/src/Demo.vue

**Comment by mrokoo** [comment]
Meet the same problem, how to solve? How painful!:dizzy_face:

**Comment by mrokoo** [comment]
@vitjaz Have you solved the problem?:kissing_closed_eyes:

**Comment by vitjaz** [comment]
@mrokoo Hi! In my UI I have to create tag with sum above table

```js
<n-space vertical>
    <n-space align="center">
      <n-button @click="showAddDialog">{{ addButtonLabel }}</n-button>
      <n-button @click="showCreateDialog" v-if="createButtonLabel">{{
        createButtonLabel
      }}</n-button>
      <n-tag v-if="addSumCalc" type="success">   <--- my sum here
        Сумма: {{ sum }}
        <template #icon>
          <n-icon :component="CheckmarkCircle" />
        </template>
      </n-tag>
    </n-space>
    <n-data-table :columns="computedColumns" :data="data" />
  </n-space>
```
Here I compute the sum:

```js
const sum = computed(() => {
  return (data.value as any[]).reduce(
    (acc: number, curVal) => acc + Number(curVal.Value),
    0
  )
})
```

![image](https://user-images.githubusercontent.com/47814045/235651659-7dcae5c2-ed36-4aea-a593-0d2edbeabaf7.png)

In my case I use Value, not value. Feel free to use your own names.
```js
columns: [
    {
      title: 'Id',
      key: 'Id',
    },
    {
      title: 'Название',
      key: 'Name',
    },
    {
      title: 'Ставка',
      key: 'Value',
    },
....
  ],
```

**Comment by nothosoo** [comment]
I am facing the same issue
