### ISSUE TITLE
The border color of slider dotBorderActive is not a variable

### ISSUE THREAD

**Issue by iaa3906** [tusen-ai/naive-ui#4686]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-alpha.8

### Browser and its version (浏览器及其版本)
Edge

### System and its version (系统及其版本)
Win11

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/slider

### Reappearance steps (重现步骤)
1. Open the theme editor.
2. Find the dotBorderActive of the slider.
3. The borderColor of dotBorderActive is a fixed value and does not change with fillColor. It is recommended to set it to follow fillColor changes.

### Expected results (期望的结果)
The borderColor of dotBorderActive will follow fillColor changes.

### Actual results (实际的结果)
The borderColor of dotBorderActive is a fixed value and does not change with fillColor

**Comment by amadeus711** [comment]
For more flexible use by users, dotBorderActive has corresponding configuration items:
![image](https://user-images.githubusercontent.com/46394163/230252721-562aabb4-50a0-4d3f-bda1-67ea0eff892b.png)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
