### ISSUE TITLE
Dialog组件或Modal模态框组件dialog预设的Negative按钮默认启用了透明背景

### ISSUE THREAD

**Issue by SuperManito** [tusen-ai/naive-ui#4691]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-alpha.8

### Browser and its version (浏览器及其版本)
latest

### System and its version (系统及其版本)
Windows 11

### Node version (Node 版本)
18

### Reappearance link (重现链接)
https://codesandbox.io/s/async-cache-7b8jfs?file=/src/Demo.vue

### Reappearance steps (重现步骤)
ButtonProps是否使用ghost参数并赋值为false

### Expected results (期望的结果)
不应该默认启用按钮背景透明效果，假如想修改按钮type类型时这会让人产生一种ButtonProps无效的错觉

### Actual results (实际的结果)
背景透明

**Comment by Talljack** [comment]
现在主流框架比如 antd、element plus等都是这样设计的，并不会有什么不妥啊，而且我看你demo里修改为error类型也很明显啊

**Comment by SuperManito** [comment]
> 现在主流框架比如 antd、element plus等都是这样设计的，并不会有什么不妥啊，而且我看你demo里修改为error类型也很明显啊

1. element plus是直接定义的按钮，在其官网，它按钮组件默认primary样式的背景就是透明的，所以与此问题无关
2. antd v4的是 `#fff`、v5的是 `#ffffff`

咱的是 `#0000`，我没有看到这样的设计
