### ISSUE TITLE
n-tag checked 状态下 background-color 能否随 type 变动

### ISSUE THREAD

**Issue by tky753** [tusen-ai/naive-ui#4693]
### This function solves the problem (这个功能解决的问题)
 n-tag 的 type 对于 check状态下的style没有影响
### Expected API (期望的 API)
比如：type: 'error'， check状态下background-color 也变成  error对应的颜色

**Comment by Sepush** [comment]
选中状态不应与type关联 至于选中的颜色可以通过 themoverrides 自定义
![image](https://github.com/tusen-ai/naive-ui/assets/39197136/2cc9cf24-b330-424a-be99-e2068463bb93)
