### ISSUE TITLE
NImage 标签的 fallback属性不生效

### ISSUE THREAD

**Issue by benjenpoetry** [tusen-ai/naive-ui#4697]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.25

### Browser and its version (浏览器及其版本)
Microsoft Edge(111.0.1661.62)

### System and its version (系统及其版本)
Win11

### Reappearance link (重现链接)
https://codesandbox.io/s/twilight-voice-rl6ljj?file=/src/Demo.vue

### Reappearance steps (重现步骤)
https://codesandbox.io/s/twilight-voice-rl6ljj?file=/src/Demo.vue

### Expected results (期望的结果)
希望fallback属性生效

### Actual results (实际的结果)
当src为空字符串时，fallback-src传入值无效

### Remarks (补充说明)
根据我的测试 2.33.5 这个版本中功能是好的

**Comment by cefiro** [comment]
I confirm it stopped working.

**Comment by benjenpoetry** [comment]
> I confirm it stopped working.
