### ISSUE TITLE
选择器自定义 label 渲染后，选择框无法同步更新值

### ISSUE THREAD

**Issue by xiaopangzhi795** [tusen-ai/naive-ui#4698]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.47

### Browser and its version (浏览器及其版本)
Chrome(110.0.5481.100)

### System and its version (系统及其版本)
MacOS(13.1)

### Node version (Node 版本)
v16.17.0

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/select#Select-Slots

### Reappearance steps (重现步骤)
1. 引入 NSelect 组件，使用 vue  ts
2. :options，在 setup 中定义一个常量，const fontIconList = ref([]); 内容为多个图标渲染。{value: 'arrow', label: () => h(GSvg, {name: 'arrow'})}。GSvg为自己封装的一个组件，主要目的是渲染一个 svg 图标。
3. v-model:value="siteInfo.fontIcon"
4. 页面刷新，可以看到选项框中，有定义的内容。默认选中的内容也生效了。

### Expected results (期望的结果)
1. 当我选择了某个选项时，该选项被真实的选中了。
2. 选中该内容后，选项卡的框中内容变更为我选中的内容。

### Actual results (实际的结果)
1. 当我选择了某个选项卡时，实际的列表中选项已经发生了改变。
2. 选中后，选项卡的展示框中，值没有发生改变，实际的接受变量已经发生了对应的改变。
note：
功能正常可用，只是选择后没办法同步渲染到展示框中。
我列表中共有十几个选项，当我其中一个选项为其他方式实现时（只是在 GSvg 上面增加一个标签包着），就可以正常渲染该选项，并且可以从该选项再次渲染其他任何选项。
比如：ABCDEF...选项，A 选项使用的其他方式渲染，从 E 到 A 可以（到除 A 之外的都不行），A 到任何都可以，选择了任何一个之后，依然只能再选择回 A 是正常的，除 A 之外依然不可选择。
当我把所有的渲染方式都变成了 A 之后，之前的问题又会复现，选择任何一个都不会进行渲染。

### Remarks (补充说明)
label 的渲染方式相同，渲染内容为自定义组件。参数为 value 传进去的。
label 必须要使用() => h();进行渲染。单纯文字是没问题的。

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
