### ISSUE TITLE
Responsive design support

### ISSUE THREAD

**Issue by vonWolfehaus** [tusen-ai/naive-ui#4699]
### This function solves the problem (这个功能解决的问题)
It is currently very difficult to manipulate components based on screen resolution for things like mobile/tablet/desktop. There is no service that helps identify which platform the app is running on. Therefore making a responsive app with Naive UI is also very difficult.
### Expected API (期望的 API)
Provide an API like Vuetify: https://vuetifyjs.com/en/features/display-and-platform/ This allows triggering display states based on device and screen resolution in both CSS and JS.

**Comment by moseskamau338** [comment]
Any progress on this?

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
