### ISSUE TITLE
NUpload 支持自定义渲染文件列表，或者在list-type是text的时候也支持on-preview

### ISSUE THREAD

**Issue by povs2012** [tusen-ai/naive-ui#4707]
### This function solves the problem (这个功能解决的问题)
文件列表时支持点击的时候不仅仅是下载，也可以预览文件，例如pdf、office文件能够自定义打开预览页面，此时又不想渲染成image-card
### Expected API (期望的 API)
支持使用slot或render函数渲染

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
