### ISSUE TITLE
textarea在项目中无法显示滚动条

### ISSUE THREAD

**Issue by wocanbe** [tusen-ai/naive-ui#4709]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-alpha.9

### Browser and its version (浏览器及其版本)
edge 111.0.1661.62,chrome 112.0.5615.50

### System and its version (系统及其版本)
window11,macos

### Reappearance link (重现链接)
https://github.com/jekip/naive-ui-admin

### Reappearance steps (重现步骤)
textarea在项目中无法显示滚动条，可以在naive-ui-admin的线上演示地址看（ https://pro.naiveadmin.com/form/basic-form ）

### Expected results (期望的结果)
希望修复滚动条不显示的BUG

### Actual results (实际的结果)
textarea在项目中无法显示滚动条

**Comment by jizai1125** [comment]
`<n-input  type="textarea"/>` 原生滚动条的样式默认应该是被去掉了，可以使用[滚动条组件](https://www.naiveui.com/zh-CN/light/components/scrollbar)包一下，或者在布局组件中设置 `native-scrollbar: false` [使用内置滚动条](https://www.naiveui.com/zh-CN/light/components/layout#scrollbar.vue)

**Comment by wocanbe** [comment]
我看dom中滚动条是存在的，滚动的时候滚动条样式(style)也在变，能让它生效，显示出来吗？
![TO{U8YTIC$T8Q19Q)66F@ H](https://user-images.githubusercontent.com/12180237/231326956-797963aa-228d-47e7-8300-628a831322c1.png)
