### ISSUE TITLE
Ellipsis 在 datatable 中使用时出现上下抖动问题

### ISSUE THREAD

**Issue by nealsongg** [tusen-ai/naive-ui#4715]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-alpha.9

### Browser and its version (浏览器及其版本)
chrome 110.0.5481.178

### System and its version (系统及其版本)
window 11

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/data-table#ellipsis-tooltip.vue

### Reappearance steps (重现步骤)
When switching to the function of clicking ellipsis text to expand the full text, the non-ellipsis text data will be jitter when clicked.
给datatable定义ellipsis的点击展开完整文本功能，对没有省略的文本数据点击会产生上下高度变化的问题，对省略的文本点击就会正常展开完整文本。
### Expected results (期望的结果)
will not be jitter

### Actual results (实际的结果)
can not solve this problem

### Remarks (补充说明)
![image](https://user-images.githubusercontent.com/115465215/231631599-e793deb9-2e80-4ad4-a179-37c9993d8e95.png)
![image](https://user-images.githubusercontent.com/115465215/231631664-1cd1c806-6b25-45d2-a502-290294e0856f.png)

**Comment by nealsongg** [comment]
在dataTable 中使用Ellipsis文本省略组件，换成ellipsis组件的点击省略文本展开完整文本功能时候，非省略的文本数据在点击时会出现上下抖动的问题。目前没有找到解决方法

**Comment by jizai1125** [comment]
可以加个 style
```js
ellipsis: {
      // ...
      style: {
        display: '-webkit-box'
      }
    }
```

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
