### ISSUE TITLE
Phone input component

### ISSUE THREAD

**Issue by rifkiard** [tusen-ai/naive-ui#4716]
### This function solves the problem (这个功能解决的问题)
I want to create an international phone input that will auto-format the phone number based on the inputted value. 
### Expected API (期望的 API)
Can we integrate naive-ui with vue-tel-input (https://vue-tel-input.iamstevendao.com/) or get the n-phone-input component that adopts similar phone rules?

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
