### ISSUE TITLE
Pagination hot update error and render failed in vite

### ISSUE THREAD

**Issue by huqingchao** [tusen-ai/naive-ui#4717]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Chrome(111.0.5563.148)

### System and its version (系统及其版本)
win11

### Node version (Node 版本)
18.6.0

### Reappearance link (重现链接)
https://codesandbox.io/p/sandbox/pensive-bardeen-to94bz?file=%2Fsrc%2FApp.vue

### Reappearance steps (重现步骤)
1、修改App.vue任意代码
2、f12控制台报错 Cannot read properties of undefined (reading 'value')
    at invokeDirectiveHook (run

### Expected results (期望的结果)
fix Pagination hot update bug and can render 

### Actual results (实际的结果)
Pagination hot update failed and log has error info

**Comment by huqingchao** [comment]
有分页组件时，更改任意dom文字，控制台报错，页面点击事件无法响应，实际项目开发中会阻塞代码热更新，需要刷新页面才能响应点击事件

**Comment by bundlejs** [comment]
也发现了这个问题, 页面有这个组件带缓存再返回这个页面的时候也是报同样的错误

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
