### ISSUE TITLE
Support `pair` prop in `NInputNumber` like in `NInput`

### ISSUE THREAD

**Issue by uporot1k** [tusen-ai/naive-ui#4720]
### This function solves the problem (这个功能解决的问题)
This feature solves the problem when you need to set a paired value.
In `NInput` this is already implemented through prop - pair
### Expected API (期望的 API)
Just like in NInput

```
<n-input-number pair />
```

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
