### ISSUE TITLE
use useDialog while use vitest and got error : No outer <n-dialog-provider /> founded

### ISSUE THREAD

**Issue by UTing1119** [tusen-ai/naive-ui#4724]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-alpha.9

### Browser and its version (浏览器及其版本)
Chrome

### System and its version (系统及其版本)
Windows(10)

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/dialog

### Reappearance steps (重现步骤)
I used ```useDialog``` in my component and used ```n-dialog-provider``` in its parent component.
They are totally good.
but when I tried to test my component with ```vitest```, I got error:

![image](https://user-images.githubusercontent.com/74576629/231954205-d79d91e9-d313-4b3c-96ec-bcdf77b22aa1.png)

### Expected results (期望的结果)
have some setting or example of testing.
do not need to change component.

### Actual results (实际的结果)
got error when testing

### Remarks (补充说明)
there is my file list(had been simplified):
```
- App.vue
    - Layout.vue <- has  <n-dialog-provider>
        - parentComponent.vue <- tested this component and got error
            - childComponent.vue
```
and there is my code:
```
// parent.test.ts
import parentComponent from './childComponent.vue'
import { shallowMount,} from '@vue/test-utils'
import { createTestingPinia } from '@pinia/testing'

describe('test_dialog',async()=>{
  let parentComponent_wrapper= shallowMount(parentComponent,{
    global: {
      plugins: [createTestingPinia(),],
    },
  })
})
```

```
// vite.config.ts
export default defineConfig({
  ...
  test: {
    globals: true,
    environment: 'jsdom',
    includeSource: ['src/**/*.{js,ts,tsx}'],
  },
  ...
})
```

I don't wanna change my component to use message or dialog,but I only find the example of how to use them without setup.
is there any way to use them normally and I can test my component correctly?

**Comment by amadeus711** [comment]
We approach this issue in the project as follows:
https://github.com/tusen-ai/naive-ui/blob/main/src/dialog/tests/Dialog.spec.tsx#L7
This is because we believe that we should maintain the purity of the testing code and try to eliminate interfering content as much as possible.
If you don't want to handle it like we do, you can try using the template function of the test library. Sorry, I'm not very familiar with this either.
