### ISSUE TITLE
I hope the custom style of the List component can customize the item's padding

### ISSUE THREAD

**Issue by lvzhenbo** [tusen-ai/naive-ui#4731]
### This function solves the problem (这个功能解决的问题)
Currently, the List component cannot customize item padding, and can only be resolved through deep or CSS important methods
目前List组件无法自定义item的padding，只能通过deep或者css important方式解决
### Expected API (期望的 API)
```js
const listThemeOverrides: ListThemeOverrides = {
    itemPadding: '0',
};
```

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
