### ISSUE TITLE
bug: n-input-number 传入 precision 后将值设置为字符串数值后抛出异常 toFixed is not a function

### ISSUE THREAD

**Issue by hairyf** [tusen-ai/naive-ui#4732]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-alpha.9

### Browser and its version (浏览器及其版本)
`*`

### System and its version (系统及其版本)
`*`

### Reappearance link (重现链接)
https://codesandbox.io/s/compassionate-dawn-we7093?file=/src/Demo.vue

### Reappearance steps (重现步骤)
```html
<template>
  <n-input-number v-model:value="value" clearable :precision="2" />
</template>

<script lang="ts">
import { defineComponent, ref, onMounted } from "vue";

export default defineComponent({
  setup() {
    const value = ref<string | number>(0);
    onMounted(() => {
      // TypeError: value.toFixed is not a function
      value.value = "1.00";
    });
    return {
      value,
    };
  },
});
</script>
```

### Expected results (期望的结果)
正常读取解析

### Actual results (实际的结果)
抛出错误 TypeError: value.toFixed is not a function

**Comment by 07akioni** [comment]
value 必须为 number
