### ISSUE TITLE
want to add a right-click menu capability to the Tab component(希望在Tab组件中添加一个右键菜单的功能)

### ISSUE THREAD

**Issue by GrayFaith** [tusen-ai/naive-ui#4733]
### This function solves the problem (这个功能解决的问题)
I tried using the right-click menu in the `<n-tab-pane>` component, but unfortunately it didn't work, 
I want to be able to provide this component with the ability to right-click menus;

我尝试在`<n-tab-pane>`组件中使用右键菜单的功能,但很遗憾无法正常的使用,
希望能够给这个组件提供一下右键菜单的功能
### Expected API (期望的 API)
I'd like `<n-dropdown>` to be supported in `<n-tab-pane>`, which would look like this `<n-tab-pane @contextMenu='(event: MouseEvent)=>onRightClick(event,xxx)'>`
 
我希望`<n-dropdown>`可以支持在`<n-tab-pane>`中使用,用法看上去是这样的`<n-tab-pane @contextmenu='(event: MouseEvent)=>onRightClick(event,xxx)'>`

**Comment by GrayFaith** [comment]
`
<n-tabs v-if='commonStore.getDynamicAsyncCustomComponentIsReady'
			v-bind='tabConfig'
			v-model:value='tabsStore["currentActivateTab"]'>
		<template v-for='item of tabsStore["tabs"]'>
			<n-tab-pane
				:closable='"A000" !== item["code"]'
				:display-directive='displayMode(item)' :name='item["code"]'
				:tab='customLabel(item)' @contextmenu='(event: MouseEvent)=>onRightClick(event,item)'>
				<component :key='`n-tabs_n-tab-pane_keep-alive_${item["key"]}_component}`'
						   :is='item["component"]'
						   :params='item["params"]'/>
			</n-tab-pane>
		</template>
	</n-tabs>
	<n-dropdown v-bind='contextMenuConfig' :on-clickoutside='onClickOutSide' @select='handleSelect'/>
`

**Comment by GrayFaith** [comment]
```
<n-tabs v-if='commonStore.getDynamicAsyncCustomComponentIsReady'
			v-bind='tabConfig'
			v-model:value='tabsStore["currentActivateTab"]'>
		<template v-for='item of tabsStore["tabs"]'>
			<n-tab-pane
				:closable='"A000" !== item["code"]'
				:display-directive='displayMode(item)' :name='item["code"]'
				:tab='customLabel(item)' @contextmenu='(event: MouseEvent)=>onRightClick(event,item)'>
				<component :key='`n-tabs_n-tab-pane_keep-alive_${item["key"]}_component}`'
						   :is='item["component"]'
						   :params='item["params"]'/>
			</n-tab-pane>
		</template>
	</n-tabs>
	<n-dropdown v-bind='contextMenuConfig' :on-clickoutside='onClickOutSide' @select='handleSelect'/>
```

**Comment by GrayFaith** [comment]
现在我可以使用addEventListener来绑定,但是这并不优雅

Now I can use addEventListener to bind, but that's not elegant
```
const tabHtml = document.querySelector(`.tab-pane-container .n-tabs-tab[data-name=${addedTab['code']}]`);
// 绑定右键菜单事件
// bind contentMenu event
tabHtml.addEventListener('contextmenu', (event: MouseEvent) => this.onRightClick(event, addedTab));
```

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
