### ISSUE TITLE
n-upload 组件使用问题

### ISSUE THREAD

**Issue by tgy3300** [tusen-ai/naive-ui#4735]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-alpha.11

### Browser and its version (浏览器及其版本)
最新

### System and its version (系统及其版本)
最新

### Node version (Node 版本)
最新

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/upload

### Reappearance steps (重现步骤)
```
---a.vue---
<template>
	<div class="bg-light-50 p-[20px]">
		<n-form
			ref="formRef"
			:model="model"
		>
			<n-form-item
				label="Input"
				path="inputValue"
			>
				<n-input
					v-model:value="model.inputValue"
					placeholder="Input"
				/>
			</n-form-item>
			<n-form-item
				label="Upload"
				path="uploadValue"
			>
				<n-upload v-model:file-list="model.fileList">
					<n-button>上传</n-button>
				</n-upload>
			</n-form-item>
		</n-form>
	</div>
</template>

<script setup lang="ts">
import { ref } from 'vue'

const model = ref({
	inputValue: '',
	fileList: [],
})
</script>
```

浏览器提示如下：
`xtraneous non-props attributes (mode) were passed to component but could not be automatically inherited because component renders fragment or text root nodes.`

只要把
```
<n-form-item
				label="Upload"
				path="uploadValue"
			>
				<n-upload v-model:file-list="model.fileList">
					<n-button>上传</n-button>
				</n-upload>
			</n-form-item>
```
这个删掉，提示就会消失

### Expected results (期望的结果)
能解决吗

### Actual results (实际的结果)
能解决吗

**Comment by tgy3300** [comment]
问题依旧没解决呀，vue升级到3.2.47，又不想使用`:show-file-list="false"`来关闭文件列表，如何解决呀

**Comment by tgy3300** [comment]
不是已经解决了吗，为什么不合并发布呢，

**Comment by amadeus711** [comment]
> 不是已经解决了吗，为什么不合并发布呢，

这个月会发一版，具体时间不好说

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
