### ISSUE TITLE
表格开启 tooltip之后 内存增加过大 卡顿

### ISSUE THREAD

**Issue by lvjinze** [tusen-ai/naive-ui#4737]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
112.0.5615.49（正式版本） (arm64)

### System and its version (系统及其版本)
MacOS(12.5.1)

### Reappearance link (重现链接)
https://codepen.io/lvjinze/pen/RweREGj

### Reappearance steps (重现步骤)
点击开启tooltip 内存增加很多
关闭tooltip 内存减少
大概10倍之差
虚拟滚动也会被影响 造成卡顿的情况

### Expected results (期望的结果)
正常

### Actual results (实际的结果)
内存增加过大 卡顿

**Comment by lvjinze** [comment]
渲染1000条数据
打开之后
![open](https://user-images.githubusercontent.com/13660311/232677464-4d5ac124-a4ed-4d79-99ee-feef6694ad8f.png)
关闭之后
![close](https://user-images.githubusercontent.com/13660311/232677474-dfca9524-fa5b-44fb-bc32-9b9320a1cbce.png)

**Comment by MinatoHikari** [comment]
开了vue-devtools？

**Comment by lvjinze** [comment]
@MinatoHikari 我刚改了一下源码 修改了一下 tooltip 渲染 目前没有发现有其他问题 我可以提个pr吗

**Comment by 07akioni** [comment]
有点好奇这是啥原因导致的？PR 的修复没有看懂

**Comment by MinatoHikari** [comment]
> 有点好奇这是啥原因导致的？PR 的修复没有看懂

看起来像是鼠标移动上去再把tooltip加入到组件树里？
就算不渲染dom，一开始就加入组件树的话，高速滚动情况下tooltip的销毁重新生成需要注意内部watch等操作的开销

**Comment by lvjinze** [comment]
> 有点好奇这是啥原因导致的？PR 的修复没有看懂

就是tooltip 渲染太多了 改成了鼠标悬浮才渲染 鼠标离开销毁

**Comment by Ch-msm** [comment]
>  就是tooltip 渲染太多了 改成了鼠标悬浮才渲染 鼠标离开销毁
哪个版本修复的呢 更新最新版本`2.34.4` 没生效

**Comment by lvjinze** [comment]
> > 就是tooltip 渲染太多了 改成了鼠标悬浮才渲染 鼠标离开销毁
> 
> 哪个版本修复的呢 更新最新版本`2.34.4` 没生效

作者没有合pr

**Comment by Ch-msm** [comment]
> > > 就是tooltip 渲染太多了 改成了鼠标悬浮才渲染 鼠标离开销毁
> > 
> > 
> > 哪个版本修复的呢 更新最新版本`2.34.4` 没生效
> 
> 作者没有合pr

好的吧 先自己实现一个先用着

**Comment by lvjinze** [comment]
> > > > 就是tooltip 渲染太多了 改成了鼠标悬浮才渲染 鼠标离开销毁
> > > 
> > > 
> > > 哪个版本修复的呢 更新最新版本`2.34.4` 没生效
> > 
> > 
> > 作者没有合pr
> 
> 好的吧 先自己实现一个先用着

我现在 就是用我提的这个pr的代码 先用 等作者修复再更新

**Comment by 07akioni** [comment]
作者打算亲自看看这个问题

**Comment by lvjinze** [comment]
> 作者打算亲自看看这个问题

那是极好的

**Comment by 07akioni** [comment]
有点尴尬，我电脑太快了

**Comment by lvjinze** [comment]
> 有点尴尬，我电脑太快了
可以关注一下内存 性能较低电脑 会有明显卡顿

**Comment by 07akioni** [comment]
我大概理解问题出在哪了，应该换个做法。

你原本做法的问题在于切换 tooltip 实际上会导致组件里面东西卸载再挂挂载，不应该把这个搞成默认行为。

可以给 Ellipsis 增加一个 lazy 属性，mouseenter 之后再渲染带 tooltip 的那个 Popover 组件，用户指明再打开。然后在文档里面明确指出这么干是为了解决内存问题。

**Comment by 07akioni** [comment]
if (props.tooltip && 鼠标 enter 过) return <NPopover>{renderTrigger()}</NPopover>
if (props.lazy) {
  return renderTrigger() // trigger 加上 mouseenter
}
...

**Comment by lvjinze** [comment]
> 我大概理解问题出在哪了，应该换个做法。
> 
> 你原本做法的问题在于切换 tooltip 实际上会导致组件里面东西卸载再挂挂载，不应该把这个搞成默认行为。
> 
> 可以给 Ellipsis 增加一个 lazy 属性，mouseenter 之后再渲染带 tooltip 的那个 Popover 组件，用户指明再打开。然后在文档里面明确指出副作用，还有这么干是为了解决内存问题。

好主意 但我对于代码不太熟悉 我的灵感来自于编辑表格 lazy这个属性 作者支持一下吧:-D

**Comment by 07akioni** [comment]
> > 我大概理解问题出在哪了，应该换个做法。
> > 你原本做法的问题在于切换 tooltip 实际上会导致组件里面东西卸载再挂挂载，不应该把这个搞成默认行为。
> > 可以给 Ellipsis 增加一个 lazy 属性，mouseenter 之后再渲染带 tooltip 的那个 Popover 组件，用户指明再打开。然后在文档里面明确指出副作用，还有这么干是为了解决内存问题。
> 
> 好主意 但我对于代码不太熟悉 我的灵感来自于编辑表格 lazy这个属性 作者支持一下吧:-D

我在最新的 main 分支上增加了一个 NPerformantEllipsis 组件，麻烦你用这个组件在 data table 里面试一下你的 demo 然后提个 PR，问题应该会解决

<img width="563" alt="image" src="https://github.com/tusen-ai/naive-ui/assets/18677354/eb567810-7f7b-48cd-be2c-7bfd6a8375e8">

**Comment by lvjinze** [comment]
> 

比之前内存下降了很多 但是1000条数据的话 您看一下内存增长是否算正常

**Comment by liuzw2579** [comment]
因为这个 table tooltip 的性能问题，我自己封装了个 tooltip 的 directive 指令。表格内 基本是 hover 悬浮显示，所以指令内公用一个 tooltip 组件实例，hover 到哪个展示那个的提示内容。

**Comment by laterdayi** [comment]
有后续的进展 ？ @lvjinze

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
