### ISSUE TITLE
data-table summary cannot read properties when uses a nested data key

### ISSUE THREAD

**Issue by motea927** [tusen-ai/naive-ui#4740]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.36

### Browser and its version (浏览器及其版本)
Chrome(112)

### System and its version (系统及其版本)
MacOS

### Reappearance link (重现链接)
https://codesandbox.io/s/data-table-summary-issue-l35bje?file=/src/Demo.vue

### Reappearance steps (重现步骤)
uncomment // const summary = undefined;
it can works,
const summary = createSummary;
can not work.

### Expected results (期望的结果)
works.

### Actual results (实际的结果)
Occur "cannot read properties of undefined (reading 'value')"

### Remarks (补充说明)
```ts=
// if not use summary, it can work.
// const summary = undefined;

// issue reproduction
const summary = createSummary;
```

**Comment by motea927** [comment]
any updates?

**Comment by Seanxyc** [comment]
Same issue here, [#4507](https://github.com/tusen-ai/naive-ui/pull/4507) this pr should be approved.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
