### ISSUE TITLE
希望为NInputNumber增加inputProps属性

### ISSUE THREAD

**Issue by RommelLiang** [tusen-ai/naive-ui#4746]
### This function solves the problem (这个功能解决的问题)
expected to add the inputProps attribute to `n-input-number`. By passing this attribute to `n-input`, and then controlling the props of the input element inside the` n-input `component (e.g. type, etc.) with the help of `n-input`'s inputProps attribute

期望为`n-input-number`增加inputProps属性。通过将该属性传递给`n-input`，然后借助`n-input`的inputProps属性控制`n-input`组件内部input元素的属性(例如type等)

### Expected API (期望的 API)

 Controls the input type by inputProps , which would look like this :
`<n-input-number :inputProps="{type:'number'}"/>`

通过inputProps控制输入框类型，用法看起来是这样的
`<n-input-number :inputProps="{type:'number'}"/>`

**Comment by MichaelSchober** [comment]
Possible duplicate. 
I think think this is also relevant for my issue for being able to change type to "number": 
https://github.com/tusen-ai/naive-ui/issues/3866 
Would be nice for mobile users to instantly have the number keyboard pop-up.

**Comment by RommelLiang** [comment]
> Possible duplicate. I think think this is also relevant for my issue for being able to change type to "number": #3866 Would be nice for mobile users to instantly have the number keyboard pop-up.

yes！They are the same

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
