### ISSUE TITLE
通过createDiscreteApi方式引用的加载条 Loading Bar组件，如何更改加载条样式，比如默认绿色改成蓝色？

### ISSUE THREAD

**Issue by nhua2013** [tusen-ai/naive-ui#4747]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-alpha.12

### Browser and its version (浏览器及其版本)
chrome 112.0.5615.137

### System and its version (系统及其版本)
Windows10

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/loading-bar

### Reappearance steps (重现步骤)
createDiscreteApi方式引入加载条 Loading Bar组件，不知道如何更改加载条的默认样式。

### Expected results (期望的结果)
期待能看到问题给个解决方式

### Actual results (实际的结果)
初始接触Naive UI框架

**Comment by jizai1125** [comment]
```ts
const {  loadingBar } = createDiscreteApi(
  ['loadingBar'],
  {
    loadingBarProviderProps: {
      themeOverrides: {
        colorLoading: 'blue'
      }
    }
  }
)
```
