### ISSUE TITLE
Data-table  横向滚动时, 触摸滑动thead时，tbody内容不跟随滑动

### ISSUE THREAD

**Issue by z242** [tusen-ai/naive-ui#4749]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-alpha.12

### Browser and its version (浏览器及其版本)
111.0.5563.148

### System and its version (系统及其版本)
window(10)

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/data-table#fixed-header-column.vue

### Reappearance steps (重现步骤)
鼠标悬浮tbody上, 左手滑动tbody, thead和tbody会跟随一起滑动, 显示正常; 
鼠标悬浮tbody上, 左手滑动tbody, 右手同时移动鼠标到thead, thead不跟随滑动, 显示异常; 

### Expected results (期望的结果)
鼠标悬浮tbody上, 左手滑动tbody, 右手同时移动鼠标到thead, thead跟随滑动, 显示正常;
或者鼠标悬浮thead上, 左手滑动thead, 右手同时移动鼠标到tbody, tbody跟随滑动, 显示正常;

### Actual results (实际的结果)
鼠标悬浮tbody上, 左手滑动tbody, 右手同时移动鼠标到thead, thead不跟随滑动, 显示异常;

**Comment by z242** [comment]
![6999b989c68c9d28eb5b9690df84bc1](https://user-images.githubusercontent.com/66671830/233290420-8b6c5ef0-fd88-47fc-a457-d19d702b1fab.png)

**Comment by luke358** [comment]
同样的问题，body也是一样的，看代码监听的鼠标事件
<img width="401" alt="image" src="https://github.com/tusen-ai/naive-ui/assets/48149577/3e6d7a9f-f6a0-4ba3-9995-e5781cbc27eb">
我加了一条判断，滚动header，或者body就修改scrollPartRef，这样用起来可行
<img width="530" alt="image" src="https://github.com/tusen-ai/naive-ui/assets/48149577/6a76ba66-a44d-4349-ad11-ce5d740cd53a">

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
