### ISSUE TITLE
n-auto-complete Property 'handleInput' does not exist on type 'unknown'.

### ISSUE THREAD

**Issue by hackyoMa** [tusen-ai/naive-ui#4752]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.47

### Browser and its version (浏览器及其版本)
Microsoft Edge 112.0.1722.48

### System and its version (系统及其版本)
MacOS 13.3.1

### Node version (Node 版本)
18.16.0

### Reappearance link (重现链接)
https://github.com/CodeActions/code-actions

### Reappearance steps (重现步骤)
          <n-auto-complete
            v-model:value="profileForm.email"
            :options="emailAutoCompleteOptions">
            <template
              #default="{
                handleInput,
                handleBlur,
                handleFocus,
                value: slotValue
              }">
              <n-input
                :placeholder="$t('userSettings.profile.email')"
                :status="data.emailAutoCompleteStatus"
                :value="slotValue"
                clearable
                maxlength="100"
                show-count
                @blur="handleBlur"
                @focus="handleFocus"
                @input="handleInput" />
            </template>
          </n-auto-complete>

pnpm run build

### Expected results (期望的结果)
build success

### Actual results (实际的结果)
Property 'handleInput' does not exist on type 'unknown'.

40                 handleInput: handleInput,

### Remarks (补充说明)
typescript version 5.0.4

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
