### ISSUE TITLE
 No outer <n-dialog-provider /> founded. on UMD

### ISSUE THREAD

**Issue by jkl0890** [tusen-ai/naive-ui#4758]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-beta.1

### Browser and its version (浏览器及其版本)
112.0.5615.121

### System and its version (系统及其版本)
Windows 10

### Reappearance link (重现链接)
https://jsbin.com/saxubitaki/1/edit?html,output

### Reappearance steps (重现步骤)
In the case of UMD
excute this code "naive.useDialog()"
Unable to get dialog object,
throw exception：No outer <n-dialog-provider /> founded

### Expected results (期望的结果)
dialog available.

### Actual results (实际的结果)
No outer <n-dialog-provider /> founded

### Remarks (补充说明)
in JS Bin and local，Can not be used

**Comment by jizai1125** [comment]
you need to wrap the component where you call related methods inside n-dialog-provider and use useDialog to get the API.

**Comment by x-strong** [comment]
> To access the API for calling related methods, you should wrap the component in `n-dialog-provider`.

BAD Design! HARD to use.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
