### ISSUE TITLE
配合form-item，提供一个n-upload校验的示例

### ISSUE THREAD

**Issue by moshuchao** [tusen-ai/naive-ui#4759]
### This function solves the problem (这个功能解决的问题)
提交之前校验一下数据
### Expected API (期望的 API)
  <n-form
    ref="formRef"
    inline
    :label-width="80"
    :model="formValue"
    :rules="rules"
    :size="size"
  >
    <n-form-item label="Upload" path="uploadValue">
        <n-upload>
          <n-button>Upload file</n-button>
        </n-upload>
      </n-form-item>
    <n-form-item>
      <n-button attr-type="button" @click="handleValidateClick">
        验证
      </n-button>
    </n-form-item>
  </n-form>

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
