### ISSUE TITLE
项目还维护吗? Data  table 虽然给了scrollTo x, y  但是Props没有给出相关参数设置attr, 怎么实现滚动到指定条目?

### ISSUE THREAD

**Issue by gowy222** [tusen-ai/naive-ui#4760]
### This function solves the problem (这个功能解决的问题)
求解.. 比如每个row 有key == UUID, 但是 怎么取到该row的y坐标,然后调用scrollTo ?  没提供任何Methods..
### Expected API (期望的 API)
scrollTo => {
   rowKey:'uuid',
   rowVal:'xxx'
}

**Comment by wcldyx** [comment]
兄弟有解决方案了吗
