### ISSUE TITLE
The addSlide removeSlide type is incorrectly defined in interface CarouselContextValue

### ISSUE THREAD

**Issue by aegorx** [tusen-ai/naive-ui#4764]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.47

### Browser and its version (浏览器及其版本)
111.0.5563.64

### System and its version (系统及其版本)
MacOS(11.2.3)

### Node version (Node 版本)
v16.14.2

### Reappearance link (重现链接)
https://jsbin.com/saxubitaki/1/edit?html,output

### Reappearance steps (重现步骤)
step 1
pnpm build:package

### Expected results (期望的结果)
no error

### Actual results (实际的结果)
src/carousel/src/Carousel.tsx:472:7
src/carousel/src/CarouselContext.ts:21:3
Type 'HTMLElement | null | undefined' is not assignable to type 'HTMLElement | undefined'.

**Comment by amadeus711** [comment]
![image](https://user-images.githubusercontent.com/46394163/236984799-99006867-4f76-4eba-af50-768dd3bdc873.png)
Need more info

**Comment by jahnli** [comment]
Closed due to inactivity. Feel free to reopen if you're still having trouble
