### ISSUE TITLE
Use icon as button to load effect optimization

### ISSUE THREAD

**Issue by SonyLeo** [tusen-ai/naive-ui#4772]
#### 1. Description

In the current NaiveUI icon button component, optimize the loading effect of the current icon as the button (hereinafter referred to as the icon button component). When other component libraries click the icon button component to display the refresh effect, the loading effect is directly displayed inside the button, rather than Adding an icon loading effect on the left. Sincerely hope you can consider optimizing the display effect of this component.

#### 2. Demand scenario

When the user needs to wait for the response of the component, the loading effect of the icon button component can increase the user experience and further improve the usability of the component.

#### 3. Advantages

This feature can help NaiveUI's icon button component improve usability and user experience, providing users with more complete functions.

#### 4. Write at the end

Once again, I sincerely ask you to consider this suggestion, if you can adopt it, the user experience of Naive UI will be even better.
#### Implementation plan

It is recommended to add a property called'loading-icon 'to the NaiveUI icon button component, through which to control whether to enable the switching of the loading effect. When this property is set to true, the button will directly display the refresh icon for loading.

**Comment by jizai1125** [comment]
Didn't get what you meant. Can you show some code?

**Comment by SonyLeo** [comment]
> Not sure what you mean. Is this the effect you're talking about？https://codesandbox.io/s/exciting-night-tp9fgd?file=/src/Demo.vue
> 
> <img alt="" width="200" src="https://user-images.githubusercontent.com/33979706/235281731-2adcf058-62f0-47ab-a737-d99173663d21.png">

First of all, nice to hear from you.



Secondly, the demo you show is the loading effect after optimization that I want to express. 



 The current official website shows only two loading effects 

(https://www.naiveui.com/en-US/os-theme/components/button#loading.vue)

It does not involve the loading effect of the icon button. When I used the same API (loading) to simulate the loading effect, I found that the loaded icon effect appeared on the left side of the icon 

(https://codesandbox.io/s/async-sun-gb213r?file=/src/Demo.vue)



Of course, if it is the author's proprietary design to distinguish it from other frameworks, then I understand.



After consulting the relevant information, I found that the loading effect of the icon buttons of other UI frameworks (Element Plus or Ant Design of vue) is to switch the loading effect directly in the original icon part using the same API (loading).



(Example of Element Plus effect: https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJmbGV4XCI+XG4gICAgICA8c3Bhbj4gbm9ybWFsOiA8L3NwYW4+XG4gICAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgOmljb249XCJFZGl0XCIgLz5cbiAgICA8L2Rpdj5cbiAgIDxociAvPiBcbiAgICA8ZGl2IGNsYXNzPVwiZmxleFwiPlxuICAgICAgPHNwYW4+IGxvYWRpbmc6IDwvc3Bhbj5cbiAgICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiA6aWNvbj1cIkVkaXRcIiBsb2FkaW5nIC8+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyBEZWxldGUsIEVkaXQsIFNlYXJjaCwgU2hhcmUsIFVwbG9hZCB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)



If you can optimize this detail, I personally think the user experience will be better.



Finally, thank you for taking the time out of your busy schedule to reply to my issue, thank you very much.

Also look forward to receiving your reply on this issue again .

**Comment by jizai1125** [comment]
@SonyLeo  You can use `render-icon` prop or `icon` slot.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
