### ISSUE TITLE
数据表格指定了max-height后，cell数据太长后导致表格无法正常滑动，会出现错乱现象

### ISSUE THREAD

**Issue by LSenbazuru** [tusen-ai/naive-ui#4773]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-beta.2

### Browser and its version (浏览器及其版本)
版本 112.0.5615.138（正式版本）

### System and its version (系统及其版本)
Win10家庭中文版

### Node version (Node 版本)
v14.21.2

### Reappearance link (重现链接)
https://github.com/tusen-ai/naive-ui/issues?q=max-height 

### Reappearance steps (重现步骤)
1. 将数据表格的属性max-height指定为200px
2.查询数据，数据中有一列数据每一个cell内容都超过300

### Expected results (期望的结果)
当前数据表格设置max-height后，cell内容过长表格也能正常滑动

### Actual results (实际的结果)
cell太长后表格无法正常显示

**Comment by jahnli** [comment]
Provide a based on CodeSandbox or stackblitz [Minimal, Reproducible Example] (https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
