### ISSUE TITLE
draggable Tree  node can NOT be placed anywhere

### ISSUE THREAD

**Issue by fogine** [tusen-ai/naive-ui#4774]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
webkit2gtk 2.40.1-1

### System and its version (系统及其版本)
Linux 6.2.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 30 Mar 2023 14:51:14  0000 x86_64 GNU/Linux

### Node version (Node 版本)
v16.18.1

### Reappearance link (重现链接)
https://github.com/fogine/naiveui-tree-bug

### Reappearance steps (重现步骤)
Drag one of the nodes. While dragging selected node there is no place highlighted where the node could be placed (`inside`, `after`, `before`) and as consequence `@drop` event is not fired.

### Expected results (期望的结果)
I should be able to drag one of the nodes to another place in the tree list. Upon inspection, I'm getting `on-dragstart` and `on-dragend`  events but no `on-dragenter` , `on-drop`, `on-dragleave` events.
I realize it might be Webkit/Webview related bug. Still I do not know what is causing the issue, is there some workaround?

### Actual results (实际的结果)
Dragging is initiated with proper visualisation of the node that is being dragged, however its not possible to drop the node to any location (no hover effect over other nodes can be seen)

### Remarks (补充说明)
The application is running in webview, its developed with Tauri. Tauri is platform for developing cross platform desktop (and mobile) applications using `Rust` on the backend. On the frontend, I use vue 3.2.45 with naive ui.
It does not work in the Webview2/Webkit though:

https://user-images.githubusercontent.com/7884288/235327039-4dea4b17-63e3-4e6f-803e-6a5f4214ac89.mp4

When running in the browser, dragging works:

https://user-images.githubusercontent.com/7884288/235339813-80a99729-dc4e-483a-a885-c4efa0251f17.mp4

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
