### ISSUE TITLE
The problem of perfect match

### ISSUE THREAD

**Issue by lpj145** [tusen-ai/naive-ui#4779]
### Naive version: 2.34.3

For the first, thank you, guys, for the excellent work here, I'm really glad to know the incredible works that you are working, is it common case to build design system thinking in perfect component matches, it means that maybe the users will not break the usability the design and bla bla, but this case is not perfect for the world, the person who developed this filter maybe feel a little lost when he starts to mix tabs with feature flags, render less components, even for a simple case when I want to evolve the tab with a router-link.

So the question is, guys, can we remove these filters? I see some other filters applied in other components and I find it only turns the components difficult to reusable or just to customize something extended.

https://github.com/tusen-ai/naive-ui/blob/52d66c4e61b04b1602d7015caa9120b781f1c1ab/src/tabs/src/Tabs.tsx#L653

Right now my solution consists of:
![image](https://user-images.githubusercontent.com/11980109/235703271-604583f1-404f-4c0b-87d7-1c82ff2575c1.png)

Is it not good but I think it is enough.

**Comment by 07akioni** [comment]
I'm sorry for this pattern. If it's possible to redevelop the library, I'll never try to extract data from `VNode`.

I took this pattern only to make API looks nice in common use case. However this pattern is not maintainable. It hooks too much into the framework (like vue, react) implementation.

These filters are required to make component work in current API pattern, so we are not able to move it.

**Comment by 07akioni** [comment]
API should better not be exposed in view layer, but in data layer.
