### ISSUE TITLE
dialog button->positiveText textColor bug（dialog弹窗确认按钮默认文本颜色当前存在问题）

### ISSUE THREAD

**Issue by Small-Shu** [tusen-ai/naive-ui#4787]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.47

### Browser and its version (浏览器及其版本)
Edge@latest

### System and its version (系统及其版本)
Windows 10

### Node version (Node 版本)
v18.14.1

### Reappearance link (重现链接)
https://codesandbox.io/s/dark-wood-kv1ok7?file=/src/App.vue

### Reappearance steps (重现步骤)
看 Link to minimal reproduction

### Expected results (期望的结果)
确认按钮默认文本颜色更突出一点

### Actual results (实际的结果)
确认按钮的默文本认颜色和鼠标悬浮文本颜色是一致的。

**Comment by Small-Shu** [comment]
dialog 的 positiveButtonProps->themeOverrides（主题覆盖）目前也是没有生效的

**Comment by amadeus711** [comment]
> ### TuSimple/naive-ui version (版本)
> 2.34.3
> 
> ### Vue version (Vue 版本)
> 3.2.47
> 
> ### Browser and its version (浏览器及其版本)
> Edge@latest
> 
> ### System and its version (系统及其版本)
> Windows 10
> 
> ### Node version (Node 版本)
> v18.14.1
> 
> ### Reappearance link (重现链接)
> https://codesandbox.io/s/dark-wood-kv1ok7?file=/src/App.vue
> 
> ### Reappearance steps (重现步骤)
> 看 Link to minimal reproduction
> 
> ### Expected results (期望的结果)
> 确认按钮默认文本颜色更突出一点
> 
> ### Actual results (实际的结果)
> 确认按钮的默文本认颜色和鼠标悬浮文本颜色是一致的。
> 
> ### Remarks (补充说明)
形如 type  为`primary`、`info`、`success`、`warning` 和 `error` 这种带底色的按钮，设计时就将其 hover 态设计为*只改变底色深浅，不改变文字颜色*。

**Comment by amadeus711** [comment]
> dialog 的 positiveButtonProps->themeOverrides（主题覆盖）目前也是没有生效的

![image](https://user-images.githubusercontent.com/46394163/236593295-7f0c28b9-03d3-4756-bc55-38d75725340f.png)
为了保证 `Dialog` 组件的正常运行，其 `positiveButtonProps` 无法覆盖可能会导致问题的 props，如果想要修改这个按钮的颜色，有两个方法：
1. 修改主题色里 `button` 对应的 `primary` 或 `default` 的颜色，此修改为全局修改
2. 使用 `deep` 对这里的颜色进行单独的 class 覆盖
