### ISSUE TITLE
是否可以增加update:resize-column

### ISSUE THREAD

**Issue by yiptsangkin** [tusen-ai/naive-ui#4793]
### This function solves the problem (这个功能解决的问题)
目前想记录resize后的宽度，然后缓存下来，但是看了下目前resize的事件好像是readonly的。是否可以增加多一个事件。
### Expected API (期望的 API)
on-update:resize-column

**Comment by laterdayi** [comment]
@nooooooom   Whether there will be subsequent updates

**Comment by wtl-tianliang** [comment]
> @nooooooom Whether there will be subsequent updates

https://github.com/tusen-ai/naive-ui/pull/4827

**Comment by laterdayi** [comment]
@wtl-tianliang     👍

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
