### ISSUE TITLE
n-modal Props "to" not work, Am I using it wrong?

### ISSUE THREAD

**Issue by ThisSeanZhang** [tusen-ai/naive-ui#4794]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
Edge/113.0.1774.35

### System and its version (系统及其版本)
Window10(22H2)

### Node version (Node 版本)
v19.8.1

### Reappearance link (重现链接)
https://codesandbox.io/s/n-modal-1w1t0n

### Reappearance steps (重现步骤)
Just config the <n-modal>

### Expected results (期望的结果)
only show in div

### Actual results (实际的结果)
still show in body

**Comment by jizai1125** [comment]
![image](https://user-images.githubusercontent.com/33979706/236713214-3ff1657a-49f8-45b7-931c-a704ef26cd55.png)

**Comment by ThisSeanZhang** [comment]
Sorry, I didn't write the demo carefully, I configured it correctly in the actual project, it is in "n-modal", I have corrected the demo now, but it still doesn't work
![image](https://user-images.githubusercontent.com/46880100/236840134-257837c5-9bcd-4e8a-87f5-6038a811ca3b.png)

**Comment by jizai1125** [comment]
The rendering is correct. 'n-modal' DOM is in the specified container.

<img width="258" alt="image" src="https://user-images.githubusercontent.com/33979706/236842904-972c0364-9943-4b7c-bedb-1e8476e14b99.png">

**Comment by ThisSeanZhang** [comment]
I thought "n-modal-mask" would also be constrained to the div like "n-drawer"

**Comment by ThisSeanZhang** [comment]
If I want "n-modal-mask" to also be constrained inside div like "n-drawer", how can I do it

**Comment by 07akioni** [comment]
It's not possible. Modal is designed as a global modal.

**Comment by ThisSeanZhang** [comment]
ok, thx ❤
