### ISSUE TITLE
NImage组件fallback-src失效无效 官网展示也无效

### ISSUE THREAD

**Issue by phcent** [tusen-ai/naive-ui#4802]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.0-beta.5

### Browser and its version (浏览器及其版本)
Chrome

### System and its version (系统及其版本)
Macos

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/image

### Reappearance steps (重现步骤)
NImage组件fallback-src失效无效 官网展示也无效

**Comment by amadeus711** [comment]
https://github.com/tusen-ai/naive-ui/pull/4708
