### ISSUE TITLE
the cover of card's border radius will follow theme-overrides setting and cannot be set again

### ISSUE THREAD

**Issue by UTing1119** [tusen-ai/naive-ui#4803]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.25

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
window11

### Reappearance link (重现链接)
https://codesandbox.io/s/immutable-morning-6szs3f?file=/src/Demo.vue

### Reappearance steps (重现步骤)
1.set card border radius by theme-overrides(borderRadius:10px)
2.set card border radius to 0 in component

### Expected results (期望的结果)
cover part's border radius will be set to 0 too

### Actual results (实际的结果)
cover part's border radius will follow theme-overrides setting and cannot be set again

### Remarks (补充说明)
there is the style I found in chrome DevTool:
![image](https://github.com/tusen-ai/naive-ui/assets/74576629/cb1f7258-1455-43c5-b42e-b59f1ecd559a)

maybe can provide cover-style like other parts

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
