### ISSUE TITLE
Make it possible for rule validators to render warnings

### ISSUE THREAD

**Issue by dariogliendo** [tusen-ai/naive-ui#4806]
### This function solves the problem (这个功能解决的问题)
Sometimes you need a field to call user's attention on its importance or impact without it being required. So it would be nice to create a rule that will trigger a warning if a user inputs certain value, or on user blur, just as you can do with errors.
### Expected API (期望的 API)
When I was trying to implement this functionality, my two main ideas were the following:
1. Make it possible to return a different value on validator function, now you can only return Error or boolean, maybe if you returned a string it could be taken as a warning. For example 
```
birthday: {
  validate(_: FormItemRule, value: string) {
     if (!value) return 'If you don't provide your birthday you won't be abled to claim your birthday present :('
  }
}
```
I know this option might not be ideal because the validation API seems to be a third-party tool.
2. Maybe if a message exists but field is not required, warning is deployed on trigger. For example:
```
birthday: {
  required: false,
  message: 'If you don't provide your birthday you won't be abled to claim your birthday present :(',
  trigger: ['blur']
}
```
Maybe there's other ways to make this solution more robust and self-explanatory, but this are the two options that came to mind when trying to make it work.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
