### ISSUE TITLE
Month类型日期选择器，is-date-disabled方法可以精确禁用到某一年某一月吗？

### ISSUE THREAD

**Issue by xzhasdf** [tusen-ai/naive-ui#4811]
### This function solves the problem (这个功能解决的问题)
我需要禁用去年8月以前的所有月份，但是is-date-disabled返回的时间是从每年1月开始，如果1月不满足就会禁用整年，无法精确到月份
### Expected API (期望的 API)
可以精确直接禁用到某月

**Comment by g-plane** [comment]
Duplicate of #4649

**Comment by Sepush** [comment]
close as Duplicate
