### ISSUE TITLE
table 设置最小宽度后在苹果手机上失效

### ISSUE THREAD

**Issue by JLXFeng** [tusen-ai/naive-ui#4812]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.1

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
苹果手机

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/data-table

### Reappearance steps (重现步骤)
使用表格，设置最小宽度后在苹果手机上查看显示失效

### Expected results (期望的结果)
可以设置最小宽度并出现滚动条

### Actual results (实际的结果)
无法设置最小宽度

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
