### ISSUE TITLE
n-upload选择2个文件时on-change里的fileList只有单个文件·并且触发2次

### ISSUE THREAD

**Issue by yudan215** [tusen-ai/naive-ui#4822]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.2

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/upload

### Reappearance steps (重现步骤)
n-upload选择2个文件时on-change里的fileList只有单个文件·并且触发2次

### Expected results (期望的结果)
fileList应该显示当次选择的2个文件对象

### Actual results (实际的结果)
n-upload选择2个文件时on-change里的fileList只有单个文件·并且触发2次

**Comment by amadeus711** [comment]
https://codesandbox.io/s/competent-snowflake-5s5tfh?file=/src/Demo.vue
没有复现，更新新版本试试，或者给个最小复现

**Comment by yudan215** [comment]
> https://codesandbox.io/s/competent-snowflake-5s5tfh?file=/src/Demo.vue

选择了2个文件
handleChange也调用了2次·fileList·第一次数组内有1个文件·第2次有2个文件
DEMO里是使用的手动上传，希望可以自动上传里知道这次选择了几个文件·哪些文件·直接把这次选择的几个文件同时上传吗

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
