### ISSUE TITLE
vue-cli创建的vue3项目，在form中使用validate方法验证表单报错

### ISSUE THREAD

**Issue by oyal** [tusen-ai/naive-ui#4823]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.13

### Browser and its version (浏览器及其版本)
Google Chrome 112.0.5615.138

### System and its version (系统及其版本)
Windows10 21H2

### Node version (Node 版本)
18.16.0

### Reappearance link (重现链接)
https://codesandbox.io/s/naiveui-form-validate-icxxo9?file=/src/App.vue

### Reappearance steps (重现步骤)
点击按钮触发form的validate方法，报错

### Expected results (期望的结果)
正常返回校验结果不报错

### Actual results (实际的结果)
报错
```
Uncaught runtime errors:
ERROR
[object Object]
    at handleError (webpack-internal:///./node_modules/webpack-dev-server/client/overlay.js:299:58)
    at eval (webpack-internal:///./node_modules/webpack-dev-server/client/overlay.js:322:7)
```

### Remarks (补充说明)
Vite中正常，Webpack报错

![image](https://github.com/tusen-ai/naive-ui/assets/88022434/e85e57da-1e17-4bd3-8712-3178070320f9)

**Comment by jizai1125** [comment]
这是 webpack 捕获的错误，可以配置 [devServer.client.overlay](https://webpack.js.org/configuration/dev-server/#overlay) 关掉

**Comment by oyal** [comment]
> 这是 webpack 捕获的错误，可以配置 [devServer.client.overlay](https://webpack.js.org/configuration/dev-server/#overlay) 关掉

同样的代码，我同事点击下拉框（n-select）都会报一个类似的错误。不清楚什么原因，我直接把项目迁移到了Vite

![2857b75fa644badef7665332d636c3e](https://github.com/tusen-ai/naive-ui/assets/88022434/072bf2f4-c0fc-4a3e-a1c5-d86ae1539eae)

**Comment by jizai1125** [comment]
> 同样的代码，我同事点击下拉框（n-select）都会报一个类似的错误。不清楚什么原因，我直接把项目迁移到了Vite
配置下关掉就不会在页面弹出来了
