### ISSUE TITLE
Dynamic Input action slot不起作用

### ISSUE THREAD

**Issue by ZZZZhan** [tusen-ai/naive-ui#4828]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.3

### Browser and its version (浏览器及其版本)
Chrome(113.0.5672.92)

### System and its version (系统及其版本)
MacOS(13.3.1)

### Node version (Node 版本)
v16.19.1

### Reappearance link (重现链接)
https://codesandbox.io/s/ygomb2

### Reappearance steps (重现步骤)
Dynamic Input添加了action slot，但是页面仍然显示默认的操作按钮

### Expected results (期望的结果)
页面显示自定义的action内容

### Actual results (实际的结果)
页面显示默认的操作按钮

**Comment by amadeus711** [comment]
这个功能还未发布
![image](https://github.com/tusen-ai/naive-ui/assets/46394163/7b9551ff-9708-4581-a539-e0dd9ff3235a)

**Comment by ZZZZhan** [comment]
不好意思，没认真看
