### ISSUE TITLE
popover 在nuxt3中使用报错

### ISSUE THREAD

**Issue by moyukingS** [tusen-ai/naive-ui#4829]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.3

### Browser and its version (浏览器及其版本)
113.0.5672.94

### System and its version (系统及其版本)
win 11

### Node version (Node 版本)
18 lts

### Reappearance link (重现链接)
https://stackblitz.com/edit/nuxt-starter-jkwdoh?file=pages/index.vue

### Reappearance steps (重现步骤)
直接移入popver

### Expected results (期望的结果)
显示悬浮窗口

### Actual results (实际的结果)
报错 error caught during app initialization TypeError: track(...) is not a function

**Comment by jizai1125** [comment]
https://github.com/nuxt/nuxt/issues/20943
