### ISSUE TITLE
Error when using Menu Component: track(...) is not defined

### ISSUE THREAD

**Issue by skybird23333** [tusen-ai/naive-ui#4830]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.3

### Browser and its version (浏览器及其版本)
Chrome(113.0.5672.93)

### System and its version (系统及其版本)
Windows 10 19043

### Node version (Node 版本)
16.16.0

### Reappearance link (重现链接)
https://github.com/skybird23333/collection/tree/gh-pages

### Reappearance steps (重现步骤)
1. `npm run dev`
2. Open the app

### Expected results (期望的结果)
A menu renders with one item "Label"

### Actual results (实际的结果)
Component does not render, produces the following logs:
[Vue warn]: Unhandled error during execution of render function 
  at <Binder ref="binderInstRef" syncTarget=true syncTargetWithParent=false > 
  at <Popover theme= {name: 'Popover', common: {…}, self: ƒ} themeOverrides=undefined show=undefined  ... > 
  at <Tooltip theme= {name: 'Tooltip', common: {…}, peers: {…}, self: ƒ} themeOverrides=undefined trigger="hover"  ... > 
  at <MenuOption internalKey="key" root=true isGroup=false  ... > 
  at <Menu options= [{…}] > 
  at <App>

runtime-core.esm-bundler.js:2939 Uncaught TypeError: track(...) is not a function
    at Object.get (runtime-core.esm-bundler.js:2939:35)
    at default (Popover.js:463:106)
    at runtime-core.esm-bundler.js:4313:31
    at renderFnWithContext (runtime-core.esm-bundler.js:766:13)
    at getSlot2 (v-node.js:7:12)
    at Proxy.render (Binder.js:132:16)
    at renderComponentRoot (runtime-core.esm-bundler.js:816:16)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5696:46)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at instance.update (runtime-core.esm-bundler.js:5809:51)

### Remarks (补充说明)
Related files: src/App.vue
App was freshly created with `create-vue`

**Comment by markthree** [comment]
@skybird23333 Hello, I encountered the same issue while using element plus and ultimately locked the Vue version to 3.2.45 to resolve it，You can temporarily use this solution in your project 👉 [stackblitz.com/edit/github-snqp2r?file=package.json](https://stackblitz.com/edit/github-snqp2r?file=package.json)

**Comment by Teranode** [comment]
vjs core pushed version 3.3.4 to fix this issue so you can use that now: https://github.com/vuejs/core/issues/8353

**Comment by 07akioni** [comment]
这个是 vue 的 bug，应该已经修复了
