### ISSUE TITLE
请问有没有微信群方便大家交流的

### ISSUE THREAD

**Issue by yq5858588** [tusen-ai/naive-ui#4831]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.3

### Browser and its version (浏览器及其版本)
98

### System and its version (系统及其版本)
win10

### Node version (Node 版本)
14

### Reappearance link (重现链接)
https://github.com/tusen-ai/naive-ui/issues/new/choose

### Reappearance steps (重现步骤)
请问有没有微信群方便大家交流的

### Expected results (期望的结果)
请问有没有微信群方便大家交流的

### Actual results (实际的结果)
请问有没有微信群方便大家交流的

### Remarks (补充说明)
请问有没有微信群方便大家交流的

**Comment by qingsoft** [comment]
同求一个微信群

**Comment by yudan215** [comment]
有个钉钉群，但几乎没人说话

**Comment by qingsoft** [comment]
> 有个钉钉群，但几乎没人说话

加了，感觉群不活跃

**Comment by 07akioni** [comment]
有几个钉钉群，微信群没有。未来可能考虑整几个
