### ISSUE TITLE
n-switch设置checked-value为数字无法选中

### ISSUE THREAD

**Issue by yudan215** [tusen-ai/naive-ui#4833]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://naive-ui.github.io/看下面的地址

### Reappearance steps (重现步骤)
https://1024code.com/codecubes/zqsmi6w

### Expected results (期望的结果)
应为选中状态

### Actual results (实际的结果)
未选中

**Comment by yudan215** [comment]
> ![image](https://user-images.githubusercontent.com/46394163/239417323-439ebb52-9563-4005-8e48-d7065542c75d.png)

结果一样的，并且这样是字符串不是数字啊

**Comment by jizai1125** [comment]
> 

`value` 属性才对，不是 `checked`

**Comment by yudan215** [comment]
> > 
> 
> `value` 属性才对，不是 `checked`

3Q`大意了

**Comment by yudan215** [comment]
> > 
> 
> `value` 属性才对，不是 `checked`

3Q`大意了
