### ISSUE TITLE
信息 Message组件内有较长单词时显示的内容不全

### ISSUE THREAD

**Issue by maddenBoy** [tusen-ai/naive-ui#4835]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Chroem（113.0.5672.127）

### System and its version (系统及其版本)
Window11

### Reappearance link (重现链接)
https://codesandbox.io/s/gallant-cherry-b0yqy0?file=/src/Demo.vue

### Reappearance steps (重现步骤)
1、使用message组件，单个单词长度过长会导致内容无法显示完全

### Expected results (期望的结果)
1、使用message组件，单个单词长度过长不影响内容显示（可能加上work-break能解决）

### Actual results (实际的结果)
使用message组件，单个单词长度过长会导致内容无法显示完全

#### 截图
![image](https://github.com/tusen-ai/naive-ui/assets/71129660/9a13ebb9-891d-4243-b24a-e190821470f2)
#### 默认不给n-message__content类加上work-break:all效果
![image](https://github.com/tusen-ai/naive-ui/assets/71129660/73152179-9106-43bc-a5c8-58183e8371c5)
#### 给n-message__content类加上work-break:all后正常显示
![image](https://github.com/tusen-ai/naive-ui/assets/71129660/78e76a20-da59-41ce-90c7-cbde215c697f)

**Comment by amadeus711** [comment]
更新最新版本

**Comment by maddenBoy** [comment]
> 更新最新版本
最新版本似乎没完全解决这个问题。。。。。
![image](https://github.com/tusen-ai/naive-ui/assets/71129660/6b30f49b-b421-4763-afdc-0b5106040743)

**Comment by XiaoSongWolf** [comment]
长数字或长字母还是不能自动换行
