### ISSUE TITLE
scrollbar 组件在IOS上无滚动条展示

### ISSUE THREAD

**Issue by BarryZhan** [tusen-ai/naive-ui#4838]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
微信浏览器

### System and its version (系统及其版本)
IOS

### Reappearance link (重现链接)
https://codesandbox.io/s/kmoxwn

### Reappearance steps (重现步骤)
在移动端无滚动条展示，PC及Chrome模拟器滚动条会出现

### Expected results (期望的结果)
出现滚动条

### Actual results (实际的结果)
无滚动条

**Comment by 07akioni** [comment]
如此设计的。iOS 的滚动条体验使用系统原生。

**Comment by jmni-cn** [comment]
不过在data-table上使用时，滚动条在ios设备上不会展示出来
![image](https://github.com/user-attachments/assets/0ad74755-ec8f-462d-8320-e5781ca08354)
