### ISSUE TITLE
tree/tree-select/Cascader 在异步加载模式下，支持深层次节点的label回显

### ISSUE THREAD

**Issue by yingnian** [tusen-ai/naive-ui#4840]
### This function solves the problem (这个功能解决的问题)
tree-select/Cascader 异步加载模式时，用户选择完数据项后，存入后台的一般都是 value，但是在编辑的时候，需要回显 label。

### Expected API (期望的 API)
能否支持 开发者直接传入一个节点对象，比如 {label: '名称', value: 1 }，然后直接显示出来label

**Comment by sinpor** [comment]
#3058 
能否支持在打开时展开到已选择项。目前是不会展开的。
![image](https://github.com/tusen-ai/naive-ui/assets/35513921/5e95ff3c-2673-45d1-8d96-20ed62d554a2)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
