### ISSUE TITLE
data-table组件难道无法使用代码来控制多选表格前面的checkbox吗

### ISSUE THREAD

**Issue by gtrgeg** [tusen-ai/naive-ui#4843]
### This function solves the problem (这个功能解决的问题)
我们有一个需求，就是用户希望点击行的同时就可以直接勾选当前行前面的checkbox。查阅了naiveui的组件库api貌似都没有看到有任何方法支持通过js代码来控制表格行前面checkbox的选中状态。目前采取的方式是使用dom元素匹配然后手动加类名。但是这种方式低效且丑陋，请问有官方的api能直接控制多选data-table的checkbox吗。如有且告知，如无也请告知。
### Expected API (期望的 API)
row-props/selected-rows.sync

**Comment by CoolJun777** [comment]
你可以尝试下  v-model:checked-row-key

**Comment by amadeus711** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/46394163/1ff0800d-581f-4bfd-8b77-0d8e57006d3c)
可以使用这个给每个单元格包个事件 div ,取到 row-key 之后使用 v-model:checked-row-key

**Comment by horseson2018** [comment]
> v-model:checked-row-key

https://codesandbox.io/p/sandbox/angry-morse-fhzj5k?file=%2Fsrc%2FDemo.vue%3A9%2C1-10%2C1
没用啊
