### ISSUE TITLE
动态录入组件，watch生成的数据时，出现的数据结构不一致

### ISSUE THREAD

**Issue by mryfan** [tusen-ai/naive-ui#4844]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Microsoft Edge 版本 113.0.1774.50 (正式版本) (64 位)

### System and its version (系统及其版本)
windows 11

### Node version (Node 版本)
v18.16.0

### Reappearance link (重现链接)
https://codesandbox.io/s/condescending-bogdan-5xtikp?file=/src/Demo.vue

### Reappearance steps (重现步骤)
1.打开上面codesandbox的链接。
2.打开浏览器的开发者工具的控制台
3.点击浏览器页面动态录入组件的“ ”按钮
4.观察控制台打印出来的数据格式

### Expected results (期望的结果)
数组的值的结构不是Proxy或者结构统一

### Actual results (实际的结果)
数组的值的结构有的是Proxy，有的不是Proxy

**Comment by mryfan** [comment]
Reappearance steps 里面的第3步，是 “ 加号”   （+）按钮

**Comment by mryfan** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/28995283/564b5b4f-f573-48bb-832e-ce89ceb0a640)

**Comment by amadeus711** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/46394163/e9203324-a33d-4b10-919d-9da889640d6a)
特殊数据接口自己用这个 api 处理

**Comment by mryfan** [comment]
我没有用到特殊的数据结构，我的意思是说直接点击加号按钮，这个组件生成的数组里面存在proxy类型的值，但是也存在不是prosy的值，我的意思是这个能不能统一成 都不是proxy类型的值呢

**Comment by mryfan** [comment]
@amadeus711
