### ISSUE TITLE
主题编辑器和NConfigProvider组件不支持Select组件

### ISSUE THREAD

**Issue by chuxinone** [tusen-ai/naive-ui#4850]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Google Chrome 113.0.5672.126

### System and its version (系统及其版本)
Mac 11.2.3

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/select#Select-Props

### Reappearance steps (重现步骤)
主题编辑器或n-config-provider组件配置Select样式无效

### Expected results (期望的结果)
相关样式覆盖生效

### Actual results (实际的结果)
没有覆盖

**Comment by amadeus711** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/46394163/3ebc6c98-0935-4e09-bf6e-17c52a3fd554)
![image](https://github.com/tusen-ai/naive-ui/assets/46394163/70ef7817-3b12-45a2-94d4-3e5f2052f976)
说一下具体情况，我这面看是生效的

**Comment by chuxinone** [comment]
> ![image](https://user-images.githubusercontent.com/46394163/240850124-3ebc6c98-0935-4e09-bf6e-17c52a3fd554.png) ![image](https://user-images.githubusercontent.com/46394163/240850292-70ef7817-3b12-45a2-94d4-3e5f2052f976.png) 说一下具体情况，我这面看是生效的

Select:{
  borderHover: "1px solid #2080f0",
  borderFocus: "1px solid #2080f0",
  boxShadowFocus:'none',
  border: '1px solid rgb(224, 224, 230)',
  borderActive: '1px solid #0f1813',
}

正常情况下在主题编辑器中配置上述配置是会生效的，但是现在是没有生效，select样式更像是内联到style了一样，如果这样来配置input是生效的，但是select无效

**Comment by jizai1125** [comment]
> hover、ficus、active等样式无法更改，无论怎么更改，它都是绿色的边框。除非css全局强制覆盖
> Select:{
borderHover: "1px solid #2080f0",
borderFocus: "1px solid #2080f0",
boxShadowFocus:'none',
border: '1px solid rgb(224, 224, 230)',
borderActive: '1px solid #0f1813',
}

正常情况下在主题编辑器中配置上述配置是会生效的，但是现在是没有生效，select样式更像是内联到style了一样，如果这样来配置input是生效的，但是select无效

有些组件复用了其他组件，要使用 peers 才能修改；参考 [调整主题 - 使用 peers 主题变量](https://www.naiveui.com/zh-CN/os-theme/docs/customize-theme#%E4%BD%BF%E7%94%A8-peers-%E4%B8%BB%E9%A2%98%E5%8F%98%E9%87%8F)

**Comment by chuxinone** [comment]
> > hover、ficus、active等样式无法更改，无论怎么更改，它都是绿色的边框。除非css全局强制覆盖
> 
> > Select:{
> > borderHover: "1px solid #2080f0",
> > borderFocus: "1px solid #2080f0",
> > boxShadowFocus:'none',
> > border: '1px solid rgb(224, 224, 230)',
> > borderActive: '1px solid #0f1813',
> > }
> > 正常情况下在主题编辑器中配置上述配置是会生效的，但是现在是没有生效，select样式更像是内联到style了一样，如果这样来配置input是生效的，但是select无效
> 
> 有些组件复用了其他组件，要使用 peers 才能修改；参考 [调整主题 - 使用 peers 主题变量](https://www.naiveui.com/zh-CN/os-theme/docs/customize-theme#%E4%BD%BF%E7%94%A8-peers-%E4%B8%BB%E9%A2%98%E5%8F%98%E9%87%8F) 例如修改 Select 组件 https://codesandbox.io/s/naiveui-themeoverrides-9nv18w?file=/src/Demo.vue

我知道了，这里有个想法，当前UI框架默认颜色是绿色，有没有可能实现设定某一个变量或通过配置某个选项让UI主题色变成黑色或其他指定色，当前这种配置太麻烦了

**Comment by jizai1125** [comment]
> 我知道了，这里有个想法，当前UI框架默认颜色是绿色，有没有可能实现设定某一个变量或通过配置某个选项让UI主题色变成黑色或其他指定色，当前这种配置太麻烦了
可以呀，全局修改主题变量

**Comment by jizai1125** [comment]
> > > 我知道了，这里有个想法，当前UI框架默认颜色是绿色，有没有可能实现设定某一个变量或通过配置某个选项让UI主题色变成黑色或其他指定色，当前这种配置太麻烦了
> > 
> > 
> > 可以呀，全局修改主题变量
> 
> 比如 我想让input menu select 这些组件默认的绿色变成蓝色，我应该怎么做？sass变量吗？

看文档啊，兄弟

**Comment by chuxinone** [comment]
> > > > 我知道了，这里有个想法，当前UI框架默认颜色是绿色，有没有可能实现设定某一个变量或通过配置某个选项让UI主题色变成黑色或其他指定色，当前这种配置太麻烦了
> > > 
> > > 
> > > 可以呀，全局修改主题变量
> > 
> > 
> > 比如 我想让input menu select 这些组件默认的绿色变成蓝色，我应该怎么做？sass变量吗？
> 
> 看文档啊，兄弟

!!! 我目前只知道主题编辑器这个，还不知道别的方法，我查阅了文档，可能是我没有找到，你能否给个demo

**Comment by jizai1125** [comment]
> > > > > 我知道了，这里有个想法，当前UI框架默认颜色是绿色，有没有可能实现设定某一个变量或通过配置某个选项让UI主题色变成黑色或其他指定色，当前这种配置太麻烦了
> > > > 
> > > > 
> > > > 可以呀，全局修改主题变量
> > > 
> > > 
> > > 比如 我想让input menu select 这些组件默认的绿色变成蓝色，我应该怎么做？sass变量吗？
> > 
> > 
> > 看文档啊，兄弟
> 
> !!! 我目前只知道主题编辑器这个，还不知道别的方法，我查阅了文档，可能是我没有找到，你能否给个demo

看文档调整主题章节

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
