### ISSUE TITLE
data-table数据表格自定义loading会与表格loading冲突

### ISSUE THREAD

**Issue by chuxinone** [tusen-ai/naive-ui#4863]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
最新google

### System and its version (系统及其版本)
mac12

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/data-table#controlled-page.vue

### Reappearance steps (重现步骤)
data-table数据表格自定义loading会与表格loading冲突,
比如如下代码会与dataTable的自带loading同时出现

<template #loading>
                <n-spin >
                  <n-alert title="啦啦啦" type="success">
                    明天再打开行李箱。宝贝，挂电话啦。
                  </n-alert>
                  <template #description>
                    你不知道你有多幸运
                  </template>
                </n-spin>
              </template>

### Expected results (期望的结果)
使用了loading Slots后,table自带的loading应不应该出现

### Actual results (实际的结果)
使用了loading Slots后,table自带的loading应不应该出现

### Remarks (补充说明)
使用了loading Slots后,table自带的loading应不应该出现

**Comment by jizai1125** [comment]
我试了没问题
[78d8344b-8252-4ce1-92cb-7ce92d088beb.webm](https://github.com/tusen-ai/naive-ui/assets/33979706/76a7e5f5-94d4-45e7-928d-3c01fd3259fc)
