### ISSUE TITLE
Tooltip style cannot be set in NEllipsis

### ISSUE THREAD

**Issue by artsmp0** [tusen-ai/naive-ui#4866]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Chrome 113.0.5672.126 (arm64)（macos）

### System and its version (系统及其版本)
macos(13.3.1)

### Node version (Node 版本)
v18.16.0

### Reappearance link (重现链接)
https://codesandbox.io/s/unruffled-hellman-27krj1?file=/src/Demo.vue

### Reappearance steps (重现步骤)
I want to set tooltip width, because tooltip maxWidth was deprecated.

### Expected results (期望的结果)
use tooltip style can be set normally.

### Actual results (实际的结果)
it can't, and type was incorrect.

### Remarks (补充说明)
<img width="957" alt="image" src="https://github.com/tusen-ai/naive-ui/assets/129932371/a6725769-747d-46aa-b51b-854a7497109f">

**Comment by amadeus711** [comment]
Try using this prop:
![image](https://github.com/tusen-ai/naive-ui/assets/46394163/267c6e79-b2d6-4234-8f95-3d8b22e6908a)

**Comment by artsmp0** [comment]
> Try using this prop: ![image](https://user-images.githubusercontent.com/46394163/241611551-267c6e79-b2d6-4234-8f95-3d8b22e6908a.png)

Thank you very much for your answer! Yes, it will work, but it will display extra length in the content very short time
<img width="602" alt="image" src="https://github.com/tusen-ai/naive-ui/assets/129932371/286c774b-44d8-4098-8213-c0b4b6b1fde8">

**Comment by amadeus711** [comment]
Give me a repo, I'll investigate it

**Comment by artsmp0** [comment]
> Give me a repo, I'll investigate it

Thanks!!!, Repo was here: https://github.com/artsmp0/gupo-naive-admin/blob/master/src/layout/components/Sider.vue#L44

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
