### ISSUE TITLE
n-carousel的嵌套使用（外层effect设置custom，里面effect设置card）

### ISSUE THREAD

**Issue by haohao809** [tusen-ai/naive-ui#4868]
### This function solves the problem (这个功能解决的问题)
现在有这样需求，在一个大的轮播图中，有一个item页面内部嵌套一个小的轮播图，分别控制，嵌套之后小的轮播没有切换效果，变成静态图片了，感觉图层不对点击不动
### Expected API (期望的 API)
n-carousel能够嵌套使用

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
