### ISSUE TITLE
Dropdown menu-props option undefined

### ISSUE THREAD

**Issue by yudan215** [tusen-ai/naive-ui#4871]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
win10

### Node version (Node 版本)
2.34.3

### Reappearance link (重现链接)
https://naive-ui.github.io/

### Reappearance steps (重现步骤)
一共有3个选项，但是menu-props 的option只打印了2次，并且都是undefined	

### Expected results (期望的结果)
与node-props一样option不会undefined	

### Actual results (实际的结果)
一直undefined

**Comment by amadeus711** [comment]
没看懂问题，请详细描述使用场景并提供最小化复现沙盒

**Comment by yudan215** [comment]
> 没看懂问题，请详细描述使用场景并提供最小化复现沙盒

https://1024code.com/codecubes/zqsmi6w 《naive-ui》，请点击链接或复制链接到浏览器打开，在线查看和运行

**Comment by jizai1125** [comment]
`menu-props` 的定义 ` (option: DropdownOption | undefined, options: (DropdownOption | DropdownGroupOption)[]) => HTMLAttributes`
option 代表在多级菜单中的父级节点，你的示例代码 undefined 是正常的

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
