### ISSUE TITLE
add "is-leaf-key" for data table

### ISSUE THREAD

**Issue by yockii** [tusen-ai/naive-ui#4873]
### This function solves the problem (这个功能解决的问题)
for tree data table, sometimes the remote response data won't have the field "isLeaf", this causes some translate code.
数据表格的树状表格使用时，有时候后端返回数据没有字段 isLeaf，就需要前端进行代码转换增加该字段，希望能够直接支持
### Expected API (期望的 API)
is-leaf-key, like row-key, should like as following:
添加属性is-leaf-key，类似 row-key一样，期望如下：
1. (row) => row.childrenCount > 0
2. (row) => row.hasChildren

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
