### ISSUE TITLE
数据表格在 Chrome 71 下无法上下滑动

### ISSUE THREAD

**Issue by yorickshan** [tusen-ai/naive-ui#4877]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
chrome 71

### System and its version (系统及其版本)
windows 10

### Reappearance link (重现链接)
https://codesandbox.io/s/7ss411

### Reappearance steps (重现步骤)
在Chrome 71中加载数据表格然后尝试上下滑动，Chrome 71 环境获取：https://live.browserstack.com

### Expected results (期望的结果)
可以上下滑动数据

### Actual results (实际的结果)
无法上下滑动

**Comment by yorickshan** [comment]
chrome 72 下可以

**Comment by adoin** [comment]
哪家会给你兼容71啊。。。啥都干不了

**Comment by amadeus711** [comment]
这种特定版本出现的问题，大概率上层不好兼容

**Comment by yorickshan** [comment]
> chrome 72 下可以



>

**Comment by yorickshan** [comment]
> 哪家会给你兼容71啊。。。啥都干不了

我没描述清楚，是 Android 9 的 webview（Chrome 68）会有这个问题，自己解决了，css 的兼容问题

**Comment by yorickshan** [comment]
> 是 Android 9 的 webview（Chrome 68）会有这个问题，自己解决了，css 的兼容问题

是 Android 9 的 webview（Chrome 68）会有这个问题，自己解决了，css 的兼容问题

**Comment by yorickshan** [comment]
> 这种特定版本出现的问题，大概率上层不好兼容

具体是低版本的安卓，如 Android 9 的 webview（Chrome 68）会有这个问题，自己解决了 https://bugs.chromium.org/p/chromium/issues/detail?id=927066
