### ISSUE TITLE
add Filter 筛选组件

### ISSUE THREAD

**Issue by Baiyuetribe** [tusen-ai/naive-ui#4884]
### This function solves the problem (这个功能解决的问题)
一般作为筛选场景，作为筛选项组合,每个级别之间有联动
<img width="537" alt="image" src="https://github.com/tusen-ai/naive-ui/assets/43716063/44119264-5552-42a0-9565-c5c98db2e789">

### Expected API (期望的 API)
相关实现案例：https://xiaomi.github.io/hiui/components/filter

**Comment by jizai1125** [comment]
可以用 radio-group 实现，修改一下主题样式
https://codesandbox.io/s/immutable-morning-6nsy7y?file=/src/Demo.vue

**Comment by Baiyuetribe** [comment]
嗯，技术上是的，但是如果可加入就更好，毕竟这个模块也是比较常见的

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
