### ISSUE TITLE
support time-zone with date-picker

### ISSUE THREAD

**Issue by motea927** [tusen-ai/naive-ui#4885]
### This function solves the problem (这个功能解决的问题)
Currently, only [time-picker](https://www.naiveui.com/en-US/os-theme/components/time-picker#timezone.vue) support time-zone,
But it may cause date string error (I use timestamp value, but want to show fixed Timezone string)
So hope can add time-zone props into [date-picker](https://www.naiveui.com/en-US/os-theme/components/date-picker#General-Props) as same as a time-picker
### Expected API (期望的 API)
https://www.naiveui.com/en-US/os-theme/components/time-picker#timezone.vue

**Comment by brubraz** [comment]
Any workaround?

**Comment by Sepush** [comment]
close as duplicate #4821
