### ISSUE TITLE
upload组件的file对象上能不能加个response属性

### ISSUE THREAD

**Issue by pylist** [tusen-ai/naive-ui#4887]
### This function solves the problem (这个功能解决的问题)
存放服务器响应过来的数据, 不然现在都没办法取response
### Expected API (期望的 API)
file: {response:{}}

**Comment by jizai1125** [comment]
#4124

**Comment by pylist** [comment]
> 可以在 `finish` 事件回调的 event 中去拿
> 
> ```ts
> function handleFinish(options: { file: UploadFileInfo; event?: ProgressEvent }) {
>   if (options.file.status === 'finished') {
>     const response = (options.event?.target as XMLHttpRequest).response
>   }
> }
> ```
> 
> 相关 issue #4124

非常感谢, event?.target能找到response可以先用了, 这个issue我关闭了

**Comment by undefind-cre** [comment]
发布到线上之后event里面target 的值为null

**Comment by linjiangl** [comment]
![image](https://github.com/user-attachments/assets/330023b7-c727-4299-b848-4cfdd9d67800)
产线还是有问题
