### ISSUE TITLE
support NNumberAnimation component add prefix and suffix props

### ISSUE THREAD

**Issue by flingyp** [tusen-ai/naive-ui#4894]
### This function solves the problem (这个功能解决的问题)
Sometimes, we use NNumberAnimation to need showing a number with prefix or suffix.
Examples:  ￥184,228,210、52%

### Expected API (期望的 API)
I think whether component provides prefix and suffix props. 
It's like: 
`<n-number-animation :from="0" :to="184228210" show-separator prefix="￥" />`
`<n-number-animation :from="0" :to="52" show-separator suffix="%" />`

**Comment by jizai1125** [comment]
I think you can use `n-number-animation` with `n-statistic` component to achieve the effect.
https://codesandbox.io/s/hopeful-hypatia-658vhj?file=/src/Demo.vue:16-25

**Comment by flingyp** [comment]
Cool! I didn't pay attention to have `n-statistic` component. Thanks!
