### ISSUE TITLE
[Dropdown] 可以增加一个异步控制的属性吗？

### ISSUE THREAD

**Issue by Hisioni** [tusen-ai/naive-ui#4901]
### This function solves the problem (这个功能解决的问题)
类似于 switch 的 loading，有时候我们在点击条目的时候，需要异步交互后台，进行处理后完成整个点击操作。

增加一个异步控制的属性，如果当启用该属性时，onSelect 传入异步函数，执行函数时，条目显示为 loading 状态，当函数执行完成后，完成 loading 消失并关闭 dropdown
### Expected API (期望的 API)
add prop `async`

then made `onSelect` must be `Promise` or `return boolean function`

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
