### ISSUE TITLE
[Dialog] An instance of the component that needs to expose the rendered content slot

### ISSUE THREAD

**Issue by pdsuwwz** [tusen-ai/naive-ui#4904]
### This function solves the problem (这个功能解决的问题)
Such as the `n-form` verification in the Dialog, when triggering the `positiveClick` callback,
first trigger the validation verification in the component, and continue to execute the following code after passing the verification
### Expected API (期望的 API)
```ts
import Test from './Test.vue'
dialog.info({
  title: 'test',
  content: () => h(Test, { modelValue: { foo: 123 } }),
  positiveText: '确认',
  async onPositiveClick (e, instance) {
    console.log('->', instance)

    await instance.validation()

    await MockAPI.updateForm()
    // ...
  }
})

```

```ts
// Test.vue
defineExpose({
  validation: () => {/** ... */}
})
```

```ts
// Get the content instance through the second parameter when the button is triggered
//  (if content is a component)
async onPositiveClick (e, instance) {
  console.log('->', instance)
  await instance.validation()
 }
```

I'm not sure if there is another solution. What I understand is that I need to change the source code to meet my needs, and I'm not sure if this applies to most needs. That's why the issue arises.

**Comment by jizai1125** [comment]
I think you can use the component ref directly. 
```ts
const testRef = ref()

dialog.info({
  title: 'test',
  content: () => h(Test, { ref: testRef }),
  positiveText: '确认',
  async onPositiveClick (e, instance) {
    // some exposed validate method...
    testRef.value.validateMethod()
  }
})
```

**Comment by pdsuwwz** [comment]
@jizai1125 
Hello, thanks for the idea. In your method, you need to define `ref` every time you use it. Personally, I feel that one more step is not friendly to lazy people like me🤔, but I tried your method and it is feasible, thank you very much, it can solve my problem now :) 🙏

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
