### ISSUE TITLE
n-date-picker兼容问题

### ISSUE THREAD

**Issue by kenixFog** [tusen-ai/naive-ui#4913]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
chrome  58.0.3029.110 (64-bit)

### System and its version (系统及其版本)
win11

### Reappearance steps (重现步骤)
基于vue-cli开发环境下，chrome 58下正常显示，打包后，页面无法渲染，经过排查

暂时注释掉跟日期相关的代码后打包就可正常运行

` <n-date-picker v-model:value="date"  type="date" />`

### Expected results (期望的结果)
是否可以或者有什么好的办法，可以兼容？

babel.config.js配置

module.exports = {
  presets: [
    '@babel/preset-env',
    '@vue/app',
  ],
}

### Actual results (实际的结果)
页面无法渲染

**Comment by kenixFog** [comment]
应该说，与会触发弹出层的这种，好像都会有问题，比如n-select，不晓得是不是css不兼容，作者是否有好的建议？这个有的运行环境受限，没法升级浏览器

**Comment by amadeus711** [comment]
这个场景是因为旧版浏览器没有项目用于实现组件的API。目前团队的人力情况无法支持对**浏览器特定版本**以及**版本过于落后**的兼容。

**Comment by UTing1119** [comment]
@amadeus711 iOS手機safari以及chrome都無法使用n-date-picker，有好的建議嗎?使用的都是最新的

手機: iphone 12
iOS版本: 16.6
Chrome: 116.0.5845.103
