### ISSUE TITLE
When the DataTable component uses the scrollTo method to scroll after opening a virtual list, excessive scrolling distance can lead to inaccurate display of view positions.

### ISSUE THREAD

**Issue by CLD5186** [tusen-ai/naive-ui#4914]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Chrome(113.0.5672.126)

### System and its version (系统及其版本)
Macos(13.4)

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/data-table#virtual.vue

### Reappearance steps (重现步骤)
使用官方大量数据表格demo，然后通过scrollTo方法进行滚动.若滚动距离过大,就会造成展示的行与滚动行不一致的问题。
Demo using official large data tables and scroll through the scrollTo method. If the scrolling distance is too large, it can cause inconsistency between the displayed rows and the scrolling rows.

### Expected results (期望的结果)
期望长距离滚动位置准确。
Expect accurate positioning for long-distance scrolling.

### Actual results (实际的结果)
比如跳转10行，也就是10行*单行的高度.滚动的高度是准确的，但是在大量数据下,滚动1000行就会不准确了。
For example, jumping to 10 lines, which is the height of 10 lines * a single line. The scrolling height is accurate, but in large amounts of data, scrolling 1000 lines will become inaccurate

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
