### ISSUE TITLE
Data table default-expand-all attribute asynchronously

### ISSUE THREAD

**Issue by haohao809** [tusen-ai/naive-ui#4915]
### This function solves the problem (这个功能解决的问题)
Whether to expand all expandable rows by default in the default-expand-all attribute, which cannot be used when expanding rows asynchronously. The data of the table is all asynchronous. Can lazy loading and asynchronous expansion be done? Currently, my solution is to get all the data through a callback before displaying the fully expanded table.
### Expected API (期望的 API)
be used when expanding rows asynchronously

**Comment by 2556227850** [comment]
我也想知道这个问题怎么解决

**Comment by Amine27** [comment]
> ### This function solves the problem (这个功能解决的问题)
> Whether to expand all expandable rows by default in the default-expand-all attribute, which cannot be used when expanding rows asynchronously. The data of the table is all asynchronous. Can lazy loading and asynchronous expansion be done? Currently, my solution is to get all the data through a callback before displaying the fully expanded table.
> 
> ### Expected API (期望的 API)
> be used when expanding rows asynchronously

Can you share your solution please ? Thank you.

**Comment by Kerwin1202** [comment]
+1

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by noeGnh** [comment]
Use key on the component and change it value after data is load for refresh data table component. You can make something like this:

```
<script setup>
  const tableKey = ref(uuidv4())

  const loadAsyncData = async () => {
    // Load your data
    //...
    tableKey.value = uuidv4()
  }
</script>

<template>
  //...
  <n-data-table
    :key="tableKey"
    :columns="columns"
    :data="tableData"
    :loading="isLoading"
    :single-line="false"
    :scroll-x="1200"
    size="small"
    striped
    default-expand-all />
  //...
</template>
```
