### ISSUE TITLE
Transfer自定义列表中清除已选择某个节点，节点状态不会改变，无论父节点还是子节点，除非全部清除

### ISSUE THREAD

**Issue by chuxinone** [tusen-ai/naive-ui#4917]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
1

### System and its version (系统及其版本)
1

### Node version (Node 版本)
1

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/transfer

### Reappearance steps (重现步骤)
Transfer自定义列表中清除已选择某个节点，节点状态不会改变，无论父节点还是子节点，除非全部清除。比如官网的demo种的自定义列表，全选后在右边已选中的节点中清掉某一个，左侧的节点状态不会变，除非清掉父节点

### Expected results (期望的结果)
Transfer自定义列表中清除已选择某个节点，节点状态不会改变，无论父节点还是子节点，除非全部清除。比如官网的demo种的自定义列表，全选后在右边已选中的节点中清掉某一个，左侧的节点状态不会变，除非清掉父节点

### Actual results (实际的结果)
Transfer自定义列表中清除已选择某个节点，节点状态不会改变，无论父节点还是子节点，除非全部清除。比如官网的demo种的自定义列表，全选后在右边已选中的节点中清掉某一个，左侧的节点状态不会变，除非清掉父节点

### Remarks (补充说明)
Transfer自定义列表中清除已选择某个节点，节点状态不会改变，无论父节点还是子节点，除非全部清除。比如官网的demo种的自定义列表，全选后在右边已选中的节点中清掉某一个，左侧的节点状态不会变，除非清掉父节点

**Comment by amadeus711** [comment]
![20230608095134](https://github.com/tusen-ai/naive-ui/assets/46394163/df9bbd14-8f6b-46cc-8b5c-b808e14e4f09)
未复现，需要提供稳定复现的最小沙盒环境

**Comment by chuxinone** [comment]
> ![20230608095134](https://user-images.githubusercontent.com/46394163/244241861-df9bbd14-8f6b-46cc-8b5c-b808e14e4f09.gif) 未复现，需要提供稳定复现的最小沙盒环境

我给你录制了一个视频，里面包含了数据，代码就是上面贴的代码，包

https://github.com/tusen-ai/naive-ui/assets/47303119/29acc1ce-22b3-4ba6-8c81-91bc20ebc58b

含重现过程

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
