### ISSUE TITLE
刷新dataTable的选中值

### ISSUE THREAD

**Issue by lidakun-six** [tusen-ai/naive-ui#4918]
### This function solves the problem (这个功能解决的问题)
在调用不同的Api的时候，可以清除onUpdateCheckedRowKeys函数选中的值，将checked的值初始化
### Expected API (期望的 API)
initChecked，值用true和false，每次请求数据的时候清空Checked的值

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
