### ISSUE TITLE
Ability to define the allowed file extensions in NUpload Component

### ISSUE THREAD

**Issue by umang-gramener** [tusen-ai/naive-ui#4920]
### This function solves the problem (这个功能解决的问题)
In a use case where the file extensions are to be limited, NUpload component does not natively support that, 
This Feature Request can help solve this, and this use case is pretty common for a file upload.
### Expected API (期望的 API)
A new parameter in the component like accept, which inside sets the parameter to accept attribute of file input

**Comment by jahnli** [comment]
https://www.naiveui.com/zh-CN/os-theme/components/upload#Upload-Props

`accept` already exists
