### ISSUE TITLE
"types": ["naive-ui/volar"]不生效呢

### ISSUE THREAD

**Issue by l406054531** [tusen-ai/naive-ui#4928]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Google Chrome  114.0.5735.110

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://codepen.io/l406054531/pen/qBQBYwx

### Reappearance steps (重现步骤)
在tsconfig.json中设置  "types": ["naive-ui/volar"], 没代码提示，volar最新版的

### Expected results (期望的结果)
<n-button type='">   type正常来说是会有提示的把

### Actual results (实际的结果)
没提示

**Comment by cxzx150133** [comment]
看上去好像是 VSCode 的锅，临时解决办法：
https://github.com/vuejs/language-tools/issues/3268#issuecomment-1586587133
后续等 volar 的 ts 版本跟进吧。

**Comment by Mask-MJ** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/41281346/88d6a4fc-cefc-419a-80a3-ce0b4e1d5525)
点击{}切换工作区版本

**Comment by l406054531** [comment]
> ![图像](https://user-images.githubusercontent.com/41281346/245359605-88d6a4fc-cefc-419a-80a3-ce0b4e1d5525.png)点击{}切换工作区版本

帅

**Comment by 1071125093** [comment]
解决了 牛逼
