### ISSUE TITLE
upload上传组件自定义多次重复上传文件

### ISSUE THREAD

**Issue by ttkican** [tusen-ai/naive-ui#4931]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Google Chrome 114.0.5735.110

### System and its version (系统及其版本)
win11

### Reappearance link (重现链接)
https://github.com/tusen-ai/naive-ui/issues/4928

### Reappearance steps (重现步骤)
<n-upload ref="uploadRef" :custom-request="customUpload">
        <n-button>选择文件</n-button>
      </n-upload>
自定义上传多次重复发送请求上传文件

### Expected results (期望的结果)
<n-upload ref="uploadRef" :custom-request="customUpload">
        <n-button>选择文件</n-button>
      </n-upload>
自定义上传不要重复发送请求

### Actual results (实际的结果)
<n-upload ref="uploadRef" :custom-request="customUpload">
        <n-button>选择文件</n-button>
      </n-upload>

**Comment by amadeus711** [comment]
需要最小可复现的沙盒环境

**Comment by tq0810** [comment]
自定义上传（custom-request），default-upload=true：第一次选择只发一次请求，成功后再重新选择一张图，就会发出两次，成功后再重新选一张，就会发出三次，以此类推，随着次数增加就会发出很多请求。

**Comment by kingwrcy** [comment]
@tq0810 上传成功后手动调用清除方法,清除上次的文件

**Comment by Enaium** [comment]
> @tq0810 上传成功后手动调用清除方法,清除上次的文件

这样就不能显示上传过的图片了

**Comment by kingwrcy** [comment]
上传过的图片服务端都返回给你上传之后的地址了,为什么显示不了呢?显示不了的话,你手动创建个img显示一下也是可以的.

**Comment by Enaium** [comment]
> 上传过的图片服务端都返回给你上传之后的地址了,为什么显示不了呢?显示不了的话,你手动创建个img显示一下也是可以的.

clear就相当于把上传的列表清空，清空后就不能显示上传过的图片了，所有只能这样做

**Comment by Enaium** [comment]
> 需要最小可复现的沙盒环境

https://www.naiveui.com/zh-CN/os-theme/components/upload#image-card-style.vue
每次上传都会把已经上传过的再次上传一遍，也就是说会多次调用customRequest

**Comment by NiceDayToDie** [comment]
使用自定义上传`custom-request`的时候，当请求完成后需调用`options.onFinish()`，可以[参考文档相关部分代码](https://www.naiveui.com/zh-CN/os-theme/components/upload#custom-request.vue)，不然就会造成多次调用`customRequest`的情况

**Comment by SchneeHertz** [comment]
> 使用自定义上传`custom-request`的时候，当请求完成后需调用`options.onFinish()`，可以[参考文档相关部分代码](https://www.naiveui.com/zh-CN/os-theme/components/upload#custom-request.vue)，不然就会造成多次调用`customRequest`的情况

感谢，我也遇到了这个问题，用你的方法是可行的
@amadeus711 可以把要求调用onFinish加到文档中吗？

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by water-Jan** [comment]
> 使用自定义上传`custom-request`的时候，当请求完成后需调用`options.onFinish()`，可以[参考文档相关部分代码](https://www.naiveui.com/zh-CN/os-theme/components/upload#custom-request.vue)，不然就会造成多次调用`customRequest`的情况

就是这个，已解决，谢谢🙏
