### ISSUE TITLE
NImage component supports customizing the toolbar and adding image download |NImage组件支持工具栏自定义

### ISSUE THREAD

**Issue by simaoczc** [tusen-ai/naive-ui#4932]
### This function solves the problem (这个功能解决的问题)
1、目前的组件只支持 show-toolbar 控制显示隐藏。在移动端希望能删减掉一些工具按钮，缩小尺寸。
2、希望工具栏增加图片下载功能，可供开发者选择配置。

---

1、the component only supports the "show-toolbar" option to control its visibility. For mobile devices, it is desired to remove some toolbar buttons and reduce its size.
2、add image download functionality to the toolbar, allowing developers to configure it as needed.
### Expected API (期望的 API)
增加toolbar-list 参数，指定工具条的功能点
---
add the "toolbar-list" parameter to specify the functionality points of the toolbar.

**Comment by simaoczc** [comment]
#4240 希望早日合并这个pr 🎉

**Comment by jahnli** [comment]
The author is working on incorporating PR

**Comment by jahnli** [comment]
download tool is complete   https://github.com/tusen-ai/naive-ui/pull/4864
