### ISSUE TITLE
Ability to pass parameters to the n-dropdown select callback function

### ISSUE THREAD

**Issue by spyderdsn** [tusen-ai/naive-ui#4935]
### This function solves the problem (这个功能解决的问题)
```
<-- v-for item in items -->
<template>
  <n-dropdown trigger="hover" :options="options" @select="handleSelect(key, item.id, item.name)">
    <n-button>Edit</n-button>
  </n-dropdown>
</template>
<-- v-for item in items -->

```
I don't see a way to pass additional parameters to the dropdown option callback function. I have dynamically created item parameters in the loop which need to be passed for the scenarios such as:

Edit Item 1, Edit Item 2
### Expected API (期望的 API)
`@select="handleSelect(key, props)`

**Comment by jahnli** [comment]
https://codesandbox.io/s/compassionate-satoshi-987prm?file=/src/Demo.vue

Is that what you were hoping for?

**Comment by spyderdsn** [comment]
Yes! Thanks, the documentation is not clear on how to do it. I’ve actually managed to do it by changing the trigger to click and attaching a second @click event which runs a seperate function which updates data() props.

**Comment by caopengan** [comment]
> https://codesandbox.io/s/compassionate-satoshi-987prm?file=/src/Demo.vue Is that what you were hoping for?

Well done

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
