### ISSUE TITLE
data table tooltip width

### ISSUE THREAD

**Issue by hyuckjin12** [tusen-ai/naive-ui#4939]
### This function solves the problem (这个功能解决的问题)
https://www.naiveui.com/en-US/os-theme/components/data-table#ellipsis-tooltip.vue

ellipsis: {
      tooltip: true,
    },

Is there a way to give tooltip width or max-width style in data table?
### Expected API (期望的 API)
https://www.naiveui.com/en-US/os-theme/components/data-table#ellipsis-tooltip.vue

**Comment by jahnli** [comment]
```
 ellipsis: { tooltip: { contentStyle: { maxWidth: '600px'} } }
```

**Comment by hyuckjin12** [comment]
thank you!
