### ISSUE TITLE
data-tabel when set flex-height and scroll-x, if data is a empty array, tabel header can't scroll.

### ISSUE THREAD

**Issue by web-jcm** [tusen-ai/naive-ui#4944]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
windows 10

### Reappearance link (重现链接)
https://codesandbox.io/s/hopeful-hellman-n82fxh?file=/src/Demo.vue

### Reappearance steps (重现步骤)
https://codesandbox.io/s/hopeful-hellman-n82fxh?file=/src/Demo.vue

### Expected results (期望的结果)
can scroll

### Actual results (实际的结果)
can't scroll

**Comment by amadeus711** [comment]
@07akioni

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
