### ISSUE TITLE
input Number组件在禁用状态下可以使用鼠标放上去通过滚动滚轮更改值

### ISSUE THREAD

**Issue by lidakun-six** [tusen-ai/naive-ui#4952]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Microsoft Edge 114.0.1823.43 (正式版本) (arm64)

### System and its version (系统及其版本)
mac OS 13.4 (22F66)

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/input-number

### Reappearance steps (重现步骤)
使用一个input Number组件，将它的状态设置为disabled，把鼠标放上去滚动滚轮，它的值依旧会改变

### Expected results (期望的结果)
input Number组件在禁用状态下不能被鼠标滚轮控制

### Actual results (实际的结果)
在使用input Number组件的时候将它的状态设置为禁用，它依然会被鼠标滚轮控制而更改值

**Comment by lidakun-six** [comment]
希望可以修复一下这个bug

**Comment by jahnli** [comment]
没复现，是否可以提供一个 `codesandbox` 链接

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
