### ISSUE TITLE
为什么官网进去不呀

### ISSUE THREAD

**Issue by mingzibuzongyao** [tusen-ai/naive-ui#4953]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
1

### System and its version (系统及其版本)
11

### Reappearance link (重现链接)
https://www.naiveui.com/

### Reappearance steps (重现步骤)
为什么官网进去不呀

### Expected results (期望的结果)
为什么官网进去不呀

### Actual results (实际的结果)
为什么官网进去不呀

**Comment by jahnli** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/20943608/4509f43c-a7dd-4716-9813-d1204bd033b2)

**Comment by Sepush** [comment]
网站是托管在 Vercel 的有时候可能会因为总所周知的原因无法访问
