### ISSUE TITLE
AutoComplete: the class prop is not working when the option created by renderOption

### ISSUE THREAD

**Issue by zhouweiming** [tusen-ai/naive-ui#4958]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36

### System and its version (系统及其版本)
MacOS(13.4)

### Node version (Node 版本)
19.7

### Reappearance link (重现链接)
git@github.com:zhouweiming/naive-ui-demo.git

### Reappearance steps (重现步骤)
```
git clone git@github.com:zhouweiming/naive-ui-demo.git
cd naive-ui-demo
npm install
npm run dev
```

open the web url in brower
input 1 or 2

### Expected results (期望的结果)
background color of the menu option is red

### Actual results (实际的结果)
background color of the menu option is transparent

**Comment by jahnli** [comment]
The repo is empty

**Comment by zhouweiming** [comment]
> The repo is empty

Sorry! The repository has just been uploaded.

**Comment by jahnli** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/20943608/534f47d7-eb69-4711-bd03-9ef5f4ae7d53)

去掉 `scope` 或者 :deep( *** )

**Comment by jahnli** [comment]
当 <style> 标签带有 scoped attribute 的时候，它的 CSS 只会影响当前组件的元素，和 Shadow DOM 中的样式封装类似。使用时有一些注意事项

**Comment by zhouweiming** [comment]
> ![image](https://user-images.githubusercontent.com/20943608/246333480-534f47d7-eb69-4711-bd03-9ef5f4ae7d53.png)
> 
> 去掉 `scoped`

I know removing scoped works, but scoped is required

**Comment by jahnli** [comment]
Closed due to inactivity. Feel free to reopen if you're still having trouble
