### ISSUE TITLE
使用 <script setup  </script>語法糖 表格無法實現只有升降序, 没有無序這個情况

### ISSUE THREAD

**Issue by dennydam** [tusen-ai/naive-ui#4961]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
chorme

### System and its version (系统及其版本)
window11

### Reappearance link (重现链接)
https://codesandbox.io/s/quiet-snowflake-ss4k99?file=/src/Demo.vue

### Reappearance steps (重现步骤)
I used the above link but using <script setup </scrip> it's doesn't working

### Expected results (期望的结果)
know the answer

### Actual results (实际的结果)
it's bug maybe?

**Comment by Sepush** [comment]
false should be boolean not string

**Comment by dennydam** [comment]
> false should be boolean not string
i try but it's not work
