### ISSUE TITLE
可拖拽调整的容器分割组件

### ISSUE THREAD

**Issue by kexirong** [tusen-ai/naive-ui#4964]
### This function solves the problem (这个功能解决的问题)
类似arco伸缩框功能
效果参考链接：https://arco.design/react/components/resize-box
### Expected API (期望的 API)
![image](https://github.com/tusen-ai/naive-ui/assets/31177595/43502b5e-b3e8-4b09-b47e-720b169be05b)

**Comment by Sepush** [comment]
close as duplicate https://github.com/tusen-ai/naive-ui/issues/1111
