### ISSUE TITLE
下拉菜单 Dropdown设置点击触发时，点击iframe时无法隐藏显示的下拉菜单

### ISSUE THREAD

**Issue by maddenBoy** [tusen-ai/naive-ui#4970]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Chrome（114.0.5735.134）

### System and its version (系统及其版本)
windows11

### Reappearance link (重现链接)
https://codesandbox.io/s/wonderful-einstein-xtjqw2

### Reappearance steps (重现步骤)
1、给dropdown组件设置trigger="click"
2、点击iframe视图中的任意地方

### Expected results (期望的结果)
下拉菜单 Dropdown设置点击触发时，点击iframe时隐藏显示的下拉菜单

### Actual results (实际的结果)
下拉菜单 Dropdown设置点击触发时，点击iframe时无法隐藏下拉菜单

#### 截图
![image](https://github.com/tusen-ai/naive-ui/assets/71129660/d8cdfbab-e0fd-4f38-85df-20aca4d40761)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
