### ISSUE TITLE
提高样式的可定制性

### ISSUE THREAD

**Issue by lightpeace312** [tusen-ai/naive-ui#4972]
### This function solves the problem (这个功能解决的问题)
感觉是因为使用了CSS in JS的方式使得样式可定制性比较差
1：useThemeVar中只提供了部分变量
2：比如多种不同类型的button，一个是type=primary， 一个是type=primary secondary 两个按钮，其类是一样的，现在需要只给前者加上一个蓝色阴影（不适用于后者）就无法实现了，只能通过改JS吗？但感觉CSS in JS封装的太多了。本来就需要了解一套CSS规则，现在还需要再了解作者封装的规则，基本不具有操作性

### Expected API (期望的 API)
希望还是能提供更方便的方法（支持大量使用css变量，但是必要的 css类或者任何其他cSS可选择标识来区分不同的组件还是不可或缺的）

**Comment by liuzw2579** [comment]
1、定制 正常应该使用 configProvider 的 `theme-overrides` 去定制 全局 common 和组件的变量；
组件自身也可以自定主题 
![image](https://github.com/tusen-ai/naive-ui/assets/30503937/957bae39-840d-4b38-a24f-e2661300528a)

2、我理解的应该是 
```css
.n-button--primary-type:not(.n-button--secondary) {
    ...
 }
```
