### ISSUE TITLE
使用Avatar 在互联网上，没有人知道你是一条狗。

### ISSUE THREAD

**Issue by yunhouhuang** [tusen-ai/naive-ui#4975]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
0

### System and its version (系统及其版本)
Win11

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/avatar

### Reappearance steps (重现步骤)
https://www.naiveui.com/zh-CN/light/components/avatar

### Expected results (期望的结果)
希望可以尊重一下大家，不要人身攻击。

### Actual results (实际的结果)
如果非要这么用，请换一下人称用词，应该把"你"换成"我"，谢谢。

**Comment by jahnli** [comment]
在互联网上, `没有人知道你是一条狗` 是一句广为人知的网络用语，它提醒人们在虚拟世界中保护自己的隐私和安全，同时也警醒人们不要轻易相信网上的信息和陌生人
