### ISSUE TITLE
Can I specify values ​​such as position x, y when displaying a dialog?

### ISSUE THREAD

**Issue by hyuckjin12** [tusen-ai/naive-ui#4978]
### This function solves the problem (这个功能解决的问题)
Can I specify values ​​such as position x, y when displaying a dialog?

dialog.success({
	// x?:
        // y?:
})
### Expected API (期望的 API)
https://www.naiveui.com/en-US/os-theme/components/dialog#Dialog-Props

**Comment by jizai1125** [comment]
Can use `style` prop to customize the position.  for example
```ts
dialog.success({
  style: {
    position: 'fixed',
    right: 0,
    top: 0
  }
})
```
