### ISSUE TITLE
数据表格 Data Table remote模式 默认选中checked-row-keys 必须设置为字符串才能起效果

### ISSUE THREAD

**Issue by liwsVincent** [tusen-ai/naive-ui#4982]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Chrome（89）

### System and its version (系统及其版本)
Windows10

### Reappearance link (重现链接)
https://github.com/tusen-ai/naive-ui

### Reappearance steps (重现步骤)
在remote模式下 设置row-key
function RowKey(row) {
  return row.id as number;
}
设置默认选中
const checkedRowKeysRef = ref([1,4442]);

设置选中响应
function handleUpdateUserCheckedRowKeysRef(keys: Array<string | number>, rows: object[]) {
  console.log('keys:', keys, rows);
}
<n-data-table
              v-model:checked-row-keys="checkedRowKeysRef"
              remote
              :columns="userColumns"
              :row-key="RowKey"
              :data="dataRef"
              :pagination="userPagination"
              max-height="400px"
              size="small"
              @update:checked-row-keys="handleUpdateUserCheckedRowKeysRef"
/>

### Actual results (实际的结果)
加载表格，默认选中不起效果，点击选中后控制台打印
keys: (3) [1, 4442, '4442']
修改代码如下后，默认选中效果与预期一致
const checkedRowKeysRef = ref(["1","4442"]);
指定rowKey的类型是数字，但是选中后 checkedRowKeys数组的类型还是字符串数组

### Remarks (补充说明)
查看源码与实例，猜测在不指定rowKey时，用数字代表选中的行的索引，指定rowKey时checkedRowKey只能用字符串类型。如果猜测不正确，请修复bug。如果猜测正确请补充文档。
export type RowKey = string | number;

**Comment by jizai1125** [comment]
没发现你说的问题
https://codesandbox.io/s/busy-panka-zt8zrm?file=/src/Demo.vue

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
