### ISSUE TITLE
pls add a function to the Scrollbar

### ISSUE THREAD

**Issue by GavinZhou0125** [tusen-ai/naive-ui#4983]
### This function solves the problem (这个功能解决的问题)
When I use the Scrollbar component as a chat window, it doesn't automatically scroll to the bottom when a new reply appears.
### Expected API (期望的 API)
const scrollbar = useScrollbar()
scrollbar.goButtom()

**Comment by jizai1125** [comment]
Can use [scrollTo](https://www.naiveui.com/zh-CN/os-theme/components/scrollbar#Scrollbar-Methods) method, `scrollbarRef.value.scrollTo({ position: 'bottom' })`

**Comment by GavinZhou0125** [comment]
`position` doesn't lies in ScrollToOptions.
```ts
interface ScrollToOptions extends ScrollOptions {
    left?: number;
    top?: number;
}
```

**Comment by jahnli** [comment]
```
const s = ref<ScrollbarInst>()
s.value?.scrollBy({})
s.value?.scrollTo({})
```

**Comment by jahnli** [comment]
> `position`不在于 ScrollToOptions 中。
> 
> ```ts
> interface ScrollToOptions extends ScrollOptions {
>     left?: number;
>     top?: number;
> }
> ```

```
const s = ref<ScrollbarInst>()
s.value?.scrollBy({})
s.value?.scrollTo({})
```

**Comment by GavinZhou0125** [comment]
Now I can only use 
```ts
scrollbarRef.value.scrollTo({ top: 9999999 })
```
which is unsafe since the page can be very long.

**Comment by jizai1125** [comment]
> 

or  `scrollbarRef.value.scrollTo({ top: Number.MAX_SAFE_INTEGER })`
