### ISSUE TITLE
数据表格增加一个复制功能

### ISSUE THREAD

**Issue by yhy0** [tusen-ai/naive-ui#4986]
### This function solves the problem (这个功能解决的问题)
数据表格增加一个copyable属性来控制该单元格内容是否可以复制
### Expected API (期望的 API)
  {
    title: 'id',
    key: 'id',
    copyable: true,
  },

**Comment by jahnli** [comment]
`rowProps`  +  [Clipboard API](https://developer.mozilla.org/zh-CN/docs/Web/API/Clipboard_API)

**Comment by yapengsoft** [comment]
自己二封一下table 就行了
