### ISSUE TITLE
NScrollbar need a `size` demo

### ISSUE THREAD

**Issue by recallwei** [tusen-ai/naive-ui#4991]
### This function solves the problem (这个功能解决的问题)
The size parameter seems not working.
### Expected API (期望的 API)
None

**Comment by jizai1125** [comment]
我试了可以的呀  https://codesandbox.io/s/competent-wave-2cwwd3?file=/src/Demo.vue
但是有个疑惑，源码里面滚动条长度计算为什么还要加上 `props.size * 1.5`，`yRailSize * containerHeight) / contentHeight + props.size * 1.5`

**Comment by jahnli** [comment]
`size` 是生效的，但是不是他误以为 `size` 指的是 `滚动条宽高`

**Comment by jizai1125** [comment]
@jahnli 你知道为什么还要加上 `props.size * 1.5` 么  😳

**Comment by jahnli** [comment]
@jizai1125  不知道是不是单纯为了增加滚动条的长度

**Comment by recallwei** [comment]
@jizai1125 这个 size 是滚动条宽度吗，我怎么看不出来

**Comment by jahnli** [comment]
这个 `size`  不是滚动条宽度

**Comment by jizai1125** [comment]
> @jizai1125 这个 size 是滚动条宽度吗，我怎么看不出来

是长度

**Comment by jahnli** [comment]
如果要设置`滚动条` `x轴时高度` 或 `y轴时宽度` 可以使用 `theme vars`

**Comment by recallwei** [comment]
@jizai1125 ok, 感觉描述不清楚，size 怎么感觉都是滚动条的大小，不是长度，长度是不是叫 length 比较好
