### ISSUE TITLE
问下如果我树状选择器,选择了子项全部，怎么样父项不会自动打勾

### ISSUE THREAD

**Issue by zhangle1** [tusen-ai/naive-ui#4994]
### This function solves the problem (这个功能解决的问题)
1 （不要打勾）
 1-1 ✔
 1-2✔
这样我可以只查询选择子项的数据
### Expected API (期望的 API)
如上

**Comment by jahnli** [comment]
`cascade`

对比 https://codesandbox.io/s/xwo7pz 、 https://codesandbox.io/s/ji52kk

**Comment by zhangle1** [comment]
@jahnli  谢谢这个对我有用
