### ISSUE TITLE
The year is disabled when some months of the year are disabeld.

### ISSUE THREAD

**Issue by hungryfoolou** [tusen-ai/naive-ui#4997]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.2

### Browser and its version (浏览器及其版本)
Chome(70.0.3538.77)

### System and its version (系统及其版本)
Windows(10)

### Node version (Node 版本)
16.17.1

### Reappearance link (重现链接)
https://codesandbox.io/s/suspicious-cannon-zqxmzt?file=/src/App.vue

### Reappearance steps (重现步骤)
English:
1.Use a n-date-picker and set type value 'month'.
2.Set is-date-disabled vlue which not more than last year.
3.Find some monthes are disabled, this is correct, but the year 2022 is also disabled. This lead when we change to 2023 and we want choose some month of 2022, but we find that we can't click 2022.
4.The quesition disappear when  is-date-disabled vlue is not more doday.
中文：
1.使用type为month的n-date-picker组件。
2.为属性 is-date-disabled设置值，值不能超过去年今日，比如如果今日为2023-6-28，则不能选择2022年6月及之前的时间。
3.我们发现2022年的一些月份（1月-6月）被disabled了，这是正确了，但同时，年份2022也被disabled了，这会导致当我们切换到2023年后如果想选择2022年某些月份（比如7月）时，不能点击2022年。
4.如果为 is-date-disabled设置值为不超过今年今日，则不存在该问题，2023这个数字仍然可以点击。

### Expected results (期望的结果)
The year is not disabled which some months of the year are disabled.

### Actual results (实际的结果)
The year is disabled which some months of the year are disabled.

### Remarks (补充说明)
The quesition disappear when  is-date-disabled vlue is not more doday.

**Comment by jizai1125** [comment]
Duplicate #4649

**Comment by Sepush** [comment]
close as duplicate
