### ISSUE TITLE
Cascader options width

### ISSUE THREAD

**Issue by Tamerlan94** [tusen-ai/naive-ui#5004]
### This function solves the problem (这个功能解决的问题)
Please add prop "consistent menu width" in cascader component as in select component. Because option in cascader are small width size and long length text are cutted in frame
### Expected API (期望的 API)
Like as select prop consistent menu width

**Comment by Sepush** [comment]
https://github.com/tusen-ai/naive-ui/issues/5360

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
