### ISSUE TITLE
avatar组件设置lazy后fallback属性失效，不能在失败后显示图片

### ISSUE THREAD

**Issue by FeiFanLiang** [tusen-ai/naive-ui#5007]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
windows

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/avatar

### Reappearance steps (重现步骤)
同时设置lazy属性和fallback后，图片加载失败不能正确显示fallback，onError回调也没有触发

### Expected results (期望的结果)
在加载失败后，正确显示fallback

### Actual results (实际的结果)
失败后，fallback失效

### Remarks (补充说明)
![image](https://github.com/tusen-ai/naive-ui/assets/30872365/6f205bf9-b3c4-4da2-92b8-97500bbb83c0)
![image](https://github.com/tusen-ai/naive-ui/assets/30872365/8f66f3c9-bd7e-4b34-bc0e-d48372059e34)

**Comment by jahnli** [comment]
```
const shouldStartLoadingRef = ref(!props.lazy)

const handleError = (e: Event): void => {
    if (!shouldStartLoadingRef.value) return
}
```

**Comment by jahnli** [comment]
- 关于 `on-error` 源码中是这样设计的，需要确定具体用意

```
const shouldStartLoadingRef = ref(!props.lazy)

const handleError = (e: Event): void => {
    if (!shouldStartLoadingRef.value) return
}
```

- `lazy` 时, 可以先 `render-placeholder` 替代

```
:render-placeholder="renderPlaceholder"

renderPlaceholder() {
  return h('div', 'placeholder')
},
```

**Comment by FeiFanLiang** [comment]
那设置的fallback也无效，使用lazy属性后，没办法进行fallback吗？
