### ISSUE TITLE
颜色选择器组件请支持获取各种modes下的颜色对象

### ISSUE THREAD

**Issue by Jeremyly** [tusen-ai/naive-ui#5008]
### This function solves the problem (这个功能解决的问题)
当前颜色选择器的值类型是string，而modes有好几种，既没提供获取modes当前值的方法，也没有提供获取各种modes对应的颜色对象。还需要自己实现对字符串的分析去获取颜色对象。非常不方便。希望实现相关功能方便获取颜色对象。
### Expected API (期望的 API)
api形如：
```
 function  getRGBA() {
......
return RGBA{R:number;g:number;b:number;A:number}
}
```

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
