### ISSUE TITLE
Modal Theme Overrides do not work

### ISSUE THREAD

**Issue by spyderdsn** [tusen-ai/naive-ui#5010]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Chrome, latest

### System and its version (系统及其版本)
MacOS

### Reappearance link (重现链接)
https://www.naiveui.com/en-US/light/components/modal

### Reappearance steps (重现步骤)
Use your Theme Editor tool, even on your website the modal Color, textColor do not work.

### Expected results (期望的结果)
Color to be changed.

### Actual results (实际的结果)
Nothing

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
