### ISSUE TITLE
Clicking on an image while previewing an NImage image in NPopover will close abnormally

### ISSUE THREAD

**Issue by cc-hearts** [tusen-ai/naive-ui#5013]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Chrome(114.0.5735.133)

### System and its version (系统及其版本)
MacOS(13.2.1 (22D68))

### Node version (Node 版本)
16.17.0

### Reappearance link (重现链接)
https://codesandbox.io/s/suspicious-ben-574g4c

### Reappearance steps (重现步骤)
1. Click the button and wait for the image to load
2. Click on the image and wait for the image preview to appear
3. Click on the picture to enlarge or reduce operations, the picture will be closed abnormally

### Expected results (期望的结果)
In popover, click the image to enlarge the operation can still preview without closing

### Actual results (实际的结果)
Clicking on the image to enlarge in popover will turn off the image preview

**Comment by amadeus711** [comment]
You need customize the display of `n-popover` according to your own business logic:
https://codesandbox.io/s/affectionate-alex-w3zcxq?file=/src/App.vue
