### ISSUE TITLE
表单行内模式直接用select框，样式会被挤压

### ISSUE THREAD

**Issue by TenXLL** [tusen-ai/naive-ui#5014]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
chrome(114.0.5735.91)

### System and its version (系统及其版本)
windows11

### Reappearance link (重现链接)
https://github.com/TenXLL/crane-front-boot

### Reappearance steps (重现步骤)
<n-form
    ref="formRef"
    inline
    :label-width="80"
    :model="formValue"
    :rules="rules"
    :size="size"
  >
    <n-form-item label="姓名" path="user.name">
      <n-input v-model:value="formValue.user.name" placeholder="输入姓名" />
    </n-form-item>
    <n-form-item label="年龄" path="user.age">
      <n-input v-model:value="formValue.user.age" placeholder="输入年龄" />
    </n-form-item>
    <n-form-item label="电话号码" path="phone">
      <n-input v-model:value="formValue.phone" placeholder="电话号码" />
    </n-form-item>
    <n-form-item label="性别" path="phone">
      <n-select
        v-model:value="formValue.sex"
        :options="options"
        placeholder="电话号码"
      />
    </n-form-item>
    <n-form-item>
      <n-button attr-type="button" @click="handleValidateClick">验证</n-button>
    </n-form-item>
  </n-form>

### Expected results (期望的结果)
给出解决方案

### Actual results (实际的结果)
使用行内模式之后，select框被挤压到最小

**Comment by amadeus711** [comment]
https://codesandbox.io/s/gallant-wildflower-f669v2?file=/src/Demo.vue
行内情况下 `n-select` 需要设置 `width` style
