### ISSUE TITLE
dataTable 获取数据有问题

### ISSUE THREAD

**Issue by lidakun-six** [tusen-ai/naive-ui#5017]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
版本 114.0.1823.58 (正式版本) (arm64)

### System and its version (系统及其版本)
MacOS13.4.1 (22F82)

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/data-table

### Reappearance steps (重现步骤)
当你使用分页的时候，在第一个页数勾选一个数据，然后跳到第二个页面勾选一个数据，勾选到的数据第一个数据会被置成undefined，也就是OnUpdateCheckedRowKeys里面的第二个参数rows，获取不到第一个数据

### Expected results (期望的结果)
修复此bug

### Actual results (实际的结果)
这个bug给我带来了bug

**Comment by amadeus711** [comment]
此行为符合预期，若想获取全部的勾选数据，需要使用：
![image](https://github.com/tusen-ai/naive-ui/assets/46394163/83dc7008-d5d1-455c-90d8-b2d00a700866)
