### ISSUE TITLE
Auto-generated Icon

### ISSUE THREAD

**Issue by spyderdsn** [tusen-ai/naive-ui#5018]
### This function solves the problem (这个功能解决的问题)
I'm using xicons and my 'tempIcon' will change based on the data parameter. If I do this:

`<n-icon :component="tempIcon" size="26"></n-icon>`

```
data() {
    return {
      tempIcon: 'Sun'
    }
},
methods: {
    newIcon() {
        this.tempIcon = 'Rain'
    }
}
```

The icon won't render. But if I do this:

`<n-icon :component="Sun" size="26"></n-icon>`
`<n-icon :component="Rain" size="26"></n-icon>`

The icon will render correctly.

### Expected API (期望的 API)
Add support.

**Comment by thelostword** [comment]
``` js
data() {
    return {
      tempIcon: Sun
    }
},
methods: {
    newIcon() {
        this.tempIcon = Rain
    }
}
```
It should be like this
