### ISSUE TITLE
keep scroll x able when data list is empty（在列表为空的时候依旧可以横向滚动）

### ISSUE THREAD

**Issue by xaios** [tusen-ai/naive-ui#5024]
### This function solves the problem (这个功能解决的问题)
when data list is empty, the table can't scroll x, can't show all the columns, and the scrollLeft will be 0

列表为空的时候不能横向滚动列表，无法展示完整的表头内容，而且横向滚动会恢复到最左侧
### Expected API (期望的 API)
```html
<n-data-table scroll-empty />
<n-data-table /> run in default is better
```

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by dggrok** [comment]
> ### This function solves the problem (这个功能解决的问题)
> when data list is empty, the table can't scroll x, can't show all the columns, and the scrollLeft will be 0
> 
> 列表为空的时候不能横向滚动列表，无法展示完整的表头内容，而且横向滚动会恢复到最左侧
> 
> ### Expected API (期望的 API)
> <n-data-table scroll-empty />
> <n-data-table /> run in default is better

这个问题解决了吗 空数据的时候也可以又滚动条
