### ISSUE TITLE
请求封装 pro-components 提升开发效率

### ISSUE THREAD

**Issue by InfernalAzazel** [tusen-ai/naive-ui#5032]
### This function solves the problem (这个功能解决的问题)
目前挺多有 pro-components  比如 element-pro-components antdv-pro-components，周游使用各种 UI 库最后还是选择 naive-ui，naive-ui 设计上的优秀是毋庸置疑的，希望能封装 pro-components 提升开发效率，可能只需要实现 2个组件  pro-layout 和 pro-crud

github 上面有很多naive-ui 开源的 admin 为什么还要封装 pro-components？

1. 每个开源的 admin 写法和封装都不一样，没有统一标准
2. 学习成本高
3. 上手难度大
4. 开发效率不好说，可能针对前端开发老手效率提升吧。

### Expected API (期望的 API)
1. pro-layout 
5. pro-crud

**Comment by Sepush** [comment]
you can write your own pro components.
open source it.
we woulde be glad to add it to community resources.
