### ISSUE TITLE
请求封装 pro-components 提升开发效率

### ISSUE THREAD

**Issue by InfernalAzazel** [tusen-ai/naive-ui#5033]
### This function solves the problem (这个功能解决的问题)
目前挺多有 pro-components  比如 element-pro-components antdv-pro-components，周游使用各种 UI 库最后还是选择 naive-ui，naive-ui 设计上的优秀是毋庸置疑的，希望能封装 pro-components 提升开发效率，可能只需要实现 2个组件  pro-layout 和 pro-crud
### Expected API (期望的 API)
1. pro-layout 
2. pro-crud

**Comment by Zheng-Changfu** [comment]
可以尝试 [pro-naive-ui](https://naive-ui.pro-components.cn/)
