### ISSUE TITLE
data-table列宽拖拽功能运行与期望不符

### ISSUE THREAD

**Issue by houxg** [tusen-ai/naive-ui#5036]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Chrome

### System and its version (系统及其版本)
MacOS

### Reappearance link (重现链接)
```
<template>
    <div style="width:100%">
        <n-data-table :columns="columns" :data="data" :bordered="false" />
    </div>
</template>

<script lang="ts" setup>
const columns = [
  {
    title: 'No',
    key: 'no',
    width: 50,
    resizable: true
  },
  {
    title: 'Title',
    key: 'title',
    resizable: true
  },
  {
    title: 'Length (minWidth: 100, maxWidth: 500)',
    key: 'length',
    resizable: true,
    minWidth: 100,
    maxWidth: 500
  },
  {
    title: 'Action',
    key: 'actions',
    resizable: true
  }
]

const data = [
  { no: 3, title: 'Wonderwall', length: '4:18', action: "ok" },
  { no: 4, title: "Don't Look Back in Anger", length: '4:48', action: "ok" },
  { no: 12, title: 'Champagne Supernova', length: '7:27', action: "ok" }
]
</script>
```

### Reappearance steps (重现步骤)
鼠标拖拽"Action"左侧的列宽调整条，向右侧移动

### Expected results (期望的结果)
"Length"列宽度变小, "Action"宽度增加, "Title"宽度不变

### Actual results (实际的结果)
"Length"列宽度变小, "Title"宽度增加, "Action"宽度不变

### Remarks (补充说明)
先拖拽"title"右侧的列宽调整条，缩小"title"宽度，再按复现步骤操作，则表现正常

**Comment by houxg** [comment]
官网示例demo就有这个问题

https://www.naiveui.com/zh-CN/os-theme/components/data-table#column-draggable.vue

**Comment by amadeus711** [comment]
补充：部分情况下会出现拖拽闪动
![20230711093132](https://github.com/tusen-ai/naive-ui/assets/46394163/d4abc550-49f8-4e46-8f6a-df5a9a5c0ef2)
![20230711093205](https://github.com/tusen-ai/naive-ui/assets/46394163/27a79d7b-d684-4d46-9729-aa2d3ec19d81)

**Comment by jizai1125** [comment]
> 鼠标拖拽"Action"左侧的列宽调整条，向右侧移动
> Expected results (期望的结果)
> "Length"列宽度变小,  "Title"宽度不变，"Action"宽度增加
> Actual results (实际的结果)
> "Length"列宽度变小,  "Title"宽度增加,，"Action"宽度不变
按照你的代码，鼠标拖拽"Action"左侧的列宽调整条，向右侧移动，拖拽的是 Length 列，实际结果不应该是 "Length"列宽度变大, "Title"宽度变大，"Action"宽度减小么

**Comment by houxg** [comment]
> > 鼠标拖拽"Action"左侧的列宽调整条，向右侧移动
> > Expected results (期望的结果)
> > "Length"列宽度变小,  "Title"宽度不变，"Action"宽度增加
> > Actual results (实际的结果)
> > "Length"列宽度变小,  "Title"宽度增加,，"Action"宽度不变
> 
> 按照你的代码，鼠标拖拽"Action"左侧的列宽调整条，拖拽的是 Length 列，向右侧拖动，实际结果不应该是 "Length"列宽度变大, "Title"宽度变大，"Action"宽度减小么？

抱歉，应该是Length列向左侧拖拽，目前是会增加"Title"的宽度，但期望是增加"Action"的宽度

**Comment by jizai1125** [comment]
> > > 鼠标拖拽"Action"左侧的列宽调整条，向右侧移动
> > > Expected results (期望的结果)
> > > "Length"列宽度变小,  "Title"宽度不变，"Action"宽度增加
> > > Actual results (实际的结果)
> > > "Length"列宽度变小,  "Title"宽度增加,，"Action"宽度不变
> > 
> > 
> > 按照你的代码，鼠标拖拽"Action"左侧的列宽调整条，拖拽的是 Length 列，向右侧拖动，实际结果不应该是 "Length"列宽度变大, "Title"宽度变大，"Action"宽度减小么？
> 
> 抱歉，应该是Length列向左侧拖拽，目前是会增加"Title"的宽度，但期望是增加"Action"的宽度

那现在功能是符合预期的，向左拖拽 Length 列，结果 Length 列宽度变小，Ttitle 列、Action 宽度变大，没问题啊

**Comment by houxg** [comment]
@jizai1125 期望是title不变，length减小，action增大哦。如您gif所示，拖拽length与action之间的调整条，title增大比较反直觉

**Comment by jizai1125** [comment]
> @jizai1125 期望是title不变，length减小，action增大哦。如您gif所示，拖拽length与action之间的调整条，title增大比较反直觉

因为你 title 列又没固定宽度，这表现是正常的

**Comment by houxg** [comment]
原来如此，那确实是我对data-table理解不够了

**Comment by little-fisher** [comment]
这个拖动列宽很容易误触到排序唉
