### ISSUE TITLE
移动端点击dropdown第一项的上方区域也会触发on-select

### ISSUE THREAD

**Issue by csl784513390** [tusen-ai/naive-ui#5037]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
chrome 114.0.5735.199

### System and its version (系统及其版本)
windows

### Reappearance link (重现链接)
https://codesandbox.io/embed/sleepy-wing-v2j9gz?file=/package.json&codemirror=1

### Reappearance steps (重现步骤)
切换浏览器到移动端样式，点击按钮使下拉菜单显示出来，点击第一个选项偏上的位置（鼠标已经离开第一项），会触发第一项的点击

### Expected results (期望的结果)
点击第一项区域外上面的地方不会触发第一项的点击事件

### Actual results (实际的结果)
触发第一项的点击

**Comment by Sepush** [comment]
https://github.com/tusen-ai/naive-ui/assets/39197136/2faab121-72db-4571-854b-7292ac55a4f4

can not reproduction
