### ISSUE TITLE
Tree的scrollTo方法支持选择滚动到最顶或最底

### ISSUE THREAD

**Issue by houxg** [tusen-ai/naive-ui#5038]
### This function solves the problem (这个功能解决的问题)
Tree的常用场景是展示多级目录，scrollTo可以以使当前目录出现在可以看到的位置。实际使用scrollTos时发现期望key的item滚动到了最底而不是最顶，对于展示目录来说造成了不方便，希望改进。
### Expected API (期望的 API)
scrollTo({key:string, position:string})

**Comment by suica** [comment]
看起来需要修改一下上游vueuc中VirtualList的scrollTo方法：

https://github.com/07akioni/vueuc/blob/2a994f5af02afd54b93e30aceb939ad63dd2d13e/src/virtual-list/src/VirtualList.ts#L60C1-L61C1

```ts
(options: { index: number, position?: 'top' | 'bottom' } & CommonScrollToOptions): void
(options: { key: string | number, position?: 'top' | 'bottom' } & CommonScrollToOptions): void
```

**Comment by jahnli** [comment]
https://github.com/tusen-ai/naive-ui/pull/5198
