### ISSUE TITLE
n-input绑定为数字类型的值会报错，每次使用得转换类型，建议添加value可以绑定数字类型的值

### ISSUE THREAD

**Issue by rainbowder** [tusen-ai/naive-ui#5039]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
google chrome 114.0.5735.199（正式版本）

### System and its version (系统及其版本)
windows10

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/input#API

### Reappearance steps (重现步骤)
n-input  v-model绑定为数字类型的值会报错

### Expected results (期望的结果)
value可以绑定数字类型的值

### Actual results (实际的结果)
n-input v-model绑定为数字类型的值会报错

**Comment by Sepush** [comment]
If you want input number, what you need is `n-input-number` not `n-input`.
These are two different input types.
Don't mix them up.

**Comment by rainbowder** [comment]
i get it!Thinks
