### ISSUE TITLE
DataTable open virtual-scroll macbook 触摸板左右滚动 表格会上下抖动

### ISSUE THREAD

**Issue by monsterkai233** [tusen-ai/naive-ui#5040]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Chrome(114.0.5735.198)

### System and its version (系统及其版本)
MacOS(13.2.1)

### Node version (Node 版本)
16.14.0

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/data-table#virtual.vue

### Reappearance steps (重现步骤)
1 将官方案例缩小至出现横向滚动条
2 使用mac触摸板在内容区进行左右滑动（ps: 表头滚动正常）

### Expected results (期望的结果)
使用mac触摸板进行左右滑动时表格不会上下滚动

### Actual results (实际的结果)
表格出现横向滚动条时使用mac触摸板在内容区进行左右滑动时表格上下抖动

**Comment by jizai1125** [comment]
这是由于使用了 vueuc 的 `VirtualList` 组件造成的，触摸板左右滑动在 y 轴方向位置肯定会有偏移，所以造成了上下抖动
![11](https://github.com/tusen-ai/naive-ui/assets/33979706/a40b218e-fa2d-4e12-b09e-df66f4240a92)

**Comment by monsterkai233** [comment]
这个也使得我已经滚动了横向滚动条在中间的时候进行上下滚动时 在x轴方向也会动

**Comment by monsterkai233** [comment]
而且我用触摸板滚动到底部一直往下滚动会一直闪烁。。

**Comment by monsterkai233** [comment]
![20230713152344_rec_](https://github.com/tusen-ai/naive-ui/assets/52212023/5b13edbd-1268-4de9-8f33-055f2646d2ea)

**Comment by jizai1125** [comment]
> 而且我用触摸板滚动到底部一直往下滚动会一直闪烁。。

搞个在线示例看一下

**Comment by monsterkai233** [comment]
> > 而且我用触摸板滚动到底部一直往下滚动会一直闪烁。。
> 
> 搞个在线示例看一下

https://codesandbox.io/p/github/monsterkai233/naive-ui-datatable/draft/boring-snowflake

**Comment by monsterkai233** [comment]
![20230713154250_rec_](https://github.com/tusen-ai/naive-ui/assets/52212023/c12be3f8-787e-4fc6-984b-d946b91df994)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
