### ISSUE TITLE
用naive-ui做了个h5微应用，嵌入到钉钉里面，有个抽屉的折叠效果，在安卓上点击空白处抽屉折叠不回去

### ISSUE THREAD

**Issue by huangwenboha563** [tusen-ai/naive-ui#5045]
### TuSimple/naive-ui version (版本)
2.34.3

### Vue version (Vue 版本)
3.2.47

### Browser and its version (浏览器及其版本)
安卓版钉钉内置的浏览器

### System and its version (系统及其版本)
安卓机

### Node version (Node 版本)
16.14.2

### Reappearance link (重现链接)
https://codepen.io/pen?&prefill_data_id=13f2ae23-c85c-47f2-b2d2-d80b309e08d7

### Reappearance steps (重现步骤)
用naive-ui做了个h5微应用，嵌入到钉钉里面，有个抽屉的折叠效果，在安卓上点击空白处抽屉折叠不回去
ios机可以，安卓不行

### Expected results (期望的结果)
想知道抽屉用了啥css特性老板本浏览器不支持的吗，可以确定的是顶顶内部的web浏览器内核不高

### Actual results (实际的结果)
用naive-ui做了个h5微应用，嵌入到钉钉里面，有个抽屉的折叠效果，在安卓上点击空白处抽屉折叠不回去

### Remarks (补充说明)
不好意思，因为室内不应用，所以没有连接..随便填了个地址,实在不好意思

**Comment by amadeus711** [comment]
可能是项目实现的 clickoutside 无法兼容太旧版本的内核，具体代码：
https://github.com/07akioni/vdirs/blob/main/src/clickoutside.ts

**Comment by huangwenboha563** [comment]
你好，我确定了 钉钉的那个是chrome69，
我们的naiveui官网在这个版本的浏览器下也不能访问

**Comment by Sepush** [comment]
Edge、Firefox、Chrome、Safari 等现代浏览器的最新的 2 个版本确保会被支持。
对于这些浏览器的其他版本中，由于开发资源的限制并没有做过严格的测试。但是我们预期 naive-ui 应该在这些浏览器不算太老的版本上能正常的运行（比如 2 年之内的版本
chrome 69 太老了 2018年发布的版本了
