### ISSUE TITLE
tree component click

### ISSUE THREAD

**Issue by VegetaSuper** [tusen-ai/naive-ui#5047]
### This function solves the problem (这个功能解决的问题)
I've added the node-props property to the tree component and bound a click event, which I want not to fire when I click the collapse icon
### Expected API (期望的 API)
No idea

**Comment by oyal** [comment]
同样的需求

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
