### ISSUE TITLE
NForm validate error message array cannot access renderMessage field

### ISSUE THREAD

**Issue by recallwei** [tusen-ai/naive-ui#5048]
### This function solves the problem (这个功能解决的问题)
For i18n, I only use renderMessage for dynamically rendering text. But I must add a redundant `message` filed for error message now. Because `renderMessage` cannot access in the return of form `validate` function.
### Expected API (期望的 API)
Expected:
[
    [
        {
            "fieldValue": "",
            "field": "username",
            "message": " ",   //  if not set message, renderMessage instead
        }
    ]
]

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
