### ISSUE TITLE
DataTable virtualScroll resizeable 滚动到底部出现空白

### ISSUE THREAD

**Issue by monsterkai233** [tusen-ai/naive-ui#5049]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Chrome(114)

### System and its version (系统及其版本)
MacOS(13.2.1)

### Node version (Node 版本)
16.4.1

### Reappearance link (重现链接)
https://codesandbox.io/p/github/monsterkai233/naive-ui-datatable/main

### Reappearance steps (重现步骤)
1 首先我固定了第一列
2 在第二列设置了resizeable并且数据进行随机以达到每一行是不一样的高度
3 将滚动条滚动到底部 拖拽将第二列拖至较小值使得滚动条往上偏移
4 此时再次滚动滚动条到底部底部出现空白

### Expected results (期望的结果)
希望滚动到底部不要出现空白

### Actual results (实际的结果)
滚动到底部出现空白

**Comment by monsterkai233** [comment]
https://codesandbox.io/p/github/monsterkai233/naive-ui-datatable/draft/boring-snowflake

**Comment by monsterkai233** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/52212023/12d15380-59f5-45b3-b812-574674362a09)

**Comment by monsterkai233** [comment]
还有个问题是我设置了singleline为false，` .n-data-table:not(.n-data-table--single-line) .n-data-table-th.n-data-table-th--last {border-bottom: 0 solid var(--n-merged-border-color);}` 导致没有下边线了。。。

**Comment by jc840031139** [comment]
我也遇到这个问题 使用flex-height后 页面内表格不足一整页 最后一行没有下分割线

![image](https://github.com/tusen-ai/naive-ui/assets/34274229/0f9ed543-fdea-4301-9fe1-9a2716e7ff77)

**Comment by zkzeke** [comment]
你好，我也遇到这个问题，希望告知如何解决。

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
