### ISSUE TITLE
add loading prop to drawer

### ISSUE THREAD

**Issue by wc-matteo** [tusen-ai/naive-ui#505]
### This function solves the problem (这个功能解决的问题)
makes it easier to put an "async" component inside a drawer
### Expected API (期望的 API)
loading prop like other elements

**Comment by 07akioni** [comment]
Loading prop? How it should look.

**Comment by wc-matteo** [comment]
like a [button](https://www.naiveui.com/en-US/light/components/button)'s loading prop. Makes a spinner appear inside the drawer. I guess `n-spin` could be used for the purpose but a prop is handier...

**Comment by Talljack** [comment]
What's the usage scenario of this? I don’t think other frameworks have this feature
