### ISSUE TITLE
关于dataTable组件的在没有数据的时候，无法进行横向滚动的问题

### ISSUE THREAD

**Issue by CLD5186** [tusen-ai/naive-ui#5052]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
114.0.5735.198

### System and its version (系统及其版本)
13.4.1 (22F82)

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/data-table

### Reappearance steps (重现步骤)
写了复现的样例https://ngzrtr-5173.csb.app/

### Expected results (期望的结果)
若表格没有数据，应该还是存在底部滚动条。

### Actual results (实际的结果)
表格数据为空，底部滚动条就不在了。

**Comment by jahnli** [comment]
空数据时，表头会有滚动条

**Comment by CLD5186** [comment]
@jahnli https://ngzrtr-5173.csb.app/这是我复现的模版。第一个没有数据，头部没有出现滚动条（横向）。笔记本触摸屏的话是可以左右滑动的，但是如果pc鼠标的话，就没办法左右滑动了。

**Comment by jizai1125** [comment]
用鼠标滚轮横向滚动的话可以按住 shift 健

**Comment by CLD5186** [comment]
@jizai1125 我看element plus它在没有数据的时候，底部的滑动条也是现实的。这样的话，用户可以鼠标放上去进行拖动。

**Comment by jizai1125** [comment]
> @jizai1125 我看element plus它在没有数据的时候，底部的滑动条也是现实的。这样的话，用户可以鼠标放上去进行拖动。

我发现设置 `max-height` 后就没滚动条了，不设表头有滚动条
https://codesandbox.io/s/loving-benz-4xlxyy?file=/src/Demo.vue

**Comment by houxg** [comment]
> > @jizai1125 我看element plus它在没有数据的时候，底部的滑动条也是现实的。这样的话，用户可以鼠标放上去进行拖动。
> 
> 我发现设置 `max-height` 后就没滚动条了，不设表头有滚动条 https://codesandbox.io/s/loving-benz-4xlxyy?file=/src/Demo.vue

是否和[#5044 ](https://github.com/tusen-ai/naive-ui/issues/5044)类似？设置flex-height之后，必须设置scroll-x才有滚动条，但column宽度可调的情况下，scroll-x如何计算呢？按各列最大值求和会有很大一段空白

**Comment by CLD5186** [comment]
@houxg 是的，也是因为设置了flex-height之后才这样。话说表格的为什么需要设置总宽度，不解。不能和element plus一样么。

**Comment by xby020** [comment]
- 如果设置了scroll-x，在有数据时能显示底部横向滚动条；
- 如果设置了scroll-x，在没有数据时，底部没有滚动条，表头有滚动条；
- 如果没有数据，同时设置了flex-height和scroll-x，所有滚动条都消失了；

希望有选项让底部的滚动条一直显示，无论是否有数据，新加的scrollProps在这种情况下不起作用。

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by fengylm** [comment]
目前看起来 在没有数据的时候只能把鼠标放在表头上,然后通过按住shift和鼠标滚轮进行滚动,不是特别直观

**Comment by 1youziLi** [comment]
我也碰到了，很奇怪，就是设置最大高度，在没有数据的时候，表头没有滚动条，鼠标不能左右滚动，只能笔记本上的触屏可以

**Comment by fy0** [comment]
> 我似乎已经解决了，简单测试了一下都没问题，核心思想是封装一个可滚动的 NEmpty 组件插入到 empty 插槽中，监听滚动事件，同时滚动表头。以下方案仅基于我的需求，大家可以自行测试一下。由于公司会扫描代码泄漏，我只能抽象着写：
> 
> 1. NDataTable 上的属性和插槽
> 
> <template>
>   <NDataTable
>     ...
>     ref="xxx"
>     scroll-x="min-content"
>     flex-height
>     ...
>   >
>     <template #empty>
>       <可滚动空组件（防扫描） :table-ref="xxx" />
>     </template>
>   </NDataTable>
> </template>
> 
> <script setup>
>   const xxx = useTemplateRef("xxx");
> </script>
> 2. 封装可滚动空组件
> 
> <template>
>   <NScrollbar 拉下去看style x-scrollable @scroll="onScroll">
>     
>     <NEmpty class="这里是flex布局横向居中" :style="{ width }" />
>   </NScrollbar>
> </template>
> 
> <script setup>
>   // 1. 自己补充一下 props 的 tableRef
> 
>   const width = ref(默认100%);
>   let 表头元素;
>   let 停止监听;
> 
>   // 2. 在 mounted 的 nextTick 中写以下代码，这一步是因为表头有一些列的宽度是可变的，需要获取最新的列宽度，空组件的的宽度必须和列宽一样
>   表头元素 = 用 tableRef 查找 (".前缀自己补充-base-table-header .前缀自己补充-table");
>   width.value = `${表头元素?.宽度 || 0}px`;
>   useResizeObserver(表头元素, (entries) => {
>     // 从 entries 的 contentRect 的拿到宽度给 width 赋值
>   });
> 
>   // 3. Unmounted 取消监听 ResizeObserver
> 
>   function onScroll(e) {
>     // 4. e.target 的 scrollLeft 赋值给表头元素父元素的 scrollLeft，注意判空
>   }
> </script>
> 
> <style scoped>
> /* 这里我是用 UnoCSS 写的，为了防止被扫到在回答中改为 style */
> :deep(.ca-scrollbar-content) {
>   width: 100% !important;
>   min-width: min-content !important;
> }
> </style>
> 3. 然后就可以了，滚动 empty 时，表头也会同步滚动，没有什么延迟，很流畅

目前最佳方案，表头滚动很反直觉
