### ISSUE TITLE
n-space下有多个按钮并排，元素使用了 display: none，还会占空间12px

### ISSUE THREAD

**Issue by zhuchaoling** [tusen-ai/naive-ui#5057]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
lastest

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
http://www.github.com?none

### Reappearance steps (重现步骤)
n-space下面的每个元素都会包裹一个div，并且有右边距12px，元素使用display:none,后，右边距依然存在

### Expected results (期望的结果)
期望：元素只要隐藏，右边距也消失

### Actual results (实际的结果)
n-space下面的每个元素都会包裹一个div，并且有右边距12px，元素使用display:none,后，右边距依然存在

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
