### ISSUE TITLE
`n-data-table` slot for row or component for column

### ISSUE THREAD

**Issue by Satont** [tusen-ai/naive-ui#5065]
### This function solves the problem (这个功能解决的问题)
Hi, i feel a bit frustrating with working on datatable.

My issue is i often need custom render for columns, and doing layout via `h` function is a bit pain.
### Expected API (期望的 API)
I see two ways there:
1. We can create new component called `n-data-table-column` for usage in vue `<template>`. In that case it should take column name from property for example called `column="name"`. 
If we not create `n-data-table-column` for other columns, they use default render from `:columns` property of `n-data-table`

2. Also this issue can be done via fully custom row customization, so we have component `n-data-table-row`, but in that case we should write all columns render here, which is might be overhead.

**Comment by fudiwei** [comment]
It seems that the official team is not planning to do this work. 😭 

I created a project [@skit/x.naive-ui](https://github.com/fudiwei/x.naive-ui) based on Naive-UI, enables to use `DataTable` in template style. Welcome to improve it.

**Comment by jahnli** [comment]
duplicate https://github.com/tusen-ai/naive-ui/issues/4273

**Comment by Satont** [comment]
@fudiwei thank! Appreciate translate to english.

**Comment by Satont** [comment]
@jahnli didn't know abotu that issues, since i'm not chinese speaker. Thanks.

**Comment by jahnli** [comment]
There is a community that has created a Naive UI based project @skit/x.naive-uiDataTable that can be used in template styles.
