### ISSUE TITLE
data-table 排序状态能不能不通过columns维护 而是使用单独的状态维护

### ISSUE THREAD

**Issue by Colory** [tusen-ai/naive-ui#5067]
### This function solves the problem (这个功能解决的问题)
较多的需要排序的场景下，columns 维护会显得复杂，在维护过程中不适合做use-xxx的提取。
例如需要后台排序的场景，通常的代码维护是将 请求利用composition api 的方式提取。
最后返回数据。

在当前的sorter 维护模式下，需要将每个需要排序的列提取维护 sorter 状态，代码较为臃肿，如果能将sorter 采用单独的状态维护。对于提取 composition api 也更方便

```xml
<template>
  <n-data-table :columns="columns" :data="data" />
</template>
```
```js
// 当前

// setup 中

const { data, sorterOf } = useRequest(/* 接口 */xxx);

const columns = computed(() => [{ key: 1, name: 1, ...sorterOf(1) }, { key: 2, name: 2, sorterOf(2) }])
```

```js

// setup 中

const { data, /* 期望直接通过sorter 绑定受控 */ sorter, onSorterChange } = useRequest(/* 接口 */xxx);

const columns = [{ key: 1, name: 1 }, { key: 2, name: 2 }]
```

### Expected API (期望的 API)
:sorter 对应 on-update:sorter

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
