### ISSUE TITLE
Date Picker

### ISSUE THREAD

**Issue by gaoyuqing18** [tusen-ai/naive-ui#5071]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
chrome版本 114.0.5735.133（正式版本） (x86_64)

### System and its version (系统及其版本)
11.6.5

### Reappearance link (重现链接)
https://codesandbox.io/s/naughty-snowflake-sr3r5z?file=/src/Demo.vue:97-122

### Reappearance steps (重现步骤)
Date Picker组件加上format="yyyy-MM-dd HH:mm" 但是弹出的时间选择面板中格式为默认的'yyyy-MM-dd HH:mm:ss'，且此时若默认值传:default-time="['00:00', '23:59']"报错

### Expected results (期望的结果)
期望面板内格式与传入的format格式一直

### Actual results (实际的结果)
面板内一直使用默认格式'yyyy-MM-dd HH:mm:ss'

**Comment by thibodeauxjl** [comment]
```
<n-date-picker
    v-model:value="range"
    type="datetimerange"
    clearable
    default-time="yyyy-MM-dd HH:mm"
    format="yyyy-MM-dd"
    :time-picker-props="{ format: 'HH:mm' }"
  />
```

**Comment by gaoyuqing18** [comment]
Thank you, man, it does work

**Comment by gaoyuqing18** [comment]
Thank you, man, it does work
<n-date-picker
    v-model:value="range"
    type="datetimerange"
    clearable
    format="yyyy-MM-dd"
    :time-picker-props="{ format: 'HH:mm' }"
    :default-time="['00:00:00', '23:59:00']"
  />

**Comment by gaoyuqing18** [comment]
Thank you, man, it does work
`<n-date-picker
    v-model:value="range"
    type="datetimerange"
    clearable
    format="yyyy-MM-dd"
    :time-picker-props="{ format: 'HH:mm' }"
    :default-time="['00:00:00', '23:59:00']"
  />`
