### ISSUE TITLE
n-cascader新增超出tooltips提示

### ISSUE THREAD

**Issue by pitilesszgw** [tusen-ai/naive-ui#5081]
### This function solves the problem (这个功能解决的问题)
文本长度超出时省略号，移入时tooltips显示
### Expected API (期望的 API)
n-cascader

**Comment by amadeus711** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/46394163/50170969-841c-4a2e-ae3a-d22ef3ac26df)
