### ISSUE TITLE
希望能给树形选择组件添加对于文件树使用场景的支持

### ISSUE THREAD

**Issue by SuperManito** [tusen-ai/naive-ui#5082]
### This function solves the problem (这个功能解决的问题)
文件树的使用场景是点击目录（文件夹）是展开/收起操作而点击文件才是业务场景，目前TreeSelect组件要想实现这样的效果只能是禁用目录节点然后点击展开开关来实现操作，TreeSelect在默认情况下点击节点后会关闭下拉菜单，展开图标又非常的小，这在目录（文件夹）很多的情况下非常不便利，并且TreeSelect组件也没有像Tree组件在使用block-node、block-line API时那样点击节点就能展开/收起的效果。
### Expected API (期望的 API)
我希望能够添加一个API实现点击带有children的节点时不会收起下拉菜单这样的效果，或者加一个将下拉菜单的展开/收起改为受控的API

**Comment by amadeus711** [comment]
https://www.naiveui.com/zh-CN/os-theme/components/tree#node-props.vue
参考这个 demo , 节点的事件可以通过给 node 加一个带 `e.preventDefault()` 的事件所拦截

**Comment by SuperManito** [comment]
> > https://www.naiveui.com/zh-CN/os-theme/components/tree#node-props.vue 参考这个 demo , 节点的事件可以通过给 node 加一个带 `e.preventDefault()` 的事件所拦截
> 
> 经过测试，在TreeSelect组件的node-props中使用onClick方法时，使用 `preventDefault()` 并不能阻止TreeSelect组件的展开菜单收起，您确定这是有效的吗？
> 
> 我需要的业务场景是在点击含有children的node节点时不会收起树形选择组件的展开菜单，而替代成树节点的展开或收起操作，与 https://tdesign.tencent.com/vue-next/components/tree-select?tab=demo#%E5%8F%AF%E8%BF%87%E6%BB%A4%E7%9A%84%E6%A0%91%E9%80%89%E6%8B%A9 的第二个框的效果一致，就是点击节点变成了展开/收起操作而不会关闭展开菜单，不过不需要勾选。也可以加个类似 https://arco.design/vue/component/tree-select#popup-visible 这种的受控API。

此外，还希望能够适配上展开动画和树节点的尺寸，目前size只改变了Select框的尺寸并没有改变树节点的尺寸，在 Arco Design 中它是联动的 https://arco.design/vue/component/tree-select#size，另外树组件也没有调整尺寸的API

**Comment by SuperManito** [comment]
> > https://www.naiveui.com/zh-CN/os-theme/components/tree#node-props.vue 参考这个 demo , 节点的事件可以通过给 node 加一个带 `e.preventDefault()` 的事件所拦截
> 
> 经过测试，在TreeSelect组件的node-props中使用onClick方法时，使用 `preventDefault()` 并不能阻止TreeSelect组件的展开菜单收起，您确定这是有效的吗？
> 
> 我需要的业务场景是在点击含有children的node节点时不会收起树形选择组件的展开菜单，而替代成树节点的展开或收起操作，与 https://tdesign.tencent.com/vue-next/components/tree-select?tab=demo#%E5%8F%AF%E6%8A%98%E5%8F%A0%E9%80%89%E9%A1%B9 的第二个框的效果一致，就是点击节点变成了展开/收起操作而不会关闭展开菜单，不过不需要勾选。
> 
> 也可以加个类似 https://arco.design/vue/component/tree-select#popup-visible 这种的受控API。

此外，还希望能够适配上展开动画和树节点的尺寸，目前size只改变了Select框的尺寸并没有改变树节点的尺寸，在 Arco Design 中它是联动的 https://arco.design/vue/component/tree-select#size ，另外树组件也没有调整尺寸的API

**Comment by SuperManito** [comment]
> > https://www.naiveui.com/zh-CN/os-theme/components/tree#node-props.vue 参考这个 demo , 节点的事件可以通过给 node 加一个带 `e.preventDefault()` 的事件所拦截
> 
> 经过测试，在TreeSelect组件的node-props中使用onClick方法时，使用 `preventDefault()` 并不能阻止TreeSelect组件的展开菜单收起，您确定这是有效的吗？
> 
> 我需要的业务场景是在点击含有children的node节点时不会收起树形选择组件的展开菜单，而替代成树节点的展开或收起操作，与 [https://tdesign.tencent.com/vue-next/components/tree-select?tab=demo#可折叠选项](https://tdesign.tencent.com/vue-next/components/tree-select?tab=demo#%E5%8F%AF%E6%8A%98%E5%8F%A0%E9%80%89%E9%A1%B9) 的第二个框的效果一致，就是点击节点变成了展开/收起操作而不会关闭展开菜单，不过不需要勾选。
> 
> 也可以加个类似 https://arco.design/vue/component/tree-select#popup-visible 这种的受控API。

@amadeus711 @07akioni

**Comment by SuperManito** [comment]
@07akioni 哥
