### ISSUE TITLE
NScrollbar rendered div element lose scoped css attr data-v-*，渲染出来的 div 丢失 vue 局部样式标记属性。

### ISSUE THREAD

**Issue by liuzw2579** [tusen-ai/naive-ui#5084]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Chrome (114.0.5735.201)

### System and its version (系统及其版本)
Windows 11

### Reappearance link (重现链接)
https://codesandbox.io/p/sandbox/gracious-elgamal-p9l754?file=%2Fsrc%2FApp.vue%3A9%2C33

### Reappearance steps (重现步骤)
在 VUE SFC 使用 `NScrollbar`，并加上 class，`<NScrollbar class="my-scrollbar">`
SFC 包含 `<style scoped>`

### Expected results (期望的结果)
NScrollbar 渲染出来的 `div.n-scrollbar.my-scrollbar` 元素 正确 包含 scoped css attr: `data-v-* `

### Actual results (实际的结果)
未包含。 NScrollbar 组件 实例的 $el 为 Text Node, 下一个元素 `nextSibling`  才是 渲染的  `div.n-scrollbar.my-scrollbar`

此问题 类似于 issue  #1788 

### Remarks (补充说明)
![image](https://github.com/tusen-ai/naive-ui/assets/30503937/ec771c0a-3e88-446a-96fd-d19592d7e96a)

**Comment by liuzw2579** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/30503937/b28e5324-f009-460e-a5c0-42432d0206b4)
https://github.com/tusen-ai/naive-ui/blob/437ce2322d24d66efb3d640befd2186da77421e4/src/_internal/scrollbar/src/Scrollbar.tsx#L847

本地测试是 这里的 `VResizeObserver` 包裹后出现的问题

**Comment by liuzw2579** [comment]
`ResizeObserver` 这个，感觉在这里 使用 hook 的方式好一些吧。
```typescript
function useReizeObserver(target: MaybeRef<HTMElement | null>, handler: (p: Param) => void) {
     watch(target, t => {
          subscrible(t, handler)
    })

    beforeUnmount(() => {
        unsubscrible(unref(target))
    })
}

// 在 setup 里
useResizeObserver(wrapperRef, handleContainerResize)
```

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by byronogis** [comment]
现在这依旧是一个存在的问题，v2.38.2
