### ISSUE TITLE
Nuxt 3 Official Naive UI module 

### ISSUE THREAD

**Issue by orenmizr** [tusen-ai/naive-ui#5089]
### This function solves the problem (这个功能解决的问题)
nuxt is the most popular vue 3 framework right now. having a naive ui module with simplify integration with one line of config and will expose naive ui to more eyes.
### Expected API (期望的 API)
the config can expose auto imports for naive ui components, setup the framework within the project.
for example - https://nuxt.com/modules/vuestic

**Comment by orenmizr** [comment]
i've been using it as well. i just wish this was a PR on the main project. but the maintainer is active and did solve some issues quickly and efficiently.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by 07akioni** [comment]
Here's the official module https://www.naiveui.com/en-US/os-theme/docs/nuxtjs
