### ISSUE TITLE
类型应该是MaybeRef

### ISSUE THREAD

**Issue by palmerye** [tusen-ai/naive-ui#5093]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Chrome 114.0.5735.198

### System and its version (系统及其版本)
macOS 13.2.1

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/dialog#useDialog-API

### Reappearance steps (重现步骤)
```
import { defineComponent, ref } from 'vue'
import { useMessage, useDialog } from 'husky-ui'

export default defineComponent({
  setup() {
    const message = useMessage()
    const dialog = useDialog()
    const loadingLoac = ref(true)
    return {
      loadingLoac,
      handleCreate() {
        dialog.create({
          title: '确定删除xxx吗？（把title故意写得很长为了看看两行的效果）',
          content: '这是一串小内容。。。',
          positiveText: '确定',
          negativeText: '关闭',
          loading: loadingLoac,
          onPositiveClick: () => {
            message.success('确定')
          },
          onNegativeClick: () => {
            message.error('不确定')
            loadingLoac.value = !loadingLoac.value
            return false
          }
        })
      },
    }
  }
})
```

### Expected results (期望的结果)
loading 类型提示正确

### Actual results (实际的结果)
不能将类型“Ref<boolean>”分配给类型“boolean | undefined”。ts(2322)
![image](https://github.com/tusen-ai/naive-ui/assets/16277812/47bcb23b-5f74-4f34-bfb0-0ff91a7247d4)

**Comment by palmerye** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/16277812/b9660a2c-d62e-4505-89a9-2e99589ffdd8)

**Comment by jizai1125** [comment]
传给 `loading` 属性不能是 ref

**Comment by palmerye** [comment]
> 传给 `loading` 属性不能是 ref

那样就无法响应式了。

场景：dialog 弹出时loading为true，button呈现loading；此时调用异步逻辑，有回调后要使loading关闭。用ref是能实现场景的需求，但ts报type类型错误。

**Comment by jizai1125** [comment]
> > 传给 `loading` 属性不能是 ref
> 
> 那样就无法响应式了。
> 
> 场景：dialog 弹出时loading为true，button呈现loading；此时调用异步逻辑，有回调后要使loading关闭。用ref是能实现场景的需求，但ts报type类型错误。

create 方法会返回一个 reactive 包裹的 options，你可以直接改，例如：
```ts
const dialog = useDialog()
const d = dialog.create({})
d.loading = true
```
