### ISSUE TITLE
input, select and other clearances can only be null

### ISSUE THREAD

**Issue by dchom** [tusen-ai/naive-ui#5094]
### This function solves the problem (这个功能解决的问题)
null cannot be reassigned by deconstruction, and is very unfriendly when I need to default to empty as a string or undefined
### Expected API (期望的 API)
The default clearing is undefined, which can be adjusted via emit or prop

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
