### ISSUE TITLE
Tabs' bar not hidden on manual update

### ISSUE THREAD

**Issue by vaibhav11s** [tusen-ai/naive-ui#5100]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
All

### System and its version (系统及其版本)
All

### Reappearance link (重现链接)
https://codesandbox.io/s/busy-hooks-j7fxl2

### Reappearance steps (重现步骤)
click on any tabs from the options. if we click on the tab from the second group, the previous tab get inactive, but the tab-bar stays in place.

### Expected results (期望的结果)
The inactivated tab's tab-bar should be hidden

### Actual results (实际的结果)
inactivated tab's tab-bar stays visible

### Remarks (补充说明)
I was trying to make the nested routes layout with tabs. when we selected the different route group item, previous group tab-bar was still visible.

**Comment by vaibhav11s** [comment]
Raised PR #5098 to solve this issue.

**Comment by 07akioni** [comment]
fix in next version
