### ISSUE TITLE
Change autocomplete style not working - works OK for other components

### ISSUE THREAD

**Issue by damianfranco-miami** [tusen-ai/naive-ui#5103]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Chrome 114.05735.248

### System and its version (系统及其版本)
Windows 10

### Reappearance link (重现链接)
https://codesandbox.io/s/red-paper-2sk9ww?file=/src/Demo.vue

### Reappearance steps (重现步骤)
Hello, 
I am not able to change the style for autocomplete. 
Works OK for others.

   <n-input v-model:value="value" :theme-overrides="themeOverrides" />

  <n-auto-complete
    v-model:value="value"
    :input-props="{
      autocomplete: 'disabled',
    }"
    :options="options"
    placeholder="Email"
    :theme-overrides="themeOverrides"
  />
</template>

themeOverrides: {
        colorFocus: 'rgba(255, 255, 255, 1)',
        borderHover: '1px solid #b4905d',
        border: '1px solid #b4905d',
        borderFocus: '1px solid #b4905d',
        boxShadowFocus: '0 0 0 2px #b4905d'
      }

### Expected results (期望的结果)
Style to change for autocomplete

### Actual results (实际的结果)
No change to autocomplete

### Remarks (补充说明)
I am able to change the style of other components like Switch Input etc

**Comment by ALiangTech** [comment]
for autocomplete component.
your code like this:
` themeOverrides: {
        peers: {
          Input: {
            colorFocus: "rgba(255, 255, 255, 1)",
            borderHover: "1px solid #b4905d",
            border: "1px solid #b4905d",
            borderFocus: "1px solid #b4905d",
            boxShadowFocus: "0 0 0 2px #b4905d",
          },
        },
      },`

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
