### ISSUE TITLE
render设置NSelect的placeholder不生效

### ISSUE THREAD

**Issue by pitilesszgw** [tusen-ai/naive-ui#5104]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
115.0.5790.102

### System and its version (系统及其版本)
13.4.1 (22F82)

### Reappearance link (重现链接)
https://codesandbox.io/s/nselesct-h-placeholder-cvt5mm?file=/src/Demo.vue

### Reappearance steps (重现步骤)
render函数下设置NSelect的placeholder，无法显示

### Expected results (期望的结果)
placeholder正常显示

### Actual results (实际的结果)
placeholder未提示

**Comment by amadeus711** [comment]
https://codesandbox.io/s/nselesct-h-placeholder-forked-2jgmxd?file=/src/Demo.vue
`n-select` 的 `value` 设置的问题

**Comment by ALiangTech** [comment]
感觉确实有点问题 ，应急处理的话 可以将你的address 设置成null 就可以了

**Comment by pitilesszgw** [comment]
> https://codesandbox.io/s/nselesct-h-placeholder-forked-2jgmxd?file=/src/Demo.vue `n-select` 的 `value` 设置的问题

感谢，暂时先这样处理
