### ISSUE TITLE
Request for document update: Please use the setup syntax sugar

### ISSUE THREAD

**Issue by s3xysteak** [tusen-ai/naive-ui#5105]
### This function solves the problem (这个功能解决的问题)
Make the document more closely aligned with the usage environment, as almost no one is not using the setup syntax anymore.
### Expected API (期望的 API)
```
<script setup>
import { ref } from 'vue'

const someVariable = ref('example')
...
```

**Comment by jahnli** [comment]
duplicate  https://github.com/tusen-ai/naive-ui/issues/5105
