### ISSUE TITLE
popover 绑定多个事件失焦报错

### ISSUE THREAD

**Issue by aegorx** [tusen-ai/naive-ui#5107]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
 115.0.5790.98

### System and its version (系统及其版本)
MacOS 13.2.1 (22D68)

### Node version (Node 版本)
16

### Reappearance link (重现链接)
https://codesandbox.io/s/intelligent-satoshi-zdxlvd

### Reappearance steps (重现步骤)
失去焦点F12控制台报错

### Expected results (期望的结果)
根据绑定事件情况判断，单个事件执行函数，多个事件执行数组函数

https://github.com/tusen-ai/naive-ui/blob/main/src/popover/src/Popover.tsx#L83
在此行判断一下

### Actual results (实际的结果)
控制台报错

**Comment by amadeus711** [comment]
经团队内部讨论，一致认为此情况应由用户自行合并事件，组件内部不予处理

**Comment by aegorx** [comment]
@amadeus711 

有些场景很难自行合并，在二次封装组件的时候会出现2个同名事件，不同业务逻辑，v-bind是外部透传的，onBlur是内部劫持的。不是所有逻辑都是内部的，如果要用户自行合并，还需要判断attr或者prop中是否存在blur业务，然后再合并到一个函数中。vue3 [mergeProps](https://cn.vuejs.org/api/render-function.html#mergeprops) 会把多个事件合并为数组，这是正常行为。

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
