### ISSUE TITLE
`v-model:value` of `<NInput>` is not reactive as `v-model` of `<input>`

### ISSUE THREAD

**Issue by heroboy** [tusen-ai/naive-ui#5111]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
firefox

### System and its version (系统及其版本)
window 10

### Reappearance link (重现链接)
https://codesandbox.io/p/sandbox/cocky-platform-96m24p?file=%2Fsrc%2Fcomponents%2FHelloWorld.vue%3A12%2C3

### Reappearance steps (重现步骤)
```tsx
<setup>
const lang = ref('aa');
const obj = reacitve({})
</setup>
```
```tsx
<template>
<NInput v-model:value="obj['x_'  + lang]"/>
<input v-model="obj['x_' +  lang]"/>
</template>
```
简单来说就是`<Ninput>`的`v-model:value`不是reactive的。当`v-model:value`发生变化时，没能立刻更新文本框中的内容。
看上述的代码，我不是很清楚这样的用法是否是正确的，但是`<input>`表现出的行为是符合我的预期的，但是`<NInput>`不正常，所以我认为这是一个bug。

1. 在上述minimal reproduction中，有3个控件lang, input, ninput
2. 首先在lang='zh'的时候，在input或ninput中输入一个文本内容。
3. 设置lang为其他内容，例如'en'

### Expected results (期望的结果)
4. 经过上述步骤，input内容变为空。因为obj['value_en']是不存在的

### Actual results (实际的结果)
5. 经过上述步骤，ninput内容没有发生变化，还是保持着obj['value_zh']的内容

**Comment by heroboy** [comment]
又测试了一下。补充一下，如果一开始
```tsx
obj = {
   value_en : 'xxxx'
}
```
则切换到`lang='en'`的时候，`<NInput>`的文本框内容会跟着变。
也就是如果切换到的`obj['xx'] === undefined`，<NInput>内的内容会维持之前的内容。
所以，可能不是我标题所说的reactive的原因。

**Comment by jizai1125** [comment]
传值为`undefined`是非受控的，所以即使你切换了 obj 的不同属性也不会影响 NInput 的变化，可以看下文档 [受控模式与非受控模式](https://www.naiveui.com/zh-CN/os-theme/docs/controlled-uncontrolled)

**Comment by heroboy** [comment]
我说的我都知道。只是觉得这样的行为和`<input>`不一致，才提了这个issue。

**Comment by jizai1125** [comment]
> 我说的我都知道。只是觉得这样的行为和`<input>`不一致，才提了这个issue。

这样的行为就是预期的

**Comment by Chheung** [comment]
another trick is to force rerender of component.
seems like Naive doesnt wanna handle undefined value. But it shows a bit of a glitchy UI.

```
  <NInput v-if="refresher" v-model:value="str"></NInput>
  <input v-model="str" />
  <NButton @click="press">DO it</NButton>
```

```
const str = ref<string | undefined>(undefined);
const refresher = ref(true);
async function press() {
  refresher.value = false;
  str.value = undefined;
  await sleep(50);
  refresher.value = true;
}
```

**Comment by heroboy** [comment]
I think the workaround is to convert undefined to null.
Losing the convenience of v-model.
```jsx
<NInput :value="str===undefined?null:str" @update:value="v=>str=v" />
```

**Comment by Chheung** [comment]
i deleted my comment as it's very misleading. Yes using NULL solves the issue 🚀
