### ISSUE TITLE
Cascader

### ISSUE THREAD

**Issue by zeng4869** [tusen-ai/naive-ui#5112]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
115.0.5790.110

### System and its version (系统及其版本)
window11

### Reappearance link (重现链接)
https://codesandbox.io/s/ur6z10

### Reappearance steps (重现步骤)
获取选中项，在获取getCheckedData key options都没有数据

### Expected results (期望的结果)
获取选中项所有key 与 options

### Actual results (实际的结果)
选中项所有key 与 options为空

**Comment by jizai1125** [comment]
`getCheckedData()` 是用于获取多选时的数据

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
