### ISSUE TITLE
An API to disable autofill background color for n-input components

### ISSUE THREAD

**Issue by TrickEye** [tusen-ai/naive-ui#5123]
### This function solves the problem (这个功能解决的问题)

This feature request is mainly targeted to the behavior after the _**autofill**_ feature of the browser is activated.

When a n-input component is autofilled, browsers will add a special background color to the input box through User Agent CSS. 

Problem is that the added background color does not suit some of the n-input component very well, for example when the input box has a prefix or suffix icon, or when the input box is in dark mode. They look a little bit weird.

Something like this: I believe the autofilled white background color should expand to the whole input box, but here the background of the suffix icon is still dark.
![image](https://github.com/tusen-ai/naive-ui/assets/85970705/f29f228b-5c30-47a1-bf30-ee3060c5c559)

I am looking forward to an API that enables me to modify the autofill background color, or just simply disable it.

Also if naive-ui would like to work on this problem and make the autofill background expand to cover the whole input box, that would be nice too!

### Expected API (期望的 API)

```
<n-input placeholder="pswd" autofillbg="disabled">
```

**Comment by 07akioni** [comment]
I've tried various solution, nothing fits all browser. So we won't provide builtin solution to disable autofill background color.

If you need to disable it for modern chrome, you may use:

```
.n-input input {
  -webkit-background-clip: text;
  -webkit-text-fill-color: var(--n-text-color);
}
```
