### ISSUE TITLE
The ButtonGroup component has no API to bind the model, nor does it have an associated change event

### ISSUE THREAD

**Issue by llifangyin** [tusen-ai/naive-ui#5128]
### This function solves the problem (这个功能解决的问题)
The ButtonGroup component has no API to bind the model, nor does it have an associated change event
### Expected API (期望的 API)
 v-model=''
@update:value="onChange"

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
