### ISSUE TITLE
Sapce 组件渲染顺序错乱问题

### ISSUE THREAD

**Issue by aegorx** [tusen-ai/naive-ui#5136]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
版本 115.0.5790.98（正式版本） (arm64)

### System and its version (系统及其版本)
13.2.1 (22D68)

### Node version (Node 版本)
18

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/space

### Reappearance steps (重现步骤)
vite打包后，切换 show 状态，点击保存按钮触发取消click。

```html
  <NSpace justify="center">
    <NButton
      v-if="show"
      type="primary"
      @click="xxx"
    >
      xxx
    </NButton>
    <NButton
      :type="show ? 'default' : 'primary'"
      @click="save"
    >
      保存
    </NButton>
    <NButton @click="cencel">
      取消
    </NButton>
  </NSpace>
```

### Expected results (期望的结果)
方案一：
https://github.com/tusen-ai/naive-ui/blob/c41c8be3432ef3e227e62f023fdc523b0bedd506/src/space/src/Space.tsx#L205
此处使用h函数包裹

方案二：
vite打包开放esbuild ignoreAnnotations参数（目前vite写死的逻辑）
https://github.com/vitejs/vite/blob/9d7d45e56f98787cd6c7f4245ad5f9562d409997/packages/vite/src/node/optimizer/index.ts#L809

### Actual results (实际的结果)
Sapce 组件下fragment元素如果存在，v-if条件判断，且未设置key的前提下，dev模式正常，开发模式由于vite打包删除vue注释，元素复用，会导致点击保存触发取消click事件，造成渲染混乱

**Comment by jizai1125** [comment]
发现是因为 space 组件中的 flatten 函数过滤掉了注释节点导致的

**Comment by equt** [comment]
#824 里面需要过滤掉 comment 节点避免出现多余的间距

**Comment by jizai1125** [comment]
> #824 里面需要过滤掉 comment 节点避免出现多余的间距

重新提了个 PR，Comment 节点就直接渲染，不再包裹一层 div，这样就不会出现多余间距
