### ISSUE TITLE
希望能给LayoutSider布局侧边栏组件加一个resize API用于自由拉伸侧边栏的宽度（类似于切割面板）

### ISSUE THREAD

**Issue by SuperManito** [tusen-ai/naive-ui#5139]
### This function solves the problem (这个功能解决的问题)
类似于 n-data-table-resize-button 的效果，能够实现自由调整展示宽度
### Expected API (期望的 API)
resizeable<boolean>: false(default)

**Comment by jahnli** [comment]
Or you can do it via n-split
