### ISSUE TITLE
Add a `strong` or `label-strong` prop for form-items or forms 

### ISSUE THREAD

**Issue by megasanjay** [tusen-ai/naive-ui#5144]
### This function solves the problem (这个功能解决的问题)
This will allow for label titles to have a bold style as an option. This will also allow for more variety when generating forms within our UIs. This would be similar to the `strong` prop in buttons
### Expected API (期望的 API)
Something like this I assume? 
```html
<n-form-item label="This is a FormItem" strong label-strong>
    <n-input v-model:value="value" />
  </n-form-item>
```

**Comment by jizai1125** [comment]
Can configure `labelFontWeight` through [customizing theme](https://www.naiveui.com/en-US/os-theme/docs/customize-theme).

**Comment by megasanjay** [comment]
Wouldn't that be a global change? I would like to change it on a case by case basis. For example I would want my modal forms to use the default font weight.

**Comment by jizai1125** [comment]
> Wouldn't that be a global change? I would like to change it on a case by case basis. For example I would want my modal forms to use the default font weight.

Normally, you can customize the theme using the `theme-overrides` prop of the component. However, the Form component currently doesn't support this. You can use `n-config-provider` to wrap the Form component instead.

**Comment by megasanjay** [comment]
I see. That's one way of approaching it. It does lead to a lot more boilerplate than a standard prop. I can use this example approach within my app. 

> However, the Form component currently doesn't support this 

I would like this to be a prop in the `form-item`  element, not the `form` element. I figured since there is a label rendered, it would be easy to add the specific class for that but you can let me know if that can be added into a plan in the future.

**Comment by jizai1125** [comment]
> However, the Form component currently doesn't support this
Although the Form component has the `theme-overrides` prop, it doesn't seem to work; maybe it's a bug. Similarly, the `form-item` component also has the `theme-overrides` prop, which works, but its usage requires applying it to each `form-item` component individually. Therefore, using `n-config-provider` is more convenient.

**Comment by megasanjay** [comment]
I can take a look at this one perhaps. Should be easy to make a parent component that I use for all bold forms. Thank you for the help. Cheers :)
