### ISSUE TITLE
data-table 希望可以加入行点击时间 和 行双击事件

### ISSUE THREAD

**Issue by pigIsDuck** [tusen-ai/naive-ui#5145]
### This function solves the problem (这个功能解决的问题)
点击行后，希望可以触发对应的事件，类似 element的  @row-click="handleTableSelectChange"
            @row-dblclick="handleTableDbClick"
我有时需要点击改行，从而触发事件
### Expected API (期望的 API)
 单击行：@row-click="handleTableSelectChange"
 双击行：@row-dblclick="handleTableDbClick"

**Comment by pengzhen-developer** [comment]
善用官方文档，组件本身已支持。

https://www.naiveui.com/zh-CN/os-theme/components/data-table#row-props.vue

<img width="575" alt="image" src="https://github.com/tusen-ai/naive-ui/assets/12759499/b58669fa-f17f-4fe8-a182-c7fa5aacc7bc">

**Comment by pigIsDuck** [comment]
> 善用官方文档，组件本身已支持。
> 
> https://www.naiveui.com/zh-CN/os-theme/components/data-table#row-props.vue
> 
> <img alt="image" width="575" src="https://user-images.githubusercontent.com/12759499/259359958-b58669fa-f17f-4fe8-a182-c7fa5aacc7bc.png">

不好意思，没搜到这个api，在官网文档找半天没搜到
