### ISSUE TITLE
穿梭框组件缺少selectAllText等属性，跟git上的文档对不上

### ISSUE THREAD

**Issue by chuxinone** [tusen-ai/naive-ui#5153]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
1

### System and its version (系统及其版本)
1

### Node version (Node 版本)
1

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/transfer

### Reappearance steps (重现步骤)
git文档地址https://github.com/tusen-ai/naive-ui/blob/main/src/transfer/demos/zhCN/index.demo-entry.md，

配置selectAllText等属性无效，实际查阅源码后发现没有留配置入口。

### Expected results (期望的结果)
selectAllText等属性正常生效

### Actual results (实际的结果)
未生效

**Comment by jizai1125** [comment]
下个版本还没发布

**Comment by chuxinone** [comment]
> 下个版本尚未发布



> 下个版本还没发布

不是2.34.4版本?那大概什么时候更新呢？目前这个很影响体验

**Comment by jizai1125** [comment]
> 不是2.34.4版本?那大概什么时候更新呢？目前这个很影响体验
啥时候发布得看作者了 🙃

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
