### ISSUE TITLE
how to get n-image's rotation after rotating in preview

### ISSUE THREAD

**Issue by l2m2** [tusen-ai/naive-ui#5154]
### This function solves the problem (这个功能解决的问题)
how to get n-image's rotation after rotating in preview.
i can't find any props or event about this.
PS: i'm not a frontend developer, i am building a frontend page with naive ui.
### Expected API (期望的 API)
whatever

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
