### ISSUE TITLE
when component Tree use 'get-children' prop, the component Tree can't expand

### ISSUE THREAD

**Issue by lnzhangsong** [tusen-ai/naive-ui#5159]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Edge 115.0.1901.203

### System and its version (系统及其版本)
Macos 13.5 (22G74)

### Node version (Node 版本)
16.20.1

### Reappearance link (重现链接)
https://codesandbox.io/s/nice-dream-jvj4ht?file=/src/Demo.vue

### Reappearance steps (重现步骤)
增加 get-children 属性后，树结构无法展开

### Expected results (期望的结果)
期望是在增加 ’get-children‘ 这个属性以后树也可以展开

### Actual results (实际的结果)
树无法展开

**Comment by lnzhangsong** [comment]
> `get-children` 返回一个子节点数组才有子节点可以展开呀

在文档中，这个属性只说明了 `获取当前选项的子选项` 除此之外好像并没有任何其他的说明。然后我的理解是**只是**用来获取当前节点的孩子节点。我觉得这块要么说明一下会修改原来的树结构，返回的节点值时修改后的节点（并且名字应该叫`filter-children`），要么就做成获取当前节点。只是通过文档和字面含义来说这个 `get-child` 应该就是获取当前节点的。

**Comment by jizai1125** [comment]
确实文档不够清晰
