### ISSUE TITLE
useForm schemas参数能支持动态类型吗？如ref([])，现在只能通过第一次传入的数组

### ISSUE THREAD

**Issue by tanwenchao** [tusen-ai/naive-ui#5169]
### This function solves the problem (这个功能解决的问题)
useForm schemas生成后根据业务会有变化
### Expected API (期望的 API)
const schemas: FormSchema[] = ref([
    {
      field: 'type',
      component: 'NSelect',
      label: '商品分类',
      componentProps: {
        placeholder: '请选择类型',
        options: [
          {
            label: '舒适性',
            value: 1,
          },
          {
            label: '经济性',
            value: 2,
          },
        ],
      },
      rules: [{ required: true, type: 'number', message: '请选择商品筛选', trigger: ['input'] }],
    },
])
...

**Comment by jahnli** [comment]
computed
