### ISSUE TITLE
radiogroup cannot update normally when an update is cancelled

### ISSUE THREAD

**Issue by chenglu4343** [tusen-ai/naive-ui#5184]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Chrome 116.0.5845.110

### System and its version (系统及其版本)
windows10

### Reappearance link (重现链接)
https://stackblitz.com/edit/vitejs-vite-kvbywm?file=src%2Fcomponents%2FHelloWorld.vue

### Reappearance steps (重现步骤)
Toggle radio and click OK to work

Switch radio, click cancel, then can not switch radiio normally

### Expected results (期望的结果)
update:value After the event is triggered, the system works properly even if the value is not updated

### Actual results (实际的结果)
update:value If the value is not changed synchronously after update:value, subsequent switchover cannot take effect

**Comment by zhangjiajia123** [comment]
I'm having this problem too. Has the problem been solved?

**Comment by zhangjiajia123** [comment]
What should I do?

**Comment by chenglu4343** [comment]
If you are in a hurry, you can choose to listen for the radio click event to change the value manually

**Comment by jahnli** [comment]
Looks like it's been repaired.
