### ISSUE TITLE
Check for breaking changes in Renovate's PRs

### ISSUE THREAD

**Issue by gerpetto** [tusen-ai/naive-ui#5185]
### This function solves the problem (这个功能解决的问题)
We noticed there were quite a number of Dependabot's PRs open. We ran Adaptly on a couple to help you catch breaking changes in these new versions. Our tool goes through the changelogs of the new versions and reports the breaking changes with a comment in the PR.

You can see the comments posted https://github.com/tusen-ai/naive-ui/pull/5177 and https://github.com/tusen-ai/naive-ui/pull/5171

It's completely free and plug-and-play since you are already using Dependabot.

We would love to hear your feedback! : )
### Expected API (期望的 API)
If you want to install the tool, you can find it here: https://github.com/marketplace/adaptly

**Comment by jahnli** [comment]
Consolidation is already underway
