### ISSUE TITLE
NSelect detect keyboard events

### ISSUE THREAD

**Issue by hyuckjin12** [tusen-ai/naive-ui#5187]
### This function solves the problem (这个功能解决的问题)
Can NSelect detect keyboard events?

When there is a tag in NSelect, I want to handle it so that the tag cannot be deleted with the backspace key event.
### Expected API (期望的 API)
https://www.naiveui.com/en-US/os-theme/components/select#tag.vue

**Comment by Sepush** [comment]
not support custom keyboard events

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
