### ISSUE TITLE
通过key触发，树结构可以展开对应的节点，并跟踪到树节点中物体的位置

### ISSUE THREAD

**Issue by aile1997** [tusen-ai/naive-ui#5193]
### This function solves the problem (这个功能解决的问题)
你好，我在做一个3D编辑器，我想在点击3D场景内的物体时，树结构可以展开对应的节点，并跟踪到树节点中物体的位置，应该怎么做？
我现在只能使用default-expand-all，展开全部节点，然后使用scrollTo跟踪到树节点中物体的位置
### Expected API (期望的 API)
byKeyOpenExpandedAndScroll

**Comment by xushanpei** [comment]
我在 "naive-ui": "2.34.4" 版本上使用 scrollTo 好像不会生效, 不知道是什么问题

**Comment by jahnli** [comment]
通过设置  `expanded-key`
