### ISSUE TITLE
cascader获取完整的路径

### ISSUE THREAD

**Issue by jieorjie** [tusen-ai/naive-ui#5195]
### This function solves the problem (这个功能解决的问题)
cascader获取完整的路径 比如 笔记本/dell
### Expected API (期望的 API)
cascader获取完整的路径 比如 笔记本/dell

**Comment by Sepush** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/39197136/fa11ac31-d4f7-4b90-8313-8447d8de8644)
