### ISSUE TITLE
模态框第一次展示，右上角关闭按钮带有focus背景色

### ISSUE THREAD

**Issue by jackercc** [tusen-ai/naive-ui#5196]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.2.47

### Browser and its version (浏览器及其版本)
Chrome 116.0.5845.110（正式版本） (arm64)

### System and its version (系统及其版本)
MacOS(13.4)

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/modal

### Reappearance steps (重现步骤)
点击：演示->遮罩关闭->来吧，弹框右上角关闭按钮自带focus背景色，此时应该还没focus

### Expected results (期望的结果)
关闭按钮不带focus背景色

### Actual results (实际的结果)
弹框出现，右上角关闭按钮自带focus背景色

### Remarks (补充说明)

![image](https://github.com/tusen-ai/naive-ui/assets/19639723/68128815-84a0-4d54-8204-bf1e1ff7e6a4)

**Comment by jizai1125** [comment]
`auto-focus: false`

**Comment by aiyingsitan010302** [comment]
![Snipaste_2023-09-01_10-08-52](https://github.com/tusen-ai/naive-ui/assets/121598086/5f135823-40ba-4717-9ee2-5e95c5b82001)

**Comment by jackercc** [comment]
没仔细看文档...感谢解答
