### ISSUE TITLE
dataTable中的defaultPageSize不生效 

### ISSUE THREAD

**Issue by Colory** [tusen-ai/naive-ui#5201]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
116

### System and its version (系统及其版本)
win11

### Node version (Node 版本)
18.15.0

### Reappearance link (重现链接)
https://codesandbox.io/s/magical-architecture-p29q3j?file=/src/Demo.vue

### Reappearance steps (重现步骤)
本地分页。非受控模式，设置了 defaultPageSize 不生效

### Expected results (期望的结果)
应该是可以分页，默认分页大小符合设定

### Actual results (实际的结果)
实际还是保持了 10 的分页设定。

**Comment by jizai1125** [comment]
`DataTable` 分页是受控的

**Comment by Colory** [comment]
> `DataTable` 内部的分页是受控的

意思是不支持非受控的设置分页大小吗，我记得之前的某个版本好像都还可以的。
如果需要通过table本地分页的话。就必须要设置受控分页才行了吗？可以简化为非受控模式的分页大小吗，后续版本有考虑支持非受控分页大小吗

**Comment by jizai1125** [comment]
> > `DataTable` 内部的分页是受控的
> 
> 意思是不支持非受控的设置分页大小吗

支持啊，你可以通过 `pageSize` 设置

**Comment by Colory** [comment]
> > > `DataTable` 内部的分页是受控的
> > 
> > 
> > 意思是不支持非受控的设置分页大小吗
> 
> 支持啊，你可以通过 `pageSize` 设置

通过 pageSize 是受控的分页大小。那就无法和sizePicker联动了。需要手动去写联动代码。
```js
{
      pageSize: 2,
      showSizePicker: true,
}
```

期望的是可以非受控下 与sizePicker 联动。 因为使用场景下是设置了分页 大小的可选项 默认从 30开始，页面较大
```js
{
  defaultPageSize: 30,
  pageSizes: [30, 50, 100, 200],
  showSizePicker: true,
}
```

**Comment by jizai1125** [comment]
```
{
  pageSize: 30,
  pageSizes: [30, 50, 100, 200],
  showSizePicker: true,
}
```

**Comment by Colory** [comment]
> ```js
> {
>   pageSize: 30,
>   pageSizes: [30, 50, 100, 200],
>   showSizePicker: true,
> }
> ```

https://codesandbox.io/s/magical-architecture-p29q3j?file=/src/Demo.vue
点击切换分页大小不生效。因为pageSize是受控的

**Comment by jizai1125** [comment]
> > ```js
> > {
> >   pageSize: 30,
> >   pageSizes: [30, 50, 100, 200],
> >   showSizePicker: true,
> > }
> > ```
> 
> https://codesandbox.io/s/magical-architecture-p29q3j?file=/src/Demo.vue 点击切换分页大小不生效。因为pageSize是受控的

需要监听下 `updatePageSize` 事件然后设置 pageSize，参考文档示例 [受控的分页](https://www.naiveui.com/zh-CN/os-theme/components/data-table#controlled-page.vue )

**Comment by Colory** [comment]
> > > ```js
> > > {
> > >   pageSize: 30,
> > >   pageSizes: [30, 50, 100, 200],
> > >   showSizePicker: true,
> > > }
> > > ```
> > 
> > 
> > https://codesandbox.io/s/magical-architecture-p29q3j?file=/src/Demo.vue 点击切换分页大小不生效。因为pageSize是受控的
> 
> 需要监听下 `updatePageSize` 事件然后设置 pageSize，参考文档示例 [受控的分页](https://www.naiveui.com/zh-CN/os-theme/components/data-table#controlled-page.vue)

所以我就是想问下 会不会后期支持`dataTable`非受控的分页大小设置 这样的就不需要代码中手动去维护`pageSize`参数了

**Comment by jizai1125** [comment]
> > > > ```js
> > > > {
> > > >   pageSize: 30,
> > > >   pageSizes: [30, 50, 100, 200],
> > > >   showSizePicker: true,
> > > > }
> > > > ```
> > > 
> > > 
> > > https://codesandbox.io/s/magical-architecture-p29q3j?file=/src/Demo.vue 点击切换分页大小不生效。因为pageSize是受控的
> > 
> > 
> > 需要监听下 `updatePageSize` 事件然后设置 pageSize，参考文档示例 [受控的分页](https://www.naiveui.com/zh-CN/os-theme/components/data-table#controlled-page.vue)
> 
> 所以我就是想问下 会不会后期支持`dataTable`非受控的分页大小设置 这样的就不需要代码中手动去维护`pageSize`参数了

是有问题，我尝试修复下
