### ISSUE TITLE
级联选择框宽度如何设置

### ISSUE THREAD

**Issue by hyeluoh** [tusen-ai/naive-ui#5202]
### This function solves the problem (这个功能解决的问题)
使用级联框做省市区时候，发现部分数据被隐藏，select框是可以使用consistent-menu-width属性不限制菜单内容，级联框是不是也可以把这个属性放出了？
### Expected API (期望的 API)
类似select 属性consistent-menu-width

**Comment by Sepush** [comment]
take a look https://github.com/tusen-ai/naive-ui/issues/5360

**Comment by Sepush** [comment]
父级元素设置宽一些应该可以解决

**Comment by hyeluoh** [comment]
感谢，关闭虚拟滚动解决了！
![image](https://github.com/tusen-ai/naive-ui/assets/31063160/a3af3382-d24a-4cca-8ffd-280a61a8fab9)

**Comment by dongpeeng** [comment]
关闭虚拟滚动后，在过滤搜索的时候，下拉选项仍然是虚拟列表呢，无法自适应宽度

<img width="825" alt="Image" src="https://github.com/user-attachments/assets/6357ea14-0b29-4574-a547-382aa2b4944c" />
