### ISSUE TITLE
trap-focus: false 会导致 NDrawer 的 close-on-esc 失效

### ISSUE THREAD

**Issue by LiuJi-Jim** [tusen-ai/naive-ui#5203]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Chrome Version 116.0.5845.140 (Official Build) (arm64)

### System and its version (系统及其版本)
macOS 13.3.1 (a) 

### Reappearance link (重现链接)
https://codesandbox.io/p/sandbox/upbeat-minsky-6xdmd4?file=/src/App.vue:29,25

### Reappearance steps (重现步骤)
使用以上 code sandbox，点击「Show drawer」，然后按下键盘 ESC 键。

### Expected results (期望的结果)
按下 ESC 应该关闭 Drawer，该行为应该与 trapFocus 无关。

### Actual results (实际的结果)
trapFocus: true 时，ESC 有效。trapFocus: false 时，ESC 失效。

**Comment by jizai1125** [comment]
这是符合预期的

**Comment by LiuJi-Jim** [comment]
即使在实现上只有焦点在 Drawer 内部才会响应 esc 是可以接受的，但是可以尝试一下，点击一下 Drawer 内部，甚至选中 Drawer 内部分文字，或者在里面加一个 <input> 这类的，保证焦点在其内部，按下 esc，还是没有响应。
<img width="1100" alt="image" src="https://github.com/tusen-ai/naive-ui/assets/2749742/699bb7b1-d94d-4fd4-854d-20a6ecb4349a">

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
