### ISSUE TITLE
在window系统中，Date Picker组件聚焦弹出日历后，点击底部状态栏日历消失，再点回页面，日历就会闪烁一下

### ISSUE THREAD

**Issue by speedhigh** [tusen-ai/naive-ui#5205]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
chrome 116.0.5845.140

### System and its version (系统及其版本)
windows 11

### Reappearance link (重现链接)
https://codesandbox.io/s/nervous-sid-lcfw75

### Reappearance steps (重现步骤)
在window系统中，Date Picker组件聚焦弹出日历后，点击底部状态栏日历消失，再点回页面，日历就会闪烁一下

### Expected results (期望的结果)
像element ui 一样，日历重新打开

### Actual results (实际的结果)
Date Picker组件聚焦弹出日历后，点击底部状态栏日历消失，再点回页面，日历就会闪烁一下

### Remarks (补充说明)
不确定在其他组件（例如n-select的filterable状态下）是否存在同样的问题

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
