### ISSUE TITLE
Data table clear the checked rows

### ISSUE THREAD

**Issue by kikyoluka** [tusen-ai/naive-ui#5208]
### This function solves the problem (这个功能解决的问题)
I checked the documentation, but I couldn't find an API or any way to clear the selected data, Can the data table have a clearFilters-like method that clearFilters clears all currently selected data?
### Expected API (期望的 API)
A table method similar to element-ui clearSelection removes the selection

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by horseson2018** [comment]
> This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

所以现在有api能清除selectedRows了嘛

**Comment by WendyHsinYun** [comment]
我也遇到這個問題，目前已經解決。

除了使用 @update:checked-row-keys="handleCheck" 以外，再加上 `:checked-row-keys="checkedRowKeys"` 這個 prop，就可以透過 checkedRowKeys.value = []; 將刪除後的選項清空。

```
  <NDataTable
    :row-key="rowKey"
    :checked-row-keys="checkedRowKeys"
    :columns="columns"
    :data="data"
    :loading="loading"
    :pagination="pagination"
    @update:checked-row-keys="handleCheck"
  />


const checkedRowKeys = ref([])


const handleCheck = async (rowKeys) => {
  checkedRowKeys.value = rowKeys;
};

// 清空 rowKeys 

const resetCheckedRowKeys = () => {
  checkedRowKeys.value = [];
};
```
