### ISSUE TITLE
create 创建Notification不支持placement配置

### ISSUE THREAD

**Issue by longchuxiong** [tusen-ai/naive-ui#5211]
### This function solves the problem (这个功能解决的问题)
只能在n-notification-provider全局使用placement，会导致全局的Notification的位置只能出现在一个位置，如果我需要一个登录成功显示在右上角，通知显示在右下角就做不到
### Expected API (期望的 API)
create时支持placement配置

**Comment by jizai1125** [comment]
n-notification-provider 可以只用在调用的地方，这样就不会影响全局了，或者可以使用 [脱离上下文的 API](https://www.naiveui.com/zh-CN/os-theme/components/discrete)

**Comment by longchuxiong** [comment]
[脱离上下文的 API](https://www.naiveui.com/zh-CN/os-theme/components/discrete)可以解决
