### ISSUE TITLE
n-menu 折叠后没有子菜单的选项也会显示为有子菜单的样式

### ISSUE THREAD

**Issue by firmianaQ** [tusen-ai/naive-ui#5216]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Chrome 116.0.5845.141

### System and its version (系统及其版本)
win11

### Reappearance link (重现链接)
https://codesandbox.io/s/currying-cache-2pvmly?file=/src/Demo.vue

### Reappearance steps (重现步骤)
首先折叠菜单，然后看悬浮的子菜单；
菜单 叙事者 和 羊男 都是没有子菜单的，
叙事者 的children值为null，
羊男 的children值为undefined，
但是叙事者 显示的是有子菜单的样式

### Expected results (期望的结果)
children的值为null也应该是没有子菜单

### Actual results (实际的结果)
只有children的值为undefined才被当作没有子菜单的项

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
