### ISSUE TITLE
Tree组件数据渲染错误问题

### ISSUE THREAD

**Issue by moshuchao** [tusen-ai/naive-ui#5217]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.2.47

### Browser and its version (浏览器及其版本)
Chrome(114.0.5735.90)

### System and its version (系统及其版本)
MacOS(10.15.7)

### Reappearance link (重现链接)
https://codesandbox.io/p/sandbox/cocky-sammet-5mz9qd?file=/src/App.vue

### Reappearance steps (重现步骤)
点击tab“我是1” > 点击tab“我是2”  > 点击tab“我是3” ,
点击tab“我是3” > 点击tab“我是2”  > 点击tab“我是1” ，此时第一个tab对应的数据没有更新。

### Expected results (期望的结果)
第一个tab对应的数据是data1

### Actual results (实际的结果)
第一个tab对应的数据是data2

### Remarks (补充说明)
并且从vue开发工具看出Tree data值是没有问题的。

**Comment by 07akioni** [comment]
厉害，能发现这种 bug 也是挺厉害的

**Comment by 07akioni** [comment]
好他妈奇怪的问题，按理说不应该来着
