### ISSUE TITLE
[请求添加组件] data form

### ISSUE THREAD

**Issue by InfernalAzazel** [tusen-ai/naive-ui#5218]
### This function solves the problem (这个功能解决的问题)
该功能 类似  [vue-json-schema-form](https://github.com/lljj-x/vue-json-schema-form)
这种组件非常多使用场景需要 比如 admin 配合 n-data-table 快速实现 CRUD
### Expected API (期望的 API)
利于 n-data-table 配合

**Comment by jahnli** [comment]
That may not be possible for the time being
