### ISSUE TITLE
Nuxt3.7 组件样式没有在服务端生成的html内

### ISSUE THREAD

**Issue by yanhoor** [tusen-ai/naive-ui#5220]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Chrome 版本 116.0.5845.140

### System and its version (系统及其版本)
MacOS 14

### Node version (Node 版本)
Node 16.16.0

### Reappearance link (重现链接)
https://codesandbox.io/s/u6w4gh

### Reappearance steps (重现步骤)
已经按文档https://www.naiveui.com/zh-CN/os-theme/docs/ssr配置，正常引入组件使用。

### Expected results (期望的结果)
在 Nuxt 3.6.5 上，比如当前页面引入组件n-button后，对应的的样式会在服务端生成的html的head内类似<style cssr-id="n-button"><style>标签内。期望在 Nuxt3.7.0 上使用也是这样。

### Actual results (实际的结果)
Nuxt3.7.0 后，组件的样式不在返回的 html 内，而是在客户端生成内联样式动态插入，也就是说这个生成步骤没有在服务端进行，而是在客户端进行，这样造成了刷新页面时，页面样式错乱。

**Comment by kakajansh** [comment]
Not sure whether it is related, but I used plugin from [nuxt-naiveui](https://github.com/becem-gharbi/nuxt-naiveui). I did not need other features of that package, so included only required parts for my project

https://github.com/becem-gharbi/nuxt-naiveui/blob/27a88613511602e998ee935edadb7c3fb15ddd36/src/runtime/plugins/naive.server.ts

**Comment by songzhen0207** [comment]
`export default defineNuxtPlugin({
  name: 'naive-ui',
  enforce: 'pre',
  setup(nuxtApp) {
    if (process.server) {
      const { collect } = setup(nuxtApp.vueApp)
      nuxtApp.ssrContext?.head.hooks.hook('tags:resolve', (ctx) => {
        //  insert Style after meta
        const lastMetaIndex = ctx.tags.map(x => x.tag).lastIndexOf('meta')
        const styleTags = collect().split('</style>').filter(Boolean).map(x => {
          const id = x.match(/cssr-id="(.+?)"/)?.[1]
          const style = (x.match(/>(.*)/s)?.[1] || '').trim()
          return {
            tag: 'style',
            props: {'cssr-id': id},
            innerHTML: style
          }
        })
        ctx.tags.splice(lastMetaIndex+1, 0, ...styleTags)
      })
    }
  }
})`
升级到3.7后，ssrContext.renderMeta方法废弃了，按照上面写个插件，暂时解决了这个问题

**Comment by songzhen0207** [comment]
```
export default defineNuxtPlugin({
  name: 'naive-ui',
  enforce: 'pre',
  setup(nuxtApp) {
    if (process.server) {
      const { collect } = setup(nuxtApp.vueApp)
      nuxtApp.ssrContext?.head.hooks.hook('tags:resolve', (ctx) => {
        //  insert Style after meta
        const lastMetaIndex = ctx.tags.map(x => x.tag).lastIndexOf('meta')
        const styleTags = collect().split('</style>').filter(Boolean).map(x => {
          const id = x.match(/cssr-id="(.+?)"/)?.[1]
          const style = (x.match(/>(.*)/s)?.[1] || '').trim()
          return {
            tag: 'style',
            props: {'cssr-id': id},
            innerHTML: style
          }
        })
        ctx.tags.splice(lastMetaIndex+1, 0, ...styleTags)
      })
    }
  }
})
```
升级到3.7后，ssrContext.renderMeta方法废弃了，按照上面代码写个插件可暂时结局。

**Comment by fschuermeyer** [comment]
Unfortunately, I have the same problem. It was solved with the additional plugin from @songzhen0207 for the moment. Thanks!

**Comment by sixdjango** [comment]
> ```
> export default defineNuxtPlugin({
>   name: 'naive-ui',
>   enforce: 'pre',
>   setup(nuxtApp) {
>     if (process.server) {
>       const { collect } = setup(nuxtApp.vueApp)
>       nuxtApp.ssrContext?.head.hooks.hook('tags:resolve', (ctx) => {
>         //  insert Style after meta
>         const lastMetaIndex = ctx.tags.map(x => x.tag).lastIndexOf('meta')
>         const styleTags = collect().split('</style>').filter(Boolean).map(x => {
>           const id = x.match(/cssr-id="(.+?)"/)?.[1]
>           const style = (x.match(/>(.*)/s)?.[1] || '').trim()
>           return {
>             tag: 'style',
>             props: {'cssr-id': id},
>             innerHTML: style
>           }
>         })
>         ctx.tags.splice(lastMetaIndex+1, 0, ...styleTags)
>       })
>     }
>   }
> })
> ```
> 
> 升级到3.7后，ssrContext.renderMeta方法废弃了，按照上面代码写个插件可暂时解决。

**it worked, thinks bro**

**Comment by 2556227850** [comment]
感谢大佬，不过官方怎么还不修复这个问题

**Comment by GoMateoGo** [comment]
> 感谢大佬，不过官方怎么还不修复这个问题

老哥.你搞定了吗? 
在nuxt.config.ts中应该怎么配置?

**Comment by 2556227850** [comment]
最新版的nuxt3在plugins里面配置就大佬贴出来的代码就行了，官网的贴出来的plugins配置插件可以不要用了

‘’不懒不惰不小孩‘’
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tusen-ai/naive-ui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月21日(星期四) 上午9:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tusen-ai/naive-ui] Nuxt3.7 组件样式没有在服务端生成的html内 (Issue #5220)





  
感谢大佬，不过官方怎么还不修复这个问题
  
老哥.你搞定了吗?
 在nuxt.config.ts中应该怎么配置?

**Comment by 07akioni** [comment]
Naive 现在官方提供 nuxt ssr 插件了

https://www.naiveui.com/en-US/os-theme/docs/nuxtjs

**Comment by codeblockhead** [comment]
> Naive 现在官方提供 nuxt ssr 插件了
> 
> https://www.naiveui.com/en-US/os-theme/docs/nuxtjs

为什么我使用这个插件首屏依然没有插入样式

**Comment by TimofeyBiryukov** [comment]
Having this issue right now with this version:
```
"nuxt": "^3.12.1",
"nuxtjs-naive-ui": "^1.0.2",
```

On the initial page load the page looks like this:
![image](https://github.com/user-attachments/assets/5a8c0803-1b4c-464e-bfbd-6286bb5a7818)

It does appear that the styles are not there when the page loads and then they snap in to place.

**Comment by docloulou** [comment]
same here, @songzhen0207 still works. any ssr fix soon ?
Thanks

**Comment by megasanjay** [comment]
For anyone searching for a solution, this gist seems to have solved my issue with this problem: https://gist.github.com/BarishNamazov/52522dd1552bbc28a781d04756ac3a64 Add it to `plugins/naive-ui.ts` and it seems to work for me

**Comment by huoliwei** [comment]
增加插件后出来警告[Vue warn]: App already provides property with key "@css-render/vue3-ssr". It will be overwritten with the new value.有谁遇到过这个问题吗？
"nuxt": "^3.13.0",
"nuxtjs-naive-ui": "^1.0.2",
"naive-ui": "^2.40.1",

**Comment by bsuooo** [comment]
> 增加插件后出来警告[Vue warn]: App already provides property with key "@css-render/vue3-ssr". It will be overwritten with the new value.有谁遇到过这个问题吗？增加插件后出来警告[Vue warn]： App 已经提供了 key 为 “@css-render/vue3-ssr” 的属性。它将被新值覆盖。有谁遇到过这个问题吗？ "nuxt": "^3.13.0", “nuxt”： “^3.13.0”， / "nuxtjs-naive-ui": "^1.0.2",“nuxtjs-naïve-naïve”： “1.0.2”， //英文 "naive-ui": "^2.40.1", “naive-ui”： “2.40.1”， //天真用户界面

增加插件后 去除 nuxtjs-naive-ui  就不会报错了

**Comment by zhaoyuqiqi** [comment]
> > 增加插件后出来警告[Vue warn]: App already provides property with key "@css-render/vue3-ssr". It will be overwritten with the new value.有谁遇到过这个问题吗？增加插件后出来警告[Vue warn]： App 已经提供了 key 为 “@css-render/vue3-ssr” 的属性。它将被新值覆盖。有谁遇到过这个问题吗？ "nuxt": "^3.13.0", “nuxt”： “^3.13.0”， / "nuxtjs-naive-ui": "^1.0.2",“nuxtjs-naïve-naïve”： “1.0.2”， //英文 "naive-ui": "^2.40.1", “naive-ui”： “2.40.1”， //天真用户界面
> 
> 增加插件后 去除 nuxtjs-naive-ui 就不会报错了

感谢！这样子可以了
