### ISSUE TITLE
data-table docs ui

### ISSUE THREAD

**Issue by hzhoup** [tusen-ai/naive-ui#5237]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Chrome(116.0.5845.188)

### System and its version (系统及其版本)
Windows(10)

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/data-table

### Reappearance steps (重现步骤)
数据表格浅色主题下 tip 和侧边栏缩起按钮样式不对
![image](https://github.com/tusen-ai/naive-ui/assets/109516832/65b553c8-d844-4194-ae18-df718275e4b2)

### Expected results (期望的结果)
相应的浅色主题

### Actual results (实际的结果)
两个组件底色是黑色，也不是深色主题的样式

**Comment by jizai1125** [comment]
你是不是改了主题编辑器中 alert 的主题

**Comment by hzhoup** [comment]
清除之后就正常了，应该以前改了，文档的主题编辑器也缓存了的么
