### ISSUE TITLE
目前upload 组件没有办法自动与 form 配合 做数据动态校验，只能手动触发

### ISSUE THREAD

**Issue by wxwebfeng** [tusen-ai/naive-ui#5239]
### This function solves the problem (这个功能解决的问题)
表单中有附件必填，上传了之后 form校验提示还是一直提示，需要开发者去手动触发校验才能清除，或者本有一个附件用户删除了，逻辑上是需要提示用户这是必填，期待后期能与formItem的 handleContentChange 方法触发自动校验
### Expected API (期望的 API)
表单中有附件必填，上传了之后 form校验提示还是一直提示，需要开发者去手动触发校验才能清除，或者本有一个附件用户删除了，逻辑上是需要提示用户这是必填，期待后期能与formItem的 handleContentChange 方法触发自动校验

**Comment by web-wade** [comment]
有合适方案吗

**Comment by easy868** [comment]
同样的问题，有合适方案吗

**Comment by qlj1997** [comment]
![image](https://github.com/user-attachments/assets/103bf50f-69b4-4e47-a95e-dfbba695ef8a)

借助 [vite-plugin-vue-devtools](https://www.npmjs.com/package/vite-plugin-vue-devtools) 发现 `n-form-item` 注入
![image](https://github.com/user-attachments/assets/065dc27d-6147-4060-9dd7-d7de430cf0d4)

```typescript
// UploadImage.vue  

import type { FormItemInjection } from 'naive-ui/es/_mixins/use-form-item';  
const formItem = inject<FormItemInjection>('n-form-item');  
...
formItem?.handleContentChange(); // 上传成功后调用
``` 

![image](https://github.com/user-attachments/assets/5d49e960-055e-43f2-b1ca-eb155cf155e1)

**Comment by jahnli** [comment]
Through custom upload, callback successfully verifies the form
