### ISSUE TITLE
深色主题下，可以让输入框背景颜色不是透明的吗？

### ISSUE THREAD

**Issue by FishHawk** [tusen-ai/naive-ui#5240]
### This function solves the problem (这个功能解决的问题)
目前，深色主题下，input背景颜色是透明的。这在有些情况下看起来很奇怪，比如在背景图片之上的输入框。

深色：
<img width="768" alt="image" src="https://github.com/tusen-ai/naive-ui/assets/46566858/73376530-44e8-43ac-93d6-9666eab9a0e1">

浅色：
<img width="768" alt="image" src="https://github.com/tusen-ai/naive-ui/assets/46566858/02904585-ac5e-4896-9dc5-57dc20e47645">

### Expected API (期望的 API)
希望深色主题下，默认的输入框背景颜色和浅色模式一样，是不透明的颜色。

**Comment by Sepush** [comment]
你可以在这个input外面使用 config-provider 来改变默认行为

**Comment by FishHawk** [comment]
> 你可以在这个input外面使用 config-provider 来改变默认行为

我知道，只是这样默认浅色/深色主题不一致，很奇怪。

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
