### ISSUE TITLE
Select 多选，主题配置有问题，选中后展示的tag的fontsize不支持自定义主题

### ISSUE THREAD

**Issue by wangnannanziyu** [tusen-ai/naive-ui#5243]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Chrome 116.0.5845.187

### System and its version (系统及其版本)
MacOS(11.5.1)

### Reappearance link (重现链接)
https://codesandbox.io/s/intelligent-pond-6fd8pj?file=/src/Demo.vue

### Reappearance steps (重现步骤)
1. 设置select的属性：multiple=true;size=small;
2. 此时，期望select选择后展示的tag字体大小应该符合fontsizesmall，为12px。但实际写死14px

主要受此样式影响：
.n-base-selection-tag-wrapper .n-tag {
    font-size: 14px;
    max-width: 100%;
}

### Expected results (期望的结果)
期望多选select选择后展示的tag字体大小符合主题设置

### Actual results (实际的结果)
多选select选择后展示的tag字体大小不受主题控制

**Comment by jahnli** [comment]
Looks like it's been repaired.
