### ISSUE TITLE
给NotificationReactive Properties增加type字段

### ISSUE THREAD

**Issue by CS-liujf** [tusen-ai/naive-ui#5245]
### This function solves the problem (这个功能解决的问题)
当前Notification组件无法动态修改其类型(比如从info转为success)，而Message
组件却可以
### Expected API (期望的 API)
仿造MessageReactive Properties，直接给NotificationReactive Properties增加type字段

**Comment by jahnli** [comment]
https://www.naiveui.com/zh-CN/os-theme/components/notification#change-content.vue
