### ISSUE TITLE
n-pagination 组件当item-count的值达到千万级别的时候，切换页码的时候会感觉明显卡顿。

### ISSUE THREAD

**Issue by zerox-v** [tusen-ai/naive-ui#5251]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Chrome(116.0.5845.188)

### System and its version (系统及其版本)
window11

### Reappearance link (重现链接)
https://codesandbox.io/s/elegant-cookies-9sclhz?file=/src/Demo.vue

### Reappearance steps (重现步骤)
1、设置item-count 为37367580 
2、点击页码 会发现很久才能切换到对应的页码上面

### Expected results (期望的结果)
期望页码的切换速度和item-count 为100 的时一样快

### Actual results (实际的结果)
实际item-count 的值越大，切换页码的时候响应就越慢

**Comment by jizai1125** [comment]
数据太大的话，会构造大量的快速跳转的下拉菜单数据，应该由于这个原因

**Comment by 07akioni** [comment]
确实应该提供一个选项关掉现在的下拉菜单交互
