### ISSUE TITLE
upload组件创建动态表单之后，我想动态回显无法做到

### ISSUE THREAD

**Issue by TenXLL** [tusen-ai/naive-ui#5280]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
118.0.5993.11

### System and its version (系统及其版本)
windows11

### Reappearance link (重现链接)
https://github.com/TenXLL/crane-naive

### Reappearance steps (重现步骤)
项目下载下来运行就能看见，调用代码就在App.vue。
简介一下就是：我创建了一个动态创建表单的组件，里面用到了upload组件，在我想回显的时候（调用组件props传入，我在onMouted里面获取props的值然后赋值给default-file-list的）。麻烦大大看一下了，看看怎么解决

### Expected results (期望的结果)
我创建了一个动态创建表单的组件，里面用到了upload组件，在我想回显的时候（调用组件props传入，我在onMouted里面获取props的值然后赋值给default-file-list的）。麻烦大大看一下了，看看怎么解决

### Actual results (实际的结果)
无法回显

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
