### ISSUE TITLE
Data Table default sorter broken when using null values

### ISSUE THREAD

**Issue by Vringe** [tusen-ai/naive-ui#5281]
### TuSimple/naive-ui version (版本)
2.34.4

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Chrome (117.0.5938.92)

### System and its version (系统及其版本)
MacOS (13.6)

### Reappearance link (重现链接)
https://codesandbox.io/s/quirky-keller-3dhh9l

### Reappearance steps (重现步骤)
Sort the "Bar" column ascending or descending -> Nothing happens

### Expected results (期望的结果)
Rows should be sorted

### Actual results (实际的结果)
Rows are not being sorted

### Remarks (补充说明)
As soon as I remove the row with the null value, sorting works again as expected.

**Comment by Vringe** [comment]
Thank you, I understand. I would like to discuss if this behavior is really desired or if this should be changed in the default sorter? In my opinion, columns with zero values should be at the very bottom or top when sorting.

**Comment by jizai1125** [comment]
> Thank you, I understand. I would like to discuss if this behavior is really desired or if this should be changed in the default sorter? In my opinion, columns with null values should be at the very bottom or top when sorting.
The `sorter` prop also accepts your  custom compare function  If you don't use the built-in compare function.

**Comment by Vringe** [comment]
Yes, I saw that. Of course, it is convenient to be able to use your own sorter functions.
However, I think that the default behavior should be changed as suggested.

How would so solve that with a custom sorter function without defining it every time? I would like to define it once globally and reference to it. But as far as I can see in the docs, only the whole rows get passed to my function without knowing the actual column which makes it impossible to use it in that way.

**Comment by 07akioni** [comment]
corresponding PR merged
