### ISSUE TITLE
data-table的row-key能否支持数组下标

### ISSUE THREAD

**Issue by WiseSheep1** [tusen-ai/naive-ui#5285]
### This function solves the problem (这个功能解决的问题)
有一种情况，需要向后端传递多个对象，采用可编辑表格实现，在编辑过程中操作表格项复选框批量删除，此时数组中没有唯一key，能不能用数组下标代替
### Expected API (期望的 API)
如data-table的row-props提供的api一样，(rowData: object, rowIndex : number) => (number | string)

**Comment by jahnli** [comment]
Customize the primary key at creation time
