### ISSUE TITLE
Official website cannot be accessed。https://www.naiveui.com/  

### ISSUE THREAD

**Issue by alan-amazing** [tusen-ai/naive-ui#5297]
### TuSimple/naive-ui version (版本)
2.35.0

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Microsoft Edge  117.0.2045.43 (正式版本) (64 位)

### System and its version (系统及其版本)
win 10

### Reappearance link (重现链接)
https://www.naiveui.com/

### Reappearance steps (重现步骤)
Official website cannot be accessed

### Expected results (期望的结果)
Can access

### Actual results (实际的结果)
Official website cannot be accessed

**Comment by lorenzohee** [comment]
青岛也无法访问

**Comment by jahnli** [comment]
被墙

**Comment by jahnli** [comment]
可以临时克隆仓库，跑下文档

**Comment by ChenYun-321** [comment]
成都这边电信可以访问，移动的被墙了。

**Comment by huyuan9479** [comment]
怎么解决啊

**Comment by jahnli** [comment]
https://ui.naiveadmin.com/

**Comment by alan-amazing** [comment]
[](url)

**Comment by fudiwei** [comment]
站点托管在 Vercel 上，今年十一前后 `cname.vercel-dns.com` 被大面积屏蔽。
