### ISSUE TITLE
希望DataTable数据表格能够支持拖拽排序

### ISSUE THREAD

**Issue by SuperManito** [tusen-ai/naive-ui#5300]
### This function solves the problem (这个功能解决的问题)
实现拖拽排序，参考 https://tdesign.tencent.com/vue-next/components/Table#%E5%8F%AF%E6%8B%96%E6%8B%BD%E6%8E%92%E5%BA%8F%E7%9A%84%E8%A1%A8%E6%A0%BC
### Expected API (期望的 API)
有个回调就行了

**Comment by jahnli** [comment]
duplicate   https://github.com/tusen-ai/naive-ui/issues/5069
