### ISSUE TITLE
tree showline 无效

### ISSUE THREAD

**Issue by ZhouJiang** [tusen-ai/naive-ui#5303]
### TuSimple/naive-ui version (版本)
2.35.0

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Chrome 117

### System and its version (系统及其版本)
win11

### Reappearance link (重现链接)
https://codesandbox.io/s/eager-gates-25cmvx

### Reappearance steps (重现步骤)
更新 2.35.0 tree showline  属性无效

### Expected results (期望的结果)
有效

### Actual results (实际的结果)
无效

**Comment by lisonge** [comment]
怎么关闭了？

我看文档里是有效的，但是从文档里点击的 demo 里是无效的

<https://codesandbox.io/s/z72sg2>

**Comment by lisonge** [comment]
看起来是文档里的 `--n-border-color` 有值

但是实际单独使用这个 tree 组件时， `--n-border-color` 无值导致设置 border 失效从而 line 没有显示

**Comment by jahnli** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/20943608/d1c89dbe-1580-4929-a4b4-a8c05f85436f)
没复现，样式是否被覆盖

**Comment by opcooc** [comment]
https://codesandbox.io/s/eager-gates-25cmvx 这个好像没地方覆盖

**Comment by lisonge** [comment]
现在有说法吗？

因为单独直接设置 `--n-border-color` 不能自动适配深色模式
