### ISSUE TITLE
n-message-provider :to="false"  can not work

### ISSUE THREAD

**Issue by Xzuoyou** [tusen-ai/naive-ui#5306]
### TuSimple/naive-ui version (版本)
2.35.0

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
104

### System and its version (系统及其版本)
win 10

### Reappearance link (重现链接)
https://naive-ui.github.io/issue-helper/?lang=zh-CN

### Reappearance steps (重现步骤)
无

### Expected results (期望的结果)
:to 生效

### Actual results (实际的结果)
:to 不生效

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
