### ISSUE TITLE
表格上下左右键盘事件触发选中、行列编辑

### ISSUE THREAD

**Issue by luzemin-github** [tusen-ai/naive-ui#5307]
### This function solves the problem (这个功能解决的问题)
实际业务操作中，大量数据录入时，常常使用键盘上下左右来切换编辑行和编辑单元格，这需要表格编辑能通过上下左右键盘事件触发选中、行列编辑
### Expected API (期望的 API)
比如通过表格编辑属性 键盘属性配置的方式，如options:{editConfig:{p:v},keyboardConfig:{p:v}}

**Comment by jahnli** [comment]
Try customizing with `row-props`
