### ISSUE TITLE
How to set z-index attribute in the image preview container?

### ISSUE THREAD

**Issue by QC2168** [tusen-ai/naive-ui#5317]
### This function solves the problem (这个功能解决的问题)
I use the drawer component and set the z-index to 5000, while I use the image component in the drawer component. However, I encountered a drawer layer level that is higher than the image preview, resulting in the image not being displayed
### Expected API (期望的 API)
:z-index="5000"

**Comment by QC2168** [comment]
I tried using deep, but it didn't work
```
:deep(.n-image-preview-container){
  z-index: 5001 !important;
}
```

**Comment by 667-1** [comment]
> I tried using deep, but it didn't work
> 
> ```
> :deep(.n-image-preview-container){
>   z-index: 5001 !important;
> }
> ```

n-image-preview-container元素是跟app同级的，把deep去掉，并且去掉scope就可以了

**Comment by QC2168** [comment]
我在`index.css`中写入解决了，如果在`App.vue`上不添加上`deep`的话，`Vue`会额外处理类名的 @667-1
