### ISSUE TITLE
NGrid的直系子组件只能是NGridItem/NGi,但无法跨组件

### ISSUE THREAD

**Issue by itmanyong** [tusen-ai/naive-ui#5320]
### TuSimple/naive-ui version (版本)
2.35.0

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
EDGE最新版

### System and its version (系统及其版本)
Windows22h2 pro x64

### Node version (Node 版本)
20.7

### Reappearance link (重现链接)
https://codesandbox.io/p/sandbox/fast-wood-65c5k5

### Reappearance steps (重现步骤)
直接使用NGrid组件。内部直接子组件必须是NGridItem，而不能是自定义组件，即时自定义组件内部直接返回了NGridItem。也会导致不渲染不执行

### Expected results (期望的结果)
能够支持自定义组件作为NGrid的直接子组件

### Actual results (实际的结果)
目前不支持自定义组件作为直接子组件

### Remarks (补充说明)
有此需求是因为有时需要动态控制多个NGridItem的显示隐藏，而多个NGridItem集成到一个组件，更够更加直观统一方便的组装逻辑和实现

**Comment by jahnli** [comment]
This is the current design
