### ISSUE TITLE
和(vike)vite-plugin-ssr一起使用，服务端渲染的html文件中未包含css样式，导致页面闪烁

### ISSUE THREAD

**Issue by DoveAz** [tusen-ai/naive-ui#5326]
### TuSimple/naive-ui version (版本)
2.35.0

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
chrome 118

### System and its version (系统及其版本)
win11

### Node version (Node 版本)
16

### Reappearance link (重现链接)
https://codesandbox.io/p/sandbox/small-worker-lt2qcv

### Reappearance steps (重现步骤)
打开链接后，刷新右侧预览区域页面，会看到n-input没有样式，在客户端渲染完成后才会加载样式

### Expected results (期望的结果)
服务端生成的html中包含样式

### Actual results (实际的结果)
服务端生成的html中未包含样式导致页面闪烁

**Comment by sansui-orz** [comment]
同样的问题，使用的Nuxt3

**Comment by DoveAz** [comment]
> 同样的问题，使用的Nuxt3
我用nuxt3 没有这个问题

**Comment by sansui-orz** [comment]
> > 同样的问题，使用的Nuxt3
> > 我用nuxt3 没有这个问题

那你这个issue说的是Nuxt2? 请问你的Nuxt3是全局引入吗？我看官方的nuxt使用例子也会有闪烁

**Comment by sansui-orz** [comment]
> > > 同样的问题，使用的Nuxt3
> > > 我用nuxt3 没有这个问题
> 
> 请问你的Nuxt3是全局引入吗？我看官方的nuxt使用例子也会有闪烁

 我发现了问题，但是还没想到如何解决。这里存在两个问题，都在Naive-ui对plugins的插件代码里。

1. 我使用了nuxt v3.7，这个版本不存在nuxtApp.ssrContext?.renderMeta方法
2. @css-render/vue3-ssr对nuxt v3.7也无法获取到css样式。

目前看来只有降级到nuxt v3.2 （这个版本经测试OK）

**Comment by sansui-orz** [comment]
找到解决方法：https://github.com/07akioni/css-render/issues/1108

**Comment by TickHeart** [comment]
@sansui-orz 非常感谢

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by 07akioni** [comment]
现在提供了官方的 nuxt module。
We provide official nuxt module now.

https://www.naiveui.com/en-US/os-theme/docs/nuxtjs

**Comment by huoliwei** [comment]
我也遇到了这个问题，但是naive-ui的官方案例中并没有这个问题，[https://github.com/07akioni/naive-ui-nuxt-demo](naive-ui-nuxt-demo)，更奇怪的是，当我移除首页中的<NColorPicker />组件时，问题出现了--！

**Comment by wzc520pyfm** [comment]
> 我也遇到了这个问题，但是naive-ui的官方案例中并没有这个问题，[naive-ui-nuxt-demo](https://github.com/07akioni/naive-ui-nuxt-demo)，更奇怪的是，当我移除首页中的NColorPicker组件时，问题出现了--！

I can reproduce it stably in nuxt@3.14.

https://github.com/07akioni/nuxtjs-naive-ui/issues/7

**Comment by Lonsho** [comment]
官方提供的插件`nuxtjs-naive-ui`在nuxt 3.17.7 中的并没有效果，使用自定义的naive-ui插件吧，这个效果还是可以的

```
import { defineNuxtPlugin } from '#imports'
import { setup } from '@css-render/vue3-ssr'

export default defineNuxtPlugin((_nuxtApp) => {
  const { collect } = setup(_nuxtApp.vueApp)
  if (import.meta.server) {
    useHead({
      style: () => collect().split('</style>').map((block) => {
        const id = /cssr-id="(.+?)"/.exec(block)?.[1]
        const style = (/>(.*)/s.exec(block)?.[1] ?? '').trim()
        return {
          'cssr-id': id,
          'innerHTML': style,
        }
      }),
    })
  }
})
```

**Comment by MomoseMitsuki** [comment]
Thank you for your example, which solved the naive-ui style flickering issue. However, we also need to configure Vite as follows to pre-bundle these dependencies in nuxt.config.ts to avoid page reloads:
```nuxt.config.ts
export default defineNuxtConfig({
  vite: {
    optimizeDeps: {
      include: [
        '@css-render/vue3-ssr',
      ]
    }
  }
})
```
