### ISSUE TITLE
[NDrawer] Resizable drawer bugs

### ISSUE THREAD

**Issue by cefiro** [tusen-ai/naive-ui#5329]
### TuSimple/naive-ui version (版本)
2.35.0

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Chrome latest

### System and its version (系统及其版本)
Linux

### Reappearance link (重现链接)
https://codesandbox.io/s/ecstatic-shirley-tzdhrs?file=/src/Demo.vue

### Reappearance steps (重现步骤)
1. Set the "min-width" or "min-height" properties
2. Change the size of the drawer (first bug). Video: https://nimb.ws/1tGjUC
3. Change the size of the browser window with the extended drawer (second bug)

### Expected results (期望的结果)
Adaptability in window size is expected

### Actual results (实际的结果)
Drawer goes beyond the boundaries of the screen

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
