### ISSUE TITLE
表格必须设置max-height才能滚动吗？

### ISSUE THREAD

**Issue by bestime** [tusen-ai/naive-ui#5331]
### This function solves the problem (这个功能解决的问题)
需要flex:1或height:100%或width:100%这种情况下，可以自动固定表头及滚动了。以前用element-ui挺好的，最近换这个框架试试，遇到表格这个问题，肯定不能指定一个具体值
### Expected API (期望的 API)
不指定srcoll-x和max-height到达固定表头和列

**Comment by jahnli** [comment]
This is the current design
