### ISSUE TITLE
官网访问卡顿，过慢

### ISSUE THREAD

**Issue by damnright** [tusen-ai/naive-ui#5340]
### TuSimple/naive-ui version (版本)
2.35.0

### Vue version (Vue 版本)
3.3.6

### Browser and its version (浏览器及其版本)
chrome89

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://www.naiveui.com/

### Reappearance steps (重现步骤)
打开google 访问官网 无论是否翻墙 访问都特别慢

### Expected results (期望的结果)
网站访问快一点  增加个国内镜像

### Actual results (实际的结果)
官网访问特别慢

**Comment by bald-head** [comment]
有没有什么解决方案，我也遇到访问缓慢， 不管事科学还是直连都很慢

**Comment by gaojiangtao-git** [comment]
先可临时使用 https://ui.naiveadmin.com/zh-CN/os-theme

**Comment by bald-head** [comment]
> 先可临时使用 https://ui.naiveadmin.com/zh-CN/os-theme

谢谢
