### ISSUE TITLE
More Calendar Props 大日历组件应有更多功能

### ISSUE THREAD

**Issue by Type-32** [tusen-ai/naive-ui#5341]
### This function solves the problem (这个功能解决的问题)
Solves the complex implementation of calendar-related props:
- adding modals and features inside a single calendar slot, etc.

### Expected API (期望的 API)
The Calendar Component should add APIs for adding stuff inside individual calendar slots like tasks
and timelines display, similar to that of a real calendar app
e.g. Apple Calendar with their single-day schedule timeline display with
stretched blocks that represent a schedule or task, or similar to kanban calendars that
has horizontally stretched blocks that represents a schedule or task with a long span over time.

**Comment by gaojiangtao-git** [comment]
了解这个Fullcalendar日历专门插件会解决你的问题

**Comment by jahnli** [comment]
`Fullcalendar`
