### ISSUE TITLE
Fix sensitive and potentially offensive content about "996" in the Card documentation

### ISSUE THREAD

**Issue by simaoczc** [tusen-ai/naive-ui#5343]
### This function solves the problem (这个功能解决的问题)
这是一个优秀的开源组件库，但是用到card组件的时候感觉有点“奇怪”？

中文文档： 
📖 如何成功
如果你年轻的时候不 996，你什么时候可以 996？你一辈子没有 996，你觉得你就很骄傲了？这个世界上，我们每一个人都希望成功，都希望美好生活，都希望被尊重，我请问大家，你不付出超越别人的努力和时间，你怎么能够实现你想要的成功？
English document:
🎸 Rock N' Roll Star
Tonight I'm a rock 'n' roll star
Tonight I'm a rock 'n' roll star

### Expected API (期望的 API)
same as english version

**Comment by xushanpei** [comment]
PUA

**Comment by Sepush** [comment]
These are just a few memes

**Comment by simaoczc** [comment]
好嘛。一看坐标 杭州， 难怪，这味很对
