### ISSUE TITLE
希望在树形列表里使用ctrl或者shift多选

### ISSUE THREAD

**Issue by txzh007** [tusen-ai/naive-ui#5349]
### This function solves the problem (这个功能解决的问题)
```js
   onClick() {
      if (selectedIds.value.includes(uuid)) {
        selectedIds.value = selectedIds.value.filter((id) => id !== uuid)
      } else {
        if (ctrlKey.value) {
          selectedIds.value = [...selectedIds.value, uuid]
        } else {
          selectedIds.value = [uuid]
        }
      }
    } 
```
ctrl部分已经实现,但是shift目前基于大量数据还没有很好的实践办法,希望寻求组件官方的支持
### Expected API (期望的 API)
node-props 可以提供vnode-id  可以通过api的方式实现连续选中

**Comment by qingruikz** [comment]
n-tree 现在支持键盘属性（keyboard）和鼠标点击选择后，要再加上 shift/ctrl 的选择逻辑的话，感觉在应用层面确实会比较复杂了。
1. 键鼠混用后的逻辑本身比较麻烦：比如 windows 系统里面，shift +点击 连续选中几个文件后再按住 shift + ArrowUp，和按 ctrl 选中同样的连续文件后，按住 shift + ArrowUp 出来的效果是不一样的。
2. tree 不像照片墙或者表格的线性数据，还包括子节点等的数据，这样会导致需要交给用户设定的属性太多了。比如，shift 连续选择是否包含途中经过节点的子节点，是否展开和非展开的子节点都要包括，等等，都需要交给用户设置的话，要加很多 props 了
 
之前的项目里面是通过 tree 的受控模式，重新封装了一下实现的，如果实在需要的话可以参考一下：
1. expandedKeys，selectedKeys 等等都需要自己管理
2. 需要手动记录最后一次非 shift 点击（用于判断 shift 选择的起点，可以在操作系统中试试就会发现 shift 点击的时候起点始终是上一次非 shift 点击），以及最后一次点击是否是 ctrl 点击（用于复刻上述 windows 系统中的选择逻辑）
3. 选择本身比较容易处理，拿到 tree 的排序，过滤后的数据后，在里面筛选就好了，比如 shift 连续选择的功能，可以通过记录的最后一次非 shift 点击的 key，以及本次 shift 点击，找到它们在数据中的 index 然后用 slice 即可。

好处是：
1. 一整套选择逻辑可以打包后放到 tabel 等等其他组件中使用
2. 可以自己微调连续选择时，子节点是否要被包括，等等细节
坏处是：
1. 受控模式的话不少 n-tree 本身的属性，回调函数都不能用了，需要自己封装，因此代码量比较大

**Comment by jahnli** [comment]
This seems beyond the realm of generality
