### ISSUE TITLE
菜单中的图标能否放在后面，而不是在菜单前面

### ISSUE THREAD

**Issue by qyh214** [tusen-ai/naive-ui#5355]
### TuSimple/naive-ui version (版本)
2.35.0

### Vue version (Vue 版本)
3.3.7

### Browser and its version (浏览器及其版本)
Microsoft Edge 版本 118.0.2088.76 

### System and its version (系统及其版本)
win11

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/menu

### Reappearance steps (重现步骤)
按照https://www.naiveui.com/zh-CN/os-theme/components/menu的说明随便写的demo

### Expected results (期望的结果)
期望能控制图标是否在菜单名字的前面或者后面

例如，帮助？  ？帮助  这两种都能设置

### Actual results (实际的结果)
只能让图标在菜单文字前面，例如？帮助

**Comment by yuding-x** [comment]
```
//MenuOption
{
    label: renderSearch(inputstr.value),
    key: 'search'
  },
```
```
function renderSearch (num:string) {
  return () => 
    h(NInput, 
    {
      style:{
        width:'30vw'
      },
      props:{
        value:num,
      },
      class:"h-input",
      placeholder:'搜索',
      onInput:(value)=>{console.log('input', value)},
      onFocus:()=>{historyTabVisible.value = true},
      onBlur:()=>{historyTabVisible.value = false}
    },
      {
//icon渲染
        suffix:renderIcon(Search)
      }
    )
}

function renderIcon (icon: Component) {
  return () => h(NIcon, null, { default: () => h(icon) })
}
```
或许你可以试试用h渲染函数实现
