### ISSUE TITLE
下拉select 校验 当value是Number类型时 校验警告后选中值后仍在提示错误

### ISSUE THREAD

**Issue by Vita-zzzxw** [tusen-ai/naive-ui#5359]
### TuSimple/naive-ui version (版本)
2.35.0

### Vue version (Vue 版本)
3.4.0-alpha.1

### Browser and its version (浏览器及其版本)
Chrome

### System and its version (系统及其版本)
window11

### Reappearance link (重现链接)
https://github.com/Vita-zzzxw(没用)

### Reappearance steps (重现步骤)
   表单下拉控件 rules:{ required: true} ，下拉添加可清除clearable
   下拉Opts: {label: 'United Kingdom', value: 148},
   {label: 'United States', value: 167},
   {label: 'Australia', value: 170},
   {label: 'Canada', value: 166}  value值只要是Number类型就有问题

### Expected results (期望的结果)
校验必填错误提示 选中后应该及时消失

### Actual results (实际的结果)
下拉值选完后清除,blur后触发必填校验, 然后再选中另一个值，必填校验错误提示仍存在

**Comment by Lucianing** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/33444972/e733ddcd-283b-4a33-861e-d4985715b156)

看下文档嘛 😂
