### ISSUE TITLE
n-cascader dropdown menu needs a width setting

### ISSUE THREAD

**Issue by VXenomac** [tusen-ai/naive-ui#5360]
### This function solves the problem (这个功能解决的问题)
When the text in the dropdown is too long, it cannot be displayed properly. Therefore, setting the width of the dropdown becomes crucial
### Expected API (期望的 API)
dropdown-menu-props="{ width: '300px' }"

**Comment by Sepush** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/39197136/d086f057-379f-4d0e-a06c-f7569e0d5d72)
https://www.naiveui.com/en-US/os-theme/docs/customize-theme
custom theme solve this
