### ISSUE TITLE
Popselect组件item添加图标

### ISSUE THREAD

**Issue by naiheyoung** [tusen-ai/naive-ui#5368]
### This function solves the problem (这个功能解决的问题)
希望可以给Popselect组件的每一项都提供一个可选的图标, options配置项里可以加一个icon属性, 用于给每一个选项设置图标
### Expected API (期望的 API)
虽然该组件也提供了一个插槽供用户自定义, 但不是特别友好, 建议给options选项添加一个icon属性
options[{label: '标题', value: '选项内容', icon: '选项图标'}]

**Comment by jahnli** [comment]
`render-label` ?

**Comment by naiheyoung** [comment]
ok, 问题已经解决, 因为个人原因给您造成不便还请见谅.

**Comment by jahnli** [comment]
问题解决，可以关闭它
