### ISSUE TITLE
希望主题支持select组件添加border样式

### ISSUE THREAD

**Issue by ltxhhz** [tusen-ai/naive-ui#5369]
### This function solves the problem (这个功能解决的问题)
themeOverrides和主题编辑器可以添加或修改select的border样式
因为同样为输入组件的input是支持border的
![image](https://github.com/tusen-ai/naive-ui/assets/51697596/5b2c7803-11f5-4aa4-ab39-48e5d17e7787)
并且select组件中也有用来配置border的元素
![image](https://github.com/tusen-ai/naive-ui/assets/51697596/4f7b4560-f23c-4deb-8b35-f335606ffed2)

### Expected API (期望的 API)
可以在themeOverrides和主题编辑器中添加或修改select的border样式

**Comment by jizai1125** [comment]
可以改的
```vue
<script lang="ts">
  import { NConfigProvider, GlobalThemeOverrides } from 'naive-ui'

  const themeOverrides: GlobalThemeOverrides = {
    Select: {
      peers: {
        InternalSelection: {
          border: '1px solid red'
        }
      }
    }
  }
</script>

<template>
  <n-config-provider :theme-overrides="themeOverrides">
    <my-app />
  </n-config-provider>
</template>
```

**Comment by ltxhhz** [comment]
明白了，感谢🙏
