### ISSUE TITLE
n-tree  组件能加入 取消选中状态的功能吗？不然只能使用v-if来取消，很不方便

### ISSUE THREAD

**Issue by Mylinaa** [tusen-ai/naive-ui#5372]
### This function solves the problem (这个功能解决的问题)
n-tree  组件能加入 取消选中状态的功能吗？不然只能使用v-if来取消，很不方便
### Expected API (期望的 API)
n-tree  组件能加入 取消选中状态的功能

**Comment by jizai1125** [comment]
没太懂啥意思，现在不是能取消选中么

**Comment by Mylinaa** [comment]
> 没太懂啥意思，现在不是能取消选中么

现在确实是不能手动取消选中状态，如果有的话，请告知一下谢谢！我看了好久文档

**Comment by jizai1125** [comment]
https://github.com/tusen-ai/naive-ui/assets/33979706/e0afcc08-2ff4-4f14-b86d-993f53f02ac6

这不是么

**Comment by Mylinaa** [comment]
> QQ20231109-204705-HD.mp4 
> 这不是么

您好，您误解我的意思了，是这个不能手动取消掉
![image](https://github.com/tusen-ai/naive-ui/assets/82194403/6566e1d5-ce82-4cc9-b3a2-ab489390b1a6)
目前我想点击list取消上一个的状态，方法是用v-if这样来取消，但是这样做肯定是不对的

**Comment by Mylinaa** [comment]
> > QQ20231109-204705-HD.mp4
> > 这不是么
> 
> 您好，您误解我的意思了，是这个不能手动取消掉 ![image](https://user-images.githubusercontent.com/82194403/281966933-6566e1d5-ce82-4cc9-b3a2-ab489390b1a6.png) 目前我想点击list取消上一个的状态，方法是用v-if这样来取消，但是这样做肯定是不对的

比如我想在这个组件外面做一个按钮，点击一下全选，在点击一下全不选，我看了很久的文档目前好像是做不到，如果您有方法请告知一下，谢谢！

**Comment by jizai1125** [comment]
> > > QQ20231109-204705-HD.mp4
> > > 这不是么
> > 
> > 
> > 您好，您误解我的意思了，是这个不能手动取消掉 ![image](https://user-images.githubusercontent.com/82194403/281966933-6566e1d5-ce82-4cc9-b3a2-ab489390b1a6.png) 目前我想点击list取消上一个的状态，方法是用v-if这样来取消，但是这样做肯定是不对的
> 
> 比如我想在这个组件外面做一个按钮，点击一下全选，在点击一下全不选，我看了很久的文档目前好像是做不到，如果您有方法请告知一下，谢谢！

你自己控制 `checked-keys` 值就可以了

**Comment by Mylinaa** [comment]
> > > > QQ20231109-204705-HD.mp4
> > > > 这不是么
> > > 
> > > 
> > > 您好，您误解我的意思了，是这个不能手动取消掉 ![image](https://user-images.githubusercontent.com/82194403/281966933-6566e1d5-ce82-4cc9-b3a2-ab489390b1a6.png) 目前我想点击list取消上一个的状态，方法是用v-if这样来取消，但是这样做肯定是不对的
> > 
> > 
> > 比如我想在这个组件外面做一个按钮，点击一下全选，在点击一下全不选，我看了很久的文档目前好像是做不到，如果您有方法请告知一下，谢谢！
> 
> 你自己控制 `checked-keys` 值就可以了

多谢，谢谢提醒，已经实现了 
![image](https://github.com/tusen-ai/naive-ui/assets/82194403/6bad4c17-fa4a-44fc-932e-cfc8d72799e1)
