### ISSUE TITLE
输入框password开启show-password-on="mousedown | click"在edge下刚输入时会有两个眼睛按钮,chrome下正常

### ISSUE THREAD

**Issue by scp-66** [tusen-ai/naive-ui#5384]
### TuSimple/naive-ui version (版本)
2.35.0

### Vue version (Vue 版本)
3.2.37

### Browser and its version (浏览器及其版本)
Microsoft Edge(119.0.2151.58)

### System and its version (系统及其版本)
windows 11

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/input#password.vue

### Reappearance steps (重现步骤)
使用edge打开官方的样例，找到密码的自定义图标那个例子，那两个输入框都会这样

### Expected results (期望的结果)
和chome下一样，只有一个小小的眼睛

### Actual results (实际的结果)
出现了两只眼睛不符合交互

**Comment by jizai1125** [comment]
加个伪类
```css
input[type=password]::-ms-reveal {
    display: none;
}
```
https://learn.microsoft.com/en-us/microsoft-edge/web-platform/password-reveal
