### ISSUE TITLE
Checkbox Indeterminate state uncertain behaviour

### ISSUE THREAD

**Issue by francescovallone** [tusen-ai/naive-ui#5387]
### TuSimple/naive-ui version (版本)
2.35.0

### Vue version (Vue 版本)
3.4.0-alpha.1

### Browser and its version (浏览器及其版本)
Versione 119.0.1 (64 bit)

### System and its version (系统及其版本)
MacOS(14.0)

### Node version (Node 版本)
v20.6.1

### Reappearance link (重现链接)
https://www.naiveui.com/en-US/os-theme/components/checkbox

### Reappearance steps (重现步骤)
1. Change value to the checkbox;
2. Set it to indeterminate;
3. The value is now stuck to indeterminate;
4. Removing the indeterminate give back the previous value;

### Expected results (期望的结果)
I would expect the indeterminate "state" to be treated as a third possible value for the checkbox: [true, false, undefined]

1. Change the value to the checkbox;
2. Set it to indeterminate;
3. If I change value the indeterminate value is overwritten;

### Actual results (实际的结果)
The indeterminate "state" supress all the other values.

**Comment by OrbisK** [comment]
This behaviour is intended. If `:indeterminate="true"` it will override the value.
