### ISSUE TITLE
带图标的n-tag在n-space中无法垂直居中

### ISSUE THREAD

**Issue by majinkai** [tusen-ai/naive-ui#5392]
### TuSimple/naive-ui version (版本)
2.35.0

### Vue version (Vue 版本)
3.4.0-alpha.1

### Browser and its version (浏览器及其版本)
Chrome

### System and its version (系统及其版本)
MacOS

### Reappearance link (重现链接)
https://codesandbox.io/s/hungry-yonath-2hmjkl

### Reappearance steps (重现步骤)
参见示例

### Expected results (期望的结果)
无法垂直居中

### Actual results (实际的结果)
无法垂直居中

**Comment by jizai1125** [comment]
没设置 `vertical` 😓

**Comment by jizai1125** [comment]
`wrap-item` 设为 false

**Comment by majinkai** [comment]
> `wrap-item` 设为 false

解决了，感谢
