### ISSUE TITLE
n-progress组件进度条能否支持渐变色

### ISSUE THREAD

**Issue by Lee-shung** [tusen-ai/naive-ui#5393]
### This function solves the problem (这个功能解决的问题)
n-progress组件进度条能否支持渐变色，当前只能设置一个颜色
### Expected API (期望的 API)
可以在color属性上新增object类型，类似于{ from: 'fromColor', to: 'toColor' }

**Comment by jahnli** [comment]
https://github.com/tusen-ai/naive-ui/pull/4237

**Comment by jahnli** [comment]
duplicate https://github.com/tusen-ai/naive-ui/issues/3640
