### ISSUE TITLE
n-code 引入highlight高亮主题无效

### ISSUE THREAD

**Issue by rainbowder** [tusen-ai/naive-ui#5396]
### TuSimple/naive-ui version (版本)
2.35.0

### Vue version (Vue 版本)
3.4.0-alpha.1

### Browser and its version (浏览器及其版本)
Chrome 119.0.6045.160（正式版本）

### System and its version (系统及其版本)
win10

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/code

### Reappearance steps (重现步骤)
n-code组件在引入highlight的样式css后，高亮主题颜色未有变化，而组件本身缺少主题参数设置，造成n-code无法变换主题颜色

### Expected results (期望的结果)
1.希望添加组件主题参数，用于调整代码块组件的主题颜色
2.希望优化n-code组件，使highlight的样式引入能够有效。

### Actual results (实际的结果)
1.n-code组件在引入highlight的样式css后，高亮主题颜色未有变化
2.组件本身缺少主题参数设置，造成n-code无法变换主题颜色

**Comment by OrbisK** [comment]
I think you can just pass your own `hljs` instance as prop.

**Comment by OrbisK** [comment]
Please add a (not) working reproduction

**Comment by Sepush** [comment]
close as no reproduction. when you provide,feel free to reopen.
