### ISSUE TITLE
menu 菜单组件没有类似menu-item的子组件，以及没有路由变化change或者select之类的事件吗？

### ISSUE THREAD

**Issue by lq9958** [tusen-ai/naive-ui#5400]
### This function solves the problem (这个功能解决的问题)
可以自由的控制渲染菜单项，监听菜单变化
### Expected API (期望的 API)
```html
<n-menu @change="handleMenuChange">
  <n-menu-item>
       菜单项1
  </n-menu-item>
  <n-menu-item>
       菜单项2
  </n-menu-item>
</n-menu>
```

**Comment by jizai1125** [comment]
1. 没有 `menu-item` 子组件；
2. 监听菜单选中可以用 `on-update:value`

**Comment by lq9958** [comment]
@jizai1125 好的，谢谢，第一次接触这个库，不太熟悉😄

**Comment by lq9958** [comment]
@jizai1125 好的，谢谢，第一次接触这个库，不太熟悉😄
