### ISSUE TITLE
n-date-picker throws an error when its formatted-value property has an empty string value

### ISSUE THREAD

**Issue by sunxdtry** [tusen-ai/naive-ui#5401]
### TuSimple/naive-ui version (版本)
2.35.0

### Vue version (Vue 版本)
3.2.41

### Browser and its version (浏览器及其版本)
Chrome/119.0.0.0

### System and its version (系统及其版本)
MacOs(14.1.1)

### Reappearance link (重现链接)
https://codesandbox.io/p/sandbox/unruffled-danilo-dsth7z?file=%2Fsrc%2FDemo.vue%3A11%2C19

### Reappearance steps (重现步骤)
n-date-picker throws an error when its formatted-value property has an empty string value。

### Expected results (期望的结果)
formatted-value supports an empty string or undefined

### Actual results (实际的结果)
Invalid time value

### Remarks (补充说明)
The value initialized for business reasons may be an empty string or undefined

**Comment by jahnli** [comment]
You are advised to initialize the default value
