### ISSUE TITLE
popover 移动端弹窗超出屏幕

### ISSUE THREAD

**Issue by vual** [tusen-ai/naive-ui#5402]
### TuSimple/naive-ui version (版本)
2.35.0

### Vue version (Vue 版本)
3.2.47

### Browser and its version (浏览器及其版本)
edge最新版

### System and its version (系统及其版本)
win10

### Node version (Node 版本)
20.9.0

### Reappearance steps (重现步骤)
![image](https://github.com/tusen-ai/naive-ui/assets/25891219/3915e85b-efd6-44d0-b6ed-e8e5baab7277)

### Expected results (期望的结果)
自动调整位置

### Actual results (实际的结果)
![image](https://github.com/tusen-ai/naive-ui/assets/25891219/d7772c49-a0d3-4f2c-8f78-b70df7ee27e2)

**Comment by Volankey** [comment]
看起来这个左右做调整都是有可能会超出这个屏幕，毕竟内容区域太大了，你应该去设置popover的max-width

**Comment by hyp530** [comment]
> 看起来这个左右做调整都是有可能会超出这个屏幕，毕竟内容区域太大了，你应该去设置popover的max-width

我觉得这个是需要fix的。在手机屏幕下，PopOver很容易都会超出。能不能改为默认不超出屏幕？

**Comment by mercury233** [comment]
https://www.naiveui.com/zh-CN/os-theme/components/popover

官网的demo本身就有这个问题，文本也不算特别长，以下是我这里电脑上宽度较窄时和手机上的效果

<img width="506" height="595" alt="Image" src="https://github.com/user-attachments/assets/0b22713e-5e52-4b3a-bf8c-4f3cdb98792d" />

<img width="468" height="267" alt="Image" src="https://github.com/user-attachments/assets/72f90026-8853-40d6-a7a3-def7d506ca38" />
