### ISSUE TITLE
[DataTable] Reorder columns and rows 

### ISSUE THREAD

**Issue by vitjaz** [tusen-ai/naive-ui#5404]
### This function solves the problem (这个功能解决的问题)
This solve case when we want to dynamically reorder columns or rows in dataTable.
### Expected API (期望的 API)
Expected API maybe like in PrimeVue

Link: https://primevue.org/datatable/#reorder

**Comment by jahnli** [comment]
duplicate https://github.com/tusen-ai/naive-ui/issues/5069
