### ISSUE TITLE
textarea with config inline-theme-disabled not show scrollbar

### ISSUE THREAD

**Issue by ggymm** [tusen-ai/naive-ui#5418]
### TuSimple/naive-ui version (版本)
2.35.0

### Vue version (Vue 版本)
3.4.0-alpha.3

### Browser and its version (浏览器及其版本)
chrome(118.0.5993.71)

### System and its version (系统及其版本)
windows11

### Reappearance link (重现链接)
https://codesandbox.io/p/sandbox/serene-wildflower-dpxkyg?file=%2Fsrc%2FApp.vue

### Reappearance steps (重现步骤)
Enter many lines of content in the textarea until it exceeds the maximum height for scrolling

### Expected results (期望的结果)
There is a scrollbar

### Actual results (实际的结果)
No scrollbar

**Comment by jizai1125** [comment]
You can wrap the scrollbar component to fix this issue temporarily.
```vue
<template>
  <!-- inline-theme-disabled -->
  <n-scrollbar>
     <n-input type="textarea" />
  </n-scrollbar>
</template>
```
Similar to issue #4570, this arises from addressing style problems in #3238. The separation of the y-axis scrollbar makes some theme CSS variables inaccessible.
