### ISSUE TITLE
`NButton` is not compatible with `Nuxt`,when doing `navigateTo` and `error` page catching

### ISSUE THREAD

**Issue by rockfang** [tusen-ai/naive-ui#5430]
### TuSimple/naive-ui version (版本)
2.35.0

### Vue version (Vue 版本)
3.3.10

### Browser and its version (浏览器及其版本)
115.0.5790.99

### System and its version (系统及其版本)
Win 10(19043.1348)

### Node version (Node 版本)
v18.18.0

### Reappearance link (重现链接)
https://stackblitz.com/edit/nuxt-starter-kpbeu1?file=pages%2Findex.vue

### Reappearance steps (重现步骤)
1. config naiveUI in `Nuxt` project
2. create a page `error.vue` as global error catch page
3. create a global middleware like `auth.global.ts` in middleware directory
4. `throw createError` in the middleware file
5. use `NButton` to trigger route change and trigger the route middleware
6. check whether the error is caught and the `error` page show

### Expected results (期望的结果)
hope click trigger from NButton could lead to  Error page in `Nuxt`

### Actual results (实际的结果)
seems like the `navigateTo` from NButton click event can't be caught

### Remarks (补充说明)
I post one issue in Nuxt.
https://github.com/nuxt/nuxt/issues/24601

**Comment by GoMateoGo** [comment]
Hello, can you tell me how you automatically import under nuxt? The official examples provided cannot be used

**Comment by 07akioni** [comment]
Can not reproduce it in my local repo

Maybe have a try at newer nuxt and naive-ui nuxt guide https://www.naiveui.com/zh-CN/os-theme/docs/nuxtjs

![CleanShot 2024-05-05 at 22 43 50](https://github.com/tusen-ai/naive-ui/assets/18677354/040d435b-6b3e-45be-9cff-7c2604933f49)

**Comment by 07akioni** [comment]
All of them only log error without any interaction.
