### ISSUE TITLE
cascader级联选择width调整方案

### ISSUE THREAD

**Issue by incitygod** [tusen-ai/naive-ui#5431]
### This function solves the problem (这个功能解决的问题)
 <n-cascader :theme-overrides="{columnWidth:'200px'}"/> 泪崩两个小时
### Expected API (期望的 API)
 <n-cascader :theme-overrides="{columnWidth:'200px'}"/>泪崩两个小时

**Comment by incitygod** [comment]
<n-cascader  :theme-overrides="{columnWidth:'200px'}" />

**Comment by incitygod** [comment]
`   <n-cascader  :theme-overrides="{columnWidth:'200px'}" />`

**Comment by jizai1125** [comment]
有啥问题么？

**Comment by incitygod** [comment]
> 有啥问题么？

在官方文档上没看到有调整宽度的属性，看了两个小时的源码才找到处理宽度的方案

**Comment by jizai1125** [comment]
> > 有啥问题么？
> 
> 在官方文档上没看到有调整宽度的属性，看了两个小时的源码才找到处理宽度的方案

调样式的话可以先看 [调整主题](https://www.naiveui.com/zh-CN/os-theme/docs/customize-theme) 有没有暴露出来

**Comment by incitygod** [comment]
> > > 有啥问题么？
> > 
> > 
> > 在官方文档上没看到有调整宽度的属性，看了两个小时的源码才找到处理宽度的方案
> 
> 调样式的话可以先看[调整主题](https://www.naiveui.com/zh-CN/os-theme/docs/customize-theme)有没有暴露出来，有暴露出变量的话可以全局覆盖或者在组件上覆盖`theme-overrides`

<n-cascader  :theme-overrides="{columnWidth:'200px'}" /> 我现在采用的就是咋组件上覆盖的方案，只需要修改当前组件，不影响其他组件

**Comment by Sepush** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/39197136/a0c010b9-f7f0-40f0-a525-86901714cccb)

**Comment by mqnu00** [comment]
> > 有啥问题么？
> 
> 在官方文档上没看到有调整宽度的属性，看了两个小时的源码才找到处理宽度的方案

我也是😂
