### ISSUE TITLE
能否把anchor的activeHref属性暴露出来

### ISSUE THREAD

**Issue by blackawn** [tusen-ai/naive-ui#5432]
### This function solves the problem (这个功能解决的问题)
在目录比较长的时候有滚动条，方便监听activeHref值的变动从而使用scrollIntoView方法来滚动聚焦当前的link
### Expected API (期望的 API)
// src/AnchorAdapter.tsx
...

return {
  scrollTo (href: string) {
    anchorRef.value?.setActiveHref(href)
  },
   anchorRef 
}

**Comment by jahnli** [comment]
是否可以提供个示例

**Comment by jahnli** [comment]
I'm not sure that makes sense.

What kind of api do you want?
