### ISSUE TITLE
表格数据如何获取排序后的数据，如何对列进行拖拽

### ISSUE THREAD

**Issue by 0Jarod0** [tusen-ai/naive-ui#5434]
### TuSimple/naive-ui version (版本)
2.35.0

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Chrome(118.0.5993.89)

### System and its version (系统及其版本)
windows11

### Node version (Node 版本)
v20.9.0

### Reappearance link (重现链接)
https://www.naiveui.com/

### Reappearance steps (重现步骤)
表格数据如何获取排序后的数据，如何对列进行拖拽

### Expected results (期望的结果)
获取排序后的数据，对列进行拖拽

### Actual results (实际的结果)
无法获取排序后的数据，列无法进行拖拽

**Comment by codeDevStory** [comment]
对列拖拽排序？
一般不都是对行拖拽排序吗

**Comment by SuperManito** [comment]
列拖拽排序早就在第三方Admin项目中实现了，多翻一翻 社区精选资源

**Comment by jahnli** [comment]
duplicate https://github.com/tusen-ai/naive-ui/issues/5069
