### ISSUE TITLE
Popup components add ESC Keyboard operation

### ISSUE THREAD

**Issue by XieZongChen** [tusen-ai/naive-ui#544]
### This function solves the problem (这个功能解决的问题)
Popup components add ESC Keyboard operation
### Expected API (期望的 API)
Popup components add ESC Keyboard operation

**Comment by 002269** [comment]
Popconfirm 也一样

**Comment by DannyFeliz** [comment]
This will be a great addition, right now I'm doing this manually all the time

**Comment by 07akioni** [comment]
Dialog & Modal already support it.

Popconfirm wip.
