### ISSUE TITLE
套了一层n-spin后不能随父级改变大小

### ISSUE THREAD

**Issue by zengyun261** [tusen-ai/naive-ui#5440]
### This function solves the problem (这个功能解决的问题)
因为n-spin内部还套了一层.n-spin-content的div, 导致不能使用类似的style被动设置大小: height: 100%, flex:1...
### Expected API (期望的 API)
v-loading

**Comment by sky124380729** [comment]
同样的问题

**Comment by jahnli** [comment]
content-style
