### ISSUE TITLE
多选上传bug

### ISSUE THREAD

**Issue by pinecone-squirrel** [tusen-ai/naive-ui#5443]
### TuSimple/naive-ui version (版本)
2.35.0

### Vue version (Vue 版本)
3.3.10

### Browser and its version (浏览器及其版本)
119.0.6045.200

### System and its version (系统及其版本)
win10

### Node version (Node 版本)
20

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/upload#API

### Reappearance steps (重现步骤)
上传组件开启多选，然后配置自定义上传方法

### Expected results (期望的结果)
我希望一次吧我选择的所有文件返回，而不是一个一个返回
是我使用的姿势不对吗？

### Actual results (实际的结果)
实际上是一个一个返回

### Remarks (补充说明)
所有组件库上传组件都是最难用的
我希望上传组件可自定义程度高一点
我都不懂为什么所有组件库上传都有自动上传选项？
你们上传都不做验证的吗？

**Comment by jahnli** [comment]
https://github.com/tusen-ai/naive-ui/issues/5468
