### ISSUE TITLE
n-select 中的render-label渲染的label，filterable无法精准过滤

### ISSUE THREAD

**Issue by Luckyre** [tusen-ai/naive-ui#5446]
### TuSimple/naive-ui version (版本)
2.33.4

### Vue version (Vue 版本)
3.2.31

### Browser and its version (浏览器及其版本)
Google Chrome 119.0.6045.200

### System and its version (系统及其版本)
window 10 

### Node version (Node 版本)
16.14.0

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/light/components/select

### Reappearance steps (重现步骤)
render-label 设置了n-select下拉选择项的code与value重组字段，例如（${code}-${name}），设置select 中的filterable =true,但是点击下拉进行code或者name值模糊查询

### Expected results (期望的结果)
可以通过name值也能filter过滤查询

### Actual results (实际的结果)
只能通过code值过滤查询，无法通过name值过滤下拉列表

**Comment by jizai1125** [comment]
指定 `label-field` 或者设置 `filter` 函数

**Comment by Luckyre** [comment]
> 他这个只能通过你绑定的那个label过滤，不能根据value过滤 自己重新写一下过滤方法吧，暂时


那还不如重组一个字段组合code,value ,我本想通过render-label动态组装

**Comment by Luckyre** [comment]
> 指定 `label-field` 或者设置 `filter` 函数

label-field只接收string, 我本想通过render-label动态组装

**Comment by jizai1125** [comment]
> > 指定 `label-field` 或者设置 `filter` 函数
> 
> label-field只接收string, 我本想通过render-label动态组装

你要是要 render-label 的结果进行过滤么，这样的话只能自己定义过滤方法了

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
