### ISSUE TITLE
n-select提供 onInputBlur,separators参数。

### ISSUE THREAD

**Issue by McPorkChop** [tusen-ai/naive-ui#5456]
### This function solves the problem (这个功能解决的问题)
在 tag 模式下，必须要回车才能创建tag，相对影响体验。input-props中的 onBlur 也会被 select 复写。
### Expected API (期望的 API)
```
<NSelect>
  v-model:value={value}
  onInputBlur={(target)=>{...}}
  seperators={[';',',']}
/>
```

**Comment by Sepush** [comment]
for seperators tack in https://github.com/tusen-ai/naive-ui/issues/2368

**Comment by jahnli** [comment]
duplicate
