### ISSUE TITLE
TreeSelect点击左侧展开箭头会自动选中当前节点

### ISSUE THREAD

**Issue by AcTeemo** [tusen-ai/naive-ui#5462]
### TuSimple/naive-ui version (版本)
2.35.0

### Vue version (Vue 版本)
3.3.11

### Browser and its version (浏览器及其版本)
Chrome 117

### System and its version (系统及其版本)
Windows11

### Node version (Node 版本)
18.18

### Reappearance link (重现链接)
https://codesandbox.io/p/sandbox/fragrant-platform-k399jj?file=%2Fsrc%2FDemo.vue%3A5%2C14

### Reappearance steps (重现步骤)
点击展开箭头，会自动选中当前节点

### Expected results (期望的结果)
不应该选中或取消当前节点

### Actual results (实际的结果)
会选中或取消当前节点

### Remarks (补充说明)
目测是seemly(happensIn方法) 0.3.7更新导致的问题，tree也有相关问题，不排除其他组件会有类似问题

**Comment by slyedoc** [comment]
Ran into same thing, though in NTreeSelect

**Comment by jahnli** [comment]
The author has fixed, reinstall try

**Comment by AcTeemo** [comment]
最新版本已经，已关闭
