### ISSUE TITLE
n-input-number 当 启用 precision 时 v-model绑定值变化必须要失去焦点

### ISSUE THREAD

**Issue by GoMateoGo** [tusen-ai/naive-ui#5463]
### TuSimple/naive-ui version (版本)
2.35.0

### Vue version (Vue 版本)
3.4.0-beta.1

### Browser and its version (浏览器及其版本)
Microsoft Edge 版本 120.0.2210.61 (正式版本) (64 位)

### System and its version (系统及其版本)
WIN11 22621.2715

### Reappearance link (重现链接)
https://codepen.io/pen/  不会使用.

### Reappearance steps (重现步骤)
      <n-input-number v-model:value="aaa"
                      :precision="0"
                      :min="1"
                      placeholder="数量"
                      @onchange:value="aaa"
      />
      {{aaa}}

const aaa = ref(0) 响应变量

watch(aaa,(newValue)=>{
  console.log(newValue) //并没有打印日志
})
1. 改变aaa的值,并没有打印变量,除非让当前input失去光标
2. 使用input  -  来修改值时, 会产生打印日志 并且模板内的aaa变量也会发生改变
3. 取消precision时候,  不需要失去光标

### Expected results (期望的结果)
开启precision 时, 当绑定值改变时,应该也随之改变

### Actual results (实际的结果)
1. 改变aaa的值,并没有打印变量,除非让当前input失去光标
2. 使用input  -  来修改值时, 会产生打印日志 并且模板内的aaa变量也会发生改变
3. 取消precision时候,  不需要失去光标

**Comment by OrbisK** [comment]
This is intended.

![image](https://github.com/tusen-ai/naive-ui/assets/37191683/46786377-15ee-4ff1-969b-6dff84eaf3b2)


FYI: pls dont use any tsx events like `on-update...` (or whatever `@onchange:value="aaa"` is) without tsx (see [here](https://www.naiveui.com/en-US/os-theme/docs/common-issues))
