### ISSUE TITLE
Offer a way to batch upload with n-upload

### ISSUE THREAD

**Issue by ClSlaid** [tusen-ai/naive-ui#5468]
### This function solves the problem (这个功能解决的问题)
I noticed that `n-upload`'s submit API will only put files to backend one by one, however, I do hope that all files could be put in one single multipart http request.

This will ease much of the pain to implement file uploading backend. I need to track uploaded files in groups and I find it hateful to implement those *start*, *continue* and *end* token like or else stateful handles.

Since we are using web forms, transfer those files in a single HTTP request directly. This will ease the pain implementing the backend.

### Expected API (期望的 API)
Adding a batch option to your dearly n-upload component.
```html
<n-upload batch></n-upload>
```
When uploading files, the http request would look like:
```HTTP
POST /upload HTTP/1.1
Host: example.com
Content-Type: multipart/form-data; boundary=1145141919810

--1145141919810
Content-Disposition: form-data; name="file1"; filename="example1.txt"
Content-Type: text/plain

[Contents of file1.txt]

--1145141919810
Content-Disposition: form-data; name="file2"; filename="example2.txt"
Content-Type: text/plain

[Contents of file2.txt]

--1145141919810--
```

### APIs that may be affected:

- custon-request
n-upload now offers a custom-request argument for users to configure their way of request. Sadly,  the argument only specifies for a single file. This might request some changes.
- auto-upload
n-upload will upload single files automatically, by default. The batch mode will implicitly introduce a batch semantic. This may make users think they've uploaded one by one but still in the same batch, meanwhile the stateless backend got multiple requests and considers it as multiple batch uploading requests.
So batch mode is not really compatible with automatic upload. If you do have better ideas please let me know.

### Issue related:
#5443

**Comment by 07akioni** [comment]
I think I won't implement it since it may influence interaction a lot for example: cancellation, percentage display. It's rather complex to implement it.

However PR is welcomed.

**Comment by ClSlaid** [comment]
Thanks for your reply.

I've come up with a way to bypass this. Still learning Vue, so sadly I can give no further contributions.

**Comment by 07akioni** [comment]
I think the main work is to refactor `submit` implementation so that multiple upload item can subscribe to one XHR.
