### ISSUE TITLE
希望能给Tree和TreeSelect组件的树节点Switcher区域加一个hover背景效果

### ISSUE THREAD

**Issue by SuperManito** [tusen-ai/naive-ui#5473]
### This function solves the problem (这个功能解决的问题)
优化折叠/展开树节点的交互
### Expected API (期望的 API)
在没有被设置 `expand-on-click` 和 `disabled` 的树节点中应用该效果

**Comment by XueHua-s** [comment]
你可以自己写组件样式穿透

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
