### ISSUE TITLE
In the collapse component the click area is smaller than the visible and full size of the item

### ISSUE THREAD

**Issue by WCPatrik** [tusen-ai/naive-ui#5482]
### TuSimple/naive-ui version (版本)
2.36.0

### Vue version (Vue 版本)
3.4.0-beta.4

### Browser and its version (浏览器及其版本)
Chrome(120.0.6099.110)

### System and its version (系统及其版本)
windows 10

### Reappearance link (重现链接)
https://codesandbox.io/p/sandbox/floral-wildflower-690do6

### Reappearance steps (重现步骤)
Click near the border of the collapse item

### Expected results (期望的结果)
It is expected to open the collapse item

### Actual results (实际的结果)
It shows the pointer that change for the click but it dosen't open the collapse item

**Comment by thibodeauxjl** [comment]
This appears to be a styling issue. When looking at the code sandbox, it appears the click event is set on 
`<div class="n-collapse-item__header-main"></div>` 
and not on the 
`<div class="n-collapse-item__header"></div>`

You could attempt to fix this by adding a style of `--n-title-padding: 0` to the collapse component then add that padding to the `<template #header>
  <div style="padding-top: ** Padding Here **"></div>
</template>`

I haven't attempted it, but that would be my approach.

**Comment by OrbisK** [comment]
The `cursor: pointer` was on the wrong element. The space above and below the header is not inteded to be clickable.

**Comment by WCPatrik** [comment]
wouldn't be better and more user friendly to have it all clickable though?

**Comment by OrbisK** [comment]
Well depends. I think you can open a feature request for that. Or a feature request for more theme overrides to controll the clickable area.
