### ISSUE TITLE
useThemeVars 在drawer 中无法使用v-bind 绑定

### ISSUE THREAD

**Issue by baiyijun** [tusen-ai/naive-ui#5488]
### TuSimple/naive-ui version (版本)
2.35.0

### Vue version (Vue 版本)
3.3.13

### Browser and its version (浏览器及其版本)
edge 120

### System and its version (系统及其版本)
win11

### Node version (Node 版本)
16

### Reappearance link (重现链接)
https://codesandbox.io/p/sandbox/trusting-kilby-4wmjl5?file=%2Fsrc%2FDemo.vue%3A38%2C37&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqduz7dw00063j6garr7q810%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqduz7dw00023j6geh7wk1wt%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqduz7dw00033j6gq64ddtjr%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqduz7dw00053j6g7g8k74a7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqduz7dw00023j6geh7wk1wt%2522%253A%257B%2522id%2522%253A%2522clqduz7dw00023j6geh7wk1wt%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqdvj9tq002y3j6f87maddkt%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A38%252C%2522startColumn%2522%253A37%252C%2522endLineNumber%2522%253A38%252C%2522endColumn%2522%253A37%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FDemo.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqdvj9tq002y3j6f87maddkt%2522%257D%252C%2522clqduz7dw00053j6g7g8k74a7%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqduz7dw00043j6gt32ga675%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqduz7dw00053j6g7g8k74a7%2522%252C%2522activeTabId%2522%253A%2522clqduz7dw00043j6gt32ga675%2522%257D%252C%2522clqduz7dw00033j6gq64ddtjr%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqduz7dw00033j6gq64ddtjr%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Reappearance steps (重现步骤)
在drawer中定义两个div, 一个div使用class : hhh-item  一个使用class: hhh-item2.
.hhh-item: {background-color: v-bind("themeVars.primaryColor")}  
.hhh-item2: {background-color: red)}
这时候, class为hhh-item的不生效  class为hhh-item2的正常显示 

### Expected results (期望的结果)
drawer 中可以正常使用 v-bind

### Actual results (实际的结果)
drawer 中可以无法正常使用 v-bind

**Comment by jizai1125** [comment]
应该是因为 Drawer，Modal 这种组件 DOM 都会脱离挂到父组件之外造成的，可以用 [n-el](https://www.naiveui.com/zh-CN/os-theme/components/element) 组件

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
