### ISSUE TITLE
在wujie微前端框架中，使用了naive-ui的子应用，n-select开启filterable后，中文输入报错问题

### ISSUE THREAD

**Issue by ashuicoder** [tusen-ai/naive-ui#5491]
### TuSimple/naive-ui version (版本)
2.36.0

### Vue version (Vue 版本)
3.3.13

### Browser and its version (浏览器及其版本)
Chrome(120)

### System and its version (系统及其版本)
windows11

### Node version (Node 版本)
v20.10.0

### Reappearance link (重现链接)
https://github.com/Tencent/wujie/issues/543

### Reappearance steps (重现步骤)
经调试是naiveui Select.js中handlePatternInput方法获取e.target时，e.target变成了wujie-app.wujie_iframe，导致没取到value。

如果是英文输入或粘贴内容进去时，e.target则为input.n-base-selection-input，此时可以取到e.target.value。

### Expected results (期望的结果)
希望修复一下

### Actual results (实际的结果)
确实已发生

**Comment by rickx81** [comment]
用这个插件 [EventTargetPlugin ](https://wujie-polyfill.github.io/doc/plugins/eventTarget.html)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by llifangyin** [comment]
good 前人栽树，后人乘凉

**Comment by llifangyin** [comment]
新问题，使用tag multiple 仍有上述问题
