### ISSUE TITLE
虚拟列表组件的scrollbar-props传入{  xScrollable: true }开启横向滚动条不生效

### ISSUE THREAD

**Issue by gpwhaha** [tusen-ai/naive-ui#5497]
### TuSimple/naive-ui version (版本)
2.36.0

### Vue version (Vue 版本)
3.4.0-beta.4

### Browser and its version (浏览器及其版本)
谷歌浏览器120.0.6099.71（正式版本） （64 位）

### System and its version (系统及其版本)
windows

### Reappearance link (重现链接)
https://codesandbox.io/p/sandbox/quirky-glade-nw8znq?file=%2Fsrc%2FDemo.vue%3A8%2C23-8%2C61

### Reappearance steps (重现步骤)
<n-virtual-list
    style="max-height: 240px; width: 200px"
    :item-size="42"
    :items="items"
    item-resizable
    class="scroll"
    :scrollbar-props="{ trigger: 'none', xScrollable: true }"
    padding-bottom="10"
  >
    <template #default="{ item, index }">
      <div :key="item.key" class="item" style="width: 500px; ">
        <img class="avatar" :src="item.avatar" alt="" />
        <span> {{ index }} - {{ item.message }}</span>
      </div>
    </template>
  </n-virtual-list>

### Expected results (期望的结果)
修复传入参数能够正确展示横向滚动条

### Actual results (实际的结果)
虚拟列表组件的scrollbar-props传入{  xScrollable: true }开启横向滚动条不生效

**Comment by jizai1125** [comment]
items-style="width: 300px;"
