### ISSUE TITLE
滚动条支持设置宽度

### ISSUE THREAD

**Issue by xhlsrj** [tusen-ai/naive-ui#5498]
### This function solves the problem (这个功能解决的问题)
5px 的宽度对一些用户点击拖拽时不是很友好，希望能设置宽度。
### Expected API (期望的 API)
size 属性容易让人误解，希望对于宽度属性能有更高辨识度的命名。

**Comment by jahnli** [comment]
通过 `theme` 可以设置宽度

**Comment by xhlsrj** [comment]
> 通过 `theme` 可以设置宽度

可以啦，谢谢。
