### ISSUE TITLE
n-select 可以增加下拉菜单的头部插槽吗

### ISSUE THREAD

**Issue by firmianaQ** [tusen-ai/naive-ui#5505]
### This function solves the problem (这个功能解决的问题)
可以设置下拉菜单的头部插槽,组件更灵活
### Expected API (期望的 API)
类似n-popselect的插槽,https://www.naiveui.com/zh-CN/os-theme/components/popselect#slot.vue

**Comment by jahnli** [comment]
https://github.com/tusen-ai/naive-ui/pull/5449

等待下次发布
