### ISSUE TITLE
Add Context Menu

### ISSUE THREAD

**Issue by shuitai** [tusen-ai/naive-ui#5507]
### This function solves the problem (这个功能解决的问题)
Add Context Menu like https://www.radix-ui.com/themes/docs/components/context-menu
### Expected API (期望的 API)
https://www.radix-ui.com/themes/docs/components/context-menu

**Comment by OrbisK** [comment]
I think as workaround you can use dropdown like: https://www.naiveui.com/en-US/os-theme/components/data-table#context-menu.vue

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
