### ISSUE TITLE
BUG! n-upload accept=".png,.jpeg,.jpg" 选择图片之后 input是空的，去掉accept则可以成功选择列出文件

### ISSUE THREAD

**Issue by gowy222** [tusen-ai/naive-ui#5508]
### TuSimple/naive-ui version (版本)
2.36.0

### Vue version (Vue 版本)
3.3.13

### Browser and its version (浏览器及其版本)
最新

### System and its version (系统及其版本)
win11

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/dark/components/upload

### Reappearance steps (重现步骤)
<template>
  <n-upload
accept=".png,.jpeg,.jpg"
  >
    <n-button>上传文件</n-button>
  </n-upload>
</template>

### Expected results (期望的结果)
设置了accept 为何可以成功调用win的选择文件框 且过滤文件类型，选中文件之后，n-upload得不到任何文件?

### Actual results (实际的结果)
accept 生效

**Comment by gowy222** [comment]
@update:file-list="upload_handleFileListChange"
    :show-file-list="false"
    :file-list="array_selected_files"
upload_handleFileListChange(in_data) =>in_data = [{}]  length=1 但是是空的

**Comment by jizai1125** [comment]
> accept="image/png,image/jpeg" accept=".png,.jpeg,.jpg" 都不行
> 
> ```
> @update:file-list="upload_handleFileListChange"
>     :show-file-list="false"
>     :file-list="array_selected_files"
> ```
> 
> upload_handleFileListChange(in_data) =>in_data = [{}] length=1 但是是空的

`file-list` 是受控的，单独设置将由你传入的值决定，你要双向绑定

**Comment by OrbisK** [comment]
Hey, so that we can work on this better and faster it would help a lot to have a complete reproduction. Just create a code sandbox with the uplaod as you use it and describe step by step what you did and when and how the error occurs!
