### ISSUE TITLE
打包后的代码在head中有大量style，非常影响SEO优化

### ISSUE THREAD

**Issue by zhonganeng** [tusen-ai/naive-ui#5515]
### TuSimple/naive-ui version (版本)
2.35.0

### Vue version (Vue 版本)
3.3.10

### Browser and its version (浏览器及其版本)
1

### System and its version (系统及其版本)
1

### Reappearance link (重现链接)
https://github.com/tusen-ai/naive-ui/issues/2371

### Reappearance steps (重现步骤)
1

### Expected results (期望的结果)
https://baidu.com

### Actual results (实际的结果)
https://baidu.com

**Comment by jahnli** [comment]
is `inline-theme-disabled` ?
