### ISSUE TITLE
expand 使用这个属性内部嵌套表格，点击一个expand按钮其他的会联动一起展开

### ISSUE THREAD

**Issue by tfish-oh** [tusen-ai/naive-ui#5516]
### TuSimple/naive-ui version (版本)
2.35.0

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
谷歌119

### System and its version (系统及其版本)
window10

### Node version (Node 版本)
18.17.1

### Reappearance link (重现链接)
https://codepen.io/pen/tour/welcome/start

### Reappearance steps (重现步骤)
直接使用就是这样的

### Expected results (期望的结果)
希望每行expand按钮各种自己没有关联

### Actual results (实际的结果)
每一行的expand没有关联各自展示各自一行的内容

### Remarks (补充说明)

![image](https://github.com/tusen-ai/naive-ui/assets/16274637/d797511f-1ed8-4509-a9cc-723a83404d68)

**Comment by 1544039017** [comment]
我也遇到了 看官网例子没问题 我试了半天还是不行

**Comment by flyzss** [comment]
加上这个:row-key="(row) => row.id",保证每行id唯一.

**Comment by FLYYZJ** [comment]
> 加上这个:row-key="(row) => row.id",保证每行id唯一.

正解，谢谢

**Comment by jahnli** [comment]
https://github.com/tusen-ai/naive-ui/issues/5516#issuecomment-2162504652  👍
