### ISSUE TITLE
NPopover无法触发ClickOutside回调

### ISSUE THREAD

**Issue by evelynn996** [tusen-ai/naive-ui#5524]
### TuSimple/naive-ui version (版本)
2.36.0

### Vue version (Vue 版本)
3.3.4

### Browser and its version (浏览器及其版本)
Chrome(120.0.6099.130)

### System and its version (系统及其版本)
Win10

### Reappearance link (重现链接)
https://codesandbox.io/p/sandbox/summer-http-32pd8v

### Reappearance steps (重现步骤)
 Npopover 设置触发方式为手动  ： trigger="manual" ， 
添加上@update:show="handleUpdateShow"和 @on-clickoutside="handle" 

### Expected results (期望的结果)
用户点击Popover以外的界面，可以触发clickOutside

### Actual results (实际的结果)
没有触发clickOutside

**Comment by jahnli** [comment]
`@clickoutside="handle"`

**Comment by evelynn996** [comment]
> `@clickoutside="handle"`

@jahnli  感谢！没想到是如此愚蠢的问题，哈哈，我这个后端仔确实没注意@on前缀这个东西
