### ISSUE TITLE
PC端px单位转换vw单位不起作用

### ISSUE THREAD

**Issue by Aristodemu** [tusen-ai/naive-ui#5525]
### TuSimple/naive-ui version (版本)
2.36.0

### Vue version (Vue 版本)
3.4.3

### Browser and its version (浏览器及其版本)
Chrome(89.0.4389.128)

### System and its version (系统及其版本)
MacOS(11.2.3)

### Reappearance link (重现链接)
暂无

### Reappearance steps (重现步骤)
```js
vite.config.js
postcss: {
      plugins: [
        postcsspxtoviewport8plugin({
          unitToConvert: "px",
          viewportWidth: (file) => {
            let num = 1920
            if (file.indexOf("m_") !== -1) {
              num = 375
            }
            return num
          },
          unitPrecision: 5, // 单位转换后保留的精度
          propList: ["*"], // 能转化为vw的属性列表
          viewportUnit: "vw", // 希望使用的视口单位
          fontViewportUnit: "vw", // 字体使用的视口单位
          selectorBlackList: [], // 需要忽略的CSS选择器，不会转为视口单位，使用原有的px等单位。
          minPixelValue: 0, // 设置最小的转换数值，如果为1的话，只有大于1的值会被转换
          mediaQuery: true, // 媒体查询里的单位是否需要转换单位
          replace: true, //  是否直接更换属性值，而不添加备用属性
          // exclude: [/node_modules/], // 忽略某些文件夹下的文件或特定文件，例如 'node_modules' 下的文件
          include: [], // 如果设置了include，那将只有匹配到的文件才会被转换
          landscape: false, // 是否添加根据 landscapeWidth 生成的媒体查询条件 @media (orientation: landscape)
          landscapeUnit: "vw", // 横屏时使用的单位
          landscapeWidth: 1024 // 横屏时使用的视口宽度
        })
      ]
    }
```
### Expected results (期望的结果)
想要通过postcss-px-to-viewport-8-plugin插件   对项目进行自适应

### Actual results (实际的结果)
配置后   NaiveUI  组件样式单位px没有转成vw

**Comment by WatcherStar** [comment]
配置有问题吧，把include去掉试试

**Comment by Aristodemu** [comment]
> 配置有问题吧，把include去掉试试

不行，如果是使用ElementPlus像这样配置就转换了，NaiveUI就是不行

**Comment by WatcherStar** [comment]
> > 配置有问题吧，把include去掉试试
> 
> 不行，如果是使用ElementPlus像这样配置就转换了，NaiveUI就是不行

这样啊，你可以换成postcss-px-to-viewport插件试试，我的是可以转换成功的
![Snipaste_2024-01-05_09-22-10](https://github.com/tusen-ai/naive-ui/assets/52285100/86e7cf79-9c59-4542-accc-2551f0b16e79)

**Comment by WatcherStar** [comment]
试了一下确实不可以，因为它是属于行内style的px这个插件是转换不了的，可以用postcss-style-px-to-viewport转换行内样式或者其他行内样式解决方案

**Comment by Aristodemu** [comment]
好的，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tusen-ai/naive-ui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月5日(星期五) 上午9:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tusen-ai/naive-ui] PC端px单位转换vw单位不起作用 (Issue #5525)





   
配置有问题吧，把include去掉试试
  
不行，如果是使用ElementPlus像这样配置就转换了，NaiveUI就是不行
  
这样啊，你可以换成postcss-px-to-viewport插件试试，我的是可以转换成功的
 Snipaste_2024-01-05_09-22-10.png (view on web)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
