### ISSUE TITLE
h(NSelect,{},null);这种写法编辑器会报错

### ISSUE THREAD

**Issue by xuchenxi12138** [tusen-ai/naive-ui#5531]
### TuSimple/naive-ui version (版本)
2.36.0

### Vue version (Vue 版本)
3.4.3

### Browser and its version (浏览器及其版本)
Chrome（80.0.4839.128）

### System and its version (系统及其版本)
windows11

### Reappearance link (重现链接)
https://github.com/xuchenxi12138/issue-bugs-for-open-project.git

### Reappearance steps (重现步骤)
h函数渲染NSelect时，如果children为null，vscode,webstorm都会报错props

h(NSelect,{},null);
这种写法编辑器会报错;
h(NSelect,{},{});
这种不会。

git clone https://github.com/xuchenxi12138/issue-bugs-for-open-project.git
cd issue-bugs-for-open-project
cd naive-ui-select-h-latest-version
npm install
npm run dev

### Expected results (期望的结果)
非必须修复

### Actual results (实际的结果)
非必须修复

**Comment by jahnli** [comment]
`h(NSelect,{options:[]});`
