### ISSUE TITLE
clearable select: clicking the clear button will incorrectly open the drop-down panel

### ISSUE THREAD

**Issue by duanmw** [tusen-ai/naive-ui#5532]
### TuSimple/naive-ui version (版本)
2.36.0

### Vue version (Vue 版本)
3.4.4

### Browser and its version (浏览器及其版本)
120.0.6099.130

### System and its version (系统及其版本)
windows10

### Node version (Node 版本)
18

### Reappearance link (重现链接)
https://codesandbox.io/s/gsnlq2

### Reappearance steps (重现步骤)
Select the value and click the clear button

### Expected results (期望的结果)
Clear the selected value, no further action

### Actual results (实际的结果)
Clear the selected value, the drop-down panel is opened

### Remarks (补充说明)
My previous version 2.34.4 did not have this problem(https://codesandbox.io/p/sandbox/affectionate-dew-2tmvjw?file=%2Fpackage.json), but I found it when I upgraded to the latest version 2.36.

**Comment by jahnli** [comment]
![chrome_zdKJeft3uf](https://github.com/tusen-ai/naive-ui/assets/20943608/486dfa9e-e6cc-4252-9719-0e3ca2ff3127)
没发现有问题

**Comment by duanmw** [comment]
> ![chrome_zdKJeft3uf](https://private-user-images.githubusercontent.com/20943608/294073373-486dfa9e-e6cc-4252-9719-0e3ca2ff3127.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMzY5ODgsIm5iZiI6MTcwNDMzNjY4OCwicGF0aCI6Ii8yMDk0MzYwOC8yOTQwNzMzNzMtNDg2ZGZhOWUtZTZjYy00MjUyLTk3MTktMGUzY2EyZmYzMTI3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDAyNTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzYTgyMWY1YmVjOWJmNDg3NzRmZWU1ZDgxYTAxNTgyMTY0YmUyZDFjMzc5M2M2Njc1MGMyZjZlYzQ2M2YyMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A4fsIuxMqzuOgrDMBZoJxIyvwA1GIJ1EcbfJMYORr1U) [ ![chrome_zdKJeft3uf](https://private-user-images.githubusercontent.com/20943608/294073373-486dfa9e-e6cc-4252-9719-0e3ca2ff3127.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMzY5ODgsIm5iZiI6MTcwNDMzNjY4OCwicGF0aCI6Ii8yMDk0MzYwOC8yOTQwNzMzNzMtNDg2ZGZhOWUtZTZjYy00MjUyLTk3MTktMGUzY2EyZmYzMTI3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDAyNTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzYTgyMWY1YmVjOWJmNDg3NzRmZWU1ZDgxYTAxNTgyMTY0YmUyZDFjMzc5M2M2Njc1MGMyZjZlYzQ2M2YyMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A4fsIuxMqzuOgrDMBZoJxIyvwA1GIJ1EcbfJMYORr1U) ](https://private-user-images.githubusercontent.com/20943608/294073373-486dfa9e-e6cc-4252-9719-0e3ca2ff3127.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMzY5ODgsIm5iZiI6MTcwNDMzNjY4OCwicGF0aCI6Ii8yMDk0MzYwOC8yOTQwNzMzNzMtNDg2ZGZhOWUtZTZjYy00MjUyLTk3MTktMGUzY2EyZmYzMTI3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDAyNTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzYTgyMWY1YmVjOWJmNDg3NzRmZWU1ZDgxYTAxNTgyMTY0YmUyZDFjMzc5M2M2Njc1MGMyZjZlYzQ2M2YyMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A4fsIuxMqzuOgrDMBZoJxIyvwA1GIJ1EcbfJMYORr1U) [ ](https://private-user-images.githubusercontent.com/20943608/294073373-486dfa9e-e6cc-4252-9719-0e3ca2ff3127.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMzY5ODgsIm5iZiI6MTcwNDMzNjY4OCwicGF0aCI6Ii8yMDk0MzYwOC8yOTQwNzMzNzMtNDg2ZGZhOWUtZTZjYy00MjUyLTk3MTktMGUzY2EyZmYzMTI3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDAyNTEyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzYTgyMWY1YmVjOWJmNDg3NzRmZWU1ZDgxYTAxNTgyMTY0YmUyZDFjMzc5M2M2Njc1MGMyZjZlYzQ2M2YyMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A4fsIuxMqzuOgrDMBZoJxIyvwA1GIJ1EcbfJMYORr1U) 没发现有问题
2.36.0
https://github.com/tusen-ai/naive-ui/assets/31787613/3e34b6cf-4587-4405-86bd-97b4c4a80e67

2.34.4
https://github.com/tusen-ai/naive-ui/assets/31787613/224df895-5771-4be9-af79-2a64348457c2

**Comment by duanmw** [comment]
> ![chrome_zdKJeft3uf](https://private-user-images.githubusercontent.com/20943608/294073373-486dfa9e-e6cc-4252-9719-0e3ca2ff3127.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMzgwNTEsIm5iZiI6MTcwNDMzNzc1MSwicGF0aCI6Ii8yMDk0MzYwOC8yOTQwNzMzNzMtNDg2ZGZhOWUtZTZjYy00MjUyLTk3MTktMGUzY2EyZmYzMTI3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDAzMDkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NzRjMGJlODVjMjcwODk4YmQ3MGI2YjQ5ZTIwZTE2NDNhZjllNDVlMjkyYTUyZTEzYTc4OWExMTg2MzM1ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.35LIbo-1K1d0qq3NkqrZY71DbI4V3wPIP1UhX6u5Sb0) [ ![chrome_zdKJeft3uf](https://private-user-images.githubusercontent.com/20943608/294073373-486dfa9e-e6cc-4252-9719-0e3ca2ff3127.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMzgwNTEsIm5iZiI6MTcwNDMzNzc1MSwicGF0aCI6Ii8yMDk0MzYwOC8yOTQwNzMzNzMtNDg2ZGZhOWUtZTZjYy00MjUyLTk3MTktMGUzY2EyZmYzMTI3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDAzMDkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NzRjMGJlODVjMjcwODk4YmQ3MGI2YjQ5ZTIwZTE2NDNhZjllNDVlMjkyYTUyZTEzYTc4OWExMTg2MzM1ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.35LIbo-1K1d0qq3NkqrZY71DbI4V3wPIP1UhX6u5Sb0) ](https://private-user-images.githubusercontent.com/20943608/294073373-486dfa9e-e6cc-4252-9719-0e3ca2ff3127.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMzgwNTEsIm5iZiI6MTcwNDMzNzc1MSwicGF0aCI6Ii8yMDk0MzYwOC8yOTQwNzMzNzMtNDg2ZGZhOWUtZTZjYy00MjUyLTk3MTktMGUzY2EyZmYzMTI3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDAzMDkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NzRjMGJlODVjMjcwODk4YmQ3MGI2YjQ5ZTIwZTE2NDNhZjllNDVlMjkyYTUyZTEzYTc4OWExMTg2MzM1ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.35LIbo-1K1d0qq3NkqrZY71DbI4V3wPIP1UhX6u5Sb0) [ ](https://private-user-images.githubusercontent.com/20943608/294073373-486dfa9e-e6cc-4252-9719-0e3ca2ff3127.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMzgwNTEsIm5iZiI6MTcwNDMzNzc1MSwicGF0aCI6Ii8yMDk0MzYwOC8yOTQwNzMzNzMtNDg2ZGZhOWUtZTZjYy00MjUyLTk3MTktMGUzY2EyZmYzMTI3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDAzMDkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NzRjMGJlODVjMjcwODk4YmQ3MGI2YjQ5ZTIwZTE2NDNhZjllNDVlMjkyYTUyZTEzYTc4OWExMTg2MzM1ZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.35LIbo-1K1d0qq3NkqrZY71DbI4V3wPIP1UhX6u5Sb0) 没发现有问题

2.36:
https://github.com/tusen-ai/naive-ui/assets/31787613/f9bef8fd-bd09-4a0f-89b0-44136425a466

2.34.4
https://github.com/tusen-ai/naive-ui/assets/31787613/004ec6bb-feb9-48f4-a253-b47bde3d715e

**Comment by jahnli** [comment]
This issue should have been fixed in the new version
