### ISSUE TITLE
Data Table组件,maxheight设置后横向滚动条失效

### ISSUE THREAD

**Issue by cnki-zan** [tusen-ai/naive-ui#5533]
### TuSimple/naive-ui version (版本)
2.36.0

### Vue version (Vue 版本)
3.2.45

### Browser and its version (浏览器及其版本)
版本 120.0.6099.131（正式版本） （64 位）

### System and its version (系统及其版本)
win 10

### Reappearance link (重现链接)
https://codesandbox.io/p/sandbox/mystifying-greider-nntr67

### Reappearance steps (重现步骤)
1、在表格内容比较多会出现横向滚动条的情况下，如果加了max-height固定了头部，横向滚动条会消失，如上面我的复现代码；
2、去掉max-height，横向滚动条显示正常。

### Expected results (期望的结果)
希望固定头部的情况下，横向滚动条正常出现

### Actual results (实际的结果)
目前固定了头部，横向滚动条就没有了

**Comment by Volankey** [comment]
可以设置一下 scroll-x="1200"

**Comment by cnki-zan** [comment]
> 可以设置一下 scroll-x="1200"

但是大部分时候都无法预估这个表格的数据有多少列，scroll-x要设多大

**Comment by jahnli** [comment]
可以设置一下 scroll-x="1200"

**Comment by zhao186** [comment]
真特么服了，看了下记录22年就有人提出这个问题，也有人给出一些莫名其妙又不切实际的解决方法，就比如上面设置scroll-x，每个问题都是，完全没解决，但是一旦有一些歪门邪道的所谓解决方案就标记为已完成，结果两年了，这个BUG还是原封不动的在这里，特么的这个表格组件真是我用过最烂的，不支持插槽说无法推断插槽类型，明明有人提出几个bug一两年不修复，一开始觉得这个UI颜值不错，拿来写后台，弄得七七八八结果出了这么个BUG，真特么想死的心都有了，第三方表格要么收费要么两三年不更新，咋办？换个UI框架推到重来？

**Comment by jahnli** [comment]
> 真特么服了，看了下记录22年就有人提出这个问题，也有人给出一些莫名其妙又不切实际的解决方法，就比如上面设置scroll-x，每个问题都是，完全没解决，但是一旦有一些歪门邪道的所谓解决方案就标记为已完成，结果两年了，这个BUG还是原封不动的在这里，特么的这个表格组件真是我用过最烂的，不支持插槽说无法推断插槽类型，明明有人提出几个bug一两年不修复，一开始觉得这个UI颜值不错，拿来写后台，弄得七七八八结果出了这么个BUG，真特么想死的心都有了，第三方表格要么收费要么两三年不更新，咋办？换个UI框架推到重来？

自己写一个不就什么问题都解决了 ？
