### ISSUE TITLE
Components Docs Bug 

### ISSUE THREAD

**Issue by stephjohnsons** [tusen-ai/naive-ui#5538]
### TuSimple/naive-ui version (版本)
2.36.0

### Vue version (Vue 版本)
3.4.5

### Browser and its version (浏览器及其版本)
Brave (1.61.109)

### System and its version (系统及其版本)
MacOS(14.0)

### Reappearance link (重现链接)
https://www.naiveui.com/en-US/dark/components/data-table#DataTable-Props

### Reappearance steps (重现步骤)
Navigate to the page. 

### Expected results (期望的结果)
DataTable Props table should be showed with overflow and scroll for the excess data, similar to the other tables.

### Actual results (实际的结果)
DataTable Props table is overlapping with the floating submenu on the right.

### Remarks (补充说明)
This is a bug for the Naive UI component documentation, not on Naive UI itself.

**Comment by OrbisK** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/37191683/73d9a52d-c387-4cc5-a804-c2b536344330)
Can't confirm this on Win11 + with Chrome Version 120.0.6099.131

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
