### ISSUE TITLE
Tree组件希望提供详细的渲染筛选项

### ISSUE THREAD

**Issue by txzh007** [tusen-ai/naive-ui#5540]
### This function solves the problem (这个功能解决的问题)
filter 这个属性 是pattern变化后才触发,希望提供属性将每个节点渲染之前 给予bool值,进行渲染过滤
### Expected API (期望的 API)
由于业务复杂性,单纯的文字过滤无法满足需求,希望由用户手动实现过滤规则

**Comment by qq295823929** [comment]
可以用计算属性啊,显示的树根据你复杂的业务过滤之后,再作为数据渲染

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
