### ISSUE TITLE
Reduce table row hover transition time

### ISSUE THREAD

**Issue by 002269** [tusen-ai/naive-ui#555]
### This function solves the problem (这个功能解决的问题)
Reduce table row hover transition time
### Expected API (期望的 API)
// 去除表格内的复选框过渡效果，使动作更干脆，当然我这里去除的不仅仅是表格内
.n-checkbox {
  .n-checkbox-box {
    transition: none;

    .n-checkbox-icon .check-icon,
    .n-checkbox-icon .line-icon {
      transition: none;
    }

    .n-checkbox-box__border {
      transition: none;
    }
  }

  .n-checkbox__label {
    transition: none;
  }
}

// 去除表格过渡效果
.n-data-table {
  // 使 hover 表格行更干脆
  .n-data-table-tr {
    transition: none;
  }
  // 使 hover 表格行更干脆
  .n-data-table-td {
    transition: none;
  }
}

减少过渡时间或者直接取消过渡，会使表格选择或悬停时感觉超级快，不然的话会有点卡卡的感觉。
过渡时间0.3秒有点长了，感觉0.1秒比较合适。

**Comment by 07akioni** [comment]
目前还是需要你先覆盖一下，这个过渡时间和主题切换是共用的，这是个麻烦事，调的太快主题切换的效果会不好
