### ISSUE TITLE
下拉框select设置了宽度, 并且设置filterable之后, 文本过长省略没有title显示, 即使设置了render-tag也不行

### ISSUE THREAD

**Issue by echoTeng** [tusen-ai/naive-ui#5550]
### TuSimple/naive-ui version (版本)
2.37.0

### Vue version (Vue 版本)
3.3.9

### Browser and its version (浏览器及其版本)
120.0.6099.199

### System and its version (系统及其版本)
windows 10

### Reappearance link (重现链接)
https://codesandbox.io/p/devbox/naive-select-vue-dnjhwr

### Reappearance steps (重现步骤)
选择下拉框选项, 鼠标移入, 设置filterable的下拉框没有title

### Expected results (期望的结果)
希望选择选项后, 设置过filterable的下拉框, 文本省略也有title

### Actual results (实际的结果)
选择选项后, 设置过filterable的下拉框, 文本省略没有title, 设置render-tag也没有

**Comment by thibodeauxjl** [comment]
I'm not quite understanding what you're aiming for. I'm not sure if it's the google translation to English. Looking at the example, it seems like 3 functional select components. When I select an object from any of the components, all the components are set. I'm not exactly sure what you are referring to as far as title. I see the text above the select options that refers to a title and they don't seem to be changing or disappearing in any use case.

**Comment by Volankey** [comment]
```
function renderLabel(option: SelectOption) {
  if (option.type === "group") return option.label + "(Cool!)";
  return h(
    "span",
    {
      title: option.label,
      class: "my-tag",
    },
    option.label
  );
}

 <n-select
    :options="options"
    :filterable="true"
    :style="{ width: '200px' }"
    :renderLabel="renderLabel"
  />
```

You should use `renderLabel` rather than `renderTag`
