### ISSUE TITLE
数据表格，树形数据，如果新增的话，不会展开，请问有办法做到吗

### ISSUE THREAD

**Issue by Mylinaa** [tusen-ai/naive-ui#5553]
![Snipaste_2024-01-08_19-26-11](https://github.com/tusen-ai/naive-ui/assets/82194403/6f2a497b-f8e3-4afe-a933-364de7bbd480)

### This function solves the problem (这个功能解决的问题)
数据表格，树形数据，如果新增的话，不会展开，请问可以做到新增之后，这一行马上展开吗
### Expected API (期望的 API)
数据表格，树形数据，如果新增的话，不会展开，想要新增之后，这一行马上展开

**Comment by Mylinaa** [comment]
大大0.0，快来看看，

**Comment by jizai1125** [comment]
自己控制 `expanded-keys` 实现？
