### ISSUE TITLE
n-modal增加拖拽功能

### ISSUE THREAD

**Issue by liangyao375** [tusen-ai/naive-ui#5554]
### This function solves the problem (这个功能解决的问题)
打开弹窗后，有时候需要看后面的数据，这时候只能关闭modal，如果增加拖拽后，体验会很好
### Expected API (期望的 API)
move

**Comment by codeDevStory** [comment]
看我的useDragModal 配合自动引出插件用起来很方便

**Comment by jahnli** [comment]
https://github.com/tusen-ai/naive-ui/pull/6583
