### ISSUE TITLE
umd-test 会提示React not defined实际没有用到React，导致后续build失败，可能需要调整下vite配置

### ISSUE THREAD

**Issue by shaoerkuai** [tusen-ai/naive-ui#5558]
### TuSimple/naive-ui version (版本)
2.37.2

### Vue version (Vue 版本)
3.4.6

### Browser and its version (浏览器及其版本)
Chrome

### System and its version (系统及其版本)
Windows

### Reappearance link (重现链接)
http://github.com

### Reappearance steps (重现步骤)
在本地build时候，umd-test会失败，报错如下：
ReferenceError: React is not defined
分析了下应该是 babel 误把 jsx 当成react组件了
`pnpm run test:umd`
导致后续的脚本不能执行

### Expected results (期望的结果)
测试通过

### Actual results (实际的结果)
```
FAIL umd-test/index.spec.js
  ● Test suite failed to run

    ReferenceError: React is not defined

      at eval (eval at Object.<anonymous> (umd-test/index.spec.js:9:1), <anonymous>:34276:23)
      at eval (eval at Object.<anonymous> (umd-test/index.spec.js:9:1), <anonymous>:4:80)
      at eval (eval at Object.<anonymous> (umd-test/index.spec.js:9:1), <anonymous>:5:3)
      at Object.eval (umd-test/index.spec.js:9:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        33.003 s
Ran all test suites.
 ELIFECYCLE  Command failed with exit code 1.
```

### Remarks (补充说明)
可能需要重新配置下vite的esbuild相关参数
```
  esbuild: {
    jsxFactory: 'h',
    jsxFragment: 'Fragment',
    jsxInject: "import { h } from 'vue';"
  }
```

以上我还没测试过，umd-test我暂时是从package.json里拿掉了，目前暂时没啥问题。。

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by likui628** [comment]
我也遇到同样的问题
