### ISSUE TITLE
“n-upload”中“on-before-upload”参数fileList为空

### ISSUE THREAD

**Issue by ashuicoder** [tusen-ai/naive-ui#5562]
### TuSimple/naive-ui version (版本)
2.37.3

### Vue version (Vue 版本)
3.4.6

### Browser and its version (浏览器及其版本)
107

### System and its version (系统及其版本)
windows 11

### Node version (Node 版本)
18

### Reappearance link (重现链接)
https://codesandbox.io/p/devbox/naive-ui-test-5qdnkz?file=%2Fsrc%2FApp.vue%3A15%2C14

### Reappearance steps (重现步骤)
`n-upload`的 `on-before-upload`函数中的`fileList`参数一直都是空的

### Expected results (期望的结果)
拿到本次选择的文件列表

### Actual results (实际的结果)
空数组

**Comment by jahnli** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/20943608/01f455ff-ee2b-4c76-a845-eb9694d86d00)

**Comment by lilonghe** [comment]
路过看了下，很神奇，这表现差异有点大


<img width="1080" height="672" alt="Image" src="https://github.com/user-attachments/assets/ba945d6a-a673-4e56-890f-1e0949c312df" />

**Comment by ashuicoder** [comment]
> ![image](https://github.com/tusen-ai/naive-ui/assets/20943608/01f455ff-ee2b-4c76-a845-eb9694d86d00)

线上地址都复现了，你的为啥没问题不得而知，反正我在项目中使用这个bug一直都存在
