### ISSUE TITLE
FormItemRule type does not have level attribute for typescript checking

### ISSUE THREAD

**Issue by ltt2801** [tusen-ai/naive-ui#5563]
### TuSimple/naive-ui version (版本)
2.37.3

### Vue version (Vue 版本)
3.4.6

### Browser and its version (浏览器及其版本)
Chrome(120.0.6099.199)

### System and its version (系统及其版本)
Windows 11

### Reappearance link (重现链接)
https://codepen.io

### Reappearance steps (重现步骤)
About the new Abnormal warning in Form

### Expected results (期望的结果)
Must be existed for typescript check

### Actual results (实际的结果)
Not be existed

**Comment by OrbisK** [comment]
Please prepare a vaild reproduction. You can use typescript in codepen.

**Comment by OrbisK** [comment]
Please reopen with valid reproduction
