### ISSUE TITLE
n-input suffix插槽中n-button按钮的loading图标无法展示

### ISSUE THREAD

**Issue by liub1934** [tusen-ai/naive-ui#5566]
### TuSimple/naive-ui version (版本)
2.37.3

### Vue version (Vue 版本)
3.4.6

### Browser and its version (浏览器及其版本)
Chrome 120.0.6099.199

### System and its version (系统及其版本)
MacOS(13.5.2)

### Reappearance link (重现链接)
https://jsbin.com/jozofodero/edit?html,output

### Reappearance steps (重现步骤)
直接打开重现连接即可

### Expected results (期望的结果)
loading加载图标是白色

### Actual results (实际的结果)
loading加载图标是主色导致和按钮主色重复看不到了

### Remarks (补充说明)

<img width="1169" alt="image" src="https://github.com/tusen-ai/naive-ui/assets/29849550/855b5f37-2808-4ed0-bc7e-f2454e538198">

**Comment by thibodeauxjl** [comment]
Hello,

You can adjust the loading color on the input component using the inline style.

```
<n-input style="--n-loading-color: white">
</n-input>
```

**Comment by jizai1125** [comment]
It's not a bug, cause by the input suffix has a default loading color, you can modify like this:

```vue
<script setup>
  inputThemeOverrides = {
    loadingColor: '#fff'
  }
</script>
<template>
  <n-input :theme-overrides="inputThemeOverrides">
    <template #suffix>
      <n-button type="primary" loading>
        获取验证码
      </n-button>
    </template>
  </n-input>
</template>
```

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
