### ISSUE TITLE
标签页Tabs组件分段类型，外层容器没有使用相对定位时，选中的tab页签样式异常

### ISSUE THREAD

**Issue by maddenBoy** [tusen-ai/naive-ui#5569]
### TuSimple/naive-ui version (版本)
2.37.3

### Vue version (Vue 版本)
3.4.7

### Browser and its version (浏览器及其版本)
Chrome(120.0.6099.200)

### System and its version (系统及其版本)
Window11

### Reappearance link (重现链接)
https://codesandbox.io/p/sandbox/icy-surf-sr9jj2?file=%2Fsrc%2FDemo.vue%3A28%2C14

### Reappearance steps (重现步骤)
方法一：
  官方文档https://www.naiveui.com/zh-CN/light/components/tabs
把tabs外层n-card的相对定位注释掉，选中的tab页签样式会丢失
方法二：
  打开https://codesandbox.io/p/sandbox/icy-surf-sr9jj2?file=%2Fsrc%2FDemo.vue%3A28%2C14  ，滚动页面，tabs激活页签样式错乱

### Expected results (期望的结果)
分段类型的标签页，外层容器没有使用相对定位时，选中的tab页签样式可以正常显示

### Actual results (实际的结果)
分段类型的标签页，外层容器没有使用相对定位时，选中的tab页签样式显示异常

### Remarks (补充说明)

把tabs外层n-card的相对定位注释掉后显示的样式
![image](https://github.com/tusen-ai/naive-ui/assets/71129660/60f842f9-f954-41d0-99bd-8535991337b3)

使用n-scrollbar包裹tabs后滚动页面的样式
![image](https://github.com/tusen-ai/naive-ui/assets/71129660/fc85d130-79ed-4ae9-ad83-2880212e38fc)

**Comment by xstxhjh** [comment]
暂时解决一下燃眉之急😩
```js
.n-tabs--segment-type > .n-tabs-nav--segment-type {
  & > .n-tabs-rail > .n-tabs-capsule {
    display: none;
  }
  & .n-tabs-tab--active {
    background-color: var(--n-tab-color-segment);
  }
}
```

**Comment by alaywn** [comment]
> 暂时解决一下燃眉之急😩
> 
> ```js
> .n-tabs--segment-type > .n-tabs-nav--segment-type {
>   & > .n-tabs-rail > .n-tabs-capsule {
>     display: none;
>   }
>   & .n-tabs-tab--active {
>     background-color: var(--n-tab-color-segment);
>   }
> }
> ```

可以解决问题

**Comment by Aslantoe** [comment]
![Dingtalk_20240126155420](https://github.com/tusen-ai/naive-ui/assets/18546413/c4b81d23-6dd1-4734-a8e7-07a82c5863bf)

更新后，tab 分段类型，放到modal中会出现初始化样式问题

**Comment by zzy-life** [comment]
> ```js
> n-tabs-capsule
> ```

我也有这个问题，你怎么解决的

**Comment by zzy-life** [comment]
> ![Dingtalk_20240126155420](https://private-user-images.githubusercontent.com/18546413/299913753-c4b81d23-6dd1-4734-a8e7-07a82c5863bf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MDY5OTcsIm5iZiI6MTcwNzQwNjY5NywicGF0aCI6Ii8xODU0NjQxMy8yOTk5MTM3NTMtYzRiODFkMjMtNmRkMS00NzM0LWE4ZTctMDdhODJjNTg2M2JmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDE1MzgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZjgxZjYzMGFhMjQ1YmE0ZGNkNjAyMDgwMGVlY2U3NjU1YjU1MmZmOWNlNGYyY2EwMWNhMjdhOTRhZDM4OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.chLa5hcdYXRDmmC3_G3IhCrDRmCzx5WB26-dtu_YDbQ)
> 
> 更新后，tab 分段类型，放到modal中会出现初始化样式问题

我也有这个问题，你怎么解决的

**Comment by zzy-life** [comment]
目前我用的setTimeout延迟加载的n-tabs，这里修复了各位踢一下谢谢

**Comment by 07akioni** [comment]
修 马上就修！

**Comment by kamatil-dev** [comment]
still can't find "position:relative", and i'm still facing the problem
![image](https://github.com/tusen-ai/naive-ui/assets/41169051/92a3b227-8c38-4030-9c21-678c9cf19aea)
