### ISSUE TITLE
弹出框auto-focus为true开启closable会聚焦关闭按钮

### ISSUE THREAD

**Issue by 18684590954** [tusen-ai/naive-ui#5570]
### TuSimple/naive-ui version (版本)
2.37.3

### Vue version (Vue 版本)
3.4.7

### Browser and its version (浏览器及其版本)
chrome

### System and its version (系统及其版本)
win

### Reappearance link (重现链接)
https://codesandbox.io/s/i4z6zx

### Reappearance steps (重现步骤)
closeable=true
auto-focus=true

### Expected results (期望的结果)
不应该聚焦关闭按钮

### Actual results (实际的结果)
聚焦关闭按钮

**Comment by jahnli** [comment]
duplicate https://github.com/tusen-ai/naive-ui/issues/5196

**Comment by 18684590954** [comment]
> duplicate #5196

我认为这个功能不是应该拿来聚焦表单第一项的吗，close本身就不该被聚焦啊，在开启auto-focus的状态

**Comment by jahnli** [comment]
可移至讨论区讨论

**Comment by Flipped199** [comment]
确实不应该聚焦到关闭按钮上 就很离谱
