### ISSUE TITLE
数据表格组件，分页配置itemCount,无效

### ISSUE THREAD

**Issue by mysllove** [tusen-ai/naive-ui#5571]
### TuSimple/naive-ui version (版本)
2.37.3

### Vue version (Vue 版本)
3.4.7

### Browser and its version (浏览器及其版本)
谷歌

### System and its version (系统及其版本)
ios

### Reappearance link (重现链接)
https://www.naiveui.com/zh-CN/os-theme/components/data-table#controlled-page.vue

### Reappearance steps (重现步骤)
     <n-data-table :columns="columns" :data="data" :pagination="paginationReactive" :single-line="false" striped :theme-overrides="tableThemeOverrides">      </n-data-table>const paginationReactive = reactive({     page: 1,     pageSize: 5,     showSizePicker: true,     pageSizes: [3, 5, 7],     displayOrder: ['size-picker', 'pages'],     itemCount: 11,     onChange: (page) => {       paginationReactive.page = page;     },     onUpdatePageSize: (pageSize) => {       paginationReactive.pageSize = pageSize;       paginationReactive.page = 1;     },   });

### Expected results (期望的结果)
出现总条数

### Actual results (实际的结果)
未出现总条数

**Comment by mysllove** [comment]
异步使用？

**Comment by DogeLasVegas** [comment]
给表格加上
            :remote="true"这个属性试试呢

**Comment by zhaowanpeng** [comment]
我服了，我弄了一下午，就这么个:remote="true"，简直恶心人啊，文档也不清不白

**Comment by jhinzhou** [comment]
弄了半天，找了这个问题反馈才发现有这么一条

**Comment by jahnli** [comment]
![image](https://github.com/user-attachments/assets/4ec8a949-c7fa-4071-a83d-64729649089a)
多看文档有好处

> 我服了，我弄了一下午，就这么个:remote="true"，简直恶心人啊，文档也不清不白

**Comment by laozhengfanle** [comment]
> 给表格加上 :remote="true"这个属性试试呢

折腾了两个小时，果然加上remote属性就搞定了。烦死了，文档那句话没看懂。根据以往的经验，添加了pagination属性(object)就代表需要分页，没想到还需要显式的告诉他这是异步操作

**Comment by jahnli** [comment]
会考虑优化下文档
