### ISSUE TITLE
使用override-default-node-click-behavior功能后, 小箭头点击失效, 不会展开数据. 

### ISSUE THREAD

**Issue by eicesoft** [tusen-ai/naive-ui#5576]
### TuSimple/naive-ui version (版本)
2.37.3

### Vue version (Vue 版本)
3.4.7

### Browser and its version (浏览器及其版本)
Chrome

### System and its version (系统及其版本)
Windows 10

### Reappearance link (重现链接)
https://stackblitz.com/edit/vue-gghj8d

### Reappearance steps (重现步骤)
使用override-default-node-click-behavior功能后, 小箭头点击失效, 不会展开数据. 

### Expected results (期望的结果)
点击箭头可以正常展开/收缩树节点

### Actual results (实际的结果)
无任何反应, 会触发override的方法

**Comment by OrbisK** [comment]
en: tree select with `override-default-node-click-behavior` does not expand children when clicking on the expand arrow. Clicking label works fine.

Reprod: https://www.naiveui.com/en-US/os-theme/components/tree-select#file-picker.vue

**Comment by eicesoft** [comment]
我的解决办法是自己控制expandedKeys. 参考代码如下
` const override = ({ option }) => {
    if (option.children) {
      console.log('toggleExpand');
      if (expandedKeys.value.includes(option.id)) {
        expandedKeys.value = expandedKeys.value.filter((item) => item !== option.id);
      } else {
        expandedKeys.value.push(option.id);
      }

      return 'toggleExpand';
    }
    return 'default';
  };`

`
 <n-tree-select
              @update:value="changeClassify"
              filterable
              block-line
              :expanded-keys="expandedKeys"
              :default-expanded-keys="expandedKeys"
              :default-value="editRow.model_classify_id"
              label-field="name"
              key-field="id"
              :options="classifies"
              show-path
              :override-default-node-click-behavior="override"
            />
`

**Comment by padcmoi** [comment]
Hello, I also have the same bug, when you click on the parent it selects it instead of expanding the children.

I used exactly the same code as the example with the same data
https://www.naiveui.com/en-US/os-theme/components/tree-select#file-picker.vue

naive-ui version 2.34.4

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
