### ISSUE TITLE
n-form表单错误信息动画优化

### ISSUE THREAD

**Issue by liub1934** [tusen-ai/naive-ui#5583]
### Describe the bug

当form表单的rule设置了多个`trigger`，比如`trigger: ['input', 'blur']`，此时`input`会触发错误信息，`blur`也会触发错误信息，错误出现会有动画效果，导致页面错误信息展示再闪一次出现。
![demo14](https://github.com/tusen-ai/naive-ui/assets/29849550/92da4dc3-4885-4b3f-8f13-a34ee21f3e9f)

### Steps to reproduce

1、打开官网示例：https://www.naiveui.com/zh-CN/os-theme/components/form
2、在年龄输入框中输入任意值并点击其他地方让输入框失去焦点
3、再次点击输入框，将内容删除，此时会出现必填的校验报错，再点击其他地方让输入框失去焦点，此时会再次出现必填项的错误校验信息

### Link to minimal reproduction

https://www.naiveui.com/zh-CN/os-theme/components/form

### System Info

```Shell
macos 13.5.2 (22G91)
chrome 120.0.6099.199
"naive-ui": "^2.37.3"
"vue": "^3.4.7"
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jizai1125** [comment]
这不是 bug吧，校验两次的原因是 trigger 设成了 `input`, `blur` 导致的

**Comment by 07akioni** [comment]
> 这不是 bug 吧，校验两次的原因是因为 trigger 设成了 `input`, `blur`

或许如果能认出来 feedback 没有变的情况可以保持原有内容不变？

**Comment by 07akioni** [comment]
This is actually a bug introduced in 2.37.0
