### ISSUE TITLE
form提交后 控制台出现报错信息 

### ISSUE THREAD

**Issue by wangshiliang888** [tusen-ai/naive-ui#5587]
### Describe the bug

![image](https://github.com/tusen-ai/naive-ui/assets/146353603/2eb24d5e-fe08-490d-8fd7-726da8f08319)
![image](https://github.com/tusen-ai/naive-ui/assets/146353603/6bf3c6d6-edb6-48fb-986b-038520a14504)

### Steps to reproduce

1，能不能屏蔽掉，elementplus 等其他的都没这个问题

### Link to minimal reproduction

github

### System Info

```Shell
all
```

### Used Package Manager

yarn

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md).
- [X] Read the [docs](https://www.naiveui.com/zh-CN/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by OrbisK** [comment]
`formRef.validate()` does return a promise and rejects with errors. This is intended. 

If you still have an issue please reopen this issue and provide further reproduction and systeminfo. (systeminfo via: `npx envinfo --system --npmPackages 'naive-ui,vue' --binaries --browsers`)
