### ISSUE TITLE
设计稿sketch文件

### ISSUE THREAD

**Issue by mesuzhiben** [tusen-ai/naive-ui#5590]
### Describe the bug

设计稿sketch文件一直没更新是否安排一份最新的同步上来

### Steps to reproduce

设计稿sketch文件一直没更新是否安排一份最新的同步上来

### Link to minimal reproduction

设计稿sketch文件

### System Info

```Shell
设计稿sketch文件一直没更新是否安排一份最新的同步上来
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
duplicate   https://github.com/tusen-ai/naive-ui/issues/5607
