### ISSUE TITLE
建议为 auto-complete 组件新增追加模式

### ISSUE THREAD

**Issue by cinyearchan** [tusen-ai/naive-ui#5591]
### Clear and concise description of the problem

现有的 auto-complete 组件会在select选中后直接覆盖输入框中的内容，且无法通过 on-select 进行hack

### Suggested solution

建议给 auto-complete 组件新增一个选项，用以控制 select 选中后是直接覆盖，还是追加内容

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jahnli** [comment]
This issue should have been fixed in the new version
