### ISSUE TITLE
vue of v.3.4.13 has issue about "Maximum recursive updates exceeded in component <LayoutContent>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function." 

### ISSUE THREAD

**Issue by yongjias** [tusen-ai/naive-ui#5594]
### Describe the bug

vue 3.4.13 got this problem. vue 3.4.11 and before don't have this problem.

### Steps to reproduce

vue 3.4.13 got this problem,
naiveui is latest version

### Link to minimal reproduction

vue 3.4.13 got this problem, naiveui is latest version

### System Info

```Shell
vue 3.4.13 got this problem, naiveui is latest version
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
