### ISSUE TITLE
Data Table的title国际化切换语言无法实时变更

### ISSUE THREAD

**Issue by weikun321688** [tusen-ai/naive-ui#5596]
### Describe the bug

DataTableColumns里的title设置为国际化语言，切换后无法实时刷新，需要整个刷新页面才会变更

### Steps to reproduce

1.
<NDataTable :columns="columns"  />

const columns = ref<DataTableColumns>([
  {
    title: $t(xxxxx),
    key: 'xxx'
  }])

2.上面代码切换语言时无法刷新

### Link to minimal reproduction

https://www.naiveui.com/zh-CN/light/components/data-table

### System Info

```Shell
naive-ui 2.37.3
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md).
- [X] Read the [docs](https://www.naiveui.com/zh-CN/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Linxiaoxxx** [comment]
请问你解决了吗

**Comment by dingxyang** [comment]
![Image](https://github.com/user-attachments/assets/185f48c8-159c-4c67-914b-8e6918b24459)

**Comment by dingxyang** [comment]
const columns = computed(() => [
{
 title: () => i18n.t('xxx')
},
...
]);
