### ISSUE TITLE
n-data-table能否增加一个去除hover颜色的选项？

### ISSUE THREAD

**Issue by qilin2008201** [tusen-ai/naive-ui#5600]
### Clear and concise description of the problem

表格行默认的hover效果能否去除掉，因为它会覆盖render的样式

### Suggested solution

增加一个hover效果的开关

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by WatcherStar** [comment]
使用n-config-provider可以全局调整组件的样式[https://www.naiveui.com/zh-CN/light/docs/customize-theme](url)

**Comment by qilin2008201** [comment]
事实上，我并不是想改hover颜色，我其实是想避免触发表格行的hover事件，即关闭hover事件触发逻辑，因为目前hover会改变表格行的背景颜色，即便我将它改成透明色，它也会显示表格下容器div的背景色，依然无法满足我的需求

**Comment by WatcherStar** [comment]
> 事实上，我并不是想改hover颜色，我其实是想避免触发表格行的hover事件，即关闭hover事件触发逻辑，因为目前hover会改变表格行的背景颜色，即便我将它改成透明色，它也会显示表格下容器div的背景色，依然无法满足我的需求

render渲染出来的组件背景色如果不是透明的或半透明的话是不会被hover的背景色所影响的，你可以试着调整一下render的样式

**Comment by qilin2008201** [comment]
我似乎找到问题了，在设置了row-class-name后即便将--n-td-color-hover设置为 transparent也无法覆盖掉hover效果，请问有什么解决的方法吗？

**Comment by WatcherStar** [comment]
你是直接在row-class-name上设置了背景色了吗，因为子节点td本身背景色是白色的所以会覆盖掉tr也就是row-class-name的背景色的，把td的背景色设为透明或unset就可以看到row-class-name的背景色了

**Comment by qilin2008201** [comment]
是的，在row-class-name上我设置了背景色，但是即便我将--n-td-color改成transparent或者unset，似乎也并不能移除掉hover效果：

```vue
<n-data-table
      :data="testTableData"
      :columns="testColumn"
      :row-class-name="rowClassName"
      style="--n-td-color: transparent; --n-td-color-hover: transparent"
/>
```

```ts
const testTableData = [
  { test1: 111, test2: 222, test3: 333 },
  { test1: 111, test2: 222, test3: 333 },
  { test1: 111, test2: 222, test3: 333 },
  { test1: 111, test2: 222, test3: 333 },
  { test1: 111, test2: 222, test3: 333 },
  { test1: 111, test2: 222, test3: 333 },
  { test1: 111, test2: 222, test3: 333 }
];

const testColumn = [
  { key: 'test1', title: 'test1' },
  { key: 'test2', title: 'test2' },
  { key: 'test3', title: 'test3' }
];

const rowClassName = () => {
  return 'test-class';
};
```

```css
:deep(.test-class) {
  color: blue;
  background-color: greenyellow;
}
```

**Comment by WatcherStar** [comment]
不是--n-td-color是--n-td-color-modal这个才是背景色，hover的背景色是这个--n-td-color-hover-modal；f12就能看得到的
![Snipaste_2024-01-18_10-48-28](https://github.com/tusen-ai/naive-ui/assets/52285100/fbc2b484-d2fb-47fb-a795-675fa8baadb5)

**Comment by qilin2008201** [comment]
谢谢解答，虽然好像改--n-td-color-modal和--n-td-color-hover-modal没有用，但是给test-class中的背景色增加important好像就可以了
```css
:deep(.test-class) {
  color: blue;
  background-color: greenyellow !important;
}
```

**Comment by Volankey** [comment]
> 谢谢解答，虽然好像改--n-td-color-modal和--n-td-color-hover-modal没有用，但是给test-class中的背景色增加important好像就可以了
> 
> ```css
> :deep(.test-class) {
>   color: blue;
>   background-color: greenyellow !important;
> }
> ```

.test-class 是 row-class，应用在表格中 tr 的，而naive中单元格颜色是作用在td上，单纯改test-class的颜色是无效的，会被td上的颜色覆盖

改颜色还是通过主题样式覆盖吧
```
<n-data-table
    :columns="columns"
    :data="data"
    :theme-overrides="{
      tdColorHover: 'red',
      tdColor: 'red',
      tdTextColor: 'blue',
    }"
    :pagination="pagination"
    :bordered="false"
/>
```
