### ISSUE TITLE
修改n-select样式的最佳实践是怎样的。希望能修改select组件的背景颜色、active和focus状态的样式

### ISSUE THREAD

**Issue by LvBay** [tusen-ai/naive-ui#5603]
### Clear and concise description of the problem

修改n-select样式的最佳实践是怎样的。希望能修改select组件的背景颜色、active和focus状态的样式

### Suggested solution

在文档中没看到相关属性

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by WatcherStar** [comment]
![Snipaste_2024-01-17_10-19-21](https://github.com/tusen-ai/naive-ui/assets/52285100/eac61ec0-76b6-4aad-b6e7-d883d0bdf3a1)
在option配置中可以添加class调整样式，要注意的是class的样式不能写在scoped里面要不然会不起作用
也可以给option写一个子组件使用render配置配合vue的h函数渲染出来 
如果要调整选择框的样式可以看这个 #5600

**Comment by jizai1125** [comment]
最好通过调整主题变量的方式（如果组件有暴露出来相应主题变量的话，在文档右下角有个主题编辑器 icon 可以查找组件有哪些主题变量）；全局调整可以用组件 `n-config-provider`的 prop `theme-overrides`，在某个组件上调整可以用组件的 prop `theme-overrides`。
注意有些组件内部会复用另一个组件，这时候要修改就要使用到 [peers 主题变量](https://www.naiveui.com/zh-CN/os-theme/docs/customize-theme)，因为 peers 相关的主题变量还没有暴露，所以要查看组件有哪些 peers 有几种办法： 
1.  ts 可以通过类型 `GlobalThemeOverrides` 查看；
2. 不用 ts 就有点难搞了，我能想到的方式就是查看打包后对应组件的声明文件，比如 Select 组件，路径在 naive-ui/es/select/styles/light.d.ts
<img width="1285" alt="image" src="https://github.com/tusen-ai/naive-ui/assets/33979706/3dada734-e76b-42c4-980e-660bdf7cdffd">

**Comment by LvBay** [comment]
@WatcherStar @jizai1125 谢谢

**Comment by checkwoodson** [comment]
怕其他的组件受到影响，还是觉得官方能出个props最好。

**Comment by jizai1125** [comment]
> 怕其他的组件受到影响，还是觉得官方能出个props最好。

不会啊，可以全局改也可以在组件上改呀

**Comment by checkwoodson** [comment]
自己捣鼓,很简单的. 那个变量我也是研究出来的.rlg
