### ISSUE TITLE
折叠面板NCollapse的expanded-names属性失效

### ISSUE THREAD

**Issue by MissWangXF** [tusen-ai/naive-ui#5606]
### Describe the bug

问题：设置了expanded-names属性后，面板任何一个item都打不开，且expanded-names指定的item也不回自动打开，控制台无报错信息。
版本：2.37.3、2.37.1

### Steps to reproduce

        <n-collapse default-expanded-names="1"  accordion :expanded-names="expandName">
          <n-collapse-item title="青铜" name="1" >
            <div>可以</div>
          </n-collapse-item>
          <n-collapse-item title="白银" name="2">
            <div>很好</div>
          </n-collapse-item>
          <n-collapse-item title="黄金" name="3">
            <div>真棒</div>
          </n-collapse-item>
        </n-collapse>

  const expandName = ref("0")

### Link to minimal reproduction

无

### System Info

```Shell
windows11，Chrome，edge
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md).
- [X] Read the [docs](https://www.naiveui.com/zh-CN/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cinyearchan** [comment]
try set expandName = ref('1') or ref('2') or ref('3') instead of ref('0')

**Comment by MissWangXF** [comment]
I have tried it. It works!&nbsp; Thanks！
But now,I have another question：when set props of 'expanded-names',the component will be&nbsp;&nbsp;'controlled mode',then I can't open any item by click.
How can I use the 'expanded-names' ,as the same time can click to open?



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tusen-ai/naive-ui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月17日(星期三) 上午9:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tusen-ai/naive-ui] 折叠面板NCollapse的expanded-names属性失效 (Issue #5606)





 
try set expandName = ref('1') or ref('2') or ref('3') instead of ref('0')

**Comment by cinyearchan** [comment]
> I have tried it. It works!&nbsp; Thanks！ But now,I have another question：when set props of 'expanded-names',the component will be&nbsp;&nbsp;'controlled mode',then I can't open any item by click. How can I use the 'expanded-names' ,as the same time can click to open?
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "tusen-ai/naive-ui" ***@***.***&gt;; 发送时间:&nbsp;2024年1月17日(星期三) 上午9:56 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [tusen-ai/naive-ui] 折叠面板NCollapse的expanded-names属性失效 (Issue #5606) try set expandName = ref('1') or ref('2') or ref('3') instead of ref('0') — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

Compared with the Chinese document, the [English document](https://www.naiveui.com/en-US/os-theme/components/collapse) explains it more clearly,
`default-expanded-names` Pre-expanded panels that can still be collapsed.
`expanded-names` Expanded panels that cannot be collapsed.

so you can't click to open when you set expaned-names

**Comment by MissWangXF** [comment]
Thank you for your response!
'default-expanded-names' just can make Pre-expanded，can't control the item expanding by code logic when the system has loaded.
There is any method to control the item by code and by clicking? I mean，I want they work as the same time.(clicking and code controlling)



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tusen-ai/naive-ui"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月17日(星期三) 上午10:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tusen-ai/naive-ui] 折叠面板NCollapse的expanded-names属性失效 (Issue #5606)





  
I have tried it. It works!&nbsp; Thanks！ But now,I have another question：when set props of 'expanded-names',the component will be&nbsp;&nbsp;'controlled mode',then I can't open any item by click. How can I use the 'expanded-names' ,as the same time can click to open?
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "tusen-ai/naive-ui" @.&gt;; 发送时间:&nbsp;2024年1月17日(星期三) 上午9:56 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [tusen-ai/naive-ui] 折叠面板NCollapse的expanded-names属性失效 (Issue #5606) try set expandName = ref('1') or ref('2') or ref('3') instead of ref('0') — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
Compared with the Chinese document, the English document explains it more clearly,
 default-expanded-names Pre-expanded panels that can still be collapsed.
 expanded-names Expanded panels that cannot be collapsed.
 
so you can't click to open when you set expaned-names

**Comment by jizai1125** [comment]
> Thank you for your response! 'default-expanded-names' just can make Pre-expanded，can't control the item expanding by code logic when the system has loaded. There is any method to control the item by code and by clicking? I mean，I want they work as the same time.(clicking and code controlling)

Can use `v-model::expanded-names`. For any component's prop pair like `xxx` and `on-update:xxx`, you can always use `v-model:xxx` directly.
