### ISSUE TITLE
dataTable的on-load能不能不要冒泡

### ISSUE THREAD

**Issue by codeDevStory** [tusen-ai/naive-ui#5608]
### Clear and concise description of the problem

on-load事件冒泡，导致触发了我自定义的行点击事件

### Suggested solution

建议默认不要冒泡

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Volankey** [comment]
You should make some judgments in your custom click event
