### ISSUE TITLE
popselect能不能新增个修改边框的功能，还有那个action插槽关闭分割线的功能？

### ISSUE THREAD

**Issue by checkwoodson** [tusen-ai/naive-ui#5609]
### Clear and concise description of the problem

popselect能不能新增个修改边框的功能，还有那个action插槽关闭分割线的功能？

### Suggested solution

popselect能不能新增个修改边框的功能，还有那个action插槽关闭分割线的功能？ 或者有其他的方法去解决这个问题吗？ 我看修改边框只能在common上修改。 这样会影响全局的。

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jahnli** [comment]
可临时  `border-bottom: none`

**Comment by jizai1125** [comment]
可以把分割线颜色设成 `transparent`

```vue
<script lang="ts">
import { defineComponent, ref } from "vue";

export default defineComponent({
  setup() {
    return {
      popoverThemeOverrides: {
        peers: {
          InternalSelectMenu: {
            actionDividerColor: "transparent",
          },
        },
      },
    };
  },
});
</script>
<template>
  <n-popselect
    :theme-overrides="popoverThemeOverrides"
  >
    <n-button>{{ value || "弹出选择" }}</n-button>
    <template #header> 不知道放些什么 </template>
    <template #empty> 没啥看的，这里是空的 </template>
    <template #action> 如果你点开了这个例子，你可能需要它 </template>
  </n-popselect>
</template>
```

**Comment by jizai1125** [comment]
> 我直接把颜色改成了#fff. 硬改样式的，也是蛋疼不暴露字段的。

改 peers 确实比较难改，可以参考这个回答 https://github.com/tusen-ai/naive-ui/issues/5603#issuecomment-1901719955
