### ISSUE TITLE
Scrollbar Props 中的size属性无效

### ISSUE THREAD

**Issue by evelynn996** [tusen-ai/naive-ui#5610]
### Describe the bug

传入了size，但是滚动条大小无任何变化。

### Steps to reproduce

随便给一个值即可
![image](https://github.com/tusen-ai/naive-ui/assets/93717293/fa60f675-2c0b-4094-8309-120799652bf1)

### Link to minimal reproduction

[复现链接](https://codesandbox.io/p/sandbox/distracted-rosalind-rlnwch?file=%2Fsrc%2FDemo.vue%3A10%2C22&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrjap4eg0006356kd45a4kjo%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrjap4ef0002356k5g98ka8n%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrjap4ef0003356kwpsc0nzb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrjap4ef0005356kozb2f650%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B42.21411192214112%252C57.78588807785888%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrjap4ef0002356k5g98ka8n%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrjap4ef0001356knfy98twa%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fmain.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clrjar0d60002356kcqbn0ddo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A10%252C%2522startColumn%2522%253A22%252C%2522endLineNumber%2522%253A10%252C%2522endColumn%2522%253A22%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FDemo.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clrjap4ef0002356k5g98ka8n%2522%252C%2522activeTabId%2522%253A%2522clrjar0d60002356kcqbn0ddo%2522%257D%252C%2522clrjap4ef0005356kozb2f650%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrjap4ef0004356kijctgglb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrjap4ef0005356kozb2f650%2522%252C%2522activeTabId%2522%253A%2522clrjap4ef0004356kijctgglb%2522%257D%252C%2522clrjap4ef0003356kwpsc0nzb%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clrjap4ef0003356kwpsc0nzb%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (6) x64 AMD Ryzen 5 3500X 6-Core Processor
    Memory: 2.18 GB / 15.91 GB

 Browsers:
    Edge: Chromium (120.0.2210.133), ChromiumDev (122.0.2325.0) 
    Internet Explorer: 11.0.19041.3636
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
duplicate https://github.com/tusen-ai/naive-ui/issues/5498

**Comment by evelynn996** [comment]
> duplicate #5498

@jahnli  谢谢！想请教一下，size代表什么？theme需要传入什么？我看文档里还没有相关介绍

**Comment by jahnli** [comment]
`Size`  我记得是不是指的占比

![image](https://github.com/tusen-ai/naive-ui/assets/20943608/22851931-c496-4c23-82bb-49de96abdb13)

**Comment by jahnli** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/20943608/ca876f19-61c1-4eba-90ba-488a20a4dde6)

**Comment by evelynn996** [comment]
> ![image](https://private-user-images.githubusercontent.com/20943608/297780336-ca876f19-61c1-4eba-90ba-488a20a4dde6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1OTAwMTYsIm5iZiI6MTcwNTU4OTcxNiwicGF0aCI6Ii8yMDk0MzYwOC8yOTc3ODAzMzYtY2E4NzZmMTktNjFjMS00ZWJhLTkwYmEtNDg4YTIwYTRkZGU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDE0NTUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MTE1OTdhMGQ3NGU3YWNiZDdmMzg3OGU3NTdjMDdjMjY3NmUyNmUwYjUxMDRjMTIxNzBiNGMyMWE2MTQ1NjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iistPTNaPv7WTxDMuvbssTm8vbR6bU5VP6nHlgxEikc)

@jahnli 感谢！不过还是小小期待一下能够更新滚动条的文档说明，不然太容易误解^_^

**Comment by jahnli** [comment]
👍
