### ISSUE TITLE
n-message-provider cannot be used with multiple layers

### ISSUE THREAD

**Issue by CandyACE** [tusen-ai/naive-ui#5613]
### Describe the bug

TuSimple/naive-ui version (版本)
2.37.3

Vue version (Vue 版本)
3.4.15

Browser and its version (浏览器及其版本)
chrome 120

System and its version (系统及其版本)
window 11

Node version (Node 版本)
18.16.0

Reproduction link (重现链接)
https://codesandbox.io/p/devbox/beautiful-rumple-wt4prm?file=%2Fpackage.json%3A16%2C28&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrkout7i0007356hr3pbc6yt%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrkout7i0002356hh3tmlszr%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrkout7i0004356hiez7b66v%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrkout7i0006356hl4pmwz5r%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrkout7i0002356hh3tmlszr%2522%253A%257B%2522id%2522%253A%2522clrkout7i0002356hh3tmlszr%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrkout7i0001356hqnt5my43%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clrkox4yk009w356hu1a08lhw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clrkpqsq00002356hc7slwpzy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A16%252C%2522startColumn%2522%253A28%252C%2522endLineNumber%2522%253A16%252C%2522endColumn%2522%253A28%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrkpqsq00002356hc7slwpzy%2522%257D%252C%2522clrkout7i0006356hl4pmwz5r%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrkout7i0005356h9y1lho6w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrkout7i0006356hl4pmwz5r%2522%252C%2522activeTabId%2522%253A%2522clrkout7i0005356h9y1lho6w%2522%257D%252C%2522clrkout7i0004356hiez7b66v%2522%253A%257B%2522id%2522%253A%2522clrkout7i0004356hiez7b66v%2522%252C%2522activeTabId%2522%253A%2522clrkpf6cj012u356hly30nkb2%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522npm%2520install%2520naive-ui%25402.37.3%2522%252C%2522id%2522%253A%2522clrkovvnw008e356hc2it9u95%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522id%2522%253A%2522clrkpf6cj012u356hly30nkb2%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

Reproduction steps (重现步骤)
There is an n-message provider globally, and then there is also one locally, using 'to' to select small divs. But using useMessage inside still displays it globally.

Expected results (期望的结果)
Can display messages in a small area

Actual results (实际的结果)
Display messages globally

Remarks (补充说明)

### Steps to reproduce

There is an n-message provider globally, and then there is also one locally, using 'to' to select small divs. But using useMessage inside still displays it globally.

### Link to minimal reproduction

https://codesandbox.io/p/devbox/beautiful-rumple-wt4prm?file=%2Fpackage.json%3A16%2C28&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clrkout7i0007356hr3pbc6yt%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clrkout7i0002356hh3tmlszr%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clrkout7i0004356hiez7b66v%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clrkout7i0006356hl4pmwz5r%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clrkout7i0002356hh3tmlszr%2522%253A%257B%2522id%2522%253A%2522clrkout7i0002356hh3tmlszr%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrkout7i0001356hqnt5my43%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clrkox4yk009w356hu1a08lhw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clrkpqsq00002356hc7slwpzy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A16%252C%2522startColumn%2522%253A28%252C%2522endLineNumber%2522%253A16%252C%2522endColumn%2522%253A28%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clrkpqsq00002356hc7slwpzy%2522%257D%252C%2522clrkout7i0006356hl4pmwz5r%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clrkout7i0005356h9y1lho6w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clrkout7i0006356hl4pmwz5r%2522%252C%2522activeTabId%2522%253A%2522clrkout7i0005356h9y1lho6w%2522%257D%252C%2522clrkout7i0004356hiez7b66v%2522%253A%257B%2522id%2522%253A%2522clrkout7i0004356hiez7b66v%2522%252C%2522activeTabId%2522%253A%2522clrkpf6cj012u356hly30nkb2%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522npm%2520install%2520naive-ui%25402.37.3%2522%252C%2522id%2522%253A%2522clrkovvnw008e356hc2it9u95%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522id%2522%253A%2522clrkpf6cj012u356hly30nkb2%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### System Info

```Shell
chrome120
```

### Used Package Manager

pnpm

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jizai1125** [comment]
The `to` prop doesn't mean the area where the message will be displayed; instead, it specifies the DOM node to which the message will be mounted.
![image](https://github.com/tusen-ai/naive-ui/assets/33979706/5b2792f7-0e74-4d2d-8ac7-83aafe7eaa36)
![image](https://github.com/tusen-ai/naive-ui/assets/33979706/22960c7e-18cc-4e33-9bbf-c4aab0b8bb5d)

**Comment by CandyACE** [comment]
> The `to` prop doesn't mean the area where the message will be displayed; instead, it specifies the DOM node to which the message will be mounted. ![image](https://private-user-images.githubusercontent.com/33979706/298255901-5b2792f7-0e74-4d2d-8ac7-83aafe7eaa36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNjUyMjYsIm5iZiI6MTcwNjA2NDkyNiwicGF0aCI6Ii8zMzk3OTcwNi8yOTgyNTU5MDEtNWIyNzkyZjctMGU3NC00ZDJkLThhYzctODNhYWZlN2VhYTM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDAyNTUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ZjY3ZDJjZWU0ZjgyNTA5NTg4YTgzZTcyZTJlYjhiZTg3YTQzOTc2MmExNjM0ZDcwNjdlNTA4NWU4YWYzOWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x5F6J3gu0YcP9eOypg8R_jNvCA51zvYlU5PK4yrKc_E) ![image](https://private-user-images.githubusercontent.com/33979706/298255907-22960c7e-18cc-4e33-9bbf-c4aab0b8bb5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNjUyMjYsIm5iZiI6MTcwNjA2NDkyNiwicGF0aCI6Ii8zMzk3OTcwNi8yOTgyNTU5MDctMjI5NjBjN2UtMThjYy00ZTMzLTliYmYtYzRhYWIwYjhiYjVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDAyNTUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MmU2OTFmOGIyN2RhMDFhZWVjNWI0YjkyZjU5M2IxODE2MDQzMjcxNjZlZWJhMGVkZjk3OTQxYjRiODgzNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OMFz8-wj7A9Fz49VBPHtHJ0laF9jshjtrXitftvVhVQ)

how can i use the message inside a `div`? plesase

**Comment by jizai1125** [comment]
> how can i use the message inside a `div`? plesase

Use `Alert` ?

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
