### ISSUE TITLE
DataTable开启virtual-scroll后下边框样式失效

### ISSUE THREAD

**Issue by Zhao-sj** [tusen-ai/naive-ui#5615]
### Describe the bug

在使用DataTable同时开启virtual-scroll时，原来下边框样式失效，原因是在添加该属性后td会新增一个last-row的类名，其样式的border-width为0，导致样式失效

### Steps to reproduce

1. 添加virtual-scroll属性

### Link to minimal reproduction

https://github.com/Zhao-sj/naive-data-table-bug.git

### System Info

```Shell
pnpm run dev
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by little-fisher** [comment]
我遇到的是开启虚拟滚动之后，往下滑动表格边框发虚
