### ISSUE TITLE
[n-data-table] 表头th的titleAlign配置项是无效的

### ISSUE THREAD

**Issue by WatcherStar** [tusen-ai/naive-ui#5621]
### Describe the bug

我想要实现单独将某一列右对齐的效果，设置了align与titleAlign；align起作用了但是titleAlign没有效果
目前的解决办法是只能将n-data-table-th__title-wrapper的flex属性去掉了

### Steps to reproduce

这是我这一列的配置
```
       {
		title: '序号',
		minWidth: 58,
		align: 'right',
		titleAlign: 'right',
		className: 'serialNumber',
		key: 'key',
		render: (_: any, index: number) => {
			return `${index + 1}`
		},
	},
```

### Link to minimal reproduction

https://www.naiveui.com/zh-CN/light/components/data-table#DataTable-Props

### System Info

```Shell
naive-ui: 2.37.3
vue: 3.3.4
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Volankey** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/23287363/0d195e02-3d09-4d09-a067-6ce3bbcc24a7)
无法复现，请给出复现demo

**Comment by WatcherStar** [comment]
> ![image](https://private-user-images.githubusercontent.com/23287363/299170293-0d195e02-3d09-4d09-a067-6ce3bbcc24a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNjc1MjEsIm5iZiI6MTcwNjA2NzIyMSwicGF0aCI6Ii8yMzI4NzM2My8yOTkxNzAyOTMtMGQxOTVlMDItM2QwOS00ZDA5LWEwNjctNmNlM2JiY2MyNGE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDAzMzM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjMDMyMDlhMzI4ZDJjNGFmYzJiMDMwYTUxOWUxOWY0MmJhNzRhOTA0NDJhNGIxZGVjNmFhZjgzMzUwNDcyYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PL5C1qS6fwfRuas-59E2eOyGwnkQ8IDzkmSk-1HeL7I) Unable to reproduce, please give a demo

I'm sorry I checked my code.  My global css is contaminating the table header style
