### ISSUE TITLE
面板分割 Split组件的resize-trigger的样式显示问题

### ISSUE THREAD

**Issue by kirklin** [tusen-ai/naive-ui#5623]
### Describe the bug

面板分割 Split组件的resize-trigger的样式显示不出来

### Steps to reproduce

仓库地址：
https://github.com/kirklin/celeris-web/blob/master/apps/admin/src/pages/chat/components/ChatPanel/index.vue
部署后地址：
https://celeris-web.vercel.app/#/chat/index

### Link to minimal reproduction

https://github.com/kirklin/celeris-web/blob/master/apps/admin/src/pages/chat/components/ChatPanel/index.vue

### System Info

```Shell
System:
    OS: macOS 13.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 578.73 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.2.0 - ~/.nvm/versions/node/v20.2.0/bin/node
    npm: 9.6.6 - ~/.nvm/versions/node/v20.2.0/bin/npm
    pnpm: 8.10.5 - ~/.nvm/versions/node/v20.2.0/bin/pnpm
    bun: 1.0.3 - ~/.nvm/versions/node/v20.2.0/bin/bun
  Browsers:
    Chrome: 120.0.6099.234
    Safari: 16.6
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md).
- [X] Read the [docs](https://www.naiveui.com/zh-CN/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by XueHua-s** [comment]
In the code you provided, I don't see the attribute of resize-trigger in the member of v-slots.

**Comment by kirklin** [comment]
I would like to use the default rather than the custom

**Comment by kirklin** [comment]
> I would like to use the default rather than the custom

![image](https://github.com/tusen-ai/naive-ui/assets/17453452/1aaef74b-2a5a-402e-8cad-f7d79d3206fb)

**Comment by kirklin** [comment]
还是我自己来修吧

**Comment by alaywn** [comment]
NSplit的min属性似乎不生效，max属性是生效的

**Comment by jahnli** [comment]
> NSplit的min属性似乎不生效，max属性是生效的

https://github.com/tusen-ai/naive-ui/issues/5623#issuecomment-1959999787 等待下次更新
