### ISSUE TITLE
pagination infinite loop bug demo

### ISSUE THREAD

**Issue by kirklin** [tusen-ai/naive-ui#5624]
### Describe the bug

pagination infinite loop bug demo

### Steps to reproduce

仓库地址：
https://github.com/kirklin/celeris-web/blob/master/apps/admin/src/pages/components/headless-table/pagination/index.vue
选择翻页组件后直接卡死

### Link to minimal reproduction

https://celeris-web.vercel.app/#/components/headlessTable/pagination

### System Info

```Shell
System:
    OS: macOS 13.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 578.73 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.2.0 - ~/.nvm/versions/node/v20.2.0/bin/node
    npm: 9.6.6 - ~/.nvm/versions/node/v20.2.0/bin/npm
    pnpm: 8.10.5 - ~/.nvm/versions/node/v20.2.0/bin/pnpm
    bun: 1.0.3 - ~/.nvm/versions/node/v20.2.0/bin/bun
  Browsers:
    Chrome: 120.0.6099.234
    Safari: 16.6
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md).
- [X] Read the [docs](https://www.naiveui.com/zh-CN/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jizai1125** [comment]
建议给个复现 demo

**Comment by jizai1125** [comment]
> demo准备ok了

你这是自己又封装了一层么，官方的示例没发现有啥问题

**Comment by kirklin** [comment]
> > demo准备ok了
> 
> 你这是自己又封装了一层么，官方的示例没发现有啥问题

我封装了@tanstack/vue-table,没有额外修改Naive ui的Pagination，在这2个配合使用的时候发生了这个问题

**Comment by jizai1125** [comment]
> > > demo准备ok了
> > 
> > 你这是自己又封装了一层么，官方的示例没发现有啥问题
> 
> 我封装了@tanstack/vue-table,没有额外修改Naive ui的Pagination，在这2个配合使用的时候发生了这个问题

那应该是自己代码的问题吧，官方组件没发现有啥问题
