### ISSUE TITLE
Modal 在特定情况下关闭异常

### ISSUE THREAD

**Issue by xhlsrj** [tusen-ai/naive-ui#5631]
### Describe the bug

在特定情况下，构建后的程序中关闭 Modal 时发生如下错误。
```TypeError: Cannot read properties of null (reading 'style')```
具体情况如下：
1. Modal 内嵌一个具有 slot 的组件
2. 该组件插槽内包含 input 且绑定响应式变量
3. 该组件插槽内还包含两层嵌套的 div 元素
4. 内层 div 设置 style 属性并绑定 click 方法
5. 绑定的 click 方法需是在 script 中声明的函数
6. 构建版本会报错，开发环境下不会报错

### Steps to reproduce

1. build
2. preview
3. click 弹窗
4. input 输入任意值
5. click 关闭

### Link to minimal reproduction

https://github.com/xhlsrj/a-issue-for-naive-modal

### System Info

```Shell
System:
    OS: macOS 14.3
    CPU: (10) arm64 Apple M2 Pro
    Memory: 76.31 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.1 - /opt/homebrew/bin/node
    npm: 10.2.4 - /opt/homebrew/bin/npm
    pnpm: 8.14.3 - /opt/homebrew/bin/pnpm
    bun: 1.0.25 - /opt/homebrew/bin/bun
  Browsers:
    Brave Browser: 120.1.61.120
    Safari: 17.3
  npmPackages:
    naive-ui: ^2.37.3 => 2.37.3 
    vue: ^3.4.15 => 3.4.15
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Volankey** [comment]
Same as #3163.

**Comment by Sepush** [comment]
close as duplicate

**Comment by LinYuanq** [comment]
> Same as #3163.

how could that be same as #3163...
