### ISSUE TITLE
image 预览功能可以自定义底部的按钮和事件吗？

### ISSUE THREAD

**Issue by youjin-git** [tusen-ai/naive-ui#5632]
### 问题的清晰而简明的描述

image 预览功能可以自定义底部的按钮和事件吗？

### 建议的解决方案

image 预览功能可以自定义底部的按钮和事件吗？

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by jahnli** [comment]
https://github.com/tusen-ai/naive-ui/pull/4240 这个PR合并后，可以拿掉一些不需要的功能
