### ISSUE TITLE
新版更新后，upload组件default-file-list的url传入接口地址，接口返回的是文件流，图片无法显示

### ISSUE THREAD

**Issue by Jonas949** [tusen-ai/naive-ui#5634]
### Describe the bug

2.30.5可以显示，3.37.3无法显示。

### Steps to reproduce

upload组件的default-file-list的url属性传入接口地址，接口返回值为图片的文件流。

<img width="797" alt="1706174924221" src="https://github.com/tusen-ai/naive-ui/assets/54925213/badbeb61-ab3f-4bdd-8508-ac2d9329e790">

### Link to minimal reproduction

https://www.naiveui.com/zh-CN/os-theme

### System Info

```Shell
系统：windows11
浏览器：chrome版本 121.0.6167.85
vue3
naive ui 3.37.3
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
