### ISSUE TITLE
date-pick组件的shortcuts快捷选项能不能改一下

### ISSUE THREAD

**Issue by codeDevStory** [tusen-ai/naive-ui#5645]
### 问题的清晰而简明的描述

快捷选项能不能不要鼠标移入就触发
而是点击后触发

因为鼠标移入就触发一次
我不清楚用户到底有没有点这个快捷选项
用户点了这个快捷选项我要做一些其他的操作
但是现在这样我根本办不到

### 建议的解决方案

能不能做成个插槽，我自己自定义
或者你可以让我定义鼠标移入的时候的方法和点击的方法

或者你把event传到回调里面来
我自己来判断是移入还是点击

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by Volankey** [comment]
You can use `footer` slot.
```html
<n-date-picker :actions="[]" v-model:value="ts1" type="date">
    <template #footer>
      <n-button size="small">do something</n-button>
    </template>
</n-date-picker>
```

**Comment by codeDevStory** [comment]
> 您可以使用`footer`插槽。
> 
> ```
> <n-date-picker :actions="[]" v-model:value="ts1" type="date">
>     <template #footer>
>       <n-button size="small">do something</n-button>
>     </template>
> </n-date-picker>
> ```

But the shortcut options are selected on mouse-over.
