### ISSUE TITLE
文档文字错误

### ISSUE THREAD

**Issue by WT-SML** [tusen-ai/naive-ui#5651]
### 描述错误

![image](https://github.com/tusen-ai/naive-ui/assets/51842002/452e12fc-ead4-43d9-8f9e-a7eebc54dcb3)
应为 `厂商`

### 复现步骤

文档错误

### 最小复现链接

https://www.naiveui.com/zh-CN/light/components/color-picker

### 系统信息

```Shell
无
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jahnli** [comment]
This issue should have been fixed in the new version
