### ISSUE TITLE
神奇的 select checkmark 消失bug

### ISSUE THREAD

**Issue by Colory** [tusen-ai/naive-ui#5653]
### Describe the bug

特定参数 keyField 和 labelField下会不显示 checkmark
keyField 手动指定了 然后值如果是负数 （猜测应该是有简单的空值判断 导致负数被判断为 false ）
就会导致选中异常 并且 checkmark消失

### Steps to reproduce

```vue
<template>
  <div>
    <n-select show :options="options" keyField="v" />
  </div>
</template>
<script setup lang="tsx">
const options = [
  {
    label: "xxx",
    v: -2,
  },
  {
    label: "fff",
    v: -1,
  },
];
</script>
<style lang="less" scoped></style>

```

### Link to minimal reproduction

https://codesandbox.io/p/devbox/funny-lamport-l8zr7d

### System Info

```Shell
System:
    OS: Windows 11 10.0.22000
    CPU: (16) x64 Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
    Memory: 999.20 MB / 31.67 GB
  Binaries:
    Node: 18.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.3.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.1 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (119.0.2151.97)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    naive-ui: ^2.37.0 => 2.37.3 
    vue: ^3.4.14 => 3.4.15
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Colory** [comment]
建议可以给 checkmark 也留个插槽

**Comment by jizai1125** [comment]
@Colory `value-field` 才对

**Comment by Colory** [comment]
🙇 抱歉，确实是我弄错了
