### ISSUE TITLE
组件案例代码建议取消 ts 示例

### ISSUE THREAD

**Issue by github-cherry** [tusen-ai/naive-ui#5654]
会 ts 的人肯定都会 js，而会 js 的人不一定会 ts。js 是原生代码，需要写ts的人家一看 js 自己脑子里就知道怎么转换成 ts 的写法

**Comment by kyuuta** [comment]
想象不到是怎么能有这么离谱的issues

**Comment by SSQLQIANBB** [comment]
> ### 问题的清晰而简明的描述
> 会 ts 的人肯定都会 js，而会 js 的人不一定会 ts。js 是原生代码，需要写ts的人家一看 js 自己就知道怎么转换成 ts 的写法
> 
> ### 建议的解决方案
> 每次打开组件代码，都要切换 js 示例，建议取消 ts 示例，直接放 js 示例就够了。会 ts 的人肯定都会 js，毕竟 js 是原生代码
> 
> ### 备选方案
> _No response_
> 
> ### 附加上下文
> _No response_
> 
> ### 验证
> * [x]  阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
> * [x]  阅读 [文档](https://www.naiveui.com/en-US)。
> * [x]  检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

> ### This is absolutely ridiculous；fuck
