### ISSUE TITLE
input 循环不能正常输入

### ISSUE THREAD

**Issue by AuYuHui** [tusen-ai/naive-ui#5656]
### Describe the bug

input 循环不能正常输入

### Steps to reproduce

```
<script setup lang="ts">
import { ref } from 'vue';

const floorData = ref([
  {
    floor: '1'
  },
  {
    floor: '2'
  }
]);
</script>

<template>
  <div>
    <template v-for="item in floorData" :key="item.floor">
      <n-input v-model:value="item.floor" type="text" placeholder="基本的 Input" />
    </template>
  </div>
</template>

<style scoped></style>
```

### Link to minimal reproduction

https://www.naiveui.com/zh-CN/os-theme/components/input

### System Info

```Shell
System:
    OS: Windows 11 10.0.22000
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 17.23 GB / 28.92 GB
  Binaries:
    Node: 18.19.0 - ~\AppData\Local\fnm_multishells\33304_1706797626413\node.EXE
    npm: 10.2.3 - ~\AppData\Local\fnm_multishells\33304_1706797626413\npm.CMD
    pnpm: 8.12.0 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (121.0.2277.83)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    naive-ui: 2.37.3 => 2.37.3 
    vue: 3.4.15 => 3.4.15
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by qq295823929** [comment]
你这个key肯定不能是一个"随着输入都在变化的floor字段"撒,你要么虚拟手动赋值一个id或者key作为:key的值,要么在这里用index作为key都行(不推荐,但是在你这里至少都行).
