### ISSUE TITLE
树型选择 Tree Select 组件默认值问题

### ISSUE THREAD

**Issue by eivmosn** [tusen-ai/naive-ui#5657]
### Describe the bug

<img width="780" alt="截屏2024-02-02 15 40 36" src="https://github.com/tusen-ai/naive-ui/assets/48376511/23320cc2-673f-4fea-9a76-4f412e8cd654">

如上图所示， 如果后端返回的是一个不包含在 options 里的值， 那么这个值就不显示了。这里不确定是否是组件的预期效果，但综合比较了其他组件库，都是会默认展示，效果大概如下：

<img width="755" alt="截屏2024-02-02 15 38 52" src="https://github.com/tusen-ai/naive-ui/assets/48376511/b10fb78b-02bc-4e9f-a569-460fae32aa2c">

### Steps to reproduce

1. 传入一个默认值 (default-value) 但这个值在 options 中是不存在的
2. 此时树形选择框中并没有展示这个不存在的默认值标签

### Link to minimal reproduction

https://stackblitz.com/edit/vitejs-vite-8fa3f5?file=src%2Fcomponents%2FTreeSelect.vue

### System Info

```Shell
System:
    OS: macOS 14.3
    CPU: (12) arm64 Apple M3 Pro
    Memory: 224.34 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/Library/Caches/fnm_multishells/30906_1706861392030/bin/node
    npm: 10.2.3 - ~/Library/Caches/fnm_multishells/30906_1706861392030/bin/npm
    pnpm: 8.12.1 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 121.0.6167.139
    Safari: 17.3
  npmPackages:
    naive-ui: ^2.37.3 => 2.37.3 
    vue: ^3.4.15 => 3.4.15
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by XueHua-s** [comment]
这个组件库的特性就是这样，如果列表内没匹配到value值相关value-key值的选项。就是不会在选中里的。

**Comment by XueHua-s** [comment]
你这个东西，你可以自己处理一下。例如，后端加载的时候，你给后端传条件，把这个项给返回来。或者你前端进行一些其他操作。

**Comment by eivmosn** [comment]
> 你这个东西，你可以自己处理一下。例如，后端加载的时候，你给后端传条件，把这个项给返回来。或者你前端进行一些其他操作。

嗯 这样的话我在想其他方式吧
