### ISSUE TITLE
希望现有<n-select>和<n-input>标签功能能同时实现

### ISSUE THREAD

**Issue by Jonas-2020** [tusen-ai/naive-ui#5661]
### 问题的清晰而简明的描述

实际业务存在大量的用户及可以选择下拉框选项的需要，也存在用户可以自行输入一些下拉框未有的选项的需要。其它组件如element ui有这种功能

### 建议的解决方案

在<n-select>加入<n-input>标签的功能，让用户可以自行输入！

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by WatcherStar** [comment]
select貌似也是可以实现类似的功能[作为 Tag 框输入使用](https://www.naiveui.com/zh-CN/light/components/select#tag-input.vue)；只要将show和show-arrow设置为true，把options数据填入就行了；不知道是不是你想要的效果
