### ISSUE TITLE
Pressing SHIFT key in n-input component generates error in console

### ISSUE THREAD

**Issue by sszhukov** [tusen-ai/naive-ui#5671]
### Describe the bug

Pressing SHIFT key in n-input component generates error in console:
Uncaught TypeError: inputTypes.contains is not a function

### Steps to reproduce

1. Go to [components/input](https://www.naiveui.com/en-US/light/components/input)
2. Focus on the first n-input field
3. Press SHIFT key on a keyboard
4. Check browser console

### Link to minimal reproduction

https://www.naiveui.com/en-US/light/components/input

### System Info

```Shell
Doesn't matter
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by kirklin** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/17453452/29402608-c8cb-4303-bc98-c39abec8133d)

There doesn't seem to be a problem.

**Comment by sszhukov** [comment]
Sorry, this is ARK Browser problem
