### ISSUE TITLE
Timeline 内容增加 VNode 类型支持

### ISSUE THREAD

**Issue by ifyun** [tusen-ai/naive-ui#5675]
### 问题的清晰而简明的描述

`TimelineItem` 的 `content` 属性目前仅支持字符串，不能使用 VNode/HTML 作为内容。

### 建议的解决方案

使 `content` 属性支持 `() => VNodeChild` 类型，类似 `Dialog` 组件。

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by jahnli** [comment]
```
    <n-timeline-item type="error" time="2018-04-03 20:46">
      <div>
        <span>这是错误</span>
        <span>这是错误</span>
        <span>这是错误1</span>
      </div>
    </n-timeline-item>
```

**Comment by ifyun** [comment]
原来有 `default` 插槽啊
