### ISSUE TITLE
is-date-disabled buggged for months

### ISSUE THREAD

**Issue by LlamameAncar** [tusen-ai/naive-ui#5676]
### Clear and concise description of the problem

When the method is-date-disabled is called with the type proterty set to month more dates are marked as disables than the ones that should be. For example if minDate is 2023-11-01 and maxDate is 2024-02-01, the whole 2023 year is disabled instead of only disabling from january to october, also if the date is inserted manually by the user, instead of using the picker, it is accepted without issue. Furthermore if instead we use as minDate 2023-01-01 all 2023 suddenly becomes available.

### Suggested solution

-

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by OrbisK** [comment]
this should be a bug report, not feature request? Please open a propper bug report via: https://github.com/tusen-ai/naive-ui/issues/new?template=bug_report.yml
