### ISSUE TITLE
tab 分段类型，放到modal中会出现初始化样式问题

### ISSUE THREAD

**Issue by zzy-life** [tusen-ai/naive-ui#5682]
tab 分段类型，放到modal中会出现初始化样式问题

_Originally posted by @Aslantoe in https://github.com/tusen-ai/naive-ui/issues/5569#issuecomment-1911627756_

**Comment by zzy-life** [comment]
![Dingtalk_20240126155420](https://private-user-images.githubusercontent.com/18546413/299913753-c4b81d23-6dd1-4734-a8e7-07a82c5863bf.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5ODY0NTEsIm5iZiI6MTcwNzk4NjE1MSwicGF0aCI6Ii8xODU0NjQxMy8yOTk5MTM3NTMtYzRiODFkMjMtNmRkMS00NzM0LWE4ZTctMDdhODJjNTg2M2JmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDA4MzU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMTcwYmUwN2I4MmRjMjVhZTRlY2ZlMjNmZGUxYzlkZTAxY2RiZTYzZmI1ZTA4MmQ1MTA3NDcwYmY3MTQzOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hM7XXa0DvR14Z90ZOm2Kr_Ahiy1zY9Iq2JnWK4rZiGM)

**Comment by OrbisK** [comment]
Please open a valid bug report via: https://github.com/tusen-ai/naive-ui/issues/new?assignees=&labels=untriaged&projects=&template=bug_report.zh-CN.yml
