### ISSUE TITLE
Request: Composition API Docs

### ISSUE THREAD

**Issue by jeffspurlock** [tusen-ai/naive-ui#5685]
### Clear and concise description of the problem

Thanks for creating this library. It would be wonderful if the documentation was updated to use the Composition API. All documentation around Nuxt 3 and Vue 3 uses Composition API by default, so trying to make sense of how to implement this with Comp API would be very difficult for anyone who isn't well versed in how those two APIs are both written and how to rewrite the Naive UI implementation into the modern design pattern. 

### Suggested solution

rewrite the docs to use the modern SFC syntax

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by OrbisK** [comment]
https://github.com/tusen-ai/naive-ui/blob/3b28b671b62efff60b172c62761e92177d093cb0/CHANGELOG.en-US.md?plain=1#L274

naive ui docs allow script setup

**Comment by 07akioni** [comment]
I think we won't rewrite current docs. For sure `setup` script is more elegant, but rewriting all existing demo code is not efficient.

Also we don't recommend anyone trying do such thing since it would be a super time-killing task which doesn't improve demo's experience much.
