### ISSUE TITLE
官网文档-更新日志，希望能展示版本具体时间

### ISSUE THREAD

**Issue by luoriwusheng-xia** [tusen-ai/naive-ui#5687]
### 问题的清晰而简明的描述

更新日志，展示具体tag 版本对应发布时间，可能更好

### 建议的解决方案

建议展示
![image](https://github.com/tusen-ai/naive-ui/assets/152823466/7d5a09f0-71ea-4bf2-8953-aad621684239)

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by jahnli** [comment]
https://github.com/tusen-ai/naive-ui/pull/5694

等发布
