### ISSUE TITLE
由于技术限制，n-grid-item 是无法被二次封装的

### ISSUE THREAD

**Issue by Mikasa33** [tusen-ai/naive-ui#5688]
### 描述错误

【由于技术限制，n-grid-item 是无法被二次封装的】
有没有什么办法能封装 Form 和 Grid 呢
```html 
// XForm
<NForm>
  <NGrid>
    <slot />
  </NGrid>
</NForm>

// XFormItem
<NFormItemGi>
  <slot />
</NFormItemGi>

// Business
<XForm>
  <XFormItem> ... </XFormItem>
  <XFormItem> ... </XFormItem>
</XForm>
```

### 复现步骤

无

### 最小复现链接

无

### 系统信息

```Shell
无
```

### 使用的包管理器

npm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by OrbisK** [comment]
naive ui manipulate VNode directly to make the components work. You cant wrap components like tab or form/-item

**Comment by sunpm** [comment]
If slots can be encapsulated, passing values between components will be more convenient, without the need to receive from child components and then pass them further down.
