### ISSUE TITLE
NDataTable组件点击特定位置会显示一个光标

### ISSUE THREAD

**Issue by labradorGitHubCanine** [tusen-ai/naive-ui#5691]
### 描述错误

点击n-data-table组件特定位置会出现光标

### 复现步骤

官网的api文档点击后就能复现
![1708420011544](https://github.com/tusen-ai/naive-ui/assets/28785991/c4f7612a-e8a0-4701-9c85-41ccb396f984)
![image](https://github.com/tusen-ai/naive-ui/assets/28785991/92fac349-9f53-4b01-b470-adf8628a638e)

### 最小复现链接

https://www.naiveui.com/zh-CN/os-theme/components/data-table

### 系统信息

```Shell
无
```

### 使用的包管理器

npm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by Volankey** [comment]
What is your operating system and browser version?

**Comment by Volankey** [comment]
I can not repeat this problem, suspected plug-in caused, suggest to open a private mode to close the plugins to try.

**Comment by jahnli** [comment]
尝试关闭 `使用文本光标浏览网页`

**Comment by labradorGitHubCanine** [comment]
> Try turning off 'Browse the Web with text Cursor'
> 
> Appearance -> Accessibility -> Use the text cursor to browse the Web

I solved this problem by following your steps, thank u
