### ISSUE TITLE
和Nuxt3一起使用时出错 No outer `n-notification-provider` found.

### ISSUE THREAD

**Issue by miaobuao** [tusen-ai/naive-ui#5692]
### 描述错误

# 500
## [naive/use-notification]: No outer `n-notification-provider` found.

at Proxy.useNotification (./node_modules/.pnpm/naive-ui@2.37.3_vue@3.4.19/node_modules/naive-ui/lib/notification/src/use-notification.js:10:33)
at setup (./app.js:17:42)
at _sfc_main.setup (./app.js:51:23)
at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:193:18)
at setupStatefulComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7548:25)
at setupComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7509:36)
at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:635:15)
at Module.ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:84:10)
at default (./node_modules/.pnpm/nuxt@3.10.2_vite@5.1.3/node_modules/nuxt/dist/app/components/nuxt-root.js:82:37)

### 复现步骤

1. layouts/default.vue 里面写`n-xxxx-provider`
2. app.vue 中使用`useNotification` | `useDialog` | `useMessage` 都会报错

### 最小复现链接

[codesandbox](https://codesandbox.io/p/devbox/nuxt-naive-ui-bug-jydv2w?file=%2Fapp.vue%3A17%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsu3prrr0007396iauqc65k2%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsu3prrq0002396iixopv68y%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsu3prrq0004396iael92q68%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsu3prrq0006396il07ldluy%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsu3prrq0002396iixopv68y%2522%253A%257B%2522id%2522%253A%2522clsu3prrq0002396iixopv68y%2522%252C%2522activeTabId%2522%253A%2522clsu4910e0002396i5vyca4nu%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522clsu3w92200fw396i448fy0l7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clsu4910e0002396i5vyca4nu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A17%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A17%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clsu3prrq0006396il07ldluy%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsu3prrq0005396i10uoav4k%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsu3prrq0006396il07ldluy%2522%252C%2522activeTabId%2522%253A%2522clsu3prrq0005396i10uoav4k%2522%257D%252C%2522clsu3prrq0004396iael92q68%2522%253A%257B%2522id%2522%253A%2522clsu3prrq0004396iael92q68%2522%252C%2522activeTabId%2522%253A%2522clsu3prrq0003396ivekyd90k%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsu3prrq0003396ivekyd90k%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clsu3q6110060396iw54fk8ob%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clsu3q65z001cdjabaxvtgkxg%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### 系统信息

```Shell
System:
    OS: Linux 6.7 Fedora Linux 39 (Workstation Edition)
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 6.51 GB / 13.51 GB
    Container: Yes
    Shell: 3.7.0 - /usr/bin/fish
  Binaries:
    Node: 20.10.0 - /usr/bin/node
    npm: 10.2.3 - /usr/bin/npm
    pnpm: 8.15.3 - ~/.local/share/pnpm/pnpm
    bun: 1.0.26 - ~/.local/share/pnpm/bun
  npmPackages:
    naive-ui: ^2.37.3 => 2.37.3 
    vue: ^3.4.15 => 3.4.19
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by Volankey** [comment]
remove the code in app.vue

```
<script setup lang="ts">
import { useNotification } from "naive-ui";

const notify = useNotification();

notify.create({
  type: "info",
  content: "baga",
});
</script>

```

**Comment by miaobuao** [comment]
How to use it in app. vue

**Comment by Volankey** [comment]
Although I don't know why you need to do this, you can refer to https://www.naiveui.com/zh-CN/os-theme/components/message#%E5%9C%A8-setup-%E5%A4%96%E4%BD%BF%E7%94%A8 for more information.
Try [createDiscreteApi](https://www.naiveui.com/zh-CN/os-theme/components/discrete)

**Comment by f754699** [comment]
必须是n-notification-provider所在的组件的子组件，才能使用。
如果想在app.vue里面使用，那就把n-notification-provider抽离到另一个组件里面，然后app.vue引入这个组件，就可以在app.vue里面使用了
所有涉及依赖注入的，都是这样

**Comment by jahnli** [comment]
AppProvider.vue

```
  <n-config-provider>
    <n-loading-bar-provider>
      <n-modal-provider>
        <n-dialog-provider>
          <n-notification-provider>
            <n-message-provider>
              <app />
            </n-message-provider>
          </n-notification-provider>
        </n-dialog-provider>
      </n-modal-provider>
    </n-loading-bar-provider>
  </n-config-provider>
```


App.vue

```
<script setup lang="ts">
const registerNaiveUiTools = () => {
  window.$message = useMessage();
  window.$loadingBar = useLoadingBar();
  window.$dialog = useDialog();
  window.$notification = useNotification();
};
registerNaiveUiTools();
</script>

<template>
  <router-view />
</template>
```
