### ISSUE TITLE
页面宽度变化后segment类型Tabs标签页指示条显示异常

### ISSUE THREAD

**Issue by Smthie** [tusen-ai/naive-ui#5705]
[https://www.naiveui.com/zh-CN/light/components/tabs](https://www.naiveui.com/zh-CN/light/components/tabs)

官网尝试切换egment类型Tabs指示条后，操作左侧侧边栏收起打开，即可复现问题。

![QQ截图20240223112606](https://github.com/tusen-ai/naive-ui/assets/39211417/860790c7-7745-4f69-a722-b1dc7ab29644)

![QQ截图20240223112655](https://github.com/tusen-ai/naive-ui/assets/39211417/29160f9c-3823-4578-a33d-8212c78389a7)

以下为其它issue类似问题：

    不仅仅有上述问题，还存在如下问题：

NTabs 设置 type="segment" ，当tabpane数量发生变化后，tabpane显示的宽度没有同步更新，比如原来是2个tabpane，更新为5个tabpane后，tabpane的宽度还是2个时的宽度：
<img width="1020" alt="image" src="https://github.com/tusen-ai/naive-ui/assets/15193980/0b598f46-c99e-4b9d-9054-f66e54405179">
（补充：如果点击切换一下tabpane后，宽度显示则恢复正常）
另外，改变NTabs所在上级元素的宽度后，比如折叠Sider后，也有上述同样的问题。
<img width="1512" alt="image" src="https://github.com/tusen-ai/naive-ui/assets/15193980/7aded26d-2c55-4a55-b292-c397fbf803eb">

PS:
type="card"没有这个问题；
版本恢复到2.36.0后，也没有这个问题

_Originally posted by @alaywn in https://github.com/tusen-ai/naive-ui/issues/5569#issuecomment-1893147425_

**Comment by alaywn** [comment]
哇哦，赞，通过官网复现问题，牛！🐂

**Comment by xstxhjh** [comment]
<img width="797" alt="image" src="https://github.com/tusen-ai/naive-ui/assets/33480698/4c3fc88c-9f2e-42ae-80ce-240582943ff4">
好像没有完全修复，弹窗中还是会出现这种情况。
