### ISSUE TITLE
文档中 Float Button 气泡提示演示示例有问题，悬浮报错

### ISSUE THREAD

**Issue by Mikasa33** [tusen-ai/naive-ui#5708]
### 描述错误

<img width="313" alt="image" src="https://github.com/tusen-ai/naive-ui/assets/29498153/4cf49b7d-7787-47ef-899c-72c9ff48f7d6">

### 复现步骤

鼠标触碰悬浮按钮

### 最小复现链接

https://www.naiveui.com/zh-CN/os-theme/components/float-button#tooltip.vue

### 系统信息

```Shell
无
```

### 使用的包管理器

npm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by kamatil-dev** [comment]
I'm facing the same problem too

**Comment by n3taway** [comment]
oh same problem too

**Comment by jahnli** [comment]
https://github.com/tusen-ai/naive-ui/commit/a5c3b902cdc2ab8895f5c4c4e07c21d5a719abc8、
等待发布
