### ISSUE TITLE
表格开启虚拟滚动，可以通过滚动到指定的行

### ISSUE THREAD

**Issue by shuaiyifa** [tusen-ai/naive-ui#5714]
### 问题的清晰而简明的描述

希望可以实现表格开启虚拟滚动的时候，scrollTo滚动到指定的行

### 建议的解决方案

tableRef.value?.scrollTo({ Rowindex: index })

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by StereoApp** [comment]
https://github.com/tusen-ai/naive-ui/issues/4765

**Comment by jahnli** [comment]
https://github.com/tusen-ai/naive-ui/issues/4765
