### ISSUE TITLE
SSR app using naive ui has low lightscore

### ISSUE THREAD

**Issue by debasispanigrahi** [tusen-ai/naive-ui#5715]
### Describe the bug

Naive ui is great. Used naive ui in Nuxt. when tried with calender and buttons, their style modified after hydration and mounting completed. Perhaps logic is to introduce style tags after component mounts. This indeed comes at a cost of very low cls (Content Layout Shift). Need Certain optimization for all styles in components so that they load beforehand.

Requirement
1. Instead of style tags added to head after component mounts, they should be available from server side for matching hydration

Solution:
1. Instead of inserting style after mounting, component styles can be made accessible by file path
2.  for dynamic style "component is:style" can be used. For uniqueness global object can be used.

### Steps to reproduce

1. Any nuxt application with naive-ui as plugin
2. use large layout shift components like calender and button
3. use browser inbuilt light house score detector.
4.  Check performance tab in lighthouse

### Link to minimal reproduction

Any Nuxt example shared in docs

### System Info

```Shell
Any Pc
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by 07akioni** [comment]
Performance, Features, Flexibility is hard to achieve at the same time (I my point of view it's impossible).

Layout shift is unavoidable in some naive's component to implement some features. Too keep the current feature scale & tech stack, lighthouse score has lower priority.

If you find some specific component whose performance is outlier, you can create another issue.

**Comment by 07akioni** [comment]
By the way we provide official nuxt module now.

https://www.naiveui.com/en-US/os-theme/docs/nuxtjs
