### ISSUE TITLE
`n-split` missing losing css variables with inline theme disabled

### ISSUE THREAD

**Issue by kirklin** [tusen-ai/naive-ui#5717]
### 描述错误

`n-split` missing losing css variables with inline theme disabled

### 复现步骤

1. 开启inline-theme-disabled
2. split的滚动条就会消失
![image](https://github.com/tusen-ai/naive-ui/assets/17453452/c43ad061-e139-4e24-bea6-dab84fa0f7b7)

### 最小复现链接

-

### 系统信息

```Shell
-
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jahnli** [comment]
Will release it in next version.
