### ISSUE TITLE
tabs 设置 type="segment" 在 <n-layout has-sider> 中 滚动会出现异常

### ISSUE THREAD

**Issue by zhannan-cn** [tusen-ai/naive-ui#5728]
### 描述错误

tabs 设置   type="segment"  后,  放置 ` <n-layout has-sider> <n-layout-content style="height: calc(100vh - 64px)"></n-layout-content></n-layout>` 中 滚动页面时会出现异常显示
![image](https://github.com/tusen-ai/naive-ui/assets/53068054/f2beca52-dd71-48f9-94fd-1d99bf6c0e22)

### 复现步骤

1.把 tabs 的 type 设置成 segment
2.放入`<n-layout has-sider> <n-layout-content style="height: calc(100vh - 64px)"></n-layout-content></n-layout>` 中
3.往 n-tab-pane 填充内容, 使其出现滚动条
4.滚动时 tabs 抬头就会显示异常, 跟着一起滚动

### 最小复现链接

https://stackblitz.com/edit/vitejs-vite-uhs9pr?file=src%2FApp.vue

### 系统信息

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.14.0 - /usr/local/bin/pnpm
  npmPackages:
    naive-ui: ^2.38.1 => 2.38.1 
    vue: ^3.4.20 => 3.4.20
```

### 使用的包管理器

npm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by nongyehong** [comment]
正好也发现了这个问题
