### ISSUE TITLE
carousel 图片有空隙

### ISSUE THREAD

**Issue by lindaoling** [tusen-ai/naive-ui#5740]
### 描述错误

下图是文档中的示例，图片左右都可能出现空隙，我在项目使用中也存在这问题

![微信截图_20240229183951](https://github.com/tusen-ai/naive-ui/assets/9306261/f63a0781-d658-4ee0-885f-77e6efb3fae6)

![微信截图_20240301124132](https://github.com/tusen-ai/naive-ui/assets/9306261/e7bf5cbc-5038-4a07-85e8-548660af1258)

### 复现步骤

直接copy文档代码

### 最小复现链接

https://www.naiveui.com/zh-CN/os-theme/components/carousel

### 系统信息

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
    Memory: 513.73 MB / 7.88 GB
  Binaries:
    Node: 18.19.0 - ~\AppData\Local\fnm_multishells\15232_1709267947265\node.EXE
    Yarn: 1.22.21 - ~\AppData\Local\fnm_multishells\15232_1709267947265\yarn.CMD
    npm: 10.2.3 - ~\AppData\Local\fnm_multishells\15232_1709267947265\npm.CMD
    pnpm: 8.15.4 - ~\AppData\Local\fnm_multishells\15232_1709267947265\pnpm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.144)
    Internet Explorer: 11.0.19041.3636
```

### 使用的包管理器

yarn

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jahnli** [comment]
see https://github.com/tusen-ai/naive-ui/issues/5691

**Comment by SvenMeiLing** [comment]
> 参见#5691

您好不是您说的这个问题,图中是描述一个图片溢出父元素的问题

**Comment by yuanhongyu123** [comment]
同样的问题。

**Comment by SvenMeiLing** [comment]
> 同样的问题。

当你把carousel元素加上border或者是父元素存在padding, img边缘会有空隙

**Comment by yuanhongyu123** [comment]
> > 同样的问题。
> 
> 当你把carousel元素加上border或者是父元素存在padding, img边缘会有空隙

这两个我都没有。。。
