### ISSUE TITLE
<n-list> failed under Vite Build possibly related to CJS

### ISSUE THREAD

**Issue by hyp530** [tusen-ai/naive-ui#5741]
### Describe the bug

```<script setup lang="ts">
const props = defineProps<{
  item1: string; 
  item2: string; 
}>();
</script>

<template>
  <n-list>
    <n-list-item> {{props.item1}} </n-list-item>
    <n-list-item> {{props.item2}} </n-list-item>
  </n-list>
</template>
```
Aboved is an example component created for a vitepress project. Everything is fine under Vite dev, however, **n-list-item** is not converted to the native **li** element under Vite build (No build errors at all!).

This is my package.json:
```
{
  "name": "naivevitepress",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "docs:dev": "vitepress dev docs",
    "docs:build": "vitepress build docs",
    "docs:preview": "vitepress preview docs"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "naive-ui": "^2.38.0",
    "sass": "^1.71.1",
    "unplugin-auto-import": "^0.17.5",
    "unplugin-vue-components": "^0.26.0",
    "vitepress": "^1.0.0-rc.44"
  }
}
```

Is it an issue related to CJS, and any solution to fix this?

### Steps to reproduce

Example code: https://github.com/hyp530/naivevitepress
Result: https://naivevitepress.vercel.app/markdown-examples.html

1.  Install vitepress: npm add -D vitepress

2.  Install naive-ui: npm i -D naive-ui  

3.  Install unplugin-auto-import and unplugin-vue-components, for auto-import:
```
import { defineConfig } from 'vite'
import AutoImport from 'unplugin-auto-import/vite'
import Components from "unplugin-vue-components/vite";
import { NaiveUiResolver } from "unplugin-vue-components/resolvers";

export default defineConfig({
  plugins: [
    AutoImport({
      imports: [
        'vue',
        {
          'naive-ui': [
            'useDialog',
            'useMessage',
            'useNotification',
            'useLoadingBar'
          ]
        }
      ]
    }),
    Components({
      dirs: ["/"],
      include: [/\.vue$/, /\.md$/],
      resolvers: [NaiveUiResolver({ sideEffect: true })],
    }),
  ],
  ssr: { noExternal: ["naive-ui", "vueuc"] },
})
```
4. Create the example components:
```
import type { Theme } from 'vitepress'
import DefaultTheme from 'vitepress/theme'
import './style.css'

import MyList from "./components/MyList.vue";
import MyList2 from "./components/MyList2.vue";

export default {
  extends: DefaultTheme,
  enhanceApp({ app, router, siteData }) {
        app.component("MyList", MyList);
        app.component("MyList2", MyList2);
  }
} satisfies Theme
```

### Link to minimal reproduction

https://github.com/hyp530/naivevitepress

### System Info

```Shell
System:
    OS: Windows 11 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 601.79 MB / 7.83 GB
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 87.0.4280.141
    Edge: Chromium (114.0.1823.58)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    naive-ui: ^2.38.0 => 2.38.0
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
dulicate https://github.com/tusen-ai/naive-ui/issues/4225#issuecomment-1974842846
