### ISSUE TITLE
给二维码 QR Code 提供 svg 选项

### ISSUE THREAD

**Issue by rwv** [tusen-ai/naive-ui#5743]
### 问题的清晰而简明的描述

希望给二维码  QR Code 提供 svg 选项，使得在高分屏下更加清晰。

### 建议的解决方案

提供 svg 选项。假如不方便实现，也可以先设置 css `image-rendering: pixelated`。

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by codeDevStory** [comment]
canvas和svg应该是可以互相转的
