### ISSUE TITLE
useModal 预设为card时不能展示content

### ISSUE THREAD

**Issue by sinpor** [tusen-ai/naive-ui#5746]
### 描述错误

useModal预设为card时配置content不能显示，style样式也无效。

### 复现步骤

``` ts
 const modalInst = modal.create({
        title: "模态框",
        preset: "card",
        style: { width: "300px" },
        content: () =>
          h(Fragment, null, {
            default: () => "Hello World",
            footer: () =>
              h(NFlex, null, [
                h(NButton, null, "取消"),
                h(
                  NButton,
                  {
                    type: "primary",
                  },
                  "确认"
                ),
              ]),
          }),
      });
```

### 最小复现链接

https://codesandbox.io/p/sandbox/festive-scott-vg3hfp

### 系统信息

```Shell
MacOS 13.4 (22F66)
Chrome 122.0.6261.94
naive-ui 2.38.1
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jizai1125** [comment]
用命令式调用 Modal 的话，`card` 预设没有 `content` prop，也没法接收 card 相关 slots，确实存在问题

**Comment by sinpor** [comment]
看了changelog没提到`useModal`的细节，我不确定是不是设计就是这样的，如果不是我有空提个pr。

**Comment by jizai1125** [comment]
> 看了changelog没提到`useModal`的细节，我不确定是不是设计就是这样的，如果不是我有空提个pr。

是有问题的，我提了 PR

**Comment by XiaoDaiGua-Ray** [comment]
能否发布一下该合并，`useModal` 的问题有点影响使用。

**Comment by jizai1125** [comment]
> 能否发布一下该合并，`useModal` 的问题有点影响使用。

得等作者发布了，你可以去催催

**Comment by XiaoDaiGua-Ray** [comment]
这个有点让人难受，因为这个问题，暂时我还找不到更好的方法。官方大大好像也在忙其他的事情，库没怎么更新了。

**Comment by jahnli** [comment]
> 这个有点让人难受，因为这个问题，暂时我还找不到更好的方法。官方大大好像也在忙其他的事情。

等待发布

**Comment by AshleyFang** [comment]
预计什么时候发布  问题版本在线上很难受

**Comment by jizai1125** [comment]
> 预计什么时候发布  问题版本在线上很难受

发了已经，2.38.2
