### ISSUE TITLE
data-table使用表头分组后排序不生效

### ISSUE THREAD

**Issue by adele-ty** [tusen-ai/naive-ui#5758]
### 问题的清晰而简明的描述

当我添加children属性来使用表头分组后，我希望某一列可以排序，因此我添加了sorter，这一列的右侧出现了向上向下箭头，但是点击之后数据并没有排序

### 建议的解决方案

----

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by hey-yuxiong** [comment]
如果非后端排序，则表格的remote要设置为false

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by adele-ty** [comment]
> 如果非后端排序，则表格的remote要设置为false

感谢
