### ISSUE TITLE
n-menu无法正常实现h()渲染

### ISSUE THREAD

**Issue by AQian-Cup** [tusen-ai/naive-ui#5768]
### 描述错误

在本机中，出现了渲染失败的情况，无法显示文字，也无法执行跳转
![image](https://github.com/tusen-ai/naive-ui/assets/61798525/a4138051-b64d-439f-a279-5fe764975858)

在最小复现中，则出现了这样的报错（可能是限制更加严格的原因，什么内容都没有出现）
![image](https://github.com/tusen-ai/naive-ui/assets/61798525/6cf45395-1154-4ebc-adb1-e8dddf8cc26e)

@vnode-* hooks in templates are no longer supported. Use the vue: prefix instead. For example, @vnode-mounted should be changed to @vue:mounted. @vnode-* hooks support has been removed in 3.4.

推测是Vue v3.4的更新导致的API兼容问题，但是label使用string类型是可以正常显示的

### 复现步骤

使用Vue v3.4以上版本在n-menu组件中使用h()渲染即可

### 最小复现链接

https://codesandbox.io/p/devbox/naive-ui-menu-jdmpl5?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltidgxc90007356gvmlw72wy%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltidgxc90002356gvlrx2bgm%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltidgxc90004356gqjsx33f7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltidgxc90006356g25jengm6%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltidgxc90002356gvlrx2bgm%2522%253A%257B%2522id%2522%253A%2522cltidgxc90002356gvlrx2bgm%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltidgxc90006356g25jengm6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltidgxc90005356gpurixtqj%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltidgxc90006356g25jengm6%2522%252C%2522activeTabId%2522%253A%2522cltidgxc90005356gpurixtqj%2522%257D%252C%2522cltidgxc90004356gqjsx33f7%2522%253A%257B%2522id%2522%253A%2522cltidgxc90004356gqjsx33f7%2522%252C%2522activeTabId%2522%253A%2522cltidikc2001x356g1lww8lco%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltidgxc90003356gogsrip8m%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%257D%252C%257B%2522id%2522%253A%2522cltidikc2001x356g1lww8lco%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cltidiiyq00g8d9hu0a3bgpei%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### 系统信息

```Shell
System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 7840H  w/ Radeon 780M Graphics
    Memory: 13.23 GB / 31.29 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE  
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD     
    pnpm: 8.15.3 - C:\Program Files\nodejs\pnpm.CMD   
    bun: 1.0.30 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (122.0.2365.66)
    Internet Explorer: 11.0.22621.1
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jahnli** [comment]
最小复现打不开

**Comment by AQian-Cup** [comment]
@jahnli 调成public了

**Comment by zenggfhcs** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/84555524/eb45b10a-ddbe-4092-b64b-64d2f78b4881) 你用了花括号包住了 h()，但是没有return

**Comment by zenggfhcs** [comment]
你要么去除包住 h() 的 {} ， 要么 在 h() 前加 return
