### ISSUE TITLE
遇到 NModal 组件 api 没触发 on-after-enter 的问题

### ISSUE THREAD

**Issue by baicaiit** [tusen-ai/naive-ui#5772]
### 问题的清晰而简明的描述

我在 axios 中某个逻辑出调用方法让 pinia 中的loginDialog状态为true, 从而让 NModal 组件显示
![image](https://github.com/tusen-ai/naive-ui/assets/42630572/20e072e2-d8ba-4156-9d90-db16d5af2324)
![image](https://github.com/tusen-ai/naive-ui/assets/42630572/2cc42438-605c-47db-a0fe-656f03803dc1)
但是现在遇到一个问题, 组件是显示出来了, 但没触发 on-after-enter 
![image](https://github.com/tusen-ai/naive-ui/assets/42630572/436e0a19-07d4-4b05-ab8b-e9f1cc44650f)

请问一下是这是 bug 还是我的用法有问题呢?

### 建议的解决方案

暂无提供描述

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by jahnli** [comment]
Provide a based on CodeSandbox or stackblitz [Minimal, Reproducible Example] (https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
