### ISSUE TITLE
tabs切换tab-pane崩溃(Tabs crashes when switch tab pane)

### ISSUE THREAD

**Issue by herokilito** [tusen-ai/naive-ui#5782]
### Describe the bug

多切换几次tab-pane会报错，然后整个tabs无法使用(Switching tab pane multiple times will result in an error, and the entire tab will become unusable)

### Steps to reproduce

在tsx中使用tabs组件 (Using the tabs component in tsx)
``` ts
const firstPartyPlugins = ref(['执行作业', '文件分发'])
...
return () => (
  <NTabs type='line' placement='left'>
    {firstPartyPlugins.value.map((e: any) => {
      return (
        <NTabPane name={e} tab={e}>
          {e}
        </NTabPane>
      )
    })}
    </NTabs>
)
...
```
然后切换4到5次tab-pane，就出现了以下的错误 (Then switching tab pane 4 to 5 times resulted in the following error)
![20240313155901](https://github.com/tusen-ai/naive-ui/assets/52948383/f2d76f21-2885-4e68-b0c4-aa23ea5497bd)
![20240313155742](https://github.com/tusen-ai/naive-ui/assets/52948383/95539ca8-fd74-4662-b70a-1b3b12cabe4e)

### Link to minimal reproduction

https://www.naiveui.com/zh-CN/light/components/tabs

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (32) x64 AMD Ryzen 9 7945HX with Radeon Graphics
    Memory: 10.36 GB / 31.18 GB
  Binaries:
    Node: 16.13.1 - D:\App\nvm\nodejs\node.EXE
    npm: 8.1.2 - D:\App\nvm\nodejs\npm.CMD
    pnpm: 6.32.6 - D:\App\nvm\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.80)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    naive-ui: ^2.38.1 => 2.38.1
    vue: ^3.2.47 => 3.2.47
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Zheng-Changfu** [comment]
无法复现，请提供案例

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
