### ISSUE TITLE
Slide组件设置了marks后，点击mark跳转的数值并不准确

### ISSUE THREAD

**Issue by WT-SML** [tusen-ai/naive-ui#5785]
### 描述错误

![image](https://github.com/tusen-ai/naive-ui/assets/51842002/23ecc663-d30a-4bb4-a598-b6d6a7286115)
如图，mark为37，但是点击这个mark并不是准确的跳转到37，而是会在37附近浮动。
当然我大概能够理解是什么样的实现方式导致了这样的结果。
但我认为，精准的跳转到mark所指的值才是正确的现象。毕竟，mark之外的空白地方并不可以点击对吗？

### 复现步骤

地址：https://www.naiveui.com/zh-CN/light/components/slider#restrict-selectable-values.vue

### 最小复现链接

https://www.naiveui.com/zh-CN/light/components/slider#restrict-selectable-values.vue

### 系统信息

```Shell
win10;chrome v120;
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by hmydgz** [comment]
step="mark" 时会精确跳转

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
