### ISSUE TITLE
NSelect 如果 option 禁用则清空

### ISSUE THREAD

**Issue by realByg** [tusen-ai/naive-ui#5788]
### 问题的清晰而简明的描述

在表单联动时，如果 `NSelect` 的 `options` 如果被动态改变，且选中的值的 `disabled` 属性为 `true`，则需要手动遍历 `options` 来清空值。

### 建议的解决方案

增加类似 `clear-if-option-disabled` 选项

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by XueHua-s** [comment]
这个完全没必要加属性了吧。你在组件外自己加逻辑也是一样的啊
