### ISSUE TITLE
Ellipsis 组件透传 class 无效（Ellipsis component passthrough class is invalid）

### ISSUE THREAD

**Issue by Nakus0426** [tusen-ai/naive-ui#5790]
### 描述错误

`Ellipsis` 组件上透传的 `class` 属性无效
在 devtools 中可以看到 `class` 已经被透传至组件的根节点，但 `class` 却无法生效
![image](https://github.com/tusen-ai/naive-ui/assets/41540888/02ed1f42-dcaf-467e-be9a-5b4328189c61)

### 复现步骤

1.在 `Ellipsis` 组件上添加 `class` 属性
2.在 `style` 中为 `class` 编写样式
3.运行查看 `class` 属性是否生效

### 最小复现链接

https://codesandbox.io/p/sandbox/stoic-franklin-cxl6s9?file=%2Fsrc%2FDemo.vue%3A5%2C12

### 系统信息

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 2.79 GB / 15.71 GB
Binaries:
    Node: 18.19.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.12.0 - C:\Program Files\nodejs\pnpm.CMD
Browsers:
    Edge: Chromium (122.0.2365.92)
    Internet Explorer: 11.0.22621.1
npmPackages:
    naive-ui: ^2.38.1 => 2.38.1
    vue: ^3.4.21 => 3.4.21
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jahnli** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/20943608/bf9a3c26-192f-427b-a97d-44b079909d1a)

检查下透传的写法

**Comment by Nakus0426** [comment]
> ![image](https://private-user-images.githubusercontent.com/20943608/313582304-bf9a3c26-192f-427b-a97d-44b079909d1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NDY2OTcsIm5iZiI6MTcxMDc0NjM5NywicGF0aCI6Ii8yMDk0MzYwOC8zMTM1ODIzMDQtYmY5YTNjMjYtMTkyZi00MjdiLWE5N2QtNDRiMDc5OTA5ZDFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA3MTk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzNTZiNjBmOGJiYjJiYzE4YTU3MzEyZTVhNzhhMGI4OTA4NjhiZDhlMDU0ZjQyZjk5MmVkMjA4NzMyODJmYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5rFGwvCVMGvr_1HK6n4dFe94ZNlg7YdA7VkKLzQrmJQ)
> 
> 检查下透传的写法

应该是 `scoped` 的问题，使用样式穿透后是能生效的
但这个现象与 [vue文档](https://cn.vuejs.org/api/sfc-css-features.html#child-component-root-elements) 的描述不太相符
![image](https://github.com/tusen-ai/naive-ui/assets/41540888/2a845983-4d1a-4523-bb83-630640f747e7)
从 devtools上看，`class` 已经作用到了根元素，是不是文档上的“根元素”指的是源码中的根元素？

**Comment by jahnli** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/20943608/d1df0bdc-9d69-4d06-926a-2f6ec606e211)

**Comment by jahnli** [comment]
如果使用 scoped 可以通过 :deep(父节点  当前节点) 命中

**Comment by Nakus0426** [comment]
使用 css module 也能解决这个问题，这样就不需要 :deep() 了
