### ISSUE TITLE
n-switch组件使用useToggle时切换过渡动画失效

### ISSUE THREAD

**Issue by estoi** [tusen-ai/naive-ui#5795]
### 描述错误

当我在`n-switch`组件的`@update:value`中调用`vueuse`的`useToggle`API时，组件切换的过渡动画失效

### 复现步骤

```javascript
// script
const toggleDark = useToggle(isDark);
```
```vue
// template
<n-switch
  v-model:value="darkMode"
  @update:value="toggleDark"
  size="medium"
>
// others
</n-switch>
```

https://github.com/tusen-ai/naive-ui/assets/44252820/4c4c9529-e029-49da-93b7-d15d8cff8140

### 最小复现链接

https://codepen.io/estoi/pen/OJGWevY?editors=1111

### 系统信息

```Shell
System:
    OS: macOS 12.7.4
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 126.46 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 21.6.2 - ~/.nvm/versions/node/v21.6.2/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v21.6.2/bin/npm
    bun: 1.0.29 - ~/.bun/bin/bun
  Browsers:
    Chrome: 122.0.6261.129
    Safari: 17.4
  npmPackages:
    naive-ui: ^2.38.1 => 2.38.1 
    vue: ^3.4.21 => 3.4.21
```

### 使用的包管理器

npm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jizai1125** [comment]
没看懂，你的复现代码跟你问题有什么关系么

**Comment by estoi** [comment]
> 没看懂，你的复现代码跟你问题有什么关系么

就是我的页面中有一个`n-switch`组件，我在组件的`@update:value`上绑定了一个事件，该事件调用了`vueuse`的`useToggle`方法，就会出现`n-switch`切换开关的过渡动画没有效果，如果我把`@update:value`上绑定的事件换成一个空函数或者去掉，过渡动画又正常了

**Comment by jizai1125** [comment]
> > 没看懂，你的复现代码跟你问题有什么关系么
> 
> 就是我的页面中有一个`n-switch`组件，我在组件的`@update:value`上绑定了一个事件，该事件调用了`vueuse`的`useToggle`方法，就会出现`n-switch`切换开关的过渡动画没有效果，如果我把`@update:value`上绑定的事件换成一个空函数或者去掉，过渡动画又正常了

好像是 useDark 影响了过渡效果

**Comment by estoi** [comment]
> > > 没看懂，你的复现代码跟你问题有什么关系么
> > 
> > 
> > 就是我的页面中有一个`n-switch`组件，我在组件的`@update:value`上绑定了一个事件，该事件调用了`vueuse`的`useToggle`方法，就会出现`n-switch`切换开关的过渡动画没有效果，如果我把`@update:value`上绑定的事件换成一个空函数或者去掉，过渡动画又正常了
> 
> 好像是 useDark 影响了过渡效果

我也发现了，明暗切换的过渡效果也没有了，已经换成其他组件了
