### ISSUE TITLE
Modal、 Drawer等组件的关闭弹窗事件能否支持阻止关闭？

### ISSUE THREAD

**Issue by zuihou** [tusen-ai/naive-ui#5801]
### 问题的清晰而简明的描述

在使用Modal、 Drawer等组件 等组件时， 若触发`on-esc`、`on-mask-click`、点击右上角关闭按钮等事件时，根据用户返回值决定是否关闭弹窗或抽屉

### 建议的解决方案

根据事件的返回值或其他方案，决定是否关闭

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by zuihou** [comment]
比如，我在检测到弹窗的表单数据发生修改时， 用户按下esc键，阻止用户关闭弹窗。

**Comment by jahnli** [comment]
`close-on-esc`  

https://www.naiveui.com/zh-CN/os-theme/components/modal#controlled.vue
https://www.naiveui.com/zh-CN/os-theme/components/dialog#async.vue

**Comment by zuihou** [comment]
close-on-esc 属性只是禁止用户点击 esc 时，关闭弹窗。

需求是:
1. close-on-esc 设置为true，允许用户使用esc关闭弹窗， 但程序检测到表单改动时，**可以通过on-esc 或者其他事件阻止框架关闭弹窗**。
2. closable 设置为true，允许用户点击右上角关闭按钮关闭弹窗， 但程序检测到表单改动时，**可以通过 某个事件阻止框架关闭弹窗**。


上面需求中： 程序检测到表单改动时，可以交给业务框架自己判断， 但上述中的加粗字体有没有办法能实现？

**Comment by jahnli** [comment]
通过自定义 `close-on-esc`  `closable` 实现业务逻辑

检测表单改动修改对应的值

**Comment by jahnli** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/20943608/9139ca27-3684-4405-ad6d-21b1b986de5e)

**Comment by zuihou** [comment]
<img width="1460" alt="image" src="https://github.com/tusen-ai/naive-ui/assets/8500410/3a82764c-3446-433a-b8ba-f9da6585cc26">
另外，drawer组件的 to 属性， 有什么讲究没？ 是否支持父级容器？ 目前发现 父子级太深时，就会失效

比如： 

```
<div id="div1">
<div  >
<div  >
<div  >
<n-button @click="xxx" />
<n-drawer to='#div1' v-model:show="xxxxxx" />
</div>
</div>
</div>
</div>
```

**Comment by jahnli** [comment]
我没具体看，看样子是 `Teleport`
