### ISSUE TITLE
Select在展开一次下拉列表后，再次点击无法展开

### ISSUE THREAD

**Issue by in-vane** [tusen-ai/naive-ui#5804]
### Describe the bug

如题

### Steps to reproduce

按文档复制粘贴的，感觉是特定情况下的问题

### Link to minimal reproduction

对不起我不怎么会使用codesandbox

### System Info

```Shell
maxOS
Vue3 + Vite 的 Electron 项目
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by nooooooom** [comment]
能否提供复现视频，或者将复现代码上传至 GitHub 上，这样方便我们帮你排查问题

**Comment by nooooooom** [comment]
我使用你提供的依赖试了以下，发现交互上没有什么问题，但是从元素属性的变化上来看应该是 `vShow` 的处理有问题。菜单正常触发了 `Transition` 的动画，但是 `vShow` 控制的 `display` 却没有变化。
![image](https://github.com/tusen-ai/naive-ui/assets/61452855/5227e4f0-5d9e-41d0-a052-f88f06742634)

然后在 Vue 的 Issues 上面搜了以下果然发现了[问题所在](https://github.com/vuejs/core/issues/10294) ，解决方式就是升级 Vue 的版本到 `3.4.17` 以上
```diff
- "vue": "^3.4.15"
+ "vue": "^3.4.17"
```

你下次还可以提供更详细的 `pnpm-lock.yaml` 或者 `yarn.lock` 来协助我们排查依赖版本上的问题，因为 `dependencies` 上面的数字版本跟实际下载的版本可能不一致。

**Comment by in-vane** [comment]
哇！感谢！受教啦！
