### ISSUE TITLE
Select 组件 render-label 和 value-field 同时使用

### ISSUE THREAD

**Issue by zuihou** [tusen-ai/naive-ui#5809]
### 问题的清晰而简明的描述

```
const formState = reactive({
  orgList: [ {id: '1', name: '111', type: '1'1}, {id: '2' , name: '2' , type: '2'} ] 
  orgId: ''
});

function renderLabel(option: SelectOption): VNodeChild {
  return [
    h(
      NTag,
      { type: ORG_TYPE_TAG_MAP.get(option.type), class: 'mr-2' },
      { default: () => ORG_TYPE_MAP.get(option.type) }
    ),
    option.name as string
  ];
}

<NSelect v-model:value="formState.orgId" :options="formState.orgList"  value-field='id' :render-label="renderLabel"></NSelect>
```

上述代码，能正常渲染下拉框， 但在选中后，无法回显。

<img width="272" alt="image" src="https://github.com/tusen-ai/naive-ui/assets/8500410/1cb55982-f798-431c-999e-5a5b8edd56c6">

### 建议的解决方案

支持 render-label 和 value-field 同时使用

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by jahnli** [comment]
提供个复现链接

**Comment by zuihou** [comment]
> 提供个复现链接

https://github.com/zuihou/soybean-admin/blob/main/src/views/multi-menu/first_child/index.vue

**Comment by zouhgithub** [comment]
我也遇到了跟你一模一样的问题 这个解决了嘛

**Comment by jahnli** [comment]
Provide a based on CodeSandbox or stackblitz [Minimal, Reproducible Example] (https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by jahnli** [comment]
> > 提供个复现链接
> 
> https://github.com/zuihou/soybean-admin/blob/main/src/views/multi-menu/first_child/index.vue

Provide a based on [CodeSandbox](https://codesandbox.io/templates/vue-vite) or [stackblitz](https://stackblitz.com/edit/vitejs-vite) [Minimal, Reproducible Example] (https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
