### ISSUE TITLE
The n-date-picker

### ISSUE THREAD

**Issue by Vinifn1** [tusen-ai/naive-ui#5810]
### Describe the bug

When using the month component of n-date-picker, instead of the system outputting the month I selected, it is showing the next month, I noticed this behavior in the test components within the lib on the naive.ui website

### Steps to reproduce

Just choose the year and the month to see
![image](https://github.com/tusen-ai/naive-ui/assets/80017331/fe061be4-ae2e-48d5-91a5-594d5a27160b)

### Link to minimal reproduction

https://www.naiveui.com/en-US/os-theme/components/date-picker#month.vue

### System Info

```Shell
Inside the lib
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
seems to have been fixed in the new version, If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
