### ISSUE TITLE
show-menu

### ISSUE THREAD

**Issue by alan4021** [tusen-ai/naive-ui#5813]
### Describe the bug

浮动按钮中的菜单显示使用show-menu之后无法正常的收起菜单

### Steps to reproduce

  <n-float-button
    :bottom="'132px'"
    :right="'132px'"
    position="fixed"
    type="primary"
    menu-trigger="click"
    :show-menu="true"
  >
    <n-icon>
      <cash-icon />
    </n-icon>
    <template #menu>
      <n-float-button shape="square" type="primary">
        <n-icon>
          <cash-icon />
        </n-icon>
      </n-float-button>
      <n-float-button>
        <n-icon>
          <cash-icon />
        </n-icon>
      </n-float-button>
      <n-float-button>
        <n-icon>
          <cash-icon />
        </n-icon>
      </n-float-button>
    </template>
  </n-float-button>

### Link to minimal reproduction

对不起我不怎么会使用codesandbox

### System Info

```Shell
"typescript": "^5.3.3",
"vue": "^3.4.19",
"vite": "^5.1.4",
"naive-ui": "^2.38.1",
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by nooooooom** [comment]
这是因为受控模式导致的，菜单会优先使用 `show-menu` 这个 `props` 来控制显示状态。

你将 `show-menu` 设置为 `true` 的需求是什么呢，或许我们可以根据需求来探讨更好的使用方式。

**Comment by alan4021** [comment]
> 这是因为受控模式导致的，菜单会优先使用 `show-menu` 这个 `props` 来控制显示状态。
> 
> 你将 `show-menu` 设置为 `true` 的需求是什么呢，或许我们可以根据需求来探讨更好的使用方式。

我希望是初始状态为显示让用户知道这个菜单有哪些功能，然后为了为了方便阅读，可以对菜单进行收缩和展开

**Comment by nooooooom** [comment]
> > 这是因为受控模式导致的，菜单会优先使用 `show-menu` 这个 `props` 来控制显示状态。
> > 你将 `show-menu` 设置为 `true` 的需求是什么呢，或许我们可以根据需求来探讨更好的使用方式。
> 
> 我希望是初始状态为显示让用户知道这个菜单有哪些功能，然后为了为了方便阅读，可以对菜单进行收缩和展开

创建一个初始值为 `true` 变量，假设是 `const showMenu = ref(true)`，然后给组件加上 `v-model:show-menu="showMenu"` 应该就可以解决了。

这个组件有一个特征是，鼠标外部移动会使 `FloatButton` 自动隐藏。如果你希望用户在首次碰到 `FloatButton` 的之前 `FloatButton` 不要自动隐藏，你可以自主监听 `mousemove` 事件，然后调控 `showMenu` 的受控行为，例如：
```ts
const floatButtonRef = ref();

const showMenu = ref(true);
let allowModifyShowMenu = false;

const setShowMenu = (value: boolean) => {
  if (allowModifyShowMenu) {
    showMenu.value = value;
  }
};

const handleMousemove = (e: MouseEvent) => {
  if (floatButtonRef.value?.$el.contains(e.target)) {
    allowModifyShowMenu = true;
    document.removeEventListener("mousemove", handleMousemove);
  }
};

document.addEventListener("mousemove", handleMousemove);
```

这里是在线用例 https://codesandbox.io/p/sandbox/wonderful-lovelace-vc32yp?file=%2Fsrc%2FDemo.vue%3A41%2C1-59%2C57

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
