### ISSUE TITLE
【n-select】能不能手动focus的时候，自动将下拉框打开

### ISSUE THREAD

**Issue by yuanhongyu123** [tusen-ai/naive-ui#5814]
### Clear and concise description of the problem

使用场景是，配合vxetable的编辑表格，我设置了autofocus，但是实际效果是，点到select中的时候，仅仅是光标进去了，下拉框没有自动展开
:edit-render="{ autofocus: '.n-base-selection-input' }"

### Suggested solution

无

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by nooooooom** [comment]
`show-on-focus` 这个 `props` 支持在聚焦时展示菜单，它在 `2.34.3` 及以上的版本被支持使用。

**Comment by yuanhongyu123** [comment]
好的，感谢，眼挫没看到文档这个属性
