### ISSUE TITLE
导出excel乱码

### ISSUE THREAD

**Issue by Xunjw** [tusen-ai/naive-ui#5819]
### Describe the bug

![image](https://github.com/tusen-ai/naive-ui/assets/31274660/528bbe15-b8be-4af1-a2da-e31bedc922e8)

### Steps to reproduce

tableRef.value?.downloadCsv({
    fileName: "sorter-filter",
    keepOriginalData: false
  })
导出中文数据乱码，CsvOptionsType对象不能设置字符编码？

### Link to minimal reproduction

无

### System Info

```Shell
无
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
提供个最小复现链接

**Comment by Xunjw** [comment]
> 提供个最小复现链接

没有办法提供链接，你导出中文内容试试？

**Comment by sleep1223** [comment]
![image](https://github.com/user-attachments/assets/93cdd108-5b36-4356-9c57-dbf104196f4f)

修改文件编码为 utf-8(带签名)

**Comment by hecktlaspha** [comment]
> Excel打开CSV文件时，默认会使用gbk编码，能否将导出的目标CSV文件的编码作为一个参数传入？

浏览器等其他`JavaScript`环境通过`TextEncoder`和`TextEncoder`支持任意的解编码, 但是node环境下面对gbk之类屎山字符集需要调包. [iconv-lite](https://github.com/ashtuchkin/iconv-lite)是支持`gbk`系列的屎山编码的. 不知道环境的话, 建议调包转码避免自己坑自己.
转换csv也可以用`deno`的标准库解决, [@std/csv](https://jsr.io/@std/csv). 一个`Array<Entity>`和一个`Array<ColumnName>`就行.
