### ISSUE TITLE
Upload 组件 data 属性为函数时，直接获取形参 file.name 返回 undefined

### ISSUE THREAD

**Issue by lingkai5wu** [tusen-ai/naive-ui#5825]
### 描述错误

Upload 组件 data 属性为函数，即 ({ file: UploadFileInfo }) => Object 时，直接获取形参 file.name 返回 undefined。

### 复现步骤

运行最小复现，观察控制台输出如下

![image](https://github.com/tusen-ai/naive-ui/assets/53172425/1037497c-9975-485e-88ec-29b6a69385c4)

### 最小复现链接

https://gist.github.com/lingkai5wu/e7bb39467fd99c8d316cb8671b2f34ee

### 系统信息

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
    Memory: 3.07 GB / 15.94 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.92)
    Internet Explorer: 11.0.22621.1
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jahnli** [comment]
提供个最小官网复现链接

**Comment by lingkai5wu** [comment]
抱歉，是我误将 `({ file: UploadFileInfo }) => Object` 当成 `(file: UploadFileInfo) => Object` 了，已解决。
不过单个变量为什么要这么设计，不太理解...

**Comment by lingkai5wu** [comment]
小建议，将文档修改为 `({ file }: { file: UploadFileInfo }) => Object`，既符合 ts 语法，也能避免与 ` (file: UploadFileInfo) => Object` 混淆
