### ISSUE TITLE
[Feature request]: NPagination support size

### ISSUE THREAD

**Issue by cnguu** [tusen-ai/naive-ui#583]
### This function solves the problem (这个功能解决的问题)
Resizing components
### Expected API (期望的 API)
```
<NPagination size="small" />
```
Similarly, the pagination in NDataTable

**Comment by 07akioni** [comment]
想要多小？

**Comment by cnguu** [comment]
> How small do you want?

link the button `tiny`

**Comment by M1CK431** [comment]
It seems to be implemented since v2.29.0: https://www.naiveui.com/en-US/light/components/pagination#size.vue
So I guess this issue should be closed?
