### ISSUE TITLE
n-select组件添加失焦后更新值属性

### ISSUE THREAD

**Issue by Mobaiyufengfei** [tusen-ai/naive-ui#5834]
### Clear and concise description of the problem

n-select可以添加一个属性让用户选择是在失焦后更新绑定值还是实时更新绑定值

### Suggested solution

与n-input-number的update-value-on-input一样，为false代表失焦后更新绑定值，为true代表实时更新绑定值

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jahnli** [comment]
@Mobaiyufengfei  这种是不是只适用于多选的情况下

**Comment by jahnli** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/20943608/39418a1a-fdfe-4b2d-be06-845bd1703fc0)

期望的是多选时点击选中，但图中马赛克区域的输入框不更新， 等失焦时更新 ？

**Comment by Mobaiyufengfei** [comment]
不是多选，就是我可以切换好几次我选中的select选项，这个过程中input框中显示的值是会随着更新的，但是不会触发绑定值的更新，等到我点组件外面的区域，让组件失去焦点后再更新绑定的值

**Comment by Mobaiyufengfei** [comment]
> @Mobaiyufengfei 这种是不是只适用于多选的情况下

不是多选，就是我可以切换好几次我选中的select选项，这个过程中input框中显示的值是会随着更新的，但是不会触发绑定值的更新，等到我点组件外面的区域，让组件失去焦点后再更新绑定的值

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
