### ISSUE TITLE
组件文档 出现错误

### ISSUE THREAD

**Issue by Ale6333499** [tusen-ai/naive-ui#5835]
### 描述错误

![image](https://github.com/tusen-ai/naive-ui/assets/113077418/ae7d9449-48e3-45e3-a1d6-d3450779eed4)

### 复现步骤

在文档中滑入按钮后 切换菜单 不生效，发现控制台报错阻塞

### 最小复现链接

https://www.naiveui.com/zh-CN/light/components/float-button

### 系统信息

```Shell
谷歌浏览器
```

### 使用的包管理器

npm

### 验证

- [x] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by Ale6333499** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/113077418/c6ba7dd3-0416-4ee5-9e9b-098c2bf56a73)
鼠标滑入此按钮就会报错

**Comment by baicie** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/44311483/d05d1aa3-166b-4516-adea-93d5e715ed79)
我尝试去看了看这个问题，发现把这块的withDirectives去掉就没问题，错误的原因是因为新的vnode.dirs长度多1在循环时无法在旧的vnode.dirs[i]获取有效值。如果有人知道为什么导致请告诉我，我看了一下午没找出来qaq

**Comment by jahnli** [comment]
等待新版发布
