### ISSUE TITLE
Seeking offline API documentation

### ISSUE THREAD

**Issue by LianSchedule** [tusen-ai/naive-ui#5838]
### 问题的清晰而简明的描述

Dear developer, could you please provide a PDF version of the API documentation? Thank you very much for your efforts

### 建议的解决方案

Provide downloadable files

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by jahnli** [comment]
`md`   可以尝试自己转换
