### ISSUE TITLE
N-Grid: v-for 遍历样式错误

### ISSUE THREAD

**Issue by hhstore** [tusen-ai/naive-ui#5847]
### 描述错误

- `n-grid` + `v-for` 遍历时, `n-gi` 样式错误, 并不是网格模式, 而是列表模式. 
- 原因是展开的 for 循环, 样式层次错误. 

## 问题复现代码:

- ✅ 如下我给出了完整的复现代码, 以及 hack 的正确样式效果. 
- ✅ 前一个示例, 是 `n-grid` 组件, 默认生成的有问题的示例. (浏览器 debug 模式, 很容易发现 for 展开, 样式层次错了)
- ✅ 后一个示例, 是我根据 `n-grid` 生成的示例样式, hack 手写的正确样式. 

```html

<template>
  <h5 style="color: red">N-Grid + `v-for` (Bug)</h5>

  <n-grid
    v-for="d in data"
    :key="d"
    :cols="3"
    :x-gap="10"
    :y-gap="10"
    class=""
    style="gap: 10px"
  >
    <n-gi>
      <button style="background-color: cadetblue">{{ d }}</button>
    </n-gi>
  </n-grid>

  <h5 style="color: green">N-Grid + `v-for` Hotfix</h5>

  <div
    class=""
    style="
      width: 100%;
      display: grid;
      grid-template-columns: repeat(3, minmax(0px, 1fr));
      gap: 10px;
    "
  >
    <!--    hotfix !!! v-for 默认生成的样式结构是错的. for 层次错了 -->
    <div v-for="d in data" :key="d">
      <div style="grid-column: span 1 / span 1">
        <button style="background-color: lightgreen">{{ d }}</button>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
const data = ['1', '2', '3', '4'];
</script>

```

### 截图效果:

- 对应上述代码的效果:

<img width="600" alt="image" src="https://github.com/tusen-ai/naive-ui/assets/3252130/0d0ed18a-613e-49c3-99bd-8afb7bb8a7c0">

### 最小复现链接

https://codepen.io/hhstore/pen/GRLxNqM

### 系统信息

```Shell
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 92.91 MB / 32.00 GB
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.15.0 - ~/Library/Caches/fnm_multishells/5836_1712479309231/bin/node
    Yarn: 1.22.22 - ~/Library/Caches/fnm_multishells/5836_1712479309231/bin/yarn
    npm: 9.5.0 - ~/Library/Caches/fnm_multishells/5836_1712479309231/bin/npm
    pnpm: 8.6.3 - ~/Library/pnpm/pnpm
  npmPackages:
    naive-ui: ^2.38.1 => 2.38.1 
    vue: ^3.2.47 => 3.4.21
```

### 使用的包管理器

yarn

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by hhstore** [comment]
## `n-grid` + `v-for` 编译出来的代码: 

- 对比可以发现, `n-grid` + `v-for`, 生成的代码, 迭代的样式层次错了, 这个 bug 应该很好修. 

<img width="600" alt="image" src="https://github.com/tusen-ai/naive-ui/assets/3252130/ec57c79f-b54a-430c-8401-93c050eaf05d">

**Comment by jizai1125** [comment]
`v-for` 放错地方了吧，应该遍历 `n-gi` 才对
```vue
  <n-gi
    v-for="d in data"
```

**Comment by hhstore** [comment]
@jizai1125 

- 是的. 通过浏览器 debug 分析, 生成的代码, 遍历层次错了. 
- 应该是比较容易修复的 bug.

**Comment by jizai1125** [comment]
> @jizai1125
> 
> * 是的. 通过浏览器 debug 分析, 生成的代码, `v-for` 遍历层次错了.
> * 应该是比较容易修复的 bug.

不是，我意思是你自己代码写错了，v-for 放错地方了

**Comment by hhstore** [comment]
> > @jizai1125
> > 
> > * 是的. 通过浏览器 debug 分析, 生成的代码, `v-for` 遍历层次错了.
> > * 应该是比较容易修复的 bug.
> 
> 不是，我意思是你自己代码写错了，v-for 放错地方了，应该放到 gi 上才对



- 确实. 改成这样. 就 OK 了.
- 对 `v-for` 层次的理解有点偏差. (我以为是外层迭代)😅
- (中间尝试在 `<n-gi> 外套一层 <div v-for>`, 也是错的)
- 是我搞错了. 问题关闭了. 

```html
  <n-grid :cols="3" :x-gap="10" :y-gap="10" class="" style="gap: 10px">
    <n-gi v-for="d in data" :key="d">
      <button style="background-color: cadetblue">{{ d }}</button>
    </n-gi>
  </n-grid>
```
