### ISSUE TITLE
switch icon can not update when theme is Dark

### ISSUE THREAD

**Issue by smilingovo** [tusen-ai/naive-ui#5850]
### Describe the bug

When I use the vueuse tool library to perform a theme's localstorage response, the icon does not update properly when the theme is dark by default

### Steps to reproduce

`<n-switch v-model:value="isDark" @update:value="toggleTheme" size="medium">
              <template #icon>
                <n-icon>
                  <i class="bi" :class="isDark ? 'bi-sun-fill' : 'bi-moon-fill'"></i>
                </n-icon>
              </template>
            </n-switch>`

### Link to minimal reproduction

none

### System Info

```Shell
"system":"windows10"
"naive-ui": "^2.38.1"
"@vueuse/core": "^10.9.0"
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by thibodeauxjl** [comment]
Have you tried: 

`<n-icon> <i class="bi" :class="{ 'bi-sun-fill': isDark,  'bi-moon-fill': !isDark }"></i> </n-icon>`

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
