### ISSUE TITLE
n-pagination 分页问题

### ISSUE THREAD

**Issue by Lin-w-b** [tusen-ai/naive-ui#5854]
### Describe the bug

当删除最后一页的最后一条数据时候，pagination没有自动跳到第一页
当在非第一页查询时候，非第一页没有数据，但是第一页有数据，没有自动跳到第一页

可以参考el-plus，会自动跳

### Steps to reproduce

当删除最后一页的最后一条数据时候，pagination没有自动跳到第一页
当在非第一页查询时候，非第一页没有数据，但是第一页有数据，没有自动跳到第一页

### Link to minimal reproduction

none

### System Info

```Shell
naive-ui 2.37.0
vue 3.2
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
提供个 `element-plus` 效果链接

**Comment by lwb0711** [comment]
你可以用一下element-plus的项目，在上面删除最后一页的最后一条数据时候，pagination会自动跳到第一页

**Comment by fushuaijiet** [comment]
我之前都是手动控制的

**Comment by lpint55** [comment]
我也遇到了同样的问题 将v-model:page修改后 @update:page并不会重新请求数据

**Comment by jahnli** [comment]
> 我也遇到了同样的问题 将v-model:page修改后 @update:page并不会重新请求数据

俩个最好别同时用，如果同时用注意先后顺序

**Comment by lpint55** [comment]
![1713617367506](https://github.com/tusen-ai/naive-ui/assets/103240521/fd34b7e7-615c-494c-8e5d-64e9d2f0df45)
我一起用了 但是我测试发现 如果我删除当前页的最后一条数据后 改变page的值并不会 触发@update:page 但是手动点击却是可以的

**Comment by lwb0711** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/51143752/eb791bd5-9660-495e-8e74-d49604923a43)

我是这样写的

**Comment by codeDevStory** [comment]
直接自己封装个hooks就完事了

**Comment by jahnli** [comment]
根据业务自己封装一层
