### ISSUE TITLE
上传组件中在删除文件时增加弹出确认框

### ISSUE THREAD

**Issue by xrhh** [tusen-ai/naive-ui#5858]
### 问题的清晰而简明的描述

在上传组件的文件列表中删除文件时可能误点删除按钮

### 建议的解决方案

在点删除时能弹出确认框

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by jahnli** [comment]
`on-remove`  业务上的逻辑，代码控制下就好了
