### ISSUE TITLE
table 使用斑马纹 不生效

### ISSUE THREAD

**Issue by sugar258596** [tusen-ai/naive-ui#5867]
### 描述错误

 <n-data-table :columns="columns" :data="data" striped />
![image](https://github.com/tusen-ai/naive-ui/assets/84883966/f2791304-2cab-4978-b49f-aa81ad35a0f4)

### 复现步骤

![image](https://github.com/tusen-ai/naive-ui/assets/84883966/376820c9-4004-4ca3-9100-5d649e0ec535)

### 最小复现链接

https://www.naiveui.com/zh-CN/os-theme/components/data-table

### 系统信息

```Shell
node:18.18.0
```

### 使用的包管理器

npm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jahnli** [comment]
官网没复现，请确保这是一个具体的 bug
