### ISSUE TITLE
n-menus增加一个失焦方法或n-menu的on-update:value回调能支持返回true/else

### ISSUE THREAD

**Issue by shaoerkuai** [tusen-ai/naive-ui#5869]
### Clear and concise description of the problem

背景：
当前我默认会渲染系统中所有的菜单项，这个菜单项对所有用户都是展示的，但是会在路由前置守卫进行跳转鉴权，如果无跳转权限，则通过mitt抛出一个无权限事件，并弹出一个message错误。
在我的header组件中，我把value绑定到当前选择的菜单key，前置守卫beforeEach抛出事件后，事件会带一个from的key，header组件收到后对当前选择的菜单进行重置（修改menu组件value双向绑定的值为之前的from key），目前效果如下：

![image](https://github.com/tusen-ai/naive-ui/assets/117460332/fd7beaf0-5450-4ba9-97fb-a578fffcf6c9)

确实能够正常重置，但当前有一个hover的颜色，需要用户手动点下其他地方才能恢复正常：
![image](https://github.com/tusen-ai/naive-ui/assets/117460332/84de4cfc-8497-4c42-b3f3-c89df4efdd94)

### Suggested solution

希望能加个失焦的method或者菜单选中回调可以从void变成boolean返回false时就代表跳转失败，，以便能抽出这个逻辑

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jahnli** [comment]
Provide a based on CodeSandbox or stackblitz [Minimal, Reproducible Example] (https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
