### ISSUE TITLE
在v-for里生成包含component的tab组件，切换时会反复触发onMounted

### ISSUE THREAD

**Issue by wangcn** [tusen-ai/naive-ui#5871]
例子无法复现

_Originally posted by @07akioni in https://github.com/tusen-ai/naive-ui/issues/4626#issuecomment-1550101472_
            
我最近也遇到这个issue里的问题。可通过以下代码复现。
`<template> 
<n-tabs type="card" animated> 
<n-tab-pane v-for="item in tabs" :key="item.key" :name="item.key" :tab="item.name"> <component :is="item.component" :key="item.key ? item.key : 'blank'" msg="aaa"> </component> 
</n-tab-pane>
</n-tabs> 
</template>`

**Comment by jahnli** [comment]
Provide a based on CodeSandbox or stackblitz [Minimal, Reproducible Example] (https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
