### ISSUE TITLE
There are some issues with the style of the official plugin when using the latest Nuxt 3.

### ISSUE THREAD

**Issue by Reknij** [tusen-ai/naive-ui#5873]
### 描述错误

The [Plugin](https://github.com/07akioni/naive-ui-nuxt-demo/blob/main/plugins/naive-ui.ts) in [Naive UI SSR doc](https://www.naiveui.com/en-US/dark/docs/ssr) don't load styles immediately.
I found the solution in a [Reddit post](https://www.reddit.com/r/Nuxt/comments/170ree2/my_naiveui_elements_dont_load_instantly/).

### 复现步骤

The website styles delayed styling on initial render or page refresh when using [Plugin](https://github.com/07akioni/naive-ui-nuxt-demo/blob/main/plugins/naive-ui.ts) from [Naive UI SSR doc](https://www.naiveui.com/en-US/dark/docs/ssr)

### 最小复现链接

https://github.com/Reknij/naive-ui-nuxt3-plugin-issue

### 系统信息

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 AMD Ryzen 5 5600H with Radeon Graphics
    Memory: 6.10 GB / 15.36 GB
  Binaries:
    Node: 18.17.1 - ~\AppData\Local\pnpm\node.EXE
    npm: 9.6.7 - ~\AppData\Local\pnpm\npm.CMD
    pnpm: 8.6.12 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    naive-ui: ^2.38.1 => 2.38.1
    vue: ^3.4.21 => 3.4.21
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by 07akioni** [comment]
We provide official nuxt plugin now. Check https://github.com/07akioni/naive-ui-nuxt-demo again.
