### ISSUE TITLE
官方网页在chrome浏览器打开，鼠标滚轮滚动会卡住无反应; 自己基于naive-ui写的项目也有这种情况

### ISSUE THREAD

**Issue by chuteany** [tusen-ai/naive-ui#5874]
### Describe the bug

官方网页在chrome浏览器打开，鼠标滚轮滚动会卡住无反应，而在edge 浏览器打开没有这种现象；
自己基于naive-ui写的项目也有这种情况

### Steps to reproduce

应该不用写复现步骤了吧

### Link to minimal reproduction

re

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i7-1255U
    Memory: 1.45 GB / 15.69 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.5 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.3 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.81)
    Internet Explorer: 11.0.19041.3636
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
未复现

**Comment by Azir-11** [comment]
未复现

**Comment by gaojiangtao-git** [comment]
提供demo  容易复现问题

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
