### ISSUE TITLE
Popover 组件中按钮为disabled 禁用状态时 弹层不出现

### ISSUE THREAD

**Issue by 1544039017** [tusen-ai/naive-ui#5876]
### 描述错误

Popover 组件中按钮为disabled 禁用状态时 弹层不出现

### 复现步骤

 <n-popover trigger="hover">
       <template #trigger>
            <n-button type="info" size="tiny" :disabled="true">VCR</n-button>
       </template>
        <span>VCR(Not Uploaded)</span>
   </n-popover>

:disabled="true"  弹层`VCR(Not Uploaded)` 不显示

### 最小复现链接

无

### 系统信息

```Shell
无
```

### 使用的包管理器

npm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by artsmp0** [comment]
<img width="896" alt="image" src="https://github.com/tusen-ai/naive-ui/assets/129932371/6cccd324-b7b1-458c-8cfe-0411900432f4">
看着是没啥问题

**Comment by jahnli** [comment]
提供的复现 [最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)
