### ISSUE TITLE
我想知道表格控件 如何选中默认行啊

### ISSUE THREAD

**Issue by JiaoZaiShiJie** [tusen-ai/naive-ui#5877]
### Describe the bug

我想知道表格控件 如何选中默认行啊
我用计算属性实现了 想问下有没有内置的 感觉文档有些东西缺少了点 也有可能我是第一次接触前端
麻烦大佬讲一下

### Steps to reproduce

1

### Link to minimal reproduction

1

### System Info

```Shell
1
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
`default-checked-row-keys`

or

`checked-row-keys`
