### ISSUE TITLE
Auto Complete放进 Modal时有错位问题

### ISSUE THREAD

**Issue by onlyJinx** [tusen-ai/naive-ui#5878]
### 描述错误

如图（右下角）

![bandicam 2024-04-17 23-41-16-000](https://github.com/tusen-ai/naive-ui/assets/21324835/5f15dd99-c78c-4b4c-b7ea-79f909a07df1)

### 复现步骤

```
<template>
  <n-button @click="showModal = true"> 来吧 </n-button>
  <n-modal v-model:show="showModal">
    <n-card
      style="width: 600px"
      title="模态框"
      :bordered="false"
      size="huge"
      role="dialog"
      aria-modal="true"
    >
      <n-auto-complete
        v-model:value="value"
        :input-props="{
          autocomplete: 'disabled',
        }"
        :options="options"
        placeholder="邮箱"
        clearable
      />
    </n-card>
  </n-modal>
</template>

<script lang="ts">
import { defineComponent, ref,computed } from "vue";

export default defineComponent({
  setup() {
  const valueRef = ref('')
    return {
      value: valueRef,
      options: computed(() => {
        return ['@gmail.com', '@163.com', '@qq.com'].map((suffix) => {
          const prefix = valueRef.value.split('@')[0]
          return {
            label: prefix + suffix,
            value: prefix + suffix
          }
        })
      })
      showModal: ref(false),
    };
  },
});
</script>

```

### 最小复现链接

https://codesandbox.io/p/sandbox/ancient-star-gjr633

### 系统信息

```Shell
不是系统问题
```

### 使用的包管理器

npm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jizai1125** [comment]
Simalar to https://github.com/tusen-ai/naive-ui/issues/4756#issuecomment-1519332273

**Comment by onlyJinx** [comment]
> 是由于 autoFocus 导致的，解决办法两种：
> 
> 1. 设置 `preset`；
> 2. `auto-focus` 设为 `false`
> 
> Simalar to [#4756 (comment)](https://github.com/tusen-ai/naive-ui/issues/4756#issuecomment-1519332273)

OK，设置了 auto-focus 后可以解决，谢谢啦
