### ISSUE TITLE
date pick 组件，绑定事件触发多次

### ISSUE THREAD

**Issue by tiny-dust** [tusen-ai/naive-ui#5886]
### 描述错误

date pick 组件，type="daterange"，绑定 confirm、update:value、update:format-value 等事件，在点击确定按钮时，会触发两次。

### 复现步骤

1. datepick组件，type="daterange"
2. 绑定 confirm等事件
3. 检查对应输出

### 最小复现链接

https://codesandbox.io/p/sandbox/goofy-curran-dshllc?file=%2Fsrc%2FDemo.vue%3A2%2C3-2%2C69&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clv6013q000063b6f1t2auzp5%2522%252C%2522sizes%2522%253A%255Bnull%252Cnull%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clv6013q000023b6f5bq018vi%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clv6013q000033b6fvu3ub6ac%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clv6013q000053b6f2xjdo0e7%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clv6013q000023b6f5bq018vi%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv6013pz00013b6fcnxdz4pf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clv601n3r003i3b6f69c1qhbc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A2%252C%2522startColumn%2522%253A3%252C%2522endLineNumber%2522%253A2%252C%2522endColumn%2522%253A69%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FDemo.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clv6013q000023b6f5bq018vi%2522%252C%2522activeTabId%2522%253A%2522clv601n3r003i3b6f69c1qhbc%2522%257D%252C%2522clv6013q000053b6f2xjdo0e7%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clv6013q000043b6fqbv65lo1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clv6013q000053b6f2xjdo0e7%2522%252C%2522activeTabId%2522%253A%2522clv6013q000043b6fqbv65lo1%2522%257D%252C%2522clv6013q000033b6fvu3ub6ac%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clv6013q000033b6fvu3ub6ac%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### 系统信息

```Shell
System:
    OS: macOS 14.4.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 19.32 MB / 16.00 GB
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 20.11.1 - /usr/local/bin/node
    npm: 10.4.0 - ~/.npm/bin/npm
    pnpm: 8.15.3 - ~/.npm/bin/pnpm
  Browsers:
    Safari: 17.4.1
  npmPackages:
    naive-ui: ^2.37.3 => 2.37.3 
    vue: ^3.4.15 => 3.4.15
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jizai1125** [comment]
没发现触发两次  https://codesandbox.io/p/sandbox/divine-sea-v8mpvx?file=%2Fsrc%2FDemo.vue%3A28%2C25

**Comment by jahnli** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/20943608/cfdb2132-cb5d-41c9-81cf-bb797399da9f)
未复现

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
