### ISSUE TITLE
filterable dropdown inputs (n-select, n-tree-select) won't close on click, only when blured  

### ISSUE THREAD

**Issue by ChenGutt** [tusen-ai/naive-ui#5902]
### Describe the bug

When passing the filterable prop to either n-select or n-tree-select, it is no longer possible to toggle the option menu. I can open it but I cannot close it. It will get closed only when blured. 

### Steps to reproduce

1. create a filterable n-select
2. try to toggle the menu open/close

alternatively: 
1. go to naive ui select element and search for the Filterable example : https://www.naiveui.com/en-US/os-theme/components/select 
2. try to toggle the menu

### Link to minimal reproduction

https://www.naiveui.com/en-US/os-theme/components/select

### System Info

```Shell
-
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
Provide a based on CodeSandbox or stackblitz [Minimal, Reproducible Example] (https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
