### ISSUE TITLE
希望Badge组件能够支持像ant design一样的【状态点】模式

### ISSUE THREAD

**Issue by 1010830256** [tusen-ai/naive-ui#5904]
### 问题的清晰而简明的描述

希望Badge组件能够支持像ant design一样的【状态点】模式

### 建议的解决方案

希望Badge组件能够支持像ant design一样的【状态点】模式

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by jahnli** [comment]
`dot`
