### ISSUE TITLE
能否将input框去空格的操作的默认值改成默认去空格 按需不去空格？

### ISSUE THREAD

**Issue by A-Yang-Git** [tusen-ai/naive-ui#5907]
### Clear and concise description of the problem

能否将input框去空格的操作的默认值改成默认去空格 按需不去空格？

### Suggested solution

能否将input框去空格的操作的默认值改成默认去空格 按需不去空格？

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by A-Yang-Git** [comment]
allow-input那个值

**Comment by Nakus0426** [comment]
讲真，还没见过有组件库输入框默认去空格的，太反直觉了

**Comment by jahnli** [comment]
自己封装下就可以了
