### ISSUE TITLE
UMD方式引入时报错，ReferenceError: naive is not defined

### ISSUE THREAD

**Issue by rysonliu** [tusen-ai/naive-ui#5908]
### 描述错误

在使用较低，但不是很低版本的浏览器，并且用UMD方式引入时，浏览器不兼容 ReferenceError: naive is not defined

### 复现步骤

1.使用较低版本chrome，例如：[https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/800850/](https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/800850/)
2.用上述版本浏览器访问官方文档的UMD演示页面：https://jsbin.com/mutewosewu/edit?html,console,output
3.js会有报错，页面也无法正常渲染
4.访问官方文档的非UMD方式导入的二维码组件页面是正常的：https://www.naiveui.com/zh-CN/os-theme/components/qr-code

### 最小复现链接

https://jsbin.com/mutewosewu/edit?html,console,output

### 系统信息

```Shell
chrome：87.0.4242.0
naiveUI：2.38.1
vue：latest
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by rysonliu** [comment]
本地报错截图显示是二维码组件部分的代码引起的：

![微信图片_20240428191021](https://github.com/tusen-ai/naive-ui/assets/55525541/fd3b2099-cca9-4c8c-b549-c467150b65ac)

**Comment by lisonge** [comment]
是 umd 的 build.target 没有设置或为 esnext  引起的

https://github.com/tusen-ai/naive-ui/blob/d1d306cfc3d5b51c32c2cf526978ac25c97e6177/rollup.config.js#L31-L40

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Static_initialization_blocks#browser_compatibility

根据 Static_initialization_blocks 的兼容性 chrome94，这意味着 naive-ui 的 umd 链接只能在 chrome94 以上工作

**Comment by rysonliu** [comment]
> 是 umd 的 build.target 没有设置或为 esnext  引起的
> 
> 
> 
> https://github.com/tusen-ai/naive-ui/blob/d1d306cfc3d5b51c32c2cf526978ac25c97e6177/rollup.config.js#L31-L40
> 
> 
> 
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Static_initialization_blocks#browser_compatibility
> 
> 
> 
> 根据 Static_initialization_blocks 的兼容性 chrome94，这意味着 naive-ui 的 umd 链接只能在 chrome94 以上工作
> 
> 
> 
> 
> 
> 

感谢答复！

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
