### ISSUE TITLE
DataTable Methods clearSorter bug

### ISSUE THREAD

**Issue by deiiviidas** [tusen-ai/naive-ui#5909]
### Describe the bug
removed becouse everything here is feature and not a bug

**Comment by deiiviidas** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/25092057/2ef210b6-1bdd-4b5a-aeb6-c2d1615d0eae)

**Comment by jahnli** [comment]
Provide the repetition of [minimum recurring example] (https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
