### ISSUE TITLE
Tree可以增加title、extra、icon等slot方便自定义

### ISSUE THREAD

**Issue by FaberSober** [tusen-ai/naive-ui#5911]
### 问题的清晰而简明的描述

Tree可以增加title、extra、icon等slot方便自定义

### 建议的解决方案

Tree可以增加title、extra、icon等slot方便自定义

title | 标题 | title: string |  
-- | -- | -- | --
extra | 渲染额外的节点内容 | - |  
drag-icon | 定制 drag 图标 | - |  
loading-icon | 定制 loading 图标 | - |  
switcher-icon | 定制 switcher 图标 | - |  
icon | 定制节点图标 | node: TreeNodeData | 

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by CandyACE** [comment]
可以通过renderLabel 来自定义渲染内容

**Comment by jahnli** [comment]
![Uploading image.png…]()
