### ISSUE TITLE
Select Slots  #header 如果是input框，input框聚焦不了

### ISSUE THREAD

**Issue by Y-Lao** [tusen-ai/naive-ui#5913]
### 描述错误
Select Slots #header 如果是input框，input框聚焦不了，无法输入

### 复现步骤

点击input聚焦

### 最小复现链接

https://codesandbox.io/p/sandbox/immutable-silence-ns82rp?file=%2Fsrc%2FDemo.vue

### 系统信息

```Shell
谷歌
```

### 使用的包管理器

yarn

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jahnli** [comment]
搞个复现链接

**Comment by Y-Lao** [comment]
0.0

**Comment by Y-Lao** [comment]
是bug吗？还是使用不规范？复现链接https://codesandbox.io/p/sandbox/immutable-silence-ns82rp?file=%2Fsrc%2FDemo.vue

**Comment by Y-Lao** [comment]
不行的，好像模板关闭才聚焦。新链接：https://codesandbox.io/p/sandbox/immutable-silence-ns82rp?file=%2Fsrc%2FDemo.vue%3A27%2C12

**Comment by jahnli** [comment]
```
setTimeout(() => {
          inputInstRef.value?.focus();
        }, 0);
```

不确定有没有别的好方案

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
