### ISSUE TITLE
datatable 树形数据不排序

### ISSUE THREAD

**Issue by xinbingyiran** [tusen-ai/naive-ui#5914]
### 描述错误

当使用树形数据时，设置了sorter，点击标题排序时，只有第一级进行了排序，其它级别不变化。

### 复现步骤

绑定含有children的data，为columns设置sorter
预览表格，点击表头排序

### 最小复现链接

https://codesandbox.io/p/sandbox/funny-franklin-2xq2ql

### 系统信息

```Shell
  System:
    OS: Windows 11 10.0.22631
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
    Memory: 2.11 GB / 7.70 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    naive-ui: ^2.38.1 => 2.38.1
    vue: ^3.4.21 => 3.4.23
```

### 使用的包管理器

npm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jahnli** [comment]
感觉设计就是这样的

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
