### ISSUE TITLE
datatable scrollTo bug

### ISSUE THREAD

**Issue by deiiviidas** [tusen-ai/naive-ui#5921]
### Describe the bug
removed becouse everything here is feature and not a bug

**Comment by jahnli** [comment]
提供的复现 [最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
