### ISSUE TITLE
滚动条横向滚动 支持鼠标滚论

### ISSUE THREAD

**Issue by sajfasjg81** [tusen-ai/naive-ui#5923]
### 问题的清晰而简明的描述

Scrollbar 启用横向滚动时可通过 滚论上下模拟左右滚动

### 建议的解决方案

添加一个开关参数

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by 07akioni** [comment]
No plan for this feature.

It's not a common use case.

Standard behavior like `ctrl + wheeling` is recommended.
