### ISSUE TITLE
vue - n-tooltip <template #trigger> Unrecognized slot name ts

### ISSUE THREAD

**Issue by deiiviidas** [tusen-ai/naive-ui#5928]
### Describe the bug

![image](https://github.com/tusen-ai/naive-ui/assets/25092057/38caf8c7-f04e-4180-84b2-e4f5db9461fb)

![image](https://github.com/tusen-ai/naive-ui/assets/25092057/64e19fe3-35ce-4b32-884b-ed8d035534e6)

typescript and me are mad becouse for random error

### Steps to reproduce

<n-tooltip trigger="hover">
   <template #trigger></template>
</n-tooltip?

should ide catch unrecognised template

/*also system info error*/

System Info

Output of npx envinfo --system --npmPackages 'naive-ui,vue' --binaries --browsers

![image](https://github.com/tusen-ai/naive-ui/assets/25092057/fc0d3aab-242b-48a2-9c89-20ad8623a818)

### Link to minimal reproduction

@next

### System Info

```Shell
"vue": "3.4.25",
"naive-ui": "2.38.1",
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
It has almost nothing to do with naiveUI

**Comment by deiiviidas** [comment]
> It has almost nothing to do with naiveUI

explain this then - jumping to the **n-select** component for **working example.**

used good template names
![image](https://github.com/tusen-ai/naive-ui/assets/25092057/9ead11d1-499b-4716-aa28-7252245b32a8)

added bad template names
![image](https://github.com/tusen-ai/naive-ui/assets/25092057/ad772b90-7e59-456e-ad19-455deb4157e3)

**Comment by deiiviidas** [comment]
> It has almost nothing to do with naiveUI
@jahnli
