### ISSUE TITLE
NPopover doesn't display when triggered using NFloatButton

### ISSUE THREAD

**Issue by ikeq** [tusen-ai/naive-ui#5933]
### Describe the bug

<img width="794" alt="image" src="https://github.com/tusen-ai/naive-ui/assets/9206414/a29faf52-3456-4d06-b78c-67db996f1fd9">

### Steps to reproduce

https://www.naiveui.com/en-US/light/components/float-button#tooltip.vue

### Link to minimal reproduction

https://www.naiveui.com/en-US/light/components/float-button#tooltip.vue

### System Info

```Shell
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 102.00 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    pnpm: 7.27.1 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 124.0.6367.156
    Edge: 124.0.2478.80
    Safari: 17.4.1
  npmPackages:
    naive-ui: ^2.38.2 => 2.38.2 
    vue: ^3.4.19 => 3.4.21
```

### Used Package Manager

yarn

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jizai1125** [comment]
Indeed, there's an issue with the popover component. It is a workaround, wrapping an element of the trigger slot.
```vue
<template>
  <n-tooltip trigger="hover" placement="right">
    <template #trigger>
      <span style="display: inline-block">
        <n-float-button position="relative">
          <n-icon>
            <cash-icon />
          </n-icon>
        </n-float-button>
      </span>
    </template>
    Lpsum
  </n-tooltip>
</template>
```
