### ISSUE TITLE
n-select menu max-height not working

### ISSUE THREAD

**Issue by Luffytaro** [tusen-ai/naive-ui#5947]
### Describe the bug

![image](https://github.com/tusen-ai/naive-ui/assets/43850284/da886549-f97b-4517-87d7-5eb2d6cac94e)

If menuProps style maxHeight is set to a smaller value than the standard height of the dropdown, the options of the select component will reach outside of the menu instead of being constrained to the maxHeight.

### Steps to reproduce

1. use n-select component
2. add maxHeight style to menuProps
3. choose pixel value smaller than standard height

![image](https://github.com/tusen-ai/naive-ui/assets/43850284/d66de1d7-1832-48bd-b560-ad9c196db892)

### Link to minimal reproduction

https://codesandbox.io/p/sandbox/flamboyant-waterfall-vthqhz?file=%2Fsrc%2FDemo.vue

### System Info

```Shell
System:
    OS: Linux 5.10 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (12) x64 13th Gen Intel(R) Core(TM) i7-1365U
    Memory: 18.63 GB / 24.79 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 19.9.0 - ~/.nvm/versions/node/v19.9.0/bin/node
    npm: 9.6.3 - ~/.nvm/versions/node/v19.9.0/bin/npm
  npmPackages:
    naive-ui: ^2.31.0 => 2.38.2 
    vue: ^3.3 => 3.4.27
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jizai1125** [comment]
Can use `theme-overrides` prop

```vue
 <n-select
      v-model:value="value"
      :options="options"
       :theme-overrides="{
        peers: {
          InternalSelectMenu: {
            height: '100px'
          }
        }
      }"
    />
```

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
