### ISSUE TITLE
公式 Equation 组件 建议value值(Latex 格式的公式表达式)支持编辑修改

### ISSUE THREAD

**Issue by fssgh** [tusen-ai/naive-ui#5948]
### 问题的清晰而简明的描述

公式 Equation 组件 建议做成表单组件，value值(Latex 格式的公式表达式)支持编辑修改

### 建议的解决方案

公式 Equation 组件 建议做成表单组件，value值(Latex 格式的公式表达式)支持编辑修改

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by jahnli** [comment]
可以二次封装解决
