### ISSUE TITLE
useDialog()方法在自定义js中返回undefined

### ISSUE THREAD

**Issue by ICanThis** [tusen-ai/naive-ui#5951]
### 描述错误

使用对话框的时候，我想将它封装为一个js，但是在调用的时候报错了，打印dialog为undefined

### 复现步骤

```javascript

import http from './http';
import {useMessage, useDialog} from 'naive-ui';

const msg = useMessage();

const dialog = useDialog();
console.log(dialog)

export function getUserInfo() {
    return http.post('/user/info');
}

export function logout() {
    return new Promise((res, rej) => {

        dialog.warning({
            title: '提醒',
            content: '确定要退出吗？',
            onPositiveClick() {
                http.post('/user/logout').then(function (e) {
                    if (e.code === 200) {
                        res(e);
                        msg.success('已退出登录。');
                        setTimeout(function () {
                            location.reload();
                        }, 500);
                    } else {
                        rej(e);
                        msg.error(e.msg);
                    }
                }).catch(e => rej(e));
            },
            onNegativeClick() {
                msg.info('取消退出。');
            }
        })

    });
}


```

### 最小复现链接

-

### 系统信息

```Shell
mac, chrome, node v20.12.0
```

### 使用的包管理器

npm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ICanThis** [comment]
尝试使用export default {}，export default class xxx{}也不能使用, useMessage()返回的也是undefined，我该怎么去在自定义的js中获取到msg和dialog对象

**Comment by ICanThis** [comment]
并且在组件内部使用的dialog和message是没有问题的

**Comment by ICanThis** [comment]
找了一下文档，解决了，使用createDiscreteApi，创建独立出来的dialog和message就可以了

**Comment by jianweiqin** [comment]
> 找了一下文档，解决了，使用createDiscreteApi，创建独立出来的dialog和message就可以了

可以给一些代码吗?找了一下没看到`createDiscreteApi`
