### ISSUE TITLE
【n-input-number】组件 `input-props` 无效

### ISSUE THREAD

**Issue by long-woo** [tusen-ai/naive-ui#5953]
### 描述错误

数字输入（n-input-number）组件的 `input-props` 属性无效

### 复现步骤

<img width="1597" alt="image" src="https://github.com/tusen-ai/naive-ui/assets/3394035/6f0a37d0-4328-42c9-ad7f-0eb75e24c0d0">

### 最小复现链接

https://stackblitz.com/edit/vitejs-vite-vdjdps?file=src%2FApp.vue

### 系统信息

```Shell
Vue: 3.4.26
Naive-ui: 2.38.2
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jizai1125** [comment]
因为顺序问题，inputProps 中的 `maxlength` 会被覆盖
<img width="732" alt="image" src="https://github.com/tusen-ai/naive-ui/assets/33979706/304cbddc-8cfb-45c4-83e2-868d556393a3">

**Comment by long-woo** [comment]
暂时用 `validator` 临时解决。

不知后续版本是否有增加 `maxlength` 属性的计划呢（或者其他）？
