### ISSUE TITLE
官网进去太慢了，能优化下吗

### ISSUE THREAD

**Issue by shengrongchun** [tusen-ai/naive-ui#5957]
### 描述错误

官网进去太慢了，能优化下吗

### 复现步骤

官网进去太慢了，能优化下吗

### 最小复现链接

官网进去太慢了，能优化下吗

### 系统信息

```Shell
官网进去太慢了，能优化下吗
```

### 使用的包管理器

npm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by gaojiangtao-git** [comment]
https://www.naiveui.com/zh-CN/os-theme/components/carousel  试下这个链接
