### ISSUE TITLE
Feature Request: `n-upload` add file size limit

### ISSUE THREAD

**Issue by BobDu** [tusen-ai/naive-ui#5962]
### Clear and concise description of the problem

We can easy limit user upload file size.

### Suggested solution

Add a props `size-limit` for `<n-upload>` component.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jizai1125** [comment]
可以通过 `on-before-upload` 实现

**Comment by BobDu** [comment]
ping @jahnli @jizai1125 是否有可能重新打开这个issue
考虑原生添加该属性去更开箱即用的提供上传文件大小限制功能?

**Comment by jahnli** [comment]
如果原生提供，会添加下

| |
jahnli
|
|
***@***.***
|
---- Replied Message ----
| From | Bob ***@***.***> |
| Date | 05/21/2024 11:36 |
| To | tusen-ai/naive-ui ***@***.***> |
| Cc | jahnli ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [tusen-ai/naive-ui] Feature Request: `n-upload` add file size limit (Issue #5962) |

ping @***@***.*** 是否有可能重新打开这个issue
考虑原生添加该属性去更开箱即用的提供上传文件大小限制功能?

**Comment by jahnli** [comment]
<input type="file"> 没看到相关 api

**Comment by jahnli** [comment]
```
  const beforeUpload = ({ file }: { file: UploadFileInfo; fileList: UploadFileInfo[] }) => {
    const fileSize = parseFloat(((file.file?.size ?? 0) / 1024 / 1024).toFixed(1));
    if (fileSize > astrictFileSize) {
      return false;
    }
    return true;
  };
```
