### ISSUE TITLE
需求：Sider折叠状态下，当Menu列表中的选项过多超出屏幕视口高度时，提供滚动条

### ISSUE THREAD

**Issue by alaywn** [tusen-ai/naive-ui#5964]
### Clear and concise description of the problem

目前Sider折叠状态下，Menu的选项过多时，弹出的menu列表会显示不全

### Suggested solution

建议：Sider折叠状态下，当Menu列表中的选项过多超出屏幕视口高度时，提供滚动条

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jahnli** [comment]
提供的复现 [最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by alaywn** [comment]
> 提供的复现 [最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)

sider中放个menu，然后给100个菜单项，就知道怎么回事了

**Comment by jahnli** [comment]
提示在线复现链接

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by Wlisfes** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/32263302/a4d71b05-395e-4580-8d5e-96bc0fcbb584)
菜单比较多的时候右侧无法滚动

**Comment by alaywn** [comment]
> ![image](https://private-user-images.githubusercontent.com/32263302/338423451-a4d71b05-395e-4580-8d5e-96bc0fcbb584.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMTYyNjksIm5iZiI6MTcxODExNTk2OSwicGF0aCI6Ii8zMjI2MzMwMi8zMzg0MjM0NTEtYTRkNzFiMDUtMzk1ZS00NTgwLThkNWUtOTZiYzBmY2JiNTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDE0MjYwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyZGVhYTg2OTg1MzczNmJiYzViNDgyYmE2MjAyNjI3MmEwMWNiNTk1YTQ3OGJkZjUwODI5NWYyNzQ4YzkxMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tSQYojqhmrl5r-aaNR1LKETobEothFnC_n_sgut3tJo) 菜单比较多的时候右侧无法滚动

就是这个问题

**Comment by liangyao375** [comment]
解决了吗？

**Comment by alaywn** [comment]
> 解决了吗？

应该还没
