### ISSUE TITLE
Rich text editor

### ISSUE THREAD

**Issue by shaniqwa-drm** [tusen-ai/naive-ui#5966]
### Clear and concise description of the problem

It would be awesome to have a rich text editor so we can style input/text area components

### Suggested solution

Create a new component, for example `n-editor` that will support basic functionality of styling the text inside the input fieldthe 

### Alternative

Currently, I have written something from scratch, customized to my needs, using editable div. There is a lot of work to handle the keyboard navigation, since it's not plain text. I consider using a 3rd party solution like this: https://v4.primevue.org/editor/ but I love naive-ui and I prefer not to install another 3rd library... so keeping my own implementation for now

### Additional context

I'm happy to contribute to this feature

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by gaojiangtao-git** [comment]
https://quilljs.com/docs/quickstart/  可以了解下，个人不建议ui集成富文本 会造成太臃肿
