### ISSUE TITLE
希望Slider可以增加多样化自定义的刻度功能

### ISSUE THREAD

**Issue by iamhw** [tusen-ai/naive-ui#5967]
### 问题的清晰而简明的描述

目前仅支持一种固定的刻度，希望可以支持自定义刻度，以提升组件在音频领域的应用，如下图：
![image](https://github.com/tusen-ai/naive-ui/assets/4383951/e29491de-3972-4ba2-ac01-2bd40c48df7b)
具体可参见[echo-ui](https://echoui.dev/zh/component/slider)

### 建议的解决方案

能否提供刻度slot，方便自定义刻度

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by jahnli** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/20943608/680e685c-6118-4a36-8c72-c8fd1d7484a2)
指的是这个 ？

**Comment by iamhw** [comment]
是的，这里的marks只能自定义显示文字，并且会默认在控制条上生成刻度，能否开放slot自定义通过svg生成更加丰富的刻度
