### ISSUE TITLE
DataTable组件新增行双击事件

### ISSUE THREAD

**Issue by liufayi** [tusen-ai/naive-ui#5972]
### 问题的清晰而简明的描述

DataTable组件新增行双击事件

### 建议的解决方案

DataTable组件新增行双击事件

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by jahnli** [comment]
`row-props`
