### ISSUE TITLE
希望增加一个cron表达式组件

### ISSUE THREAD

**Issue by wangxiahui007** [tusen-ai/naive-ui#5979]
### 问题的清晰而简明的描述

希望增加一个生成cron表达式的组件

### 建议的解决方案

n-cron

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by jahnli** [comment]
This seems to be beyond the scope of a general component library and can use excellent plugins from the community
