### ISSUE TITLE
Cascader 组件中的数据在不同分组中 选择会出现混乱  label 和value 一致时

### ISSUE THREAD

**Issue by mortal-nf** [tusen-ai/naive-ui#5980]
### Describe the bug

组件中的数据在不同分组中 选择会出现混乱  label 和value 一致时

### Steps to reproduce

1.点击第一项
2.点击第二项
3.选择第三项 
结果 显示值与选择值不一致
![QQ截图20240525220145](https://github.com/tusen-ai/naive-ui/assets/55874355/dd686308-10f4-4bf1-a56a-e836dcfb213b)

### Link to minimal reproduction

https://codesandbox.io/p/sandbox/admiring-fire-wpq3sr?file=%2Fsrc%2FDemo.vue%3A21%2C13

### System Info

```Shell
win10 
chrome124.0.6367.210
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
Reproduction example missing

This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
