### ISSUE TITLE
希望给NButton增加工具提示属性

### ISSUE THREAD

**Issue by windinternet** [tusen-ai/naive-ui#5981]
### 问题的清晰而简明的描述

在按钮上增加工具提示是非常普遍的一个需求，特别是使用图来表达意图的场景，如果每个需要按钮的地方都拉套用一次工具提示的话就太麻烦了

### 建议的解决方案

直接在NButton组件增加 tips属性，如果存在自动套一个工具提示，并使用hover的方式触发

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by jahnli** [comment]
https://www.naiveui.com/zh-CN/os-theme/components/popover#basic.vue

**Comment by windinternet** [comment]
naive-ui 是可以套用弹出信息做工具提示，只是每个按钮都需要手动套太麻烦了，直接给button增加一个属性，来接收工具提示的内容会快很多，少写很多样板代码

**Comment by windinternet** [comment]
> https://www.naiveui.com/zh-CN/os-theme/components/popover#basic.vue

naive-ui 是可以套用弹出信息做工具提示，只是每个按钮都需要手动套太麻烦了，直接给button增加一个属性，来接收工具提示的内容会快很多，少写很多样板代码

**Comment by jahnli** [comment]
二次封装下就好了

**Comment by windinternet** [comment]
> 二次封装下就好了

目前自己就是这样打算了，如果官方直接封装就更好了

**Comment by gaojiangtao-git** [comment]
根据各自需求封装就好，封装太深不建议
