### ISSUE TITLE
Create dialog without icon

### ISSUE THREAD

**Issue by yxzlwz** [tusen-ai/naive-ui#5982]
### Clear and concise description of the problem

As I'm working on a file manage system, I use dialog to ask user to rename file, confirm delete, etc. I believe it is much better if I can create a dialog without icon in the title.

### Suggested solution

Allow `null` in `iconPlacement` or `type`

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US).
- [x] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by windinternet** [comment]
直接用模态框+卡片预设自己写一个更快，另外他本身的 content 等属性都是支持传入渲染函数的，也可以使用渲染函数来指定渲染效果，这些属性本来就是可以不传的。naive-ui组件库的自由度很高的，很难相信会对你实现文件重命名等操作造成困扰

**Comment by jahnli** [comment]
`slot` should be possible
