### ISSUE TITLE
Add a horizontal virtual scroll to NDataTable

### ISSUE THREAD

**Issue by ValentinDankovtsev** [tusen-ai/naive-ui#5996]
### Clear and concise description of the problem

Thanks for adding virtual scroll vertically to the DataTable. but there is a problem with scrolling, if there are many columns and rows, rendering takes a long time and a significant amount of memory is spent. Please add a horizontal virtual scroll.

there is a similar request, but for some reason it is closed https://github.com/tusen-ai/naive-ui/issues/1340.

### Suggested solution

**Expected API**
```
<n-data-table
  :columns="columns"
  :data="data"
  virtual-scroll
  scroll-mode="['vertical', 'horizontal]"
/>
```

### Alternative

for Example
https://vxetable.cn/#/table/scroll/fullCols

### Additional context

https://github.com/tusen-ai/naive-ui/assets/72089109/835f41b1-7ae2-4ffc-bbac-402fa55b6f27

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jahnli** [comment]
This feature is already in the author's plans, and the specific release date is not yet certain

**Comment by jahnli** [comment]
The author has completed the development and is expected to release the next version

![image](https://github.com/user-attachments/assets/e2183cd3-07df-43d2-a694-0556fbcd870b)
