### ISSUE TITLE
Cascader组件搜索筛选下拉列表显示不全

### ISSUE THREAD

**Issue by lvyiwen** [tusen-ai/naive-ui#5997]
### 问题的清晰而简明的描述

级联选择器筛选项由于文字过多出现省略号，看不全整体路径

### 建议的解决方案

希望文字超出时hover增加tooltip显示

### 备选方案

或者直接全量显示

### 附加上下文

图片上传不上去官网打开Cascader屏幕缩小搜索就会出现

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by jahnli** [comment]
```
renderLabel(option: { value?: string | number; label?: string }) {
        return h(
          NEllipsis,
          {},
          { default: () => h("span", {}, label) }
        );
      },
```

**Comment by lvyiwen** [comment]
> ```
> renderLabel(option: { value?: string | number; label?: string }) {
>         return h(
>           NEllipsis,
>           {},
>           { default: () => h("span", {}, label) }
>         );
>       },
> ```

加了Filterable搜索之后renderLabel是不生效的

**Comment by dongpeeng** [comment]
> > ```
> > renderLabel(option: { value?: string | number; label?: string }) {
> >         return h(
> >           NEllipsis,
> >           {},
> >           { default: () => h("span", {}, label) }
> >         );
> >       },
> > ```
> 
> 加了Filterable搜索之后renderLabel是不生效的

+1，可以支持在过滤时下拉项不展示路径，仅展示叶子节点的标签吗？

**Comment by YaleWan** [comment]
renderLabel 对 filterable时候搜索不生效 ，展示不全，希望得到解决，或者有替代方案

<img width="438" height="320" alt="Image" src="https://github.com/user-attachments/assets/c966d319-4ef4-4811-a969-e20c5e432227" />
