### ISSUE TITLE
qrcode 组件的中间icon的image设置跨域

### ISSUE THREAD

**Issue by 18684590954** [tusen-ai/naive-ui#6002]
### 问题的清晰而简明的描述

qrcode组件的icon创建时给image属性设置允许跨域

### 建议的解决方案

 let aborted = false;
          const img = new Image();
          // img.setAttribute("crossOrigin",'anonymous')
          img.src = iconSrc;

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by jahnli** [comment]
Reproducibility provided [Minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by 18684590954** [comment]
在导出canvas为图片时中间的icon时有跨域错误
![image](https://github.com/tusen-ai/naive-ui/assets/58258652/e41ce0e8-939a-4d3e-93fd-608eac5b3253)

**Comment by Sepush** [comment]
img.crossOrigin = "Anonymous";

https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image
