### ISSUE TITLE
Message内容为纯数字或纯字母的时候不能

### ISSUE THREAD

**Issue by XiaoSongWolf** [tusen-ai/naive-ui#6005]
### 描述错误

Message内容为纯数字或纯字母的时候不能换行；
![微信图片_20240531173938](https://github.com/tusen-ai/naive-ui/assets/19815977/6ae3fe1b-7642-4019-80e2-a7eb6fc7ec3b)

### 复现步骤

复现的极简代码：
```
const {error} = useMessage();

function handleExport() {
	const messageStr: string = "这儿有个bug, 1111111111111111111asfasdjkfhaskjdhfkjhk12312341234231453245643562346523452345234523452345234, 这儿有个bug;";
	error(messageStr);
}
```

### 最小复现链接

https://github.com/tusen-ai/naive-ui/assets/19815977/6ae3fe1b-7642-4019-80e2-a7eb6fc7ec3b

### 系统信息

```Shell
Vue版本：3.2.47
Vite版本：5.2.11
Naive UI版本为：2.38.2
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jahnli** [comment]
Referring to other UI libraries, this seems to be expected behavior. You can try `overflow-wrap` to modify it.
