### ISSUE TITLE
组件内使用NFormItemGi组件无法渲染、是否应该找内层的NFormItemGi组件

### ISSUE THREAD

**Issue by baicie** [tusen-ai/naive-ui#6011]
### 问题的清晰而简明的描述

1. 创建一个组件直接返回NFormItemGi 里面包个input啥的组件
2. 在form组件中使用创建的组件
3. 期望是渲染，可能是vnode没有去找嵌套的NFormItemGi组件

### 建议的解决方案

处理嵌套的NFormItemGi组件

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by jahnli** [comment]
提供的复现 [最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by baicie** [comment]
> 提供的复现 [最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)

有点忙等下班哈哈

**Comment by baicie** [comment]
> 提供的复现 [最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)

https://github.com/baicie/for-naiveui-form-item

**Comment by baicie** [comment]
`import { NFormItemGi, NInput } from "naive-ui";
import { defineComponent } from "vue";

const Child = defineComponent({
  setup() {
    return (
      <NFormItemGi span={6}>
        <NInput />
      </NFormItemGi>
    );
  },
});

export default Child;
`

`import { NForm, NFormItemGi, NGrid, NGridItem, NInput } from "naive-ui";
import { defineComponent } from "vue";
import Child from "./components/Com";

const App = defineComponent({
  setup() {
    return () => (
      <NForm
        labelPlacement="left"
        showFeedback={false}
        style={{ marginLeft: "50px" }}
      >
        <NGrid cols={24} xGap={20} yGap={20}>
          <NFormItemGi span={12}>
            <NInput />
          </NFormItemGi>

          <Child />
        </NGrid>
      </NForm>
    );
  },
});

export default App;
`

**Comment by baicie** [comment]
``` tsx
import { NForm, NFormItemGi, NGrid, NGridItem, NInput } from "naive-ui";
import { defineComponent } from "vue";
import Child from "./components/Com";

const App = defineComponent({
  setup() {
    return () => (
      <NForm
        labelPlacement="left"
        showFeedback={false}
        style={{ marginLeft: "50px" }}
      >
        <NGrid cols={24} xGap={20} yGap={20}>
          <NFormItemGi span={12}>
            <NInput />
          </NFormItemGi>

          <Child />
        </NGrid>
      </NForm>
    );
  },
});

export default App;

```
```tsx
import { NFormItemGi, NInput } from "naive-ui";
import { defineComponent } from "vue";

const Child = defineComponent({
  setup() {
    return (
      <NFormItemGi span={6}>
        <NInput />
      </NFormItemGi>
    );
  },
});

export default Child;

```

**Comment by jahnli** [comment]
很有可能像 grid 一样， NForm 子元素只能是 NFormItem

**Comment by baicie** [comment]
是这样的因为只找了一层没继续往下找 算是用法没用对 继续往下找也不现实
