### ISSUE TITLE
NSelect的scroll事件无法触发

### ISSUE THREAD

**Issue by Jafeyyu** [tusen-ai/naive-ui#6024]
### 描述错误

使用naive-ui的版本为2.38.2
使用NSelect的on-scroll事件，不能够触发事件，上官网的组件demo查看，发现组件的demo也没有触发on-scorll事件

### 复现步骤

1.NSelect配置@scroll=“handleScroll”，option配置的比较少，配置了5个，此时select没有滚动条
2.打开页面，select滚动
3.handleScroll方法没有触发
4.后来把option配置多一些，大概20个，此时select是由滚动条的，这是发现是可以触发onScroll

### 最小复现链接

https://codesandbox.io/s/nzczkp

### 系统信息

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i9-13900H
    Memory: 12.86 GB / 31.75 GB
  Binaries:
    Node: 21.7.1 - D:\Program Files\nodejs\node.EXE
    npm: 10.5.0 - D:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.5 - D:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (125.0.2535.79)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    naive-ui: 2.38.2 => 2.38.2
    vue: 3.4.27 => 3.4.27
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jahnli** [comment]
这是符合预期的吧

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
