### ISSUE TITLE
n-tree组件node-props的onClick点击复选框没反应

### ISSUE THREAD

**Issue by xiaomaoJT** [tusen-ai/naive-ui#6029]
### Describe the bug

2.36.0版本正常，2.38.2版本点击复选框无反应，只有点击node才能激活onClick方法。

const nodeProps = ({ option }: { option: TreeOption }) => {
  return {
    onClick(e) { }
    }
  }
}

### Steps to reproduce

1、点击复选框
2、onClick方法无反应

### Link to minimal reproduction

无

### System Info

```Shell
2.36.0为可用版本 
System:
    OS: macOS 13.6.4
    CPU: (8) arm64 Apple M1
    Memory: 65.67 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 124.0.6367.80
    Safari: 17.3
  npmPackages:
    naive-ui: 2.36.0 => 2.36.0
    vue: ^3.4.5 => 3.4.27
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
提供的复现 [最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by xiaomaoJT** [comment]
vue3+vite环境
<n-tree
                block-line
                block-node
                :show-line="true"
                selectable
                ref="treeRef"
                checkable
                :animated="false"
                expand-on-click
                check-on-click
                class="home-container-split-tree"
                default-expand-all
                :pattern="pattern"
                :data="treeData"
                :watch-props="['defaultCheckedKeys']"
                :default-checked-keys="defaultCheckedKeys"
                :node-props="nodeProps"
              />


const nodeProps = ({ option }: { option: TreeOption }) => {
  return {
    onClick(e) {
//点击复选框无法触发
       if (treeGetClickTarget(e) == 'checkbox') {
      checkedRowKeys.value = treeRef.value.getCheckedData().options
       }
    }
  }
}

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by ShangChien** [comment]
点击tree组件的switcher-icon，无法触发nodeProps中的onClick事件，导致[文档](https://www.naiveui.com/zh-CN/os-theme/components/tree#Others) 的`treeGetClickTarget: (e: MouseEvent) => ('checkbox' | 'switcher' | 'node')`函数无法调用确认点击的对象为`switcher`

Naive-UI version: 2.40.1

复现：https://codesandbox.io/p/sandbox/falling-darkness-3mkjh9
