### ISSUE TITLE
Searching in the group selector, where options are loaded via the API, does not work for androids

### ISSUE THREAD

**Issue by Aleksoge** [tusen-ai/naive-ui#6038]
### Describe the bug

Searching in the group selector, where options are loaded via the API, does not work on many androids, especially cheap ones

### Steps to reproduce

![image](https://github.com/tusen-ai/naive-ui/assets/110264552/1ee12193-d985-41d5-83b6-31c76fcd75ec)
group selector
![image](https://github.com/tusen-ai/naive-ui/assets/110264552/af7bcb95-a42e-41ff-b5cc-2d8d91d3a2c1)
![image](https://github.com/tusen-ai/naive-ui/assets/110264552/b9bf41d7-5352-4e9a-a6b4-0cce08874758)
allGroups is answer from api with groups list

### Link to minimal reproduction

https://uust-time.ru/ 

### System Info

```Shell
Android Poco
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
This is a PC library, not too much compatibility processing for mobile
