### ISSUE TITLE
duplicated text inside n-date-picker@daterange @template#footer

### ISSUE THREAD

**Issue by deiiviidas** [tusen-ai/naive-ui#6040]
### Describe the bug
removed becouse everything here is feature and not a bug

**Comment by jahnli** [comment]
提供的复现 [最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by deiiviidas** [comment]
persišviesk galvą, atsiunčiau tau nuotrauką tau nesimato? gal pabraukti? ar aklas?

**Comment by deiiviidas** [comment]
清醒一下，我给你发了一张照片，你看不到吗？也许下划线？你是瞎子吗

**Comment by jahnli** [comment]
> 清醒一下，我给你发了一张照片，你看不到吗？也许下划线？你是瞎子吗

要复现链接，你是瞎 ？ 我看你什么图

**Comment by pengzhen-developer** [comment]
> persišviesk galvą, atsiunčiau tau nuotrauką tau nesimato? gal pabraukti? ar aklas?

应该是和我同一个疑问，存在 2 个位置的 slot。
https://github.com/tusen-ai/naive-ui/issues/5956

**Comment by jahnli** [comment]
https://github.com/tusen-ai/naive-ui/issues/5956
