### ISSUE TITLE
使用NConfigProvider注入组件默认prop

### ISSUE THREAD

**Issue by s3xysteak** [tusen-ai/naive-ui#6042]
### 问题的清晰而简明的描述

如题
类似于

父组件：
```vue
<template>
  <n-config-provider :propsOverride="{Dialog: {bordered: true}}">
    <n-modal-provider>
      <Child />
    </n-modal-provider>
  </n-config-provider>
</template>
```

子组件：
```vue
<script setup>
const modal = useModal()
modal.create({
  // ...
  preset: 'dialog',
  // 此时bordered默认为true
})
</script>
```

### 建议的解决方案

创建一个组合式函数包装每个组件的props，用于处理默认情况

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by firmianaQ** [comment]
+1

**Comment by pengzhen-developer** [comment]
可以参考这个问题：
https://github.com/tusen-ai/naive-ui/issues/2696

作者已给出方案：
https://github.com/tusen-ai/naive-ui/issues/2696#issuecomment-1083259799

**Comment by jahnli** [comment]
https://github.com/tusen-ai/naive-ui/issues/2696#issuecomment-1083259799
