### ISSUE TITLE
openOpenFileDialog there DoesnT Seem To BeSuchA Method

### ISSUE THREAD

**Issue by yxl989458** [tusen-ai/naive-ui#6043]
### Describe the bug

![image](https://github.com/tusen-ai/naive-ui/assets/84430882/3c3cf78d-c301-4a34-9fb3-6a73d466d468)

This method is not called when opening the file selection box

### Steps to reproduce

This method is not called when opening the file selection box

### Link to minimal reproduction

This method is not called when opening the file selection box

### System Info

```Shell
system
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
提供的复现 [最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
