### ISSUE TITLE
使用js修改menu的value，菜单不会自动展开

### ISSUE THREAD

**Issue by huangbh1024** [tusen-ai/naive-ui#6046]
### 描述错误

使用js修改menu的value，菜单不会自动展开

### 复现步骤

1. 给menu设置v-model:value
2. 使用js修改value的值

### 最小复现链接

https://codesandbox.io/p/sandbox/bold-cookies-cldz8z

### 系统信息

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 22.58 GB / 39.68 GB
  Binaries:
    Node: 20.11.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.2.4 - D:\Program Files\nodejs\npm.CMD
    pnpm: 8.14.1 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (125.0.2535.92)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    naive-ui: ^2.38.2 => 2.38.2
    vue: ^3.4.21 => 3.4.27
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jahnli** [comment]
`:watch-props="['defaultValue', 'defaultExpandedKeys']"`

**Comment by jahnli** [comment]
或者手动控制
