### ISSUE TITLE
更新到最新2.38.2版本后，form表单中inline模式下select组件宽度没有了

### ISSUE THREAD

**Issue by a1113590485** [tusen-ai/naive-ui#6050]
### 描述错误

更新到最新2.38.2版本后，form表单中inline模式下select组件宽度没有了

### 复现步骤

```
<n-form
            ref="formRef"
            inline
            label-placement="left"
            :model="filterFormData"
            :show-feedback="false"
          >
            <n-form-item label="类型" path="categoryId">
              <n-select clearable
                v-model:value="filterFormData.categoryId"
                label-field="categoryName_Default"
                value-field="code"
                :options="categoryOptions"
                :consistent-menu-width="false"
              />
            </n-form-item>
</n-form>
```

其中n-select宽度没有了
![企业微信截图_17183296619886](https://github.com/tusen-ai/naive-ui/assets/32317987/f9625df5-b1fa-4c18-b8f7-a8a6b84bafda)

### 最小复现链接

无

### 系统信息

```Shell
无
```

### 使用的包管理器

npm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jahnli** [comment]
提供的复现 [最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by tinywaves** [comment]
> 提供的复现 [最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)

https://codesandbox.io/p/devbox/jx623d

**Comment by tinywaves** [comment]
> > 提供的复现 [最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)
> 
> https://codesandbox.io/p/devbox/jx623d [@jahnli](https://github.com/jahnli)

https://github.com/tusen-ai/naive-ui/issues/5014

**Comment by jahnli** [comment]
看样子是有点问题

**Comment by jahnli** [comment]
好像与初始值是 `null` 或者 `undefined` 有关

**Comment by tinywaves** [comment]
> [@tinywaves](https://github.com/tinywaves) 好像与初始值是 `null` 或者 `undefined` 有关

是的，不过在表单里初始值设置为零值算是常见需求。而且似乎是父级必须要给定一定的宽度限制渲染才会正常，比如：https://www.naiveui.com/zh-CN/os-theme/components/form#left.vue。官方这边是否考虑给一个初始值或者想个办法去动态计算一下宽度啥的。
