### ISSUE TITLE
Select可以提供prefix插槽吗

### ISSUE THREAD

**Issue by JunjunZheng** [tusen-ai/naive-ui#6058]
### 问题的清晰而简明的描述

使用Select组件时，需要设置输入框头部内容，可以增加一个prefix插槽吗

### 建议的解决方案

可以提供prefix插槽吗

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by liuyang0826** [comment]
可以用InputGroup包裹实现吧

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
