### ISSUE TITLE
The demo floating button on the official website is invalid

### ISSUE THREAD

**Issue by 14752222** [tusen-ai/naive-ui#6067]
### Describe the bug

官网点击 浮动按钮 Float Button 时候，然后再点击案例的button后切其他组件仍然显示 浮动按钮 
![微信图片_20240620115033](https://github.com/tusen-ai/naive-ui/assets/53716400/966c964e-3e21-41cd-b20d-da4f7221b75d)

### Steps to reproduce

1，点击组件的浮动按钮选项
2，案例的浮动按钮点击几次
3，再点击侧边栏就无效了
![微信图片_20240620115033](https://github.com/tusen-ai/naive-ui/assets/53716400/57cae3ef-9020-4090-b64d-579db44e7a43)

### Link to minimal reproduction

https://www.naiveui.com/zh-CN/os-theme/components/float-button

### System Info

```Shell
npx envinfo --system --npmPackages 'naive-ui,vue' --binaries --browsers
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Sepush** [comment]
repeat with https://github.com/tusen-ai/naive-ui/issues/5933 
fix in https://github.com/tusen-ai/naive-ui/commit/a5c3b902cdc2ab8895f5c4c4e07c21d5a719abc8
