### ISSUE TITLE
NScrollbar 缺失 vue scope 生成的作用域属性

### ISSUE THREAD

**Issue by byronogis** [tusen-ai/naive-ui#6076]
### Describe the bug

见 #5084 ，

现在这依旧是一个存在的问题，v2.38.2。

### Steps to reproduce

https://codesandbox.io/p/sandbox/gracious-elgamal-p9l754?file=%2Fsrc%2FApp.vue%3A9%2C33

From #5084 

### Link to minimal reproduction

NScrollbar 

### System Info

```Shell
System:
    OS: Linux 6.6 NixOS 24.11 (Vicuna) 24.11 (Vicuna)
    CPU: (4) x64 AMD Ryzen 5 3400G with Radeon Vega Graphics
    Memory: 9.29 GB / 15.58 GB
    Container: Yes
    Shell: 5.9 - /run/current-system/sw/bin/zsh
  Binaries:
    Node: 20.14.0 - /run/user/1000/fnm_multishells/34715_1719097963740/bin/node
    npm: 10.7.0 - /run/user/1000/fnm_multishells/34715_1719097963740/bin/npm
    pnpm: 9.4.0 - /run/user/1000/fnm_multishells/34715_1719097963740/bin/pnpm
  npmPackages:
    naive-ui: ^2.38.2 => 2.38.2 
    vue: ^3.4.21 => 3.4.29
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
Provide a based on CodeSandbox or stackblitz [Minimal, Reproducible Example] (https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
