### ISSUE TITLE
data-tables downloadCsv is shit

### ISSUE THREAD

**Issue by deiiviidas** [tusen-ai/naive-ui#6079]
### Describe the bug

feature https://www.naiveui.com/en-US/os-theme/components/data-table#export-csv.vue

okay first of all bug/issue number 1:
ENCODING IS FUCKED UP 
![image](https://github.com/tusen-ai/naive-ui/assets/25092057/c083f7cb-b947-4692-bda4-c59c4a1b3ab2)
result
![image](https://github.com/tusen-ai/naive-ui/assets/25092057/4962fdbc-9ca3-473f-8d56-73bd333abcc0)

second issue
after downloading the csv it does not show rendered text, instead it shows data by key and completely ignores render value and uses data.key value instead - like wtf ?
![image](https://github.com/tusen-ai/naive-ui/assets/25092057/2c86b2ca-7c03-42ac-b14d-39471feb366b)
![image](https://github.com/tusen-ai/naive-ui/assets/25092057/35188ee9-07d9-477a-9275-e076b45580ab)
![image](https://github.com/tusen-ai/naive-ui/assets/25092057/1d1de6e0-fd69-48c3-904a-feaad23621dc)

issue number 3 completely ignores summary data and does not include in csv 

![image](https://github.com/tusen-ai/naive-ui/assets/25092057/10cdf7fd-c2fa-4ed5-af8f-f4951c5ee339)
![image](https://github.com/tusen-ai/naive-ui/assets/25092057/72a661aa-4e06-449f-9018-1973122a2987)

### Steps to reproduce

- [x] dont be asshole and read text.

### Link to minimal reproduction

bug is a bug

### System Info

```Shell
asd
```

### Used Package Manager

npm

### Validations

- [ ] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [ ] Read the [docs](https://www.naiveui.com/en-US/).
- [ ] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [ ] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [ ] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
This is just a simple csv. You have to implement complex functions yourself.
