### ISSUE TITLE
build:package 报错

### ISSUE THREAD

**Issue by JS-an** [tusen-ai/naive-ui#6080]
### 描述错误

如图所示
![image](https://github.com/tusen-ai/naive-ui/assets/25688878/870f7f79-27db-4ddd-ad55-2b717589fcfe)

### 复现步骤

npm run build:package

### 最小复现链接

无

### 系统信息

```Shell
windows 10 
node 20.11.0
pnpm 9.4.0
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by JS-an** [comment]
PS: Linux 下构建一切正常

**Comment by jahnli** [comment]
https://github.com/tusen-ai/naive-ui/issues/6178  duplicate
