### ISSUE TITLE
n-data-table tree 模式并启用 ellipsis 时错位

### ISSUE THREAD

**Issue by realByg** [tusen-ai/naive-ui#6087]
### 描述错误

`n-data-table` 的 `tree` 模式下，每一行第一个 `column` 会增加 indent 和 expand 的两个placeholder div， 然后如果这个 `column` 的文字过长并启用了 `ellipsis`，由于 `n-ellipsis` 的 `max-width` 为 `100%`，导致显示错位
![image](https://github.com/tusen-ai/naive-ui/assets/39550067/a9e62f92-c808-4ef9-b3be-5a5316ebb795)

### 复现步骤

如 codesandbox 链接

### 最小复现链接

https://codesandbox.io/s/vigorous-bartik-shrvfg

### 系统信息

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900HX
    Memory: 5.09 GB / 15.74 GB
  Binaries:
    Node: 21.7.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.68)
    Internet Explorer: 11.0.22621.3527
```

### 使用的包管理器

npm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by realByg** [comment]
现在暂时的解决方法是自己手动 render 一个 ellipsis 
```jsx
render: (row) => (
 <NEllipsis class='max-w-[calc(100%-32px)]'>{row.text}</NEllipsis>
),
```

**Comment by jahnli** [comment]
No problems were found in the example,If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
