### ISSUE TITLE
在n-tree 组件的node-props属性里绑定的双击事件同时会触发单击事件

### ISSUE THREAD

**Issue by wangxiahui007** [tusen-ai/naive-ui#6093]
### 描述错误

 在n-tree 组件的node-props属性里绑定的双击事件同时会触发单击事件

### 复现步骤

<n-tree  :data="data" :node-props="nodeProps"></n-tree>

const nodeProps =  ({ option }) => {
  return {
    onDblclick(event) {
      console.log("双击")
    },
    onClick(event) {
       console.log("单击")
    }
  };
}

### 最小复现链接

https://github.com/wangxiahui007/tes-app.git

### 系统信息

```Shell
系统：macOs 14.0 
浏览器：谷歌126.0.6478.114（正式版本） (arm64)
```

### 使用的包管理器

yarn

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jahnli** [comment]
https://www.naiveui.com/zh-CN/os-theme/components/tree#override-click-behavior.vue   不确定能不能解决你的问题

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by Xiaobaishushu25** [comment]
数据表格也是这样
