### ISSUE TITLE
能否提供个Naive UI样式中px转rem方法或思路？我还不想那么快放弃这个UI框架

### ISSUE THREAD

**Issue by ying-tch** [tusen-ai/naive-ui#6096]
### 问题的清晰而简明的描述

如题，我好不容易将项目中的UI框架替换为了Naive UI，但却因为它无法将px转rem而前功尽弃。Elementplus部分组件写法太过冗余，AntdV的功能太少，ArcoV的bug又太多，目前试下来Naive还是相对称心。我不想放弃它，想请教还有什么办法，可以让我将Naive样式中的px都转化为rem。

### 建议的解决方案

框架开发者能否提供个方法或思路？

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by Preyou** [comment]
https://git.caner.top/Caner/naiveUI2Rem

以前官方群的一个老哥分享的，我不知道能不能用，你可以试下

**Comment by Preyou** [comment]
这里提个醒，所有涉及虚拟列表的地方都不能用rem作单位

**Comment by ying-tch** [comment]
> https://git.caner.top/Caner/naiveUI2Rem
> 
> 以前官方群的一个老哥分享的，我不知道能不能用，你可以试下

嗯嗯，感谢您的分享。我试试看

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
