### ISSUE TITLE
为数字输入框提供圆角

### ISSUE THREAD

**Issue by qiaoshouzi** [tusen-ai/naive-ui#6097]
### 问题的清晰而简明的描述

希望为数字输入框提供圆角

### 建议的解决方案

圆角

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by far1shs** [comment]
他不是支持圆角吗？自定义主题的话修改 Input
![image](https://github.com/tusen-ai/naive-ui/assets/97778999/651b1af8-3182-4eff-ba4a-e093ef73cd57)
![image](https://github.com/tusen-ai/naive-ui/assets/97778999/4bde138a-d44e-4841-b87f-bafe58155a83)

**Comment by jahnli** [comment]
![Uploading image.png…]()

**Comment by qiaoshouzi** [comment]
我是希望像 input 那样有个 round
![image](https://github.com/tusen-ai/naive-ui/assets/61568944/d1bfa109-fcf2-4e20-9639-47adbc3d777c)
