### ISSUE TITLE
弹出层 （比如：Popover）在页面空间不足时，不应该只是简单调整 placement，可以适量地偏移

### ISSUE THREAD

**Issue by zestack** [tusen-ai/naive-ui#6103]
### 问题的清晰而简明的描述

弹出层 （比如：Popover）在页面空间不足时，组件只是简单调整了 placement 的值，这个时候还应该考虑偏移量，来保证尽最大程度的显示出更多的内容。

[示例](https://play.vuejs.org/#eNp9VFtvE0cU/ivT7UOCiHfdhNLKXqJehNT2IUWlUh+6FVp7x7uTzM6MZmZtp1GkNCmhaikRAomriJACQQiFICEUHMifweP4jb/A2ZvjAOJld85lzjnfd+acJetbIex2gq2a5aqmJEIjhXUiZj1GYsGlRktI4hZaRi3JYzQBrhNjprnzmOKmnkJz57jgbSxHjswnbVxJCHh7rMmZ0ihWITqTRpuc+AFTytFvXNLgs4kTRy5caAKHwu33P8DU4hJNUqwRAW21Dj8XzcDv5MkTaMljqLxjt32aYFskKprM9Agt4MUaIlO5QP0GpqW4DIGXPeY6OWZAC4LGsaC+xiAh5AakjZRepPiMZwk/CAgLa19WRRdNV+Fb75BAR7UvqtV2px5hEkY6E6J6QBREgcQtirv1+URp0lqsADyNmc61FcyCuk9JyCoEkqpCq7Qvdb3B4UT+TNOhBpcBlhVQ1T0rKwsKG1FdK5BDgcXJsxDkbuIYUoG2wbXmMShblAikIt4pYkCUEiz6XEsShliOTGBsJHCRzYo8kesU8uiyc4yqTDVOV84NOp0RVZBzOuUmx1M7BSwqTkkAXQ5GwMows/29lf7e48HT68ODNbO1fXj7b/PqpbnUG9xfd53UYcyfMJFo1K7EPMAUUsMbA7zO+yHN62tm4+lwe91c7pnNzSL27gbEHtx4YVZuvX11efDP1f7+k1E282x1cPPgcKvX3/vfXHz0ZmXVPFwd3LubW4drr83W5vDSY/PvI/PXxuH2PkQwu88gS3//QX5xcOe52bqdBly/aHZe9nsflp/Vtt8b7uyYjdXhyhp0ivsaeg+Tg+Amcn0UwSgAskhroWqOM+ZhN3nsBLypHF9K3gHg8IJCnLb+QoP6bAG4zSwohXHwn+v4s8js3Du8spvXfLyeccl1ymeWT0NhOtZ5a8rKF0El9oU9rziDLZKNnlcY4EHW8iFNdeVKSJVHeBImFsIMSWn/Ztqe+dqehpRKO4QFuGvH8xAqG1yYW8irFQxUi4TvZYUoglAsfy7HYSy7Dxun81Om0zLBxVaAOxFuLnxEP6+6eaHnJFZYtrFnjWw5zbn57Pk53IXzyAhPMaHg/QnjLxief5LWmLt9l7AAyh7zy6r9MSMRev2rOtuF9aFKUGmhGRuZv2fBVv7+E9CPyp2xT42xeAHam8YEAsFgT39lLb8DfwtISA==)

### 建议的解决方案

参考 [floating-ui](https://floating-ui.com/docs/arrow) 库。

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by webceoboy** [comment]
+1

**Comment by jahnli** [comment]
https://github.com/tusen-ai/naive-ui/issues/6577  duplicate
