### ISSUE TITLE
动态表单只有输入框才能正常报错！！！！！！！！！！！！

### ISSUE THREAD

**Issue by xinfeiyanwu** [tusen-ai/naive-ui#6104]
### 描述错误

`<template>
    <n-form ref="formRef" :model="dynamicForm" :style="{ maxWidth: '640px' }">
      <template :key="index" v-for="(item, index) in dynamicForm.hobbies">
        <n-form-item
          label="爱好"
          :path="`hobbies[${index}].hobby`"
          :rule="{
            required: true,
            message: `请输入爱好`,
            trigger: ['input', 'blur'],
          }"
        >
          <n-input v-model:value="item.hobby" placeholder="Input" />
        </n-form-item>
        <n-form-item
          label="爱好"
          :path="`hobbies[${index}].hobby1`"
          :rule="{
            required: true,
            message: `请输入爱好`,
            trigger: ['input', 'blur'],
          }"
        >
          <n-checkbox-group v-model:value="item.hobby1">
            <n-space>
              <n-checkbox value="Option 1"> Option 1 </n-checkbox>
              <n-checkbox value="Option 2"> Option 2 </n-checkbox>
              <n-checkbox value="Option 3"> Option 3 </n-checkbox>
            </n-space>
          </n-checkbox-group>
        </n-form-item>
        <n-form-item label="Select" :path="`hobbies[${index}].hobby2`">
          <n-select
            v-model:value="item.hobby2"
            placeholder="Select"
            multiple
            :options="[
              {
                label: 'saaa',
                value: 'saa',
              },
              {
                label: 'ddsds',
                value: '21111',
              },
            ]"
          />
        </n-form-item>
        <n-form-item label="Select" :path="`hobbies[${index}].hobby3`">
            <n-checkbox v-model:checked="item.hobby3">
            Checkbox
            </n-checkbox>
        </n-form-item>
        <n-form-item
          label="只有输入框正常？？？"
          :path="`hobbies[${index}].hobby4`"
          :rule="{
            required: true,
            message: `只有输入框正常？？？`,
            trigger: ['input', 'blur'],
          }"
        >
          <n-input v-model:value="item.hobby4" placeholder="Input" />
        </n-form-item>
        <n-form-item
          label="数字输入框也有问题？？？"
          :path="`hobbies[${index}].hobby5`"
          :rule="{
            required: true,
            message: `数字输入框也有问题？？？`,
            trigger: ['input', 'blur'],
          }"
        >
        <n-input-number v-model:value="item.hobby5" />
        </n-form-item>
      </template>
  
      <n-form-item>
        <n-space>
          <n-button attr-type="button" @click="handleValidateClick">
            验证
          </n-button>
          <n-button attr-type="button" @click="addItem"> 增加 </n-button>
        </n-space>
      </n-form-item>
    </n-form>
  </template>
  
  <script lang="ts">
  import { FormInst } from "naive-ui";
  import { defineComponent, reactive, ref } from "vue";
  
  export default defineComponent({
    setup() {
      const formRef = ref<FormInst | null>(null);
  
      const dynamicForm = reactive({
        name: "",
        hobbies: [{ hobby: "", hobby1: [], hobby2: [], hobby3:'', hobby4: '', hobby5: 0 }],
      });
  
      const removeItem = (index: number) => {
        dynamicForm.hobbies.splice(index, 1);
      };
  
      const addItem = () => {
        dynamicForm.hobbies.push({ hobby: "", hobby1: [], hobby2: [], hobby3:'', hobby4: '',  hobby5: 0 });
      };
  
      const handleValidateClick = () => {
        formRef.value?.validate((errors) => {
          if (!errors) {
            console.log("验证通过");
          } else {
            console.log(errors);
          }
        });
      };
  
      return {
        formRef,
        dynamicForm,
        addItem,
        removeItem,
        handleValidateClick,
      };
    },
  });
  </script>`

### 复现步骤

动态添加表单是不是只有输入框能报必填的错误？

### 最小复现链接

https://codesandbox.io/s/red-mountain-cfw45d?file=/src/Demo.vue

### 系统信息

```Shell
动态添加表单是不是只有输入框能报必填的错误？动态添加表单是不是只有输入框能报必填的错误？
```

### 使用的包管理器

npm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by xinfeiyanwu** [comment]
作者在吗，表单严重bug，看到麻烦改一下了。

**Comment by jahnli** [comment]
检查 `trigger`  看官网示例

**Comment by jahnli** [comment]
![Uploading image.png…]()
