### ISSUE TITLE
官网文档说明混乱

### ISSUE THREAD

**Issue by shen-lan** [tusen-ai/naive-ui#6105]
### Describe the bug

`https://www.naiveui.com/zh-CN/os-theme/components/data-table#DataTable-Props`  这里很清楚的写了 DataTableColumn 的所有属性，其中  titleRowSpan： title 行所占的单元格的个数。尴尬的事情来了，https://www.naiveui.com/zh-CN/os-theme/components/data-table#merge-cell 合并单元格这里， 合并表头又变成了  titleColSpan，且  titleColSpan未在DataTableColumn 属性说明中出现。
疑惑： 合并表头我到底该用哪个属性？

### Steps to reproduce

1

### Link to minimal reproduction

1

### System Info

```Shell
：1
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Nakus0426** [comment]
应该是使用 `titleColSpan`来合并表头列

**Comment by jahnli** [comment]
https://github.com/tusen-ai/naive-ui/pull/6116
