### ISSUE TITLE
希望可以给 n-tag标签里面的图标和头像 增加一个显示在文字前面或者后面的功能

### ISSUE THREAD

**Issue by HongJian-Yang** [tusen-ai/naive-ui#6106]
### 问题的清晰而简明的描述

无

### 建议的解决方案

无

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by jahnli** [comment]
slot default ?

**Comment by HongJian-Yang** [comment]
@jahnli    It's probably like this, although you can also put it behind using div and n-icon, can you add #suffix and #prefix to the slot like n-input

`<n-tag type="success">
      Checked
      <template #icon #prefix or #suffix>
        <n-icon :component="CheckmarkCircle" />
      </template>
    </n-tag>`
    
I don't know why the code for this comment is a single line. I've tried many times, but it's always a single line

![QQ截图20240705105225](https://github.com/tusen-ai/naive-ui/assets/58871921/17655d9e-12d8-481d-bc4f-9ece95d57f9d)

**Comment by jahnli** [comment]
没太必要吧，直接 default 插槽里放文字 + 图标不就可以随便自定义了吗

**Comment by HongJian-Yang** [comment]
> 没太必要吧，直接 default 插槽里放文字 + 图标不就可以随便自定义了吗

这样也能实现,  只是说官方提供的话, 感觉不用调大小和样式
