### ISSUE TITLE
select组件placeholder失效

### ISSUE THREAD

**Issue by daijianzzz** [tusen-ai/naive-ui#6107]
### Describe the bug

无

### Steps to reproduce

无

### Link to minimal reproduction

无

### System Info

```Shell
无
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
![image](https://github.com/tusen-ai/naive-ui/assets/20943608/b2354823-9c26-4735-a7ac-efd34ec8465d)
检查代码

**Comment by day-after-day** [comment]
这个设定非常反直觉，或者说反用户习惯。

解决方案就是你把 对应的 v-model 值设为undefined ，placeholder就能正常显示出来。

**Comment by Zhaocl1997** [comment]
emmm，确实，才发现，试了一下，select给空字符串的话placeholder就会消失🥲  还试了一个input，给空字符串ph就不会消失
感觉行为还是统一一下吧 可以的话 我改下select提个pr

**Comment by jahnli** [comment]
欢迎 pr
