### ISSUE TITLE
Table with ellipsis + lineClamp is not vertically centered

### ISSUE THREAD

**Issue by shaniqwa** [tusen-ai/naive-ui#6109]
### Describe the bug

when using the table column with ellipsis config with a tooltip and lineClamp, the text is not vertically centered in the td.

with lineClamp:
![Screenshot 2024-07-04 at 13 19 24](https://github.com/tusen-ai/naive-ui/assets/124711028/3959beba-34f5-42f6-94f9-6d3dc6b9463c)

without lineClamp:
![Screenshot 2024-07-04 at 13 23 13](https://github.com/tusen-ai/naive-ui/assets/124711028/c0a6315f-58bc-4a3a-9f67-1f13ba7abf80)

### Steps to reproduce

1. use ellipsis with lineClamp config:
```
      ellipsis: {
        tooltip: true,
        lineClamp: 4
      },
```
2. the text is not aligned 

### Link to minimal reproduction

https://codesandbox.io/s/gifted-lena-k53rqr?file=/src/Demo.vue

### System Info

```Shell
System:
    OS: macOS 14.4.1
    CPU: (8) arm64 Apple M2
    Memory: 73.92 MB / 24.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.2.0 - /opt/homebrew/bin/node
    Yarn: 4.0.2 - /opt/homebrew/bin/yarn
    npm: 10.2.3 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 126.0.6478.127
    Edge: 126.0.2592.87
    Safari: 17.4.1
  npmPackages:
    naive-ui: ^2.38.2 => 2.38.2 
    vue: ^3.4.21 => 3.4.21
```

### Used Package Manager

yarn

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Nakus0426** [comment]
Use this style to solve the problem:
``` css
.n-ellipsis {
    overflow: hidden;
    vertical-align: middle;
}
```

**Comment by shaniqwa** [comment]
@Nakus0426 thank you :)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
