### ISSUE TITLE
Nuxt3中表单的自定义验证规则取不到值

### ISSUE THREAD

**Issue by zy598586050** [tusen-ai/naive-ui#6112]
### 描述错误

自定义validator里取不到值，甚至formRef.value.validator报没有validator方法

### 复现步骤

请看下面的复现Demo

### 最小复现链接

https://github.com/zy598586050/nuxt3-naive-ui-bug

### 系统信息

```Shell
"naive-ui": "^2.38.2",
"nuxt": "^3.12.3",
"nuxtjs-naive-ui": "^1.0.2",
"vue": "latest"
```

### 使用的包管理器

npm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by zy598586050** [comment]
@jahnli 请教一下，感谢感谢

**Comment by zy598586050** [comment]
v-model:value
不能省略:value

**Comment by jahnli** [comment]
👍
