### ISSUE TITLE
The rail of n-slider has problem while using vertical mode.

### ISSUE THREAD

**Issue by dustbin1415** [tusen-ai/naive-ui#6114]
### Describe the bug

The rail of n-slider didn't display while using vertical mode. It looks like the width of n-slider’s rail has some problems.

### Steps to reproduce

Using n-slider with `vertical` prop.

### Link to minimal reproduction

https://github.com/dustbin1415/reproduction-of-NSlider-bug

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) arm64 Snapdragon (TM) 8cx Gen 3 @ 3.0 GHz
    Memory: 2.31 GB / 15.43 GB
  Binaries:
    Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.81)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    naive-ui: ^2.38.2 => 2.38.2
    vue: ^3.4.31 => 3.4.31
```

### Used Package Manager

npm

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [x] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Nakus0426** [comment]
Please provide an example where you can run and see this bug as it does not exist in the documentation and its codesandbox.
![image](https://github.com/tusen-ai/naive-ui/assets/41540888/02b53ed7-6d7d-400f-a72d-f6721617ffe2)

**Comment by dustbin1415** [comment]
> Please provide an example where you can run and see this bug as it does not exist in the documentation and its codesandbox. ![image](https://private-user-images.githubusercontent.com/41540888/346797646-02b53ed7-6d7d-400f-a72d-f6721617ffe2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MzQwNzcsIm5iZiI6MTcyMDUzMzc3NywicGF0aCI6Ii80MTU0MDg4OC8zNDY3OTc2NDYtMDJiNTNlZDctNmQ3ZC00MDBmLWE3MmQtZjY3MjE2MTdmZmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDE0MDI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0ZmQxNmQwN2Y3MGJjMWNmMTYwMTVlNzU3ODliOTMwNDBhYTEwMWE0YWYzMWZhYjRmZDQ2NGJmZGQ0NTVlZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zOCEgEDQUePSVsOEP_JigXayG69zC1sltrIO_2kFzCQ)

I have already update the hub of reproduction with the whole vue framework. And I'm sure the bug can be seem in that. I just built the project with `npm creat vue@latest` command and change the `vue` file.

**Comment by jizai1125** [comment]
It’s caused by the universal selector style `box-sizing: border-box`. Remove or override it.
<img width="412" alt="image" src="https://github.com/tusen-ai/naive-ui/assets/33979706/5b247444-c5bf-4761-8b17-42913650ddaa">
