### ISSUE TITLE
树 Tree组件使用关联选项搜索时，会出现勾选的选项错误的情况

### ISSUE THREAD

**Issue by maddenBoy** [tusen-ai/naive-ui#6115]
### 描述错误

树 Tree组件使用关联选项搜索时，会出现勾选的选项错误的情况

### 复现步骤

1、[打开链接](https://codesandbox.io/s/small-wave-vd79j4?file=/src/Demo.vue)
2、搜索0-0-0，然后勾选0-0-0
![image](https://github.com/tusen-ai/naive-ui/assets/71129660/969c5050-010d-45a4-9699-969ef73966c0)
3、清空搜索条件后，0下的节点全部被勾选
![image](https://github.com/tusen-ai/naive-ui/assets/71129660/56412494-d59f-4e99-9edc-a6b76527a771)
4、或者在勾选0-0-0后，把0-0-0改成0-0-1，发现0-0-1也被勾选
![image](https://github.com/tusen-ai/naive-ui/assets/71129660/4493db90-28a9-4125-803d-b2117dce4a40)

### 最小复现链接

https://codesandbox.io/s/small-wave-vd79j4?file=/src/Demo.vue

### 系统信息

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 9 5900HX with Radeon Graphics        
    Memory: 14.09 GB / 31.40 GB
  Binaries:
    Node: 14.16.0 - ~\AppData\Local\Volta\tools\image\node\14.16.0\node.EXE
    Yarn: 1.22.19 - C:\Program Files\Volta\yarn.EXE
    npm: 6.14.11 - ~\AppData\Local\Volta\tools\image\node\14.16.0\npm.CMD
    pnpm: 8.14.1 - C:\Program Files\Volta\pnpm.EXE
  Browsers:
    Edge: Chromium (126.0.2592.87)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    naive-ui: 2.38.1 => 2.38.1 
    vue: ^3.2.39 => 3.2.39
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by Nakus0426** [comment]
复现的链接挂了
![image](https://github.com/tusen-ai/naive-ui/assets/41540888/0f721e6e-3ab9-4907-9921-f335f04fab05)

**Comment by maddenBoy** [comment]
> 复现的链接挂了 ![image](https://private-user-images.githubusercontent.com/41540888/346457760-0f721e6e-3ab9-4907-9921-f335f04fab05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjIxNjAsIm5iZiI6MTcyMDQyMTg2MCwicGF0aCI6Ii80MTU0MDg4OC8zNDY0NTc3NjAtMGY3MjFlNmUtM2FiOS00OTA3LTk5MjEtZjMzNWYwNGZhYjA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA2NTc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNTkxMjc0N2VjMDNkNTYxMGU2YTkwYzc5ODhmMWJkNDlhMjViNGFjZTk4NGNhZGI5MTc2ODRiY2JkYzkxMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mec6MW5srRblAsAy12ylrPWKyGAPC0KHNdqn2HH9gTw)

用这个链接试一下https://codesandbox.io/s/small-wave-vd79j4?file=/src/Demo.vue，其实就是官网tree组件中的搜索示例，给tree组件加上cascade、checkable属性

**Comment by Nakus0426** [comment]
> > 复现的链接挂了 ![image](https://private-user-images.githubusercontent.com/41540888/346457760-0f721e6e-3ab9-4907-9921-f335f04fab05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjIxNjAsIm5iZiI6MTcyMDQyMTg2MCwicGF0aCI6Ii80MTU0MDg4OC8zNDY0NTc3NjAtMGY3MjFlNmUtM2FiOS00OTA3LTk5MjEtZjMzNWYwNGZhYjA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA2NTc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNTkxMjc0N2VjMDNkNTYxMGU2YTkwYzc5ODhmMWJkNDlhMjViNGFjZTk4NGNhZGI5MTc2ODRiY2JkYzkxMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mec6MW5srRblAsAy12ylrPWKyGAPC0KHNdqn2HH9gTw)
> 
> 用这个链接试一下https://codesandbox.io/s/small-wave-vd79j4?file=/src/Demo.vue 其实就是官网tree组件中的搜索示例，给tree组件加上cascade、checkable属性

试了一下，是这个prop导致的 `show-irrelevant-nodes="false"`，临时解决可以先不用这个功能

**Comment by maddenBoy** [comment]
> > > 复现的链接挂了 ![image](https://private-user-images.githubusercontent.com/41540888/346457760-0f721e6e-3ab9-4907-9921-f335f04fab05.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjIxNjAsIm5iZiI6MTcyMDQyMTg2MCwicGF0aCI6Ii80MTU0MDg4OC8zNDY0NTc3NjAtMGY3MjFlNmUtM2FiOS00OTA3LTk5MjEtZjMzNWYwNGZhYjA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA2NTc0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlNTkxMjc0N2VjMDNkNTYxMGU2YTkwYzc5ODhmMWJkNDlhMjViNGFjZTk4NGNhZGI5MTc2ODRiY2JkYzkxMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mec6MW5srRblAsAy12ylrPWKyGAPC0KHNdqn2HH9gTw)
> > 
> > 
> > 用这个链接试一下https://codesandbox.io/s/small-wave-vd79j4?file=/src/Demo.vue 其实就是官网tree组件中的搜索示例，给tree组件加上cascade、checkable属性
> 
> 试了一下，是这个prop导致的 `show-irrelevant-nodes="false"`，临时解决可以先不用这个功能

需要用到搜索的场景数据量一般都比较多，不使用show-irrelevant-nodes属性（只是加了横线）感觉还是要在海量数据中找到想要的数据进行勾选，比较麻烦😄
