### ISSUE TITLE
NDataTable Column sorter adds `n-data-table-td-hover` class

### ISSUE THREAD

**Issue by davidmoshal** [tusen-ai/naive-ui#6118]
### Describe the bug

Adding a 'sorter' property to an NDataTable, and setting tdColorHover results in `n-data-table-td-hover` class being attached to every td element row in that column when the table is sorted by that column!

In addition if a `defaultSortOrder'`is specified then all the cell rows in that column have the tdColorHover applied (ie: have n-data-table-td--hover class applied)

### Steps to reproduce

The error can be reproduced on your website:

1. go to: https://www.naiveui.com/en-US/os-theme/components/data-table
2. use the Theme Editor to set tdColorHover to a distinct color.
3. sort the table
4. Open devtools, and note that even though there is no hovering over the cells, the n-data-table-td--hover class is applied: 

<img width="879" alt="Screenshot 2024-07-09 at 1 10 24 AM" src="https://github.com/tusen-ai/naive-ui/assets/650245/4b6effa7-b5b6-4bf5-a4cf-f484a06f4b7a">

### Link to minimal reproduction

https://www.naiveui.com/en-US/os-theme/components/data-table

### System Info

```Shell
npx envinfo --system --npmPackages 'naive-ui,vue' --binaries --browsers
sh: envinfo: command not found


Note: the error occurs on your website!
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by davidmoshal** [comment]
I believe the error is here:

Line 831 of `src/data-table/src/TableParts/Body.tsx`:
```ts
isColumnSorting(column, mergedSortState)) &&
`${mergedClsPrefix}-data-table-td--hover`,
```
this is what I'm seeing, ie: if the column is sorting ,then the hover class is added

**Comment by davidmoshal** [comment]
And commenting out this: ` || isColumnSorting(column, mergedSortState)` fixes it:
ie:
```ts
((hoverKey !== null &&
  cordKey[displayedRowIndex][colIndex].includes(
    hoverKey
  ))
  // || isColumnSorting(column, mergedSortState)
) &&
  `${mergedClsPrefix}-data-table-td--hover`,
  ```
  I can't see why the hover color should be applied whenever the column is sorting?
  What am I missing here?

**Comment by 07akioni** [comment]
This is the expected behavior. I think it's better to split those two states by different class names.

**Comment by davidmoshal** [comment]
Makes sense to separated them, otherwise while sorting, the entire column is the hover color, and if all columns are sortable, with a default sorter, then the entire table is the hover color!
