### ISSUE TITLE
无限滚动组件使用滚动条不能一直触发on-load

### ISSUE THREAD

**Issue by shilim-developer** [tusen-ai/naive-ui#6133]
### 描述错误

无限滚动组件拖动滚动条到底部时，然后就无法再触发到底部了
### 复现步骤

使用滚动条拖动到底部，元素增加后，就不再继续出发加载了，使用文档的演示就可以复现

### 最小复现链接

https://www.naiveui.com/zh-CN/light/components/infinite-scroll

### 系统信息

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1155G7 @ 2.50GHz
    Memory: 1.50 GB / 15.79 GB
Browsers:
    Edge: Chromium (126.0.2592.87)
    Internet Explorer: 11.0.22621.3527
```

### 使用的包管理器

npm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by shilim-developer** [comment]
帮你发现问题了
https://github.com/tusen-ai/naive-ui/blob/main/src/_internal/scrollbar/src/Scrollbar.tsx#L432
https://github.com/tusen-ai/naive-ui/blob/main/src/infinite-scroll/src/InfiniteScroll.tsx#L31

handleCheckBottom检查是否在底部用的是scrollbar的containerScrollTop，但在scrollbar的回调中其实先触发onScroll事件再更新containerScrollTop的值，所以handleCheckBottom中拿到的containerScrollTop的值其实不是最新的

**Comment by CrassusX** [comment]
window.addEventListener('scroll', onScroll, true);
