### ISSUE TITLE
n-grid栅格布局与vuedraggable一起使用不显示不报错

### ISSUE THREAD

**Issue by breezechime** [tusen-ai/naive-ui#6134]
### 描述错误

我使用n-grid和vuedraggable实现拖拽但是n-grid一旦加入vuedraggable item就会不显示

![image](https://github.com/tusen-ai/naive-ui/assets/89468384/35fb6431-bac2-44fa-bd88-ca5ae25f1862)

### 复现步骤

```vue
<n-grid :cols="3" :x-gap="12" style="padding-left: 4px; padding-right: 4px">
      <draggable :list="state.commonCompList">
        <template #item="{element}">
          <n-grid-item class="comp-item-se">
            <i class="icon"
               :style="{
                   'background-image': 'url(' + element.image + ')'
                 }"></i>
            <div class="name">{{ element.name }}</div>
          </n-grid-item>
        </template>
      </draggable>
    </n-grid>
```

### 最小复现链接

https://codesandbox.io/p/sandbox/loving-sanne-h7c7q9?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clygzap4w00063j6jjv6dg13x%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clygzap4w00023j6jsfscb2ck%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clygzap4w00033j6j8ye867i5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clygzap4w00053j6jj0hf7eua%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clygzap4w00023j6jsfscb2ck%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clygzap4v00013j6j50rlz05a%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.html%2522%257D%255D%252C%2522id%2522%253A%2522clygzap4w00023j6jsfscb2ck%2522%252C%2522activeTabId%2522%253A%2522clygzap4v00013j6j50rlz05a%2522%257D%252C%2522clygzap4w00053j6jj0hf7eua%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clygzap4w00043j6jwncfq65j%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clygzap4w00053j6jj0hf7eua%2522%252C%2522activeTabId%2522%253A%2522clygzap4w00043j6jwncfq65j%2522%257D%252C%2522clygzap4w00033j6j8ye867i5%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clygzap4w00033j6j8ye867i5%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### 系统信息

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 AMD Ryzen 5 4600H with Radeon Graphics         
    Memory: 412.18 MB / 15.87 GB
  Binaries:
    Node: 20.15.0 - D:\develop\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.7.0 - D:\develop\nodejs\npm.CMD
    pnpm: 7.27.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (126.0.2592.87)
    Internet Explorer: 11.0.19041.4355
```

### 使用的包管理器

npm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by breezechime** [comment]
没人吗？

**Comment by jahnli** [comment]
'n-grid' content can only be 'n-grid-item'

```
 if ((child?.type as any)?.__GRID_ITEM__ !== true)
          return
```
