### ISSUE TITLE
选择器Select的SelectOption中value值无法使用number类型的数字

### ISSUE THREAD

**Issue by shijunpeng15** [tusen-ai/naive-ui#6141]
### Describe the bug

选择器Select的SelectOption中value值无法使用number类型的数字

### Steps to reproduce

选择器Select的SelectOption中value值无法使用number类型的数字

### Link to minimal reproduction

https://stackblitz.com/edit/vitejs-vite-facawk?file=src%2Fcomponents%2FHelloWorld.vue

### System Info

```Shell
naive-ui：2.38.2
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
你需要为 rule 添加
`type: 'number'`

**Comment by HongJian-Yang** [comment]
> 你需要为 rule 添加 `type: 'number'`

如果是boolean 是不是 `type: 'boolean `也可以, 因为有些选项只有true false
