### ISSUE TITLE
Dialog 自定义content 文字意外的换行?

### ISSUE THREAD

**Issue by HongJian-Yang** [tusen-ai/naive-ui#6143]
### Describe the bug

打开官方的例子, https://codesandbox.io/s/st4hfc
然后把content内的文字换成冒号后这一行文字:    确定 启用 这个 [这个东西的名字] 下的 [/aa/bb/cc/dd/ee/ff/dd] 吗?
就会被换行? 如果是中文, 则没有这个问题
中文: 确定 启用 分组 [分组的名字啊] 下的 [/中文中文中/中文中文中/中文中文中/{id}] 访问地址?
![QQ截图20240715140450](https://github.com/user-attachments/assets/158314ee-784f-41e1-9f61-0dae938a004b)
![QQ截图20240715141133](https://github.com/user-attachments/assets/896a3e15-b8c9-40e1-a4e3-dac99f21962a)

### Steps to reproduce

把content内的文字换成: 确定 启用 这个 [这个东西的名字] 下的 [/aa/bb/cc/dd/ee/ff/dd] 吗?

### Link to minimal reproduction

https://codesandbox.io/s/st4hfc

### System Info

```Shell
Microsoft Edge
版本 126.0.2592.102 (正式版本) (64 位)
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HongJian-Yang** [comment]
找到原因了, css样式 https://developer.mozilla.org/zh-CN/docs/Web/CSS/word-break

**Comment by Nakus0426** [comment]
应该是 `[英文]` 被识别成了单词，导致 `word-break: break-word` 生效了，而  `[中文]` 则不会
