### ISSUE TITLE
Data Table增强列、行拖动排序

### ISSUE THREAD

**Issue by mustars** [tusen-ai/naive-ui#6144]
### 问题的清晰而简明的描述

Data Table增强列、行拖动排序

### 建议的解决方案

Data Table增强列、行拖动排序

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by jahnli** [comment]
https://github.com/tusen-ai/naive-ui/issues/6187  duplicate
