### ISSUE TITLE
tabs标签页位置设置为left的时候，prefix和suffix位置没有同步切换到标签列的上下位置，还是在标签列的左右两边

### ISSUE THREAD

**Issue by yuanhongyu123** [tusen-ai/naive-ui#6151]
### Describe the bug

tabs标签页位置设置为left的时候，prefix和suffix位置没有同步移动到上下位置，还是在标签页的左右两边

![image](https://github.com/user-attachments/assets/12bc4463-5e09-463e-98c0-2138fe44d07d)

![image](https://github.com/user-attachments/assets/48ced6b0-fff7-42bc-be3c-6aeaf016f16c)

### Steps to reproduce

无

### Link to minimal reproduction

无

### System Info

```Shell
无
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Nakus0426** [comment]
请提供最小复现

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
