### ISSUE TITLE
n-flex 和 n-ellipsis同时使用会出现两个title

### ISSUE THREAD

**Issue by zlecheng** [tusen-ai/naive-ui#6153]
## 代码
```html
<n-flex align="center" justify="space-between">

<n-ellipsis style="max-width: 240px">
  <span>  内容区域内容区域内容区域 </span>
</n-ellipsis>

</n-flex>

```

## 截图
![image](https://github.com/user-attachments/assets/6ec7f3c4-5618-4355-ad63-8cc1f6f273d9)

### Steps to reproduce

n-flex 内部使用  n-ellipsis

### Link to minimal reproduction

无

### System Info

```Shell
电脑信息：windows11 64位 
vue版本：^3.4.27
native-ui版本：^2.38.2
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
提供个在线复现链接

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
