### ISSUE TITLE
树 Tree组件数据量稍大时展开所有节点时会明显卡顿

### ISSUE THREAD

**Issue by maddenBoy** [tusen-ai/naive-ui#6163]
### 描述错误

树 Tree组件数据量稍大时展开所有节点时会明显卡顿

### 复现步骤

1、打开链接
2、点击展开节点，此时发现明显卡顿（可调整treeNum变量，treeNum为6时没有明显卡顿，treeNum越大时卡顿越明显）

### 最小复现链接

https://codesandbox.io/s/wizardly-frost-rymj2j?file=/src/Demo.vue

### 系统信息

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 9 5900HX with Radeon Graphics        
    Memory: 7.59 GB / 31.40 GB
  Binaries:
    Node: 14.16.0 - ~\AppData\Local\Volta\tools\image\node\14.16.0\node.EXE
    Yarn: 1.22.19 - C:\Program Files\Volta\yarn.EXE
    npm: 6.14.11 - ~\AppData\Local\Volta\tools\image\node\14.16.0\npm.CMD
    pnpm: 8.14.1 - C:\Program Files\Volta\pnpm.EXE
  Browsers:
    Edge: Chromium (126.0.2592.102)
    Internet Explorer: 11.0.22621.3527
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by Nakus0426** [comment]
这么大量的数据，你应该把 `virtual-scroll` 开起来的，用你的例子试了下，开启虚拟列表后展开/折叠全部并没有明显的卡顿
![PixPin_2024-07-22_15-24-53](https://github.com/user-attachments/assets/897aaf23-d705-4173-acf3-b24b51b638eb)

**Comment by maddenBoy** [comment]
没有设置高度、或者最大高度的场景似乎不适用这种解决方案

**Comment by Nakus0426** [comment]
> 没有设置高度、或者最大高度的场景似乎不适用这种解决方案

那就没办法，这么多dom节点和数据不可能不卡
而且，这个高度也不一定是个静态值，只要指定了高度即可

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
