### ISSUE TITLE
message能不能统一自定义样式呀?

### ISSUE THREAD

**Issue by pepsi1211** [tusen-ai/naive-ui#6169]
### 问题的清晰而简明的描述

因为在头部是白色底色的时候, message的提示非常不明显, 现在项目说要改, 如果二次封装, 那要改的地方非常多, 有没有什么方法能够统一修改message的 样式

### 建议的解决方案

在message添加一个统一的渲染方式

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by jahnli** [comment]
https://codesandbox.io/s/empty-rain-wr3r3m?file=/src/Demo.vue:0-1046
