### ISSUE TITLE
二次封装的NSelect, options应该怎么写

### ISSUE THREAD

**Issue by ZaL0-0** [tusen-ai/naive-ui#6175]
### Describe the bug

有个需求必须二次封装select组件，如图所示想创建类似右侧一样循环生成的option标签，但是没找到NOption标签，写死的options假数据也没有生效，尝试了renderReportsOption没有效果
![image](https://github.com/user-attachments/assets/3e12c2a7-deea-49de-9f8b-7f2397c62b12)

### Steps to reproduce

描述即可

### Link to minimal reproduction

暂无

### System Info

```Shell
"naive-ui": "^2.38.1",
"vue": "^3.4.26",
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
`options`  是 `Select` 的 `Props`

**Comment by ZaL0-0** [comment]
> `options` 是 `Select` 的 `Props`

是，我直接写props也不生效，我上面给options重新赋值了

**Comment by jahnli** [comment]
发个在线复现链接

**Comment by ZaL0-0** [comment]
> Collaborator

我这个是基于开源组件库进行改造的，依赖的有点多不知道怎么给最小复现🤦‍
![image](https://github.com/user-attachments/assets/06c57c84-31e8-4b10-b5d7-c79e20dc5112)
![企业微信截图_17216974781136](https://github.com/user-attachments/assets/8899ce82-19b5-4aef-bd5b-ba11f62cffca)
props数据可以打印出来，其实就是想吧options单独拿出来循环赋值，类似与element的ElOption那个写法
