### ISSUE TITLE
n-tree checkbox 增加样式自定义

### ISSUE THREAD

**Issue by yushan023** [tusen-ai/naive-ui#6176]
### 问题的清晰而简明的描述

![image](https://github.com/user-attachments/assets/bd8f300a-f778-496a-ab7c-6db585a62265)
需求：勾选【2300】运营部  需要把【2706】系统保障二部  【413116】运营三部   一起勾选，
但是取消勾选【2706】系统保障二部  【413116】运营三部   不能取消勾选【2300】运营部
这个时候我需要将【2300】运营部前面的checkbox 背景颜色调整与主题色不一样区分

现在只支持勾选/半选 

### 建议的解决方案

我曾经还看到过下图这种填充的样式
勾选子项，并不代表勾选父节点
勾选父项，就需要把子项也勾选
![image](https://github.com/user-attachments/assets/f077e9fd-1e02-410b-b618-21637ccb1b09)
![image](https://github.com/user-attachments/assets/28a425b7-40f1-4394-86f8-bffb2dd63cd1)

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by jahnli** [comment]
可以通过标签 `style` 自定义

**Comment by yushan023** [comment]
我在树里面怎么用style自定义checkbox呢？你能举个例子嘛？

**Comment by yushan023** [comment]
希望n-tree 增加render-checkbox 这种属性  根据属性渲染不同的样式
现在n-tree只有render-label
