### ISSUE TITLE
关于n-tree级联数据回显的问题

### ISSUE THREAD

**Issue by dimples9527** [tusen-ai/naive-ui#6188]
### 描述错误

当我在使用n-tree组件时，同时开启cascade支持级联选择，然后checked-keys进行已选择数据回显，如图
![image](https://github.com/user-attachments/assets/cf74048e-fb5a-46e0-9c7e-6166819e4cc5)
当我在checked-keys中设置的节点有父节点时，他会在回显的时候自动勾选父节点下的所有子节点，实际上，父节点下的部分子节点并未被选择，也并未设置到checked-keys中，我想要的功能是，数据回显时只选择我在checked-keys中设置的节点，但是在手动选择时，还是能够支持级联选择

### 复现步骤

1. 树节点数据回显
2. 树节点勾选

### 最小复现链接

无

### 系统信息

```Shell
无
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by oknimasi** [comment]
你可以这样想，你把data中最底层的数据作为 checked-keys的参数是不是就可以了

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
