### ISSUE TITLE
ip输入框支持？

### ISSUE THREAD

**Issue by LinYuanq** [tusen-ai/naive-ui#6201]
### 问题的清晰而简明的描述

现在貌似input控件不支持ip输入框

### 建议的解决方案

先确认能否支持？不支持的话是否考虑支持？

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by Sepush** [comment]
![image](https://github.com/user-attachments/assets/ec5a1928-81eb-46a1-a115-77705dde4f8a)

**Comment by LinYuanq** [comment]
> ![image](https://private-user-images.githubusercontent.com/39197136/354905149-ec5a1928-81eb-46a1-a115-77705dde4f8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NDM2MjMsIm5iZiI6MTcyMjg0MzMyMywicGF0aCI6Ii8zOTE5NzEzNi8zNTQ5MDUxNDktZWM1YTE5MjgtODFlYi00NmExLWExMTUtNzc3MDVkZGU0ZjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA3MzUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwMzM0ZWQ4YzI0N2VmNWVjMWM4ZDhhY2VhMjIyMmM1NTAyNTRhYjhlZmMwOWZlNzVmYzgwZWE4NTllYmRlOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MTUqA5CeGLboKEeeo5MppdM9-Ql9bQtiKogtz0PfKY4)

您贴的图只是证明了普通输入框能够输入ip的形式。。但并非ip输入框，或许我应该描述的更精确一些：能够自动支持ip4形式下的四个分段及各分段ip范围的自动限制的输入框类型。

**Comment by LinYuanq** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/39197136/354905149-ec5a1928-81eb-46a1-a115-77705dde4f8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4NDM2MjMsIm5iZiI6MTcyMjg0MzMyMywicGF0aCI6Ii8zOTE5NzEzNi8zNTQ5MDUxNDktZWM1YTE5MjgtODFlYi00NmExLWExMTUtNzc3MDVkZGU0ZjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDA3MzUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwMzM0ZWQ4YzI0N2VmNWVjMWM4ZDhhY2VhMjIyMmM1NTAyNTRhYjhlZmMwOWZlNzVmYzgwZWE4NTllYmRlOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MTUqA5CeGLboKEeeo5MppdM9-Ql9bQtiKogtz0PfKY4)
> > 
> > 
> > 您贴的图只是证明了普通输入框能够输入ip的形式。。但并非ip输入框，或许我应该描述的更精确一些：能够自动支持ip4形式下的四个分段及各分段ip范围的自动限制的输入框类型。
> 
> 这种应该是不会特别支持的 你可以使用 form 和 input 自定义validation封装一个Field

好的
