### ISSUE TITLE
data-table 虚拟滚动样式不更新

### ISSUE THREAD

**Issue by duyuntao** [tusen-ai/naive-ui#6204]
### 描述错误

我使用data-table组件并且自定义了所有列，我将列铺满并且给了背景颜色，背景颜色是动态的，但是发现颜色并没有改变

### 复现步骤

1.使用data-table
2. 开启虚拟滚动
3.  使用render给与一个元素 并动态生成css给与元素

### 最小复现链接

无

### 系统信息

```Shell
无
```

### 使用的包管理器

npm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by Nakus0426** [comment]
请提供最小复现链接
![image](https://github.com/user-attachments/assets/50595191-8e7a-41dd-9c74-3caadc64cf2e)
