### ISSUE TITLE
希望优化数据表格 Data Table每一行数据不同的显示需求

### ISSUE THREAD

**Issue by weixinyi** [tusen-ai/naive-ui#6206]
### Clear and concise description of the problem

希望表格支持插槽写法

### Suggested solution

比如说column.ellipsis.tooltip 使得省略内容有弹出提示的这个属性，写法略微麻烦，如果支持插槽，就可以直接在插槽里写一个文字提示

### Alternative

希望可以在columns属性里支持slot属性

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jahnli** [comment]
https://www.naiveui.com/zh-CN/os-theme/components/data-table#ellipsis-tooltip.vue
https://www.naiveui.com/zh-CN/os-theme/components/data-table#custom-style.vue

你也可以使用  `render` `tsx` 来代替插槽
