### ISSUE TITLE
Popconfirm 嵌套 组件包装的tooltip 使用时出错

### ISSUE THREAD

**Issue by s3xysteak** [tusen-ai/naive-ui#6210]
### 描述错误

在popConfirm中使用tooltip正常，但是在popConfirm中使用 组件包装的tooltip 出错

### 复现步骤

1. 点击按钮
2. popconfirm显示在左上角
3. 期望显示在按钮上方

### 最小复现链接

https://stackblitz.com/edit/vitejs-vite-m8svcq?file=src%2FApp.vue

### 系统信息

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz
    Memory: 5.37 GB / 15.90 GB
  Binaries:
    Node: 20.10.0 - ~\AppData\Local\fnm_multishells\11540_1722325192738\node.EXE
    npm: 10.2.3 - ~\AppData\Local\fnm_multishells\11540_1722325192738\npm.CMD
    pnpm: 9.6.0 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by collincheng** [comment]
@s3xysteak 
<img width="1327" alt="image" src="https://github.com/user-attachments/assets/725791a2-4f66-4475-8004-d92c00c684bd">
关注一下 getTriggerElement 的样式

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
