### ISSUE TITLE
umd 方式引入message报错

### ISSUE THREAD

**Issue by ArtisanQ** [tusen-ai/naive-ui#6215]
### 描述错误

umd 方式引入message报错
![image](https://github.com/user-attachments/assets/09c5116b-af64-4710-8e99-6457108d294e)

### 复现步骤

![image](https://github.com/user-attachments/assets/09c5116b-af64-4710-8e99-6457108d294e)

### 最小复现链接

--

### 系统信息

```Shell
--
```

### 使用的包管理器

npm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jahnli** [comment]
you need to provide `n-message-provider`
