### ISSUE TITLE
想要一个往左边弹出的菜单

### ISSUE THREAD

**Issue by jiangzik** [tusen-ai/naive-ui#6223]
### 问题的清晰而简明的描述

![image](https://github.com/user-attachments/assets/836712d6-7d25-4e9c-b57a-19f6027f140e)

### 建议的解决方案

现在菜单都是在左侧的这种，向右侧弹出。能否新增一个属性，让菜单是在右侧的，往左侧弹出

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by Mikasa33** [comment]
是这个吗？
折叠侧边栏的位置 https://www.naiveui.com/zh-CN/light/components/layout#collapse-right.vue

**Comment by jiangzik** [comment]
感谢，还是我学艺不精
&nbsp;


　
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月1日(星期四) 晚上6:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tusen-ai/naive-ui] 想要一个往左边弹出的菜单 (Issue #6223)














 
是这个吗？
 折叠侧边栏的位置 https://www.naiveui.com/zh-CN/light/components/layout#collapse-right.vue
