### ISSUE TITLE
我想面板加一个小按钮，可以直接让它收缩或者弹出

### ISSUE THREAD

**Issue by jiangzik** [tusen-ai/naive-ui#6224]
### 问题的清晰而简明的描述

https://github.com/user-attachments/assets/a64ef64c-e6a1-40ee-ac1c-0ab6ae1e6f12

### 建议的解决方案

类似于菜单的弹出与收起加到面板分割里去

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by Nakus0426** [comment]
用 `resize-trigger` 插槽自己实现一个即可

**Comment by jiangzik** [comment]
好的十分感谢，就是自己实现的可能主题适配方面会有点不好看

**Comment by Nakus0426** [comment]
> 好的十分感谢，就是自己实现的可能主题适配方面会有点不好看

搭配 `n-element` 和 `config-provider` 即可，参考[这篇文章](https://www.naiveui.com/zh-CN/light/docs/theme)
