### ISSUE TITLE
数据表格能否设定其整体高度填充剩余的高度空间

### ISSUE THREAD

**Issue by abcbuzhiming** [tusen-ai/naive-ui#6226]
### 问题的清晰而简明的描述

官方例子对表格的高度都是限制最大高度，而且是是明确的px单位，比如max-height="150px"。但是这样只能让表格限定为固定高度，不能适应界面响应化的要求

### 建议的解决方案

能否给出一个类似CSS中 flex:1 这样的设定，就是让表格的高度，填充剩余的内容区域的高度。而不是像现在这样，要不就是高度限死，要不就是和表格里的记录数量有关系。不能跟着内容区高度产生联动。因为很多时候表格其实是内容区域的最后一个元素，大部分设计者都是希望这个元素能占据内容区域剩下的空间。

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by yeyuqh** [comment]
DataTable 不是有 `flex-height` 属性吗

**Comment by jahnli** [comment]
![image](https://github.com/user-attachments/assets/cbab4019-c501-4587-a019-0a2906d2fbb0)

**Comment by weixinyi** [comment]
flex-height 设置了就必须给个高度 ，pc端要滚动，手机端自适应的话就得 :flex-height判断
