### ISSUE TITLE
modal.create 中的 content 渲染自定义组件时无法在组件内使用 useMessage()

### ISSUE THREAD

**Issue by AemonCao** [tusen-ai/naive-ui#6227]
### 描述错误

modal.create 中的 content 渲染自定义组件时无法在组件内使用 useMessage()。

![image](https://github.com/user-attachments/assets/d3494d15-46d1-49e6-93be-ab8ca45dec18)

### 复现步骤

```VUE
// App.vue
<template>
  <NConfigProvider
    :theme="_theme"
    :locale="_locale"
    :date-locale="_dateLocale"
  >
    <NNotificationProvider>
      <NModalProvider>
        <NDialogProvider>
          <NMessageProvider>
            <RouterView />
          </NMessageProvider>
        </NDialogProvider>
      </NModalProvider>
    </NNotificationProvider>
  </NConfigProvider>
</template>

```

```vue
<script setup lang="ts">
const modal = useModal()

function handleClick() {
  const submitModal = modal.create({
    title: '编辑',
    preset: 'card',
    class: 'w-200',
    content: () => h(TheSubmit),
  })
}
</script>

<template>
	<NButton @click="handleClick">编辑</NButton>
</template>
```

```vue
// TheSubmit.vue
<script setup lang="ts">
import { useMessage } from 'naive-ui'

const message = useMessage()
</script>

<template>
	<div></div>
</template>
```

当点击“编辑”按钮时就会报错。

具体见复现链接。

### 最小复现链接

https://codesandbox.io/p/devbox/naive-ui-usemodal-d2vk9h

### 系统信息

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Memory: 18.06 GB / 39.92 GB
  Binaries:
    Node: 18.18.0 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    Yarn: 1.22.22 - ~\scoop\apps\yarn\current\bin\yarn.CMD
    npm: 9.8.1 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
    pnpm: 9.1.1 - G:\Code\gantt\node_modules\.bin\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    naive-ui: ^2.38.2 => 2.38.2
    vue: ^3.4.27 => 3.4.27
```

### 使用的包管理器

pnpm

### 验证

- [x] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by Sepush** [comment]
``` vue
<template>
  <NMessageProvider>
    <NModalProvider>
      <A />
    </NModalProvider>
  </NMessageProvider>
</template>
```

in your case  ` <NMessageProvider>` should be the parent of `<NModalProvider>` 

or when your model create it did not have message context

**Comment by AemonCao** [comment]
> ```
> <template>
>   <NMessageProvider>
>     <NModalProvider>
>       <A />
>     </NModalProvider>
>   </NMessageProvider>
> </template>
> ```
> 
> in your case ` <NMessageProvider>` should be the parent of `<NModalProvider>`
> 
> or when your model create it did not have message context

Thanks! It worked!
