### ISSUE TITLE
浮动按钮文档中的气泡案例无法生效

### ISSUE THREAD

**Issue by AemonCao** [tusen-ai/naive-ui#6228]
### 描述错误

浮动按钮文档中的气泡案例无法生效。

https://www.naiveui.com/zh-CN/os-theme/components/float-button#tooltip.vue

应该会有tooltip的气泡提示。但实际上并没有。

感觉和这个bug也有关系：https://github.com/tusen-ai/naive-ui/issues/6067

### 复现步骤

直接访问官方文档即可复现。

### 最小复现链接

https://www.naiveui.com/zh-CN/os-theme/components/float-button#tooltip.vue

### 系统信息

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700K
    Memory: 2.28 GB / 31.71 GB
  Binaries:
    Node: 20.13.1 - ~\scoop\apps\nvm\current\nodejs\nodejs\node.EXE
    Yarn: 1.22.22 - ~\scoop\apps\yarn\current\bin\yarn.CMD
    npm: 10.5.2 - ~\scoop\apps\nvm\current\nodejs\nodejs\npm.CMD
    pnpm: 9.1.1 - ~\Code\gantt\node_modules\.bin\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    naive-ui: ^2.38.2 => 2.38.2 
    vue: ^3.4.27 => 3.4.27
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by AemonCao** [comment]
https://github.com/user-attachments/assets/71c084ea-e002-4ab4-b594-adae1963463b

补充一个视频。并且在点击过按钮后，页面部分按钮会失效。

**Comment by Sepush** [comment]
repeat with https://github.com/tusen-ai/naive-ui/issues/5933 
fix in https://github.com/tusen-ai/naive-ui/commit/a5c3b902cdc2ab8895f5c4c4e07c21d5a719abc8
