### ISSUE TITLE
N-select attribute "default-value" does not setted in value

### ISSUE THREAD

**Issue by dartalex969** [tusen-ai/naive-ui#6229]
### Describe the bug

Props `default-value` does not affect on value itself. The value does not changed when props passed. It only displays thing, but not changes anything.

Why is it necessary? Imagine that we have a Parent component (Form) that passes props into Child component. We want to display in Child component select and update value into Parent component. So when i decide to pass a default-value I cannot scope it in Child component, although it's his area of ​​responsibility. I would be forced to pass default value for props, or make default value in Parent component. So attribute `default-value` is now unused, just for display, not for real changes

### Steps to reproduce

- create an empty reactive variable for value
- create an options object ( `{value: string | number, label: string}[]` ) 
- set a default-value attribute to `options[0].value`  
**Expected**: value to be setted as default value  
**Obtained**: value still undefined (no `doUpdateValue` call when `selectedOptionRef` computed run)  

### Link to minimal reproduction

https://codesandbox.io/s/immutable-sun-h3kd99?file=/src/App.vue

### System Info

```Shell
System:
    OS: macOS 14.4.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 81.34 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.7.3 - /opt/homebrew/bin/node
    Yarn: 1.22.22 - ~/node_modules/.bin/yarn
    npm: 10.5.0 - /opt/homebrew/bin/npm
    pnpm: 9.1.4 - ~/Uzum/FE/superadmin/node_modules/.bin/pnpm
  Browsers:
    Chrome: 127.0.6533.89
    Safari: 17.4.1
  npmPackages:
    naive-ui: 2.38.1 => 2.38.1 
    vue: 3.4.21 => 3.4.21
```

### Used Package Manager

yarn

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
You can use `value` `@update:value` or `v-model`
