### ISSUE TITLE
make table to be responsive to mobile view

### ISSUE THREAD

**Issue by srivishnu-sivan** [tusen-ai/naive-ui#6230]
### Clear and concise description of the problem

when a page is opened on mobile, half of the table is visible and half is not, 
![image](https://github.com/user-attachments/assets/608097ff-58b8-46e2-ab0a-f8648e8e522b)

### Suggested solution

in module NTable and NDataTable make it happen

### Alternative

give a prop name mobile, let it figure out the screen resolution and display the table based in it

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Sepush** [comment]
We might not specifically adapt to the mobile end.
