### ISSUE TITLE
弹窗中无法执行复制逻辑 n-modal

### ISSUE THREAD

**Issue by xstxhjh** [tusen-ai/naive-ui#6239]
### Describe the bug

<n-modal>  这个弹窗组件打开状态中，执行下面的复制逻辑无法复制成功。「关闭弹窗可以复制成功」

### Steps to reproduce

<n-modal> 打开时之行下面逻辑

```js
const copyHandleCommon = (stringValue = ''): boolean => {
  const textarea = document.createElement('textarea')
  textarea.readOnly = true
  textarea.style.position = 'absolute'
  textarea.style.left = '-9999px'
  textarea.value = stringValue
  document.body.appendChild(textarea)
  textarea.select()
  const result = document.execCommand('Copy')
  document.body.removeChild(textarea)
  if (result) {
    return true
  }
  return false
}
```

### Link to minimal reproduction

www.naiveui.com

### System Info

```Shell
"vue": "^3.4.31",
    "naive-ui": "^2.38.2",
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by pengzhen-developer** [comment]
不是 Naive UI 的问题，这是浏览器的可访问性限制，就像 Video 的自动播放无声音一样，你必须获得足够的可访问权限后，才能正常播放，可参考该回答：
https://stackoverflow.com/questions/48122221/working-copy-to-clipboard-function-doesnt-work-when-called-in-bootstrap-modal


``` javascript
function copytext(text) {
    var textField = document.createElement('textarea');
    textField.innerText = text;
    document.body.appendChild(textField);
    textField.select();
    textField.focus(); // 重点：模拟 Focus 
    document.execCommand('copy');
    textField.remove();
    console.log('should have copied ' + text); 
    ajax-error.focus(); // 移除 Focus
}
```

**Comment by serious-snow** [comment]
我这边遇到了同样的情况，解决办法是把 autoFocus和trapFocus改为false

{
  autoFocus: false,
  trapFocus: false
}
