### ISSUE TITLE
Upload 组件的`submit`公开类型与实际功能不一致

### ISSUE THREAD

**Issue by NHZEX** [tusen-ai/naive-ui#6246]
### 描述错误

https://www.naiveui.com/zh-CN/os-theme/components/select
`submit`文档内的声明是：`(fileId?: string | number)`

代码中的声明是：
https://github.com/tusen-ai/naive-ui/blob/da1483bb2841a91edb22bda068f047a80f7af909/src/upload/src/public-types.ts#L6-L8

实际功能：
https://github.com/tusen-ai/naive-ui/blob/da1483bb2841a91edb22bda068f047a80f7af909/src/upload/src/Upload.tsx#L577

存在不一致

### 复现步骤

无

### 最小复现链接

https://github.com/tusen-ai/naive-ui/blob/da1483bb2841a91edb22bda068f047a80f7af909/src/upload/src/public-types.ts#L6-L8

### 系统信息

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 5700X 8-Core Processor
    Memory: 31.14 GB / 63.93 GB
  Binaries:
    Node: 20.14.0 - ~\AppData\Local\Volta\tools\image\node\20.14.0\node.EXE
    Yarn: 1.22.21 - ~\AppData\Local\Volta\tools\image\yarn\1.22.21\bin\yarn.CMD
    npm: 10.7.0 - ~\AppData\Local\Volta\tools\image\node\20.14.0\npm.CMD
    pnpm: 9.6.0 - ~\AppData\Local\Volta\tools\image\pnpm\9.6.0\bin\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    naive-ui: 2.39.0 => 2.39.0 
    vue: 3.4.35 => 3.4.35
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by Sepush** [comment]
fix in pr #5882
