### ISSUE TITLE
Cascader , multiple is true, and discard all selections,@update:value handleUpdateValue callback with [null] as the value,not []

### ISSUE THREAD

**Issue by daselang** [tusen-ai/naive-ui#6249]
### Describe the bug

as the Title,
For Cascader ,:multiple"true",
select multi options and then discard all sections,
@update:value handleUpdateValue callback with [null] as first param value,not [],
I think when 0 options is selected, it should be [] empty array.

### Steps to reproduce

1.:multiple"true"
2.select multi options
3.discard all selections
4.watch the on-update:value event
5.retrieve [null]  but not the []

### Link to minimal reproduction

no link

### System Info

```Shell
System:
    OS: macOS 14.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 44.13 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.2.0 - /usr/local/bin/node
    Yarn: 4.1.1 - /usr/local/bin/yarn
    npm: 10.8.0 - /usr/local/bin/npm
    Watchman: 2024.05.06.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 127.0.6533.100
    Safari: 17.5
  npmPackages:
    naive-ui: ^2.38.1 => 2.38.1
    vue: ^3.2.41 => 3.4.21
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by OrbisK** [comment]
hey, please create a minimal reproduction so we can help. just a codesandbox or a github repo

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
