### ISSUE TITLE
cascader 级联选择, 多选后input框显示的tag内的文字没有居中

### ISSUE THREAD

**Issue by HongJian-Yang** [tusen-ai/naive-ui#6260]
### 描述错误

cascader 级联选择, 多选后input框显示的tag内的文字没有居中, 如果f12取消tag里面文字span标签的line-height, 则居中了, 是不是继承样式里面的有样式失效了

### 默认样式
![1](https://github.com/user-attachments/assets/3b754932-9855-4234-941a-b52291ad625f)

### 取消line-height
![2](https://github.com/user-attachments/assets/b1528d9e-3a7c-421a-afb1-54591f189d25)

### 复现步骤

打开官网例子, https://www.naiveui.com/zh-CN/os-theme/components/cascader
多选后即可复现

### 最小复现链接

https://www.naiveui.com/zh-CN/os-theme/components/cascader

### 系统信息

```Shell
naive-ui版本2.39.0
谷歌浏览器版本127.0.6533.100（正式版本） （64 位）
```

### 使用的包管理器

npm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by HongJian-Yang** [comment]
还有个关键点就是, 如果全屏浏览器, 文字就居中了,  如果浏览器不是全屏, 3/2屏幕, 文字就不会居中,  是不是什么媒体查询 或者 根据屏幕高度 计算文字高度没有处理好

**Comment by HongJian-Yang** [comment]
强迫症很难受

**Comment by jahnli** [comment]
No recurrence.

![image](https://github.com/user-attachments/assets/9c377669-846e-4631-9429-2b066595709e)

**Comment by HongJian-Yang** [comment]
> No recurrence.
> 
> ![image](https://private-user-images.githubusercontent.com/20943608/369948681-306b5bfd-5fae-4f2a-94d0-5c82b82c7c5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjk2MjgsIm5iZiI6MTcyNzE2OTMyOCwicGF0aCI6Ii8yMDk0MzYwOC8zNjk5NDg2ODEtMzA2YjViZmQtNWZhZS00ZjJhLTk0ZDAtNWM4MmI4MmM3YzVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA5MTUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3YjFjYjA4NzFiYWYwMjBiNTYzZWI0NjgyNGUyYjM4OTk3NDA1NTRhMGRmZWEzOTk2NDEwNDExN2RhOTVjZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BY7DjNScT-FYJC7MLdP8Z7pWihkA8IwT3bTRaK59aK8)

我现在也复现不了了, 难道是电脑问题
