### ISSUE TITLE
Update to `date-fns@3` and  `date-fns-tz@3`

### ISSUE THREAD

**Issue by BracketJohn** [tusen-ai/naive-ui#6265]
### Clear and concise description of the problem

naive-ui uses `date-fns@2` and `date-fns-tz@2`. This leads to:
- larger bundle size
- worse TS-support
- missing out on fixes & improvements as v2 development has stopped (last release >1 year ago)
- hacks required for correct usage (see below)

Example of one of the required hacks:
https://github.com/tusen-ai/naive-ui/blob/590ad1e6f3f19714d70a5ce73b258d5207ac4489/scripts/post-build/complete-path.js#L141-L145

In addition, the whole ecosystem is moving to v3, so projects using naive-ui will have package duplications when they install naive-ui and date-fns@3.

### Suggested solution

At the end of 2023 `date-fns@3` was released. It contains a lot of improvements as outlined [here](https://blog.date-fns.org/v3-is-out/):
<img width="605" alt="image" src="https://github.com/user-attachments/assets/5d95e86f-9759-4136-a240-e3050ed91ca8">

In addition `date-fns-tz@3` was released in April, with much better ESM/tree-shaking support & support for `date-fns@3`: https://github.com/marnusw/date-fns-tz/blob/master/CHANGELOG.md

The suggested solution is to update the dependencies to v3 and remove related hacks from the code-base. 

### Additional context

I created this issue as we encountered the duplicate-dependency warning and then dug into it. Thanks for building & maintaining naive-ui!

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Sepush** [comment]
actually we use v3 now
```json
 "date-fns": "^3.6.0",
 "date-fns-tz": "^3.1.3",
```
