### ISSUE TITLE
表格支持横向虚拟滚动   

### ISSUE THREAD

**Issue by maxfrees** [tusen-ai/naive-ui#6270]
### 问题的清晰而简明的描述

表格支持横向虚拟滚动

### 建议的解决方案

表格支持横向虚拟滚动

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by jahnli** [comment]
The author has completed the development and is expected to release the next version

![image](https://github.com/user-attachments/assets/e2183cd3-07df-43d2-a694-0556fbcd870b)
