### ISSUE TITLE
数据表格导出csv 不支持嵌套的数据

### ISSUE THREAD

**Issue by sleep1223** [tusen-ai/naive-ui#6279]
### 描述错误

![image](https://github.com/user-attachments/assets/e58b9364-dd8f-4faf-a35c-9ae602ad96a9)

数据能正常渲染, 但是导出csv时为空

### 复现步骤

无

### 最小复现链接

无

### 系统信息

```Shell
无
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jahnli** [comment]
表格不支持复杂的数据，可以自行处理
