### ISSUE TITLE
首先这个不确定是否是bug。使用h标签触发chrome自动翻译。

### ISSUE THREAD

**Issue by zstthm** [tusen-ai/naive-ui#6280]
### Describe the bug

然后写代码，h标签。
中文字 ：用户名（使用文字  用户名1，能够触发翻译成其他的。   但是如果输入 用户名123，则又不会翻译）
然后会被自动翻译成为 ： 项目

有点好奇具体是什么原因造成的？

设置html 头<html lang="zh-CN">，则不会被触发。

### Steps to reproduce

1. 首先vue首页的 <html lang="en">
2. Vue中使用使用<h1>用户名</h1>       (除了 h  其他标签不会被翻译)
3. 然后触发google自动翻译 然后自动替换成    项目  两个字

### Link to minimal reproduction

无

### System Info

```Shell
chrome
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Xdy1579883916** [comment]
1. 首先html上设置了lang属性后，谷歌翻译会按照指定语种翻译，你自动翻译的情况请检查是否开启一律翻译某某语言了
2. 如果你不希望网页被翻译请设置 translate="false" 到对应dom上，例如html标签
