### ISSUE TITLE
期待有一天能用 Slot 插槽替换所有 Render 函数

### ISSUE THREAD

**Issue by AAABingBing** [tusen-ai/naive-ui#6282]
### Clear and concise description of the problem

感觉好多场景都可以用 Slot 代替 Render 函数
期待有一天能用 Slot 插槽替换所有 Render 函数

### Suggested solution

/

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Zheng-Changfu** [comment]
目前来说，是没有那一天的，作者也说过了不用插槽的原因，也不会花精力做这件事

**Comment by wangz-code** [comment]
为什么我觉得 h 函数挺好用的 [脸红]

**Comment by jahnli** [comment]
https://github.com/tusen-ai/naive-ui/issues/216

`tsx`  一样的

![55dcc7a997e06e6d8b6624226edc100c](https://github.com/user-attachments/assets/3b67e6b9-36ae-4b01-ab71-f0e551dbcd80)
