### ISSUE TITLE
描述 Descriptions组件DescriptionItem Props，label-class不生效

### ISSUE THREAD

**Issue by mysllove** [tusen-ai/naive-ui#6290]
### Describe the bug

描述 Descriptions组件DescriptionItem Props，label-class不生效

### Steps to reproduce

https://www.naiveui.com/zh-CN/os-theme/components/descriptions#DescriptionItem-Props

### Link to minimal reproduction

https://www.naiveui.com/zh-CN/os-theme/components/descriptions#DescriptionItem-Props

### System Info

```Shell
mac
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
