### ISSUE TITLE
Steps步骤条组件最后一个步骤的宽度和前面的宽度是一样的还是有线的宽度

### ISSUE THREAD

**Issue by sfw5201314** [tusen-ai/naive-ui#6294]
### Describe the bug

Steps步骤条组件最后一个步骤的宽度和前面的宽度是一样的还是有线的宽度但是最后一步已经没有线了应该只有点的宽度就行

### Steps to reproduce

Steps步骤条组件最后一个步骤的宽度和前面的宽度是一样的还是有线的宽度但是最后一步已经没有线了应该只有点的宽度就行

### Link to minimal reproduction

Steps步骤条组件最后一个步骤的宽度和前面的宽度是一样的还是有线的宽度但是最后一步已经没有线了应该只有点的宽度就行

### System Info

```Shell
Steps步骤条组件最后一个步骤的宽度和前面的宽度是一样的还是有线的宽度但是最后一步已经没有线了应该只有点的宽度就行
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
Provide a based on CodeSandbox or stackblitz [Minimal, Reproducible Example] (https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
