### ISSUE TITLE
大部分可拖动组件在移动端失效

### ISSUE THREAD

**Issue by AAABingBing** [tusen-ai/naive-ui#6295]
### Describe the bug

大部分可鼠标拖动组件不支持移动端

- ColorPicker 颜色选择器色盘在移动端无法拖动选择
- Split 面板分割在移动端无法拖动

### Steps to reproduce

/

### Link to minimal reproduction

/

### System Info

```Shell
/
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
This is a `PC` library, currently may not be very good for mobile compatibility
