### ISSUE TITLE
createDiscreteApi创建Notification不支持placement配置

### ISSUE THREAD

**Issue by liaoyu1992** [tusen-ai/naive-ui#6297]
### Clear and concise description of the problem

createDiscreteApi 创建的notification 只能显示在右上角

### Suggested solution

createDiscreteApi create等时支持placement配置

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jizai1125** [comment]
```ts
const { ... } = createDiscreteApi(
  [...],
  {
     notificationProviderProps: { ... }
  }
)
```
