### ISSUE TITLE
文档错别字

### ISSUE THREAD

**Issue by AemonCao** [tusen-ai/naive-ui#6312]
### 描述错误

案例的标题有错别字

<https://www.naiveui.com/zh-CN/os-theme/components/input#graphemes.vue>

![image](https://github.com/user-attachments/assets/532bd3c5-f2e8-42ac-b2ba-73ddf8ac034b)

### 复现步骤

<https://www.naiveui.com/zh-CN/os-theme/components/input#graphemes.vue>

### 最小复现链接

https://www.naiveui.com/zh-CN/os-theme/components/input#graphemes.vue

### 系统信息

```Shell
/
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by z0ffy** [comment]
https://github.com/tusen-ai/naive-ui/issues/4438

**Comment by jahnli** [comment]
https://github.com/tusen-ai/naive-ui/issues/4438   不是错别字

**Comment by AemonCao** [comment]
学到了！
