### ISSUE TITLE
NInput 受 LastPass 影响，placeholder 向上漂移

### ISSUE THREAD

**Issue by lparam** [tusen-ai/naive-ui#6332]
### 描述错误

LastPass 图标插入输入框尾部，导致 placeholder 位置向上漂移

## 没有 LastPass 的情况
<img width="328" alt="2024-09-08_22-28" src="https://github.com/user-attachments/assets/da81a478-7865-4631-a177-13c94eceefcc">

## 开启 LastPass 的情况
<img width="348" alt="2024-09-08_22-28_1" src="https://github.com/user-attachments/assets/971f4b31-8040-49f5-83db-4fe87c09e237">

## 代码

```html
<script setup lang="ts">
import { NInput } from 'naive-ui'
</script>

<template>
  <n-input type="text" placeholder="用户名" />
  <n-input type="password" placeholder="密码" />
</template>
```

### 最小复现链接

https://www.naiveui.com/zh-CN/light/components/input

### 系统信息

```Shell
System:
    OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
    CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700K
    Memory: 9.66 GB / 31.08 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 20.15.0 - /usr/local/bin/node
    npm: 10.7.0 - /usr/local/bin/npm
    pnpm: 9.9.0 - ~/.npm-packages/bin/pnpm
  Browsers:
    Chrome: 128.0.6613.119
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by Zheng-Changfu** [comment]
> ### 描述错误
> LastPass 图标插入输入框尾部，导致 placeholder 位置向上漂移
> 
> ### 复现步骤
> ## 没有 LastPass 的情况
> <img alt="2024-09-08_22-28" width="328" src="https://private-user-images.githubusercontent.com/657233/365445587-da81a478-7865-4631-a177-13c94eceefcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NDkzOTksIm5iZiI6MTcyNTg0OTA5OSwicGF0aCI6Ii82NTcyMzMvMzY1NDQ1NTg3LWRhODFhNDc4LTc4NjUtNDYzMS1hMTc3LTEzYzk0ZWNlZWZjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQwMjMxMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTk1MTJmZmUwOWQ2Y2I0ZjBkNTdlODM2MTFlNjFmODRhZDI2Yzk1ZTYyYjZiOWM3MGNlMzE4MDRmZDM0NDNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.h_qt53MHzYBUKCbfzL_5n2tXTL_zFR0qCLKVYKdTYNQ">
> ## 开启 LastPass 的情况
> <img alt="2024-09-08_22-28_1" width="348" src="https://private-user-images.githubusercontent.com/657233/365445611-971f4b31-8040-49f5-83db-4fe87c09e237.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NDkzOTksIm5iZiI6MTcyNTg0OTA5OSwicGF0aCI6Ii82NTcyMzMvMzY1NDQ1NjExLTk3MWY0YjMxLTgwNDAtNDlmNS04M2RiLTRmZTg3YzA5ZTIzNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQwMjMxMzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDk4ODY5OTU1Y2YzZTk0NDRjNGM1MjE2Y2FhOTU1YzU5ZTI4NTQxNWNhZjEwMDQzNjQwMTM3Nzc1YTk2ZjVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Kjq-EVfX2Wo8iQoZIyaOww5FLuiTe813LmZkdU7LxXY">
> ## 代码
> ```
> <script setup lang="ts">
> import { NInput } from 'naive-ui'
> </script>
> 
> <template>
>   <n-input type="text" placeholder="用户名" />
>   <n-input type="password" placeholder="密码" />
> </template>
> ```
> 
> ### 最小复现链接
> https://www.naiveui.com/zh-CN/light/components/input
> 
> ### 系统信息
> ```shell
> System:
>     OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
>     CPU: (24) x64 13th Gen Intel(R) Core(TM) i7-13700K
>     Memory: 9.66 GB / 31.08 GB
>     Container: Yes
>     Shell: 5.9 - /usr/bin/zsh
>   Binaries:
>     Node: 20.15.0 - /usr/local/bin/node
>     npm: 10.7.0 - /usr/local/bin/npm
>     pnpm: 9.9.0 - ~/.npm-packages/bin/pnpm
>   Browsers:
>     Chrome: 128.0.6613.119
> ```
> 
> ### 使用的包管理器
> pnpm
> 
> ### 验证
> * [x]  阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
> * [x]  阅读 [文档](https://www.naiveui.com/zh-CN/)。
> * [x]  检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
> * [x]  确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
> * [x]  提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

请提供复现链接或代码示例

**Comment by jahnli** [comment]
提供的复现 [最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by lparam** [comment]
@Zheng-Changfu 

## Vue3 代码

```html
<script setup lang="ts">
import { NInput } from 'naive-ui'
</script>

<template>
  <n-input type="text" placeholder="用户名" />
  <n-input type="password" placeholder="密码" />
</template>
```

**Comment by Zheng-Changfu** [comment]
> @Zheng-Changfu
> 
> ## Vue3 代码
> ```
> <script setup lang="ts">
> import { NInput } from 'naive-ui'
> </script>
> 
> <template>
>   <n-input type="text" placeholder="用户名" />
>   <n-input type="password" placeholder="密码" />
> </template>
> ```

这也不是复现代码啊

**Comment by jahnli** [comment]
应该去 LastPass 反馈，为什么影响了原本组件的样式
