### ISSUE TITLE
动态渲染 Tabs 组件不生效

### ISSUE THREAD

**Issue by eivmosn** [tusen-ai/naive-ui#6334]
### Describe the bug

使用 component 动态渲染 tabs 组件不生效

### Steps to reproduce

可以直接查看最小复现 https://stackblitz.com/edit/vitejs-vite-roe9y8?file=src%2FApp.vue

### Link to minimal reproduction

https://stackblitz.com/edit/vitejs-vite-roe9y8?file=src%2FApp.vue

### System Info

```Shell
System:
    OS: macOS 14.3.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 486.56 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.local/state/fnm_multishells/78005_1725871713632/bin/node
    npm: 10.2.3 - ~/.local/state/fnm_multishells/78005_1725871713632/bin/npm
    pnpm: 9.9.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 128.0.6613.120
    Safari: 17.3.1
  npmPackages:
    naive-ui: ^2.39.0 => 2.39.0 
    vue: ^3.5.3 => 3.5.3
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Zheng-Changfu** [comment]
貌似设计时就是不能被二次封装，https://github.com/tusen-ai/naive-ui/blob/main/src/tabs/src/Tabs.tsx#L811

**Comment by eivmosn** [comment]
> 貌似设计时就是不能被二次封装，https://github.com/tusen-ai/naive-ui/blob/main/src/tabs/src/Tabs.tsx#L811

使用TSX封装或者h函数又可以了

**Comment by Zheng-Changfu** [comment]
> > 貌似设计时就是不能被二次封装，https://github.com/tusen-ai/naive-ui/blob/main/src/tabs/src/Tabs.tsx#L811
> 
> 使用TSX封装或者h函数又可以了

tsx 可以的，不会多一层组件

**Comment by eivmosn** [comment]
> > > 貌似设计时就是不能被二次封装，https://github.com/tusen-ai/naive-ui/blob/main/src/tabs/src/Tabs.tsx#L811
> > 
> > 
> > 使用TSX封装或者h函数又可以了
> 
> tsx 可以的，不会多一层组件

<script setup lang="ts">
defineOptions({
  name: 'Render',
})

defineProps<{
  widgets: any[]
}>()
</script>

<template>
  <template v-for="widget in widgets" :key="widget.id">
    <n-tabs v-if="widget.type === 'tabs'" v-bind="widget.props">
      <n-tab-pane v-for="pane in widget.children" v-bind="pane.props" :key="pane.id">
        <Render v-if="pane.children" :widgets="pane.children" />
      </n-tab-pane>
    </n-tabs>
    <component v-bind="widget.props" :is="`n-${widget.type}`" v-else>
      <Render v-if="widget.children" :widgets="widget.children" />
    </component>
  </template>
</template>

最终这样做搞定了
