### ISSUE TITLE
n-carousel轮播图，只有两张图片时，使用鼠标拖拽会出现错误的过渡效果

### ISSUE THREAD

**Issue by Garan902** [tusen-ai/naive-ui#6350]
### 描述错误

轮播图只有两张图片时，从左往右鼠标拖拽，会出现错误的过渡效果（体现为第二张图从右向左进入），如图所示
![PixPin_2024-09-12_17-18-47](https://github.com/user-attachments/assets/35c3b790-f1de-4137-ab7e-dd7bdf7b5597)

### 复现步骤

无

### 最小复现链接

https://codesandbox.io/p/sandbox/young-haze-4v5gs7?workspaceId=b3423207-520b-449a-b14a-0868937f6371

### 系统信息

```Shell
没装envinfo
```

### 使用的包管理器

npm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jahnli** [comment]
Sandbox not found


This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
