### ISSUE TITLE
是否可以给n-image组件的下载功能增加一个自定义下载的方法

### ISSUE THREAD

**Issue by hanjialin** [tusen-ai/naive-ui#6351]
### 问题的清晰而简明的描述

目前默认的下载有时候图片会作为一个链接直接展示在浏览器页签里面，无法进行下载。

### 建议的解决方案

我是个菜鸟，没什么好的建议。

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by Zheng-Changfu** [comment]
可以自定义工具栏：https://www.naiveui.com/zh-CN/os-theme/components/image#custom-toolbar.vue
