### ISSUE TITLE
【数字输入 Input Number】输入部分负数可能存在符号被取消的现象

### ISSUE THREAD

**Issue by BelieveSongxh** [tusen-ai/naive-ui#6357]
### Describe the bug

数字输入 Input Number 在输入-1<num<0范围内的数字时候，会出现输入负号后再输入0，0直接替换掉符号，例如-0.001。只能在输入0.001后，再返回第一位添加负号

### Steps to reproduce

数字输入组件：<n-input-number  />
输入-号，再次输入0，0会替换掉-号，再次输入后续 .1
输入结果 0.1 ，并非-0.1

### Link to minimal reproduction

暂无

### System Info

```Shell
暂无
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
https://github.com/tusen-ai/naive-ui/pull/6281
