### ISSUE TITLE
n-form中使用n-button的block，宽度会超出容器

### ISSUE THREAD

**Issue by seepine** [tusen-ai/naive-ui#6363]
### 描述错误

n-form中使用n-button的block，宽度会超出容器
![image](https://github.com/user-attachments/assets/fa68d246-82f9-4c26-8463-ff4f4d96a2a1)

### 复现步骤

如复现demo

### 最小复现链接

https://stackblitz.com/edit/vitejs-vite-ub74gm?file=src%2FApp.vue

### 系统信息

```Shell
"vue": "^3.5.6",
"naive-ui": "^2.39.0"
```

### 使用的包管理器

npm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jahnli** [comment]
This is `block` props `s code
```
    display: flex;
    width: 100%;
```

You should give the second button `flex:1`
