### ISSUE TITLE
Dialog组件内容区使用h函数渲染一个外部导入的组件时，无法识别TailwindCSS的样式，需要使用 行内样式才可以

### ISSUE THREAD

**Issue by ZRMYDYCG** [tusen-ai/naive-ui#6366]
### Describe the bug

Dialog组件内容区使用h函数渲染一个外部导入的组件时，无法识别TailwindCSS的样式，需要使用 行内样式才可以

### Steps to reproduce

Dialog组件内容区使用h函数渲染一个外部导入的组件时，无法识别TailwindCSS的样式，需要使用 行内样式才可以

### Link to minimal reproduction

Dialog组件内容区使用h函数渲染一个外部导入的组件时，无法识别TailwindCSS的样式，需要使用 行内样式才可以

### System Info

```Shell
Dialog组件内容区使用h函数渲染一个外部导入的组件时，无法识别TailwindCSS的样式，需要使用 行内样式才可以
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
提供的复现 [最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
