### ISSUE TITLE
表格内使用ellipsis设置tooltip的时候要把tooltip的深色改成浅色没有快捷入口

### ISSUE THREAD

**Issue by Lastcall9** [tusen-ai/naive-ui#6367]
### 问题的清晰而简明的描述

表格内使用ellipsis设置tooltip的时候要把tooltip的深色改成浅色没有快捷入口 需要很麻烦手动设置contentStyle等去修改 或者写render或者h函数自己实现文本省略+tooltip展示

### 建议的解决方案

给一个入口类似dark：false这种

### 附加上下文

  {
    key: '',
    title: '',
    minWidth: 200,
    ellipsis: {
      lineClamp: 2,
      tooltip: {
        contentStyle: { maxWidth: '600px' },
        render: (row) => row.userComment,
      },
    },
  },

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by jahnli** [comment]
`n-config-provider`       `theme-overrides`

```
    Tooltip: { color: '#FFFFFF', textColor: '#333639' },
```
