### ISSUE TITLE
form 动态表单验证bug

### ISSUE THREAD

**Issue by zw-gone** [tusen-ai/naive-ui#6368]
### Describe the bug

动态表单验证bug

### Steps to reproduce

复现步骤：
1、点击增加
2、在爱好2中填入文字
3、点击验证
4、删除爱好1
此时爱好2验证状态变error

### Link to minimal reproduction

https://www.naiveui.com/zh-CN/os-theme/components/form#dynamic.vue

### System Info

```Shell
chrome
```

### Used Package Manager

npm

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
提供的复现 [最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by zouhgithub** [comment]
v-for  key为索引的问题  你自己使用的时候不用索引当作key不就好了吗

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
