### ISSUE TITLE
使用defineAsyncComponent按需加载，子组件无法渲染问题

### ISSUE THREAD

**Issue by repertory** [tusen-ai/naive-ui#6371]
### Describe the bug

```vue
<script>
import { defineAsyncComponent } from 'vue'
export default {
  components: {
    NTabs: defineAsyncComponent(() => import('naive-ui/es/tabs/src/Tabs.mjs')),
    NTabPane: defineAsyncComponent(() => import('naive-ui/es/tabs/src/TabPane.mjs'))
  }
};
</script>

<template>
  <n-tabs type="line" animated>
    <n-tab-pane name="oasis" tab="Oasis"> Wonderwall </n-tab-pane>
    <n-tab-pane name="the beatles" tab="the Beatles"> Hey Jude </n-tab-pane>
    <n-tab-pane name="jay chou" tab="周杰伦"> 七里香 </n-tab-pane>
  </n-tabs>
</template>
```

以上代码希望能够适配

### Steps to reproduce

按照以上方式，n-tab-pane内容不会被渲染

如果将以上组件添加到main.js中作为全局组件引入
```vue
app.component('NTabs', defineAsyncComponent(() => import('naive-ui/es/tabs/src/Tabs.mjs')))
app.component('NTabPane', defineAsyncComponent(() => import('naive-ui/es/tabs/src/TabPane.mjs')))
```
然后将代码修改为
```vue
import { NTabs, NTabPane } from 'naive-ui'
export default {
  components: { NTabs, NTabPane }
};
</script>

<template>
  <n-tabs type="line" animated>
    <n-tab-pane name="oasis" tab="Oasis"> Wonderwall </n-tab-pane>
    <n-tab-pane name="the beatles" tab="the Beatles"> Hey Jude </n-tab-pane>
    <n-tab-pane name="jay chou" tab="周杰伦"> 七里香 </n-tab-pane>
  </n-tabs>
</template>
```
则页面会报错

### Link to minimal reproduction

#

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (20) x64 13th Gen Intel(R) Core(TM) i7-13700H
    Memory: 12.01 GB / 15.46 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 22.8.0 - ~/.nvm/versions/node/v22.8.0/bin/node
    npm: 10.8.2 - ~/.nvm/versions/node/v22.8.0/bin/npm
  npmPackages:
    naive-ui: ^2.39.0 => 2.39.0 
    vue: ^3.5.5 => 3.5.8
```

### Used Package Manager

npm

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
提供的复现 [最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
