### ISSUE TITLE
Upload: Custom slot for text file list

### ISSUE THREAD

**Issue by howdymatt** [tusen-ai/naive-ui#6388]
### Clear and concise description of the problem

For Directory drag and drop, I need to show the `fullPath` and a "This will be uploaded to: XXX" where XXX is calculated by a function. 

### Suggested solution

Provide a FileListItem template with slots for icon, file information, and actions. 

### Alternative

Disabling file list view and writing one myself.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jahnli** [comment]
![image](https://github.com/user-attachments/assets/9180d4bc-879f-4396-8ebc-c4643b058ed1)
指的是这些图标和文字描述 ？

**Comment by jahnli** [comment]
![image](https://github.com/user-attachments/assets/d509966c-941d-4dd7-9e60-1ec604228759)
