### ISSUE TITLE
文档页面的卡顿

### ISSUE THREAD

**Issue by Tie-Tie** [tusen-ai/naive-ui#6392]
### Clear and concise description of the problem

对比elementui的时候肉眼可见的感觉出button页面的卡顿以及其它页面的一些卡顿，希望能够进行优化，逐渐很好，很想用，但是感觉卡卡的

### Suggested solution

对比elementui的时候肉眼可见的感觉出button页面的卡顿以及其它页面的一些卡顿，希望能够进行优化，逐渐很好，很想用，但是感觉卡卡的

### Alternative

对比elementui的时候肉眼可见的感觉出button页面的卡顿以及其它页面的一些卡顿，希望能够进行优化，逐渐很好，很想用，但是感觉卡卡的

### Additional context

对比elementui的时候肉眼可见的感觉出button页面的卡顿以及其它页面的一些卡顿，希望能够进行优化，逐渐很好，很想用，但是感觉卡卡的

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Zheng-Changfu** [comment]
button 文档卡？能说的清楚一点么

**Comment by pinecone-squirrel** [comment]
date-picker那个文档页面打开面板掉帧

**Comment by pinecone-squirrel** [comment]
可能是chrome 129版本的原因
edge打开没问题不掉帧

**Comment by jahnli** [comment]
目前猜测是 chrome 129 版本导致的，有问题再提 issue
