### ISSUE TITLE
我想要给数据表格n-data-table加一个选择单行数据时使用色块表示

### ISSUE THREAD

**Issue by jiangzik** [tusen-ai/naive-ui#6402]
### 问题的清晰而简明的描述

![image](https://github.com/user-attachments/assets/aeaa538f-4bb0-431c-8dcd-e6c0cfcb988e)

### 建议的解决方案

类似于element-plus那样，应该是单击的时候，清除其他行的css，给那一行加上css。不想引入type='selection'，不美观

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by jahnli** [comment]
`row-props`

**Comment by jiangzik** [comment]
我有尝试过，但是没有效果。可以麻烦给个示例吗

const rowProps = (row) => {
  return {
    style: {
      backgroundColor: selectedRow.value === row ? 'rgba(250, 250, 252, 1)' : 'transparent',
    },
    onClick: () => {
      selectedRow.value = row; // 更新选中行
    },
  };
};

**Comment by jahnli** [comment]
https://codesandbox.io/p/sandbox/spring-hooks-gw9pl4?file=%2Fsrc%2FDemo.vue%3A1%2C1-75%2C1
大概这样，配合  `row-props`
