### ISSUE TITLE
Form doesn't validating date picker

### ISSUE THREAD

**Issue by iqbaltawakkal** [tusen-ai/naive-ui#6406]
### Describe the bug

Hi guys, I'm not sure if this issue duplicate or not.
as title says, if youre using datepicker in the formItem it will get ignored if it has rules

### Steps to reproduce

1. create minimal form component
2. use datepicker inside formitem
3. set `required` rules for datepicker
4. set `path` , `value` etc
5. validate
6. datepicker will shown error even if its not `null`

### Link to minimal reproduction

https://codesandbox.io/p/sandbox/stoic-cache-52lhts?file=%2Fsrc%2FDemo.vue%3A16%2C1

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (12) x64 Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
    Memory: 6.64 GB / 15.87 GB
  Binaries:
    Node: 18.13.0 - C:\Program Files\nodejs\node.EXE       
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD       
    npm: 9.7.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    naive-ui: ^2.39.0 => 2.39.0
    vue: ^3.4.37 => 3.4.38
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
`trigger: ['blur', 'change']`

**Comment by iqbaltawakkal** [comment]
@jahnli hi, I update the minimal repro. it stills ignore datepicker, maybe i missed something, im not sure. 
![image](https://github.com/user-attachments/assets/eb5e62a8-b7ce-4bd2-a041-bc1e59838edb)

**Comment by jahnli** [comment]
```
date: {
          type: "number",
          required: true,
          message: "Please input your date",
          trigger: ["blur", "change"],
        },
```

**Comment by jahnli** [comment]
https://www.naiveui.com/zh-CN/os-theme/components/form#left.vue  对照官网例子

**Comment by iqbaltawakkal** [comment]
Ahhh I missed the type, thanks a lot!
