### ISSUE TITLE
n-scrollbar和n-modal 的问题

### ISSUE THREAD

**Issue by yang867381349** [tusen-ai/naive-ui#6414]
### 描述错误

场景：我要做一个可以拖动的窗口，现在拖动窗口内需要滚动条来解决展示不下的问题。为什么要用到n-modal，是因为打开前需要接口校验是否已经初始化好。现在n-scrollbar  的windth:fit-content影响了展示效果。导致左右展示区域出现右侧超出去了。

### 复现步骤

拉取至本地后，yarn install  安装，即可查看复现问题。

### 最小复现链接

https://github.com/yang867381349/Naive-UI-part

### 系统信息

```Shell
Darwin Flex-yangdeMBP 24.0.0 Darwin Kernel Version 24.0.0: Mon Aug 12 20:54:30 PDT 2024; root:xnu-11215.1.10~2/RELEASE_X86_64 x86_64
├─┬ @vitejs/plugin-vue-jsx@4.0.1
│ └── vue@3.5.10 deduped
├─┬ @vitejs/plugin-vue@5.1.4
│ └── vue@3.5.10 deduped
├─┬ naive-ui@2.40.1
│ ├─┬ @css-render/vue3-ssr@0.15.14
│ │ └── vue@3.5.10 deduped
│ ├─┬ vdirs@0.1.8
│ │ └── vue@3.5.10 deduped
│ ├─┬ vooks@0.2.12
│ │ └── vue@3.5.10 deduped
│ ├── vue@3.5.10 deduped
│ └─┬ vueuc@0.4.64
│   └── vue@3.5.10 deduped
├─┬ pinia@2.2.2
│ ├─┬ vue-demi@0.14.10
│ │ └── vue@3.5.10 deduped
│ └── vue@3.5.10 deduped
├─┬ unplugin-vue-components@0.27.4
│ └── vue@3.5.10 deduped
├─┬ vite-plugin-vue-devtools@7.4.6
│ └─┬ @vue/devtools-core@7.4.6
│   └── vue@3.5.10 deduped
├─┬ vue-router@4.4.5
│ └── vue@3.5.10 deduped
└─┬ vue@3.5.10
  └─┬ @vue/server-renderer@3.5.10
    └── vue@3.5.10 deduped
```

### 使用的包管理器

yarn

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jahnli** [comment]
提供在线的复现 [最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by yang867381349** [comment]
这已经是最小的是复现了。再小就不显示问题。我是把我项目中的东西提取出来到对应的里面

**Comment by jahnli** [comment]
> 这已经是最小的是复现了。再小就不显示问题。我是把我项目中的东西提取出来到对应的里面

提供 `codesandbox` 在线复现

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
