### ISSUE TITLE
importing component changes font on all views 

### ISSUE THREAD

**Issue by MariuzM** [tusen-ai/naive-ui#6417]
### Describe the bug

why importing button component fonts all being changed? 
also why doing refresh your lib does not respect my fonts and forces to use its? 

### Steps to reproduce

Start the app 

### Link to minimal reproduction

https://github.com/tusen-ai/naive-ui

### System Info

```Shell
System:
    OS: macOS 14.6.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 24.27 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.17.0 - ~/dev/node-v20.17.0/bin/node
    npm: 10.8.2 - ~/dev/node-v20.17.0/bin/npm
    bun: 1.1.29 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 129.1.70.119
    Chrome: 126.0.6478.127
    Safari: 17.6
  npmPackages:
    naive-ui: ^2.40.1 => 2.40.1 
    vue: ^3.5.10 => 3.5.10 

bun is also package manager
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
This seems to have nothing to do with naive, Provide online reproducible links

**Comment by MariuzM** [comment]
Im trying to reproduce this but now getting issues with import i want to manually import how this is being done? 
https://github.com/MariuzM/test__nuxt/tree/test-naive-ui
app/pages/index.vue

**Comment by MariuzM** [comment]
Why did you close this and not give me time to make repo?

**Comment by MariuzM** [comment]
following the docs 

<img width="1220" alt="image" src="https://github.com/user-attachments/assets/035df47d-996f-41c8-81aa-9f1e09b0c19b">

**Comment by jahnli** [comment]
![image](https://github.com/user-attachments/assets/c1b7ef31-bbfc-4355-afdb-cf3d5a5bd4bd)

https://github.com/07akioni/naive-ui-nuxt-demo

I installed the naive ui & nuxt naive ui dependency and it is normal, refer to the demo above

**Comment by MariuzM** [comment]
perfect thank you, i did know another lib is needed thought nuxt module lib had it 

but i want to go back to original issue where font changes when i use button
<img width="855" alt="image" src="https://github.com/user-attachments/assets/f2ce4f6c-7f54-4ce6-a4a0-192fab39f396">


without button font goes back to normal size 
<img width="929" alt="image" src="https://github.com/user-attachments/assets/cb02adc4-c3b3-4aec-96ab-0a22acb53ab1">

**Comment by moliyu** [comment]
@MariuzM 
![image](https://github.com/user-attachments/assets/127d4caf-d96b-47d1-a81b-b5fe84b46fd7)
because it will inject nglobal style to the head. you can custom your style.css and use it with  nuxt.config.ts > css: ['custom.css']
