### ISSUE TITLE
在 <script setup lang="ts"> 使用useMessage() 报错

### ISSUE THREAD

**Issue by lizhan12** [tusen-ai/naive-ui#6442]
### 描述错误

naive-ui.js?v=2512b343:957 Uncaught Error: [naive/use-message]: No outer <n-message-provider /> founded. See prerequisite in https://www.naiveui.com/en-US/os-theme/components/message for more details. If you want to use `useMessage` outside setup, please check https://www.naiveui.com/zh-CN/os-theme/components/message#Q-&-A.
    at throwError (naive-ui.js?v=2512b343:957:9)
    at useMessage (naive-ui.js?v=2512b343:109061:5)
    at setup (App.vue:5:17)
    at callWithErrorHandling (chunk-PP2TJUEO.js?v=2512b343:2334:19)
    at setupStatefulComponent (chunk-PP2TJUEO.js?v=2512b343:9989:25)
    at setupComponent (chunk-PP2TJUEO.js?v=2512b343:9950:36)
    at mountComponent (chunk-PP2TJUEO.js?v=2512b343:7311:7)
    at processComponent (chunk-PP2TJUEO.js?v=2512b343:7277:9)
    at patch (chunk-PP2TJUEO.js?v=2512b343:6793:11)
    at render2 (chunk-PP2TJUEO.js?v=2512b343:8074:7)

### 复现步骤

把下面GitHub的demo，下载到本地，进行运行就会看到这个错误
![image](https://github.com/user-attachments/assets/20b75883-1b78-4c9d-acca-893ef07f4fcc)

### 最小复现链接

https://github.com/lizhan12/naive-test

### 系统信息

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12400F
    Memory: 4.38 GB / 15.84 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    naive-ui: ^2.38.2 => 2.39.0 
    vue: ^3.4.15 => 3.4.34
```

### 使用的包管理器

npm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jahnli** [comment]
![image](https://github.com/user-attachments/assets/660af6cb-c256-4d2e-9415-2f523b0bd27f)

**Comment by lizhan12** [comment]
希望在官方文档中，给出 语法糖 setup 使用的方法

**Comment by jahnli** [comment]
![image](https://github.com/user-attachments/assets/8e617085-d243-4af0-abb7-bca13be4a234)
其实在这边有个小 demo
