### ISSUE TITLE
naive-ui UMD版本,在Microsoft Edge浏览器中运行报错

### ISSUE THREAD

**Issue by che-my** [tusen-ai/naive-ui#6444]
### 描述错误

**Uncaught SyntaxError: Unexpected token '{'
Uncaught ReferenceError: naive is not defined**
![0e7f1c61-a2c8-4c1c-9549-ab93c4f6d0fb](https://github.com/user-attachments/assets/185fa506-5f81-4458-86b3-2ba11ef5ed52)

### 复现步骤

使用官网UMD的例子,在Microsoft Edge （版本92.0.902.67）浏览器中运行即可

### 最小复现链接

https://www.naiveui.com/zh-CN/light/docs/umd

### 系统信息

```Shell
window10系统, Microsoft Edge （版本92.0.902.67）
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jahnli** [comment]
换个高版本试试

**Comment by che-my** [comment]
好的, 试了更新浏览器就行了
