### ISSUE TITLE
请在ntree里添加缩进控制，比如让父和子之间没有缩进

### ISSUE THREAD

**Issue by future-mike** [tusen-ai/naive-ui#6466]
### Clear and concise description of the problem

原文链接：https://www.naiveui.com/zh-CN/os-theme/components/tree
在tree中，没有控制节点的缩进
很多情况下我们可能需要这种格式，让结构更紧密，腾出更多的空间
父节点
子节点1
子节点2
子节点3

### Suggested solution

增加缩进参数

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jahnli** [comment]
`n-tree` has an `indent` props that will be added later in the document.
