### ISSUE TITLE
IOS12 Safari 浏览器不兼容

### ISSUE THREAD

**Issue by SK2888** [tusen-ai/naive-ui#6468]
### 描述错误

目前测试IOS12版本 Safari 浏览器不兼容，IOS15以上是正常，其它版本未知。官网https://www.naiveui.com也无法正常兼容打开。

### 复现步骤

1.IOS12版本 Safari 浏览器访问官网https://www.naiveui.com无法正常打开。
2.使用 UMD引入同样出现无法兼容。

### 最小复现链接

http://zb.crpa-gd.com

### 系统信息

```Shell
IOS12
```

### 使用的包管理器

npm

### 验证

- [x] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jahnli** [comment]
NaiveUI More for PC
