### ISSUE TITLE
textarea 可以给他加一个圆角吗

### ISSUE THREAD

**Issue by jiangzik** [tusen-ai/naive-ui#6478]
### 问题的清晰而简明的描述

现在普通的input有圆角了，但是他无法使用自动的高度autusize，只有textarea可以使用autusize

### 建议的解决方案

我还不知道该怎么实现，类似于ai聊天的那种输入框

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by jahnli** [comment]
Textarea should also have rounded corners

**Comment by jiangzik** [comment]
不，并没有
![image](https://github.com/user-attachments/assets/9ac85780-7b8e-4949-af6c-b02301be1982)
![image](https://github.com/user-attachments/assets/f1b53d00-2c94-4bcb-83f9-90774c4f34cc)

**Comment by jahnli** [comment]
by theme or `n-config-provider`
