### ISSUE TITLE
分页的建议

### ISSUE THREAD

**Issue by 002269** [tusen-ai/naive-ui#648]
### This function solves the problem (这个功能解决的问题)
分页的建议
### Expected API (期望的 API)
1. 希望上一页下一页的内容可以自定义，而不仅仅是箭头
2. 希望中间的一堆分页数字也有一个整体的开关，关闭的话，只显示上一页和下一页
https://codesandbox.io/s/52zxc?file=/src/Demo.vue
https://52zxc.csb.app/
3. 希望上一页、下一页有 显示/不显示 的开关
4. 希望跳转到 N 页的 input 后面可以有一个确定按钮的可选项，而不仅仅是回车跳转
https://codesandbox.io/s/intelligent-merkle-0o6kw?file=/src/Demo.vue
https://0o6kw.csb.app/
5. 希望 show-quick-jumper 和 show-size-picker 和 分页部分 都支持前后缀插槽，而不仅仅是整体的分页
6. 希望分页支持尺寸，和按钮一样

概述：
1. 上一页下一页，中间的数字部分，页码选择，快速跳转，是四个独立的部分，应该分别支持显示/不显示，前后缀
2. 快速跳转应该增加一个可选的“确定”按钮
3. 分页支持尺寸调整，和按钮一样

**Comment by HarperGG** [comment]
@07akioni 上面这些api都需要支持吗 :monocle_face:

**Comment by 07akioni** [comment]
> @07akioni 上面这些api都需要支持吗 🧐

这个相关的我来搞吧，看起来有点复杂

**Comment by HarperGG** [comment]
好滴

**Comment by 07akioni** [comment]
目前看来多数都有了，如果具体哪个还缺少的话可以再提 issue
