### ISSUE TITLE
form表单禁用时, 表单中项目可以设置不禁用

### ISSUE THREAD

**Issue by konglingbase** [tusen-ai/naive-ui#6486]
### 问题的清晰而简明的描述

当 form 表设置:disabled="true"时  可否单独设置表单中某一个表单不禁用

### 建议的解决方案

<n-form
      :disabled="true"
    >
      <n-form-item :disabled="false" label="Input" path="inputValue">
        <n-input v-model:value="model.inputValue" placeholder="Input" />
      </n-form-item>

</n-form
当 form item 设置为不禁用时 表单中次项可以编辑

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by thikiiii** [comment]
给form item下的组件设置disabled
