### ISSUE TITLE
如何部署静态文档？

### ISSUE THREAD

**Issue by anihCevol** [tusen-ai/naive-ui#6492]
### 问题的清晰而简明的描述

有内网开发需求，想构建一个静态文档导入内网使用 请问该如何操作 ？或是否可以提供一个类似 element-plus gh-pages分支 可以直接访问文档

### 建议的解决方案

有内网开发需求，想构建一个静态文档导入内网使用 请问该如何操作 ？或是否可以提供一个类似 element-plus gh-pages分支 可以直接访问文档

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by simonliang20** [comment]
```
1. 下载代码
2. pnpm i
3. pnpm build:site
4. 就会生成 site目录，部署到内网即可
```
<img width="279" alt="image" src="https://github.com/user-attachments/assets/9fc173bc-b980-42d1-bebb-6d2cc962ac53">

**Comment by anihCevol** [comment]
pnpm build:site 说缺少 naive-ui，一直报错，还没找到原因，我再试试吧

**Comment by hp100277** [comment]
解决了吗，最新的main分支还有这个问题

**Comment by anihCevol** [comment]
没 已放弃
