### ISSUE TITLE
关于vue安装sass和naive-ui后，控制条部分报错，但是sass1.79以上版本开始弃用了，请看文档就直接代码替换

### ISSUE THREAD

**Issue by Verdant-Grassland** [tusen-ai/naive-ui#6496]
### 描述错误

运行控制台有报错，警告提示弃用了，请需要替换

### 复现步骤

sass官方文档这里 https://github.com/sass/dart-sass/blob/main/CHANGELOG.md#1790

### 最小复现链接

https://github.com/sass/dart-sass/blob/main/CHANGELOG.md#1790

### 系统信息

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
    Memory: 3.34 GB / 19.75 GB
  Binaries:
    Node: 22.9.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - ~\AppData\Local\pnpm\yarn.CMD
    npm: 10.8.3 - D:\Program Files\nodejs\npm.CMD
    pnpm: 9.12.2 - ~\AppData\Local\pnpm\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    naive-ui: ^2.40.1 => 2.40.1
    vue: ^3.4.30 => 3.5.12
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jahnli** [comment]
Seems unrelated to naive

**Comment by Verdant-Grassland** [comment]
您好，我运行这样报错了

**Comment by Verdant-Grassland** [comment]
哦哦，麻烦你naive-ui尽快新增sass吧
很多人都在用sass

**Comment by jahnli** [comment]
By the way, naive-ui no less, sass, css variables, no webpack loaders, you should go to the sass repository for help
