### ISSUE TITLE
使用createDiscreteApi创建全局消息后, 会产生2个app

### ISSUE THREAD

**Issue by cooting-cn** [tusen-ai/naive-ui#6497]
### Describe the bug

使用createDiscreteApi 后 查看到有多个app生成

### Steps to reproduce

![image](https://github.com/user-attachments/assets/2df56656-a60b-40bd-877f-9e9ac14d4e63)
应该可以合成一个

### Link to minimal reproduction

https://gitee.com/cooting/arlog

### System Info

```Shell
"naive-ui": "^2.39.0"
"vue": "^3.5.8",
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
Provide a based on [CodeSandbox](https://codesandbox.io/templates/vue-vite) or [stackblitz](https://stackblitz.com/edit/vitejs-vite) `s [Minimal  Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) 

This seems unrelated to naive-ui, if confirmed there is a problem reopen
