### ISSUE TITLE
InfiniteScroll 无限滚动组件能否加入触顶加载

### ISSUE THREAD

**Issue by uiYzzi** [tusen-ai/naive-ui#6498]
### 问题的清晰而简明的描述

现在 InfiniteScroll 组件默认是触底加载，在用来做聊天界面时不太方便

### 建议的解决方案

加入一个新的属性，用来切换触顶加载或触底加载，当处于触底加载时滚动条开始位置默认为 0，触顶加载默认为 100%

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by jahnli** [comment]
https://github.com/tusen-ai/naive-ui/pull/6333  ？

**Comment by uiYzzi** [comment]
> https://github.com/tusen-ai/naive-ui/pull/6333   this ？

yep，sorry for the duplicate issue，thank you for your contribution

**Comment by jahnli** [comment]
Then I'll close it and wait for merge & release
