### ISSUE TITLE
轮播图设置属性为slides-per-view="auto"时表现异常

### ISSUE THREAD

**Issue by QuarkPixel** [tusen-ai/naive-ui#6500]
### 描述错误

轮播图设置slides-per-view="auto"属性时，会报错：
```
Uncaught TypeError: slideSizesRef.effect.run is not a function
    at handleSlideResize (naive-ui.js?v=1392700f:71801:30)
    at handleResize (naive-ui.js?v=1392700f:4446:9)
    at ResizeObserverDelegate.handleResize (naive-ui.js?v=1392700f:4416:9)
```

并且对应的逻辑也会出现问题：最后一页的内容是无法正常加载的：
![CleanShot 2024-10-29 at 14 47 02](https://github.com/user-attachments/assets/3e5ae2c7-7717-4111-8d15-efc34fadfb43)
![CleanShot 2024-10-29 at 14 46 15](https://github.com/user-attachments/assets/02e5a7c5-3fb8-4f06-8361-1ecea7904ece)

### 复现步骤

1. 滑动至轮播图的最后一页

### 最小复现链接

https://github.com/QuarkPixel/naive-ui-bug-minimal-reproduction

### 系统信息

```Shell
System:
    OS: macOS 15.0.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
    Memory: 38.27 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - /usr/local/bin/node
    npm: 10.2.4 - /usr/local/bin/npm
    pnpm: 9.12.2 - ~/Library/pnpm/pnpm
  Browsers:
    Safari: 18.0.1
  npmPackages:
    naive-ui: ^2.40.1 => 2.40.1 
    vue: ^3.5.12 => 3.5.12
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jahnli** [comment]
Provide a based on [CodeSandbox](https://codesandbox.io/templates/vue-vite) or [stackblitz](https://stackblitz.com/edit/vitejs-vite) `s [Minimal  Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by QuarkPixel** [comment]
[Minimal Reproducible Example](https://stackblitz.com/~/github.com/QuarkPixel/naive-ui-bug-minimal-reproduction)

**Comment by jahnli** [comment]
https://github.com/tusen-ai/naive-ui/pull/6438
