### ISSUE TITLE
Form Validation Report Error Uncaught (in promise) version-^2.38.2

### ISSUE THREAD

**Issue by lyublueberry** [tusen-ai/naive-ui#6502]
### Describe the bug

if the fields are empty and the form and table are validated, an error occurs when the button is clicked , error Uncaught (in promise) naive-ui.js?v=da9e97c2:60606

### Steps to reproduce

1.Do not fill in the table and fields 2. Click button 
the handler contains the following code: 
from.value?.validate((errors) => if (errors) message.error('');
return;
an error occurs at this stage

### Link to minimal reproduction

from.value?.validate((errors) => if (errors) message.error(''); return;

### System Info

```Shell
Windows 10, Google Chrome v 126.0.6478.127
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
Provide a based on [CodeSandbox](https://codesandbox.io/templates/vue-vite) or [stackblitz](https://stackblitz.com/edit/vitejs-vite) `s [Minimal  Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by lyublueberry** [comment]
> Предоставьте [минимальный воспроизводимый пример](https://stackoverflow.com/help/minimal-reproducible-example) на основе [CodeSandbox](https://codesandbox.io/templates/vue-vite) или [stackblitz](https://stackblitz.com/edit/vitejs-vite)[](https://stackoverflow.com/help/minimal-reproducible-example)

https://codesandbox.io/p/sandbox/2zj98t the error in the console is similar to the error in my project

**Comment by lyublueberry** [comment]
> Provide a based on [CodeSandbox](https://codesandbox.io/templates/vue-vite) or [stackblitz](https://stackblitz.com/edit/vitejs-vite) `s [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)

https://www.naiveui.com/en-US/os-theme/components/form

**Comment by zhangwh754** [comment]
> > Предоставьте [минимальный воспроизводимый пример](https://stackoverflow.com/help/minimal-reproducible-example) на основе [CodeSandbox](https://codesandbox.io/templates/vue-vite) или [stackblitz](https://stackblitz.com/edit/vitejs-vite)
> 
> https://codesandbox.io/p/sandbox/2zj98t the error in the console is similar to the error in my project

add catch after validate function can provisionally fix warn.

``` js
  formRef.value
    ?.validate(errors => {
      if (!errors) {
        // ...
      } 
    })
    .catch(err => err)
```

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by woodhull** [comment]
I am also having this issue. The issue happens with the code examples in the docs.
