### ISSUE TITLE
`<NDataTable />` Cell Border - 表格单元格边框

### ISSUE THREAD

**Issue by 002269** [tusen-ai/naive-ui#651]
### This function solves the problem (这个功能解决的问题)
datatable 的建议
### Expected API (期望的 API)
1. 希望增加序号列，如例子中的第二列
2. 希望任何一列可以单独的添加左边框或右边框，如例子中的第二列右边的边框
3. 希望通过点击其它区域，达到选中行的目的，而不必每次都要瞄准了复选框点击才能选中，可大大提高使用者的工作效率，如例子中通过点击序号列实现选中
4. 希望 @update:checked-row-keys 同时反馈当前变化的行的 key，同时标识该行是选中还是取消选中
https://codesandbox.io/s/quiet-dream-qmsi7?file=/src/Demo.vue
https://qmsi7.csb.app/

**Comment by 002269** [comment]
方便的增加序号列，和 selection 一样
      {
        type: "selection",
      },

**Comment by 07akioni** [comment]
关于第三点可以用 rowProps，这个监听 click 与否组件库没法决定，因为冲突太多了

**Comment by xcore-oss** [comment]
行点击选中不用组件实现也许，但是可不可以丢个行点击事件出来

**Comment by Rucling** [comment]
前端页面勾选了，怎么用代码取消掉？？？

**Comment by equt** [comment]
1. 使用 `render`
2. 保留
3. 使用 `rowProps`
4. 使用 `checked-row-keys`

**Comment by equt** [comment]
相关 https://github.com/tusen-ai/naive-ui/issues/1357，通过设置单元格的样式来实现边框

@07akioni 需不需要关掉这个？

**Comment by 07akioni** [comment]
> 相关 [https://github.com/tusen-ai/naive-ui/issues/1357，通过设置单元格的样式来实现边框](https://github.com/tusen-ai/naive-ui/issues/1357%EF%BC%8C%E9%80%9A%E8%BF%87%E8%AE%BE%E7%BD%AE%E5%8D%95%E5%85%83%E6%A0%BC%E7%9A%84%E6%A0%B7%E5%BC%8F%E6%9D%A5%E5%AE%9E%E7%8E%B0%E8%BE%B9%E6%A1%86)
> 
> @07akioni 需不需要关掉这个？

感觉可以，本质上一个问题
