### ISSUE TITLE
希望上传组件能够支持裁剪图片

### ISSUE THREAD

**Issue by Kriac** [tusen-ai/naive-ui#6510]
### Clear and concise description of the problem

如果 Upload 组件能够支持上传前进行裁剪图片就太好了

### Suggested solution

比如可以通过一个 【 before-crop 】 字段就能决定是否开启 ?

### Alternative

github上也有类似的开源仓库，但是我还是认为官方去适配会会让组件的一致性更好！

1. [vue-img-cutter](https://github.com/acccccccb/vue-img-cutter)
2. [vue-cropper](https://github.com/xyxiao001/vue-cropper)

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jahnli** [comment]
As far as I know, there is no such plan for the time being. This does not belong to the scope of the basic component library. It is better to package it yourself.
