### ISSUE TITLE
NCode设置显示行号后依然不显示行号

### ISSUE THREAD

**Issue by zhouyusd** [tusen-ai/naive-ui#6514]
### 描述错误

NCode设置显示行号后依然不显示行号
<img width="686" alt="image" src="https://github.com/user-attachments/assets/fe57e99a-7db8-4b2c-8ff4-ea66494020a9">

### 复现步骤

文档中的显示行号例子，也不现实
<img width="1073" alt="image" src="https://github.com/user-attachments/assets/88d3f204-1a97-4af1-9c78-3b767192f2e4">

### 最小复现链接

https://codesandbox.io/p/sandbox/hfmg2j

### 系统信息

```Shell
System:
  OS: macOS 14.6.1
  CPU: (20) x64 12th Gen Intel(R) Core(TM) i9-12900H
  Memory: 28.82 GB / 64.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 20.17.0 - ~/.nvm/versions/node/v20.17.0/bin/node
  npm: 10.8.2 - ~/.nvm/versions/node/v20.17.0/bin/npm
  pnpm: 9.12.3 - ~/.nvm/versions/node/v20.17.0/bin/pnpm
Browsers:
  Chrome: 130.0.6723.92
  Safari: 17.6
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by AdoKevin** [comment]
请注意阅读 [Code 组件文档](https://www.naiveui.com/zh-CN/os-theme/components/code#basic.vue) 预备条件部分

![image](https://github.com/user-attachments/assets/a5488e92-638c-496e-95cb-1d619309d7fd)
