### ISSUE TITLE
input输入框初始值为空时，输入值后再重置初始值input框更新异常

### ISSUE THREAD

**Issue by lyric-zemin** [tusen-ai/naive-ui#6526]
### 描述错误

input输入框初始值为空时，输入值后再重置初始值input框更新异常
[demo](https://codesandbox.io/p/sandbox/awesome-bartik-74pz8s?file=%2Fsrc%2FDemo.vue%3A14%2C13)

### 复现步骤

1. 打开demo
2. 输入框输入123
3. 点击reset按钮
4. 输入框不更新

### 最小复现链接

https://codesandbox.io/p/sandbox/awesome-bartik-74pz8s?file=%2Fsrc%2FDemo.vue%3A14%2C13

### 系统信息

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 5700G with Radeon Graphics
    Memory: 3.78 GB / 15.87 GB
  Binaries:
    Node: 20.12.0 - ~\AppData\Local\nvs\default\node.EXE
    npm: 10.5.0 - ~\AppData\Local\nvs\default\npm.CMD
    pnpm: 9.12.2 - ~\AppData\Local\nvs\default\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    naive-ui: ^2.40.1 => 2.40.1
    vue: ^3.5.12 => 3.5.12
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by johnson0903** [comment]
根據[文件](https://www.naiveui.com/zh-CN/os-theme/docs/controlled-uncontrolled)，設定為 `undefined` 會將元件模式轉為非受控，若要清空請設定為 `null`
