### ISSUE TITLE
需要upload组件的删除功能，

### ISSUE THREAD

**Issue by sangeyun** [tusen-ai/naive-ui#6527]
### 问题的清晰而简明的描述

目前组件不够灵活，max限制为1上传成功后，无法主动恢复到未上传状态，不能做重新上传。

### 建议的解决方案

新增一个可以移除已上传文件的方法

### 附加上下文

页面需求如下：
![image](https://github.com/user-attachments/assets/cb6a637a-624b-4ae4-ba1e-7b05ebefcee6)

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by jahnli** [comment]
手动清空 file-list
