### ISSUE TITLE
n-menu collapsed 问题

### ISSUE THREAD

**Issue by transtone** [tusen-ai/naive-ui#6530]
### 描述错误

在 collapsed 状态下，如果菜单项有 `children:null` 存在，会被识别成目录，而`非collapsed`状态下是正常的。

### 复现步骤

在 menuOptions 中添加 children:null 项。

### 最小复现链接

https://www.naiveui.com/zh-CN/os-theme/components/menu#API

### 系统信息

```Shell
所有
```

### 使用的包管理器

npm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by transtone** [comment]
在接口转换树型数据的时候，有些转换函数会留有 `children:[]`，或`children:null` 的数据存在，当 children 为空时，是当做菜单项处理呢，还是当成目录？

不管当成什么，压缩和展开状态的形式应该一致，对吧。

**Comment by jahnli** [comment]
设置为 undefined

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
