### ISSUE TITLE
n-popover 在  n-scrollbar 里面 定位超出屏幕无法显示全部！

### ISSUE THREAD

**Issue by Exclusive-gfj** [tusen-ai/naive-ui#6531]
### 描述错误

显示的popover会根据当前悬浮的元素定位设置偏移位置，导致在一些位置上会出现超出屏幕外面无法全部展示。

![image](https://github.com/user-attachments/assets/c12aac31-d3d1-44e6-99af-a923266192af)

![image](https://github.com/user-attachments/assets/682398a2-cbb9-40e6-a2b1-a5b09a784239)

### 复现步骤

1. 菜单3 往下的

### 最小复现链接

https://codesandbox.io/p/sandbox/distracted-moon-6d7pkr?workspaceId=6790dc2c-e08e-49a1-b5e5-6757fc665fac

### 系统信息

```Shell
naive-ui,vue
```

### 使用的包管理器

npm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jahnli** [comment]
https://github.com/tusen-ai/naive-ui/issues/6577  duplicate

**Comment by Exclusive-gfj** [comment]
> #6577 duplicate
通过设置 max width and max height 只能保证Popover的内容在可视的区域内不操作，但是这个问题是 Popover 的偏移位置超出了屏幕了。除非把 Popover 调的很小，但是如果的宽高设置的过大就会出现，所以并不能只通过设置 最大高宽，能不在设置偏移位置的时候处理？
