### ISSUE TITLE
Datatable点击展开，所有的都展开了

### ISSUE THREAD

**Issue by boat2oasis** [tusen-ai/naive-ui#6532]
### Describe the bug

![image](https://github.com/user-attachments/assets/5d6839ae-c9c9-4425-bd48-87bedf58a13b)
Datatable，点击展开的时候都展开了，最终定位到 let data = ref<RowData[]>([]); 这样定义的列表data会导致全部展开，

### Steps to reproduce

![image](https://github.com/user-attachments/assets/5d6839ae-c9c9-4425-bd48-87bedf58a13b)
Datatable，点击展开的时候都展开了，最终定位到 let data = ref<RowData[]>([]); 这样定义的列表data会导致全部展开，

### Link to minimal reproduction

Datatable，点击展开的时候都展开了，最终定位到 let data = ref<RowData[]>([]); 这样定义的列表data会导致全部展开，

### System Info

```Shell
![image](https://github.com/user-attachments/assets/5d6839ae-c9c9-4425-bd48-87bedf58a13b)
Datatable，点击展开的时候都展开了，最终定位到 let data = ref<RowData[]>([]); 这样定义的列表data会导致全部展开，
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
Provide a based on [CodeSandbox](https://codesandbox.io/templates/vue-vite) or [stackblitz](https://stackblitz.com/edit/vitejs-vite) `s [Minimal  Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) 

Use a unique key
