### ISSUE TITLE
DataTable组件，当data为树形数据且异步获取时，设置defaultExpandAll为true无效

### ISSUE THREAD

**Issue by liusk123** [tusen-ai/naive-ui#6535]
### Describe the bug

DataTable组件，当data为树形数据且异步获取时，设置defaultExpandAll为true无效

### Steps to reproduce

可复现链接：https://codesandbox.io/p/sandbox/agitated-engelbart-gn7pqn

### Link to minimal reproduction

https://codesandbox.io/p/sandbox/agitated-engelbart-gn7pqn

### System Info

```Shell
Win10，Chrome130.0.6723.117
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Zheng-Changfu** [comment]
defaultXXX 属性只在组件初始化时生效
1. 你可以转为受控
2.数据刷新后刷新组件（动态 key）#不推荐
