### ISSUE TITLE
popover 性能

### ISSUE THREAD

**Issue by webceoboy** [tusen-ai/naive-ui#6543]
### 描述错误

popover如果显示一个grid或者list，如果节点几百了就卡了

### 复现步骤

```
<n-popover>
 <template #trigger><n-button>click</n-button></template>
<n-grid><n-grid-item v-for="(item,index) in list" key="index"></n-grid-item></n-grid>
</n-popover>
```

### 最小复现链接

--

### 系统信息

```Shell
System:
    OS: macOS 15.0
    CPU: (8) arm64 Apple M1
    Memory: 80.70 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.2 - ~/.nvm/versions/node/v18.20.2/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 10.8.2 - ~/.nvm/versions/node/v18.20.2/bin/npm
  Browsers:
    Chrome: 131.0.6778.70
    Edge: 128.0.2739.79
    Safari: 18.0
  npmPackages:
    naive-ui: ^2.40.1 => 2.40.1 
    vue: ^3.4.21 => 3.5.12
```

### 使用的包管理器

npm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by webceoboy** [comment]
:flip="false" 好像可以显示

**Comment by jahnli** [comment]
Provide a based on [CodeSandbox](https://codesandbox.io/templates/vue-vite) or [stackblitz](https://stackblitz.com/edit/vitejs-vite) `s [Minimal  Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
