### ISSUE TITLE
国内无法访问主站

### ISSUE THREAD

**Issue by c445352742** [tusen-ai/naive-ui#6544]
### 描述错误
![微信图片_20241116211721](https://github.com/user-attachments/assets/53f97191-e36d-49fc-aba8-c0b257aa48a4)
要不要挂个备份网站，或者在github发布离线electron / tauri 文档？

### 复现步骤

国内vpn访问

### 最小复现链接

https://www.naiveui.com/

### 系统信息

```Shell
chrome
```

### 使用的包管理器

npm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by jahnli** [comment]
You can run locally.
