### ISSUE TITLE
希望表单可以支持在没有错误信息时隐藏feedback的div

### ISSUE THREAD

**Issue by nijinekoyo** [tusen-ai/naive-ui#6545]
### 问题的清晰而简明的描述

希望表单可以支持在没有错误信息时隐藏feedback的div，因为feedback的div会占用一定的高度，没办法自由的排版表单，关闭feedback的话又会导致错误信息无法展示，所以希望可以有一个没有错误时隐藏feedback的div的功能

![image](https://github.com/user-attachments/assets/897a8816-e760-484e-94ac-7324d723ad2c)

### 建议的解决方案

抱歉，我无法提供解决方案

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by Zheng-Changfu** [comment]
你暂时可以通过样式覆盖掉 min-height
