### ISSUE TITLE
Make it so that infiniteScroll loads data when the height of '.n-scrollbar-container' becomes greater than the height of '.n-scrollbar-content'.

### ISSUE THREAD

**Issue by DenniLa2** [tusen-ai/naive-ui#6547]
### Clear and concise description of the problem

Data do not load if the height of '.n-scrollbar-container' becomes greater than the height of '.n-scrollbar-content'.

### Suggested solution

Check the height of these divs. If the height of '.n-scrollbar-container' becomes greater than the height of '.n-scrollbar-content', emit the '@load' event.

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by jahnli** [comment]
Provide a based on [CodeSandbox](https://codesandbox.io/templates/vue-vite) or [stackblitz](https://stackblitz.com/edit/vitejs-vite) `s [Minimal  Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
