### ISSUE TITLE
Date range event

### ISSUE THREAD

**Issue by klyuk88** [tusen-ai/naive-ui#6555]
### Describe the bug

On blur event I get event.target.value of only one input in daterange. It is not possible to implement custom logic on two inputs.
I want to capture custom values in date-math format, for example now-1d and parse them back to date. But it doesn't work for daterange. 

### Steps to reproduce

Listen to blur event in daterange picker, output event.target.value on blur event

### Link to minimal reproduction

-

### System Info

```Shell
Vue 3, MAC OS
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
I don't understand the specific needs.

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
