### ISSUE TITLE
在企业微信使用，DataTable只要有滚动条的情况，表头列和数据列就会发生错位

### ISSUE THREAD

**Issue by longlogn** [tusen-ai/naive-ui#6557]
### Describe the bug

在企业微信使用，DataTable只要有滚动条的情况，表头列和数据列就会发生错位
![企业微信截图_20241123152200](https://github.com/user-attachments/assets/e8358c69-0b27-4b1c-bf8c-fc6506a057d3)

### Steps to reproduce

1、使用企业微信打开任意Naive UI写的页面，打开有Data Table的页面
2、Data Table需要设置 flex-height
3、会看到表头出现滚动条和滚动条的占位空间

### Link to minimal reproduction

https://www.naiveui.com/zh-CN/os-theme/components/data-table

### System Info

```Shell
pnpm: 9.12.3 - E:\software\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (129.0.2792.65)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    naive-ui: 2.40.1 => 2.40.1
    vue: 3.5.12 => 3.5.12
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by 07akioni** [comment]
我感觉是企业微信的浏览器版本较低导致的？一些 css 没生效可能

**Comment by 07akioni** [comment]
我尝试修复一下，不一定管用，没管用的话再 open 吧
