### ISSUE TITLE
CSS 按钮权重问题并没有得到解决

### ISSUE THREAD

**Issue by TaroXin** [tusen-ai/naive-ui#6562]
### Describe the bug

类似于 #1808 的问题，只不过使用的是 @unocss/reset/tailwind.css，实际还是 tailwind，出现Button按钮背景颜色被覆盖的问题

### Steps to reproduce

1. main.ts 中引入 import `@unocss/reset/tailwind.css`，自行引入 tailwind reset 一样
2. 使用 n-button
```vue
 <n-button type="primary">
      Save
 </n-button>
```
3. 效果如下截图
![image](https://github.com/user-attachments/assets/eb4e9b2f-8ec9-4ea3-ae12-65dc1fb53374)
4. 被覆盖的CSS截图
![image](https://github.com/user-attachments/assets/86ebf0a8-dce4-4811-9756-c58811c0eb4e)

### Link to minimal reproduction

https://codesandbox.io/p/devbox/ytnff5

### System Info

```Shell
System:
    OS: macOS 14.5
    CPU: (8) x64 Apple M1 Pro
    Memory: 15.39 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v18.17.1/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.15.6 - ~/.nvm/versions/node/v18.17.1/bin/pnpm
    bun: 1.0.25 - ~/.bun/bin/bun
  Browsers:
    Chrome: 131.0.6778.86
    Safari: 17.5
  npmPackages:
    naive-ui: ^2.40.1 => 2.40.1 
    vue: ^3.5.12 => 3.5.12
```

### Used Package Manager

pnpm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
Codesandbox cannot be opened

**Comment by TaroXin** [comment]
@jahnli Codesandbox NEED VPN if you in china

**Comment by jahnli** [comment]
> @jahnli If you are in China, Codesandbox needs VPN

has opened

**Comment by a81n9** [comment]
@TaroXin  改入如下写法试试

```
import '@unocss/reset/tailwind-compat.css'
```

[Unocss style-reset](https://unocss.dev/guide/style-reset#tailwind-compat)

>This reset is based on [Tailwind reset](https://unocss.dev/guide/style-reset#tailwind), minus the background color override for buttons to avoid conflicts with UI frameworks. See [linked issue](https://github.com/unocss/unocss/issues/2127).

**Comment by TaroXin** [comment]
@a81n9 确实可以了，多谢！
