### ISSUE TITLE
Named export 'VBinder' not found. The requested module 'vueuc' is a CommonJS module, which may not support all module.exports as named exports. CommonJS modules can always be imported via the default export, for example using: import pkg from 'vueuc'; const { VResizeObserver, VirtualList, VFollower, VBinder, VTarget, VOverflow, VFocusTrap } = pkg;

### ISSUE THREAD

**Issue by JbDumaine** [tusen-ai/naive-ui#6564]
Named export 'VBinder' not found. The requested module 'vueuc' is a CommonJS module, which may not support all module.exports as named exports. CommonJS modules can always be imported via the default export, for example using: import pkg from 'vueuc'; const { VResizeObserver, VirtualList, VFollower, VBinder, VTarget, VOverflow, VFocusTrap } = pkg; 
I get this error when building my app for production when reloading pages in browser. How I can resolve it ?
thanks a lot

_Originally posted by @JbDumaine in https://github.com/tusen-ai/naive-ui/discussions/6563_

**Comment by jahnli** [comment]
Provide a based on [CodeSandbox](https://codesandbox.io/templates/vue-vite) or [stackblitz](https://stackblitz.com/edit/vitejs-vite) `s [Minimal  Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by Ricciflows** [comment]
I was finally able to solve this error by adding the following to `nuxt.config.ts`
```js
build: {
    transpile: ["vueuc"],
  },
```

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem

**Comment by hacxy** [comment]
I encountered the same problem on vitepress today, the following configuration can solve it: 
```ts
{
  vite: {
    ssr: {
      noExternal: ['naive-ui', 'vueuc'],
    },
  }
}
```

**Comment by razorness** [comment]
This fix results into deactivated tree-shaking in Nuxt v4. My frontend gets bloated by >3.000 requests and 55 MB in total. Just to load the frontpage in dev mode.

**Comment by liubin595338764** [comment]
> This fix results into deactivated tree-shaking in Nuxt v4. My frontend gets bloated by >3.000 requests and 55 MB in total. Just to load the frontpage in dev mode.

me too!!!

**Comment by razorness** [comment]
@liubin595338764 my fix was to use following settings in `nuxt.config.ts`:

```ts
  vite: {
		optimizeDeps: {
			include: [ 'naive-ui', 'vueuc' ]
		},

		resolve: {
			alias: {
				// force es import of vuec
				'vueuc': fileURLToPath(new URL('node_modules/vueuc/es/index.js', import.meta.url))
			}
		},

		ssr: {
			noExternal: [ 'vueuc', 'naive-ui' ]
		},

  }
```
