### ISSUE TITLE
n-tag 关闭时无法获取标签内容

### ISSUE THREAD

**Issue by konglingbase** [tusen-ai/naive-ui#6571]
### Describe the bug

n-tag 关闭时无法获取标签内容

### Steps to reproduce

n-tag 关闭时无法获取标签内容

### Link to minimal reproduction

n-tag 关闭时无法获取标签内容

### System Info

```Shell
n-tag 关闭时无法获取标签内容
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
Provide a based on [CodeSandbox](https://codesandbox.io/templates/vue-vite) or [stackblitz](https://stackblitz.com/edit/vitejs-vite) `s [Minimal  Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
