### ISSUE TITLE
颜色选择器 Color Picker 出入错误颜色值时直接消失。

### ISSUE THREAD

**Issue by fgq1021** [tusen-ai/naive-ui#6572]
### 问题的清晰而简明的描述

当输入值符合颜色值开头格式，但又不完全符合颜色值格式，选择器报错并直接消失。
例如：rgba(1,1,1)、#呀哈哈、rgb(123123)
但是若输入值完全不符合颜色值开头格式，选择器会显示透明。
例如：呀哈哈

### 建议的解决方案

这里显然是做过错误处理的，希望出错时可以按透明或最近一次的颜色处理。

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by jahnli** [comment]
Provide a based on [CodeSandbox](https://codesandbox.io/templates/vue-vite) or [stackblitz](https://stackblitz.com/edit/vitejs-vite) `s [Minimal  Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
