### ISSUE TITLE
官网上传Upload组件点击不出现文件上传弹框

### ISSUE THREAD

**Issue by lilyandwang** [tusen-ai/naive-ui#6573]
### Describe the bug

点击官网upload组件，没有任何反应，不会出现文件上传弹框，11月27日上午还正常，下午就异常了

### Steps to reproduce

直接打开官网（https://www.naiveui.com/zh-CN/light/components/upload），随意点击演示中的上传文件按钮皆可复现

### Link to minimal reproduction

https://www.naiveui.com/zh-CN/light/components/upload

### System Info

```Shell
官网问题
```

### Used Package Manager

npm

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
Provide a based on [CodeSandbox](https://codesandbox.io/templates/vue-vite) or [stackblitz](https://stackblitz.com/edit/vitejs-vite) `s [Minimal  Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) 

No recurrence, open again if there is a problem,
