### ISSUE TITLE
Popover 溢出可视区域的优化建议

### ISSUE THREAD

**Issue by cyycm** [tusen-ai/naive-ui#6577]
### 问题的清晰而简明的描述

与优化项 #6531 和 #6103 一致

如下图，只要 Popover 内容撑满直到最大宽度，必定无法显示全部内容，这直接导致我无法使用该组件

![企业微信截图_17327859253106](https://github.com/user-attachments/assets/d0817475-62d4-4125-b80e-5ecffb99062e)

### 建议的解决方案

建议增加参数，能控制弹出的内容不会溢出到可视空间外

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by jahnli** [comment]
By setting the max width and max height can be solved
