### ISSUE TITLE
表格row-props 定义的onDblclick和onClick事件如何区分开？ 

### ISSUE THREAD

**Issue by dengsong666** [tusen-ai/naive-ui#6584]
### 描述错误

双击事件会触发onClick两次

### 复现步骤

无

### 最小复现链接

无

### 系统信息

```Shell
System:
    OS: Windows 11 10.0.26100
    CPU: (12) x64 12th Gen Intel(R) Core(TM) i5-12400
    Memory: 11.34 GB / 31.75 GB
  Binaries:
    Node: 18.17.0 - D:\Env\Node\nodejs\node.EXE
    npm: 9.6.7 - D:\Env\Node\nodejs\npm.CMD
    pnpm: 9.2.0 - D:\Env\Node\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.26100.1882
  npmPackages:
    naive-ui: ^2.40.1 => 2.40.1
    vue: latest => 3.5.12
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by Zheng-Changfu** [comment]
这是原生事件的行为，你需要自己去处理它
