### ISSUE TITLE
数据表格 Data Table 添加数据可上下拖动的功能

### ISSUE THREAD

**Issue by DotWho** [tusen-ai/naive-ui#6588]
### 问题的清晰而简明的描述

数据表格 Data Table 添加数据可上下拖动的功能

### 建议的解决方案

无

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by Zheng-Changfu** [comment]
行拖拽你可以使用 sortablejs 自行实现
