### ISSUE TITLE
关于Data Table columns 插槽的提议

### ISSUE THREAD

**Issue by guo0588** [tusen-ai/naive-ui#6601]
### 问题的清晰而简明的描述

我现在要使用表格，但是我有个痛点，我是columns数据是单独定义在一个ts文件中，我的DateTable组件是在一个单独文件（index.vue）中，我现在的问题是在一行中，有某个单元格需要触发事件（点击），从而刷新整个表格，如果columns数据和DateTable 是在一个文件中，很好处理，但是如果分开两个文件就不好处理了……，希望可以针对单元格添加一个slotName ，可以自定义。

### 建议的解决方案

 { title: "姓名", key: "name", align: "center" ,slotName:"我是插槽"},

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md)。
- [X] 阅读 [文档](https://www.naiveui.com/en-US)。
- [X] 检查是否已经存在请求相同功能的问题，以避免创建重复的问题。

**Comment by jahnli** [comment]
At present, there is no plan. What can be achieved through slot and render can basically be achieved.
