### ISSUE TITLE
表格滚动条在360浏览器不显示

### ISSUE THREAD

**Issue by ZQdefier** [tusen-ai/naive-ui#6602]
### 描述错误

360v13版本浏览器 不支持CSS inset属性  滚动条不显示

### 复现步骤

360v13版本浏览器 不支持CSS inset属性  滚动条不显示

### 最小复现链接

360v13版本浏览器 不支持CSS inset属性  滚动条不显示

### 系统信息

```Shell
360浏览器
```

### 使用的包管理器

npm

### 验证

- [x] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by Zheng-Changfu** [comment]
临时的解决办法是自己先用 postcss 处理一下 inset 的问题
