### ISSUE TITLE
当使用 NDrawer 组件设置容器在 app 根元素内时， 会导致 Pagination 的 show-quick-jump-dropdown 被遮挡

### ISSUE THREAD

**Issue by XiaoDaiGua-Ray** [tusen-ai/naive-ui#6628]
### 描述错误

当我把 `NDrawer` 设置在 根元素（`app`）内时，然后在里面设置了一个位置刚好不触发 `show-quick-jump-dropdown` 判定位置在下方出现的时候，会导致出现位置判定错误，或者说是层级关系错误，然后显示不完整。并且会导致 `NDrawer` 的高度被顶起。

<img width="703" alt="image" src="https://github.com/user-attachments/assets/b4de7ba2-6c63-4d28-90cb-24562d7f1280" />
<img width="715" alt="image" src="https://github.com/user-attachments/assets/548753b6-1f06-48c5-ace4-25183cd96350" />

### 复现步骤

1. 设置元素在 `app` 根元素出现
2. 设置元素刚好在底部出现

### 最小复现链接

暂无

### 系统信息

```Shell
- vue: 3.5.13
- vite: 5.4.3
- naive-ui: 2.40.3
```

### 使用的包管理器

pnpm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by Zheng-Changfu** [comment]
麻烦提供一下复现的链接

**Comment by jahnli** [comment]
Provide a based on [CodeSandbox](https://codesandbox.io/templates/vue-vite) or [stackblitz](https://stackblitz.com/edit/vitejs-vite) `s [Minimal  Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
