### ISSUE TITLE
Menu组件设置responsive自适应收起菜单项缺失问题

### ISSUE THREAD

**Issue by isatis-summer** [tusen-ai/naive-ui#6632]
### Describe the bug

设置mode为horizontal，responsive为true，自适应收起菜单项不缺失。但是当有部分菜单项是设置show为:false不可见时。收起里的菜单项会错乱。

### Steps to reproduce

目前版本：2.40.3

### Link to minimal reproduction

/

### System Info

```Shell
/
```

### Used Package Manager

yarn

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
Provide a based on [CodeSandbox](https://codesandbox.io/templates/vue-vite) or [stackblitz](https://stackblitz.com/edit/vitejs-vite) `s [Minimal  Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
