### ISSUE TITLE
naiveui vue3  echarts

### ISSUE THREAD

**Issue by enryteam** [tusen-ai/naive-ui#6643]
### 描述错误

import * as echarts from 'echarts';

console.log(echarts); 
返回undefined 加载echarts undefined

### 复现步骤

<template>
  <n-card title="柱状图示例" class="chart-card">
    <div ref="chartRef" class="chart"></div>
  </n-card>
</template>

<script setup>
import { onMounted, onUnmounted, ref } from 'vue';
import * as echarts from 'echarts';
import { NCard } from 'naive-ui';

const chartRef = ref(null);
let chartInstance = null;

const initChart = () => {
  if (chartRef.value) {
    chartInstance = echarts.init(chartRef.value);
    const option = {
      title: {
        text: '销售数据',
      },
      tooltip: {},
      xAxis: {
        data: ['一月', '二月', '三月', '四月', '五月', '六月'],
      },
      yAxis: {},
      series: [
        {
          name: '销量',
          type: 'bar',
          data: [5, 20, 36, 10, 10, 20],
        },
      ],
    };
    chartInstance.setOption(option);
  }
};

const resizeHandler = () => {
  if (chartInstance) {
    chartInstance.resize();
  }
};

onMounted(() => {
  console.log("加载echarts",echarts)
  initChart();
  window.addEventListener('resize', resizeHandler);
});

onUnmounted(() => {
  window.removeEventListener('resize', resizeHandler);
  if (chartInstance) {
    chartInstance.dispose();
  }
});
</script>

<style scoped>
.chart-card {
  height: 400px;
}

.chart {
  height: 100%;
}
</style>

### 最小复现链接

test

### 系统信息

```Shell
chrome win10 64位
```

### 使用的包管理器

npm

### 验证

- [X] 阅读 [贡献指南](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.zh-CN.md)。
- [X] 阅读 [文档](https://www.naiveui.com/zh-CN/)。
- [X] 检查是否已经存在[相同问题的问题](https://github.com/tusen-ai/naive-ui/issues)，以避免创建重复的问题。
- [X] 确保这是一个具体的 bug。有关问题和答案，请打开 [GitHub 讨论](https://github.com/tusen-ai/naive-ui/discussions)。
- [X] 提供的复现是[最小可复现的示例](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by Zheng-Changfu** [comment]
请提供一下最小复现示例，看你说的是 echarts，这和 naive 有什么关系么

**Comment by jahnli** [comment]
It doesn't seem to have anything to do with naivety.
