### ISSUE TITLE
n-data-table 中rowProps 的className失效

### ISSUE THREAD

**Issue by isCatSeven** [tusen-ai/naive-ui#6645]
### Describe the bug

在最新的2.40.4版本中出现修改className后无法生效

### Steps to reproduce

重新修改className无法更新到dom中

### Link to minimal reproduction

https://github.com/tusen-ai/naive-ui/tree/v2.40.4

### System Info

```Shell
macos15.2, chrome 131.0.6778.205（正式版本） (arm64)
```

### Used Package Manager

yarn

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/tusen-ai/naive-ui/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.naiveui.com/en-US/).
- [X] Check that there isn't [already an issue](https://github.com/tusen-ai/naive-ui/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/tusen-ai/naive-ui/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jahnli** [comment]
Provide a based on [CodeSandbox](https://codesandbox.io/templates/vue-vite) or [stackblitz](https://stackblitz.com/edit/vitejs-vite) `s [Minimal  Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
