### ISSUE TITLE
模态框和对话框动画效果问题

### ISSUE THREAD

**Issue by ywwsw** [tusen-ai/naive-ui#860]
### TuSimple/naive-ui version (版本)
2.16.2

### Vue version (Vue 版本)
3.2.2

### Browser and its version (浏览器及其版本)
89

### System and its version (系统及其版本)
window10

### Node version (Node 版本)
14.4

### Reappearance link (重现链接)
https://github.com/ywwsw/test-electron-naiveui.git

### Reappearance steps (重现步骤)

git repo

npm install

npm run dev

打开窗口后，可以按ctrl + shift +i  打开浏览器开发者工具

问题描述：在使用electron的时候，窗口最大化或加大尺寸后，模态框和对话框的动画效果就会变得缓慢，不改变尺寸的情况下，重复点击几十次后偶尔也会出现动画变得缓慢。

### Expected results (期望的结果)
是否可以增加选项是否启用动画效果？

### Actual results (实际的结果)
窗口尺寸改变后 模态框和对话框的动画效果就会变得缓慢

**Comment by mollerzhu** [comment]
我也遇到了同样的问题，css动画执行很慢

**Comment by 07akioni** [comment]
> 我也遇到了同样的问题，css动画执行很慢

复现 repo 已经没得了，除了执行慢还有什么额外的信息吗？我不太确定原因是啥

**Comment by jahnli** [comment]
This issue does not have any recent activity. If you are still experiencing similar problems, open a new error, including a minimal copy of the problem
